### ISSUE TITLE
Need Help: How to package my JavaScript library code with webpack as extensible as jQuery?

### ISSUE THREAD

**Issue by kingller** [webpack/webpack#10041]
How to package my JavaScript library code with webpack as extensible as jQuery?

For example,  
Sometimes, I only need `jquery`,
So, I use it as bellow,
```
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
```
But, sometimes, I need some extra features (such as Draggable), so I add `jquery-ui` to my page,
```
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
```

Now, I use `output.library` to package my code as JavaScript library, but I want to package my javascript library code into multiple files and then reference them as needed as above. Because my library is too large.

Can you help me please?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
