### ISSUE TITLE
Asset module gets different hash

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#10119]
# Bug report

**What is the current behavior?**

using different configurations:
```js
rules: [
			{
				test: /\.css$/,
				loader: 'css-loader'
			},
			{
				test: /\.ttf$/,
				type: "asset"
			}
		]
```

```js
rules: [
			{
				test: /\.css$/,
				loader: 'css-loader'
			},
			{
				test: /\.ttf$/,
				oneOf: [
					{
						issuer: /\.js$/,
						loader: 'glyph-size-loader'
					},
					{
   type: "asset"
}
]
			}
		]
```

creates different hash for same asset

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/vankop/webpack-asset-module

**What is the expected behavior?**

same hash for each asset

**Other relevant information:**
webpack version:  5.0.0-beta.9
Node.js version: 10.17
Operating System: OSX

**Comment by evilebottnawi** [comment]
Thanks for issue, investigate

**Comment by smelukov** [comment]
in progress

**Comment by vankop** [comment]
Actually I get other problem as well (can not substitute problem to small repo for now):
with `oneof` configuration getting 2 assets in dev mode but only one really used, in production mode 1 asset

**Comment by smelukov** [comment]
Got it!
Its not about asset modules, but about generating module hash
Module hash generates from different fact (includes module identifier)
A module identifier is getting from the chunk graph
The problem solves by adding
```
optimization: {
    moduleIds: 'deterministic'
},
```

It makes all modules id deterministic independent from its position in a chunk graph
@sokra is it expected behavior?

**Comment by sokra** [comment]
Two problems here:

* `[hash]` in assetModuleFilename and webassemblyModuleFilename should probably use content hash instead of module hash
* There is a hash conflict when using the `issuer` matcher, because both modules try to claim the same module id (by moduleIds: "deterministic"). Conflict is resolved, but this give one of the modules a different id that it used to receive. Best if we can avoid conflict in first place. Maybe we should use full name when module is matched by `issuer`. Not sure if this helps a lot...

**Comment by smelukov** [comment]
@sokra I want to fix it by changing default value of `output.assetModuleFilename` to `[contenthash][ext]` and something like this:

__`lib/asset/AssetModulesPlugin.js`__
```diff
+ const contentHash = createHash(outputOptions.hashFunction);
+ 
+ codeGenerationResults
+ 	.get(module)
+	.sources.get(type)
+	.updateHash(contentHash);

result.push({
	render: () =>
		codeGenerationResults.get(module).sources.get(type),
	filenameTemplate,
	pathOptions: {
		module,
		filename,
		chunkGraph,
+		contentHash
	},
	auxiliary: true,
	identifier: `assetModule${chunkGraph.getModuleId(module)}`,
	hash: chunkGraph.getModuleHash(module)
});
```

plus some changes in `lib/TemplatedPathPlugin.js` to respect `contentHash` in `PathData` event if no `chunk` passed.

What do you think about that?

**Comment by evilebottnawi** [comment]
bump

**Comment by chenxsan** [comment]
Hope this can be fixed soon, it makes the asset module a bad option to replace url-loader/file-loader since updating anything in your project now would change the  output assets' filename.
