### ISSUE TITLE
Option to update manifest 'js' path

### ISSUE THREAD

**Issue by shashidhark** [webpack/webpack#10126]
I have webpack configured and it was working fine until I applied lazy load. Path to js folder is public/js where all my js files stored. It was working fine for vendor files as I am specifying direct path in the index.html. This fails in the case of lazy loading, because manifest file uses dynamic path which by default takes public/files.js.

Following are the temporary solutions
1) Move all lazy loading files to public/ (need to change the folder structure.)

2) Edit the manifest.js as follows

    ... e){return i.p+""+({}[e]||e)+".js"}( ...

    to

    ... e){return "js/"+i.p+""+({}[e]||e)+".js"}( ...

    (need to edit manifest after build)

Is there any option to handle this from webpack?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
