### ISSUE TITLE
build umd package error

### ISSUE THREAD

**Issue by loqhcn** [webpack/webpack#10131]
# Bug report

in build umd package ,  docs is 
```
typeof self !== 'undefined' ? self : this 

```

but build file content is 
```
window
```
eferenceError: window is not defined

**Comment by sokra** [comment]
You can configure this with `output.globalObject`, default depends on `target`.

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
