### ISSUE TITLE
undefined export when compiling vendors with DllPlugin mode production

### ISSUE THREAD

**Issue by wfortin** [webpack/webpack#10189]
# Bug report

**What is the current behavior?**
Compiling a simple React App using DLLPlugin with the `@reach/dialog` package included fails to initialize. Project compiles fine, but crashes at runtime with error:
```
TypeError: undefined is not an object (evaluating 'e[r].call')
```
Project runs fine when building in non production mode. (`--mode development`)
Project runs fine when excluding `@reach/dialog` from the Dll bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a minimal project to replicate the issue https://glitch.com/edit/#!/reach-webpack-bug

**What is the expected behavior?**
Same behaviour as in ` --mode development`.
App boots fine with no error when bootstrapping the application.

**Other relevant information:**
webpack version:  webpack 4.41.5, webpack-cli 3.3.10
Node.js version: 10.16.3
Operating System: MacOS
Additional tools: include the `@reach/dialog` package in the project.

**Comment by wfortin** [comment]
Adding `optimization.usedExports: false` seems to solve the issue. I'm still wondering why @reach/dialog is the only library affected by this in our project with multiple dependencies.

**Comment by sokra** [comment]
Yep, it's a bug. It's caused by the `sideEffects` optimization, when combined with `DllPlugin` with `entryOnly: false`. The `sideEffects` optimization skips some modules from the graph because they are unused. These modules are not included in the file. Later in the process the DllPlugin flags all exports from all modules as used, which causes the skipped modules to be referenced again.

You can workaround it by using the `entryOnly` option for the `DllPlugin`, which makes only the module specified in the `entry` option accessible by the app bundle. This way `usedExports` and `sideEffects` can still run on the dependency graph of these modules. This is a functional difference, but should result in smaller vendor bundles.

Or you can disable `usedExports` in the vendor build. This would be functional the same as your original code, but do not yield the bug.
