### ISSUE TITLE
Class constructor names set to parent class name

### ISSUE THREAD

**Issue by bttf** [webpack/webpack#10198]
# Bug report

We noticed one of our webpack-built scripts that uses `pg-promise` + `pg-query-stream` was failing due to a check where an instance of the class `QueryStream` was failing a check against its `constructor.name`.

**What is the current behavior?**
```
const QueryStream = require('pg-query-stream');

const qs = new QueryStream('SELECT 1');

console.log(qs.constructor.name);

// Output: 'Readable'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Example repo w/ steps to repro: https://github.com/bttf/webpack-class-name-bug

Notes:
- The check in `pg-promise` that surfaced the issue: https://github.com/vitaly-t/pg-promise/blob/bea9548567cee6bb482113714bffdec323c3b240/lib/stream.js#L29
- Downgrading to webpack@3.8.1 removes the issue

**What is the expected behavior?**
```
const QueryStream = require('pg-query-stream');

const qs = new QueryStream('SELECT 1');

console.log(qs.constructor.name);

// Output: 'PgQueryStream'
```

**Other relevant information:**
webpack version: 4.41.5 / 3.8.1
Node.js version: 10.17.0
Operating System: MacOS
Additional tools:

**Comment by sokra** [comment]
webpack 4 bundles in production mode by default. This means the resulting file will be minimized.
During minimizing function and class names are not kept by default. This is the expected behavior, that why it's strongly recommended to not rely on function or class names!

I would recommend to open an issue on `pg` to advise them not not rely on function or class names.

As workaround you could disable name mangling or minimizing at all.

* mangling during minimizing
  * Disable minimizing: `optimization.minimize: false`
  * Disable name mangling in terser: https://stackoverflow.com/questions/56540461/how-to-configure-terserplugin-to-not-mangle-classnames
* renaming during module concatenation (only for ESM)
  * Disable it: `optimiziation.concatenateModules: false`
