### ISSUE TITLE
use dynamic import in npm library use webpack

### ISSUE THREAD

**Issue by ourfor** [webpack/webpack#10228]
# Bug report

https://stackoverflow.com/questions/56029866/how-to-load-dynamic-import-chunks-bundles-from-npm-dependency-module

https://stackoverflow.com/questions/57496375/how-do-i-use-webpack-dynamic-imports-inside-an-npm-package

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Please fill issue, no need put links on stackoverflow

**Comment by lebronjs** [comment]
> # Bug report
> https://stackoverflow.com/questions/56029866/how-to-load-dynamic-import-chunks-bundles-from-npm-dependency-module
> 
> https://stackoverflow.com/questions/57496375/how-do-i-use-webpack-dynamic-imports-inside-an-npm-package
> 
> **What is the current behavior?**
> 
> I use lazy load in the library, which I write for another project. when I package it and publish it to npmjs. I import it in another project. It can't work and show can't find the dependencies, which I dynamic loay in the library
> 
> in the library.
> 
> ```js
>     return new Promise((resolve) => {
>         import(/* webpackChunkName: "lute" */'../../js/lute/lute.min.js')
>            .then(module => {
>                if(vditor && typeof vditor === "object" && !vditor.lute) {
>                    vditor.lute = Lute.New();
>                    vditor.lute.PutEmojis(vditor.options.hint.emoji);
>                    vditor.lute.SetEmojiSite(vditor.options.hint.emojiPath);
>                    vditor.lute.SetParallelParsing(false);
>                    vditor.lute.SetInlineMathAllowDigitAfterOpenMarker(vditor.options.preview.inlineMathDigit);
>                    resolve();
>                }
>         })
>     });
> ```
> 
> **If the current behavior is a bug, please provide the steps to reproduce.**
> 
> **What is the expected behavior?**
> 
> **Other relevant information:**
> webpack version:
> `^4.39.1`
> Node.js version:
> `v12.12.0`
> Operating System:
> MacOS Mojave `10.14.5 (18F132)`
> Additional tools:

老哥你解决了吗

**Comment by Dorianslavov** [comment]
It's possible that your import has incorrect path and not getting resolved. Have you tried using `catch` in case some errors are present ?

**Comment by agupta1989** [comment]
@ourfor did you find any solution to this problem ?

Why this issue is closed ?

**Comment by muke1908** [comment]
@alexander-akait Can we please re-open the issue? 
or did anyone find any solution to this?

**Comment by alexander-akait** [comment]
What do you mean?

**Comment by muke1908** [comment]
when `publicPath` is set to auto, it'll often resolve a wrong path for the dynamic imports. 
[AutoPublicPathRuntimeModule.js](https://github.com/webpack/webpack/blob/main/lib/runtime/AutoPublicPathRuntimeModule.js) - From this it seems like it tries to find path from the last append script to dom. 

As an example it will fail in following case: 
```
<script src="./dist/module1.js" />
<script src="./external/someExternalModule" />
```

Now if I have any dynamic import in `module1.js` webpack will try to load in from `./external` instead of `dist`.

**Comment by alexander-akait** [comment]
Please provide reproducible test repo, I think you have something wrong in your configuration

**Comment by muke1908** [comment]
@alexander-akait I have created a repro repo. https://github.com/muke1908/dynamic-import-repro
Current behavior: Chunks are not part of the dist of app
Expected behavior: All chunks should be copied to app.

<img width="644" alt="Screenshot 2023-05-29 at 20 19 17" src="https://github.com/webpack/webpack/assets/20297989/8f376df3-ee34-427a-8d97-3beb33a27ade">

**Comment by alexander-akait** [comment]
@muke1908 Don't bundle libraries at all (if you really don't understand why you need it), because you will lose a lot of optimizations, if you really need to bundle it and use module federation, you can:
- create a new container and expose required code
- copy `ts_dynamic_ts.js` manually

Supporting double bunding is limited, in future when we improve ESM support, it will be less limited, but anyway, it is not recommended way

Why it happened? Because webpack can't analize generated code and undestand what it is dynamic import. Your target is not ESM, so webpack needs to generate some `fancy` code to implement dynamic import/regular import support for your target, but unfortunately because of this the code becomes unanalysable

feel free to feedback

**Comment by muke1908** [comment]
Thanks! It helps. 
We probably go ahead with manually-copying solution.

**Comment by paztis** [comment]
I have the same kind of problem, but I bundle my library because it has dependencies to private package only accessible in my company.

We bundle it to be able to deliver it outside.
And we need chunks to avoid a big loading at the beginning.

How to resolve these cases ? Is it possible to produce a library partially bundled (only our internal modules) ?
