### ISSUE TITLE
Any Webpack experts care to join Angular CLI planning hangout?

### ISSUE THREAD

**Issue by dancancro** [webpack/webpack#1023]
Hi folks,

I don't have a bug to report.  I'm just looking for an authority on Webpack.

I organize weekly Google Hangouts between some top open source thinkers, educators and Google team members in an effort to unify/improve approaches to single-page app development.  Towards the formation of an AngularJS command-line interface, this week we're considering build tool options including Webpack.

It would be great if someone who knows it well could join us.  We'll be meeting tomorrow at [7:30 pm gmt](https://www.google.de/?gfe_rd=cr&ei=3s5AVYHhOqqG8Qf0n4H4CA&gws_rd=ssl#q=current%20time%20gmt).  It usually lasts about an hour.  We'll do short overviews of each option followed by some Q & A.

If you're free then and interested in shaping the course of AngularJS app development, please write me and I'll send you the Hangout link.

Thanks,
Dan

**Comment by dancancro** [comment]
One more thing... I made a questionnaire about tools to inform [this](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=393788427) big comparison spreadsheet about alternative web technologies. In case anyone has a few spare minutes, I would really appreciate if someone could complete the questionnaire for Webpack.

Just click [here](https://docs.google.com/forms/d/1N-EHlJN2ov5m92Q46amZlKYD34Pkj-xg_zsA3cukZ6U/viewform) 

Thanks!

**Comment by sokra** [comment]
I don't think it can answer these questions with a simple YES/NO form. Some questions doesn't apply, because webpack is not a package manager and many questions only apply for one of the tools.

My subjective optinion is that webpack does a pretty good job for **optimized** bundling of javascript and stuff that compiles to js or is referenced by js (css, images, etc.). It does the best job in splitting your modules into multiple on demand loaded parts (Code Splitting). It's pretty fast for incremental builds. Highly configurable, but difficult to getting started with.

**Comment by dancancro** [comment]
That's fine.  If something doesn't apply, just ignore it.  I don't really pay much attention to tool labels - "package manager", "build tool", "module loader"  and so on because what matters is what the tool can do, not how people categorize it.

I know that putting things into black and white is not a very popular thing to do.  But at the end of the day, people have to make decisions and without booleanized characteristics (YESes and NOs to questions without adjectives of degree) comparing complex things is very very hard.  My goal is to make it easier for people to choose the best tools for their needs.

From your remarks, I've put YESes next to "Lets you break applications into discrete, lazy-loadable modules" and "Supports incremental builds" for Webpack.  I think that's what you meant.  Perhaps you could elaborate on what makes it highly configurable and difficult to get started with.

**Comment by sokra** [comment]
> Perhaps you could elaborate on what makes it highly configurable and difficult to get started with.

webpack has a rich plugin system. Most features are plugins. There are (too) many config options regarding output and resolving. Maybe you know the angular-webpack-plugin, which parses `angular.module`, threads angluar dependency as module dependencies and resolve them with a custom resolver algorithmus.

Difficult to getting started: Mainly because of missing good getting started docs and bad "wrong configuration" error handling.

**Comment by sokra** [comment]
Filled the form. Hope everything is correct... ;)
