### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by rostaryms** [webpack/webpack#10289]
Hi,

I'm following along a video tutorial and I'm trying to type 'npm run dev' into the command prompt. However I'm getting the error below. Anyone know what's going on?

![JS_Error](https://user-images.githubusercontent.com/56840832/72834398-bdf49c00-3c56-11ea-9a9f-67f4e29300dd.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

Looks like outdated webpack-cli version
