### ISSUE TITLE
Is there a way to have access to webpack.config defined constants and also bower_components and custom modules in a loader?

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#1033]
I need to use to be able to resolve my modules and webpack node_modules in the loader #3
https://github.com/at0g/nunjucks-loader/issues/3

This is necessary for my setup of nunjucks-loader because the templates need to access locale date that is downloaded async with fancy bundle loader tricks.  Also I'm having trouble accessing modules in the locale module that are not entirely within my main nodeModulesRoot.  I'm tested this by copying an app module and a bower module into nodeModulesRoot and it at least resolves it but then the constant is causing me an issue.

**Comment by IngwiePhoenix** [comment]
I dont exactly get what you are trying to do. However, to access the config, you can use `this.options` to access the entire config object.

For the other points, I have no idea what you are trying to do. I use a plugin to resolve Bower modules since the built-in mechanism is somehow not working...

**Comment by dschissler** [comment]
I am trying to use a translation library called Jed that has been fed async locale data and is wrapped in my locale module.  I use common `t`, `n` style gettext functions with it in my nunjucks templates.  Jed is stored in bower_components because that version worked for me (rather than the npm version).

So basically this new nunjucks-loader appears to work but doesn't resolve very good (at least by default).

**Comment by dschissler** [comment]
Also the loader doesn't seem to use any webpack resolving with other loaders that are defined like the yaml loader.

I'm wondering if there is another layer that needs to be wrapped around this loader so that it can figure the normal things out and include them in the output and magically work.

**Comment by sokra** [comment]
There is a `this.resolve` function in the loader context you can use.

**Comment by at0g** [comment]
Thanks for your response @sokra - `this.resolve` does not help in this case, as the path is already being resolved - the issue is dependencies within the required file being resolved using the current webpack configuration.

Hopefully this gives a better explanation of the issue:

Dependencies
A: a loader
B: a file path passed to A via query params
C: a file required by B
D: a resource to be processed by A

When D is processed by A, A must require B before D can be parsed/processed.
B is not a dependency of D, the path to B is passed as a configuration option to A.

The problem occurs when there is a `resolve` key in webpack config that is used to resolve C.
A requires B, but B fails to resolve C.
If B is required directly (outside of the loader), then C resolves as expected

#1038 has a link to a repo that reproduces the situation.

**Comment by dschissler** [comment]
@sokra Any ideas on where to start.  I created the initial port from browserify and I stopped when I had it using the runtime only in the front end code but the templates didn't understand where they were in the file system and at0g's version understand this but is unable to use helpers that have user npm dependencies.  This later requirement is vital since localization files are probably best loaded asynchronously and for custom logic that requires user modules.

It seems like we are dead in the water (at least I am) without this working.  I think that this sort of thing would take me days to a week to figure out and I just don't have the time.
