### ISSUE TITLE
Compiling unused code

### ISSUE THREAD

**Issue by johnsky95** [webpack/webpack#10394]
https://github.com/johnsky95/webpack_dead_code

I created a demo app.

`export class ClassA {

sayHello() {
    console.log('hello');
}

sayBye() {
    console.log('bye');
}
}

new ClassA().sayHello();`

function sayBye() is still compiled, is this a bug or I am configuring something wrong, no idea :/

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
