### ISSUE TITLE
Mechanism to configure output options per entry point

### ISSUE THREAD

**Issue by Lalitha-Iyer** [webpack/webpack#10410]
## Feature request

There are only a few of all the available output options that can be customized per entry point, eg  `filename: '[name].bundle.js'`, and the syntax is bespoke. 

It would be nice to have a standardized way to configure all of the output options for each entry point, when there are multiple entry points. 

**What is the expected behavior?**

We should be able to configure output options like `globalObject` for each entry point

**What is motivation or use case for adding/changing the behavior?**

Currently I have to maintain different configs and execute them with multicompiler, when the only change is one property of output options `globalObject`
I am running into timing issues as the second config, depends on the successful run of the first compiler. I can avoid such timing issues if I just had one config with different entry points, with an ability to customize output options per entry point.

**How should this be implemented in your opinion?**
Maintain output options map, with the `entryChunkName `  as the key.
This can act as output overrides that get applied, over the standard ones that are provided in the output object.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
We are working on making some output options available per entry point, e. g. `libary` and `target`, but `globalObject` is probably not one of them, since it has influence on modules (e. g. externals) and modules need to be independent of entry points.

It would be possible to have a `library.globalObject` configuration option which could be per entry point, if this would work for you.

Anyway you can create bundles that work with multiple globalObjects by making it an expression:

``` js
globalObject: "(typeof self === 'undefined' ? window : self)"
```

**Comment by Lalitha-Iyer** [comment]
yes, I can work with the expression, thanks for the suggestion

**Comment by Lalitha-Iyer** [comment]
yes, I can work with the expression, thanks for the suggestion

**Comment by Lalitha-Iyer** [comment]
@sokra is there an issue or PR that I can follow for `output options available per entry point, e. g. libary and target`

**Comment by evilebottnawi** [comment]
@Lalitha-Iyer https://github.com/webpack/webpack/projects/5#card-29122473
