### ISSUE TITLE
webpack and two different origin websites

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#10495]
I've already posted the question on stackoverflow. Hope this will better find the one who can give me some best practice hints.

https://stackoverflow.com/questions/60494036/webpack-and-two-different-origin-websites

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
