### ISSUE TITLE
Update acorn in webpack 4

### ISSUE THREAD

**Issue by dacevedoatfluid** [webpack/webpack#10516]
https://www.npmjs.com/advisories/1488

**Comment by sokra** [comment]
We can't update to the next major version without a breaking change. Is there a fixed acron 6 version?

**Comment by alan-agius4** [comment]
@sokra the fix seems to have been backported to 6.4.1 https://github.com/acornjs/acorn/issues/930

**Comment by fabb** [comment]
acorn 6.4.1 shows up as affected: https://www.npmjs.com/advisories/1488/versions
i wrote to security@npmjs.com and hope they whitelist 6.4.1 again.

**Comment by fabb** [comment]
ok, 6.4.1 is now has been whitelisted in npm: https://www.npmjs.com/advisories/1488/versions

**Comment by evilebottnawi** [comment]
Great!

**Comment by oznu** [comment]
Using `npm audit fix` now works for projects using webpack.

**Comment by mkapal** [comment]
> Using `npm audit fix` now works for projects using webpack.

How did you manage to fix it? I can see that in Webpack's `yarn.lock` file, `acorn` is still locked to version `6.4.0`, which still contains the vulnerability.

**Comment by Favna** [comment]
@mkapal bit late to the party but if you're using yarn add this to your package.json, then let yarn regenerate the lockfile.
```json
  "resolutions": {
    "acorn": "^6.4.1",
    "minimist": "^1.2.2"
  }
```

---

I'm jumping in here because I noticed @sokra closed this issue, despite the issue not being fixed at all. The latest release of Webpack (v4.42.1) still has a dependency of acorn v6.2.1, rather than v6.4.1, thus forcing us to either rely on package-lock.json (npm), which is very very unreliable since the lockfile is not meant to determine versions, that's the role of the package.json; OR thankfully the resolutions field in package.json for Yarn, which already a lot better than NPM but ideally it would not be needed.

So when are you releasing Webpack v4.42.2 with a bump of acorn to v6.4.1?

**Comment by Sukesh-Gundoji** [comment]
Hi @sokra , The is not yet fixed in 4.42.1. can you please let us know when are we getting this fixed.
This is flagging as vulnerability during audit.

**Comment by sokra** [comment]
It's not webpacks job to bump up versions of packages in your lockfile. The fixed version is within the valid range and can be installed with webpack. There are CLI commands in yarn and npm to upgrade the version in the lockfile. Alternatively you could remove the entry from the lockfile and run install or delete the complete lockfile. Anyway managing the lockfile is your job, similar to managing your package.json. (there are also tools like dependa-bot to automate that.)

Even if we would update our supported acorn version in our package.json, this would mean the same work for you as you need to upgrade webpack .

We won't publish a new version to "fix" that.

**Comment by fabb** [comment]
`npm --depth 9999 update --no-save acorn` should do the trick in client projects.

**Comment by G-Rath** [comment]
An even faster way is to use my [`npm_remove_package_from_lock`](https://github.com/G-Rath/scripts/blob/master/src/npm_remove_package_from_lock) script to remove all entities of the package from the lock (entities here refers to the "lock" of the package, rather than its constraint).

Then you can just run `npm i`, which will see the lock is missing packages, and install them; since what it's installing is not in the lock, it will grab the latest version of the package that fits with the constraints and thus always grab highest version possible.

This is a lot faster than doing `npm update --depth 9999`, because that requires calculating the entire tree to update every package, and on large projects (or, any project that has such `jest`) typically it'll just crash beacuse of the max call depth.

(btw, there is also a [`yarn_remove_package_from_lock`](https://github.com/G-Rath/scripts/blob/master/src/yarn_remove_package_from_lock)).

**Comment by fabb** [comment]
I sometimes just do `npm i acorn@5.7.4`, and then reset the `package.json` again and then run `npm i`.

**Comment by paztis** [comment]
Hi

Acorn is integration optional chaining in 7.3.0
Webpack 4.44.2 is still pointing to ^6.4.1

Isn't it possible to upgrade it officially without migratiung to webpack 5.0 beta ?
