### ISSUE TITLE
Incremental build performance after 1.5

### ISSUE THREAD

**Issue by dettier** [webpack/webpack#1051]
I noticed a significant performance degradation for all versions past 1.4. Build time is about the same, but incremental build are 3-5x times slower.
Here's the resuls for the same project (about 1000 modules in 10 chunks) using the same config:

```
Version: webpack 1.4.15
Time: 1219ms
```

```
Version: webpack 1.8.11
Time: 4851ms
```

**Comment by sokra** [comment]
Which config? devtool?

**Comment by dayletter** [comment]
+1
I thought it was my problem, since I didn't see many people brought this up.

- It happened after the NewWatchingPlugin becomes default.
- It is slow even if devtool is not set.
- Only happens on my Windows 8.1 PC; It is still very fast on Mac.

**Comment by dettier** [comment]
I confirm that this happens only under Windows, just tested it under OS X and there is no perf degradation.
My config is pretty big. but nothing special https://gist.github.com/dettier/362e738f16b9681fd5d7.
I tried different devtool settings (even disabling it) with no luck.

**Comment by larryhe** [comment]
I had the exactly the same issue on my mac pro (2.2 GHz Intel Core i7 with 16 GB RAM) but even worse, my incremental build time is close to or sometimes longer than rebuild time (around 3 minutes). Our project has a huge code base with over 900 modules and was based on requireJS. Recently we planned to migrate to webpack. everything works fine. rebuild the whole project takes about 3 minutes which is absolutely acceptable given that we have a huge code base. But the biggest problem is incremental build time is incredibly long and each time whatever file you change, you have to wait about 2 minutes for webpack to finish compile and bundle. I tried all the tips on http://webpack.github.io/docs/build-performance.html but seems not working. I thought it might be each of our chunk is too big or all the code mangled together and each file changed will cause the whole application to rebuilt.   So I wrote a really small test module with below content and split it out in entry file. But still whenever I change the test file, it took almost 3 minutes or more to build the test module, which does not make any sense at all. How come build a tiny chunk take the same time or longer than building the whole project. 
My webpack.config listed below and I also generated a profiled stats.json and uploaded it to online analysis tool to get some hints. but my stats.json is too big (90MB) and it crashed the tool.  Could anyone here especially @sokra share some ideas on how to identify the incremental build performance issue and improve it. this is very important for us because we can not migrate to webpack without cutting down the incremental build time to an acceptable range (like less than 30 seconds 2 minutes is way too longer). Thanks again for this great project. 

```
......... other content is omitted 
//entry file and split the test module out
require(['testModule'], function(TestM){
    var m = new TestM.default();
    m.show();
});
```
```
//test module content
function TestM() {
    console.log('================test module loaded--------------');
    this.show = function(){
        console.log('test module shown ---------------');
    }
}
export default TestM;
```
```
'use strict'
var webpack = require('webpack')
var path = require('path')
var excludes = require('./excludes');


module.exports = {
    'entry': {
        'common.base': ['cssua', 'jquery','backbone', 'underscore'],
        'entry1': 'entry1',
        'entry2': 'entry2',
        'entry3': 'entry3'
    },
    'output': {
        'pathinfo': true,
        'path': path.join(__dirname, 'dist'),
        'publicPath': '/resources/dist/',
        'filename': '[name].js'
    },
    cache: true,
    plugins: [
        new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),
        new webpack.ProvidePlugin({ _: 'underscore'}),
        new webpack.ProvidePlugin({ cssua: 'cssua'}),
        new webpack.optimize.CommonsChunkPlugin({name: 'common.base', minChunks: 2}),
        new webpack.SourceMapDevToolPlugin({
            filename: '[file].map',
            exclude: excludes,
            columns: false, // no columns in SourceMaps
            module: true // use SourceMaps from loaders
        })
    ],
    'resolve': {
        'root': [
            path.join(__dirname, './')
        ],
        'alias': {
            'cssua': 'lib/cssua',
            'backbone': 'lib/backbone/backbone',
            'underscore': 'lib/underscore/underscore',
            'backbone.paginator': 'lib/backbone.paginator/lib/backbone.paginator',
            'jquery': 'lib/jquery/dist/jquery',
            'snap.svg': 'lib/Snap.svg/dist/snap.svg'
        }
    },
    module: {
        'noParse': [/moment.js/, /base64.js/],
        'loaders': [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: excludes,
                query: {
                    cacheDirectory: true,
                    presets: 'es2015',
                    compact: false
                }
            },
            {
                'test': /\.hbs$/,
                'loader': 'handlebars-loader',
                'query': {
                    runtime: 'handlebars/runtime',
                    helperDirs: [
                        __dirname + "/templates/helpers"
                    ],
                    partialDirs: [
                        __dirname
                    ]
                }
            },
            {
                'test': /base64/,
                'loader': 'imports?this=>window'
            },
            {
                'test': /snap.svg/,
                'loader': 'imports?this=>window,fix=>module.exports=0'
            }
        ]
    }
}
```

**Comment by sokra** [comment]
@larryhe Have you tried without the `SourceMapDevToolPlugin`?

**Comment by larryhe** [comment]
Hi @sokra Thanks for your quick response. I will git it try and update it later. But we do need to generate source map to debug ES6 code because we do not want to debug transformed code. Thanks again for this great project.

**Comment by larryhe** [comment]
Hi @sokra , I just tried to comment out SourceMapDevToolPlugin but still did not see any difference. Incremental building that tiny test modules takes almost the same amount of time as rebuild the whole application. Any ideas that I can identify the performance issue.

**Comment by TheLarkInn** [comment]
I'm going to close this as we have made significant updates to build performance circa webpack 3. Please feel free and submit a new bug if there are still problems. Preferrably with a chrome devtools trace using the --inspect flags.
