### ISSUE TITLE
Common plugins/loaders causing ModuleConcatenationPlugin bailouts, are there plans to fix?

### ISSUE THREAD

**Issue by Linksku** [webpack/webpack#10558]
## Feature request

Hi, so far, I've noticed that the following all cause ModuleConcatenationPlugin bailouts: DefinePlugin (injected variables), css-loader (module.id), and resolve.modules (context). It'll be nice if modules using these features can be concatenated.

For resolve.modules, I've found that Babel's module-resolver plugin does the same thing and it works with ModuleConcatenationPlugin. I haven't figured out how to address the other two. Are there existing alternatives?

**What is the expected behavior?**
Modules are concatenated.

**What is motivation or use case for adding/changing the behavior?**
Smaller file size.

**How should this be implemented in your opinion?**
No idea.

**Are you willing to work on this yourself?**
No.

**Comment by evilebottnawi** [comment]
Please provide reproducible test repo, thanks

**Comment by sokra** [comment]
DefinePlugin is fixed in webpack 5.

`module.id` is still a limitation, but you can use `mini-css-extract-plugin` in production.

`resolve.modules` do not opt-out. This seem to be something else. Do you mean `require.context`? yes this opts-out and there are no plans in fixing that.

webpack 5 will be able to do more optimization even without concatenating. Not being able to concatenate modules isn't such a big problem.
