### ISSUE TITLE
ES module not in cache?

### ISSUE THREAD

**Issue by stevenvachon** [webpack/webpack#10655]
```js
import module from '@namespace/module';

console.log(module);
//-> Module

console.log(Object.values(require.cache).filter(({exports}) => exports === module)?.i);
//-> undefined

console.log(require.resolve('@namespace/module'));
console.log(require.resolveWeak('@namespace/module'));
//-> Uncaught Error: Unable to resolve specifier '@namespace/module' from...
```

Are ES modules stored elsewhere?

**Comment by sokra** [comment]
Do not rely on `require.cache` for ESM. This is unspecced behavior.

They are sometimes in the cache. Exports is the whole namespace object of the module, so you have to use `import * as module` to find it in the cache.

But don't do that. If you really want to do something with the cache use `module.id` to access the module in cache.

Due to optimizations like module concatenation modules might not exist in the cache anymore. When using `module.id` it's guaranteed that a real module will be emitted.

This is webpack-only behavior!

**Comment by stevenvachon** [comment]
@sokra Thanks. Ultimately, I'm trying to get the path/URL to the module. Is that available somewhere consistent?

**Comment by stevenvachon** [comment]
Also, I actually am using `import * as module ...` in my code, but simplified it for the above example. The module is still not found in `require.cache`.

**Comment by sokra** [comment]
> Ultimately, I'm trying to get the path/URL to the module. Is that available somewhere consistent?

No, in production mode only an numeric id exist. Path is not avaiable.

**Comment by stevenvachon** [comment]
Okay, thank you.
