### ISSUE TITLE
UglifyJsPlugin hangs on module building.

### ISSUE THREAD

**Issue by cutandpastey** [webpack/webpack#1078]
When building my application with `webpack.optimize.UglifyJsPlugin({})` webpack consistently hangs at around ` 53% 267/366 build modules`. This seamed strange as I would expect it to hang at the optimising chunks stage (if at all).

When I comment https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L139 I get a successful build. Oddly enough the sources seem to have been both mangled and minified.  

Sadly I'm finding it hard to extract any debug information to move any further with this. Is there somewhere in the source I can add some logs to get a better idea of which module in my stack is causing the issue? I've tried `context.resource` but deleting the code in the offending module doesn't seem to effect the issue at all.

**Comment by jedwards1211** [comment]
Webpack is hanging for me, though I'm not using UglifyJsPlugin :(

**Comment by jamespamplin** [comment]
Hi, found the issue that was causing this problem for us. It was a bad HTML template breaking the html-loader / html-minifier. A badly closed quote `"` in the source, was breaking things. Switching to `raw` loader worked, allowing me to narrow in on the issue.

When you enable `UglifyJsPlugin`, it also activates minification in all loaders that support minification (`context.minimize`). So if you have similar issues when you enable `UglifyJsPlugin`, or use `-p` on the CLI, then I suggest you look at potential issues with all your loaders.

I suggest that webpack should implement a timeout for each compiler process so that it can catch hanging plugins, and error accordingly. Ideally, webpack should've errored with a timeout such as:

    html-loader timed out after 10s processing file: src/templates/bad-template.html

**Comment by cutandpastey** [comment]
thanks @jamespamplin

**Comment by johngrogg** [comment]
+1 to the suggestion to figure out how to error out in the html loader if `context.minimize` is true and a html error is causing the process to hang. Just ran into this problem today and it took me a couple hours to track down which file had the issue, since there was no actual error message.

**Comment by lazabogdan** [comment]
+1 .. just lost 6hrs of my life tracking down a similar issue caused by a loader when using `webpack -p`. The build was just stalling at "build modules" and no error, no timeout, no nothing. Just lovely time tracking it down in a serious dependency tree.

**Comment by JoshZA** [comment]
:+1:

**Comment by heziqiang99** [comment]
+1, it works when i delete "UglifyJsPlugin"
