### ISSUE TITLE
UglifyJsPlugin options.exclude does not work?

### ISSUE THREAD

**Issue by cutandpastey** [webpack/webpack#1079]
When using the UglifyJsPlugin within my webpack build I get a large list of errors from my `bower_components` dependencies. It looks to me (from here: https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L43) that I should be able to use something like this

``` js
new webpack.optimize.UglifyJsPlugin({
  exclude: [
    /bower_components\//
  ]
})
```

which continues to throw out a massive list of errors, leading me to believe they are still being parsed.

**Comment by kentcdodds** [comment]
I believe that I'm experiencing this as well:

```javascript
new webpack.optimize.UglifyJsPlugin({
  exclude: /\.test\.js/i,
  compress: {warnings: false}
})
```

**Comment by kentcdodds** [comment]
I've realized that in my case the reason that this is happening is that by the time the code gets to my `UglifyJsPlugin` it has already been concatenated into a single file (by the name of `formly.min.js`). I need to figure out a way to uglify before it concats...

**Comment by kentcdodds** [comment]
My solution was to use the `uglify-loader` and use `exclude: /\.test\.js/i`. This is not ideal for actually uglifying all the code because it works at the module level, but I'm just interested in my code working uglified under test. My actual distributable still uses `UglifyJsPlugin` so this workaround worked well for me.

**Comment by snapwich** [comment]
[I actually mentioned this issue in the pull-request that introduced this exclude feature for the UglifyJsPlugin.](https://github.com/webpack/webpack/pull/560#issuecomment-66818521)  Currently you can only exclude generated webpack chunks from being parsed, which is kind of pointless IMO since the general use-case is to avoid parsing required libraries, not your own generated code.

Hopefully the UglifyJsPlugin exclude feature can be updated to work as would be expected.  Although at this point it might need to be added as an additional configuration API since some projects may now be dependent on exclude working as it currently does.

**Comment by UnsungHero97** [comment]
is there any update on this? are there plans to implement a way to exclude files from being uglified?

**Comment by gdi2290** [comment]
this was merged already (via https://github.com/webpack/webpack/pull/560#issuecomment-66818521) I've used it

**Comment by okbel** [comment]
any update on this?

**Comment by gdi2290** [comment]
@okbel it's merged you can use it. I've been using it https://github.com/gdi2290/angular2-seed-RouterLink-error/blob/master/webpack.config.js#L42

**Comment by snapwich** [comment]
@gdi2290 the point of this issue is not that exclude doesn't exist or can't be used, it's that it doesn't work as expected.  Currently It only allows you to exclude post-processed chunks, as opposed to excluding individually included files as we had hoped.  Are you saying that the later has been implemented and merged?

**Comment by gdi2290** [comment]
oh my mistake, ya having pre-processed chunks would be nice rather than post-processed.

**Comment by Humeira** [comment]
I got the same issue today.
So the `exclude` does not work as expected? 💭

**Comment by MilosRasic** [comment]
It's working as expected, which is processing your generated chunks rather than source files. If you want to ignore only a few modules, extract them into a separate chunk and exclude that one from UglifyJsPlugin.

**Comment by Sawtaytoes** [comment]
@MilosRasic I've separated stuff out into a separate bundle, but how do I run UglifyJS on that one bundle separately from the rest? In my particular case, I need to mangle for one set of code and not mangle for the rest.

**Comment by MilosRasic** [comment]
@Sawtaytoes 
```
					new webpack.optimize.UglifyJsPlugin({
						exclude: 'chunkToNotUglify',
					}),
```

**Comment by Sawtaytoes** [comment]
Thanks! I was able to run this against my chunk name, and it did work. All I had to do was to put the UglifyJS plugin declaration in there twice. Once for the main bundle files excluding this particular one and another declaration for this particular one with `mangle: false`. I appreciate the help 👍.

**Comment by alvinbriones232** [comment]
Hi i'm having the same issue, my question is how to except a file in mangle? is it possible?

**Comment by alexsandro-xpt** [comment]
Thank you @MilosRasic , you save my week.
