### ISSUE TITLE
CommonsChunkPlugin & file-loader cause error.

### ISSUE THREAD

**Issue by cutandpastey** [webpack/webpack#1081]
When creating a common chunk from a chunk that loads assets with the file-loader I get:

```
Uncaught TypeError: Cannot read property 'call' of undefined
```
from:

``` js
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

It's important to note that I don't get this inlining assets with the url-loader. 

Ive tried to create a limited test case here: https://github.com/cutandpastey/webpack-problem/tree/jp-common-file-loader

### Steps to test:
- clone git@github.com:cutandpastey/webpack-problem.git
- checkout jp-common-file-loader 
- `npm install`
- `webpack`
- `npm start`
- open http://localhost:8080

That should do the trick.

**Comment by cutandpastey** [comment]
Misconfiguration, thanks @sokra

**Comment by Taytay** [comment]
@cutandpastey (or @sokra) : I am getting this too, and I know I'm doing something wrong with my commons chunk plugin. Any chance you remember if it was something silly and can point me in the right direction?

**Comment by Taytay** [comment]
Here's what I think happened:
Turns out it implies you have two webpack runtimes loaded in your page at the same time.
It can be caused by having a commons chunk (which will include the runtime) and an entry point that the commons chunk didn't reference, and thus includes the runtime itself.
As soon as I added my other entry points chunks to the list of chunks in the `CommonsChunkPlugin`, they no longer included the extra runtime, so including them in my page was no longer a problem.

**Comment by cchamberlain** [comment]
Thanks for the write-up @Taytay, this makes a lot of sense now but the error gives no hint as to what the issue is. Since the options for commons chunk plugin vary so widely, it would be nice if there were some sort of message that says you're loading multiple runtimes or something.

**Comment by acostaf** [comment]
HI All 

Just for information, I founf that this error it is a bit misleading, it is not a bug but the way how you build your common chunks. please refer to 

https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks
or 
https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk
