### ISSUE TITLE
Specifying “target” in webpack config as “electron-renderer” gives an error “window is not defined” while building with next build

### ISSUE THREAD

**Issue by aecs4** [webpack/webpack#10952]
In order to use "ipcRenderer" inside renderer process in my electron app, I have specified target as "electron-renderer" in my webpack config. Before specifying target it was not allowing me to import ipcRenderer in my code. But after doing this, it gives above specified error. All i want to do is to use ipc modules inside my renderer process.

my next.config.js is

`const withSass = require("@zeit/next-sass");
const withCss = require("@zeit/next-css");
const withPlugins = require("next-compose-plugins");
const webpack = require("webpack");
require("dotenv").config();

module.exports = withPlugins([
  [ withCss, {
      webpack: (config) => {
        const env = Object.keys(process.env).reduce((acc, curr) => {
          acc[`process.env.${curr}`] = JSON.stringify(process.env[curr]);
          // console.log(acc);
          return acc;
        }, {});
        config.node = {
          fs: 'empty'
        }
        config.plugins.push(new webpack.DefinePlugin(env));
        config.target = 'electron-renderer';

        return config;
      }
    } ],
  [
    withSass,
    {
      cssModules: true,
      cssLoaderOptions: {
        importLoaders: 1,
        localIdentName: "[name]___[local]___[hash:base64:5]",
      },
    },
  ],
])`

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
