### ISSUE TITLE
webpack regenerates the bundle every time

### ISSUE THREAD

**Issue by XVincentX** [webpack/webpack#1100]
Hello!
Is webpack capable to understand that the current output directory is up-to-date and avoid to regenerate all the bundles?

`webpack --config webpack.config.js`

Bundles generated. Then I simply run again

`webpack --config webpack.config.js`
without changing any file.

The bundle time is the same of the first run. I was expecting some mechanism able to detect that the build has not been touched.

Am I missing something or isn't a provided feature?

**Comment by shama** [comment]
Incremental builds are typically done with `watch` which enables `cache` by default: http://webpack.github.io/docs/configuration.html#cache

The re-build needs to happen within the same process context (such as a script that sits open and watches as opposed to running the command twice) in order to work.
