### ISSUE TITLE
HMR for federated modules

### ISSUE THREAD

**Issue by ChrisSG** [webpack/webpack#11182]
Hello all, hi @ScriptedAlchemy 

I opened this separately because I did not get any response on the original thread #10352. The question is if it would be possible to implement "comprehensive" HMR support for federated modules. 

That is you have an complete app made from different fragments that are served from other locations - e.g. one host with multiple remotes - and want to work on this using HMR (hot module reloading). In some setups it might be feasible to work on every fragment separately but on others not - e.g. if the remotes are not stand alone.

Is it already possible to achieve HMR where you view the whole app as one and have HMR with maybe react-hot-loader working? What would be needed to achieve that? I

I tried all sorts of things by even altering the Webpack source code for adapting the remote entries etc. This lead to a hot reload actually being triggered and updating the source code on the client. Sadly still components were not being re-rendered...

Thank you!

Regards,

Christian 

P.S.: I had a look at the HMR ssr eample but this is not quite the same setup as the one described here...

**Comment by ScriptedAlchemy** [comment]
Cross container hmr will be delivered seperately. 

Are you talking about reloading production to unstick updated modules or hmr in development for better DX?

**Comment by ChrisSG** [comment]
Hi Zack,

thanks footer your reply! I am talking about dev hmr for better DX. I got pretty far as I described.The re-rendering did not work though. What do you mean by "separately"? Anything I can do/help with? 

Regards,

Chris

**Comment by ScriptedAlchemy** [comment]
Use live reload and add something like this. ![image](https://user-images.githubusercontent.com/25274700/96356131-36ca3c80-109f-11eb-92d9-5c03dd058a3d.jpeg)

Cross container hmr won't officially come out this year. I think our budget is stretched. Which makes it hard to dev features. 

So till things renew, and everyone has time to get to HMR. Good old fashioned live reload or manual refresh does the job.

**Comment by ScriptedAlchemy** [comment]
True cross container hmr is going to be tricky. I think Tobias might be the only one with a solid idea on how to do it. 

But it likely requires big changes to HMR internals. Something I'd not touch alone without support from the project author. 

We could fork and improve live reloading as a stop gap solution. Since this works already, but could be better designed for federated environments. 
We could also open an issue with the project author of live reload and try to collaborate

**Comment by ChrisSG** [comment]
What I did was basically add the ability to have  websocket connections to multiple dev servers. The code then got updated and replaced. I just wonder what went wrong with the rendering not being triggered. I could try to find and publish my solution. Need to have a look which dependencies I used so we could all for further assistance....

**Comment by ScriptedAlchemy** [comment]
It's more than socket connections. The host needs to suppose of modules it has from the remote. 

Webpack needs to be aware of all HMR graphs and a hot reload requires hmr on remote as well and host remote modules. 


Like MF, the hot update needs to be shared and understood amongst all remotes in use.

**Comment by ChrisSG** [comment]
Ah right! Forgot I had a simpler use case as well. One "master" that pulls in many remotes with a directed graph towards the master all the time...

**Comment by ScriptedAlchemy** [comment]
If you're seriously looking into this. Can we get a shared repo going somewhere/ use one of my module federation example repos? I'm looking to get HMR of prod servers running. But I've not acquired might information on HMR. Like how'd you'd hook up the sockets lol. 

HMR is my weakness in webpack experience. If primitive "reload all" command can be sent to running servers or dev mode, it's a big step in the right direction

**Comment by ChrisSG** [comment]
Will do!

**Comment by ScriptedAlchemy** [comment]
Heads up on live reload. I need to fork the project because multiple remotes attempt to start the server on same port. 

I'll separate server boot from reload commands so it'll work with multiple remotes.

**Comment by ChrisSG** [comment]
Ok, great!  I'm still stuck with untangling the stuff I did so I can create a repo. Will take a while...

**Comment by ScriptedAlchemy** [comment]
We can create a private repo if it's got things you don't want public. I have many companies who send or Grant me access to their code. 

Otherwise I'll await your public repo!

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Maybe you want to help with webpack-dev-server?

**Comment by ScriptedAlchemy** [comment]
@evilebottnawi We would need to get on a call. I don't understand HMR at the level I need to for this. 

I'm happy to help WDS and I really want to learn HMR api and would like to enable prod hmr with MF 

If you're willing to walk me thru, I'll gladly dedicate efforts toward it

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy yep, I will help you, I want to finish webpack-dev-server v4 and we will focus on HMR for module federation

**Comment by ScriptedAlchemy** [comment]
Excellent, all my HMR work will be reallocated to WDS, very excited to work with you again @evilebottnawi - its been a while since our last collab on mini-css

**Comment by ChrisSG** [comment]
Sorry guys for letting you down. We are having heavy issues on our production environment the last two weeks. I will create the repo as soon as things run smooth again...

**Comment by sokra** [comment]
You can vote for this here: https://webpack.js.org/vote/

**Comment by wdfinch** [comment]
Any updates here?

**Comment by edarioq** [comment]
Also wondering for any updates on this ?

**Comment by Phinome** [comment]
do not ask anymore, vote for here:  https://webpack.js.org/vote/

**Comment by wdfinch** [comment]
I have voted, but that doesn't really give me any insight into the status of this. Is there a certain amount of votes required to get this delivered? Is this being worked on?

We aren't trying to be disrespectful, but I don't really know how the votes and external roadmap sync with current what is being actually worked on.

**Comment by ScriptedAlchemy** [comment]
@wdfinch I spent a significant amount of my influencer points on mf hmr. 

The thing you have to consider is MF on its own was extremely complex. Adding HMR across containers is not at all trivial. 

There's limited number engineers that can implement such a complex feature. Considering the sheer expense ($) and time to essentially implement a what a page reload solves. 

I'd prefer webpack spends tens of thousands on other more legitimate features before worrying about something that's so easy to manually work around. 

Yeah it's _slightly_ annoying but since it's pretty stable in production- I'm happy to wait. 

I'm pretty sure webpack pulls from highest voted and works the way down. 

While I can't speak to priority - I do know what the effort looks like for HMR and more or less why we didn't publish it back in October with MF. 

In order for HMR to work, the host would need to receive the context graphs of all remotes and how the relate to the host container. Since we have to flush parent modules as well as the actual child that's being hot reloaded. That's hard to do. 

If HMR is anything near what we had to change for MF to work - we are looking at some pretty large rewrites to the existing apis. 

This is OSS after all

**Comment by zhangzippo** [comment]
> Use live reload and add something like this. ![image](https://user-images.githubusercontent.com/25274700/96356131-36ca3c80-109f-11eb-92d9-5c03dd058a3d.jpeg)
> 
> Cross container hmr won't officially come out this year. I think our budget is stretched. Which makes it hard to dev features.
> 
> So till things renew, and everyone has time to get to HMR. Good old fashioned live reload or manual refresh does the job.

hello, is this can solve the MF‘s hotreload problem? if it can, i want to try
