### ISSUE TITLE
The class name disappears

### ISSUE THREAD

**Issue by doox911** [webpack/webpack#11266]
Why does the class name disappear during production product build?

My packege:
https://github.com/doox911/inspector

https://stackoverflow.com/questions/63129448/class-module-is-not-exported

**Comment by sokra** [comment]
It's calling "minimizing".

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
