### ISSUE TITLE
initialize hook is undefined

### ISSUE THREAD

**Issue by atilkan** [webpack/webpack#11273]
**Do you want to request a *feature* or report a *bug*?** 
 *bug*

**What is the current behavior?**
initialize hook is undefined. https://webpack.js.org/api/compiler-hooks/#initialize

**If the current behavior is a bug, please provide the steps to reproduce.** 
I can tap any other hooks but initialize.

```
{
     apply: (compiler) => {
        compiler.hooks.initialize.tap("AfterEmitPlugin", (compilation) => {
          console.log("started!");
         });
     },
},
```

**What is the expected behavior?**
return initialization information. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by sokra** [comment]
> Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.

Missing!

Probably webpack 4, but this is a webpack 5 hook...

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by atilkan** [comment]
Webpack 5 beta but when i go to documentation it is 5 by default. So i need to read little note somewhere on the huge page.
