### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by krishnaTORQUE** [webpack/webpack#11284]
It was working until I update to latest version

No issue in development server

Once I build the project getting this issue

SyntaxError: missing } after property list
note: { opened at line 1, column 1998

ChunkLoadError: Loading chunk 1 failed
/static/js/1.75c86cba.chunk.js

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
