### ISSUE TITLE
Loading all chunks in development mode

### ISSUE THREAD

**Issue by simkessy** [webpack/webpack#11287]
When webpack is in development mode, it loads all the chunks in my page as opposed only those needed in development. This is extremely slow on a large site, we're loading multiple mb's per refresh and overload load is 3 minutes. 

![image](https://user-images.githubusercontent.com/5871660/89492801-48ba6580-d767-11ea-8fc0-9c3f64f22ecc.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
