### ISSUE TITLE
webpack tutorial is broken

### ISSUE THREAD

**Issue by bobzhang** [webpack/webpack#1130]
I followed this tutorial, it is not working when I try to add a css file

cat entry.js
```
require("!style!css!./style.css");
document.write(require('./content.js'));
```
```
webpack_tutorial$ webpack ./entry.js bundle.js 
Hash: 6975b28bf0ad8a1c7ddd
Version: webpack 1.9.10
Time: 42ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.74 kB       0  [emitted]  main
   [0] ./entry.js 76 bytes {0} [built] [1 error]
   [1] ./content.js 45 bytes {0} [built]

ERROR in ./entry.js
Module not found: Error: Cannot resolve module 'style' in /Users/hongbozhang/git/react.git/code/webpack_tutorial
 @ ./entry.js 1:1-34
```

**Comment by SimenB** [comment]
`npm install --save-dev style-loader`?

**Comment by bobzhang** [comment]
I installed it, but still get the same error

**Comment by bobzhang** [comment]
ah, it's css-loader, it would be nice to document it : )

**Comment by shama** [comment]
@bobzhang The docs are an editable wiki here: https://github.com/webpack/docs/wiki/contents feel free to update them or point me to the location that needs correction. Thanks!

**Comment by bebraw** [comment]
@bobzhang Safe to close?

**Comment by bobzhang** [comment]
Yes, please

**Comment by Tabares** [comment]
It works installing loader thanks for the advice...

**Comment by gary1410** [comment]
The above comment was a bit vague.  Instead of `npm install --save-dev style-loader` USE `npm install --save-dev css-loader`  I'm not sure what the difference is, I'm not too familiar with the npm ecosystem.  Anyway I can get an explanation.  I wouldn't mind updating the docs on the wiki afterwords.  Took me about an hour.  Would love to safe an hour time for someone else.
