### ISSUE TITLE
context module doesn't work with array of aliases

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack#11335]
**webpack.config.js**

```js
module.exports = {
    mode: 'development',
    devtool: 'source-map',
    entry: './src/main/index.js',
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    resolve: {
        alias: {
            app: [path.join(__dirname, 'src/main'), path.join(__dirname, 'src/foo')]
        }
    }
};
```

**index.js**

```
import a from 'app/widgets/a';
import b from 'app/widgets/b';
import c from 'app/widgets/c';

console.log('\nstatic import\n');

a();
b();
c();

console.log('\ndynamic import\n');

const load = id => import(/* webpackMode: "eager" */ `app/widgets/${id}`);

load('a').then(ad => ad.default())

    .then(() => load('b'))
    .then(bd => bd.default())

    .then(() => load('c'))
    .then(cd => cd.default())

    .catch(err => console.log(err));
```

Reproducible test repo - https://github.com/homobel/webpack5-dynamic-import

Ref: https://github.com/webpack/webpack/issues/9802#issuecomment-674073005

**Comment by Zuckjet** [comment]
@sokra @evilebottnawi   I am glad to try to fix this issue, and I want to have a discussion here to make sure I don't misunderstand this issue before sending a PR.

when createing a ContextModule
```new ContextModule(result.resolveDependencies, result),
```
the **result** params is  a string which valuse is "xxx/src/main/widgets", so  ```resolveDependencies``` function in ContextModuleFactory.js just read files under "main/widgets" directory . And thus not including files under "foo/widgets" directory. 

In order to fix this issue, it seems I should make changes in two repo, both webpack and enhanced-resolve.

1. Since the result param in ```new ContextModule(result.resolveDependencies, result)```  is resolved by alias plugin  in enhanced-resolve, I should make it return array not string.
2. the resolveDependencies function in ContextModuleFactory.js should be able to handle array.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Reverted

**Comment by vankop** [comment]
merged again =)
