### ISSUE TITLE
change rules Use path

### ISSUE THREAD

**Issue by fish-uncle** [webpack/webpack#11351]
I wrote my own cli for launching and packaging projects
```
npm i cli -g
```
Then I found a problem

On startup

The Babel loader set in the CLI reads the

The report did not find the loader error

Is there any way to do this?

If the installation in the project is no problem

**Comment by fish-uncle** [comment]
```
entry: [
    'webpack-hot-middleware/client?noInfo=true&reload=true',
  ]
```

have same problem

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by evilebottnawi** [comment]
I will reopen issue when you fill out the issue template
