### ISSUE TITLE
out of memory in nodejs v10 webpack5 beta 27

### ISSUE THREAD

**Issue by ckken** [webpack/webpack#11352]
![image](https://user-images.githubusercontent.com/3890513/90754332-53026500-e30c-11ea-92fb-52cdbbfbf594.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
