### ISSUE TITLE
Loss css after build

### ISSUE THREAD

**Issue by yarastqt** [webpack/webpack#11424]
# Bug report

**Introduction**

I have a component with structure:

```sh
├── Button.css                  # Common css
├── Button.js                   # Common implementation
├── Button@desktop.css          # Desktop-specific css
├── Button@desktop.js           # Reexport common implementation and import desktop-specific css
├── _view
│   ├── Button_view_action.css
│   └── Button_view_action.js   # Modifier with import css and export logic
├── desktop
│   ├── bundle
│   │   ├── index.js            # Public API with applying modifier and desktop implementation
│   │   └── package.json        # Turn off side effects
│   ├── index.js                # Desktop public API with reexports modifier and implementation 
│   └── package.json            # Side effects — css
├── index.js                    # Common public API with reexports modifier and implementation
└── package.json                # Side effects — css
```

**What is the current behavior?**

After build with production mode, css from re exported files will be removed:

```js
/** Button@desktop.js */
export * from './Button'
import './Button@desktop.css'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Repository with minimal example for reproduce — https://github.com/yarastqt/webpack-css-issue

Steps:

1. Install dependencies — `npm ci`
1. Try change import one of `common|desktop|bundle` in `src/index.js` file
1. Build with prod mod — `npm run build:prod`
1. Look in `build/css/bundle.css` for result

**What is the expected behavior?**

All css-files should be exist in bundle.

**Other relevant information:**
webpack version:  **4.44.1**
Node.js version: **12.18.1**
Operating System: **macOS Catalina 10.15.6**
Additional tools: **—**

**Comment by sokra** [comment]
Such kind of problem is often caused by incorrect side effects flagging. You seemed to assume that and added sideEffects flags for *.css. But here it misses `Button@desktop.js`. It's not obvious, but it also has side effects. The definition of the sideEffects flags says: "has no side effects when no direct export is used".

But the `Button@desktop.js` module has a side effect (imports the css), when no direct exports are used (reexports are not direct exports).

Side effects flag doesn't bubble up the modules tree. Instead "no side effects" override the side effect of the dependencies.

Webpack 5 applies the side effects optimization in dev mode too, so this should become easier to find in future.

**Comment by sokra** [comment]
Yes, every module which evaluating has an effect on exports of other modules.

Button@desktop.js has an effect on Button.js.

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
