### ISSUE TITLE
Webpack + Reactjs, How to build split vendors, runtime enviroment file and component file

### ISSUE THREAD

**Issue by namnguyen2091** [webpack/webpack#11468]
My purpose, split vendors, runtime enviroments file and component file (js file) maybe like this:
- vendors.js
- runtimes.js
- component.js (each route each component)
I have a layout, every page I will include vendors.js and runtimes.js and each page has unique component.js file. I think this is stupid idea but I wanna know I can do it or not. So can I do it?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by namnguyen2091** [comment]
> It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

sorry, I will update my answer

**Comment by evilebottnawi** [comment]
@namnguyen2091 Please use stackoverflow or gitter for questions, there are a lot of guides in google
