### ISSUE TITLE
Change webpack DefinePlugin value based on Webpack build context

### ISSUE THREAD

**Issue by Acidic9** [webpack/webpack#11557]
## Feature request

Allow function to be passed to DefinePlugin with build context passed as an argument.

Stackoverflow post related to this: https://stackoverflow.com/questions/64131789/change-webpack-defineplugin-value-based-on-webpack-build-context

**What is the expected behavior?**

More dynamic DefinePlugin behaviour allowing value of key to be based on the current build context.

**What is motivation or use case for adding/changing the behavior?**

I wanted to write a single JavaScript entry which can be compiled into two separate outputs: one with all features and one with less features (free version).

Here is an example of the behavious I needed:

```javascript
module.exports = {
  entry: {
    main: "main.js",
    "main-free": "main.js",
  },
  plugins: [
    new webpack.DefinePlugin({
      FREE_VERSION: (ctx) => ctx.entryName.endsWith("-free"),
    }),
  ],
  output: {
    filename: `[name].js`,
  },
};
```

```javascript
// main.js

if (FREE_VERSION) {
  alert("You're using a free version.");
} else {
  alert("Thank you for purchasing.");
}
```

**How should this be implemented in your opinion?**

Keys should support functions which will be evaluated on build.

```javascript
new webpack.DefinePlugin({
  KEY: (webpackContext) => webpackContext.entryName,
})
```

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Already possible https://webpack.js.org/plugins/define-plugin/#runtime-values-via-runtimevalue

**Comment by denis-migdal** [comment]
> Already possible https://webpack.js.org/plugins/define-plugin/#runtime-values-via-runtimevalue, feel free to feedback

Are you sure we can really get the entry name from the module ?

**Comment by alexander-akait** [comment]
@denis-migdal What do you mean? Which entry name?

**Comment by denis-migdal** [comment]
> [@denis-migdal](https://github.com/denis-migdal) What do you mean? Which entry name?

OP declares 2 entries :
- main
- main-free

He wants to build the first using `FREE_VERSION=false` and the second with `FREE_VERSION=true`.

For that, he wanted to use something like:
```js
plugins: [
    new webpack.DefinePlugin({
      FREE_VERSION: ({module}) => JSON.stringify( getEntryName(module).endsWith("-free") )
    }),
  ],
```

I tried to take a look at it, but didn't found a simple way to access the entry name from the module.
Which may be due to the fact that the module is processed only once, even if used by multiple entries (?).

The solution seems to be the one suggested in his SO, to return an array of Webpack configuration, each having a different `DefinePlugin` (the issue being that Webpack would then process some shared files twice).

**Comment by alexander-akait** [comment]
You need a module graph here, because module can be in multiple chunks, also modules can be removed/concatenated/moved/extracted, so you can get value in wrong placed, why you need to relay on such strange logic?

I recommend to use multicompiler mode as you describe above, this will allow you to fine-tune the logic and not mix it modules/options/variables/etc

**Comment by denis-migdal** [comment]
> I recommend to use multicompiler mode as you describe above, this will allow you to fine-tune the logic and not mix it modules/options/variables/etc

The issue I see is that, if we have a big code base that takes ~8sec to build, having 2 targets makes it ~16sec to build (and more if we have more targets).

Not sure also how it would behave in watch mode (and with `tsc`).


I do not know Webpack's internals, but assuming we have a `foo.ts` file using `FREE_VERSION`, it could be nice if Webpack/DefinePlugin could internally create `foo.ts[FREE_VERSION=true]` and `foo.ts[FREE_VERSION=false]` modules, and fetch the correct version when imported.

The goal would be to not rebuild modules that do not use `FREE_VERSION`, instead of building them twice each time, without worrying about cache issue.

**Comment by denis-migdal** [comment]
> technically this can be solved through `layer` https://webpack.js.org/configuration/module/#rulelayer (you can find more examples in our test - `test/ConfigCases`).

Can't find information about what layers are in Webpack (only found some unanswered SO questions).

> Why just don't use:
> 
> ```
> { entryFull: "./entry-full.js" entryFree: "./entry-free.js" }
> ```
> 
> And check `process.env.FREE_VERSION` only in `entry-free.js`?

Let's assume a project:
```
|---- others/...
|---- modules
|        |---- A/index.ts
|        |---- B/index.ts
|        |---- C/index.ts
|        |---- D/index.ts
|        |---- E/index.ts
|----main.ts
```

In the `index.ts` files, let's assume some `if( ! FREE_VERSION )` conditions.

The goal would then to be able to build 2 versions of `main.ts`, one where `FREE_VERSION` is set to `true` for all files it imports directly or indirectly, and one where it is set to `false`.

For a large code base, we might want to avoid rebuilding all files twice, even more if some files doesn't use `FREE_VERSION`.

**Comment by alexander-akait** [comment]
@denis-migdal Sorry for delay, I will send a test case to our repo and provide how to make what you want, we already support it

**Comment by alexander-akait** [comment]
So you don't need to really on chunks, because it is unsafe (as was requested originally), instead you are working with modules

**Comment by denis-migdal** [comment]
> [@denis-migdal](https://github.com/denis-migdal) Look at this [#19383](https://github.com/webpack/webpack/pull/19383), do you need something additional?
> 
> I will add more complex tests with `layer` splitting too, may useful for large codebases

Thanks.

I will test that with the current Webpack version this WE.


Is there a place in the documentation explaining what layers are (last time I checked I didn't found much information about this feature).

**Comment by alexander-akait** [comment]
@denis-migdal It's still experimental, although there are a lot of tests, so I would say that you can use it in real projects, but the documentation is very bad, unfortunately I can't find time for documentation at all, especially experimental things 😞

**Comment by denis-migdal** [comment]
`ctx.module.layer` is always `null` for me (using webpack 5.98.0).
Even after setting `cfg.experiments.layers = true;`.

I guess I have some how to use the Webpack dev version.

**Comment by denis-migdal** [comment]
Sorry, I previously made a mistake.

Seems to work. 👍

**Comment by alexander-akait** [comment]
@denis-migdal Feel free to feedback if you will other questions about layers, it is very interesting feature
