### ISSUE TITLE
[webpack 4] disable parallelism

### ISSUE THREAD

**Issue by Scrum** [webpack/webpack#11564]
How to disable parallel processing `entry` what would they be processed sequentially?

Perhaps there is another way to indicate the dependency `entry` from another `entry`?

as an example I have
```js
{'A': 'A-path'},
{'B': 'B-path'}
```

I need `B` to start getting ready after the end of `A`

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
