### ISSUE TITLE
Webpack command builds code with broken exports

### ISSUE THREAD

**Issue by SurmaAa** [webpack/webpack#11575]
Hey, I've got a problem with making a React Component npm package. In a component in this package I use an image (import MyPicture from 'path/image.png'). I wanted to export it in as a git npm package so I installed babel to transpile it and it failed on converting png to js so I installed webpack and used image-loader + babel-loader. Everything on npm start works but my IDE (Webstorm) doesn't see the paths after webpack builds.  If I build it using babel, the IDE finds the correct paths, but the image isn't transpiled. Anyone got similar problem?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by evilebottnawi** [comment]
Please use the issue template and I will reopen issue
