### ISSUE TITLE
Webpack 5. Offline plugin error.

### ISSUE THREAD

**Issue by sergeu90** [webpack/webpack#11642]
After update i have some error.I don't know where write. But after update i have some problem.
https://github.com/NekR/offline-plugin/issues/491 I wrote there. 

Maybe someone had problems with this

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please be patient and wait answer from developers of plugin, but I recommend to migrate on workbox-webpack-plugin
