### ISSUE TITLE
Webpack 5 HMR plugin error in runtime.[hash].hot-update.js

### ISSUE THREAD

**Issue by SPWizard01** [webpack/webpack#11670]
# Bug report

**What is the current behavior?**
i am not sure whether this is webpack-dev-server issue or webpack or something else, however after 1st hot reload happens there is a constant error: 
```
jsonp chunk loading:103 Uncaught TypeError: Cannot read property 'push' of undefined
    at self.webpackHotUpdatePACKAGEJSONNAME (jsonp chunk loading:103)
```

```
self["webpackHotUpdatePACKAGEJSONNAME"] = (chunkId, moreModules, runtime) => {
	for(var moduleId in moreModules) {
		if(__webpack_require__.o(moreModules, moduleId)) {
			currentUpdate[moduleId] = moreModules[moduleId];
			if(currentUpdatedModulesList) currentUpdatedModulesList.push(moduleId);
		}
	}
	if(runtime) currentUpdateRuntime.push(runtime); // error happens here
	if(waitingUpdateResolves[chunkId]) {
		waitingUpdateResolves[chunkId]();
		waitingUpdateResolves[chunkId] = undefined;
	}
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

launch dev-server with hot:true

**What is the expected behavior?**
does not happen in webpack@4
i think that the issue is that this variable `currentUpdateRuntime` is accessed before it is initialized in:
`__webpack_require__.hmrI.jsonp`
or 
`__webpack_require__.hmrC.jsonp`

**Other relevant information:**
webpack version:  5.1.0
Node.js version: v12.18.0
Operating System: Windows 10
Additional tools:
webpack-devs-server@latest

**Comment by evilebottnawi** [comment]
Sorry, please provide more infromation  

> If the current behavior is a bug, please provide the steps to reproduce.

launch dev-server with hot:true

is not enough to debug the problem

I will reopen this issue after you fix it

**Comment by evilebottnawi** [comment]
Please provide your configuration as minimum, recommendation is to create reproducible repo

**Comment by birdofpreyru** [comment]
@evilebottnawi This issue is real, I also encountered it. For me the crash happens in this line of code generated by Webpack@5: https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L325 when I reload a page after the first HMR happened.

I am not able to reproduce it with a simple codebase, but I figured out that it can be fixed by setting initial values of `currentUpdate` and `currentUpdateRuntime` here:
https://github.com/webpack/webpack/blob/3094cf4e2431853352e6183c0e4cb33708bb9f1b/lib/hmr/JavascriptHotModuleReplacement.runtime.js#L20-L23
_i.e._ replacing that with
```
 var currentUpdateChunks; 
 var currentUpdate = {}; 
 var currentUpdateRemovedChunks; 
 var currentUpdateRuntime = []; 
```

Such update breaks 4 unit tests, which explicitly check that `currentUpdate` is not equal `{}` in some situations; though reviewing the actual Wepback code it seems to me the only spot where it may alter something is this one: https://github.com/webpack/webpack/blob/master/lib/hmr/JavascriptHotModuleReplacement.runtime.js#L382-L387, where if `currentUpdate` is undefined all these four variables are initialized to empty arrays/objects, and `applyHandler` is pushed to `applyHandlers` array. So, it seems the code can be refactored without altering the current behavior, but avoiding the possibility of `currentUpdate` and `currentUpdateRuntime` being undefined, which is not good as a bunch of code attempts to access them without verifying they are actually defined:

**Comment by evilebottnawi** [comment]
> I am not able to reproduce it with a simple codebase

I am too, so I can't find a problem, we can't change code without tests

**Comment by birdofpreyru** [comment]
@evilebottnawi I figured it out. It happens if any `XXX.hot-update.js` is by mistake loaded into the frontend as a standalone script. Thus not a Webpack bug, but detecting it automatically and throwing a clear error message may be a nice feature. The mistake is easy to do, if somebody takes chunk names from webpack stats and infects them all as `<script>` into html (oiginally there is no `xxx.hot-upload.js` chunks, and when they appear it is difficult to find out the problem from an obscure error message about a crush inside Webpack).

**Comment by evilebottnawi** [comment]
@birdofpreyru Do you have ideas how we can improve it?

**Comment by birdofpreyru** [comment]
@evilebottnawi something like this: https://github.com/birdofpreyru/webpack/commit/0f228d356c6e936e458743594b10a48aa5c5b5ab (though, I'd guess, there is a better way to check it)?

**Comment by evilebottnawi** [comment]
@birdofpreyru I think we should output this only when HMR enabled for reduce runtime code, anyway good idea, maybe you can send a PR?

**Comment by birdofpreyru** [comment]
Sure @evilebottnawi , PR created.

**Comment by retyui** [comment]
how can i fix this issue or debug?

**Comment by birdofpreyru** [comment]
@retyui rewise how JS chunks are injected into your HTML. If upon DOM inspection in HMR mode you see there elements directly refererring to `xxx.hot-update.js`, they should not be there, and you should track down how they appear there and prevent it.

**Comment by retyui** [comment]
@birdofpreyru 

Hmm...
I checked my DOM when an error accrue and there is no script with `xxx.hot-update.js`

```js
polyfills.js:978 Uncaught TypeError: Cannot read property 'push' of undefined
    at self.webpackHotUpdateapp_mobile (polyfills.js:978)
    at 0.e6b96d1b60024bc8391f.hot-update.js:9
```

I see that on the Network tab an initiator of the load is `0.js:602` (not HTML)

```js
// See seond  attached file (more code + stach trace)
/******/ 	/* webpack/runtime/load script */
//...
/******/ 			needAttach && document.head.appendChild(script);
```

Network:
![image](https://user-images.githubusercontent.com/4661784/106356725-6e858900-630a-11eb-80b4-dc938db7d7e4.png)

Code:
![image](https://user-images.githubusercontent.com/4661784/106356913-988b7b00-630b-11eb-997d-cfd999c7f714.png)

**Comment by retyui** [comment]
@birdofpreyru 

Omg, It does not work for me!!!

The problem was that a spreading array to object and it led to duplication `webpack/runtime`

and a `webpack-hot-middleware/client?reload=true` was isolated from 'src/index.js'

```
// webpack.dev.confg.js
const devConfig = {
  entry: [
    //
    'webpack-hot-middleware/client?reload=true',
    'src/index.js',
  ],
};

/
// webpack.confg.js
module.exports = {
  entry: {
    base: ['my-module'],
    ...devConfig.entry,
  },
};

// And result was
entry = {
  base: ['my-module'],
  [0]: 'webpack-hot-middleware/client?reload=true',
  [1]: 'src/index.js',
};
```

**Comment by vjpr** [comment]
I had the same issue when using Module Federation. If I remove the federated import (`import('MyModule/Button')`), then everything works fine. Adding the federated import and things break.

I am using a proxy to avoid CORS issues, so that `localhost:3000` goes to my `host` app, and `localhost:3000/federation/MyModule` redirects to my `other` app.

When the websocket message arrives, it inits `currentUpdateRuntime = []`.

I think the issue is that the `webpack/runtime/jsonp chunk loading` (`self.webpackHotUpdate`) is being loaded a second time when I import my `other` app. In the dev tools, I can see that it's being run from the `other` app when it errors. So I suspect it's re-initing `var currentUpdateRuntime;`.

I guess its an issue with my entry point from my `other` app.

**Comment by kbruccoleri** [comment]
> @evilebottnawi I figured it out. It happens if any `XXX.hot-update.js` is by mistake loaded into the frontend as a standalone script. Thus not a Webpack bug, but detecting it automatically and throwing a clear error message may be a nice feature. The mistake is easy to do, if somebody takes chunk names from webpack stats and injects them all as `<script>` into html (oiginally there is no `xxx.hot-upload.js` chunks, and when they appear it is difficult to find out the problem from an obscure error message about a crush inside Webpack).

This saved me, thanks so much for this!

**Comment by SecretPocketCat** [comment]
> @retyui rewise how JS chunks are injected into your HTML. If upon DOM inspection in HMR mode you see there elements directly refererring to `xxx.hot-update.js` (after the actual HMR have been triggered at least once), they should not be there, and you should track down how they appear there and prevent it.

@birdofpreyru So just to be clear - the `.hot-update.` scripts (incl. a manifest) should never be present in the markup of the page - not initially, nor after any number of HMR updates. Otherwise the `Cannot read property 'push' of undefined` from the OP is gonna pop-up.
Is that right?

**Comment by birdofpreyru** [comment]
@SecretPocketCat Correct.
