### ISSUE TITLE
__webpack_require__.u returns a undefined hash for webworker scenario

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#11677]
# Bug report

**What is the current behavior?**
It outputs undefine as the hash

```js
/******/ 	/* webpack/runtime/get javascript chunk filename */
/******/ 	(() => {
/******/ 		// This function allow to reference async chunks
/******/ 		__webpack_require__.u = (chunkId) => {
/******/ 			// return url for filenames based on template
/******/ 			return "" + chunkId + "." + undefined + ".js";
/******/ 		};
/******/ 	})();
```
if I change to use `[name].[hash].js` as the `output.filename`, it works

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`git clone https://github.com/wood1986/webpack-v5-webworker-bug`
`yarn start`
open dist/index.<hash>.js

it should be a hash not "undefined"

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 14.13.0
Operating System: 10.15.7
Additional tools:

**Comment by wood1986** [comment]
I try to fix but I need some hints

**Comment by ivan-aksamentov** [comment]
Oh, thanks. I thought I am going crazy with this error. This holds us back from otherwise very smooth upgrade.

Could this be the fragment that produces the erroneous name?
https://github.com/webpack/webpack/blob/77329b4d0e1aa35e26d8a32b2a8968a824b5de9c/lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js#L46-L52

Maybe this function?
https://github.com/webpack/webpack/blob/2f2cbe50fe9274d732346e9c47c63a944a071e8a/lib/javascript/JavascriptModulesPlugin.js#L367-L377

**Comment by sokra** [comment]
The issue is a bit tricky. It's about the order in which the chunks are created. worker chunk need to be generated before the main chunk.
But it could also become a bit tricky when two workers depend on each other in circular way... (maybe we just keep this as unsupported edgecase)
