### ISSUE TITLE
Exports are placed inside a namespace when libraryTarget is commonjs2

### ISSUE THREAD

**Issue by dkamyshov** [webpack/webpack#11688]
# Bug report

**What is the current behavior?**

If `output.library` is specified and `output.libraryTarget` is `commonjs2`, library exports are placed inside a namespace (`output.library`).

If `output.library` is omitted, the exports are as expected, but the paths in source maps are incorrect (paths do not include library name).

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction repository: https://github.com/dkamyshov/webpack-5-lib-reproduction

See https://github.com/dkamyshov/webpack-5-lib-reproduction/blob/master/README.md for details.

**What is the expected behavior?**

Same as with webpack@^4 - no namespace and correct paths in source maps.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 12.8.4
Operating System: Ubuntu 20.04.1 LTS
Additional tools: yarn v1.22.5

**Comment by dkamyshov** [comment]
The issue is still present as of webpack@5.4.0. Is this working as intended? Am I missing something in the config?

**Comment by evilebottnawi** [comment]
No, need a fix, feel free to send a fix

**Comment by sokra** [comment]
The namespace is missing because you don't have a `"name"` in your `package.json`. The configuration options `output.devtoolNamespace` controls the namespace in SourceMaps. It defaults to `output.library.name || output.uniqueName`. `output.uniqueName` defaults to `package.json`.`"name"`.

While the inconsistency of `output.library` between webpack 4 and 5 is unintended, I think changing that is not worth it. That would be a breaking change. You could take it as feature...
