### ISSUE TITLE
Dynamic Requires

### ISSUE THREAD

**Issue by nick-thompson** [webpack/webpack#118]
Hi!

My entry module uses a dynamic require, which forces Webpack to try to build every file under the context directory into one gigantic bundle. Is there a way to restrict which files webpack tries to bundle in this case? For example, ignoring any files underneath various test directories? Is there also a way to force webpack to split these files out into several bundles?

I think, because the dynamic require is so ambiguous, Webpack determines that every file within the context directory should be bundled with the entry file so that they're all available should the dynamic require need them. That makes plenty of sense, but at some point I'd like `require` to send off an ajax request for the next bundle. How can I force that?

Thanks!

**Comment by surkova** [comment]
Just to contribute with a use case for dynamic loading: I'm working on a application that needs to load language and formatting data depending on a parameter in the address string. Right now, using `require.context` I see that all files a being bundled whereas I require only one of them. Still, the bundle is huge.

**Comment by fresheneesz** [comment]
@surkova You can use `require.ensure` to handle dynamic loading in your case.

**Comment by fresheneesz** [comment]
@surkova You can use `require.ensure` to enable dynamic loading in your case

**Comment by mschipperheyn** [comment]
Just curious, why a callback in stead of a Promise? Seems kind of old school

**Comment by SimenB** [comment]
Webpack 2 will suport SystemJS, which returns a promise

**Comment by adamziel** [comment]
Is there a way to make webpack behave a bit like `require.js` and load each and every file asynchronously in development? This would eliminate the need for source maps that are the root cause of many debugging troubles (some stack traces are not mapped for example)

**Comment by jhnns** [comment]
@adamziel I think that would be pretty complicated to do and thus it out of scope (and it drastically changes the way how your code works in development).

**Comment by juan-bastidas** [comment]
Hi

I have a folder with many files, those are libs to load different shapes on an application to draw things. Normally we don't need all of them loaded at once, they are needed on demand.

I'have defined a split point for all files within that folder. I load those files dynamically at runtime, but not all of them are needed just few depending on the case.
The folder contains 64 files, all of them 9MB and again at runtime I load 5, maximum 10.

I'm moving from requirejs world to webpack and with requirejs I see on the browser just few of them loaded, with webpack the problem is that one bundle is created, that bundle contains all files so the bundle is 9MB. I want to not have them all in just oen bundle, I've tried many things and few plugins like webpack-split-by-path and split-by-name-webpack-plugin but still one bundle is generated. How can I configure webpack to make more bundles or even generate one bundle per file just for that folder?

Any advice?

Thanks

**Comment by somebody32** [comment]
@juan-bastidas I recently wrote an [article about that](https://medium.com/@somebody32/how-to-split-your-apps-by-routes-with-webpack-36b7a8a6231#.dy38h6mqr/
There I'm splitting app by routes, but I think it can be easily converted to your case

**Comment by jbielick** [comment]
@juan-bastidas I have a similar setup and this was indeed possible with @somebody32 's help.

For example:

We load templates asynchronously and we only need one or two. There are dozens, though. One template can be loaded like this and will be bundled completely separately. If you're also using the CommonChunksPlugin, these isolated pieces will only contain their specific content and not the common code.

Install `bundle-loader` and then:

```
    let getTemplate = require(`bundle!./templates/${templateName}.jsx`);

    getTemplate((module) => {
      let preview = React.createElement(module.default, data);
      ReactDOM.render(preview, this.el);
    });
```

**Comment by mcku** [comment]
I have a similar situation as @somebody32 mentioned where app is split by routes and dynamic requires. The interesting thing is, output bundle contains unminified strings wrapped by `eval()`. Is there a way to make sure it gets minified, or am I missing something?

example:
```
/* this is okay to me */
!function(e){function n(t){if(r[t])return r[t].exports;var a=r[t]={exports:{},id:t,loaded:!1};return e[t].call(a.exports,a,a.exports,n),a.loaded=!0,a.exports}var t=window.webpackJsonp;window.webpackJsonp=function(r,o){for(var i,s,l=0,c=[];l<r.length;l++)s=r[l],a[s]&&c.push.apply(c,a[s]),a[s]=0;for(i in o)e[i]=o[i];for(t&&t(r,o);c.length;)c.shift().call(null,n)};var r={},a={1:0};return n.e=function(e,t){if(0===a[e])return t.call(null,n);if(void 0!==a[e])a[e].push(t);else{a[e]=[t];var r=document.getElementsByTagName("head")[0],o=document.createElement("script");o.type="text/javascript",o.charset="utf-8",o.async=!0,o.src=n.p+""+({0:"chp",2:"fp",3:"csp",4:"lp",5:"clp"}[e]||e)+".chunk.js",r.appendChild(o)}},n.m=e,n.c=r,n.p="",n(0)}

/* why eval ?  */
([function(module,exports,__webpack_require__)
	{eval("\"use strict\";\nvar __extends = (this && this.__extends) || function (d, b) {\n    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];\n    function __() { this.constructor = d; }\n    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\n};\nvar __assign = (this && this.__assign) || Object.assign || function(t) {\n    for (var s, i = 1, n = arguments.length; i < n; i++) {\n        s = arguments[i];\n        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))\n            t[p] = s[p];\n    }\n    return t;\n};\nvar React = __webpack_require__(1);
		
```
**... the whole module continues without minification ...**

Is this above how dynamic require is intended to work, how can i push more uglifyjs2 into it?

**Comment by mcku** [comment]
Well, I could not find a working means in webpack but the workaround was to check environment conditionally in the code such as:
```
    require.ensure(['./myModule'], (require) => {
        resolve(require(
          (process.env.NODE_ENV === "production"?'uglify!':'')+
          './myModule'
        ).default);
```
this one results in the same eval wrapped strings, but this time they are uglified

**Comment by sokra** [comment]
It's wrapped by `eval` because you used an `eval` devtool.

**Comment by kentmw** [comment]
@fresheneesz did you end up solving your problem of wanting to require user defined plugins using webpack? I am starting to design a plugin architecture and I'd like the person building the application (using webpack) to define an plugin config, something like:
```
plugins = [
  {
    package: "myPlugin",  // or "../path/to/plugin/myPlugin"
    // other config
  },
  {
    // ...another plugin
  }
]
```
and in the main application, I'm hoping to do:
```
plugins.forEach(function(plugin) {
  require(plugin.package);
});
```

@sokra Because the person defining the plugin config is the same person running webpack to build the end bundle, I don't see why this would be a security issue.

**Comment by fresheneesz** [comment]
@kentmw I haven't yet, but I will soon (in the next month or so). In my case, the person defining the plugin config will not be the same person building the end bundle, so I just won't be using any webpack functionality directly for this.

**Comment by jri** [comment]
Thanks to sokra's Apr 17, 2014 comment the problem of loading independently compiled bundles is now solved for me. I describe a slightly adapted solution for Webpack 2 here:
https://stackoverflow.com/questions/43163909/solution-load-independently-compiled-webpack-2-bundles-dynamically

**Comment by luisherranz** [comment]
That's really interesting @jri, thanks for sharing.

I ended up doing the same, but using comonjs for library output and systemjs to import the plugins. I wouldn't recommend Systemjs, it has given me some headaches so I guess your JSONP method is better.

One of the problems I found was the access to the common chunks, so libraries like react are not included on each plugin. I ended up using Webpack's DLL. The problem here is that each time you update or change this vendors bundle the chunk ids get messed up and you need to rebuild all your plugins arsenal. I use FixModuleIdAndChunkIdPlugin to solve this but it has giving me some troubles when combined with DedupePlugin. You also need to retrieve this vendors bundle and keep it in sync with everything.

After a while using this system I wonder if it's worth the effort or if it would be better to switch back to "one webpack" configuration and let the backend server retrieve all the plugins and build everything at once each time.

This is the code just in case anyone wants to take a look:
https://github.com/worona/worona-cdn/tree/master/packages

**Comment by jedwards1211** [comment]
@fresheneesz 
> I'm working on a project where we want the ability for users to develop javascript plugins. These plugins will be pretty arbitrary, and potentially as numerous as users. Maybe the plugins will be stored in a database, maybe in the filesystem, but regardless, the application code itself won't know about the location of the file at the bundle-time of the main application.

I think now you could use `DllPlugin`/`DllReferencePlugin` to accomplish what you're trying to do.  This same kind of thing has been on the back of my mind for some time...

**Comment by jedwards1211** [comment]
@luisherranz 
> The problem here is that each time you update or change this vendors bundle the chunk ids get messed up and you need to rebuild all your plugins arsenal.

Maybe `NamedModulesPlugin` would solve this problem?

**Comment by fresheneesz** [comment]
Thanks for the note @jedwards1211, I'm a bit out of that world at the moment, but I'll have to check it out when I get back in!
