### ISSUE TITLE
Extend Webpack Compilation Stages

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#11822]
## Feature request

Add more `processAssets` stages to process assets after they have been optimised (e.g. by terser)

**What is the expected behavior?**

Webpack allows plugins to hook into the asset generation using the [`processAssets` hook](
https://webpack.js.org/api/compilation-hooks/#processassets) of the compilation:

```js
compilation.hooks.processAssets.tap(
  {
    name: 'MyPlugin',
    stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
  },
  (assets) => {
    // code here
  }
);
```

Right now we have the following stages:

- `PROCESS_ASSETS_STAGE_ADDITIONAL` - Add additional assets to the compilation.
- `PROCESS_ASSETS_STAGE_PRE_PROCESS` - Basic preprocessing of the assets.
- `PROCESS_ASSETS_STAGE_DERIVED` - Derive new assets from the existing assets.
- `PROCESS_ASSETS_STAGE_ADDITIONS` - Add additional sections to the existing assets e.g. banner or initialization code.
- `PROCESS_ASSETS_STAGE_OPTIMIZE` - Optimize existing assets in a general way.
- `PROCESS_ASSETS_STAGE_OPTIMIZE_COUNT` - Optimize the count of existing assets, e.g. by merging them.
- `PROCESS_ASSETS_STAGE_OPTIMIZE_COMPATIBILITY` - Optimize the compatibility of existing assets, e.g. add polyfills or vendor prefixes.
- `PROCESS_ASSETS_STAGE_OPTIMIZE_SIZE` - Optimize the size of existing assets, e.g. by minimizing or omitting whitespace.
- `PROCESS_ASSETS_STAGE_SUMMARIZE` - Summarize the list of existing assets.
- `PROCESS_ASSETS_STAGE_DEV_TOOLING` - Add development tooling to the assets, e.g. by extracting a source map.
- `PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER` - Optimize the transfer of existing assets, e.g. by preparing a compressed (gzip) file as separate asset.
- `PROCESS_ASSETS_STAGE_ANALYSE` - Analyze the existing assets.
- `PROCESS_ASSETS_STAGE_REPORT` - Creating assets for the reporting purposes.

**What is motivation or use case for adding/changing the behavior?**

There are different use cases especially during the HTML generation which require access to the optimised assets:

1. Inlining CSS
2. Inlining Javascript
3. Sub resource Integrity Hashing (e.g. the webpack-subresource-integrity plugin from @jscheid https://github.com/waysact/webpack-subresource-integrity/issues/126)

However this means that tasks which needs to be done after the html generation would have to be moved after the html generation stage:

1. HTML Compression / Optimisation
2. WorkBox @jeffposnick (e.g. https://github.com/jantimon/html-webpack-plugin/issues/1522 )
3. Gzip Compression

**How should this be implemented in your opinion?**

To get a clean flow of the following stages without placeholders we would need to add additional stages.

![stages](https://user-images.githubusercontent.com/4113649/97170137-71ad2e00-178b-11eb-9363-b04560c9227d.png)

**Comment by evilebottnawi** [comment]
It is impossible, because terser can be replaces in any time on other plugin, I think you are a little mistaken how it works

**Comment by evilebottnawi** [comment]
> There are different use cases especially during the HTML generation which require access to the optimised assets:

> Inlining CSS
> Inlining Javascript
> Sub resource Integrity Hashing (e.g. the webpack-subresource-integrity plugin from @jscheid waysact/webpack-subresource-integrity#126)

It should be implemented on plugin side, we don't know how you process it

**Comment by evilebottnawi** [comment]
I have said many times that you should delete **minify** from the plugin :disappointed:

**Comment by jantimon** [comment]
@evilebottnawi I am not sure what you mean - this is also a step towards removing html minification from the html-webpack-plugin

Maybe you misunderstood what I meant by inlining css require access to the optimised assets during html generation.  
I don't want to add additional stages for css inlining. I only want the html generation to happen AFTER the css (or js) has been optimised so my plugin can inline the minified assets.

This feature request is about finding a way how we can ensure that plugins are executed in the correct order - I also discussed this topic with @sokra and we agreed the we will probably need to add additional stages

**Comment by evilebottnawi** [comment]
> I only want the html generation to happen AFTER the css (or js) has been optimised so my plugin can inline the minified assets.

How you minify js/css? Just for information

**Comment by jantimon** [comment]
I don't want to minify it by myself - I want to get the asset after all optimisations have been completed.  
This would allow me to get the minified result if another plugin minified it.

**Comment by evilebottnawi** [comment]
> I don't want to minify it by myself - I want to get the asset after all optimisations have been completed.
> This would allow me to get the minified result if another plugin minified it.

But how you want to minimize inlined code (`<script>`/`<style>`/`<svg>`/etc)?

**Comment by jantimon** [comment]
https://webpack.js.org/api/compilation-object/#getassets

```js
getAsset("main.js")
```

After the optimisation this would already give me the minified code so I don't need to minify it any further

**Comment by evilebottnawi** [comment]
> But we are moving a way from the original topic - this is not about minification it is about controlling the asset processing flow

Your problem is directly related to this problem

> getAsset("main.js")

It is how you get assets, not minified

**Comment by jantimon** [comment]
Why isn't the plugin which optimizes the javascript not using [`updateAsset`](https://webpack.js.org/api/compilation-object/#updateasset)?

**Comment by evilebottnawi** [comment]
Because update assets should not do it

**Comment by jantimon** [comment]
But terser-webpack-plugin is using `updateAsset`:
https://github.com/webpack-contrib/terser-webpack-plugin/blob/69419c2cf0927828e221061418f573f172724f5f/src/index.js#L488

**Comment by evilebottnawi** [comment]
I think you misunderstood my question. I mean how you want to minize content inside `style/script/etc` tags inside `HTML` file

**Comment by jantimon** [comment]
maybe all we need is

```js
Compilation.PROCESS_ASSETS_STAGE_GENERATE_META_ASSETS = 2600;
Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_META_ASSETS = 2700;
```

**Comment by jeffposnick** [comment]
How does the change in #11956 affect plugins that need to generate a manifest of some/all assets and then include that manifest inline within another asset, like `workbox-webpack-plugin` does?

When adding `webpack` v5 support, I initially had `workbox-webpack-plugin` run at the `PROCESS_ASSETS_STAGE_SUMMARIZE` stage, because that is explicitly called out as the stage to use for generating a service worker manifest:

https://github.com/webpack/webpack/blob/a16909c5fdb9efe9f1dd20226a1e7fc216160d1a/lib/Compilation.js#L3462-L3467

However, with the most recent changes that `html-webpack-plugin` has made, this stage appears to be too early, and someone from the community [opened a PR](https://github.com/GoogleChrome/workbox/pull/2671) to switch `workbox-webpack-plugin` to use the `PROCESS_ASSETS_STAGE_ANALYSE` stage. I don't know whether that's the "right" thing to do or not, as many things about the `webpack` v5 plugin API still appear to be in flux.

**Comment by jantimon** [comment]
Right now there is `processAssets` - I am not 100% sure if I understood @sokra correctly but https://github.com/webpack/webpack/pull/11956 will add a hook which is executed after `processAssets` which is also allowed to add assets like html or manifests

**Comment by jeffposnick** [comment]
FWIW, I'm going to go ahead and update `workbox-webpack-plugin` to use `PROCESS_ASSETS_STAGE_ANALYSE` instead of `PROCESS_ASSETS_STAGE_SUMMARIZE`, so that it can pick up the assets created by the latest `html-webpack-plugin` pre-release.

I understand that this might need to be updated once #11956 is merged, but I currently have now idea _how_ that would need to be updated, so I'm in a bit of a holding pattern until I hear more. In the meantime, we are eager to get initial `webpack` v5 support rolled out for `workbox-webpack-plugin`, even if we need to update the internals in a subsequent minor release.

**Comment by mrmgreen** [comment]
> #11956

Just FYI Looks like this has been merged now

**Comment by alexander-akait** [comment]
We need to add `addiontalAssets: true` to `processAssets` in compression-webpack-plugin

**Comment by alexander-akait** [comment]
It is in my roadmap on the next week

**Comment by jantimon** [comment]
I have the same problem like @jeffposnick - I don't understand how #11956 would help us here.

How can we run the html generation after:
  - all images are processed
  - all css and js are minimized

How can we run the workbox generation after:
  - all html files have been generated

**Comment by alexander-akait** [comment]
@jacjantimon problem still exist? I want to help your, I think you are missing something

**Comment by alexander-akait** [comment]
@jantimon You don't need `How can we run the html generation after`, additional assets will compressed even after your stage, can you provide link on the problem and steps to see it

**Comment by jantimon** [comment]
I guess for me it is fine for now :) unless you tell me that the current html-webpack-plugin stage usage doesn't work for you

**Comment by alexander-akait** [comment]
@jantimon So we can close this?

**Comment by alexander-akait** [comment]
Just for information, mini example of html plugin for tests https://github.com/webpack/webpack/blob/ed742e071b69c8cab6b60ed9d7ac1731a42aa02a/test/configCases/process-assets/html-plugin/webpack.config.js

**Comment by alexander-akait** [comment]
@jeffposnick Found bug with `InjectManifest` and `compression-webpack-plugin`, try to fix it tomorrow

**Comment by alexander-akait** [comment]
I don't have string opinion here, maybe @sokra says what is the best here

**Comment by sokra** [comment]
I wonder why this is a problem. compression-plugin should run pretty late in OPTIMIZE_TRANSFER stage. After that no modifications should happen to assets anyway. In which stage does InjectManifest run? Does compression-plugin run in the correct stage?

**Comment by sokra** [comment]
InjectManifest should use `PROCESS_ASSETS_STAGE_SUMMARIZE`

**Comment by sokra** [comment]
``` js
/**
 * Summarize the list of existing assets
 * e. g. creating an assets manifest of Service Workers.
 */
Compilation.PROCESS_ASSETS_STAGE_SUMMARIZE = 1000;


/**
 * Optimize the transfer of existing assets, e. g. by preparing a compressed (gzip) file as separate asset.
 */
Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER = 3000;
```

**Comment by jeffposnick** [comment]
Thanks for digging into this, @alexander-akait & @sokra! I've reopened https://github.com/GoogleChrome/workbox/issues/2667 to track this.

> If I understand correctly that there are two stages of work with custom sw.js:
> 
> - first generation (asset was emitted)
> - replace self.__WB_MANIFEST (asset was emitted again, but have compressed key in asset info, so compression plugin skip compressing)

You're correct in that there are two stages. The first stage happens via a child compilation, [kicked off via `compiler.hooks.make`](https://github.com/GoogleChrome/workbox/blob/3d02230f0e977eb1dc86c48f16ea4bcefdae12af/packages/workbox-webpack-plugin/src/inject-manifest.js#L151-L155).

The second stage, where `self.__WB_MANIFEST` is replaced, happens at... well, probably not the right time, in that it was originally `PROCESS_ASSETS_STAGE_SUMMARIZE`, but I [switched to `PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER - 10`](https://github.com/GoogleChrome/workbox/pull/2675) in order to be compatible with assets created by `html-webpack-plugin` in its alpha releases. There's a comment in the source that that logic should change once this issue is resolved, so if this issue is resolved, it's a good time to change it 😄

That being said, I still am not sure how the "additional assets" functionality is supposed to work, so if you all have specific suggestions as to how to remediate `InjectManifest`, I'm all ears.

(Chances are the same change will need to be made to [`GenerateSW`](https://github.com/GoogleChrome/workbox/blob/3d02230f0e977eb1dc86c48f16ea4bcefdae12af/packages/workbox-webpack-plugin/src/generate-sw.js), which is a separate plugin that creates a new asset containing a service worker with a precache manifest, instead of performing a child compilation.)

**Comment by sokra** [comment]
Ah I think I understand the issue now. This is related to InjectManifest running a child compiler to generate the SW. The compression plugin already generate a .gz file in the child compiler. And modifies the original asset after that.

@alexander-akait If this is the issue: The compression plugin should compress assets again in the main compilation. It shouldn't set a `compressed` flag similar to the `minimized` flag in terser-webpack-plugin. It's doesn't modify the asset so this is not needed. It should set `related.compressed` instead. Skipping compression again is not needed as this is not expensive due to caching (if unmodified).

**Comment by clshortfuse** [comment]
I'm having this issue with a deploy system. Basically after everything is completed and minified, I want to upload to Amazon S3. I had it working before (webpack v4), but the new changes make this... difficult. 

I write my manifest file with `compilation.hooks.additionalAssets` and that works fine. I add the new manifest file with `compilation.assets[manifest] = {source, size}`. That works fine and deploys fine.

But my JS assets are all unminified at the time I hook into it. I'm not sure where I'm supposed to hook. I've been using the `PROCESS_ASSETS_STAGE_REPORT`, fyi.
