### ISSUE TITLE
webpack5 hmr cannot work

### ISSUE THREAD

**Issue by keaderzyp** [webpack/webpack#11833]
我通过@webpack-cli/serve启动本地服务运行项目，并且配置了--hot
更新代码的时候只有控制台有自动更新的日志出现，浏览器页面不自动更新
"webpack": "^5.1.3",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0",
只有切换到webapck4.44.*的版本hmr才能正常工作

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by baixiaoyu2997** [comment]
same issue

**Comment by baixiaoyu2997** [comment]
我找到了相关问题，我把tagert设置为web就可以了。
https://github.com/webpack/webpack-dev-server/issues/2758
