### ISSUE TITLE
ensure() behavior discussion.

### ISSUE THREAD

**Issue by neekey** [webpack/webpack#1188]
Hi, I'm digging into the ensure() behavior about how different relations of entries and ensured-submodules will affect the build result and the network resource loading. Below is a situation that ensure() doesn't behave as I expected:

We have 2 entries A.js and D.js and 2 submodule c.js and d.js, and their relation is:

- c require d
- A require d, A ensure c
- B ensure c

After building this assets, we will get a list of bundles:

- A.bundle.js ( combined with A.js and d.js )
- 1.1.js ( will be loaded by A.js, only contain c.js )
- B.bundle.js ( only contain B.js )
- 2.2.js ( will be loaded by B.js, contain c.js and d.js )

So if we put either B.bundle.js or A.bundle.js into out page, it will work as expected and will load their own ensure scripts ( A.bundle -> 1.1 and  B.bundle -> 2.2 )

What if we put one entry into page and then execute another later ( after the former process is totally finished ) ? So I did a little test:

If we put B.bundle.js into page first, then B will be loaded, and then dynamically load 2.2.js which makes submodule c and d into the memory and executed. After that we put A.bundle.js into page, obviously module d will be redundant once, which is expected, and since module c has already been loaded via 2.2.js, there's no need to load 1.1.js, and webpack just works well as I expected.

But what If we put A.bundle.js into page first? The dependence is a little bit of different but I thought it will quite the same: A.bundle.js will bring d and c into page, and when turn to B.bundle.js, there's no need to load 2.2.js since all its dependencies is ready right in the memory. But the test fails as 2.2.js is still loaded.

Why? So is this behavior expected or do I miss something?

**Comment by sokra** [comment]
In your example A.bundle.js and B.bundle.js are entry chunks. Each entry chunk include a webpack runtime, which contains an (independent) module store. This way each entry chunk operate independent from the other. Each one stores the loaded module/chunks/module instances/etc. This is propably not what you want to do.

Before trying to load multiple entry points in a page, check if the second entry point is really an entry point or should be better loaded via Code Splitting or via CommonsChunkPlugin. (95% propability)

If you really need to load multiple entry points in one page you need to ensure that only one runtime is loaded. Because you want to all modules to be in a common scope. Best to ensure this is to use the CommonsChunkPlugin to extract a commons chunk (may be empty) which is the new root and the only chunk which contains the webpack runtime.
