### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by ttjimsen** [webpack/webpack#11898]
To install them, you can run: npm install --save webpack/lib/web/FetchCompileAsyncWasmPlugin webpack/lib/web/FetchCompileWasmPlugin

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
