### ISSUE TITLE
Problem exporting project as a dependencies

### ISSUE THREAD

**Issue by iBobo5** [webpack/webpack#11978]
Hello everyone,
I'm trying to build my custom frontend library using webpack.
Here my core project repository: https://github.com/iBobo5/MBCore.git

I've choose 2 different webpack config files to use npm start and try live my components and to use npm run build to export my project as a .tgz

After that I've create myapp project with create-react-app and I've installed core package from .tgz but if I try to import Pippo component from core into the new project it can't be found.

What I'm doing wrong?
Thanks

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use gitter or stackoverflow or `create-react-app` repo for questions
