### ISSUE TITLE
WEBPACK 5:Importing Routes from remote and then using in host gives error:Error: Invariant failed: You should not use <Route> outside a <Router>

### ISSUE THREAD

**Issue by ajayjaggi** [webpack/webpack#12004]
REMOTE FILE FOR EXPORTING THE ROUTES:
![Screen Shot 2020-11-16 at 11 18 08 PM](https://user-images.githubusercontent.com/46561425/99288707-04f4f300-2862-11eb-94f8-3a426a1c5233.png)

HOST FILE WHERE I AM USING THESE ROUTES
![Screen Shot 2020-11-16 at 11 18 36 PM](https://user-images.githubusercontent.com/46561425/99288854-35d52800-2862-11eb-9bb1-e4408188afa6.png)

**Comment by ajayjaggi** [comment]
Error: Invariant failed: You should not use <Route> outside a <Router>
This is the error i get

**Comment by ajayjaggi** [comment]
Pls suggest how to resolve this

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
