### ISSUE TITLE
undefined && require('mockjs') will pack mockjs

### ISSUE THREAD

**Issue by xiecz123** [webpack/webpack#12063]
# Bug report

**What is the current behavior?**
undefined && require('mockjs') will pack mockjs

**If the current behavior is a bug, please provide the steps to reproduce.**
step0: mkdir webpack-demo && cd webpack-demo
step1: npm init -y
step2: npm i webpack webpack-cli mockjs -D
step3: mkdir src && cd src && touch index.js
step4: type undefined && require('mockjs')
step5: cd ..
step6: npx webpack

**What is the expected behavior?**
"mockjs" will not be packaged

**Other relevant information:**
webpack version:  5.7.0
Node.js version: 12.16.1
Operating System: macOS Catalina
Additional tools:

**Comment by evilebottnawi** [comment]
Try to use `null` or `false`

**Comment by xiecz123** [comment]
> Try to use `null` or `false`

use 'null' or 'false' not be packaged, pls tell me why use 'undefined' will be packaged

**Comment by evilebottnawi** [comment]
@xiecz123 because evaluator doesn't support `undefined`, it is feature

**Comment by xiecz123** [comment]
@evilebottnawi Thank you for your answer

**Comment by xiecz123** [comment]
@evilebottnawi Thank you for your answer

**Comment by evilebottnawi** [comment]
Let's keep open, I think we should improve this

**Comment by rjgotten** [comment]
FWIW I have some code that relies on this type of behavior with a dynamic import to ensure a few modules that produces separate files as side effects (e.g. MiniCSSExtract stylesheets) _are_ built, but aren't actually imported or run in production builds since there I need only the compiled CSS and don't need the JS hookups that also facilitate hot reloading.

I can imagine I'm not the _only_ one using this quirk to facilitate such a scenario, so if the behavior here is changed, keep in mind to have another way to realize the same pattern, please.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Still valid, will be great to support `undefined`

**Comment by vankop** [comment]
@sokra should we support `undefined` also?

**Comment by alexander-akait** [comment]
Yes, because it will be `false`, one note - in IE you can override `undefined` on any variable, but I feel it like a bug, we can add note about this  to docs

**Comment by sokra** [comment]
Yep, sounds good to add
