### ISSUE TITLE
If path name to index.template.html contains another file extension, loader will fail

### ISSUE THREAD

**Issue by H-a-w-k** [webpack/webpack#12192]
# Bug report

**What is the current behavior?**

If the folder of the source code contains file extension names, such as .js, a syntax error will occur when loading index.template.html. It will be interpreted as javascript.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Create a folder named not-allowed-with.js-in-name
- Enter folder
- Clone a repo and try to build

**What is the expected behavior?**

index.template.html will not get syntax error on <!Doctype

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Do not ignore section - **If the current behavior is a bug, please provide the steps to reproduce.**, I will reopen it after you fix it

**Comment by alexander-akait** [comment]
Please create reproducible test repo, I can't reproduce and I will reopen it
