### ISSUE TITLE
Hot Module Replacement without webpack-dev-server

### ISSUE THREAD

**Issue by nilssolanki** [webpack/webpack#1220]
Is there currently a way to use hot module replacement with a different backend than `webpack-dev-server`? We use a bunch of different backends (django, node, ...) for our projects, so I was wondering if there is either a way to handle the streaming of the modified module through a utility like browser-sync or another backend-independent way?

**Comment by sokra** [comment]
yes, HMR is a webpack feature not a webpack-dev-server feature.
webpack-dev-server just offer a way to notify the browser that an update is available.

**Comment by nilssolanki** [comment]
Do you know of any good examples that illustrate how that would work (in particular, how webpack would notify the backend when a module is hot)?

**Comment by sokra** [comment]
> how webpack would notify the backend when a module is hot

That would be up to you. i. e. you can poll with `webpack/hot/poll?1000` or use a signal with `webpack/hot/signal`. Or take one of these as base for your own implementation (i. e. using one of your applications channel)

**Comment by nilssolanki** [comment]
I am obviously out of my depth here. So far, I only added HMR to my webpack config:

    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ],

How do I expose the `/webpack` api?

**Comment by sokra** [comment]
http://webpack.github.io/docs/hot-module-replacement-with-webpack.html#what-is-needed-to-use-it

**Comment by faceyspacey** [comment]
@sokra server side if you're using `webpack --watch` how can you get notified when the code is initially built so you can run it? Currently in my package.json scripts I call webpack twice

- once to watch
- a second time to build it, after which I execute the built code in node

The problem with this is it's finnicky. If you watch the same config too long before you build it, HMR won't connect to the other webpack instance. Often I'll just watch separately so that I don't exit early and have a node process in the background like this: `npm run watch & npm run build && node dist/main.js`

So it would be nice to be able to be able to use the `--watch` param while knowing when the initial build is done so you can execute the build with node.

**Comment by mehulmpt** [comment]
Has anyone figured it out yet? Using HMR without dev server? I'm stuck at the issues @faceyspacey mentioned.

**Comment by FabianPiconeDev** [comment]
http://webpack.github.io/docs/hot-module-replacement-with-webpack.html#what-is-needed-to-use-it is broken, please provide a working doc.

**Comment by kpettinga** [comment]
I'm also looking for a way to implement HMR without webpack-dev-server. Any examples out there??

**Comment by rflmyk** [comment]
Me too.  +1

**Comment by Falieson** [comment]
https://github.com/webpack-contrib/webpack-hot-middleware <== how to get HMR working in Express

**Comment by RussCoder** [comment]
I would recommend to use parcel bundler - in a watch mode it creates a file on a disk, as if a whole project was built, but the file contains some additional code which automatically enables HMR. As I have understood, parcel actually starts a kind of server, but just for HMR sockets. 

The parcel's watch mode is awesome, because it allows you to have the same reference in your HTML (the same URL in the script's src attribute) file both for production and for development, since in the latter case the output bundle is just replaced with a special dev bundle with inbuilt HMR support and nothing changed in terms of references and a file structure of your  project.

And of course, in case of React parcel works out of the box with no config required.

**Comment by RussCoder** [comment]
I would recommend to use the parcel bundler - in a watch mode it creates a file on a disk, as if a whole project was built, but the file contains some additional code which automatically enables HMR. As I have understood, parcel actually starts a kind of server, but just for HMR sockets. 

The parcel's watch mode is awesome, because it allows you to have the same reference in your HTML (the same URL in the script's src attribute) file both for production and for development, since in the latter case the output bundle is just replaced with a special dev bundle with inbuilt HMR support and nothing changed in terms of references and a file structure of your  project.

And of course, in case of React parcel works out of the box with no config required.

**Comment by nickelghost** [comment]
I managed to solve this issue by using a reverse proxy on my backend. You still run a webpack server, just proxy it on the public folder URL if in dev mode. This is my quick and dirty example (echo framework for golang):
```go
if os.Getenv("APP_WEBPACK_FORWARD") == "true" {
	g := e.Group("/admin")
	webpackURL, _ := url.Parse("http://localhost:3001")
	g.Use(middleware.Proxy(middleware.NewRandomBalancer(
		[]*middleware.ProxyTarget{{URL: webpackURL}},
	)))
}
```
HMR just works.
