### ISSUE TITLE
peerDependencies behavior change as of npm@3

### ISSUE THREAD

**Issue by iarna** [webpack/webpack#1221]
So, as you may already know, with npm@3 (on the registry now, currently in beta), peerDependencies are no longer installed for you. They act as assertions, warning you if you don't meet their requirements, but they do not break the install nor do they trigger installation of the thing mentioned.

This means that `npm install -g webpack` will not result in a working install out of the box as `node-libs-browser` won't be installed.

I'd like to work with you all to figure out what the best solution is for this. My first reaction would be to just make `node-libs-browser` a regular dependency. Is there a reason not to do that?

**Comment by IngwiePhoenix** [comment]
You probably read the npm@3 changelog, like I did :)

In there, they actually do suggest turning most peer dependencies into normal dependencies, since npm@3 flattens the install tree automatically. This will avoid duplicated installs - and, the module will be available at the best-possible version. If two modules depend on a whole different version, then their required version will be installed in a submodule tree, like the current NPM does.

Therefore: Add peerDependencies as normal dependencies. :)

My cent for that, at least. o.o

**Comment by iarna** [comment]
I wrote the npm@3 changelog 😉

**Comment by IngwiePhoenix** [comment]
O.O! O-oh…well…i didn’t know. Sorry!

It’s well written. :)

**Comment by SpaceK33z** [comment]
This can be closed now, as #1197 is merged.
