### ISSUE TITLE
`Watchpack Error (stats): Error: EACCES: permission denied` since upgrading to v5

### ISSUE THREAD

**Issue by hisuwh** [webpack/webpack#12290]
# Bug report

Since upgrading webpack to the latest version I'm getting the following errors in my output window when watching:

```
Watchpack Error (stats): Error: EACCES: permission denied, lstat '/mnt/c/pagefile.sys'
Watchpack Error (stats): Error: EACCES: permission denied, lstat '/mnt/c/pagefile.sys'
Watchpack Error (stats): Error: EACCES: permission denied, lstat '/mnt/c/pagefile.sys'
```

Node: `12.16.3`
webpack: `5.11.1`
webpack-cli: `4.3.0`
OS: windows 10

Running in WSL

**What is the expected behavior?**

I would not expect to see these errors in the console?  It looks as if webpack is trying to watch system files which it shouldn't be doing.  I wouldn't expect it to be watching files outside my project directory.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please do not ignore how we can reproduce this, I can't help you without that information

**Comment by hisuwh** [comment]
@alexander-akait I didn't ignore your template.  Thanks for reading my issue and taking time to understand it...

To reproduce run webpack with the above versions in wsl

**Comment by alexander-akait** [comment]
Do you think I didn't? I asked for reproducible repo because I was unable to reproduce

> I didn't ignore your template.

Ignore, I don't see `**If the current behavior is a bug, please provide the steps to reproduce.**`

Could you handle such an issue in my place without being able to reproduce something? Respect time of other developers, with reproducible test repo or steps to reproduce you would have received an answer already, and nobody lose the time, that is why it is so important to fill in all the fields

**Comment by hisuwh** [comment]
> and nobody lose the time

Thats not true - I would lose the time setting up the reproducible repo.  But I appreciate there is not a lot to go on here. I guess didn't include steps to reproduce because this tool only has one step, `webpack` and this particular error does not seem like it would be affected by my config.  Not sure what else to give you other than my entire setup which I'm not sure is necessary.

> Could you handle such an issue in my place without being able to reproduce something.

No, but I get similarly vague issues raised by clients all day long.  I just have non-technical clients so I can't ask them to reproduce things to the same extent.  I have to ask probing questions and do a little digging.  Sometimes a seemingly erroneous error I instantly know what it might because I'm familiar with the codebase.

In the sea of open source code its hard to tell what's maintained by volunteers and what is backed by companies - in the latter case there should be the resources to investigate issues properly.  I appreciate a lot of times it's volunteers giving up their time which I appreciate.  But what I don't appreciate is my issue being seemingly dismissed out of hand because I missed something off your template.  

> I asked for reproducible repo because I was unable to reproduce

Why not say this in the first instance and avoid all the conflict?

**Comment by alexander-akait** [comment]
Feel free to ping me when reproducible test repo will be created

> Why not say this in the first instance and avoid all the conflict?

I said about, you don't fill out all fields in the issue template, please look at https://github.com/webpack/webpack/issues/new?template=Bug_report.md template and look on your
