### ISSUE TITLE
When paths get long...

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1235]
I am contributing to a project which has a very nested structure. To the point, where I had to copy-paste this:

```javascript
var utils = require('../../../../js/utils');
```

And I am not even done on there. Currently I am converting the project from AMD `define()` to `require()`, so it runs smoother with commonly used systems. However, the long paths are an issue.

In my own project that I had once used the module aproach from here: https://gist.github.com/branneman/8048520

... but WebPack won't work with this. Due to the paths getting concateinated (`require(path + file)`), WebPack is going to do anything but the required result. I.e. it might not resolve correctly.

That is why I wanted to ask, if there is a way to do "project local" requires. So, that instead of many `../../../`s, one could "just" require fromt he top of their module, like when using the `app-modules-path`.

Is this possible or can it be implemented?

Kind regards, Ingwie.

**Comment by altano** [comment]
There are a lot of ways of doing this.  If, for example, you have a specific modules directory that isn't node_modules, you can add it to resolve.modulesDirectories and require() will resolve it.

If you just want to be able to resolve from the root of your directory always, so you can specify paths relative to the root (to facilitate refactoring and moving files around more easily), then you can specify resolve.root.

The third option, resolve.fallback, is just what it sounds like: it's the last place webpack looks to try and require() something that it couldn't otherwise find.

It sounds like in your case you want to specify your project root, so let's say you have:

```
test-project
`-- src
    |-- a.js
    |-- b.js
    `-- inner
        `-- even
            `-- more
                `-- nested
                    `-- c.js
```

If you specify in the webpack config:

```javascript
{
    ...
    resolve = {
        root: path.resolve(__dirname, 'src')
    },
    ...
}
```

then in c.js, instead of having `require('../../../../a')` you can just specify `require('a')`.  This is short and sweet but can lead to ambiguity if any of your filenames are the same name as any node modules.  Here's what I would recommend:

1. Structure your application so that you have 

```
|-- src
|   |-- all_your_scripts_under_this_directory.js
|   `-- inner
|       `-- even
|           `-- more
                `-- nested
                    `-- c.js
`-- webpack.config.js
```

2. In your webpack.config.js, specify the root like so:

```
module.exports = {
    ....
    resolve: {
        root: __dirname  // <======== this is key
    },
    ....
};
```

Now from any file in the src directory, you can reference any other file unambiguously from the src dir, e.g. in the example above, from c.js you can specify `require('src/a')`

**Comment by bebraw** [comment]
@IngwiePhoenix Safe to close?

**Comment by IngwiePhoenix** [comment]
Kinda had to hack around it with resolve aliases and a symlink inside node_modules. Not super happy with it but it works.

Yes, closeable.
