### ISSUE TITLE
how to define a global variable?

### ISSUE THREAD

**Issue by fridaymeng** [webpack/webpack#1236]
such as title.

**Comment by andreypopp** [comment]
Do you mean you want to inject some global vars via webpack? http://webpack.github.io/docs/list-of-plugins.html#defineplugin there's `DefinePlugin` for that.

That's seems like a question rather than issue with webpack. It is advised to use [StackOverflow](http://stackoverflow.com/tags/webpack) for that instead.

**Comment by fridaymeng** [comment]
got it ,thanks.

**Comment by shama** [comment]
@sokra Looks like this issue can be closed now.

**Comment by avesus** [comment]
`DefinePlugin` doesn't define a global variable. It tries to replace all the occurrences of the variable "name". How to declare a global variable without loading a file in Webpack 2?

**Comment by avesus** [comment]
Just use externals instead if you need to create a global variable.
Example:

```
externals: {
  'webpackVariables': `{
     serverUrl: '${ env.server }',
     cordovaBuild: '${ env.cordova }',
   }`,
},
```

Then use it as `const webpackVariables = require('webpackVariables');`

**Comment by mqklin** [comment]
@avesus thank you very much

**Comment by dxcqcv** [comment]
How do I update global `webpackVariables` in one module then other modules auto update like normal global variables in pure js ? help @avesus

**Comment by davidcalhoun** [comment]
@avesus Your comment is a gateway drug that opened up a whole realm of solutions for me.  Thanks!

**Comment by AlexLeung** [comment]
@avesus I don't think this works anymore. I get an error 
```
Error: Cannot find module '{serverUrl: 'someurl'}'
```

**Comment by ldonis** [comment]
@AlexLeung  you can define a constant through plugins interface
```js
plugins: [
            new webpack.DefinePlugin({
                some_global_constant: "some_global_value"
            })
        ]
```

remember to import webpack inside webpack.config.js
`var webpack = require("webpack")`

**Comment by AlexLeung** [comment]
Yea I ended up getting the plugin to work. I’m building an alternative to webpack-dev-server which takes the url as an option rather than as a string added to the entry file value. The url is injected into the client using the DefinePlugin.

The plugin allows for HMR in node & web if anyone is interested.

**Comment by aalauno** [comment]
I had similar problem..
I wanted to use some variable from **.env** file as global.
Eventually I could define it using **JSON.stringify()**

It's also related to your custom values.

```
// here is webpack.config.js filie
require('dotenv').config();

new webpack.DefinePlugin({
    'process.env.HOST': JSON.stringify(process.env.HOST)
})
```

then, I could use process.env.HOST variable as global

**Comment by aalauno** [comment]
I had similar problem..
I wanted to use some variable from **.env** file as global.
Eventually I could define it using **JSON.stringify()**

It's also related to your custom values.

```
// here is webpack.config.js filie
require('dotenv').config();

new webpack.DefinePlugin({
    'process.env.HOST': JSON.stringify(process.env.HOST),
    'process.CUSTOM': JSON.stringify({ a: 0, b: [1, 2, 3] }), // just an example
});
```

then, I could use process.env.HOST variable as global
also you can use process.CUSTOM as object

**Comment by aalauno** [comment]
I had similar problem..
I wanted to use some variable from **.env** file as global.
Eventually I could define it using **JSON.stringify()**

It's also related to your custom values.

```
// here is webpack.config.js file
require('dotenv').config();

...
plugins: [
    new webpack.DefinePlugin({
        'process.env.HOST': JSON.stringify(process.env.HOST),
        'process.CUSTOM': JSON.stringify({ a: 0, b: [1, 2, 3] }), // just an example
    }),
]
...
```

then, I could use process.env.HOST variable as global
also you can use process.CUSTOM as object

**Comment by matthias-ccri** [comment]
DefinePlugin doesn't actually define anything. What it does is replace variables that exist in your bundle code. If the variable doesn't exist in your code, it will do nothing. So it doesn't create global variables.

In order to create a global variable, write it in your code:
```js
window.MyGlobal = MY_GLOBAL; 
```

And use DefinePlugin to replace `MY_GLOBAL` with some code:
```js
new webpack.DefinePlugin({
    'MY_GLOBAL': `'foo'`,
    // or
    'MY_GLOBAL': `Math.random()`,
}),
```

Then your output JS will be like this:
```js
window.MyGlobal = 'foo';
// or
window.MyGlobal = Math.random(); 
```

But `MY_GLOBAL` will never actually exist at runtime, because it is never defined. DefinePlugin has a misleading name.
