### ISSUE TITLE
types declaration on webpack 5

### ISSUE THREAD

**Issue by WanderWang** [webpack/webpack#12405]
webpack 5 contains ```types.d.ts``` , but seems that missing lot of declaration from ```@types/webpack@4.x.x``` 

for example , how to implement a custom Loader with declaration ?

```@types/webpack@4.x.x``` define ```webpack.loader.Loader``` but webpack 5 have no similiar declaration

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

`@types/webpack` have types for webpack@4, but built-in types for webpack@5, they are different

Close in favor https://github.com/webpack/webpack/issues/11630, please describe in https://github.com/webpack/webpack/issues/11630 what is missing for your and we will answer you, no need duplicate
