### ISSUE TITLE
How to add webpack to an existing HTML project and package it?

### ISSUE THREAD

**Issue by mofengfs** [webpack/webpack#12438]
I didn't pay much attention to webpack before, but now I encountered an html project that had to be packaged.
Since the official document only introduces configuration examples, it is difficult to have a sense of substitution. I carefully read 1/3 of the official document and took notes. I still have no idea about packaging existing projects.

I configured webpack myself, but I can only package the contents of the leaked files:

![image](https://user-images.githubusercontent.com/16655229/104838405-b44b5600-58f5-11eb-82fe-1ce5181ea391.png)
![image](https://user-images.githubusercontent.com/16655229/104838408-ba413700-58f5-11eb-80b2-48e0ca33c49a.png)

How does it package complex project structure dependencies?
For example, I have a project with the following directory structure:

![image](https://user-images.githubusercontent.com/16655229/104838425-d349e800-58f5-11eb-9897-b146dbe4eeff.png)

**Comment by akgupta0777** [comment]
you need different loaders to package your images, CSS, fonts and stuff. Read the docs for more info.

**Comment by alexander-akait** [comment]
Answer above, and please prefer to use discussions or stackoverflow for questions,  you can copy files using `copy-webpack-plugin`, maybe you can setup the right `publicPath`, please provide configuration, otherwise it is hard to say what is wrong, closed because it is question without enough information (it doesn't mean that we don't want to help you), feel free to feedback and we will help
