### ISSUE TITLE
webpack5 hook done assets only size() is supported

### ISSUE THREAD

**Issue by SherrybabyOne** [webpack/webpack#12486]
# Bug report

**What is the current behavior?**
I used to write a plug-in in webpack 4, but now I report an error when upgrading webpack 5.

I used to use the absolute address of the product in webpack hook's done, but I found that this attribute was deleted in webpack 5, Stats.compilation.assets To provide the file name of the assets without providing any other information. What is the purpose of this change.

If I need the absolute address of the assets, what should I do in webpack 5

**If the current behavior is a bug, please provide the steps to reproduce.**
```
compiler.hooks.done.tapAsync('CheckES6Plugin', async (stats: Stats, callback) => {
      const jsFiles = Object.keys(stats.compilation.assets)
        .map(item => stats.compilation.assets[item].source());
});
```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.13.0
Node.js version: 12.20.0
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Yes, that's intentional. At this point assets are only on disk and no longer in memory. Either read it back from disk or do you checks earlier in the process.

`Compilation.hooks.processAssets` is a good option. Make sure to choose a appropriate stage e. g. `Compilation.PROCESS_ASSETS_STAGE_ANALYSE`.

**Comment by SherrybabyOne** [comment]
Oh, yes, I see. Thank you very much
