### ISSUE TITLE
Way to recognize when initial compilation with lazy plugin has finished.

### ISSUE THREAD

**Issue by JonnyBurger** [webpack/webpack#12564]
## Feature request

I have tried the new lazy compilation option and it's awesome!
I am creating a Create-React-App type of app using webpack-dev-middleware and one thing I noticed is that Webpack marks itself as ready (using `done` hook) before the entry point is compiled. This means if I cold start my app and immediately open the browser, I get an empty white page.

It would be nice to have a way to figure out when the initial compilation is done so only then we can open the browser for better DX. Does something like this in form of a hook already exist?

**What is the expected behavior?**
Webpack only changing to a ready state once the webapp can be visited

**What is motivation or use case for adding/changing the behavior?**
Better developer experience

**How should this be implemented in your opinion?**
For example using a hook, or changing when when Webpack calls the 'done' hook. The PR #12553 which could disable lazy importing for certain files also looks promising, because then maybe I could disable it for my entry files.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
I don't think you need hook here, you can do it on tool/application side

**Comment by JonnyBurger** [comment]
@alexander-akait Can you tell me how I could implement it on the application side?

**Comment by alexander-akait** [comment]
You have `__webpack_hash__` so you can check it was changed or not

**Comment by sokra** [comment]
There are multiple things that you could do about that:

If your application has only a single entrypoint it make sense to disable lazy compilation for entrypoints, because there is no benefit in only compiling it when visited (since you can only visit this entrypoint). We should make this the default when there is only a single entrypoint.

Above thing will also give the the experience that the browser only opens when the page is ready.

Lazy Compilation has the option to create a custom User Interface when lazy compiling via the `experiments.lazyCompilation.client` option. This allows to disable e. g. a spinner and a message in the browser.

**Comment by JonnyBurger** [comment]
Thanks a lot! With the new webpack version that came out today, I can do the following:

```console
	experiments: {
		lazyCompilation: {
			entries: false,
		},
	}
```

and it works perfectly! 🥳 

Thanks a lot for the swift help and my issue is resolved!
