### ISSUE TITLE
Are you open to a sideEffects comment directive?

### ISSUE THREAD

**Issue by evanw** [webpack/webpack#12595]
## Feature request

Hello. I'm the author of [esbuild](https://github.com/evanw/esbuild), another JavaScript bundler. Webpack currently has [this feature](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) where you can write `"sideEffects": false` in your `package.json` file and all files in that package are considered to be side-effect free (i.e. imports of those files can be removed if none of the imported names are used). There is also a more advanced form where you can write `"sideEffects": [...]` to explicitly list out the files that have side effects. All files not in that list are considered to be side-effect free by omission.

I'm wondering if you would be open to another form where a comment in the file can cause Webpack to consider the file to be side-effect free. One proposal would be to use `// @sideEffects false`.

**What is the expected behavior?**

If a JavaScript file contains a comment with contents that match `/@sideEffects\s+false\b/`, the file is considered to have no side effects for the purpose of tree shaking. This is the same behavior as if the enclosing `package.json` file had a `"sideEffects": [...]` entry that listed all files in the package except the files containing these comments.

**What is motivation or use case for adding/changing the behavior?**

My reasons:

1. The current `"sideEffects": [...]` form is very error-prone. It's easy to shoot yourself in the foot by setting it up once, forgetting that it's there, and then adding more files to your package that do have side effects. This is an issue that affects real projects. https://github.com/tensorflow/tfjs/issues/4248 is one example of this happening. In my opinion it would have been better for the array in `package.json` to be opt-in instead of opt-out, but that ship has sailed already.

2. It's also easy to shoot yourself in the foot by adding side effects to an existing file because there's nothing in the file that tells you that the code in the file is being treated in a special way, and it's easy to forget about this field in `package.json` (especially because the name of the files with special behavior are missing from the array). I imagine this is extra challenging for packages being worked on by a team of people where someone is making changes long after the decision was made to configure that field in `package.json`.

3. This comment directive would be useful for authors of compile-to-JS languages. For example, one of the authors of [ReScript](https://github.com/rescript-lang) (a.k.a. BuckleScript/Reason) contacted me about adding a comment directive like this to esbuild: https://github.com/evanw/esbuild/issues/754. My response was that I didn't want to create a new esbuild-specific annotation and fragment the ecosystem. That's one of the reasons why I'm reaching out to you about this, to see if another bundler is also interested. I think Webpack is the original creator of the `sideEffects` field?

    Their rationale was that it's easy for their compiler to determine if the code in the file has side effects or not and that it's natural to generate a comment in the file that describes the properties of the file, but that it's unnatural for their compiler to modify the user's `package.json` file. I agree with that, especially since adding `"sideEffects": [...]` with an array containing every file in the package except cross-compiled ReScript files would be very error-prone for the user since a) they won't be aware of that change at all and b) it will surely lead to correctness issues with their package for any user-created files containing side effects.

**How should this be implemented in your opinion?**

Not sure what goes in this section, sorry! I guess I could say that I think it should be implemented inside Webpack itself instead of as an external plugin if it is to be a convention that works across bundlers.

**Are you willing to work on this yourself?**

Sure, I could give it a shot.

**Comment by sokra** [comment]
There was some discussion about a new `/*#__PURE__*/` a while ago in the terser repo.

For me one takeaway was: Avoid comments and use something else instead that's part of the AST.
The problem with comments is that they might be moved around in weird ways by tools, and they are difficult to match to parts of the AST.

A `// @sideEffects false` comment would have similar problems. It's not clear to which part of the code it applies to. What happens if the file is concatenated with other files and the tool that does that doesn't know about this comment. e. g. assuming rollup doesn't support it and bundles a module containing this comment into a bundle. Now the whole bundle is (incorrectly) flagged as side effect free.

In the discussion about PURE I proposed this syntax instead:

```js
// apply PURE to an expression:
("#__PURE__", expression)

// apply PURE to a statement:
("#__PURE__");
statement;

// both also support multiple annotations:
("#__PURE__", "#__MAGIC__", expression)
("#__PURE__", "#__MAGIC__");
statement;


// examples:

var Component = ("#__PURE__", withSomething(MyComponent));

("#__PURE__")
import xyz from "xyz";
```

I really like the expression-level syntax. The statement-level syntax has some weak points.

* Existing minimizers will remove the syntax when they don't understand it.
* It's part of the AST, so it can easily processed
* Multiple annotations are supported
* Can be easily extended to more annotations
* string can be anything simple to complex

So technically a file can be considered as side-effect-free if all statements and all imports are PURE. So this might be enough, but a bit much work if the file contains many statements. Grouping would be possible via BlockStatements (`("#__PURE__") { ... }`), but that doesn't work well for `export ...` since it must be on top level.

So a kind of syntax which affects a list of statements would be nice to have.
Maybe: `("#__REGION__", "#__PURE__");` to `("#__ENDREGION__");`

``` js
("#__REGION__", "#__PURE__");
import xyz from "xyz";

console.log("test");

const abc = calc();

export { abc }
("#__ENDREGION__");
```

So `"#__REGION__"` is special and applies a bunch of annotations to a region of statements. `("#__ENDREGION__");` MUST follow, otherwise this is an error (to prevent forgetting it). And it must be in the same parent node in AST.

Technically a `("#__FILE__", "#__PURE__");` is also possible, but I prefer to not do this due to problems with concatenation resp. bundling.

**Comment by sokra** [comment]
The `#__xxx__` content syntax is up to discussion. Currently it's just the format that the comment syntax uses. But as the change or conflicts is much lower as with comments we could choose a more readable syntax.

One idea could be to align this with the decorators proposal. It would be a kind of build-time decorator.

``` js
("@pure");
import xyz from "xyz";

("@pure", expression)

("@region", "@pure");

("@endregion");
```

On the other hand this could be confusing, since the locations where these annotations can be placed are very different from decorators.

**Comment by bobzhang** [comment]
my 2 cents, in general such attributes should be applied mechanically instead of filled by humans.
- it is easy to get it wrong, we should not trust programmers on this
- it is easy to get it out of sync
So I suggest we design the syntax easier for machines instead of by human

**Comment by evanw** [comment]
> What happens if the file is concatenated with other files and the tool that does that doesn't know about this comment. e. g. assuming rollup doesn't support it and bundles a module containing this comment into a bundle. Now the whole bundle is (incorrectly) flagged as side effect free.

That's an excellent point. This wouldn't be a problem with esbuild since it strips unfamiliar comments, but most other tools carry comments through to the output. I think this is sufficient to convince me that this direction isn't the clear, easy win I thought it might be. It's a pretty serious downside. I'm going to close this because I don't think I should champion this anymore. Others can still feel free to chime in if they feel otherwise. Thanks for such a comprehensive answer.
