### ISSUE TITLE
hotOnly option is not working

### ISSUE THREAD

**Issue by nuong** [webpack/webpack#12597]
# Bug report

**What is the current behavior?**
Cannot start webpack-dev-server if set `hotOnly` true
Error:
```
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'hotOnly'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

**If the current behavior is a bug, please provide the steps to reproduce.**
 Use webpack 5:  webpack@5.11.0 and webpack-dev-server@4.0.0-beta.0
 Enable hotOnly option:
 ```
 devServer: {
     hotOnly: true
 },
 ```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  webpack@5.11.0
Node.js version: v14.15.1
Operating System: MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Use `hot: 'only'`, it is in CHANGELOG

**Comment by nolimitdev** [comment]
https://webpack.js.org/configuration/dev-server/#devserverhot

**Comment by DrThouraya** [comment]
> Use `hot: 'only'`, it is in CHANGELOG

Hi @alexander-akait , 

I upgrade node to 10.20 and npm to 6.14 and the ERROR message had changed! 
![newerrormessage](https://user-images.githubusercontent.com/21196992/147482593-d17e43cc-329e-44c9-a235-7811194c3318.png)
when looking to fix this error, many persons recommend to change the "webpack.config.js" file, However, I didn't find this file in my directory [https://github.com/DrThouraya/regards-frontend/tree/master/webapp](url).

Thanks for your help!
PS: I didn't found the last post so I write for you here..Thank you!

**Comment by alexander-akait** [comment]
Some developers use more complex webpack configuration names, in your case -  `webpack.*.*.js`, you can found a lot of them here https://github.com/DrThouraya/regards-frontend/tree/master/webapp

From your error report - https://github.com/DrThouraya/regards-frontend/blob/master/webapp/webpack.dev.preprod.config.js config was used, but looks you have configuration for webpack dev server v3, I am afraid I can't help here, because maintenance of these packages should do migration, there are a lot of other options for v3, I recommend to open issue in https://github.com/RegardsOss/regards-frontend and ask developer about v4 migration

**Comment by DrThouraya** [comment]
Thanks a lot @alexander-akait. I texted to one of the developers!
