### ISSUE TITLE
TypeError: XYZ.<function> is not a function

### ISSUE THREAD

**Issue by dennisjac** [webpack/webpack#1265]
I'm trying to get a basic webpack+react+flux setup going but I seem to have trouble requiring() certain modules.

Right now I'm trying to integrate this event emitter:
https://github.com/Olical/EventEmitter

Since this module is installed using bower I added the bower components to the path in webpack.config.js:
...
modulesDirectories: ['node_modules', 'bower_components'],
...

In my js file I then require the components:
var React = require('react');
var emitter = require('eventEmitter/EventEmitter');
emitter.on("store-changed", function() {...}.bind(this));

This works fine and when I run webpack-dev-server the EventEmitter.js gets included but in the browser console I get this:
TypeError: emitter.on is not a function

Just for kicks I also tried something like fs=require('fs') followed by fs.statSync(...) but get the same error that fs.statSync is not a function.

What am I doing wrong?

**Comment by shama** [comment]
The API for that library wants you to create an instance in order to use the emitter:
https://github.com/Olical/EventEmitter/blob/master/docs/api.md#eventemitter

```js
var Emitter = require('eventEmitter/EventEmitter');
var emitter = new Emitter()
emitter.on("store-changed", function() {...}.bind(this));
```

Also just a note, node.js has a built in `var EventEmitter = require('events').EventEmitter` so that external library might not be necessary with webpack.

As for `require('fs')`, the web browser doesn't have a file system as such webpack doesn't have a compatible web version of `fs`. Which is why `fs.statSync` is also not a function.
