### ISSUE TITLE
Behaviour: "reference error <function> is not defined" (window scope)

### ISSUE THREAD

**Issue by W1N3** [webpack/webpack#12666]
First thing first, all the problem and code I asked on stack overflow about this problem:
https://stackoverflow.com/questions/66056579/webpack-referenceerror-a-function-is-not-defined

The whole point of this issue, in a nutshell, is to understand why the const and var functions got missed on window when using webpack.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please prefer to use `Discussions` for questions, otherwise please use the issue template. if you need to expose it to window you need write `window.checkPass = function (input) {}`, we don't expose to window by default to prevert collision with existing globals
