### ISSUE TITLE
TypeError: __webpack_require__(...) is not a function on nodejs

### ISSUE THREAD

**Issue by Stexxe** [webpack/webpack#12694]
# Bug report

**What is the current behavior?**
I get `TypeError: __webpack_require__(...) is not a function` while running bundled script by `node`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the sample project [webpack_require.zip](https://github.com/webpack/webpack/files/5987194/webpack_require.zip). The steps to reproduce the problem are the following:
1. Install `webpack` and `node-fetch`: `npm install`
2. Bundle the script that requires `node-fetch` and makes a simple request: `./node_modules/.bin/webpack-cli`
3. Run bundled script: `node dist/result.js`

**What is the expected behavior?**
I expect information about the response to be printed in the console the same way when I run the original script: `node src/index.js`.

**Other relevant information:**
webpack version:  5.22.0
Node.js version: v12.18.4
Operating System: macOS Catalina 10.15.7

**Comment by alexander-akait** [comment]
@Stexxe Here interesting case, when you run `node src/index.js` Node.js uses the `main` field from `package.json` from `node-fetch` package (i.e. `node-fetch/lib/index.js`), but when you run `webpack`, `webpack` uses the `module` field so we bundle `node-fetch/lib/index.mjs`, and because you use `require` we export the `default` **property** (not `default` export, because not `default` export for Commonjs).

Try to change:
```js
require('node-fetch').default("http://example.com").then(console.log.bind(console));
```

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/5756
