### ISSUE TITLE
Webpack 5: Library build with WebWrokers does not work with applications that are dependent on it

### ISSUE THREAD

**Issue by tsarapke** [webpack/webpack#12719]
# Bug report

**What is the current behavior?**

We have a core library based on React, that used among several applications that built on top of `react-scripts`.
Our library contain various heavy computations that used among our applications.
Adding `new Worker` construction in library, produces additional chunk in build result (what is quite expected). But when using component from a library that uses this WebWorker does not load worker script (a chunk from library). The WebWorker chunk does not exist in project build.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Download project: `https://github.com/tsarapke/proj.git`. It use a library with WebWorker: `https://github.com/tsarapke/lib`
2) `yarn install`
3) `yarn start`

![image](https://user-images.githubusercontent.com/7983863/108496003-912c1180-72ba-11eb-90ad-2117e9f8cb9f.png)

**What is the expected behavior?**

Project build should contain WebWorker chunk from a library.
In accordance with provided example - it should print 'Hello World' in console when WebWorker post message.

**Other relevant information:**
webpack version:  webpack version: 5.22.0
Node.js version: v14.15.5
Operating System: Win10
Additional tools: Yarn

**Comment by alexander-akait** [comment]
Here two problems, go to `http://localhost:3000/src_workers_helloWorld_worker_js.index.js` and look at content of file, the first problem - you use new webpack v5 syntax - `new URL('./file.js', import.url.meta)` (after bundling you have `new Worker(new URL(/* worker import */ __webpack_require__.p + __webpack_require__.u("src_workers_helloWorld_worker_js"), __webpack_require__.b))`), but because `react-scripts` uses v4, new syntax is not understandable (parsed and analyzed), so browser try to request `src_workers_helloWorld_worker_js.index.js` from `/`, (but file located in `node_modules/lib/dist/src_workers_helloWorld_worker_js.index.js`), and the second bug, webpack should copy assets from bundled `new URL` syntax.

**Comment by tsarapke** [comment]
Have tried to create "proj2 (https://github.com/tsarapke/proj2.git)" with Webpack 5 avoiding `react-scripts`. So yes, it could not find workerized chunk. It throws 404 error.

![image](https://user-images.githubusercontent.com/7983863/108513595-e0cb0700-72d3-11eb-9e6d-edc4ff0fae1b.png)

So... is it actually a bug or feature? Should Webpack 5 copy worker chunks from library package?

**Comment by alexander-akait** [comment]
> Should Webpack 5 copy worker chunks from library package?

Here two bugs:
- `react-scripts` should update `webpack` to v5, to understand `new URL` syntax, can't be fixed here
- `webpack` should copy files from bundled `new URL`

**Comment by tsarapke** [comment]
Regarding first point, as far as I know, at the moment some work is being done towards migration (have no idea how long it would be).

As for the second... Hope it will be fixed in near future (begging_cat.gif)

**Comment by alexander-akait** [comment]
bump

**Comment by dandansoysauce** [comment]
I am having this bug as well. Though I don't use CRA, but webpack is not copying the files resulting to a `404 Not Found`

![image](https://user-images.githubusercontent.com/25461756/123339449-30b92380-d57d-11eb-9e8f-21700b26211b.png)

**Comment by tsarapke** [comment]
Any chance(plans) to get it fixed in near future? This actually blocks a case when lib and project does not depends on `react-scripts`. So you can't make it work with usual own webpack config.

**Comment by alexander-akait** [comment]
Can you provide more infromation?

**Comment by tsarapke** [comment]
@alexander-akait there is already provided case by @dandansoysauce. In a few word, if I have library with WebWorker and some application that builded with Webpack 5 but not with RCA, it still does not see worker-related chunk from library.

**Comment by alexander-akait** [comment]
Why your build library?

**Comment by tsarapke** [comment]
You can read my first message in this topic
> Adding new Worker construction in library, produces additional chunk in build result (what is quite expected). 
How I can make Worker to be used in some shared component that a part of... let say, `library.js`, and make it possible to be used in other applications? (what actually sounds impossible).

**Comment by alexander-akait** [comment]
I think you don't need to bundle library

**Comment by jlyman** [comment]
Or potentially another angle: It may be that the lib doesn't necessarily need to be closed source, but that we don't want to make assumptions about how the consuming application's bundling/transpiling process is constructed? So we go to lowest common denominator by bundling the library so that it is a single, usable bundle of code, allowing consuming apps to do with it as they please?

**Comment by alexander-akait** [comment]
Let's keep open, maybe we will found better solution to solve it

**Comment by ckken** [comment]
mark

**Comment by winniederidder** [comment]
Our project has a similar issue. We are building a programming scratchpad that uses WebWorkers to evaluate arbitrary code. We then want to be able to include this scratchpad into other applications that want to run code locally.

The workers are correctly bundled into separate files to allow loading. However, upon spawning the workers, the application looks in the current directory for the bundle (for example /806.index.js) but the actual location is within the node_modules of your current project, i.e. /node_modules/@dodona/papyros/lib/806.index.js. 

By copying the worker bundles into that location, they can be loaded, but this is of course far from ideal as you want your package to be plug-and-play.

**Comment by vankop** [comment]
@alexander-akait this should work with latest webpack

> webpack should copy files from bundled new URL

**Comment by alexander-akait** [comment]
@vankop Why do you think? We don't copy already bundled code, maybe only ESM can help here

**Comment by vankop** [comment]
ah.. I see
```js
const worker = new Worker(new URL(/* worker import */ __webpack_require__.p + __webpack_require__.u("src_workers_helloWorld_worker_js"), __webpack_require__.b));
```
this is not statically analyzable..

**Comment by alexander-akait** [comment]
Yes, so I think only ESM can help here, or we need implement it on parser level and rebundle, it is not easy

**Comment by winniederidder** [comment]
@alexander-akait Could you give an example of using ECMA modules in the supported fashion? My previous post in this discussion describes my currently working approach, but if there is a better way I will gladly use it (and update my comment accordingly).

**Comment by alexander-akait** [comment]
You can try it using `output.module` https://webpack.js.org/configuration/output/#outputmodule to build library

**Comment by winniederidder** [comment]
output.module is described as an experimental feature. How likely is it that it will become stable and fully supported?

**Comment by alexander-akait** [comment]
I think it is already stable (except real edge cases), maybe we need to do it officially

**Comment by kevinsjoberg** [comment]
I've been experimenting with this quite a bit and I haven't to get this worker at all. I have an app A that uses a package P that contains a web worker. I get a 404 when the web worker starts as it tries to load the file from the public path `/` while the file in reality is part of the package P.

- I've tried inlining the web worker URL (does not work).
- I've tried using the experimental support for outputting ESM (does not work).

@alexander-akait I'm not sure what you've had in mind, but as far as I can tell, neither approach does not work. I'd love to see a minimal working example if anyone have managed to get this working. 🙂

**Comment by alexander-akait** [comment]
Can you provide examples?

**Comment by kevinsjoberg** [comment]
Sure. Here's an example of trying to use the worker coming from `packages/external-web-worker`. Configured to use ESM.

https://github.com/kevinsjoberg/external-web-worker-example

**Comment by alexander-akait** [comment]
@kevinsjoberg I see the problem, we have:
```
new Worker(new URL(r.p+r.u(438),r.b),{type:"module"})}
```

and `r.p+r.u(438)` and `r.b` are not statically analyzable 

In theory if you have static public path and base Url, we can optimize our output and create something like:
```
new Worker(new URL(""+438 + ".external-web-worker.js","http://example.com"),{type:"module"})}
```

So terser compress strings and we will have statically analyzable worker code, another solution is allow to set them (options) using webpack comments and generate code with provide values (but it sounds like dirty hack)

Also we generate `e.b=document.baseURI||self.location.href;` (i.e. base URL), but we have `output.module` so I expected output with `import.meta.url` (especial when I am creating library). But we can solve it using `target: ["webworker", "es2020"],`, that is some misleading, because when I set ECMA module output and build library I expected `import.meta.url` will be used (I fully understand why we generate `e.b=document.baseURI||self.location.href;`), but I think we should revisit it, as minimum generate a warning/info about `import.meta.url` is not supported and polyfill will be used, just my ideas to improve DX.

/cc @vankop Any ideas?

@kevinsjoberg Here classic double bundling, I think you will faced with it using other bundlers too, but why you run webpack on library, why not keep code in library as is and avoid bundling, because you will bundle your code when you will create application with your library

**Comment by vankop** [comment]
I think library in this case should output ESM module and in this case we will output `new Worker(new URL("<relative_to_output_root_path/worker.js", import.meta.url))`

**Comment by alexander-akait** [comment]
@vankop Yep, but it can be some tricky to implement right now...

**Comment by winniederidder** [comment]
> @kevinsjoberg Here classic double bundling, I think you will faced with it using other bundlers too, but why you run webpack on library, why not keep code in library as is and avoid bundling, because you will bundle your code when you will create application with your library

This is not feasible when developing a library that will be imported by external projects (i.e. as an npm package), as it will be found already bundled within the node modules.  I think this is also the original point of this issue, that it is difficult to do this without worker-loader.

**Comment by Swoorup** [comment]
Has anyone ever got this to work?

**Comment by Swoorup** [comment]
> > Has anyone ever got this to work?
> 
> The [Papyros-application](https://github.com/dodona-edu/papyros) makes use of WebWorkers to run Python/JavaScript code that the user filled in. It is included in [Dodona](https://github.com/dodona-edu/dodona) where it is enabled in Python exercises so users can write and run code in their browser instead of a locally installed IDE.
> 
> For it all to work, worker-loader is still required as there is no better alternative at this point in time (see the rules in [the webpack config](https://github.com/dodona-edu/papyros/blob/main/webpack.config.js?rgh-link-date=2023-02-24T14%3A57%3A01Z) )

thank you, I removed worker-loader from my project, looks like I need it back in again.

**Comment by winniederidder** [comment]
> thank you, I removed worker-loader from my project, looks like I need it back in again. Out of curiosity don't you need to disable worker in
> 
> ```json
> test: /\.ts?$/,
> 					loader: "ts-loader",
> 					exclude: /node_modules/,
> 					```
> ```

Likely not necessarry, but maybe it provides a 0.0001 ms speedup by not having to check that entire folder, just in case ;)

**Comment by alexander-akait** [comment]
Sorry for delay, do you need inline mode for workers, right? Or about double bundling (because the original isse about it)

**Comment by winniederidder** [comment]
My goal with this issue is to provide better bundling support for workers . The current approach requires inlining workers using worker-loader, which causes the bundling output to be very large which causes latency. This gets worse if your library contains multiple workers that are not always all needed, it depends on the user's action which worker needs to run. With the current approach, both are fetched upon loading the page instead of chunked.
The issue lies in new Worker(...) that is by default outputted to some url that cannot be resolved anymore when including the library in a different package. Example in question is [Papyros](https://github.com/dodona-edu/papyros) which is a library with workers to run the user's code in different programming languages, that is then included in [Dodona](https://github.com/dodona-edu/dodona).

**Comment by alexander-akait** [comment]
@winniederidder Yeah, understood, after bundling consturction is not statistically analizable, right?, so I have a few questions:
- Why you bundle your library?
- Is ESM good output for you?

**Comment by alexander-akait** [comment]
@winniederidder The main problem is that webpack generate a special runtime to properly load worker processes and they are don't statically analizable, only way here is ESM and fix output to be statically analizable. But it is not easy for all cases (that is why it was not implemented yet).

I asked about bundling library, because you don't need to bundle it in most of cases. Also you can create worker factory and pass compiled sciprt to there, if you provide me example your problem with code I will show how we can solve it

**Comment by winniederidder** [comment]
@alexander-akait We already discussed earlier in this thread why the libraries need to be bundled. It would probably still be interesting to see it done without bundling as well. Your alternative solution with a worker factory is new to me too, so please indulge us in what you think the solution might be.
[This repository](https://github.com/lawrence-witt/set-worker-timer/tree/b65fa52459f1c649f6c92a4e58fe6a5f66f2ff89) is an example package with a worker in it, it was also my basis to find a working approach using worker-loader. So assume for now that this is a library that I want to be able to use in another project, how would I build/include it elsewhere?

**Comment by alexander-akait** [comment]
@winniederidder sorry for the delay in replies, there are a lot of issues every day (now your issues on top), I think I've lost the context, maybe you can provide with example of your problem, you provide repo, do you want to bundle it? Looks like the package uses analizable syntax. Do I undestand correctly - you want to use this package in your library (and bundle this library) and then reuse the library in your application?

**Comment by winniederidder** [comment]
@alexander-akait Indeed, as I mentioned, assume the linked repository is a project we would like to bundle to then publish it on the npm registry. Afterwards, we would like to use npm install to include it in another project, that should be able to be bundled to be deployed as a web application.

**Comment by winniederidder** [comment]
@alexander-akait I no longer work on the project that could benefit from this, so I won't be trying it out myself either. Hopefully other developers with this issue can give it a go and report back here with the results :)

**Comment by alexander-akait** [comment]
Okay, I will keep open, so feel free to ping me or any feedback
