### ISSUE TITLE
Using splitChunks together with library causes undefined exports

### ISSUE THREAD

**Issue by janeksmielowski** [webpack/webpack#12723]
I'm trying to create library, built by webpack. Creating an entry with some exported function works just fine.
The problem starts when I add splitChunks property with any of these settings: `chunks: "all"`, `"async"` or `"initial"`.
When I'm trying to use the exported module I got `undefined`.

# Bug report

**What is the current behavior?**
Using `splitChunks` and `library` makes exports undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
{
    entry: "bundle.ts",
    output: {
        library: "MyLibrary",
        libraryTarget: "window"
    },
    optimization: {
        splitChunks: {
            chunks: "all"
        }
    }
}
```

**What is the expected behavior?**
Exported modules should be available in `window.MyLibrary`.
I repeat, my current configuration, without splitChunks is **fine** and I can use my exported function.

**Other relevant information:**
webpack version:  4.42.1, also checked on 5.23.0
Node.js version: 15.6.0
Operating System: Windows
Additional tools: -

**Comment by alexander-akait** [comment]
You forget to include splitted chunk in HTML file (run `ls -l ./dist`), I recommend do not use `splitChunks` for libraries if you don't understand why you need this, unfortunately you ignore `**If the current behavior is a bug, please provide the steps to reproduce.**` so won't fix

**Comment by janeksmielowski** [comment]
I cannot include it, because I have dynamically named files, with hash. I use it, because I need it, to split same logic, used in multiple places. Why doesn't webpack resolve this splitted chunk itself? Is it possible to make it resolve automatically?

**Comment by alexander-akait** [comment]
> Why doesn't webpack resolve this splitted chunk itself?

When you split `initial` chunks you need manually inject them, otherwise what's the point of split them, just don't use `all`

> Is it possible to make it resolve automatically?

You can use `html-webpack-plugin` or logic from this plugin to generate `script` and `style` tags

**Comment by janeksmielowski** [comment]
The thing is I've got multiple entry points. One is using HTML and the second will just expose library.
I actually need splitting, because it makes my build improved a lot.
Any idea, what should I do?

**Comment by alexander-akait** [comment]
You can get this information from `stats`, if you need good logic please look at `HTMLWebpackPlugin` code, it will be faster

**Comment by janeksmielowski** [comment]
Thanks for response @alexander-akait !

So, I just emitted the HTML file, with all chunks injected, as you suggested, but still my export is undefined :( 
Do you have any further guidelines? Does webpack remove these exports by default? Should I turn on some option to prevent it? I've been searching for many days and I still haven't found a solution.

**Comment by alexander-akait** [comment]
> Do you have any further guidelines?

Use `html-webpack-plugin`

> Does webpack remove these exports by default?
> Should I turn on some option to prevent it?

Do you build library or application?

**Comment by janeksmielowski** [comment]
I used this plugin and it outputs HTML with all the necessary chunk names, so it looks fine now. Then, I open the HTML and my export is undefined.
I build an application, with multiple entrypoints. Some of them are for standalone application and some of them are exposing  functions for another app, that is working alongside

**Comment by alexander-akait** [comment]
Do you use `webpack serve`?

**Comment by janeksmielowski** [comment]
Yes. It also happens when I build it for production

**Comment by alexander-akait** [comment]
Please provide simple example

**Comment by janeksmielowski** [comment]
Okay, I set up a minimal example and it is working, so I need to compare it with my project and trace, what is causing the problem.

I will keep you updated

**Comment by janeksmielowski** [comment]
Hi,

I've found an issue with my configuration and it came out I simply didn't pull all the required chunks needed.

Thanks for help!

**Comment by GouJieShinee** [comment]
@janeksmielowski how fixed it? i meet the same problem whit splitChunks when import module is undefined

**Comment by janeksmielowski** [comment]
Hi,

Basically, I generate HTML file by html-webpack-plugin which is automatically filled with scripts filenames. Then I just inject all of them into my app.

If I remember well, the main cause for the problem was the order of running the scripts. Ensure that you run main script last, after all chunks. You can look at async or defer properties of script tag documentation.

Hope it helps, good luck!

**Comment by Shashank-Bhatt1** [comment]
@janeksmielowski how did you managed to solve this? If you don't mind, can you please share your solution which might help others?

i have setup these configurations and 

```
optimization: {
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all',
          maxSize: 500000, // Limit vendor chunks to 500KB
        },
        styles: {
          test: /(\.css)$/, // Matches any CSS file
          name: 'styles',
          chunks: 'all',
          enforce: true, // Ensures that the chunk is created even if it's not larger than minSize
          maxSize: 500000, // Limit the chunk size to 200KB
        },
      },
    },
  },
```

it generated multiple chunks which it includes somewhere in compiled files something like this and also in output directory.

`var __webpack_exports__ = __webpack_require__.O(undefined, ["vendors-node_modules_a","vendors-node_modules_fabric_dist_fabric_js-7a94a469","styles-node_modules_cropperjs_dist_cropper_css-d8200bd8","styles-output_css_custom_css-178d476e","styles-output_css_main_css-e7ca733b"],`

I am unable to get exported values from my package when using splitChunksPlugin

**Comment by janeksmielowski** [comment]
Hi,

It was so long time ago, I don't remember now 🙈🤣 However, I will try to find it out and get back to you.

I think I didn't resolve it, and just removed splitChunks property. Then some webpack version resolved this issue, and it just worked.

What version are you using?

**Comment by janeksmielowski** [comment]
> Hi,
> 
> I've found an issue with my configuration and it came out I simply didn't pull all the required chunks needed. Everything works as expected now.
> 
> Thanks for help!

In general this was an issue. Make sure you import all the files

**Comment by shashank-brightness** [comment]
@janeksmielowski Thanks for looking into that. 

Okay so I understood webpack does not include all chunks when splitted out via this plugin but how did you instruct webpack so it included back them? 
you mentioned html-webpack-plugin, i tried HtmlWebpackPlugin (with zero config as it just suggests but we know it is always myth :grinning:) but i could not get, how it worked and what its template, chunks etc props was for.

I have also removed `splitChunksPlugin` for now but i wished i could do better for optimization.

TBH, webpack should include all chunks files itself instead of requiring developer to first figure out, configure and then do this.

**Comment by shashank-brightness** [comment]
@janeksmielowski  Thanks for looking into that. 

Okay so I understood webpack does not include all chunks when splitted out via this plugin but how did you instruct webpack so it included back them? 
you mentioned html-webpack-plugin, i tried HtmlWebpackPlugin (with zero config as it just suggests but we know it is always myth :grinning:) but i could not get, how it worked and what its template, chunks etc props was for.

I have also removed `splitChunksPlugin` for now but i wished i could do better for optimization.

TBH, webpack should include all chunks files itself instead of requiring developer to first figure out, configure and then do this.

**Comment by Shashank-Bhatt1** [comment]
@janeksmielowski Thanks for looking into that. 

Okay so I understood webpack does not include all chunks when splitted out via this plugin but how did you instruct webpack so it included back them? 
you mentioned html-webpack-plugin, i tried HtmlWebpackPlugin (with zero config as it just suggests but we know it is always myth :grinning:) but i could not get, how it worked and what its template, chunks etc props was for.

I have also removed `splitChunksPlugin` for now but i wished i could do better for optimization.

TBH, webpack should include all chunks files itself instead of requiring developer to first figure out, configure and then do this.

**Comment by janeksmielowski** [comment]
The only purpose why I used html-webpack-plugin was to grab the final names of the files and chunks, that I needed to import, to make it work.

Basically, when you build the app, webpack generates an HTML with a few scripts injected, eg.:
```html
<head>
    <script defer="defer" src="/runtime~index.js"></script>
    <script defer="defer" src="/index.js"></script>
</head>
<body></body>
```

It could look something like this or it could generate more files (chunks).

In my case, I needed to build the library, and import it into an existing web app.
The issue was that I only imported index.js, and did not import all the other files.

You can also check a similar issue and I believe the reason was identical: https://github.com/webpack/webpack/issues/11152
