### ISSUE TITLE
does not compile when using yarn v2

### ISSUE THREAD

**Issue by npenin** [webpack/webpack#12735]
# Bug report

**What is the current behavior?** When using yarnv2 (which enforces proper dependency usage), it is not able to reference json-schema as it is not declared as a dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?** All references used by webpack should be declared as direct dependencies in package.json

**Other relevant information:**
webpack version:  5.23.0
Node.js version: 14.15.4
Operating System: alpinelinux
Additional tools: yarn v2

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Do not ignore `If the current behavior is a bug, please provide the steps to reproduce.`

Webpack don't use `json-schema` package

**Comment by tuchuants** [comment]
Webpack USE it, in generated types.d.ts. Same issue with yarn v3.

**Comment by alexander-akait** [comment]
@tuchuants please provide what is the error, yarn have webpack test and webpack have yarn pnp tests and no problems
