### ISSUE TITLE
How to make SourceMaps work for 1p Packages with WebPack ?

### ISSUE THREAD

**Issue by rahulrsingh09** [webpack/webpack#12732]
We have a bunch of 1p JS packages which are used across web and mobile (React Native App). One thing we have noticed is the source map only works for the base package and not for the 1p packages as those are node dependencies added at compile time.

The 1p node modules are not captured as part of the source maps how do we enable for our packages alone? I tried using https://www.npmjs.com/package/source-map-loader but it dosent work and gives error at compile time . 

**Setup**

[![enter image description here][1]][1]

    ERROR in (webpack)-dev-server/client?http://localhost:8080
    Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):
    TypeError: this.getOptions is not a function
        at Object.loader

**WebPack Config** 

    devtool: 'source-map',
      module: {
        rules: [
          {
            test: /\.js$/,
            enforce: "pre",
            use: ["source-map-loader"],
          },
          {
            test : /\.scss$/,
            use: {
              loader: 'sass-loader',
              options: {
                includePaths: ["./node_modules"]
              }
            }
          },
          {
            test: /\.js$/,
            use: {
              loader: 'babel-loader'
            }
          },
          {
            test: /\.mjs$/,
            include: /node_modules/,
            type: 'javascript/auto'
          }
        ]
      },

  [1]: https://i.stack.imgur.com/QqCjn.png

**Comment by sokra** [comment]
What are 1p packages?

The error sounds like you are using an outdated webpack version, but I can't say because:

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
