### ISSUE TITLE
Errors should output to STDERR

### ISSUE THREAD

**Issue by sonnyp** [webpack/webpack#1278]
Right now if there is an error such as ``Unexpected identifier``` it goes to STDOUT, it should go to STDERR and the process should exit with an error code so that CI , npm test, ... can detect something went wrong.

**Comment by sonnyp** [comment]
Duplicate https://github.com/webpack/webpack/issues/1278

**Comment by SimenB** [comment]
@sonnyp Duplicate of itself? I'd like to follow the other issue but a quick search didn't find it...

**Comment by sonnyp** [comment]
@SimenB my bad

**Comment by hogmoru** [comment]
This is still a problem with WebPack 4.29.0.
**That was not a duplicate of #708** (which is primarily about exit code, a bit about exiting early, but does not seem to mention printing errors to stderr instead of stdout).
Granted, now it exits with non-zero code in case of build errors, but it still prints everything to stdout, errors or not.
Not sure what it _should_ do. Current behavior is not completely absurd, but it's a problem when webpack is called from other tools that only show stderr when the command exits with non-zero status (which sounded reasonable... I have this problem with [Rush](https://rushjs.io/): it tells me build has failed but does not show WebPack errors).
Pondering whether I should open a new issue here, or for Rush, or both 😅

**Comment by jackkinsella** [comment]
Could we consider re-opening this? Other tools, such as `webpacker` in the Rails world, have trouble printing out `webpack` related logs when there is a failure because these tools expect the errors to be on `stderr`, not `stdout`. See [here](https://github.com/rails/webpacker/issues/1677) for details.

**Comment by leimonio** [comment]
This is still an issue on `webpack` `v4.41.2`.

**Comment by evilebottnawi** [comment]
@jackkinsella @leimonio Can you open new issue with reproducible test repo, big thanks!

**Comment by hogmoru** [comment]
@evilebottnawi Opened #10022
