### ISSUE TITLE
Webpack 5 and Webpack-dev-server Integration

### ISSUE THREAD

**Issue by SatishChandraPalakoti** [webpack/webpack#12848]
Webpack 5 configured with webpack dev server configuration is **NOT** picking up the file location to serve from. It's forcing me to explicitly mention this at the webpack-cli args in the package.json

NOT WORKING !!!!
    ```
devServer:{
        contentBase: './build',
        port: 9000
    },
```

WORKING !!

``` "start": "webpack serve --content-base=build --open",```

I am currently not using any htmlPlugins inside the webpack configuration, assuming it might conflict with the devServer configurations.

**Comment by SatishChandraPalakoti** [comment]
"webpack": "^5.24.4",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers and use `Discussions` for help

Double check your `publicPath`
