### ISSUE TITLE
Inline loaders don't work with asset type

### ISSUE THREAD

**Issue by 7rulnik** [webpack/webpack#12876]
# Bug report

**What is the current behavior?**

I'm trying to use an inline loader with `!!` to have some unique behavior for several modules.

```js
import rawTxt from '!!raw-loader!./raw.txt';
```

But if rule has one of type `asset/resource`, `asset/inline`, `asset/source` or `asset` it will be transformed with this type, not the inline loader. But if a rule has `use` inline loader will be applied and loaders from `use` will be ignored.

Rule configuration:
```js
{
    test: /\.txt$/i,
    type: 'asset/inline',
}
```

So in this case `rawTxt` will be base64, not raw.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/7rulnik/webpack-asset-inline-loader-bug-repro

**What is the expected behavior?**

I expect that behavior should be the same for rules with `type` and for rules with `use`. So even for `asset/*` types inline loader should have priority.

As I understand I can use `resourceQuery` to workaround this issue.

**Other relevant information:**
webpack version: 5.24.4
Node.js version: 14.15.4
Operating System: macOS 11.2

**Comment by alexander-akait** [comment]
> As I understand I can use resourceQuery to workaround this issue.

It is not workaround, it is official solution https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax

In long term we need to avoid and remove inline syntax for loaders (we keep them for backward compatibility), because it is out of ECMA modules spec, also it is specific webpack syntax, it is bad for future JS ecosystem. 

I think we need update docs on new approach.

**Comment by alexander-akait** [comment]
Answered
