### ISSUE TITLE
Create type declarations for more interfaces

### ISSUE THREAD

**Issue by MarkKoester** [webpack/webpack#12913]
Webpack's exported types are missing many that were previously provided by @types/webpack.

Examples include:
- ConfigurationFactory (extremely common)
- MultiConfigurationFactory
- Loader function signature

**Comment by dopry** [comment]
It would also be nice to export all defined interfaces such as CallbackFunction<T>, etc so they're easy to depend on in consuming code.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use this https://github.com/webpack/webpack/issues/11630 issue to report about missing types and please respect time of other developers and use the issue template in future

We don't have `ConfigurationFactory` and `MultiConfigurationFactory` types and never have them
