### ISSUE TITLE
How to compile vue2 file and vue3 file

### ISSUE THREAD

**Issue by BlackCubeNo99** [webpack/webpack#13009]
my package.json install `vue-loader`、`vue-template-compiler`、`@vue/compiler-sfc`、`vue2`、`vue3`

```json
// package.json
"devDependencies": {
  "vue-loader": "16.1.2",
  "vue-template-compiler": "2.6.12",
  "@vue/compiler-sfc": "3.0.7"
},
"dependencies": {
  "vue": "2.6.12",
  "vue3": "npm:vue@3.0.7"
}
```

How to set vue2 and vue3 alias config ?

```javascript
// webpack.config.js
module.exports = {
  entry: ['a.js', 'b.ts'],
  resolve: {
    alias: {}
  }
}
```

a.js use vue2
```javascript
// a.js
import Vue from 'vue'
import App from './App.vue'

new Vue({
  el: '#app',
  render: h => h(App)
})
```

b.ts use vue3
```typescript
// b.ts
import { createApp } from 'vue3'
import App from './App.vue'

createApp(App).mount('#app')
```

Can someone help me ?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please prefer `Dicussions` for questions. Also please include what is the problem. Because we don't understand you, thanks
