### ISSUE TITLE
webpack 5.28.0 compiled with 2 errors

### ISSUE THREAD

**Issue by Octansf** [webpack/webpack#13001]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Error appear when start my project with node js.
In browser when inspect errors two correspond at webpack-dev-server/client utils index.js
Object { loc: "index", message: "Module not found: Error: path argument is not a string" }
index.js:160:11

in file line 160 is : log.error(strippedErrors[i]);

complete for is:
for (var i = 0; i < strippedErrors.length; i++) {
      log.error(strippedErrors[i]);
    }

I try to fixed but I don´t understand why appear this error

Thanks in advanced for help

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
