### ISSUE TITLE
node module problem

### ISSUE THREAD

**Issue by shradhanandsingh** [webpack/webpack#13039]
there is some error appear while run this project. **Please help me if any one solve this issue**
I already install webpach dev, webpack-cli, node-sass and pace also but I con not solve this problem

**Comment by shradhanandsingh** [comment]
![bug](https://user-images.githubusercontent.com/45650321/113259077-5a4e1000-92ea-11eb-8742-6277a2c2b311.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please open an issue in `ng` repo. You have invalid configuration, please read the error message.

**Comment by alexander-akait** [comment]
You have the `enforce` option for `module.rules[1][4]`, but it is not allowed
