### ISSUE TITLE
Getting error "You may need an additional loader" using with Angular / PDF.js

### ISSUE THREAD

**Issue by csname1910** [webpack/webpack#13092]
I am getting the following error.

You can reproduce it with this minimal GitHub repository:

https://github.com/csname1910/errordemo

    Error: ./node_modules/pdfjs-dist/build/pdf.js 2413:45
    Module parse failed: Unexpected token (2413:45)
    File was processed with these loaders:
     * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
     * ./node_modules/@ngtools/webpack/src/ivy/index.js
    You may need an additional loader to handle the result of these loaders.
    |         intent: renderingIntent,
    |         renderInteractiveForms: renderInteractiveForms === true,
    >         annotationStorage: annotationStorage?.getAll() || null
    |       });
    |     }

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You need webpack v5 (for optional chaining ) or setup `babel-loader` to handle it, please ask this in `@angular/cli` repo, because we can't fix it on our side
