### ISSUE TITLE
can't find module 'fs'

### ISSUE THREAD

**Issue by ChenYCL** [webpack/webpack#13112]
# Bug report
can't find module 'fs'

**What is the current behavior?**
```
in ./node_modules/react-docgen-typescript/lib/parser.js
Module not found: Error: Can't resolve 'fs'
```

**Other relevant information:**
webpack version:  5.31.2
Node.js version: 14.16.1
Operating System:  10.15

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please set `target: node` if you build app for Node.js or use `resolver.fallback.fs: false` if you want to ignore module for browser (note it can be unsafe because some modules can't be used in browser because they will be create only for Node.js)
