### ISSUE TITLE
[suggestion] Add an API call to compile without writing to a file

### ISSUE THREAD

**Issue by skyrpex** [webpack/webpack#1314]
Hi there,

I spent some time looking for this feature, without any luck.

I'd like to suggest:
* Have Webpack a function to compile from a string & return the sources and sourcemaps instead of writing them to disk.

In my case, it'd allow me to wrap Webpack in a better Gulp plugin, and work with streams in a good way.

For example:
```javascript
const source =  'const test = true;',
const compiler = webpack({
    // options...
});
compiler.compileString(source, (err, result) => { // This would ignore entry and output options
    console.log(result.stats); // == stats file...
    console.log(result.code); // == 'var test = 1;'
    console.log(result.map); // == sourcemap contents
});
```

**Comment by sokra** [comment]
You can pass a custom filesystem, i. e. the `memory-fs`, to compile in memory.

Keep in mind that webpack is not only emitting one file. You could have multiple entry chunks, additional chunks, extracted stylesheet, emitted file from `file-loader`, etc.

**Comment by philipwalton** [comment]
I would like this as well. If you're using webpack as a sub-build tool for larger build tool, I'd be very useful to have the ability to both pass in and get back a file/stream or an array of files/streams.

**Comment by skyrpex** [comment]
I didn't know about ```memory-fs```. It suits my needs! There's no need for extra methods as I suggested...

This can be closed on my side. Thanks.

**Comment by philipwalton** [comment]
Can either of you link to a place in the docs where `memory-fs` is being passed to webpack? I didn't see a usage example.

**Comment by skyrpex** [comment]
@philipwalton, I created a gulp plugin for webpack where I use it: [here you go](https://github.com/skyrpex/gulp-webpack-sourcemaps)

**Comment by philipwalton** [comment]
I tried playing around with this for a bit and while at first it seemed promising, I don't think it works for in-memory entry files.

I thought I could make it work by setting the compiler's `inputFileSystem` to an instance of `MemoryFileSystem` like so:

```js
var mfs = new MemoryFileSystem();
compiler.inputFileSystem = compiler.outputFileSystem = mfs;
```

but that only seems to work for files that have a corresponding "real" file in the actual file system. I'm trying to dynamically make an entry file and write it to the memory file system, but when I do that the produced bundle only contains an error log:

```js
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1);
	(function webpackMissingModule() { throw new Error("Cannot find module \"/Users/philipwalton/Projects/philipwalton/polyfill/src/code.js\""); }());


/***/ },
```

Even though the file is actually in the memory store, which I confirm by logging `console.log(mfs.readFileSync(path.resolve('src/code.js'), 'utf-8'));` in the success callback.

And this makes somewhat sense because it would be far too tedious to put *every* single possible file that may be required into the in-memory file system prior to generating the bundle, but it also means that I don't think it's possible to dynamically generate a source file without writing it to the file system first.

Please correct me if I'm wrong.

**Comment by skyrpex** [comment]
I completely forgot about that point. You're right!

**Comment by bebraw** [comment]
@skyrpex Is this still relevant?
