### ISSUE TITLE
Theres a way to watch/reload changes made over the template file ("html-webpack-plugin")

### ISSUE THREAD

**Issue by josoroma** [webpack/webpack#1321]
Hi!

There's only one thing I can't achieve right, and that's refresh the browser every time there is a change in the "index.html" template. Seems that Webpack plays well for the files defined in the "entry" property but not for this "index.html" template file outside the entry ones. Here is an extract from my config file:

```
var pluginHtml = require('html-webpack-plugin');
```
...
```
  plugins:[
    new pluginHtml({
      title: 'Angular Starter',
      template: './src/index.html'
    })
  ]
```

Thanks in advance!

**Comment by bebraw** [comment]
Maybe [webpack-service](https://www.npmjs.com/package/webpack-service) would work for this purpose.

**Comment by SpaceK33z** [comment]
This issue belongs at the [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin/issues) issue tracker. It doesn't reload your page because the current version doesn't use webpack's loaders. At the moment there is [a PR](https://github.com/ampedandwired/html-webpack-plugin/pull/41) that fixes this issue.

**Comment by bebraw** [comment]
Closing. Please track https://github.com/ampedandwired/html-webpack-plugin/pull/41 .
