### ISSUE TITLE
save bundles into localStorage

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#1322]
Do you plan to save packages into localStorage?
Many systems can do it . For an example - lmd.js

**Comment by shama** [comment]
Could you elaborate on this more? I am not familiar with lmd.js

**Comment by budarin** [comment]
https://github.com/azproduction/lmd/wiki/LocalStorage-cache
https://github.com/azproduction/lmd/blob/master/examples/plugins/cache_async/js/initializer.js

a small loadel check if the bundle of the version in localStorage - if no - it clears localStorage from different versions of bundles and then saves bundles in it.
Before every require to a server loader checks the localStorage for the nedeed bundle and if it absent in it - loads it from the server

**Comment by sokra** [comment]
No no plans. I don't see a need for this. Browser cache works perfect with webpack ([long term caching documentation](http://webpack.github.io/docs/long-term-caching.html). I don't see a way how localStorage should/can improve it.

**Comment by budarin** [comment]
Browser cache works perfect with webpack on desktops and fat channels, but on mobile devices chache is small and cost of reloading bundles is high!

**Comment by KevinEverywhere** [comment]
Why was this issue closed? This is such an important issue that is very hard to find an answer to by oneself. Why should one have to import angular again, for instance, when one changes files in the application that have nothing to do with the framework? Should we not be able to download the  framework once and then have it available in the future? The world does not share Bay Area bandwidth, and there are many users who will benefit from speed increase of localStorage vs download.

**Comment by hanai** [comment]
Using localstorage can save http request

**Comment by KevinEverywhere** [comment]
The issue comes from the bundling process: not much direction or support is given to those developers who would like to avoid forcing users to unload the same code over and over. It should be one of the goals of webpack to help with this process: the process of loading as little data as possible on secondary application visits. Only that which changes matters to the subsequent downloads.

**Comment by iamaddy** [comment]
@KevinEverywhere ,I can't agree with you anymore.In my application, I don't use webpack ,but i save javascript code into localStorage, that make my page more fast.

**Comment by sokra** [comment]
https://github.com/NekR/offline-plugin

@NekR

**Comment by KevinEverywhere** [comment]
@iamaddy , I am interpreting that as you agreeing, not that you have stopped agreeing! I think that this is still a very hot and important topic for webpack--they are today's big cheese for bundllng, but this is a big slice unhandled. Without a way to spread and minimize the download requirements of an app or page, a great portion of webpack-react content is large and downloaded repeatedly. Newcomers like rollup already take size into consideration, and helping developers select some content for download-save could do much for shrinking the requirements for download from webpack-bundled content.

**Comment by KevinEverywhere** [comment]
Two questions for @sokra, is this for development or the content in a page (i.e., to benefit the developer or the consumer); and 2., is this only supporting Chrome and Firefox (i.e., ServiceWorker dependent)?

http://caniuse.com/#search=serviceworker

**Comment by NekR** [comment]
@sokra thanks for ccing me 👍 

@KevinEverywhere I think you should ask those question to me since that was the he brought me here. There is everything in docs though, but I'll guide you through it and answer your questions.

> is this for development or the content in a page 

It's for production. Absolutely, there is no sense to do that in development unless your are just testing that functionality, in any other case that only would harm your development workflow.

> is this only supporting Chrome and Firefox (i.e., ServiceWorker dependent)?

It isn't dependent on ServiceWorker, but with ServiceWorker you get most of the features. When ServiceWorker isn't available, `offline-plugin` uses legacy AppCache to perform the caching. But even if was supporting only ServiceWorker, then that wouldn't be that bad anyway because Chrome + Firefox marketshare is nearly 70% of users, so that's pretty good amount. Not to mention that ServiceWorker is also being in development in Microsoft Edge right now.

**Comment by bebraw** [comment]
Let's close this for real this time as the plugin handles it.
