### ISSUE TITLE
Duplicated modules with multiple requires

### ISSUE THREAD

**Issue by leoselig** [webpack/webpack#1332]
I am having a lot of situations in which I am depending on some module from multiple files. I end up with the multiple occurances of that module in the output bundle, each of which has different id's. I would expect this module to occur once which is what I also need because most of these are singletons whose state I need accross the application.

So far I don't have any good starting point. Are there any typical causes for this?

**Comment by mdcone** [comment]
I'm seeing the same. From what I've read about it, the webpack loader is supposed to act just like the CommonJS loader in Node. However it appears that isn't currently the case because while using the same code I'm seeing different loading behaviors in each environment. I thought that the DedupePlugin would solve this issue for me, however the issue is the module system itself. 

There's a line in the ouputted __webpack_require__ function which says:
```
modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
```

I found by changing the outputted code to:

```
                if (modules[moduleId].loaded !== true) {
					// Execute the module function
					modules[moduleId].loaded = true;
					modules[moduleId].moduleIndex = moduleId;
					modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
				} else {
					module.id = installedModules[modules[moduleId].moduleIndex].id;
					module.exports = installedModules[modules[moduleId].moduleIndex].exports;
				
				}
```

Gives me the desired result. Instead of calling the module again to populate the module.exports with a new set of exports (thus re-instantiating the module) I will go look up the previously seen instance's exports and module id and just copy those over. I'm not sure if there are other side effects of this, but that's my 20 minute fix. We'll see if this should turn into a pull request or something later I suppose.
