### ISSUE TITLE
allowCollectingMemory is being normalized away

### ISSUE THREAD

**Issue by markjm** [webpack/webpack#13491]
# Bug report
normalization.js is removing allowCollectingMemory, not allowing us to set it in config

**What is the current behavior?**
allowCollectingMemory will always be default value

**If the current behavior is a bug, please provide the steps to reproduce.**
set allowCollectingMemory to false - note it remains true (in development)

**What is the expected behavior?**
allowCollectingMemory is settable

**Other relevant information:**
webpack version:  5.38.1
Node.js version: n/a
Operating System: n/a
Additional tools: n/a

**Comment by markjm** [comment]
To add some further information, I am having trouble understanding what this memory collection is supposed to do. `buffer.slice` is directly referencing the underlying larger buffer, meaning memory would be released once all the slices are de-referenced. It seems like doing these `buffer.from` copying is actually increasing memory while this is running (at the benefit of more quickly being able to GC the underlying large buffer).

It seems to me like the focus should be on making sure all underlying & sliced buffer references are cleaned up timely vs trying to do all these buffer copies

**Comment by sokra** [comment]
Many of these buffer slices resp. buffer copies are never collected since they are e. g. stored as source code of a Module. e. g. Modules will end up being stored in memory cache after deserializing.

Copying buffers allows to collect the larger buffer when
* only a part of the deserialized cache is used
* parts of the deserialized cache are thrown away later (e. g. in watch mode when no longer used or replaced with a new version)

I also dislike that we need to copy these buffers instead of slicing. It would be cool if that could be optimized by the GC instead of creating copies early on. Maybe it's possible to implement something with WeakRefs and FinializerRegistry...
