### ISSUE TITLE
Requiring gsap is broken

### ISSUE THREAD

**Issue by AlexGalays** [webpack/webpack#1356]
Hello,

When requiring gsap's CSSPlugin (and probably many other modules from that library) webpack chooses the AMD strategy and cannot find the "TweenLite" module at this line:

https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/plugins/CSSPlugin.js#L2592

I've not used AMD for years, and can't tell whether it's wrongly used by gsap (I suspect it is); If that's the case, how can they fix it ?

**Comment by SimenB** [comment]
https://github.com/umdjs/umd/blob/master/commonjsStrict.js

**Comment by AlexGalays** [comment]
Yes, I disabled AMD and it works; Just wished it could be fixed at the source instead of working around it on my side. Not sure what they're doing wrong with their UMD code?

**Comment by SimenB** [comment]
I don't know if there's anything wrong with it (except for being non-standard). The problem in the AMD-branch is that it expects to get `TweenLite` from somewhere, and unless you define where that is (using `alias`) it fails. CJS is a relative path, so that works fine.
It might work having the relative path in the amd definition as well, but I haven't used AMD in months, so I might very well be wrong :smile:

**Comment by bebraw** [comment]
If this is still a relevant problem, please report upstream to GSAP guys.
