### ISSUE TITLE
`module.rule.generator.emit = false` results in different emitted filenames

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack#13628]
# Bug report

**What is the current behavior?**

When `module.rule.generator.emit` is set to `false` for asset resources, webpack is supposed to emit the same filename as when it's set to `true`. This doesn't work correctly if there's an image minimizer in the chain, presumably because the minifier is only running when `{emit: true}` and ends up influencing the asset hash.

Note that this reproduces regardless of the asset filename, e.g., setting it to something like `[contenthash][ext]` does not fix the issue.

Not sure if this bug is specific to `image-minimizer-webpack-plugin` or generally an issue with webpack, so I'm reporting it in both places. (See https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/217.)

**If the current behavior is a bug, please provide the steps to reproduce.**

[Here](https://github.com/billyjanitsch/webpack-bug-emit-hash) is a minimal reproduction. See the readme and test file for details.

**What is the expected behavior?**

The emitted filename should always the same, regardless of whether `emit` is set to `true` or `false`. See the failing test case in the repo.

**Other relevant information:**
webpack version: 5.40.0
Node.js version: 14.17.0
Operating System: macOS
Additional tools:

**Comment by alexander-akait** [comment]
> Not sure if this bug is specific to image-minimizer-webpack-plugin or generally an issue with webpack, so I'm reporting it in both places. (See webpack-contrib/image-minimizer-webpack-plugin#217.)

Firstly we need found place where bug stored, when we will fix or move the issue in other repo

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/217

**Comment by makaria** [comment]
remove `|| this.emit === false` in getTypes will produce correct contenthash when emit is false

https://github.com/webpack/webpack/blob/e518d0da94639476354f028cdf032de4be6813a0/lib/asset/AssetGenerator.js#L402

maybe related: https://github.com/webpack/webpack/commit/7572217e97c94a43a7bd62d6d27da2100e537ea6

**Comment by makaria** [comment]
turn out it's because the problem gif's full hash is `63269829566710439434dae6582fa16f9345afbf`, and it's first 20 characters is pure number, when hash is pure number, [nonNumericOnlyHash](https://github.com/webpack/webpack/blob/main/lib/util/nonNumericOnlyHash.js) will add `a` prefix to make hash has at least one non numeric char.

need option opt out this behavior, we need real hash only

https://github.com/webpack/webpack/blob/e518d0da94639476354f028cdf032de4be6813a0/lib/asset/AssetGenerator.js#L303-L306

https://github.com/webpack/webpack/blob/e518d0da94639476354f028cdf032de4be6813a0/lib/util/nonNumericOnlyHash.js#L8-L22

related: https://github.com/webpack/webpack/commit/f1d329cc0e5241327575d3b3d6f491ff95773c8b
