### ISSUE TITLE
Inline loaders are ignore in webpack 5

### ISSUE THREAD

**Issue by artaommahe** [webpack/webpack#13683]
# Bug report

**What is the current behavior?**

Inline loaders are ignored if webpack configuration has rules for these files.

```ts
const testImage = require('!file-loader!./images/test-image.png');
const testIcon = require('!html-loader!image-webpack-loader!./images/test-icon.svg');

console.log('> testImage', testImage);
console.log('> testIcon', testIcon);
```

```js
// from storybook's webpack configuration
{
  test: /\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
  type: 'asset/resource',
  generator: { filename: 'static/media/[path][name].[ext]' }
}
```

results in 
```
> testImage file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-image..png
> testIcon file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-icon..svg
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/artaommahe/webpack-5-inline-loaders

code https://github.com/artaommahe/webpack-5-inline-loaders/blob/main/src/index.js
webpack config https://github.com/artaommahe/webpack-5-inline-loaders/blob/main/webpack.config.js

- git clone
- yarn install
- yarn webpack
- open `dist/index.html`
- see undefined for images and this in console
  ```
  > testImage file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-image..png
  > testIcon file:///D:/projects/tests/webpack-5-inline-loaders/dist/static/media/src/images/test-icon..svg
  ```
- comment out images rule in webpack config
- yarn webpack
- see expected result as 
  ```
  > testImage Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}default: "file:///D:/projects/tests/webpack-5-inline-loaders/dist/6af9ab209f7be65032e1462798741a97.png"
  > testIcon Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}default: "<svg ..."
  ```

Same if `!!` is used.

**What is the expected behavior?**

Expected result is overriding rule with the inline loaders as it worked in webpack 4.x.

**Other relevant information:**
webpack version:  5.41.1
Node.js version: 12.18.1
Operating System: Win10
Additional tools:
```
"file-loader": "^6.2.0",
"html-loader": "^2.1.2",
"html-webpack-plugin": "^5.3.2",
"image-webpack-loader": "^7.0.1",
"webpack": "^5.41.1",
"webpack-cli": "^4.7.2"
```

first found in https://github.com/storybookjs/storybook/issues/15438, than narrowed to the clean webpack's issue

**Comment by alexander-akait** [comment]
Works as expected `file-loader` is not compatibility with asset modules

**Comment by alexander-akait** [comment]
Also `[ext]` includes `.` (dot), you should not specify `.` when you use `[ext]`

**Comment by alexander-akait** [comment]
`image-webpack-loader` should be used as pre loader, because it is compression and not affected on output format (i.e. commonjs or es modules) https://webpack.js.org/configuration/module/#ruleenforce

**Comment by wafflepie** [comment]
@alexander-akait Are inline loaders going to be deprecated soon?

I maintain an internal library of React components where SVG icons are imported like this:

```
import(`!!babel-loader?{"plugins":["module:@ci/atoms/babel.cjs"],"presets":["@babel/preset-env","@babel/preset-react"]}!@svgr/webpack?+titleProp,+ref,+icon,-babel!./assets/${type}.svg`);
```

It's really ugly, but it allows the library to be used in any Webpack application without needing to rely on some specific config, so it's one less thing to track in a plethora of different applications. The SVG icons are thus plug'n'play in both Storybook and Gatsby ([well, not anymore](https://github.com/storybookjs/storybook/issues/15438)), as well as applications with a custom Webpack config.

What do you believe is the best solution? Should Storybook not use any convenience asset module rules? We are currently doing this (so we don't break all the other applications):

```
config.module.rules.forEach(rule => {
  if (rule.type === 'asset/resource') {
    // https://github.com/storybookjs/storybook/issues/15438
    rule.test = new RegExp(rule.test.source.replace('svg|', ''), rule.test.flags);
  }
});
```

Maybe Webpack could consider `!!` at the start of the import so the asset module rules won't take effect at all? Since it already kinda means "I'll handle it myself".

**Comment by alexander-akait** [comment]
We have `!=!` syntax for complex cases, look at here https://github.com/webpack/webpack/issues/11074#issuecomment-648658214

**Comment by alexander-akait** [comment]
Also we prepare new version of `image-minimizer-webpack-plugin`https://github.com/webpack-contrib/image-minimizer-webpack-plugin/`  and describe a lot of cases, so you can migrate from `image-webpack-loader` on good, full featured and cachable version

**Comment by wafflepie** [comment]
@alexander-akait Thanks a lot for the response. I've managed to get a single icon working:

```
`calendar.js!=!@svgr/webpack!./assets/calendar.svg`
```

SVGR now correctly transforms the SVG file to a React component and no `.svg` rules apply. The issue comes with using an expression to import the icons.

```
`${type}.js!=!@svgr/webpack!./assets/${type}.svg`
```

This doesn't work for me, the resulting file contains

```
(self["webpackChunk_cbs_instance_lka"] = self["webpackChunk_cbs_instance_lka"] || []).push([["shared-libs_atoms_src_components_Icon_assets_calendar_svg"],{

/***/ "../../shared-libs/atoms/src/components/Icon/assets/calendar.svg":
/*!***********************************************************************!*\
  !*** ../../shared-libs/atoms/src/components/Icon/assets/calendar.svg ***!
  \***********************************************************************/
/***/ (function(module) {

module.exports = "data:image/svg+xml;base64,PHN...

/***/ })

}]);
```

Is it possible to use the `!=!` syntax somehow with these expressions?

I'm thinking about ditching `.svg` altogether and using some random extension instead, but I'm still curious if this is possible somehow, because it'd be easier to inspect the icon assets manually.

**Comment by alexander-akait** [comment]
> Is it possible to use the !=! syntax somehow with these expressions?

Can you clarify? Maybe you can create small repo with example what do you want to achieve and I will help you

**Comment by wafflepie** [comment]
Sure, I'll prepare a repo and get back to you, thanks!

**Comment by wafflepie** [comment]
@alexander-akait https://github.com/wafflepie/reproduction-svgr-webpack `yarn && yarn start`

For some reason, this reproduction throws an error instead of emitting a file with a data URI, but the fully static import works fine.

**Comment by alexander-akait** [comment]
Hm, works fine:
```js
import { renderToString } from "react-dom/server";
import { createElement } from "react";

const importFooAsset = () => import(`!@svgr/webpack!./assets/foo.svg`);

const importDynamicAsset = (type) =>
  import(`!@svgr/webpack!./assets/${type}.svg`);

(async () => {
  const foo = await importFooAsset();
  console.log(renderToString(createElement(foo.default))); // React component, renders an SVG element.

  const bar = await importDynamicAsset("bar"); // Error: Cannot find module 'bar.js!=!@svgr/webpack!./assets/bar.svg'
  console.log(renderToString(createElement(foo.default)));
})();
```

```bash
yarn run v1.22.10
$ rimraf dist && webpack && node dist/main
asset main.js 220 KiB [emitted] (name: main)
asset node_modules_svgr_webpack_lib_index_js_assets_bar_svg.js 2.31 KiB [emitted]
asset node_modules_svgr_webpack_lib_index_js_assets_baz_svg.js 1.77 KiB [emitted]
asset node_modules_svgr_webpack_lib_index_js_assets_foo_svg.js 1.61 KiB [emitted]
runtime modules 2.05 KiB 6 modules
cacheable modules 213 KiB
  modules by path ./node_modules/ 210 KiB
    modules by path ./node_modules/react-dom/ 137 KiB 3 modules
    modules by path ./node_modules/react/ 70.6 KiB
      ./node_modules/react/index.js 190 bytes [built] [code generated]
      ./node_modules/react/cjs/react.development.js 70.5 KiB [built] [code generated]
    ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
  modules by path ./assets/*.svg 2.79 KiB
    ./node_modules/@svgr/webpack/lib/index.js!./assets/foo.svg 679 bytes [built] [code generated]
    ./node_modules/@svgr/webpack/lib/index.js!./assets/bar.svg 1.31 KiB [optional] [built] [code generated]
    ./node_modules/@svgr/webpack/lib/index.js!./assets/baz.svg 839 bytes [optional] [built] [code generated]
  ./index.js 591 bytes [built] [code generated]
./assets/ lazy !./node_modules/@svgr/webpack/lib/index.js! ^\.\/.*\.svg$ namespace object 160 bytes [built] [code generated]
external "stream" 42 bytes [built] [code generated]
webpack 5.42.1 compiled successfully in 589 ms
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42.52 42.52" data-reactroot=""><circle cx="21.26" cy="21.26" r="21.26"></circle></svg>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42.52 42.52" data-reactroot=""><circle cx="21.26" cy="21.26" r="21.26"></circle></svg>
Done in 0.90s.
```

webpack config:
```
module.exports = {
  entry: "./index.js",
  mode: "development",
  target: "node",
  devtool: false,
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: "url-loader",
        type: 'javascript/auto'
      },
    ],
  },
};
```

but you can safely remove `url-loader`:
```
module.exports = {
  entry: "./index.js",
  mode: "development",
  target: "node",
  devtool: false,
};
```

I am missing something?

And sorry for delay

**Comment by wafflepie** [comment]
@alexander-akait I can't use `!@svgr/webpack!./assets/${type}.svg` because we're trying to avoid the `asset/resource` rule.

I've updated the reproduction repository to include the original issue we're trying to avoid, here's a quick recap:

1. Some existing application (whose Webpack config I don't want to modify) uses `asset/resource` for SVGs.
2. I want to skip this rule and instead supply my own set of loaders in the import expression (doesn't work with just `!` at the start).
3. Apparently, this is possible using `!=!` which works well for "static" imports, i.e. `foo.js!=!@svgr/webpack!./assets/foo.svg`.
4. Once I need to use dynamic expressions, i.e. `${type}.js!=!@svgr/webpack!./assets/${type}.svg`, this fails.

All applications in our ecosystem use Webpack and have arbitrary configs. I want to have a component which is usable in any of them, because it configures its own loaders and is thus fully plug'n'play.

**Comment by alexander-akait** [comment]
Why not register svgr loader on `resourceQuery` and using `./assets/foo.svg?type=svgr`? It is real weird, we try to avoid inline syntax and strongly recommend do not use it, it is old legacy stuff, we are on es modules, so we can use `query` or `assert` (will be in near future)

**Comment by artaommahe** [comment]
> we try to avoid inline syntax and strongly recommend do not use it, it is old legacy stuff, we are on es modules, so we can use query or assert (will be in near future)

For us the main issue is tooling and different webpack configs. E.x. angular and storybook for angular use different loaders at least for images. For consistent behavior we have to use inline loaders, but now they are ignored by assets modules rules and we have to fine-tune storybook's webpack config... It doesn't look like scalable solution.

**Comment by wafflepie** [comment]
@alexander-akait Sure, I can find a workaround and this would probably work pretty well. I was just hoping/asking if there is a supported solution where it wouldn't be necessary to modify the Webpack config at all, because this would require modifying 5 of them on our side if we dropped the inline loaders completely (just because of a single React component with specific requirements).

If this is not planned/supported, that's fine. I just wanted to raise awareness of my particular use case (which doesn't seem that unreasonable to me).

**Comment by alexander-akait** [comment]
To be honestly inline loader syntax is hack from the past, when dreamed about ES modules, now we have them and even more we have `import foo from './something.ext' assert { type: "something" }`, of course we can probably see how improve inline syntax for as context requests, but I think we need to get away from this syntax as soon as possible in favor `import something from './something?query'` and in future in favor import assertion. I can open this problem, but again, most likely it will not be fixed in the near future and perhaps never...

**Comment by alexander-akait** [comment]
Also we merged https://github.com/webpack/webpack/pull/12278, so you can try it on the next release, I think it is great syntax/feature :star:
