### ISSUE TITLE
When specified, "proxy"  in package.json must be  a string or an object.  

### ISSUE THREAD

**Issue by shen-lan** [webpack/webpack#13727]
1、`Vue Project`. `vue.config.js`
```
When specified, "proxy" 
in package.json must be 
a string or an object.  
Instead, the type of "proxy" was "object".      
Either remove "proxy" from package.json, or make it an object.
```
2、the code:

    proxy: [
      {
        context: ['/auth', '/api'],
        target: 'http://localhost:3000'
      }
    ]

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Pleask ask this in vue-cli repo, anyway there is recommendation how to fix the problem, please follow this
