### ISSUE TITLE
When different devices compile the same code, the hash of file name is different

### ISSUE THREAD

**Issue by jiao1187875445** [webpack/webpack#13910]
When my colleagues and I compile the same project on different systems, or even in different directories of the same system, the file hash of the compilation result is different. Is there any solution to make the hash generation independent of the absolute path

**Comment by jiao1187875445** [comment]
webpack 4

**Comment by jiao1187875445** [comment]
This leads to submitting all the compiled code almost every time you submit the code, which is time-consuming and unfriendly to the browser cache

**Comment by csvan** [comment]
Use `contenthash`

https://webpack.js.org/guides/caching/#output-filenames

**Comment by sokra** [comment]
webpack 5 with `[contenthash]` will create a hash of the file content.

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
