### ISSUE TITLE
BuildDependencies in cache not update 

### ISSUE THREAD

**Issue by killagu** [webpack/webpack#13916]
# Bug report

**What is the current behavior?**
I'm using webpack to bundle my project, if `BuildDependencies` in cache configuration is updated but the cache pack is not invalid, the pack will not updated.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use this repo: https://github.com/killagu/webpack-cache-bug/
1. Run `npm run build`
2. Run `npm run build2`

The cache will not update.

**What is the expected behavior?**
Update the cache to ensure all `BuildDependencies` will be checked in next bundle.

**Other relevant information:**
webpack version:  5.48.0
Node.js version: v14.16.0
Operating System: MacOS
Additional tools:

**How to fix it?**
```js
// https://github.com/webpack/webpack/blob/main/lib/cache/PackFileCacheStrategy.js#L1116
- if (!pack.invalid) return;
this.logger.log(`Storing pack...`);
let promise;
const newBuildDependencies = new Set();
for (const dep of this.newBuildDependencies) {
	if (!this.buildDependencies.has(dep)) {
		newBuildDependencies.add(dep);
	}
}
+ if (!pack.invalid && !newBuildDependencies.size) return;
```

If it's right, I'm glad to fix it.

**Comment by alexander-akait** [comment]
Solution is still invalid. 

Firstly you have two different builds and store them in the same directory, in this case you should `cache.version` (https://webpack.js.org/configuration/cache/#cacheversion), you have different `buildDependencies` so I think it is different build.

Anyway we can solve it, but in this case we should compare `this.buildDependencies` and `newBuildDependencies`, because you can not only add them and also delete them, in your solution deleting new build dependencies still use old cache.

**Comment by killagu** [comment]
@alexander-akait Thank you for replay. Use `cache.version` to solve is a good idea.

**Comment by alexander-akait** [comment]
Anyway let's mark it as enhancement

**Comment by sokra** [comment]
Deleting build dependencies is not valid. They have to stay in the cache, since cache entries have been created with these build dependencies.
