### ISSUE TITLE
Shimming window["jQuery"]

### ISSUE THREAD

**Issue by blazkovicz** [webpack/webpack#1406]
This configuration does not replace window["jQuery"] with require("jquery") in knockout (v. 3.3.0) module.
What should I do to avoid exposing jQuery in window and provide knockout with jQuery?
```javascript
new webpack.ProvidePlugin({
      'window.jQuery': 'jquery',
      'jQuery': 'jquery',
      'window["jQuery"]': 'jquery'
    })
```

**Comment by SpaceK33z** [comment]
It could be that the jquery dependency in knockout does not match with your included jquery. I had an issue like that with Backbone, and finally fixed it by adding this to the webpack config:

```
resolve: {
    alias: {
        'jquery': require.resolve('jquery'),
    }
}
```

**Comment by blazkovicz** [comment]
Your solution exposes global variable jQuery, I want to avoid that.

**Comment by SpaceK33z** [comment]
That's not true, it doesn't expose anything. It only forces the use of `node_modules/jquery` instead of e.g. `node_modules/knockout/node_modules/jquery`

**Comment by blazkovicz** [comment]
That's not my case.

**Comment by jhnns** [comment]
The guys from knockout have put a lot of effort to "protect" their code against unwanted changes :grinning:...
it would be better if they'd actually `require("jquery")` in case a module system is detected. [Just as recommended by the UMD](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js).

However, the `ProvidePlugin` does not work, because `window["jQuery"]` is not an identifier, but a property access. It would have been worked, if they'd just accessed `jQuery`.

There is actually no other way than exposing the `jQuery`-object to window. Every other attempt is not worth the effort imho. But you could send a PR to knockout and tell them, that it's impossible to use their library without global variables.

**Comment by blazkovicz** [comment]
@jhnns Yes, I already added comment to their issue regarding amd, but they do not hurry with the solution. `ProvidePlugin` has examples for `window.jQuery` replacement, so I thought `window['jQuery'] ` should work too.

**Comment by jhnns** [comment]
Yep, sorry about that, my examples on Stackoverflow were wrong. I've corrected them.

**Comment by rosenfeld** [comment]
@blazkovicz, if you are still interested on this, I solved this issue on my own by using a custom loader (maybe adding a generic text replacement loader would be a better solution):

ko-loader.js:
```javascript
module.exports = function(source) {
  this.cacheable();
  return source.replace('jQueryInstance = window["jQuery"]', 'jQueryInstance = require("jquery")');
};
```

in webpack.config.js:

```javascript
    ,resolveLoader: {
      alias: { 'ko-loader': __dirname + '/ko-loader' }
    }
    ,module: {
        loaders: [
          { test: /knockout-latest\.debug\.js$/, loader: 'ko-loader'}
        ]
    }
```

I hope that helps.

**Comment by blazkovicz** [comment]
@rosenfeld, thanks! I'll try that. What's the `this.cachable();`?

**Comment by rosenfeld** [comment]
`this.cacheable` tells webpack the output of that function can be cached and won't change for a given source. Most loaders should be flagged as cacheable and this is not an exception. I guess it will only make any difference when you are using `--watch` or the dev server since webpack only seems to support in-memory caching...
