### ISSUE TITLE
How to close warnings while compiling

### ISSUE THREAD

**Issue by Dennisic** [webpack/webpack#14073]
see pic 
![image](https://user-images.githubusercontent.com/65406422/131059127-b534f0e5-99da-4fc5-a8d7-4cfb149f9141.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
