### ISSUE TITLE
how can webpack get variables of src files ?

### ISSUE THREAD

**Issue by dongshuangshuang** [webpack/webpack#14088]
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
