### ISSUE TITLE
browserslist target throws when Babel can understand it 

### ISSUE THREAD

**Issue by eps1lon** [webpack/webpack#14203]
# Bug report

**What is the current behavior?**

Using the following `.browserslistrc` that was generated a few weeks back with `npx browserslist --mobile-to-desktop "> 0.5%, last 2 versions, Firefox ESR, not dead, not IE 11"` throws.

```
and_chr 91
and_ff 89
and_qq 10.4
and_uc 12.12
android 91
baidu 7.12
chrome 90
edge 91
firefox 78
ios_saf 12.4
kaios 2.5
op_mini all
op_mob 76
opera 76
safari 14
samsung 13.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
$ git clone https://github.com/eps1lon/webpack-targets-browserslist
$ yarn
$ yarn start
```

**What is the expected behavior?**

Webpack is able to understand this browserlist since Babel is able to. See https://github.com/babel/babel/issues/12123 for more context.

**Other relevant information:**
webpack version:  5.52.0
Node.js version: 12.22.6
Operating System: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
Additional tools: browserslist@4.17.0, caniuse-lite@1.0.30001255

**Comment by alexander-akait** [comment]
> mobileToDesktop: Use desktop browsers if Can I Use doesn’t have data about this mobile version. For instance, Browserslist will return chrome 20 on and_chr 20 query (Can I Use has only data only about latest versions of mobile browsers). Default is false.

I don't think we should enable it by default, better to throw error on wrong browserslist entries, it will allow developer validate which browser should be used

/cc @ai

**Comment by ai** [comment]
`mobileToDesktop` is a very specific option just for Babel because they have a limited database (without data for mobile browsers)

For instance, we do not use it in Autoprefixer since we are using prefixes accroding to Can I Use database which have this data.

But how webpack is using Browserslist?

I am not fully get the issue? What is an error if somebody is throwing something on this config?

**Comment by alexander-akait** [comment]
@ai no magic just load config and pass it to browserslist https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L54

> I am not fully get the issue? What is an error if somebody is throwing something on this config?

browserslist just throw an error about unknown entry due `android 91`

**Comment by alexander-akait** [comment]
This is probably the question, should we use `mobileToDesktop` option or not?

**Comment by ai** [comment]
> This is probably the question, should we use mobileToDesktop option or not?

I think not. It is better to use `mobileToDesktop` option on Babel level on top of browsers from webpack

**Comment by ai** [comment]
Because `mobileToDesktop` is a specific Babel hack. It could leads to compatibility data losses for other tool

**Comment by eps1lon** [comment]
> Because `mobileToDesktop` is a specific Babel hack. It could leads to compatibility data losses for other tool

Could you explain this with a concrete example? "it's a babel hack" is not really helpful since what constitutes a hack is subjective.

@JLHwung Could you maybe shine some light on why you use `mobileToDesktop` in Babel? As a Webpack and Babel user, an inconsistent behavior between these two libraries is the worst solution. Would be nice if we could agree on the best behavior.

**Comment by ai** [comment]
Mobile browsers are not 100% equal to desktop browsers. Sometimes some feature is available only in desktop browser. With `mobileToDesktop` you may have wrong compatibility data because you converted all mobile browsers to desktop browsers.

It is not so critical for JS, since JS VM are more often similar between mobile and desktop. But it is more critical for data formats.

Simple non-real example:

1. User has `.browserslistrc` with `last 1 FirefoxAndroid version`
2. With `mobileToDesktop` option, Browserslist will return `ff 92`. Without this option, it will return `and_ff 92`.
3. If we have a webpack loader for video compression, with `mobileToDesktop` option loader will use AV1 (because desktop version of Firefox [supports](https://caniuse.com/?search=av1) AV1). But it will be wrong because mobile version doesn’t support it.

**Comment by alexander-akait** [comment]
@ai Maybe it is good idea to add this to browserslist docs

**Comment by ai** [comment]
Babel uses `mobileToDesktop` because they do not have support data for `ESx` features for mobile browsers. They have only data about desktop users.

For JS runtime, it is more likely to assume that desktop and mobile versions will have the same ES features. It is a hack (since we can’t 100% guarantee the same version of JS VM in mobile and desktop), but it is pretty safe to use it in this context.

**Comment by ai** [comment]
*Seems like I was wrong in previous comment. I deleted it.*

How `mobileToDesktop` option works:

1. By default, `last 2 and_ff versions` will return only `and_ff 90`. Only 1 version because Can I Use have only data for latest mobile Firefox version.
2. With `mobileToDesktop`, `last 2 and_ff versions` will return `and_ff 91, and_ff 90`. This option is assuming that mobile browsers have the same versions that desktop browsers and is using desktop browsers’ data.

The problem with `mobileToDesktop` is that browsers is not correct Can I Use versions. Autoprefixer (who uses Can I Use to get data about the prefixes) will not be able to use `and_ff 91` data.

Here is an example:

1. User is using `last 1 and_ff versions`
2. With `mobileToDesktop` Browserslist returns `and_ff 91`.
3. Autoprefixer doesn’t find any vendor prefixes for `and_ff 91` (because Can I Use data has only `and_ff 90` data) and will not insert vendor prefixes for mobile Firefox.

**Comment by ai** [comment]
I improved docs https://github.com/browserslist/browserslist/commit/49af84894d7eb8a043f2b063f62efed71bb9ca09

**Comment by alexander-akait** [comment]
So I think we're doing it right, there is a chance of a difference in JS syntax/API and this can lead to the generation of incorrect code

**Comment by ai** [comment]
> So I think we're doing it right, there is a chance of a difference in JS syntax/API and this can lead to the generation of incorrect code

In one hand, yeap we can’t use non-`mobileToDesktop` result in Babel.

In other hand, using `mobileToDesktop` for everyone will lead to `unknown version` error.

Maybe the best option is to read Browserslist config, but do not convert it to browser versions. Pass it as queries, so every tool will convert it to versions according to their options.

**Comment by alexander-akait** [comment]
@ai we only pass query or config to browserslist and nothing more

**Comment by ai** [comment]
@alexander-akait in this case I do not understand where the error is coming from

**Comment by alexander-akait** [comment]
and lots of bugs in versions, so this was rewritten to this

**Comment by ai** [comment]
Got it. The error happened because `.browserslistrc` was generated from `--mobile-to-desktop` output.

@eps1lon you should not do it. It is better to keep origin queries in `.browserslistrc`. Your Browserslist config is invalid. For instance, Autoprefixer will not work with it.

**Comment by vankop** [comment]
@alexander-akait should we close this in favor of #14226 ?

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/issues/14226 is not related to this, but we can close it, using `mobileToDesktop` is not safe and can lead to wrong generation of runtime

Anyway feel free to feedback
