### ISSUE TITLE
feature request: createRequire detect

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack#14228]
## Feature request

**What is the expected behavior?**

For code like below:

```js
import { createRequire as _createRequire } from 'module'
const __require = _createRequire(import.meta.url)
```

`__require` should be detected as an alias of CommonJS require and the imported module of `__require` should be the type of `javascript/auto` instead of `javascript/esm`.

**What is motivation or use case for adding/changing the behavior?**

This allows webpack to bundle this format of ESModule projects.

And [TypeScript is going to add Node-12 module emit](https://github.com/microsoft/TypeScript/pull/44501) which will generate code like above.

**How should this be implemented in your opinion?**

Detect import of `module` module and track the pattern of `const $requireAlias = $importedCreateRequire(import.meta.url)`.

**Are you willing to work on this yourself?**
yes but I'm not familiar with webpack internal.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by Jack-Works** [comment]
Hi, @alexander-akait I have created a PR at #14241, but I'm not familiar with webpack internals and want some helps.

I tested with the following code:

> index.mjs
```js
import { createRequire as _createRequire } from "module";
const __require = _createRequire(import.meta.url);
const mod = __require("./cjs.cjs");
console.log(mod.a);
```

> cjs.cjs
```
module.exports.a = 1;
```

With the current process in #14241, I'd be able to add `cjs.cjs` into the compilation. But I encountered the following problems:

- I don't know how to edit AST so I can remove `import { createRequire as _createRequire } from "module"; const __require = _createRequire(import.meta.url);` these two lines of code.
- I don't know how to replace `__require` to `__webpack_require_`.

The current emit is:

```js
"use strict";
// ./index.mjs
__webpack_require__.r(__webpack_exports__);
Object(function webpackMissingModule() { var e = new Error("Cannot find module 'module'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());

const __require = Object(function webpackMissingModule() { var e = new Error("Cannot find module 'module'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())("MY_LOCAL_FILE_PATH");
const mod = __require(/*! ./cjs.cjs */ "./cjs.cjs");
console.log(mod.a);
```

And I think the correct way to do this is to remap the aliased name (`__require` in the case above) of require I detected to the `CommonJsImportsParserPlugin.js` so `require.resolve` and other functions work too. But I don't have any idea how to do that.

**Comment by alexander-akait** [comment]
Bad idea to use `cjs.cjs`, there are another module with the same name

**Comment by alexander-akait** [comment]
Also you can use `import { createRequire } from 'module'`

**Comment by Jack-Works** [comment]
> Also you can use `import { createRequire } from 'module'`

Actually, I'm using the code generated by the new emit target of TypeScript (module=node12). I need to make sure I have tracked the aliased name of imported `createRequire` instead of trying to match any specified name. Otherwise, it will not work with generated code.

And the test code I wrote (`index.mjs` and `cjs.cjs`) doesn't important, I just want to do the code transform as code written in #14241

**Comment by alexander-akait** [comment]
We should not supported only edge cases, we should support all possible cases

**Comment by vankop** [comment]
bump

**Comment by Jack-Works** [comment]
Cool!

**Comment by paztis** [comment]
I reopen this issue

I'm trying to bundle a nodejs application that uses prettier inside

prettier has got a index.mjs file starting like this:

`
import { createRequire as __prettierCreateRequire } from "module";
import { fileURLToPath as __prettierFileUrlToPath } from "url";
import { dirname as __prettierDirname } from "path";
const require = __prettierCreateRequire(import.meta.url);
const __filename = __prettierFileUrlToPath(import.meta.url);
const __dirname = __prettierDirname(__filename);

...

var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
  get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
  if (typeof require !== "undefined") return require.apply(this, arguments);
  throw Error('Dynamic require of "' + x + '" is not supported');
});
`

It is transformed like this by webpack
`
const require = (0,module__WEBPACK_IMPORTED_MODULE_0__.createRequire)("file:///usr/xxxx/node_modules/prettier/index.mjs");
const __filename = (0,url__WEBPACK_IMPORTED_MODULE_1__.fileURLToPath)("file:///usr/xxxx/node_modules/prettier/index.mjs");
const __dirname = (0,path__WEBPACK_IMPORTED_MODULE_2__.dirname)(__filename);

...

var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
  get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
  if (typeof require !== "undefined") return require.apply(this, arguments);
  throw Error('Dynamic require of "' + x + '" is not supported');
});
`

Because of this I face 2 problems:
- things loaded through __required are not catch at all by webpack
(gracefully the only load native nodejs modules so it works)
- my delivery build is done on a linux machine. When I execute on a windows machine the result, it crash with this message
`
 uncaughtException: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file://us/xxxx/node_modules/prettier/index.mjs' TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string.

` 

Because it is a linux filepath and not a windonw one.
So packaging is totally blocked with this issue.

Any idea how to solve / workaround it ?


I try to point on the cjs delivery of prettier, but it is totally useless as teh cjs imports internally the mjs.

Thanks for the info

**Comment by alexander-akait** [comment]
You can disable `import.meta.url` parse for module - https://webpack.js.org/configuration/module/#moduleparserjavascriptimportmeta, but your logic in code can be broken, when you bundle you have only one file and in different place, so logic where you need path and load something by this path may be incorrect

**Comment by paztis** [comment]
but this is disabling it for the full bundling, not only for this problematic case.
In the other places it is well done.

**Comment by alexander-akait** [comment]
Just set it for module where you can disable it

**Comment by paztis** [comment]
In this case, import.meta.url will be resolved at runtime ?
I generate a commonjs module not an esm one

Le jeu. 13 mars 2025, 16:54, Alexander Akait ***@***.***> a
écrit :

**Comment by alexander-akait** [comment]
> In this case, import.meta.url will be resolved at runtime ?
> I generate a commonjs module not an esm one

No, we just will not transform `import.meta.url`, it means you need a babel plugin for such module to handle this sutiation propertly
