### ISSUE TITLE
Support dead code elimination

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#1433]
``` js
import _ from 'lodash';

_.noop();
```

Even though I do nothing with `lodash` package, `webpack` will import the entire `lodash` package.

[Tree shaking](http://blog.sethladd.com/2013/01/minification-is-not-enough-you-need.html) is possible when the entire code base is ES6 and uses import statements, e.g.

foo.js:

``` js
let a = 'A',
    b = 'B';

export {
    a,
    b
}
```

bar.js:

``` js
import {a} from './foo.js'
```

In this scenario, webpack ought to eliminate the definition of `b` from the generated code.

**Comment by IngwiePhoenix** [comment]
Why does this only work on  ES6 and not ES5?

**Comment by gajus** [comment]
Because of the dynamic nature of ES, e.g.

```js
var _ = require('lodash');

_[Math.random()];
```

**Comment by gajus** [comment]
As opposed to if you are using import statement and explicitly define dependencies, you cannot dynamically request anything has not been loaded, e.g.

```js
import {noop} from 'lodash';
```

**Comment by gajus** [comment]
I have further explained the issue here, https://github.com/esdiscuss/esdiscuss.org/issues/91.

**Comment by sokra** [comment]
yep. I also have this in my mind, but need to focus on other stuff first.

**Comment by gajus** [comment]
I later come across a simple babel plugin that does this specifically for lodash, [`babel-plugin-lodash`](https://github.com/megawac/babel-plugin-lodash).

**Comment by david0178418** [comment]
That plugin is awesome.  It would be great to see webpack do the tree-shaking natively to get this benefit across the board, though.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/tree/webpack-2/examples/harmony-unused

**Comment by trusktr** [comment]
@sokra If we're importing CommonJS modules via ES6 syntax, what does that imply for tree shaking? For example, lodash's modules are CommonJS (the NPM version of lodash). So what would the following imply?

```js
import debounce from 'lodash/function/debounce'
```

What I mean is, without looking at the debounce.js file, what can we accurately assume with regards to CommonJS modules? Specifically, will we loos some ability to statically analyze the import due to the fact that there can be conditional require statements? Will all require statements be treated as top-level imports and always imported, letting the conditionals simply run at run time (with the possibility of some module never being used but still included in the bundle)? And the same with AMD?

**Comment by SimenB** [comment]
https://www.npmjs.com/package/lodash-es

**Comment by sokra** [comment]
@trusktr This currently only affects es6 modules importing es6 modules.

**Comment by bebraw** [comment]
There's tree shaking now. The lodash webpack plugin is cool too. Please open specific issues if you run into problems.

**Comment by Kovensky** [comment]
Tree shaking unfortunately doesn't help with the lodash (or lodash-es) situation, see https://github.com/webpack/webpack/issues/1750.

Even with lodash-es, a module where no imports are used must still execute according to spec.
