### ISSUE TITLE
Add a 'webworker' field for bundler

### ISSUE THREAD

**Issue by stevemk14ebr** [webpack/webpack#14681]
## Feature request

**What is the expected behavior?**
A `target` of webworker should first look for a `webworker` field, rather than `browser` first as it currently is.

**What is motivation or use case for adding/changing the behavior?**

> from: https://webpack.js.org/configuration/resolve/#resolvemainfields
> When importing from an npm package, ... this option will determine which fields in its package.json are checked. The 
> default values will vary based upon the target specified in your webpack configuration. When the target property is set to webworker, web, or left unspecified the following fields are checked in order
> mainFields: ['browser', 'module', 'main'],

some libraries guard usage of keywords like `document` or `window` behind bundler fields like `browser`. This is important for code minification and switching implementation APIs depending on the final environment. There currently is no default field to describe the environment web workers live in. They are _mostly_ the `browser` environment but without access to DOM apis, which is an important distinction. Trying to using a library that uses DOM apis in a web worker will fail. Currently library authors have no way to specify `browser` vs `webworker` difference. 

Please see https://github.com/wooorm/parse-entities/issues/19 for a case where this matters. This library uses `document.createElement` for the browser implementation, and has an alternative field `react-native` for non-browser API implementation. By default webpack uses the `browser` field which causes webworkers to bundle incorrectly. There is no way for the library author to fix this, as there is no default `webworker` field that is tried first when the target is set to `webworker`. [Here](https://github.com/wooorm/parse-entities/blob/6d7cef95baa04c3430f929cb017b541f54b9e863/package.json#L28-L33) is where the library defines it's two fields to switch implementation depending on the bundler `target`

**How should this be implemented in your opinion?**
A new field `webworker` should be introduced, and checked for before `browser` when the target `webworker` is used. Please see https://webpack.js.org/configuration/resolve/#resolvemainfields which documents the current order as `browser`, then `module`, then `main`.

**Are you willing to work on this yourself?**
no, sorry.

**Comment by wooorm** [comment]
To add: the default in the above also uses non-browser features. But, when the `browser` field is explicitly requested, then DOM features are used (because it’s a bunch smaller). However, in some cases that doesn’t work, hence the `react-native` undo of the `browser` field!

**Comment by alexander-akait** [comment]
conditional exports are only valid solution, we don't want to add more nonstandard fields to `package.json`, because other bundlers is not supported it, but we already support https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1130

**Comment by stevemk14ebr** [comment]
Are you saying 'worker' field is checked before 'browser' when the target is 'webworker'?

**Comment by alexander-akait** [comment]
worker is always browser, you can't use worker in Node.js

**Comment by vankop** [comment]
> Are you saying worker field is checked before browser when the target is webworker?

you can prioritize this in resolve options https://webpack.js.org/configuration/resolve/#resolvealiasfields

**Comment by alexander-akait** [comment]
@wooorm Why do not use `conditional exports`? Even we fix it here, it will be not fixed in other bundlers/tools, it is not universal solution

**Comment by wooorm** [comment]
I’m :+1: on conditions. See [my first comment](https://github.com/webpack/webpack/issues/14681#issuecomment-963598357), I propose advocating to make it semistandard by trying to get it documented in Node, and for other bundlers to also support it.

The difference between other bundlers and webpack, I believe, is that webpack has a specific webworker preset which includes `'browser'` fields.
If I change things in `parse-entities` and switch to conditions, webpack will still pick `browser` fields for other packages in webworkers, right?
I believe that’s what this issue is also about: webpack should maybe not choose `browser` fields in webworkers, because the `browser` field is for browsers APIs **including DOM apis** (https://github.com/defunctzombie/package-browser-field-spec#overview).

**Comment by alexander-akait** [comment]
> The difference between other bundlers and webpack, I believe, is that webpack has a specific webworker preset which includes 'browser' fields.

Yes, because `webworker` like a browser

> If I change things in parse-entities and switch to conditions, webpack will still pick browser fields for other packages in webworkers, right?

`exports` should override other `main`/`browser`/etc

> I believe that’s what this issue is also about: webpack should maybe not choose browser fields in webworkers, because the browser field is for browsers APIs including DOM apis (https://github.com/defunctzombie/package-browser-field-spec#overview).

I agree with `including DOM apis`, but here some problems - I just want to say any changes with non standard fields in `package.json` are frozen, because it is breaking change and we can break other libraries/packages which rely on this behavior. Fortunately we have conditional exports on ecosystem lever right now and I think we should move ahead.

Right now I recommend to use https://webpack.js.org/configuration/resolve/#resolvealiasfields as workaround

**Comment by wooorm** [comment]
I don’t think this has anything to do with `exports`, I want to switch between a file locally.
This is about imports, but I don’t think webpack supports that? Here’s what I *think* I should do to make it work:

```js
  "imports": {
    "#decode": {
      "react-native": "./lib/decode.js",
      "worker": "./lib/decode.js",
      "browser": "./lib/decode.dom.js",
      "default": "./lib/decode.js"
    }
  },
  "exports": {
    ".": "./index.js"
  },
```

It works in Node.js but esbuild crashes on it

**Comment by wooorm** [comment]
@alexander-akait so I don’t think I can start using an `import` map in packages if most bundlers don’t support it yet.
And for the workaround (`resolve: {aliasFields: ['react-native']}`), while it does work for me in a small demo, I don’t think that would work in the real world. With `webpack-loader` it might be possible to switch the worker to use that and the rest of the code to not use that, with webpack 5 that loader is built in and there is no fine grained control

**Comment by wooorm** [comment]
raised a PR to “standardize” the condition: https://github.com/nodejs/node/pull/40914

**Comment by alexander-akait** [comment]
@wooorm Yep, we need standartize it, let's wait solution, I think we shouldn't rush with it yet

**Comment by wooorm** [comment]
Sure, but to reiterate my previous comment, I’d rather not wait on Rollup, esbuild, and other bundlers to start supporting import maps though, I think that can take at least a year to become commonplace.

Meanwhile, webpack is either picking `browser` code for web workers and “normal” bundles, or not picking browser code at all (plus it seems this choice isn’t even available for Next.js users ([stackblitz](https://stackblitz.com/edit/github-fjdjb6-redalq?file=next.config.js))). I really don’t want to ship 10kb extra to millions of users just to support web workers in webpack.

**Comment by alexander-akait** [comment]
It will be breaking change, we can't do it, some can rely on that, so we can't just change it

**Comment by wooorm** [comment]
I’m not proposing a solution, I’m explaining the severity of the problem: workers in Next.js are always broken, workers in webpack 5 are mostly broken, as I understand it.
Me as a maintainer shipping 10kb extra to millions of websites is not an acceptable workaround just to solve webpack, and breaking every bundler other than webpack to solve webpack isn’t acceptable either.
For all I care webpack patches this with an `_xxxWebpackWorkerWorkaround` field, which would hardly be a breaking change? I’ll usethat. There must be *some* way to choose different code for workers, or configure webpack 5 workers separately from the main code.

**Comment by alexander-akait** [comment]
Why you put `10kb`? You can just check env on supporting DOM, it is less than 10kb

**Comment by wooorm** [comment]
Because the version that uses DOM APIs is 0kb compared to the non-dom version, which is 10kb minzipped https://github.com/wooorm/parse-entities/blob/main/lib/decode-entity.browser.js https://github.com/wooorm/parse-entities/blob/main/lib/decode-entity.js

**Comment by alexander-akait** [comment]
You can do:
```
"browser": {
  "./browser.js": "./lib/decode-entity.browser.js",
  "./webworker.js": "./lib/decode-entity.webworker.js"
},
```

And load `./lib/decode-entity.js` based on env, so bundler drop unused code.

We have two problems:
- wrong logic based on `browser`, it will be breaking change
- adding the `webworker` property is bad idea, because we have `exports`, we should avoid introduce new features on legacy solutions

Even webpack added workaround it will be required change webpack.config.js, so next.js developers (and not only) still can't use it

**Comment by wooorm** [comment]
what do you propose for env switching? If that’s done, is the `browser` field still needed? Something with `process.env` you mean right?

> adding the `webworker` property is bad idea, because we have exports, we should avoid introduce new features on legacy solutions

Is this what you think would be a breaking change? I don’t really expect `webworker` to be used in `package.json`s.
I get that `conditions` are the future, and it isn’t ideal, but it would help a lot here.
I don’t get why it can be added as a condition, but not as a property?

---

Maybe this would work? Though I can’t use import maps, I could publish `decode-entity` itself as a package as a workaround? 🤔🤔🤔

**Comment by alexander-akait** [comment]
> Something with process.env you mean right?

Yep, or versa vice, `globalThis.document`, like:
```
if (globalThis.document) {
  require(...)
} else { 
  require(...)
}
```

> I don’t get why it can be added as a condition, but not as a property?

Because adding new fields to package.json requires standardization, we have already made a lot of problems in this, we should not continue to do this

Even if we add it, we cannot enable it by default, as I said earlier, because this will be a critical change and breaks other libraries and requires set additional options in configuration, so it won't solve problems for many developers, they don't have configuration (next.js end etc) or some do not understand why this is and all the details of the problem, so they will not add it by default

**Comment by alexander-akait** [comment]
bump

**Comment by stevemk14ebr** [comment]
bump +1

**Comment by cesutherland** [comment]
For webpack, setting [target](https://webpack.js.org/concepts/targets/) works for me:

```
{
  target: "webworker"
}
```

This will impact browser code built with the same config, as well — for now I have two separate webpack configs, depending on the target. I build and import the web worker bundle statically (eg. `new Worker('/assets/worker.js')`).

If I configure workers [the way webpack suggests](https://webpack.js.org/guides/web-workers/) the `worker` target's package exports are not used/configured automatically, [as described here](https://webpack.js.org/guides/package-exports/#target-environment) — instead it uses the browser import.

This feels like a webpack bug?

**Comment by alexander-akait** [comment]
Can you create reproducible test repo?
