### ISSUE TITLE
webpack 5 is keep stuck on building rather ignoring those error

### ISSUE THREAD

**Issue by afhaider** [webpack/webpack#14726]
compare to webpack 4  is 100% better then this webpack 5 which keep stuck on loading and waste people time 
i dont know what the point on webpack 5 when this is unstable 

i notice when i use babel loader this gonna more slower  and throw some kind of funny error even i add those plugin though it disappear 

yarn run v1.22.15
$ webpack --watch --config webpack.config.js
10% building 0/1 entries 0/0 dependencies 0/0 modules(node:27571) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)

seriously take around 5-10min to build  on webpack v5
take less then 15sec on webpack v4

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates. Also will be great to provide a small reproducible repo.

Please fill out all fields, we can't help you without it
