### ISSUE TITLE
Enhancement: Designate a global config.

### ISSUE THREAD

**Issue by resistdesign** [webpack/webpack#1488]
I'm working with 200+ packages but I need them configured all the same way. This means copying and pasting the config many times.

It would be great if I could somehow make the config somewhere once and tell the CLI to use it by default.

**Comment by SimenB** [comment]
Install global/publish package with default config and import it locally?

**Comment by resistdesign** [comment]
@SimenB I was thinking about that but I guess I'm looking for it to be officially supported somehow. That way the config file doesn't have to be in all your packages at all if that's possible.

**Comment by sokra** [comment]
The config is a node.js module. Node.js common practices apply here. There is no need for any offically support. See @SimenB hint

**Comment by resistdesign** [comment]
@sokra So if Node.js common practices don't include new things then new things will never be born?

**Comment by sokra** [comment]
I don't meant it that way. I meant: You can write custom tooling around the webpack config, because it's just a node.js module. You can require modules in the webpack.config.js that enhance it or allow usage of a global config. It's extensible. There is no need for additional tooling in the webpack core.

**Comment by resistdesign** [comment]
Ah I see, thank you for clarifying :)
