### ISSUE TITLE
devtool source-map creates broken `webpack://` urls when `output.library.name` is an array containing a placeholder

### ISSUE THREAD

**Issue by ZebulanStanphill** [webpack/webpack#14927]
# Bug report

**What is the current behavior?**

When using an `output.library.name` containing a `[name]` placeholder, e.g. `['MyLib', '[name]']`, the source maps generated by `'devtool': 'source-map'` are broken. I get a bunch of JS console warnings like this when using my scripts:

```
Source map error: Error: Invalid URL: webpack://MyLib.[name]/webpack/bootstrap
```
![image](https://user-images.githubusercontent.com/19592990/145136953-f443a52e-5673-46e1-9819-151b1e5f4e68.png)

The problem seems to be that the `[name]` placeholder in `output.library.name` is being treated as literal in the source map URLs, rather than being filled in with the entry file name. Source maps aside, the JS does work as expected, with the placeholder being replaced in other contexts. As far as I can tell, this is a bug, as using the `[name]` placeholder in `output.library.name` is a [supported feature](https://github.com/webpack/webpack/commit/9e6b6deea4076322ae68d122c19e99bd4b9d162b).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an empty folder. Add the following files:

`webpack.config.js`:
```js
const path = require('path')

module.exports = {
	mode: 'production',
	context: path.resolve(__dirname, 'src'),
	entry: { foo: './foo.js' },
	output: {
		path: path.resolve(__dirname, 'build'),
		filename: '[name].js',
		library: { name: ['MyLib', '[name]'], type: 'window' },
		clean: true,
	},
	devtool: 'source-map',
	module: {
		rules: [{ test: /\.js$/u, use: ['babel-loader'] }],
	},
	cache: true,
}
```
`package.json`:
```json
{
	"browserslist": "last 5 Chrome versions, last 3 Firefox versions, last 3 Safari versions, last 3 ChromeAndroid versions, last 2 Android versions, last 2 FirefoxAndroid versions",
	"scripts": {
		"build": "webpack"
	},
	"devDependencies": {
		"@babel/core": "^7.16.0",
		"@babel/preset-env": "^7.16.4",
		"@babel/preset-react": "^7.16.0",
		"babel-loader": "^8.2.3",
		"prettier": "^2.5.1",
		"webpack": "^5.65.0",
		"webpack-cli": "^4.9.1"
	}
}
```
`babel.config.json`:
```json
{ "presets": [["@babel/preset-env", { "spec": true }]] }
```
`demo.html`:
```html
<html>
	<head>
		<meta charset="utf-8" />
		<script defer src="./build/foo.js"></script>
	</head>
	<body>Look at the JS dev console.</body>
</html>
```
`src/foo.js`:
```js
export function myThing() {
	console.log('beep')
}
```

2. Run `npm i && npm run build`.
3. Open `demo.html`.
4. Check the JS dev console.

**What is the expected behavior?**

The source maps should contain working `webpack://` URLs with the `[name]` placeholder filled in as expected.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 16.13.1
Operating System: KDE Neon Linux

**Comment by alexander-akait** [comment]
Feel free to send a fix, should be easy

**Comment by ZebulanStanphill** [comment]
I took a look, but since I've never looked at Webpack's code before, I'm a bit lost. If anyone with more experience wants to tackle this, please do, and thank you. Best I could gather is that `name` is absent from [the list here](https://github.com/webpack/webpack/blob/c854e30df7f879d9989a7ab7aa83d1f0d1fa6862/lib/ModuleFilenameHelpers.js#L172), and that may have something to do with it. I don't know how/where to get the value of name to use in that list.

**Comment by TrickyPi** [comment]
@alexander-akait @ZebulanStanphill I want to tackle this, Can i take it ?

**Comment by ZebulanStanphill** [comment]
@TrickyPi Be my guest! :+1:

**Comment by alexander-akait** [comment]
Yes, PR welcome

**Comment by TrickyPi** [comment]
#15002

**Comment by sokra** [comment]
I can reproduce the problem. Seems more like a Firefox bug that it doesn't access the url.

`webpack://MyLib.[name]/webpack/bootstrap` is a valid url. It's a custom scheme, which basically allows anything after the scheme. You can also run `new URL("webpack://MyLib.[name]/webpack/bootstrap")` in JS and it parses the URL just fine.

It might not be a perfect default for the `output.devtoolNamespace` to include the raw `[name]` from the `output.library` option, but you can easily override it via e. g. `output.devtoolNamespace: "MyLibrary"`.

We can't replace the `[name]` with the entrypoint name, since
* chunks can be referenced by multiple entrypoints
* multiple entrypoints can be on a single page which could make it a race condition which name a source has

We could change the default for `devtoolNamespace` etc. to exclude `[name]`. That's here: https://github.com/webpack/webpack/blob/b3871e84122b6cc5298ad403ca46c3cd3df2a2b5/lib/config/defaults.js#L681-L697

**Comment by TrickyPi** [comment]
Oh, i get it. It's seem like sourceMap not support  [name] placeholder which defined in output.library.name.

**Comment by TrickyPi** [comment]
Could we change the devtoolNamespace in here?  It seems like it's more appropriate.
https://github.com/webpack/webpack/blob/b3871e84122b6cc5298ad403ca46c3cd3df2a2b5/lib/config/defaults.js#L863

**Comment by sokra** [comment]
> Could we change the devtoolNamespace in here? It seems more appropriate to change the default for devtoolNamespace.

Technically yes, but actually the `output.uniqueName` default is already broken and you get also weird names for e. g. `output.chunkLoadingGlobal`. So better "fix" the `uniqueName` default directly, by fxing `getLibraryName`

**Comment by TrickyPi** [comment]
okay, before "fixing" this problem, i have a confusion, is it necessary to "fix" `uniqueName` default? since developer can via output.devtoolNamespace to avoid this problem.  If it's necessary, currently the solution i can think of is to exclude `[name]` in here,
https://github.com/webpack/webpack/blob/b3871e84122b6cc5298ad403ca46c3cd3df2a2b5/lib/config/defaults.js#L690
but i worry about it will cause unexpected problems, since it also change the default of `hotUpdateGlobal` etc.

**Comment by sokra** [comment]
> since it also change the default of `hotUpdateGlobal` etc.

You also want to avoid `[name]` in these options too.

**Comment by TrickyPi** [comment]
Okay
