### ISSUE TITLE
Proposal: Source maps v4

### ISSUE THREAD

**Issue by robpaveza** [webpack/webpack#14996]
## Feature request

**What is the expected behavior?**
Analyzing JS stack traces is complex. Source maps provide a reasonable debugging experience at runtime, but when analyzing an exception, it's difficult to reconstruct an unminified stack trace, even with V3 source maps available. The best case of this often is that the token at the point of the error can be discovered, so a language parser will need to walk backward from that token to try to find a function declaration to get the name.

Consider a tiny example such as this:

```js
function causeError() {
  throw new Error('Expected failure.');
}
causeError();
```

Upon minification, this might become:
```js
(()=>{throw new Error('Expected failure.')})();
```

A plain rendering of this in an error stack might look like:
```
Error: Expected failure.
    at example.js:1:13
    at example.js:1:45
```

With source maps, we can get a pretty reasonable output:

```
Error: Expected failure.
    at example-src.js:2:3
    at example-src.js:4:1
```

However, the token at 2:3 is `throw`. That isn't terribly useful. If I reconstructed that stack by hand, I would expect:

```
Error: Expected failure.
    at causeError (example-src.js:2:3)
    at Global code (example-src.js:4:1)
```

To that end, the Edge DevTools team are proposing a v4 of Source Maps that will support this by encoding a notion of "scopes" -- source text ranges that correspond to a given runtime name. This is at MicrosoftEdge/MSEdgeExplainers#538.

**What is motivation or use case for adding/changing the behavior?**
We've seen other tools that do this -- https://github.com/bloomberg/pasta-sourcemaps as an example -- but if we can standardize this, we can incorporate that functionality into our everyday developer tools.

**How should this be implemented in your opinion?**
The spec proposes that the `scopes` field would be comprised of a list 6 VLQs for each scope name mapping:
 - Source index
 - Start line
 - Start column
 - End line
 - End column
 - Scope name index

Given an input source map from a tool like TypeScript already producing these values, the only thing a tool like Webpack would need to do is combine all of them, in this case, combining and de-duping the `scopeNames` field, and providing a small amount of modification (updating the source index and scope name index) when combining all of the various `scopes` values from each of the input source maps.

**Are you willing to work on this yourself?**
Yes. And, I've been working on producing this in TypeScript as well -- microsoft/typescript#47152

**Comment by sokra** [comment]
Interesting proposal, but I have a few questions:

I guess the idea is to make it similar to the `mappings` field, which why I wondered about the following differences:

* the "key" in `mappings` field is the generated line+column. Why isn't that the case for the `scopes` field? I think it should also "keyed" by generated line+column. It should use the same format as `mappings` (`;` moves to next line, only `column` is a value)
* the `mappings` fields only specifies starting points and not ranges. Why isn't that the case for the `scopes` field? I think it should only define the starting point of a range and that would continue until the next point.

These changes would make the `scopes` smaller and more similar to `mappings`, which would also make it easier to reuse implementations.

Each `scopes` field would be 2 VLQs:

* generated column
* (optional) scope name index
* let's say there could be additional values that should be ignored by implementations to support future extensions.

`;` moves to the next line, multiple entries on a single line are separated by `,` (exactly like `mappings`)

**Comment by robpalme** [comment]
Hey all, glad to see interest and energy on this proposal.  Here's some background from the previous work we did on this that may address @sokra's questions.

### Background 

In [pasta](https://github.com/bloomberg/pasta-sourcemaps) at least, the reason for expressing the named scope as a range (two coordinates) rather than a single point (one coordinate) is consequence of two key design decisions:

1. ***Scope name decoding is based on source location***
    - As usual, you first take the generated location and decode a source location.  The new step is to then map that source location to a source scope name
    - The alternative (as @sokra says) would be to key scope name decoding off the generated location, which may well be more direct. This would work, but it offers less information and involves some repetition of the source name index each time you return to a previous scope. Almost all use-cases require computing source location anyway, so it is easily at hand to perform the subsequent name lookup.
2. ***Scope declarations are per-function - meaning nested instead of linear***

```
// *nested*                            // *linear*
| "<top-level>"                        | "<top-level>"
|                                      |
|  |  "causeError"         vs            |  "causeError"
|  |                                     |
|                                      | "<top-level>"
```

The nested approach means it only needs one VLQ entry per-function.  Whereas a function that has many inner functions needs to repeatedly reference the same name as you go into and out of the children.

The nested approach has a semantic benefit - it truly expresses the logical structure of the source code, i.e. there is a 1:1 correspondence of VLQ entries and functions.  So you can easily disambiguate edge cases such as two contiguous functions with the same name, or a function within a function of the same name.  Additionally, taking @sokra's suggestion that we might want future extensions, it seems more likely for that to become useful if we keep the data associated with a semantic per-function datastructure, e.g. you could imagine adding more per-function metadata such as `isExported`, `isAsync`, `isDeprecated`, `listOfDecorators`.

### Discussion

The above is core spec discussion rather than anything specific to webpack, so maybe we should talk about this in [the proposal repo](https://github.com/MicrosoftEdge/MSEdgeExplainers/pull/538)?  This also highlights the need for us to build recorded rationale for each key design decision so we can get more buy-in and avoid explaining these same things across repos. I think @ldarbi can help with that.

Maybe it would also be good to chat about this in [the TC39 Tooling Group](https://github.com/tc39/js-outreach-groups) run by @romulocintra.  That brings together the kind of folk who would be interested in this. I think the next meeting will be mid-January (the github is a little out of date).

**Comment by romulocintra** [comment]
This is a really good topic for the Tools discussion, please be my guests at the next meeting happening in January - in case you want/need an invite ping me at rcintra@igalia.com ...

**Comment by sokra** [comment]
> Implementing this as the pointer to source line+col rather than generated line+col reduces the implementation complexity and number of tools that need to be updated to take advantage of the change:
> 
> * If you imagine a tool chain of TypeScript + WebPack + Terser, then TypeScript needs to emit the full list. WebPack only needs to modify the `sourceIndex` and `nameIndex` fields, and Terser doesn't need to modify it at all.
> * Assuming that you're generating full source maps, it's a (relatively fast) two-step process to resolve generated->scope. First you resolve the `mapping` for generated->source, and then resolve the scope using the previously-resolved source.

I can't really follow that argument.

* Most source map operations involve re-numbering the sources indicies, which would require touching scopes too.
* It's not possible to declare scopes in generated-only code (which doesn't have a original source code attached)
* Multiple pieces of generated code can map to the same original code and it's no longer possible to have different scopes for that.

> > * the `mappings` fields only specifies starting points and not ranges. Why isn't that the case for the `scopes` field? I think it should only define the starting point of a range and that would continue until the next point.
> 
> As @robpalme notes above, the ranges reflect the lexical scopes of the language. I believe I mistakenly indicated that there would be a linear output of scopes in the spec proposal; when I actually implemented it, it followed the "nested" form noted above.

With a "nested" form I would still encode points and use them as start (scope name index set) and end (scope name index) locations which push/pop from a scope stack.

e. g.

```
| "scopeA"
|
|  |  "scopeB"
|  |
|  |  | "scopeC"
|
|
```

encodes as `[0 "scopeA"];;[0 "scopeB"];;[0 "scopeC"];[0],[0];;[0]`

---

In general I would look more into what would be the best format rather then looking into which tools need to be changed...

**Comment by ldarbi** [comment]
Here is a simple example to demonstrate the two approaches discussed so far. 

In this example we have one source file that gets minified.

Source file

```js
1    // source file
2    function foo() 
3    {
4        function bar() 
5        {
6            throw new Error("oops");   
7        }
8        bar();
9    }
10   foo()
```
Generated file

```js
1    function o(){function o(){throw new Error("oops")}o()}o();
```

The two options for encoding the `scopes` field would look like this.

## 1. "Key by generated" (list starting positions in the generated file each time a scope change occurs)

Similar to the existing `mappings` field, we'll use generated file locations as keys. We'll have an entry for every time a scope change occurs. 
- When a new scope starts, we'll specify column number and scope name index. 
- When a scope ends, we'll only specify column number (scope name will be implicit due to us popping a stack). 
- We'll use `;` to go to a new line
- We'll use `,` to seperate entries

In our example let's assume `scopeNames = ["foo", "bar"]`

- The first scope starts at column 14 and corresponds to `"foo"` (scope name index = 0) so the entry will be `{14,0}`
- The second scope starts at column 27 (13 relative to the first scope) and corresponds to `"bar"` (scope name index = 1) so the entry will be `{13,1}`
- The second scope ends at column 51 (24 relative to the first scope) so the entry will be `{24}`
- The first scope ends at column 55 (4 relative to the end of previous scope) so the entry will be `{4}`

To summarize, the logical representation of `scopes` will looks like this: 

```
{14,0},{13,1},{24},{4}
```

Essentially each function gets two entries, with three numbers altogether - two numbers in the start point entry (starting column and scope name index) and one number in the end point entry (ending column).

## 2. "Key by source function" (indexed by source file, then function)

In this option the entries are based on the source file, and each function gets one entry representing its coordinates. 

In our example there will be two entries to represent the two functions. Again, assuming `scopeNames = ["foo", "bar"]`

- `foo` is represented by `startLine = 3, startColumn = 1, endLine = 9, endColumn = 1`. Adding the scope name index to the start of the entry, we have `{0,3,1,9,1}`
- `bar` is represented by  `startLine = 5, startColumn = 4, endLine = 5, endColumn = 4`. Adding the scope name index to the start of the entry, we have `{1,5,4,5,4}`

<i>Note that we would use appropriate relative indexing for columns and lines to reduce the numbers, but for simplicity of the explainer we'll leave them as absolute.</i>

**Comment by alexander-akait** [comment]
bump
