### ISSUE TITLE
Add multiple entry points to one bundle

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#15]
I want to use webpack to bundle unit tests in the test-folder. Therefore I want to search the test-folder for js-files and add these files to the bundle created by webpack. Is it possible to add multiple entry points like `.addEntry()` in browserify?

**Comment by puppybits** [comment]
Can you load an secondary entry with a different set of loaders? 

For instance, I'm trying to create a service worker for offline caching. I've excluded the folder that contains the service worker and included it on the other. There are no calls to the service-worker.js (it's just manually loaded in the static index.html). The service-worker entry point is picking up React and hot loader instead of just going through Babel. Here's the salient parts of my config.

    entry: {
         app: "app.js",
         'service-worker': 'persistence/service-worker.js'
    },
    module: {
        loaders:[{
            test: /\.js|\.jsx/,
            loaders: ["react-hot", "jsx?harmony", "babel"],
            exclude: /persistence/
        }, {
            test: /service\-worker\.js/,
            loaders: ["babel"],
            include: /persistence/
      }]
