### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kevinolivar** [webpack/webpack#15060]
# Bug report

**What is the current behavior?**
After running `npm run prod`, webpack throws,

```
➜  aem-test git:(main) ✗ npm run prod

> aem-maven-archetype@1.0.0 prod
> NODE_ENV=production webpack --config ./webpack.prod.js && clientlib --verbose

/Users/kolivar/aem-test/node_modules/webpack/lib/util/runtime.js:60
exports.forEachRuntime = (runtime, fn, deterministicOrder = false) => {
                         ^

RangeError: Maximum call stack size exceeded
    at exports.forEachRuntime (/Users/kolivar/aem-test/node_modules/webpack/lib/util/runtime.js:60:26)
    at ExportInfo.setUsed (/Users/kolivar/aem-test/node_modules/webpack/lib/ExportsInfo.js:1017:4)
    at ExportsInfo.setUsedWithoutInfo (/Users/kolivar/aem-test/node_modules/webpack/lib/ExportsInfo.js:392:31)
    at processReferencedModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:80:25)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:270:9)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:206:10)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:206:10)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:206:10)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:206:10)
    at processModule (/Users/kolivar/aem-test/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:206:10)
````

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://github.com/kevinolivar/aem-test
- Run `npm run prod`

**What is the expected behavior?**
The application should successfully be built as with using the command `npm run dev`.

If it can also help investigating this issue, I first thought it was maybe related to MiniCssExtractPlugin. Here some more details on that issue https://github.com/webpack-contrib/mini-css-extract-plugin/issues/733. 
However, the problem may also be in webpack.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 16.11.1
Operating System: Mac OS Big Sur 11.5.2 (20G95)
Additional tools:
npm version: 8.0.0
yarn version: 1.22.5
webpack-cli version: 4.9.1
webpack-dev-server version: 4.7.1
webpack-merge version: 5.8.0
mini-css-extract-plugin version: 2.4.5

**Comment by alexander-akait** [comment]
I look at source code of `glob-import-loader` and there are some problems too:
- `import` has absolute paths, i.e. `import "/home/evilebottnawi/IdeaProjects/aem-test/src/main/webpack/site/main.ts";`, and it is wrong, because import should be URL
- Also `import` should have relative paths (relative to the file where it is used), not absolute, because it will be bad for cache

Why you need this loader? I would recommend to be as close as possible with ESM spec and do not use this loader.

**Comment by alexander-akait** [comment]
Anyway I found a problem, your code is
```
// Other code
import "./**/*.ts";
```

After glob you have:
```ts
import "/home/evilebottnawi/IdeaProjects/aem-test/src/main/webpack/site/main.ts";
```

i.e. you load `main.ts` inside `main.ts` -  circular dependencies, webpack tries to optimize your code (css modules generated by `mini-css-extract-plugin` in referenced module and webpack tried to understand can we drop some code for this, https://webpack.js.org/configuration/optimization/#optimizationusedexports) and here we have a loop (and a problem), because. Adding more modules will fix the problem (i.e. just create `foo.ts` and you will see it). But yes, we should generate the better error message here.

So solution is exclude `main.ts`, I tried using `/**/!(*main).ts`, but loader emits an error. So I recommend to fix circular dependency, because I'm sure this is not the behavior you expect (note - circular dependencies have some limitations in webpack). And using glob can be very dangerous because you can accidental include/import something in your code and it will be bad for your app size/perf, especial using `**/*`.

**Comment by kevinolivar** [comment]
> I look at source code of `glob-import-loader` and there are some problems too:
> 
> * `import` has absolute paths, i.e. `import "/home/evilebottnawi/IdeaProjects/aem-test/src/main/webpack/site/main.ts";`, and it is wrong, because import should be URL
> * Also `import` should have relative paths (relative to the file where it is used), not absolute, because it will be bad for cache
> 
> Why you need this loader? I would recommend to be as close as possible with ESM spec and do not use this loader.

I am using a generated project and this is what I get out of the box, 
https://github.com/adobe/aem-project-archetype/tree/develop/src/main/archetype/ui.frontend.general

https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.frontend.general/src/main/webpack/site/main.ts

The thing is that it works fine if I don't upgrade the npm packages. Eg. webpack...
As you can notice, the package.json contains outdated packages.

**Comment by alexander-akait** [comment]
There is the problem with circular dependencies, I am afraid it works before, but works invalid, using `import "./**/*.ts";` should not include itself, it is wrong

**Comment by kevinolivar** [comment]
@alexander-akait Thanks for your reply, I will then remove this glob-import-loader.

**Comment by alexander-akait** [comment]
You can try to rewrite glob to exclude file, but I am failed with it, maybe due old version of glob

**Comment by sokra** [comment]
Importing itself shouldn't lead to an error... That might be a bug.

**Comment by kevinolivar** [comment]
> 

or at least a better message? As @alexander-akait mentioned

**Comment by kevinolivar** [comment]
> You can try to rewrite glob to exclude file, but I am failed with it, maybe due old version of glob

@soluml?

**Comment by soluml** [comment]
@kevinolivar thanks, yea I'll take a look at it tomorrow. Patching glob-import-loader to prevent a file from including itself should be simple to do, but you still have to be mindful that generic globs as you've implemented them can still cause you to include more than intended. It's not a standard feature so be sure to check out the docs for the loader. I'll tag you once an update is available. 

@alexander-akait some glob features (special characters) aren't available due to incompatibilities with underlying webpack tooling. The loader docs calls these out.

Also, even though the loader should exclude itself from the import, it's worth looking into Sokra's note that self importing shouldn't cause an error. I hadn't run into this problem with Webpack 4 when I forked/built the loader.

**Comment by alexander-akait** [comment]
@sokra It is due `mini-css-extract-plugin`, when we have one CssModule and import itself in one file, we have a loop

**Comment by soluml** [comment]
@kevinolivar - `glob-import-loader` has been updated which excludes the resourcePath from being glob imported.

**Comment by kevinolivar** [comment]
@soluml thanks mate, appreciate. I think at the end, as a good practice and as you and @alexander-akait mentioned, it is good not relying on glob but rather ESM spec. Just to avoid importing undesirable files.

Is there anything else open to address? Or this issue can be closed?

From my understanding, maybe for @alexander-akait a better way of handling circular dependencies with clearer error message if that issue was caused by the mini-css-extract-plugin (and not webpack)?

I really appreciate your help @alexander-akait and @soluml. @sokra too for your input as well.

**Comment by alexander-akait** [comment]
Let's keep open, webpack still should not throw an error on circular dependencies

**Comment by soluml** [comment]
@kevinolivar All the loader does is make it easier to import large numbers of files in a single easy to read statement. This can be helpful in component libraries, or in AEM's case, importing all component JS/TS into a single clientlib. In these cases though, it's best to be more specific.. something like: `import './components/**/.ts'` where we'd want to import all component TypeScript into a site clientlib for example.

You can also do something similar to this with Webpack's `require.context`, but then, you don't get the advantages of ESM so this tries to give you the best of both worlds.

The loader is also handy in that it leverages the enhanced-loader package under the covers, meaning you can also use globbing with things like aliases: `import 'MY_COMPONENTS_FOLDER/**.ts';`. This is also the reason why some globbing characters can't be used.

Hopefully that makes sense. If you have 20+ odd components that you need to import into a single entry for clientlib purposes, this may really help you out. Any new components will automatically be added to the clientlib which I've found very handy when working on big teams. If you're just importing a few files here and there, best to be explicit and skip the globbing. Any non-globbed imports will be completely ignored by the loader so there shouldn't be any harm in using it on an as needed basis.

**Comment by kevinolivar** [comment]
@soluml I myself never used glob but always manually included files I needed. Eg. exporting my components through a single index.ts. 
I guess case by case. Eg. team size, project size...

Your explanation makes absolutely sense, thanks again for the clarifications.

**Comment by kevinolivar** [comment]
> Importing itself shouldn't lead to an error... That might be a bug.

Any news regarding this?

**Comment by alexander-akait** [comment]
@vankop `glob-import-loader` fixed the problem, the main problem here https://github.com/webpack/webpack/issues/15060#issuecomment-1002093799 (but maybe we fixed it?), need to check it, circular import itself, try

**main.ts**

```ts
import "./main.ts";
```

**Comment by vankop** [comment]
@alexander-akait
circular import itself works fine in js and css (mini-css) I have checked

**Comment by kevinolivar** [comment]
Thank you guys!
