### ISSUE TITLE
Worker not bundling imported files

### ISSUE THREAD

**Issue by TheColorRed** [webpack/webpack#15165]
I am trying to load a Worker in the following way:

```ts
const url = new URL('./path/to/worker.ts', import.meta.url);
const worker = new Worker(url);
```

In the worker file I am trying to do an import:

```ts
import { someFunction } from './functions';

someFunction();
```

If I don't provide `{ type: 'module' }` to the Worker constructor, the import doesn't get bundled with the worker and the following error is displayed in the console:

> Uncaught SyntaxError: Cannot use import statement outside a module

 If I do provide `{ type: 'module' }` to the Worker constructor then it request the file without the extension: `http://localhost:8080/functions` which then returns a `404` due to the fact that a file without the extension doesn't exist.

I would expect this to be bundled similar to the way that it is bundled when creating a webpage that uses imports as well where everything is in one file. Is there something I am doing wrong or is this a missing Webpack feature?

**Comment by alexander-akait** [comment]
Worker handled only when you write `const worker = new Worker(new URL('./path/to/worker.ts', import.meta.url));`, otherwise it is not statically analyzable, it is limitation, sorry

**Comment by debo07** [comment]
Hi @alexander-akait , I am facing similar issues while trying to use Web Worker script using webpack 5. Could you please help me here!

Below is the **usage of the worker script** in the main thread.
```javascript
const worker = new window.Worker(
    new URL("../workers/listOperation.worker.js", import.meta.url),
    {
        type: "module",
    },
);
worker.postMessage({ list: hugeList, params: reqData });
worker.onerror = err => console.error(err);
worker.onmessage = e => {
    const { list } = e.data;
    // Usage of `list` from the response
    worker.terminate();
};
return worker;
```

_It works fine if there are no imports used in the script. But when I import any node modules (e.g. `loadash/get`) or any other function/constants from local, it does not work as the output webWorker bundle file doesn't transpile and bundle the imported code. It keeps the "import" statement as it is._

Below is the worker script (`listOperation.worker.js`)
```javascript
import get from "lodash/get";
import { ANY_CONSTANT } from "../constants"; // This is some local constant

addEventListener("message", e => {
    const { list, params } = e.data;
    
    // Here I have some usage of `get` method from `lodash/get` and ANY_CONSTANT
    
    self.postMessage({
        list: list,
    });
});
```

Webpack outputs the bundle file like below which won't be usable by the browser, if I put the `/\.worker.js$/` pattern in the the `exclude` of `babel-loader` rule.
```javascript 
import get from "lodash/get";import{ANY_CONSTANT}from"../constants";addEventListener("message",(e=>{const{list:s,params:t,.......
```
And even if I don't put the `/\.worker.js$/` pattern in the the `exclude` of `babel-loader` rule, the output bundle still doesn't include the implementation of `get` from `lodash/get` or the value of the constant. It just outputs it in cjs using `require`.

Also, I made use of asset module so that I can put the output file inside a directory, not directly in the root of the `dist` folder. Configuration changes in my webpack.config looks like this.
```javascript
module.exports = {
    entry: {...},
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [/(node_modules)/, /\.worker.js$/],
                use: {
                    loader: "babel-loader", // This uses the config defined in babel.config.js
                },
            },
            {
                test: /\.worker.js$/,
                exclude: /(node_modules)/,
                type: "asset/resource",
                generator: {
                    filename: "js/workers/[hash][ext][query]",
                },
            },
        ],
    },
}
```

**Comment by debo07** [comment]
Hi @alexander-akait, sorry for the delay in response. Here is the github repo - https://github.com/debo07/WebWorkerPOC to reproduce this issue.

**Comment by debo07** [comment]
Hi @alexander-akait, did you get a chance to look into it? Is this an issue on webpack side or am I missing some configuration? Let me know if I am expected to raise a separate issue.

**Comment by alexander-akait** [comment]
@debo07 don't worry, it is in my TODO list, sorry for delay, a lot of tasks

**Comment by debo07** [comment]
Thanks @alexander-akait for checking this.
Initially I was trying out without type: `"asset/resource"` only. However, it was still not bundling the web worker script and another thing was that I was not able to control the output directory. e.g. post build all the `js` files goes to `dist/js` folder as per `output.filename` configuration. However, the worker script bundle was directly outputting in the `dist` folder instead of `dist/js`, something like [this](https://stackoverflow.com/q/68987801/5084280). I am not sure if all these were happening because of the `window.Worker` syntax. Now it is working fine when I removed the `window` part.

_As a side note why I considered web worker as an asset is inspired from_ [this article](https://web.dev/bundling-non-js-resources/). _Also, `type: "asset/resource"` allowed me to set the output directory correctly using `generator.filename`_

However, in my actual repo, now the **only issue** remains is dev mode handling i.e. **Inlining the web workers**, as my worker script and main script are from different origin, it blocks it because of same origin policy. `worker-loader` had an option(as shown below) to load it as inline blob in such scenarios. How do you suggest to handle it? TIA
```
// webpack.config.js
module.exports = {
  module: {
    rules: [
      {
        loader: "worker-loader",
        options: { inline: isDevelopment ? "fallback" : "no-fallback" },
      },
    ],
  },
};
```

**Comment by vankop** [comment]
problem is we can't check just for `web`... maybe we should support `window.Worker` and `globalThis.Worker` by default? btw for Node.js we does this ( we support `new Worker` for Node.js target )

**Comment by vankop** [comment]
cc @sokra

**Comment by alexander-akait** [comment]
Let's reopen for an answer

**Comment by debo07** [comment]
Hi @vankop @alexander-akait, I can still live with the `new Worker()` syntax as I don't need to use `window.Worker` syntax.

As requested in the previous comment could you please help me **inline** the web worker in dev mode? I tried with `asset/inline`, but then again it does not bundle the imported module properly.

**Comment by vankop** [comment]
> inline the web worker in dev mode

you mean using blob? webpack can only output it as bundle..

**Comment by debo07** [comment]
@vankop yeah, I am talking about url blob here which `worker-loader` supports. More can be found [here](https://v4.webpack.js.org/loaders/worker-loader/#inline).
I couldn't find anything to achieve the similar using webpack v5.

**Comment by vankop** [comment]
> Shall we consider this a limitation of webpack 5

for now yes..

**Comment by alexander-akait** [comment]
@debo07 You can solve it on application side, why you need inline? Due CORS?

**Comment by Bankde** [comment]
> Worker handled only when you write const worker = new Worker(new URL('./path/to/worker.ts', import.meta.url));, otherwise it is not statically analyzable, it is limitation, sorry

Sry for reviving old thread. 
As someone who encountered the same issue, can we add the limitation warning into the document page?
https://webpack.js.org/guides/web-workers/
