### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by AkifObaidi** [webpack/webpack#15358]
I have upgraded my Webpack 4 to 5 and when i am trying to build my project i got this error :
 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields and provide reproducible repo, we can't help you without it.
