### ISSUE TITLE
can't use production mode when use React.lazy to import component, but the develoption mode is ok.

### ISSUE THREAD

**Issue by chenwenqin** [webpack/webpack#15500]
webpack.prod.config
{
  mode: process.env.NODE_ENV,
  module: {
    rules: [
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        include: path.resolve("./src"),
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
      ......,
    ]
  },
  ......,
  optimization: { splitChunks: { chunks: "all" } },
}

.babelrc
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}

when i use `cross-env NODE_ENV=development` to build, it's work well, but `cross-env NODE_ENV=production` will get following error:
![image](https://user-images.githubusercontent.com/32031718/157589014-1a3260e6-2526-42b3-a0e1-0f00cadad119.png)

env:
"webpack": "^5.70.0",
"webpack-cli": "^4.9.2",
"babel-loader": "^8.2.3",
"@babel/preset-env": "^7.16.11",
"@babel/preset-react": "^7.16.7",
"@babel/preset-typescript": "^7.16.7",

Does anyone have this problem ?

**Comment by chenwenqin** [comment]
I‘m sure that the problem is `react.lazy(()=>import('./add.tsx'))`, when i use `import Add from './add'`, this well be ok.

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it. Also will be great to create reproducible repo.
