### ISSUE TITLE
Using `require.resolve` to get resolved file path (node)

### ISSUE THREAD

**Issue by MadLittleMods** [webpack/webpack#1554]
*I updated this question once I realized I needed to remove the `exclude` from the raw loader. For reference [here was my original question](https://gist.github.com/anonymous/aca12532be529064a670).*

---

How do you get [`require.resolve`](https://webpack.github.io/docs/api-in-modules.html#require-resolve) to return the resolved file name as it would [in node](https://nodejs.org/api/globals.html#globals_require_resolve)?

I am dealing with [this code in a dependency](https://github.com/atom/atom-space-pen-views/blob/75ccee886e723a7a4913a4286e089225eec8834d/src/select-list-view.coffee#L6): 

```
atom.themes.requireStylesheet(require.resolve('../stylesheets/select-list.less'))
```

I added the [`raw-loader`](https://github.com/webpack/raw-loader) but [`require.resolve`](https://webpack.github.io/docs/api-in-modules.html#require-resolve) returns the `module.id`(webpack) vs the resolved file path(node) which is expected by [`atom.themes.requireStylesheet`](https://atom.io/docs/api/v1.0.19/Atom#instance-themes)

```js
{
	module: {
		loaders: [{
			test: /\.less$/,
			loader: 'raw'
		}]
	}
}
```

**Comment by sokra** [comment]
> How do you get require.resolve to return the resolved file name as it would in node?

This doesn't work.

`require.resolve` returns the module identifier according to CommonJS. In node.js this is the filename. In webpack this is a number.

**Comment by faceyspacey** [comment]
@sokra is there a workaround to get the file name? I see that i can do this:

```
const funcString = __webpack_modules__[10]
```

and then extract the file name using a regex to parse it from, eg:
```
/ WEBPACK FOOTER\n// ./~/react-dom/lib/SyntheticEvent.js\n// module id = 10\n//
```
But is there a more trustworthy way to go about this? And is this way trustworthy at all? 

Note: the reason I'm looking to do this is to get the file name from a server build and find it's corresponding chunk in a client build for pre-embedding in the output html as part of server side rendering + code splitting. I'm looking to embed bundles that were code split, which aren't the primary bundles. And since I'm making connections between 2 separate builds, I need the file name, not the module ID which wont be the same.

**Comment by alexcroox** [comment]
@faceyspacey did you ever find out how to do this? I have a dependancy that only accepts a string

**Comment by DimitarTachev** [comment]
@alexcroox you could wrap your require.resolce with an eval. In this way, it will be skipped by webpack and executed runtime. E.g. **eval("require.resolve('myCoolFolder/theFile.js')")**

**Comment by lucas-rudd** [comment]
Anything ever come of this? I am also running into the same issue with a 3rd party module.

The string is needed to pass to `path.dirname`
