### ISSUE TITLE
resolve.extensions not working for files different from js, jsx

### ISSUE THREAD

**Issue by Piemontez** [webpack/webpack#15626]
I have some problem for similar situation.

In my case, i have one system work in web broswer, and work in dekstop electron app.
The webpack and the system worked perfectly as long as I didn't need to separate functionality from the web and desktop systems.

To solve this situation, I separated files with different extensions webview.tsx and desktop.tsx as "FileOpenMenu.desktop.tsx" and "FileOpenMenu.webview.tsx". And for import I would like to import like this "import FileOpenMenu from 'FileOpenMenu".

For this I needed to create 2 webpack files that would load the correct file depending on the final packaging, as shown below.

webpack.desktop.jsx
extensions: ['**.deskopt.jsx**', '.jsx', '.js']

webpack.webview.jsx
extensions: ['**.webview.tsx**', '.jsx', '.js']

However webpack does not resolve the "**.desktop.tsx**" and "**.webview.tsx**" extensions.

_Originally posted by @Piemontez in https://github.com/webpack/webpack/issues/12042#issuecomment-1087662697_

**Comment by Piemontez** [comment]
I make simple project to simulate this bug.
[webpackresolverextensions.zip](https://github.com/webpack/webpack/files/8411712/webpackresolverextensions.zip)

After download open project folder and run "yarn && yarn build:webview && yarn build:desktop"

The main problem is in the "src/index.ts", where i try to import "operations" file.

src/index.ts
```
import { loadfile } from "./operations";

console.log(loadfile("abc.txt"));

```

operations.desktop.ts
```
const loadfile = function (filename: string) {
  console.log(`File ${filename} successful loaded.`);
};

export { loadfile };
```

operations.webview.ts
```
const loadfile = function (_filename: string) {
  console.log(`Operation not alowed in webview container.`);
};

export { loadfile };
```

output error
```
ERROR in /home/piemontez/Projects/testes/webpackresolverproblem/src/index.ts
./src/index.ts 1:25-39
[tsl] ERROR in /home/piemontez/Projects/testes/webpackresolverproblem/src/index.ts(1,26)
      TS2307: Cannot find module './operations' or its corresponding type declarations.

```

But i configured on the webpack file to resolve this extensions and problem.

**Comment by Piemontez** [comment]
I tryed to use NormalModuleReplacementPlugin, but with him I had the same problem reported here https://github.com/TypeStrong/ts-loader/issues/838

**Comment by alexander-akait** [comment]
Yep, that is `ts` resolver problem, firstly `ts` converts files to `js` and then `webpack` parses `js` and uses own resolver, so `extensions` will not work for `ts`, because `ts` has own resolver. 

Solutions:
1. `transpileOnly` https://github.com/TypeStrong/ts-loader#transpileonly (Recommended), just move types validation step from build (it will speedup build), and also it will emit files as is and webpack resolver will work
2. Use `paths` and create different `tsconfig.json` for `desktop` and `mobile` envs and load conditional files like modules, i.e. `import { loadfile } from "operations";` and set `operation` on different paths for desktop and mobile
3. Use `import()` and load files based on env (also good way)
4. Create custom ts plugin (it can be not easy) 
5. Rely on tree shaking and keep code together (you need ESM and avoid side effects as much as possible) 

Sorry, we can't fix it on webpack side,

**Comment by Piemontez** [comment]
Thanks for helpful

I solved this one in a similar way as you said in one webpack.config.js

i add webpack.NormalModuleReplacementPlugin plugin and replace postfix name file like that:

```typescript
const isWebview = !!process.env.WEBVIEW;
const postfixSearch = '-factory';
const postfixName = isWebview ?  '-webview' : '-renderer';
...
plugins: [
 new webpack.NormalModuleReplacementPlugin(
      new RegExp(`(.*)${postfixSearch}(\.*)`),
      function (resource) {
        resource.request = resource.request.replace(postfixSearch, postfixName);
      }
    ),
...
]
....
```
and webpack load correct file for deskop or web version.
