### ISSUE TITLE
Implement module.children object

### ISSUE THREAD

**Issue by chrishowes** [webpack/webpack#1569]
Similar to https://nodejs.org/api/modules.html#modules_module_children

**Comment by sokra** [comment]
`module.children` and `module.parent` is too expensive.

If you need it consider rethinking your design, because relying on `module.parent` is pretty error-prone when there are muliple parents and `module.children` is pretty useful because you are in control for you `require`s and you should already know you children.

**Comment by chrishowes** [comment]
understandable. is there a better way to dynamically access your children at runtime? 

my use case: hack'd version of a namespaced REPL. i've got a loader that adds an eval() function onto every export. my entry point contains a REPL, which i'd like to be able to use module.children to "traverse" the require tree and then call the proper eval function in my modules.

obviously this isn't a normal use case, so feel free to close out.

**Comment by sokra** [comment]
If it's only a hack'd version, you can add the `HotModuleReplacementPlugin`. It also needs `children` and `parents` of module and tracks them. With this plugin enabled you'll have `children` and `parents` on the module object.

**Comment by chrishowes** [comment]
Perfect, thanks!

**Comment by dominictarr** [comment]
module.parent is _very often_ used to test wether you are in the main js file - if you at least make it falsey, then all the modules that do that will still work.
