### ISSUE TITLE
Some question about ConcatenatedModule and 'external' module

### ISSUE THREAD

**Issue by jayjliang** [webpack/webpack#15810]
First of all, appreciate the great work that webpack do!

I have a complex project which have thousand modules, one day the build result not work and throw some errors when run it. After debug inside webpack，I found [this line](https://github.com/webpack/webpack/blob/main/lib/optimize/ConcatenatedModule.js#L1586) work, but it's too complex for me to understand the whole logic about this file, and can't find some info by google search.

So could someone provide some information about：
1. how to understand 'external' moudle
2. when will run into [this logic](https://github.com/webpack/webpack/blob/main/lib/optimize/ConcatenatedModule.js#L1586)

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it
____________

this is related to different runtimes..
