### ISSUE TITLE
multicompiler build with `webpack serve`

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#15824]
# Bug report

Multicompiler build with dependencies fails with `webpack serve` and success with common `webpack` build

**What is the current behavior?**
build with `webpack serve` fails without building dependency compiler first.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/vankop/webpack-serve-bug

- run `npm run build`. it should successfully build
- remove `src2/build1.js`
- run `npm run serve`. it should fail

**What is the expected behavior?**
build succeeded

**Other relevant information:**
webpack version:  latest
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Yeah, it is intresting, by default when you run serve, we run dev server on both compiation (but we keep files in memory), to solve it we need:
1. Allow to disable dev server for required compilation, here is issue https://github.com/webpack/webpack-cli/issues/2408

As workaround now you can do it:
```js
const path = require("path");

module.exports = [
    {
        mode: "production",
        name: "build1",
        entry: "./src1",
        output: { filename: "build1.js", path: path.resolve(__dirname, "src2") },
        devServer: {
            devMiddleware: {
                writeToDisk: true,
            }
        }
    },
    {
        mode: "production",
        name: "app",
        dependencies: ["build1"],
        entry: "./src2",
    }
];
```

I want to close the issue here (in favor https://github.com/webpack/webpack-cli/issues/2408), because we should fix bug/implement enchantment in webpack-cli.

Feel free to feedback
