### ISSUE TITLE
Build error when using npm link for a dependency

### ISSUE THREAD

**Issue by donasaur** [webpack/webpack#1594]
Hi, there exists an issue currently where if I npm link a module, e.g., [mds](https://github.com/stanford-gfx/mds.js), and then inside of webpack.config.js, I have a line of the form:

```
        test: require.resolve('mds'),
        loader: 'imports?d3=d3'
      },
```
under loaders

And then I try to build with webpack, it will say:
```
ERROR in ../mds.js/mds.js
Module not found: Error: Cannot resolve module 'd3' in /Users/donasaur/projects/mds.js
 @ ../mds.js/mds.js 2:9-22
```
even though I have d3 installed my source directory(e.g., `modulesDirectories: ['client/js', 'node_modules']`)

If I don't use the linked/local copy of `mds` and I `npm install` it instead, then the build process is fine. Any idea why this may be the case? (if it's not a bug)

Thanks!

**Comment by jokeyrhyme** [comment]
I had this error as well.

As soon as I replace the `npm link` dependency with a normal `npm install` dependency, everything works fine.

**Comment by kpdecker** [comment]
When using `npm link`, the resolve is done relative to the actual files on disk, not the path of the link, i.e. `../mds.js` not `./node_modules/mds.js`. Due to this, require isn't going to be able to find `./node_modules/d3`. There are a number of ways around this, but they all depend on the exact configuration that you are working with. The simplest likely is creating an alias with the path to d3 in your webpack config.

```
resolve: {
  alias: {
    d3: require.resolve('d3')
  }
}
```

But you may also want to consider adding d3 as a dependency to the linked module. Note that when doing that, you can potentially run into issues with having multiple different instances of the dependency, in which case you need to link that dependency to ensure that any state stored in the module is maintained.

**Comment by jokeyrhyme** [comment]
So, this is an npm/node issue and not a webpack issue?

**Comment by kpdecker** [comment]
You'd see similar behaviors if using native node `require`. There is an recent open issue on this but this behavior has been like this for many years so I'm doubtful that the node behavior will change. https://github.com/nodejs/node/issues/3402. Webpack could do something different if they choose to, but that would be a decision for the maintainers of webpack, which I am not.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#145
