### ISSUE TITLE
Dependency miss match error is throwing while npm install if we use `jsonpscriptsrc-webpack-plugin` npm package with gulp 4.0.2

### ISSUE THREAD

**Issue by Aravinth113** [webpack/webpack#16052]
If we try to `npm install` the `jsonpscriptsrc-webpack-plugin` npm package along with gulp 4.0.2 to override the `jsonpScriptSrc` method, we are facing the dependency mismatch issue.

This issue is occurring only if we use the node version 15.0.0 to 15.7.0 and having gulp 4.0.2 in dependency list. For other node versions, it installs the package fine.

![image](https://user-images.githubusercontent.com/63036062/179185714-e9969d31-c9c3-4e02-b32c-8fcc3595e2d5.png)

Issue details:

![image](https://user-images.githubusercontent.com/63036062/179184496-89d8c0ef-5d72-4fa9-b7af-45aa63aef929.png)

Replication procedure:

1. Download and unzip the attached zip file.
2. In that folder, having a package.json file
3. Switch the node js version to 15.7.0
4. Try to `npm install` inside the folder location and you will find the issue.

[webpack.zip](https://github.com/webpack/webpack/files/9119202/webpack.zip)

**Comment by alexander-akait** [comment]
Please open an issue in `jsonpscriptsrc-webpack-plugin`

**Comment by karavinth** [comment]
Hello @alexander-akait, Thanks for your update.

I have searched `jsonpscriptsrc-webpack-plugin` GitHub repo for creating the ticket. But the repository is not found and npmjs also not given `jsonpscriptsrc-webpack-plugin` repository URL.

FYR: https://www.npmjs.com/package/jsonpscriptsrc-webpack-plugin

**Comment by alexander-akait** [comment]
Pleae write about this to npm team, it can be a maleware

**Comment by cipollafrancesco** [comment]
Hey,

**I ran into the same issue while upgrading an old repo to Webpack 5.**

At runtime, I was getting the following error:

```
ReferenceError: jsonpScriptSrc is not defined
```

After investigating, I discovered that the problem was caused by a dependency conflict in my `package.json`. Specifically, I had the `webpack-retry-chunk-load-plugin`, which had a peerDependency on Webpack 4.

To resolve it, I removed the plugin from my dependencies and from my production config (`webpack.prod.js`).

Here’s how it looked before the fix:

```js
new RetryChunkLoadPlugin({
  maxRetries: 3,
  retryDelay: 3000,
}),
```

After this change, the `jsonpScriptSrc` error disappeared. 
**I also confirmed by searching through the entire build folder, and the broken `jsonpScriptSrc` reference no longer appears.**

Hope this helps!
