### ISSUE TITLE
webpack loader with npm link

### ISSUE THREAD

**Issue by acnovais** [webpack/webpack#1613]
I am using webpack with babel loader. I have one other local module in ES6 that needs to be processed by babel so I changed my loader config as follows:

```
loaders: [{
      test: /\.js$/,
      loaders: ['babel'],
      exclude: /node_modules\/(?!other-module)/,
      include: __dirname
}]
```

This works fine when the dependency is installed normally. But if I use npm link instead of installing, that module is not processed by the loader. 

Am I missing something? Or is there a workaround for this?

**Comment by kumavis** [comment]
>  npm linked modules doesn’t find their dependencies
https://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

**Comment by acnovais** [comment]
My problem is not that the linked modules don't find their dependencies. That is something that "comes later".
It is that they aren't even processed by the loader.

**Comment by agonbina** [comment]
Currently dealing with the same issue here, I've tried aliasing the module name to the actual local path where the linked package is located, and added the same path to the `include`s array in the babel loader configuration but webpack is not able to recognize this. 

Any ideas how to get ES6 modules installed via `npm link` to work with Webpack?

**Comment by heruan** [comment]
Same here: the bundle gets messed up with both `npm link /path/to/foo` and `resolve.alias.foo: '/path/to/foo'`.

**Comment by kub1x** [comment]
Ok. I was about to complain here, but then I fiddled with it a bit more and the sun rose above and  some configuration that **does work** appeared from some (un)holly place: 
```
module.exports = {
  resolve: { 
    // EITHER this (which I find nicer):
    alias: { "my-package": path.join(__dirname, "node_modules/my-package" },
    // OR this (surprisingly both worked for me): 
    //alias: { "my-package": path.join(__dirname, "../my-package" },

    // You don't really need the resolve.fallback unless you do: import "something"
    // that is not in my-package's package.json dependencies. 
    //fallback: path.join(__dirname, "node_modules") 
  },

  // I thing this is the biggie so that webpack uses root project's loaders 
  // when they are absent in your linked package. Deduced from the name...
  resolveLoader: { fallback: path.join(__dirname, "node_modules") },

  module: {
    loaders: [
      // The TypeScript loader is used just for everything (no include). 
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader'],
        exclude: [/\.(spec|e2e)\.ts$/]
      },
      // But I used the sass for my-package only. Absolute path ONLY here!
      {
        test: /\.scss$/,
        include: helpers.root('../my-package/src'),
        loaders: ['raw', 'sass']
      },
    ]
  }
};
```
Just for completenes: 
* I linked my package using `npm link ../my-package`. 
* This is an Angular2 project thus the sass and typescript. 
* No loaders are installed in `my-package` all are used from my apps dependencies. 
* But the loaders must be pointed to `my-package`s **actual** directory, or used everywhere. 
* `--watch` works on my module so the server reloads when I change it, yaaaay!

**Comment by tomprogers** [comment]
> Any ideas how to get ES6 modules installed via npm link to work with Webpack?

If you're using `npm link`, I assume you're trying to build a project that depends on a module that you are also developing simultaneously, which is what's causing problems. I'm doing the same thing.

By convention npm modules are published in ES5. My understanding of the problem here is that, by using `npm link` to pull in a module, we bypass the normal `npm publish` process, including the pre-publish transpilation step. Unless the host project's JS environment happens to resemble that of the linked module, or if you've specifically instructed webpack to ignore `node_modules` (which 99% of all boilerplates & tutorials do), then your host project won't be able to properly transform the linked module.

I don't think it's a good idea for consuming projects to simply repreat a linked module's transpilation settings, which is essentially what people seem to recommend.

I think a better remedy would be to actually run the linked module's build process from within that project folder, and then leave the built assets in place. That seems to have worked for me.

**Comment by op1ekun** [comment]
@tomprogers Not that simple unfortunately. All my `npm-link`ed modules are built locally so their `package.json` points to a `dist` directory with already transpiled files. However I still run into:
```
Module not found: Error: Cannot resolve module 'babel-loader' in /Users/xxx/Workspace/my-project/dist/my-module
```
when try to use `webpack` in the main app :/

`resolveLoader` doesn't to anything for me...

**Comment by op1ekun** [comment]
I'm on macos so I went `osxfuse` + `bindfs` way. Works like a charm.
Linux guys should just use `mount --bind`.

**Comment by ryancastle** [comment]
In webpack 3, this resolved the loader issue for a globally installed `ts-loader`.

    resolveLoader: {
        modules: ['/usr/lib/node_modules']
    }

**Comment by cdtinney** [comment]
@tomprogers could you expand on how you've done this?

> I think a better remedy would be to actually run the linked module's build process from within that project folder, and then leave the built assets in place. That seems to have worked for me.

**Comment by tomprogers** [comment]
@cdtinney It's been a while, but this is what I recall.

- My app is in `~/projects/my-app`
- The dependency that I'm npm-linking (which I'm also maintaining) lives in `~/projects/cool-module`
- The problem is that running my-app's build process fails to process cool-module's source correctly

1. `cd ~/projects/cool-module`
2. `npm build` (or whatever script the module provides for compilation)
3. `cd ~/projects/my-app`
4. `npm start` (or whatever app script you're trying to run, which has been failing because of un-compiled dependencies)

It's not my-app's job to know how to transform cool-module's source.
