### ISSUE TITLE
strictExports: true is not enforced if unused module is empty

### ISSUE THREAD

**Issue by eps1lon** [webpack/webpack#16213]
# Bug report

[Similar to #4897](https://github.com/webpack/webpack/issues/4897)

**What is the current behavior?**

Importing a non-existent named export from an empty module triggers no warning with `strictExports: true`

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro: https://github.com/eps1lon/webpack-strict-exports-empty

**What is the expected behavior?**

`export '...' was not found in '...'`

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.14
Operating System:  MacOS Monterey
Additional tools:

**Comment by alexander-akait** [comment]
@eps1lon That is intresting, because there is no bug here. Set `type: "javascript/esm"` and you will see it.

Why? Webpack tries by default parse source code using `javascript/auto` (i.e. firstly `javascript/dynamic` then  `javascript/esm` if an exception was thrown). The `strictExports` option works only for  `javascript/esm`. But when a file is empty, webpack successfully parses a file as `javascript/dynamic`, because it was parsed as not `javascript/esm` (i.e ECMA modules) you didn't get errors.

There are two solutions:
1. Parse files as `javascript/esm` firstly (it will be breaking change, we are considering it for webpack v6)
2. Set `javascript/esm` for loaders (reccomended) https://webpack.js.org/configuration/module/#ruletype

**Comment by eps1lon** [comment]
>  That is intresting, because there is no bug her

If I feed this code to a runtime implementing modules according to spec, it does throw a SyntaxError.
I added a `js-modules` folder to the repro which reproduces with a completely empty `getBiometricsSecret.js` and a `getBiometricsSecret.js` with just `export {}` (and therefore doesn't match what Webpack does).

 So if you don't want to surface these errors, then it's not a bug. But a bundler should actually reject invalid JavaScript in my opinion. I'm a bit confused how you can justify wether something is a bug by using the implementation. With that reasoning nothing is a bug.

**Comment by alexander-akait** [comment]
> If I feed this code to a runtime implementing modules according to spec, it does throw a SyntaxError.

Yes, you are right. But webpack consider empty file as `javascript/dynamic` firstly (i.e. non ESM) as I written above.

> I added a js-modules folder to the repro which reproduces with a completely empty getBiometricsSecret.js and a getBiometricsSecret.js with just export {} (and therefore doesn't match what Webpack does).

> So if you don't want to surface these errors, then it's not a bug. But a bundler should actually reject invalid JavaScript in my opinion. I'm a bit confused how you can justify wether something is a bug by using the implementation. With that reasoning nothing is a bug.

Yes, it is the bug if you are considering your project as ESM firstly. I just want to say that we can't change this now - it will be a breaking change, so we are considering it for webpack v6. Changing logic now could potentially break code for other developers, that is why I marked it for webpack v6. 

Currently you can set `javascript/esm` for loader which handle ESM files:
```js
rules: [
      {
        test: /\.m?(j|t)s$/,
        type: "javascript/esm",
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-typescript", "@babel/preset-env"],
          },
        },
      },
    ], 
```

Even more you can put `import "./index.ts";` (just for test) in `getBiometricsSecret.ts` and comment empty export and webpack throws an error (because now it parsed as `javascript/esm`)

**Comment by alexander-akait** [comment]
We considered it even for webpack 5 - https://github.com/webpack/webpack/projects/5#card-10425786 but the feedback then showed that most of the projects are not ready in this, so we postponed it

**Comment by vankop** [comment]
sounds like with `javascript/esm` should be an error.. not sure.

**Comment by alexander-akait** [comment]
@vankop if you set `javascript/esm` you will get this error, just try it using the repo above

**Comment by eps1lon** [comment]
I don't get what Webpacks's notion of "type" has anything to do with it other than explaining the implementation. This is just an implementation detail for me. 

I understand you don't want to change the behvavior for the default but if I set `strictExports`, I want `strictExports`. It doesn't matter to me wether Webpack considers empty files a different type. JavaScript does not and that's what `strictExports` should be for. Otherwise we created another migration step that will just cause frustration in the ecosystem: CommonJS sloppyness, Webpack `strictExports` and JS modules. Webpack is injecting itself into the ecosystem when all there should be are CommonJS sloppyness for historic reasons and JS modules.

**Comment by alexander-akait** [comment]
You can do it, just set `type: "javascript/esm"` and webpack will do it as you expected. We can't change logic for `type: "javascript/dynamic"`, we don't know original type of JS/TS when we parse them, so when you have empty file we don't know is it ESM or is it CommonJS, you can `require` empty file, even more you can add export in `setTimeout` and another dirty/hacky ways, so we can't report about these errors. There is only one solution - parse files as ESM first, but it will be breaking change for webpack v5 and sorry we can't change it right now.

**Comment by vankop** [comment]
@eps1lon set
webpack.config
```js
module.exports = {
  module: {
     rules: { type: "javascript/esm" }
  }
};
```

or in root package.json `type: "module"`

**Comment by vankop** [comment]
right now by default we have `javascript/auto`, this allows bundling esm+cjs together

**Comment by alexander-akait** [comment]
@vankop Let's keep open for webpack v6, because I think we should solve it in the next major release (maybe we should switch on ESM first)
