### ISSUE TITLE
Double loader application when using configuration & require loader directive in same app.

### ISSUE THREAD

**Issue by sterpe** [webpack/webpack#1626]
My feeling is that something like this should not result in a webpack compilation error which seems to occur because the loader is applied twice, or that there should be someway to do this, such that it doesn't result in an error.

```
//a.js
  require('json!./foo.json')
//b.js
  require('./foo.json')

//webpack.config.js
  module.exports {
    //..
    modules : {
      loaders: [
        { test: /\.json$/, loader: "json" }
      ]
    }
  };
```

This has come up in our application because we still run unit tests for the moment vis-a-vis requireJS, but would like to transition new modules to commonJS syntax (no overloaded requires).

I had hoped that making the loader.test a function would allow me to do something like this:

```
ƒ(filename) {
  return /\.json$/.test(filename) && (! /^json\!/.test(filename))
}
```

But the `filename` argument does not include the loader directive.

**Comment by sokra** [comment]
Just don't use the inline require syntax for these loaders. It makes no sense to use it for loaders that can be matched to an extension. Always use the configuration for these loaders.

If you still want to use the inline require syntax, i. e. if you want to apply other loaders than in configuration, prefix a `!`: i. e. `require('!raw!./foo.json')` gives you the raw file content instead of a json object. (`!` prefix **override** the configured loaders)

Use inline require syntax for loaders that **add** behavior to the module: i. e. `require('bundle!./foo.json')` loads the module on demand in addition to returning a json object.

But you would never use the `json-loader` in a require. It's a loader that is always bound to the extension. Same with `babel-loader`, `coffee-loader`, `html-loader`, etc. Everything that has a special extension.

**Comment by sterpe** [comment]
Thanks I guess for the moment i am trying to find a way to keep requireJS plugin syntax compat while shifting away from it in newer code.  Maybe I should rethink my approach
