### ISSUE TITLE
context.contextInfo.request doesn't return the correct value

### ISSUE THREAD

**Issue by its-dibo** [webpack/webpack#16299]
I created a [minimal reproduction](https://github.com/eng-dibo/issue-webpack-externals), run `npm run build`

in my webpack.config file I added a function to externals[] array, the first argument of this function accepts `context` which contains `contextInfo.request` which is expected to return the exact value provided in `import` or `require` statements.

but the actual value is different, it returns the absolute path 

open the file "src/file1.ts", you will see

```
import value from "./sub/fil2"
```
the expected value of `request` here is `./sub/file2`, but the actual received value is something like `/home/workspace/sub/file.ts`

**Comment by alexander-akait** [comment]
Good question, on the one hand yes, on the other resolved path is better to handle complex cases, but we should store the both things, but changing it will be breaking change for us, so let's add the new property - `originalRequest`, feel free to send a PR

**Comment by eng-dibo** [comment]
I see that there is a context wehere `context.contextInfo.issuer` is empty, 
i.e. the file is requiring itself 
I have to skip this context in order to see the actual context

```
 externals: [
    (ctx, cb) => {
     console.log(ctx)
      return cb(undefined, `commonjs2 ${ctx.request}`);

   // I should make this check every time
   //   if (ctx.contextInfo?.issuer) {
   //     return cb(undefined, `commonjs2 ${ctx.request}`);
   //   }
   //  cb();
    },
  ],
```

you will see something like this (windows)
```
{
  context: 'C:\\Users\\w.i\\Desktop\\tmp\\node\\issue-webpack-externals',
  request: 'C:\\Users\\w.i\\Desktop\\tmp\\node\\issue-webpack-externals\\src\\file1.ts',
  dependencyType: 'esm',
  contextInfo: { issuer: '', issuerLayer: null, compiler: undefined },
  getResolve: [Function: getResolve]
}
```

in dist/****/file1.js, it requires itself, or accurately it requires the source version of itself
```
require('C:\\Users\\w.i\\Desktop\\tmp\\node\\issue-webpack-externals\\src\\file1.ts')
```

**Comment by eng-dibo** [comment]
also, there is another issue (I updated the minimal repo to address it)

if file1.ts requires 'sub/file2' whitch in its turn requires './file3' (i.e ROOT/sub/file3.ts)
and we added /file3/ into externals[] list.

the scenario would be as following:
file1.js includes the compiled content of file2.js as it, whitch is expected
but file2.js content is `reuire('./file3')` which is excluded from the bundling
here is the problem, the final result of file1.js is `require('./file3') instead of `require('./sub/file3') which is wrong

and the context for this externals is something looks like:

```
{
  context: 'C:\\Users\\w.i\\Desktop\\tmp\\node\\issue-webpack-externals\\src\\sub',
  request: './file3',
  dependencyType: 'esm',
  contextInfo: {
    issuer: 'C:\\Users\\w.i\\Desktop\\tmp\\node\\issue-webpack-externals\\src\\sub\\file2.ts',
    issuerLayer: null,
    compiler: undefined
  },
  getResolve: [Function: getResolve]
}
```
here is file2 is the issuer, but actually as it merged into file1, the real issuer should be file1
