### ISSUE TITLE
[idea] Use Discourse instead of Gitter.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1644]
It is free, can be self hosted, and has unlimited history, and is easier to keep track of conversations with. In Gitter and Slack, conversations get lost (especially when the room has tons of users like Webpack's room does). It has all the good things, like super configurable notifications, @mentions, and GitHub Markdown.

http://discourse.org.

Examples:

* https://forums.meteor.com
* http://forums.infamous.io
* http://discourse.wicg.io
* https://forums.hummingbird.me
* http://teh.moe
* https://tekinvestor.no
* https://animeforums.me
* http://discourse.wicg.io

**Comment by sokra** [comment]
The hosting is not free.

**Comment by sokra** [comment]
But I really like it. If it would be free for open source projects I would use it.

**Comment by Daniel15** [comment]
Discourse isn't too good, especially not on mobile. It doesn't really have any "killer features" over other forum systems, and is generally a lot buggier. If you want a forum system, I'd suggest more fully-featured and well-known systems such as SMF, phpBB or Vanilla over Discourse.

**Comment by trusktr** [comment]
@sokra 

> But I really like it. If it would be free for open source projects I would use it.

It's [completely free and open source](https://github.com/discourse/discourse) and can be self-hosted. All you need is some server to put it on.

@Daniel15 

> Discourse isn't too good, especially not on mobile. It doesn't really have any "killer features" over other forum systems, and is generally a lot buggier.

I feel like that's completely opposite of my experience. It works fine on Mobile. The three forums softwares you mentioned are all using outdated techniques (full page reloads). SMF ([this one](http://www.simplemachines.org/)?) isn't mobile at all. And how is Vanilla's ([this one](https://vanillaforums.com)?) mobile view any better than Discourse?

**Comment by Daniel15** [comment]
> I feel like that's completely opposite of my experience. It works fine on Mobile. 

Do you have a high-end phone? Discourse is not very efficient and uses a lot of RAM, so it only really works on very high-end phones. Most of the world is still on entry-level Android devices, on which other sites work fine but Discourse-powered sites perform very poorly. Perhaps developers are more likely to have newer more expensive phones, but "you can't use this site because your phone isn't good enough" isn't a good experience IMO.

As an example, the infinite scroll in Discourse simply keeps appending data to the page, rather than properly recycling DOM nodes. This means that scrolling through a post will use more and more RAM until the tab crashes. Not really much of an issue on desktop, but definitely an issue on mobile due to lower per-app memory limits. Because they use infinite scroll, the "home" and "end" keys on the keyboard don't do what you'd expect.

Additionally, Discourse has no proper bug tracker. They use the forum for tracking bugs, resulting in a pretty terrible experience (eg. there's no connection between commits and bugs). It's bad enough that people have set up unofficial bug trackers for it (discoursebugs.com used to be one, but it looks like that's since been taken offline).

>  The three forums softwares you mentioned are all using outdated techniques (full page reloads)

I guess Github is also outdated, as most actions result in full page loads. Google too - Going through search results does full page reloads. The whole web doesn't need to unnecessarily use AJAX :smile: Most forum systems use AJAX where it makes sense, like when writing replies.

> And how is Vanilla's (this one?) mobile view any better than Discourse?

I haven't actually tried Vanilla much on mobile, just on desktop. But for one, they use proper pagination, so you don't encounter the issues with infinite scroll on mobile. The site you linked is the commercial version of Vanilla, the open source site is at http://vanillaforums.org/discussions.

**Comment by sokra** [comment]
> I guess Github is also outdated, as most actions result in full page loads. Google too - Going through search results does full page reloads.

github and google don't do full page loads.

**Comment by Daniel15** [comment]
> github and google don't do full page loads.

Hmm, good point! My knowledge is outdated :D I'll edit that out of my post. Github never used to do AJAX loading other than for comment submission, I must have not noticed that.

**Comment by trusktr** [comment]
> Most of the world is still on entry-level Android devices

This is a good point to keep in mind. Discourse has a no-javascript fallback.

**Comment by bebraw** [comment]
This probably isn't going to happen unless someone steps up and starts to host and maintain it.

By the looks of things [gitter](https://gitter.im/webpack/webpack) and [Stack Overflow](https://stackoverflow.com/questions/tagged/webpack) seem to work adequately. There is also a community at [Reactiflux](http://www.reactiflux.com/) too. I would love to push a lot of support issues to Stack Overflow and perhaps stop accepting support related questions here (cleaner).

**Comment by bebraw** [comment]
Since April we've pushed a lot of support to Stack Overflow and implemented a proper issue template for the repository. A lot of people use the template and it has helped a lot. Sadly there's no way to force to use it (certain info is always useful). But overall the situation has gotten a bit better.

If someone wants to run and handle Discourse or other webpack forum, feel free to go. We can even link to it.
