### ISSUE TITLE
Remove tab prefixing of souce code?

### ISSUE THREAD

**Issue by josdejong** [webpack/webpack#166]
Right now, when bundling a bunch of javascript files, each line of source code is prefixed with a tab ([see code](https://github.com/webpack/webpack/blob/master/lib/FunctionModuleTemplate.js#L23)). This adds quite some extra whitespace (for my project it results in a 4% larger library size). Besides that, my project uses 2-space indentation, so the resulting mix of tabs and spaces for indentation is quite weird.

I'm not sure if anyone prefers this extra indentation, but I would be very happy if webpack would just not add these tabs. Or make it customizable?

**Comment by mnpenner** [comment]
Thank you for the configuration option, but I think the default should be an empty string.

It took me quite awhile to figure out why tabs were appearing in the output of my program. It's because I was using ES6 template literals, which allow for multi-line strings. Inserting a tab at the start of each line actually changes the source code!

So either the default should be changed so as not to create bugs, or special care needs to be taken to not tab-in ES6 template literals.

**Comment by jhnns** [comment]
You're right, that's a valid use-case. @sokra what do you think?

**Comment by sokra** [comment]
yes, we should remove it (or default it to `""`)

**Comment by jhnns** [comment]
@mnpenner can you make a pull-request?

**Comment by mnpenner** [comment]
I can try.

```js
if(module.strict) source.add(this.outputOptions.sourcePrefix + "\"use strict\";\n");
source.add(new PrefixSource(this.outputOptions.sourcePrefix, moduleSource));
```

Wouldn't that cause the prefix to be added twice if `strict` is enabled?

**Comment by mnpenner** [comment]
Stats tests are failing because the byte size is off. I can 'correct' the expected stats, but then I'm assuming the new stats are actually correct.

**Comment by sokra** [comment]
`node test/statsCases/accept-stats.js` update the test cases for stats changes.

**Comment by mnpenner** [comment]
@sokra Oh.. I did it by hand. They're passing now. I'll know for next time. Thanks :)
