### ISSUE TITLE
HMR issues with ESM

### ISSUE THREAD

**Issue by nick4fake** [webpack/webpack#16606]
This file has a problem with ES module:
https://github.com/webpack/webpack/blob/main/hot/poll.js

![image](https://user-images.githubusercontent.com/1065993/210295997-960244b5-1bf3-4e59-aa4c-815704ba3138.png)

As per https://webpack.js.org/api/hot-module-replacement/ it should have conditional switch to import.meta.webpackHot

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Looks like some loader/plugins generate non ESM compatibility code, without more infromation we can't help you, sorry
