### ISSUE TITLE
Disabling evaluation of `import.meta` doesn't work reliably

### ISSUE THREAD

**Issue by hirasso** [webpack/webpack#16802]
# Bug report

Disabling evaluation of `import.meta` doesn't work reliably

**What is the current behavior?**

I have instructed WebPack not to evaluate `import.meta`:

```js
{
  // ...
  module: {
    parser: {
      javascript: {
        importMeta: false,
      },
    },
  },
  // ...
}
```

It works fine in simple cases, but will still evaluate `import.meta` if found in `new Url(path, import.meta.url)`:

```js
// Will not be evaluated (as intended)
console.log(import.meta.url);
console.log(new URL(import.meta.url).toString());

// If used as `base` for `new URL`, import.meta will still be evaluated (the bug):
console.log(new URL("./app.css", import.meta.url).toString());

// Workaround: Storing import.meta in a temporal variable disables evaluation:
const importMeta = import.meta;
console.log(new URL("./app.css", importMeta.url).toString());
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Instruct WebPack to disable evaluation of `import.meta` as [described in the docs](https://webpack.js.org/configuration/module/#moduleparserjavascriptimportmeta)
- Try using `new Url("./my-file.ext", import.meta.url)`

**What is the expected behavior?**

WebPack should leave `import.meta` untouched, even if being used inside `new Url("./my-file.ext", import.meta.url)`

**Other relevant information:**
webpack version: 5.76.0 
Node.js version: v16.13.2
Operating System: OSX
Additional tools: –

**Comment by alexander-akait** [comment]
Hm intresting, `import.meta.url` in such contest is a part of assets modules, so if you disable evalation of `import.meta.url` here you will disable assets modules at all (except `import "data:..."`), I am afraid some developer can want to have assets modules and disable evalation of `import.meta`, so I think it is not a bug and it is a feature require. But yes, it sounds misleading because you are waiting `import.meta` will be kept as is everywhere.

I think we can't change behaviour of this without breaking chage, so I'd prefer to add a new option - allow to disable assets modules at all, anyway you can manually change your `defaultRules` and don't add this https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L657

**Comment by hirasso** [comment]
Activity... 🤖😄

**Comment by alexander-akait** [comment]
@hirasso Just want to say we have https://webpack.js.org/configuration/module/#moduleparserjavascripturl, so if you put them to `false` you will keep `new URL(...)` syntax and import.meta.url

**Comment by hirasso** [comment]
@alexander-akait oh wow, thanks for pointing this out! That will work, thank you guys!!
