### ISSUE TITLE
Add test coverage for `moduleFilenameHelpers`

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16851]
After approving #16756, I realized we do not have coverage (that I could find) for this or other moduleFilenameHelper scenarios. 

Documentation usages:
https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate

Let's add a set of cases to cover this in tests.

**Comment by dhananjay0610** [comment]
Hi, @TheLarkInn  can I start working on this, can you please assign this to me..

**Comment by alexander-akait** [comment]
You can send a PR

**Comment by ArchitGajjar** [comment]
Hi @TheLarkInn  - is this issue still open ? can i work on this ?

**Comment by mayankkamboj47** [comment]
@TheLarkInn I've opened a PR. But I couldn't test some parts of the file, because the examples/test cases you guys left out in the comments actually don't match the output the functions give. 

For `replaceDuplicates`, the comment says : 
```
 const array = ["a", "b", "c", "a", "b", "a"];
 const result = ModuleFilenameHelpers.replaceDuplicates(array, (item, index, count) => `${item}-${count}`);
 // result: ["a-1", "b-1", "c", "a-2", "b-2", "a-3"]
 ```
But the actual output starts counting from 0,  ["a-0", "b-0", "c-0", "a-1", "b-1", "a-2"]

For `matchPart`, the comment says
```
 ModuleFilenameHelpers.matchPart("foo.js", "foo."); // false
```
but the actual output is true.
