### ISSUE TITLE
Best way to use JSX with webpack-2

### ISSUE THREAD

**Issue by maxenglander** [webpack/webpack#1704]
I'm trying out webpack-2. It seems that, in order to do code-splitting with ES6, I should drop babel and let webpack compile ES6 with Acorn. If I'm right about that, is there any recommended way to do React parsing? If no way/loader exists yet, what would be the proper way to roll my own?

**Comment by Ceane** [comment]
You can do code splitting with webpack-2 using babel using [System.import](http://www.2ality.com/2014/09/es6-modules-final.html#the_ecmascript_6_module_loader_api) instead of `require.ensure`. The thing I think you are referring to is tree shaking, which IMO webpack already does, though not as natural as ES6 import/exports allow. 

I have an example for you [here](https://github.com/Ceane/webpack-2-w-babel-example). Note that I am using Babel 6.
