### ISSUE TITLE
Using resource query strings is incompatible with a package's "exports" field for defining entry points

### ISSUE THREAD

**Issue by ferdaber** [webpack/webpack#17181]
# Bug report

**What is the current behavior?**
Currently, you cannot use resource queries in an import for a package who has defined an `"exports"` field, because webpack thinks that the entire import path should be resolvable in the target package's entry points.

**If the current behavior is a bug, please provide the steps to reproduce.**

Say you have the following construction:

**Some package that is in `node_modules` with the following `package.json`**
```jsonc
// my-package/package.json
{
  "name": "my-package",
  "exports": {
    ".": "main.js"
  }
}
```

**Entry point of bundle**
```js
// entry-point.js
import sourceString from 'my-package?source';
```

**Webpack configuration**
```js
// webpack.config.js
module.exports = {
  entry: "./entry-point,js",
  module: { rules: [
    {
      resourceQuery: "source",
      type: "asset/source"
    }
  ] }
};
```

Attempting to build this will produce the following error:
```
ERROR in ./entry-point.js
Module not found: Error: Package path ./?source is not exported from package <path>/node_modules/my-package
(see exports field in <path>/node_modules/my-package/package.json)
```

**What is the expected behavior?**

It seems that Webpack is not stripping out the resource query part of the import URL prior to attempting to resolving it against the package's entry points. Moreover, attempting to actually add an entry point defined as `"./?source"` in `my-package/package.json` will result in webpack skipping the entire resource query rule entirely (as in, it will assume there is no resource query, and replaces the resource path with whatever is resolved from the `"./?source"` export condition.

I expected the resolution logic to resolve the package entry point without the query string first (aka to `my-package/main.js`), and then apply the resource query afterwards (as if the import was to `"my-package/main.js?source"`)

**Other relevant information:**
webpack version:  5.82.1
Node.js version: 16.17.0
Operating System: Win 10
Additional tools:

**Comment by alexander-akait** [comment]
Expected, run your code without `webpack` (i.e. `node ./entry-point.js`) and you will have the same behaviour, also you need to use `".": "./main.js"`, and also I strongly recommend to use `new URL("path/to/file.ext", import.meta.url);` for assets modules and avoid using `import`, because it will allow to run your code without bundler in future and will be more compatible between different enviroments.

Sorry, we can't change default Node.js logic, if you still think it is a wrong behaviour, please open an issue in Node.js repo

Also if you really need this, you can create a small plugin for the resolver to work with it.

But again, it is very unsafe because you include raw code in your bundle, I strongly recommend to use `new URL(...)` syntax and use `asset/resource`/`asset/inline` for your case.

**Comment by fregante** [comment]
I don't understand this logic. Webpack allows `import stylesheet from "bootstrap/scss/bootstrap.scss?url"` which definitely won't work in node, so why is webpack suddenly limited by what node can do?

**Comment by alexander-akait** [comment]
@fregante Because `bootstrap` doesn't have the `exports` field - https://github.com/twbs/bootstrap/blob/main/package.json

**Comment by fregante** [comment]
That was just an example. Webpack allows importing anything as long as you specify how to deal with it in its config. 

```js
import "./style.css"
``` 

👆 does not work in node. Works in webpack. 

> so why is webpack suddenly limited by what node can do?

**Comment by alexander-akait** [comment]
@fregante Yes, webpack allows, the main problem here is resolving, not in imports and what you are importing, resolving `exports` will be backported from node.js and align with it, what is your problem and why do you try to solve?

**Comment by fregante** [comment]
Nothing is stopping webpack from separating `path` from `?url` _before_ passing it to the resolver. I don’t think I've ever seen anyone using search parameters in exports maps, so it does not belong there.

I made a [small repro](https://github.com/fregante/webpack-sandbox/tree/main/exports-plus-search-params) with webpack and vite. Build output and logs are committed too. It points to `p-memoize`, which effectively uses `"exports": "./index.js"`, the most restrictive type of exports map. Vite can handle `"p-memoize?raw"` and `"p-memoze?url"`

**Comment by alexander-akait** [comment]
> Nothing is stopping webpack from separating path from ?url before passing it to the resolver

No we can't, otherwise it will break `exports` logic and you will get access to private modules, we **should not** change default Node.js resolving behavior. This issue was previously discussed with the node team and other developers, and everyone jointly decided not to provide this ability because it could violate a lot of things

> Vite can handle "p-memoize?raw" and "p-memoze?url"

Vite uses `?raw` and `?url` query parameters to specify how to generate module output and that is why they are stripping from original request, we don't provide such ability and pass all query parameters to original resource, technically vite violates resolving spec too here

The specification clearly states how resolving should work for the `export` field, and we do not want to give the opportunity to violate the specification

**Comment by fregante** [comment]
> you will get access to private modules

If you can resolve `"p-memoize"`, I'm only asking to resolve `"p-memoize?raw"` the same way as `"p-memoize"` _and then_ treat it as an asset. This has nothing to do resolving files not listed by the `exports` map.



> otherwise it will break `exports` logic

The only reason I see here, I just found out, is that search parameters _can_ be part of the exports map. 

```json
{
  "name": "my-lib",
  "exports": {
    ".": "./root.js",
    "./?param": "./param.js"
  }
}
```

and this works in node:

```js
import('my-lib');        // loads root.js
import('my-lib/?param'); // loads param.js
```

This satisfies me 👍

**Comment by alexander-akait** [comment]
> The only reason I see here, I just found out, is that search parameters can be part of the exports map.

Yes, they can be part and can be used how you write above

> If you can resolve "p-memoize", I'm only asking to resolve "p-memoize?raw" the same way as "p-memoize" and then treat it as an asset. This has nothing to do resolving files not listed by the exports map.

Please read the resolving specification (on Node.js docs site). You can return different modules using query parameters (as you done above). We can't simply allow `?raw`, since someone could export `?raw` and return another module (I know that more likely no one will do it, but this is a clear description of the logic how resolving should work), this would break the resolving logic at all, that is how resolving works.
