### ISSUE TITLE
Suggestion: {'process.env' :{NODE_ENV:JSON.stringify('production')}} vs {'process.env.NODE_ENV':JSON.stringify('production')}

### ISSUE THREAD

**Issue by aunz** [webpack/webpack#1720]
Hello

With this entry

``` js
//entry.js
let p = process
let e = p.env
console.log(e.NODE_ENV,process.env.SOMETHING_ELSE)
```

if the definition is: 

``` js
//webpack.config.js (A)
new webpack.DefinePlugin({'process.env':{NODE_ENV:"'production'"}})
...
//output.js
var p = process;
var e = p.env;
console.log(e.NODE_ENV, {"NODE_ENV":'production'}.SOMETHING_ELSE);
```

But

``` js
//webpack.config.js (B)
new webpack.DefinePlugin({'process.env.NODE_ENV':"'production'"}),
...
//output.js
var p = process;
var e = p.env;
console.log('production', process.env.SOMETHING_ELSE);
```

With webpack 2.0.1-beta in Windows 10.

This [example](https://github.com/webpack/react-starter/blob/master/make-webpack-config.js) by the main author also uses the config (A). Wouldn't config (B) be better?

**Comment by sokra** [comment]
webpack should better emit `undefined` for `process.env.SOMETHING_ELSE` because it can know that it is undefined.

**Comment by negativetwelve** [comment]
Just wanted to leave a comment here because this issue actually affected us pretty badly when we upgraded to 2+.

We're using `2.1.0-beta.25`, setting:

```
new webpack.DefinePlugin({
  'process.env': {
    'NODE_ENV': JSON.stringify('production'),
  },
}),
```

will actually override ALL of `process.env` effectively getting rid of all environment variables set (via something like heroku).

Setting it to:

```
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production'),
}),
```

solves the issue where ONLY `process.env.NODE_ENV` is set. This makes sense, but I believe it's different from Webpack 1 and should be pointed out. 

Hope this helps someone!

**Comment by forresto** [comment]
I don't understand using `JSON.stringify('production')` over `'"production"'` or `"\"production\""` ... is there a reason to rely on the `JSON.stringify` quirk?

**Comment by Kovensky** [comment]
@forresto if the value is a string, webpack treats it as replacement _code_. Using `JSON.stringify` is the more obvious way to ensure that the string will result in a string when inserted in the code, instead of an identifier; it may also be important if the string you're going to use may have embedded quotes.

**Comment by stevematdavies** [comment]
```
new webpack.DefinePlugin({
  "process.env": { 
     NODE_ENV: JSON.stringify("production") 
   }
})
```

Chrome Error:

`Uncaught Error: React is running in production mode, but dead code elimination has not been applied`

**Comment by enriquecaballero** [comment]
Getting the same error as @stevematdavies.

**Comment by aunz** [comment]
@stevematdavies  try `new webpack.DefinePlugin({ 'process.env.NODE_ENV' : "'production'" })`

**Comment by cannyedge34** [comment]
Getting same error as @stevematdavies, @enriquecaballero 

@aunz  this code `new webpack.DefinePlugin({ 'process.env.NODE_ENV' : "'production'" })` throws this error in console:

`You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.`
