### ISSUE TITLE
combine all static files to respective singular files

### ISSUE THREAD

**Issue by matt212** [webpack/webpack#1745]
Hi , 
how can we combine all external files like js and css files to respective singular file and then minify 
the singular file of css and js using webpack

**Comment by shama** [comment]
By creating an entry point and `require()`ing the other files. Then use the [uglify plugin](https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin) to minify.

See: http://webpack.github.io/docs/tutorials/getting-started/

**Comment by matt212** [comment]
Hi, 
i know that is self explanatory but how to do it dynamically and without modifying(adding require in every js file we want to combine ) any other js file.
something like 
entry ['file.js',file2.js,file3.js]
output
  [consolidated file (file.js+file2.js+file3.js)]

**Comment by shama** [comment]
I'm probably not understanding the request but if you want to concat files together just read the files and concat the strings together. You don't need webpack for that.

webpack and module bundlers in general are not designed to concat files together. Rather you specify which files depend on each other and the module bundler pieces those files together in a far more optimized way then simple concatenating.

**Comment by matt212** [comment]
Hi, 
thanks for clarification .
I have 153 js and 28 css files which I manually need to concate and minify and then publish to prod 
kinda tedious process for every build release  .
hence  I wanted to make compiler so that when we want to publish to prod all static files (js and css)
should be converted to minified  respective singular files and then those contents of files would be placed to required webpages so that when all js,css content would be on page for optimization purpose rather than on files

**Comment by involve-it** [comment]
Hi, 
It is really strange there is no plugin for simply appending a file to a bundle without 'requiring' or using loaders. Very simple use case: I have a bunch of minified verndor css libs, if I bundle them using loaders, build will take ~5 seconds (because css loaders actually parse files), so I would rather just concat them for dev performance, knowing they are production-ready..  And I still would like to use Webpack since this is my chosen bundling tool.
Hope all that makes sense!

**Comment by shama** [comment]
If the build takes ~5 seconds for a simple use case, it's probably doing something it shouldn't or something that could be optimized. Are they simple CSS files or is it shelling out to ruby to compile sass files or some other heavy operation to compile?

For instance, the app I work on is very complex, has ~1000 scripts in typescript and ~100 CSS in stylus. It currently takes ~4 seconds to rebuild.

Be sure to take advantage of watch modes while dev'ing to reduce the build time. You can also configure webpack to avoid parsing files with [noParse](https://webpack.github.io/docs/configuration.html#module-noparse) too.

I don't think there is a plugin because blindly concatenating files is a simple operation without webpack: 

```shell
cat *.css > bundled.css
```
