### ISSUE TITLE
esm on module federation broken

### ISSUE THREAD

**Issue by wibed** [webpack/webpack#17479]
webpack crashes in production mode and on development outputs the error to be found in the following issue
https://github.com/module-federation/module-federation-examples/issues/3108

repro:
https://github.com/wibed/mfExample

relevant issues:
- https://github.com/webpack/webpack/issues/14111

set chunks to false, async or initial had no effect except for the server to start up and after 
the first request throw the error instead of during build time

**Comment by ScriptedAlchemy** [comment]
This is not a issue with webpack. This is module-federation/node library. ESM is filesystem bound, if you want federation with esm then you will have to make the files accessible over the filesystem. Streaming runtime requires me to wrap modules and my node plugin is a modified version of commonjs chunk loading runtime modules. 

since i cannot hot reload production with esm - i didnt bother to look deeper into esm support since fundamentally it wouldnt work nicely. 

Once NodeRealms is released and stable, it might be worth looking at again. 

Either way, please close this issue as webpack is working as expected
