### ISSUE TITLE
Minification step of production mode breaks build if key of object is diacritic character

### ISSUE THREAD

**Issue by unzico** [webpack/webpack#17507]
# Bug report

**What is the current behavior?**

The minification step of the production mode breaks the build and the code cannot be run inside the browser.

Explanation (please see the reproduction repo):
The `match-sorter` dependency includes a dependency called `remove-accents`, that maps characters with a [diacritic](https://en.wikipedia.org/wiki/Diacritic) to a character without a diacritic, e.g. `À` to `A`. This dependency is used in the `match-sorter` dependency to remove accents from strings before sorting them.

The original code is similar to this:

```js
var characterMap = {
  "À": "A",
  "Á": "A",
  "Â": "A",
  "Ã": "A",
  "Ä": "A",
  // ...
};
```

During the production build process (enabled by `config.mode === "production"`), webpack minifies the code. This results in the following code:

```js
// prettified for readability
var r = {
  // notice the missing quotes around the keys
  À: "A",
  Á: "A",
  Â: "A",
  Ã: "A",
  Ä: "A",
  // ...
};
```

The browser interprets this as a syntax error, because the keys are not quoted. This is not a problem in development mode, because the code is not minified and the quotes aren't removed. When we take a look at the source code in the browser, the code looks like this:

![Source code viewed in browser](https://raw.githubusercontent.com/unzico/webpack5-prod-minify/main/image.png)

The result: `Uncaught SyntaxError: Invalid or unexpected token (at main.js:233:14)`.
As soon as we put the key in quotes, the error is gone.

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone the following repo and follow the instructions described in the README.
https://github.com/unzico/webpack5-prod-minify

**What is the expected behavior?**

The minifier shouldn't remove the quotes from characters that have a diacritic, if the character is the key of an object.

Instead of 
```js
var r = {
  À: "A",
  Á: "A",
  Â: "A",
  // ...
};
```
it should be
```js
var r = {
  "À": "A",
  "Á": "A",
  "Â": "A",
  // ...
};
```

**Other relevant information:**
webpack version:  `5.88.2`
Node.js version: `18.16.0`
Operating System: `Windows 10`
Additional tools: `Google Chrome Version 114.0.5735.199 (official build) (64 bit)`

**Comment by ipatel5** [comment]
what is the workaround for this? i'm facing a similar issue.

 "webpack": "^5.88.2"

**Comment by unzico** [comment]
> what is the workaround for this? i'm facing a similar issue.
> 
> "webpack": "^5.88.2"

Unfortunately, we havn't found a workaround for this and build the app in development mode.

**Comment by unzico** [comment]
Bug still exists.

**Comment by fabiosantoscode** [comment]
I'm not sure what's going on. I cloned the repo, removed `yarn.lock` to update terser, and after `yarn; yarn prod` I can reproduce the issue in `dist/main.js`. But when I disable `optimizer.minimize` in webpack.prod.js and then put dist/main.js, now unminified, into terser, I can't reproduce it.

terser-webpack-plugin doesn't set any options, right?

I can't debug further, because I don't know how this yarn 2 space science works yet, and can't change Terser to add console.log or something like that.

**Comment by unzico** [comment]
I replaced yarn with npm. That should make it easier for you to debug it :)

**Comment by fabiosantoscode** [comment]
`npm why` is a really funny command to type out

**Comment by fabiosantoscode** [comment]
Looks like something is passing the `ecma: 2015` option, which makes Terser assume the recepient of its code can cope with these unescaped object keys.

I think this is a remnant of the time where setting `ecma` was necessary for the Terser parser to accept modern syntax, which is no longer the case. It now accepts any JS, however modern and the `ecma` option only changes the compression and output steps.

If it's necessary to support old Terser and new Terser simultaneously, `parse.ecma` can be set instead of the root `ecma`, so as to only apply to the parse step.

The failure in the screenshot with `À€` underlined probably was a Terser issue at some point, but it works now. I modified remove-accents to add the EUR sign somewhere and the output is correct.

```js
/*...*/={"À€":"A",Á:"A",Â:"A",/*...*/
```

Notice how only the problematic `À€` is quoted.

**Comment by alexander-akait** [comment]
Resolved
