### ISSUE TITLE
tree-shaking with lodash-es

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#1750]
See https://github.com/webpack/webpack/issues/1612#issuecomment-161018259.
Currently tree-shaking lodash-es modules is not possible with webpack 2 beta.

First clone into `node_modules`:

``` bash
git clone -b es --depth=1 https://github.com/lodash/lodash.git ./node_modules/lodash-es
```

then:

``` bash
npm i -g webpack@beta
```

then:

``` bash
npm i babel-loader@^5 babel-core@^5
```

with test.js:

``` js
import { chunk } from 'lodash-es';
console.log(chunk([1,2,3,4], 2));
```

then:

``` bash
webpack ./test.js ./bundle.js -p --display-chunks --display-modules --display-origins --module-bind js=babel-loader?blacklist[]=es6.modules
```

is

```
> gzip-size bundle.js | pretty-bytes
30.41 kB
```

While the output of `import { chunk } from 'lodash-es/array/chunk'`
is

```
> gzip-size bundle.js | pretty-bytes
1.19 kB
```

Related to https://github.com/rollup/rollup/issues/45

**Comment by jdalton** [comment]
Anything I can do to help?

**Comment by jdalton** [comment]
Ping.

**Comment by shama** [comment]
@jdalton Thanks for the notice! I'm sure @sokra will address when he gets time for it.

**Comment by jdalton** [comment]
Anything I can do to help?

**Comment by shama** [comment]
Yes! If you want, please test out the webpack 2 beta and investigate any issues you find. Or take a look at the issue tracker to help free up more of @sokra's time to put towards webpack 2. There are many questions that just need a little bit of research to address. Thanks!

**Comment by jdalton** [comment]
>  Yes! If you want, please test out the webpack 2 beta and investigate any issues you find. 

This issue is about webpack 2 beta, I did the investigation, and outlined how to reproduce the issue in detail. I believe I've created modules in a way that should enable tree-shaking. @shama do [you see](https://github.com/lodash/lodash/blob/es/lodash.js) any obvious issues? The only thing I can think of is that the inclusion of
```js
export { default as default } from './lodash.default';
```

is giving webpack 2 grief. What do you think?

**Comment by shama** [comment]
I'm not sure what the cause of this issue is. If I were to take a guess, it's likely babel is transforming the modules in a way that webpack can't remove the unused code or webpack is tripping on some syntax in lodash-es.

I'm not sure, I haven't tried debugging this issue yet.

**Comment by jdalton** [comment]
> If I were to take a guess, it's likely babel is transforming the modules in a way that webpack can't remove the unused code or webpack is tripping on some syntax in lodash-es.

\cc @sebmck

**Comment by sparty02** [comment]
@jdalton can you try with Babel 6?  default export semantics changed between Babel 5 and Babel 6, wondering if that could impact it?

**Comment by sebmck** [comment]
Is Webpack doing the DCE on the CommonJS output?

**Comment by sokra** [comment]
Not babels fault. I noticed the issue, but it's a bit difficult.

We can optimize it, but this would be an unsafe optimization. The ES6 spec says that all dependencies must be loaded even if the exports are not used.

**Comment by jdalton** [comment]
@sparty02 
> can you try with Babel 6?

Just tried and the result is similar to Babel 5 in terms of resulting file size.

@sokra 
> but it's a bit difficult.

Can you clarify (deep dive) into what the tricky part is.

> The ES6 spec says that all dependencies must be loaded even if the exports are not used.

Isn't the point of the tree shake optimization to work around this?

**Comment by jdalton** [comment]
Is there something I can do in the way I generate the lodash-es modules to make it easier for you?

**Comment by indeyets** [comment]
@jdalton generating single file without re-exports would solve the issue, I believe

**Comment by jdalton** [comment]
@indeyets Would you give an example to clarify.

**Comment by Awk34** [comment]
I think what @indeyets is suggesting is instead of importing and re-exporting like is done now:

```js
...
export { default as add } from './add';
...
```
to concatenate everything into a single file like this:
```js
...
export function add(augend, addend) {
  var result;
  if (augend === undefined && addend === undefined) {
    return 0;
  }
  if (augend !== undefined) {
    result = augend;
  }
  if (addend !== undefined) {
    result = result === undefined ? addend : (result + addend);
  }
  return result;
}
...
```

I doubt that this would change anything, though.

**Comment by jdalton** [comment]
> I doubt that this would change anything, though.

If it's already having a hard time recognizing there are no size effects to something straight forward (as it is now) I can't imaging inlining packages (with their local vars) would make things easier.

**Comment by Akkuma** [comment]
Maybe I'm misunderstanding the issue, but wouldn't that have to work @Awk34 ? Otherwise the entire tree shaking system would clearly not be working. The issue from my understanding is that by re-exporting causes webpack to not safely know if the original file causes a side effect during import. In other words, much like you can cause side effects just by `require('something')`, the initial imports to then export could be causing side effects. If every method was inlined into one file there would be no ambiguity.

This still seems highly impractical for most developers as they don't have tooling to make an inlined file just for webpack. If webpack allowed explicitly marking files as having side effects that would work around the spec I believe. Webpack already has its own `require.ensure`, so would it be that much of a leap to be able to declare imports with side effects?

**Comment by nlwillia** [comment]
It would be nice if there were standards support for a "weak reexport" that would say "I'm exporting this thing, but it doesn't need to be evaluated unless someone uses it".  This would not change the semantics of loading except that a loader _could_ use it as a signal to do more aggressive optimization.  Nothing prevents loaders from evolving this on their own as a comment or annotation or external configuration, but if there's value to it then having it in the language instead of being loader-specific would be better for everyone.

Obviously, if a naive weak reexport targets a module with default side-effects then you might see inconsistent behavior, but I don't think that risk means that a well-structured library like `lodash-es` shouldn't have the option to declare its own safety.  In SystemJS where all this happens in the browser, it's rather important that reexports _not_ be eagerly fetched, but there's no way to avoid that today without drilling down to the individual files (`import {x} from 'lodash-es/x'`) which is quite a bit less pleasant syntactically than plucking names out of a single lodash import (`import {x,y,z} from 'lodash-es'`).  Webpack doesn't have to be as concerned with when/if the dependency gets fetched (not that reading hundreds of lodash modules that it doesn't need to is a great thing), but it still would benefit from a clear signal that it can exclude something from the bundle.

**Comment by cspotcode** [comment]
LoDash uses its own functions to create some of its other functions, which triggers mandatory bundling of a lot of unused code.  For example, [instantiating `without` invokes `rest`](https://github.com/lodash/lodash/blob/4.6.1/lodash.js#L7076-L7080).  This means that, even if `without` is never imported, the entire implementation of `rest` and all its dependencies *must* be packaged in order to preserve possible side-effects.  Tree shaking and dead code elimination aren't allowed to remove `rest` unless they can prove it's a pure function (no side-effects).  Because JS is so dynamic and doesn't have static typing, this is almost never possible to prove at build time.

Dead code removers like Uglify could theoretically have a "frozen environment" or "predictable builtins" mode where they assume that all JS built-ins (Object, RegExp, window, etc) follow the JS engine's native behavior.  That means it could make additional assumptions about what does and doesn't trigger side-effects.

For example, today when Uglify sees this:
```
const unused = Math.floor;
```
it can only minify to this:
```
Math.floor; // gotta keep those side-effects; "floor" might have a getter function
```
With a "frozen environment" option, however, it could assume that accessing `Math.floor` is side-effect-free because no one has monkey-patched the environment.  This would require the code minifier to contain an inventory of JS's native APIs so it can make those decisions.  Anything not in that inventory, such as a new browser API or node built-in, would be assumed to trigger side-effects.

**Comment by cspotcode** [comment]
I put together a ready-to-run project that shows what webpack is emitting before and after dead code elimination.  It's more grokkable than the default minified output.  It has certainly helped me thinking about which code is reachable, what triggers side-effects, etc.

https://github.com/cspotcode/lodash-webpack-DCE-example

It writes plain and gzipped file sizes into `build/file-sizes.txt`.  Webpack emits code comments marking all exports as either used or unused.

**Comment by jdalton** [comment]
This issue seems to be resolved using webpack 2.1.0-beta.15 for both `lodash` and `lodash-es`.

`index.js`:
```js
import { chunk } from 'lodash-es';
console.log(chunk([1,2,3,4], 2));
```
and
```js
import { chunk } from 'lodash';
console.log(chunk([1,2,3,4], 2));
```

running
```bash
webpack ./index.js ./bundle.js -p --module-bind js=babel-loader?presets=es2015
```
generates a file that's ~1.3 kB gzipped.

**Comment by jdalton** [comment]
Oops false positive.

**Comment by Kovensky** [comment]
This is still the case in beta.25.

While webpack 2 will, correctly, not re-export any of the unused top-level re-exports, the `__webpack_require__` calls are left in. While this will, at an absolutely pedantic way, keep correctness as all the side-effects of the modules (such as requiring other modules and calling their functions) will still happen, it is not deletable by uglify ([the entry point](https://github.com/cspotcode/lodash-webpack-DCE-example/blob/master/build/named-export.js#L20137-L21067) from @cspotcode's repo, [the same module](https://github.com/cspotcode/lodash-webpack-DCE-example/blob/master/build/named-export-uglified.js#L3587-L3670) after uglify without mangling).

It would be better if, when an import is done specifically for reexporting (as is done in `lodash-es/lodash.js`, the entry point), the import call itself should not be emitted if it is unused. The unused dependencies also should be not emitted at all, as no minifier can tell that an array element accessed with a dynamic index is unused.

**Comment by wmertens** [comment]
Do we already know why this is not working? Is it because the default export exports everything, which means evaluating everything?

Even then, shouldn't side-effect-less functions then be removed by uglify?

I just would like to understand how to write code so that unused exports without side-effects are not included in the final bundle…

**Comment by obartra** [comment]
@wmertens I don't think it's the `default` export. I was wondering the same thing and tried the build with a custom version of `lodash-cli` that doesn't include the default export and webpack 2 still included everything.

I've put it in [this repo](https://github.com/obartra/lodashes-webpack)

**Comment by jdalton** [comment]
There's always [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to help with cherry-picking.

**Comment by wmertens** [comment]
Yes, and that works fine, but I'd like to know why it doesn't work out of
the box…

**Comment by jmlopez-rod** [comment]
I think it all has to do with the default exports. Consider the `lodash-es/isArray`. Currently this file looks like this:

```js
var isArray = Array.isArray;

export default isArray;
```

When I put this into my some file in my example I see the following in my webpack bundle:

```js
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an array, else `false`.
 * @example
 *
 * _.isArray([1, 2, 3]);
 * // => true
 *
 * _.isArray(document.body.children);
 * // => false
 *
 * _.isArray('abc');
 * // => false
 *
 * _.isArray(_.noop);
 * // => false
 */
var isArray = Array.isArray;

/* harmony default export */ __webpack_exports__["a"] = (isArray);
```

Somehow isArray got picked up and I never made use of it. Lets now change the exports so that we don't use `export default`:

```js
var isArray = Array.isArray;

// export default isArray;
export { isArray };
```

The new shiny webpack bundle already picked up the fact that I never used `isArray`:

```js
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export isArray */
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an array, else `false`.
 * @example
 *
 * _.isArray([1, 2, 3]);
 * // => true
 *
 * _.isArray(document.body.children);
 * // => false
 *
 * _.isArray('abc');
 * // => false
 *
 * _.isArray(_.noop);
 * // => false
 */
var isArray = Array.isArray;

// export default isArray;
```

I have a feeling that if the lodash modules would avoid using `export default` and instead export each function with the name it was given then webpack would have no issue shaking the tree.

Please see this tslint rule that was developed for linting typescript files to prevent users from using default exports:

https://palantir.github.io/tslint/rules/no-default-export/

Main point to take:

> current tooling differs on the correct way to handle default imports/exports. Avoiding them all
> together can help avoid tooling bugs and conflicts.

**Comment by wmertens** [comment]
Wow, weird, why would there be a difference between `default` and named exports? Is this perhaps some ES spec rule? If not, this seems like it could be a webpack bug…

**Comment by sokra** [comment]
This is really weird. The default export should be picked the same way. Could you file a new issue for this?

**Comment by jmlopez-rod** [comment]
Here is it: https://github.com/webpack/webpack/issues/4761. I hope you guys can reproduce it with the repo.

**Comment by damianobarbati** [comment]
Any news on this? I see lodash-es not tree shaked as well

```
import { map } from 'lodash-es';
```

But the whole lodash-es lib ends up in the vendor.min.js when building for production.
Works fine with custom code with exports.

**Comment by TrySound** [comment]
@damianobarbati Don't use it this way (until cherry picking babel plugin). Current problem is monkey-patched default export. And still in the next release monolitic bundle will be dropped.

**Comment by damianobarbati** [comment]
@TrySound how should I use it? 
With direct imports like `import map from 'lodash-es/map'`? 😱

I can't find much info on this cherrky-picking about babel, can you point something interesting about it? 

Thanks! :)

**Comment by wmertens** [comment]
I saw that with the externals config you could make a small function
to map requests for lodash.x to lodash/x.

However, I don't see a way to do that with named imports. Would be
nice to have a small function that just replaces named imports with
per-file imports.

**Comment by TrySound** [comment]
Sorry, forgot about links :)
https://github.com/lodash/lodash/wiki/Roadmap
https://github.com/lodash/babel-plugin-lodash

**Comment by damianobarbati** [comment]
Thanks so much! 

IMHO this sucks, because this means we're going to have this problem with a lot of modules.
Applying a direct plugin/exception for lodash does not look like a good fit :\

**Comment by TrySound** [comment]
This plugin is customizable and can be used with any library. But library with transparent es modules only references can be tree shaked as well. I did this in recompose library.

**Comment by Attrash-Islam** [comment]
Anything new about this issue?

**Comment by AviVahl** [comment]
`lodash` released 4.17.5, and the `lodash-es` package now contains the `"sideEffects": false` flag, which allows webpack4 to tree-shake lodash.

I've created a tiny repo showing the behavior: https://github.com/AviVahl/lodash-es-webpack4
There was no need to even use named imports.

**Comment by edmorley** [comment]
I think this issue is now resolved, so can be closed?

**Comment by malliapi** [comment]
is it ? How do we do tree-shaking with lodash-es and webpack 4?

**Comment by jdalton** [comment]
Yep, Webpack 4 supports the `"sideEffects": false` flag, which `lodash-es` uses to enables cherry-picking.

**Comment by LKay** [comment]
@jdalton Can you provide any working example? I have usual es6 imports ie. `import { get } from "lodash-es"` and webpack is not tree shaking the lodash at all resulting in including full lodash library into my bundle. I'm using Webpack 4.11 so `sideEffects` flash should be use, but it's not. Only explicit functions import ie. `import get from "lodash-es/get"` make the bundle smaller.

**Comment by AviVahl** [comment]
https://github.com/AviVahl/lodash-es-webpack4
@LKay

**Comment by LKay** [comment]
@AviVahl Thank you, but I import only specific functions from `lodash-es` (ie/ `import { isEmpty, isNil } from "lodash-es"`) not all as combined object (`import * as _ from "lodash-es"`). And tree shaking doesn't work if cherry picking is in place.

**Comment by sheepsteak** [comment]
@LKay if you're using Babel make sure it isn't transpiling the ES6 `import` into `require`. Webpack needs to see the `import` and `exports` statements to do tree-shaking. If you're using [babel-preset-env](https://github.com/babel/babel-preset-env#modules) you can turn off the transpiling like this:

```json
{
  "presets": [
    ["env", {
      "modules": false
    }]
  ]
}
```

**Comment by blikblum** [comment]
Playing with lodash-es and tree shaking, i noticed a bundle size bigger than expected.

This occurs because `/lodash-es/lodash.default.js` is being bundled in some cases even when not used (directly or indirectly).

To test try:

```js
import {filter} from 'lodash-es'

filter()
```

Will create a minified 16.5 kb bundle. lodash.default.js is bundled although is not imported by filter or its dependencies.

Webpack reports the reason as "harmony side effect evaluation"

If i import functions not used by 'lodash.default.js' to configure chaining like `head`, tree shaking works fine with a <1kb bundle.

So i would say that somehow the sideEffects flag used by lodash-es is not being considered at all
