### ISSUE TITLE
Support default rule for internal types

### ISSUE THREAD

**Issue by h-a-n-a** [webpack/webpack#17569]
## Feature request

Currently, for those who use `experiments.css` would encounter an issue for custom loader pipelines. I don't know if it is the design by webpack:

less file
```less
@import "variable.css";
```

The rule is configured as follows:

```js
{
  test: /\.less$/,
  use: ['less-loader'],
  type: 'css'
}
```

The transformation will result in a failure as `preferRelative` for this rule is not configured. This leads to an misalignment with the builtin rule for `css` files. In order to make it work, developers should configure like this:

```js
{
  test: /\.less$/,
  use: ['less-loader'],
  type: 'css',
  resolve: { preferRelative: true  }  // There might be other default rules to be applied.
}
```

To avoid the logic difference, we'd better to introduce a default rule for the internal type.

See more details here: https://github.com/web-infra-dev/rspack/issues/3913

@alexander-akait Any bias on this one?

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
@h-a-n-a Sorry for delay, still valid?

**Comment by ahabhgk** [comment]
Yes, still valid.

I think it's caused by didn't add `resolve.preferRelative = true` for `resolve.byDependency["css-import"]`

https://github.com/webpack/webpack/blob/45c39892e105ce5d486b2aa07796b3c12fc019af/lib/config/defaults.js#L713-L717

https://github.com/webpack/webpack/blob/45c39892e105ce5d486b2aa07796b3c12fc019af/lib/config/defaults.js#L1472-L1480
