### ISSUE TITLE
Generate separate CSS file for each chunk(not only initial chunk)?

### ISSUE THREAD

**Issue by PinkyJie** [webpack/webpack#1758]
Is it possible to generate separate CSS file for each chunk?
`new ExtractTextPlugin('[name].css')` can only generate CSS file for entry chunks(initial chunks), if I add parameter `{allChunks: true}`, it will output CSS in other chunks in the initial chunks also. Is there a way to exclude CSS in non-initial chunks and output them in separate file?

**Comment by PinkyJie** [comment]
I'm asking this is because if I put assets path in CSS, and this CSS is loaded by chunk, then Chrome can not resolve this path correctly.

<img width="1019" alt="7iua7" src="https://cloud.githubusercontent.com/assets/551329/11864945/7dcac750-a455-11e5-964b-0a3d4569ec4c.png">

When I right click the background URL path in the Dev tool, the full URL is `chrome-devtools://devtools/bundled/assets/images/logo.46e065707257b2930a699c7cdacd7e86.png`.

**Comment by mattkrick** [comment]
I'm interested in this, too. However, we'd also need a way to corroborate a route to a css chunk, otherwise you won't know what css chunk to ask for on a given route.

**Comment by sokra** [comment]
Possible but pretty difficult, because chunk loading need to load css too and wait for loading...

**Comment by mattkrick** [comment]
just to make sure I understand...you're saying the problem is making sure that `B.css`loads before `B.js` otherwise the user could see a FOUC?
If that's the case, I'd be cool with a big waring saying that predictive loading is required. I know it's not a hard guarantee against a FOUC but it should suffice for beta testing the new feature... of course I may have misunderstood the problem.
