### ISSUE TITLE
Google Closure Compiler Advanced Mode Issue

### ISSUE THREAD

**Issue by SanderSpies** [webpack/webpack#176]
Note: I'm a webpack newbie :-). 

Combining webpack together with google closure compiler advanced mode doesn't seem to be working due to the "exports" helper variable within the loader. Removing this helper variable got everything working on my machine.

**Comment by quirinpa** [comment]
A good compression mechanism that i can think of would be for webpack itself to store unrepeated  dependencies in vars, for example. I guess there would be a lot of problems with that, it would probably break hot dev server. Anyway i'm not sure how good would be the level of compression through closure alone because it doesn't understand dependencies like webpack. It would be awesome if something could be done in regards to the closure-webpack relationship.. I'm a bit high so excuse me if i'm being intrusive.

**Comment by nadimtuhin** [comment]
any update on the issue?
