### ISSUE TITLE
How to hide context map of dynamic require?

### ISSUE THREAD

**Issue by pawawat** [webpack/webpack#1795]
when i use dynamic require i get this map on chunk

var map = {
        "./AboutPage": 247,
        "./AboutPage.jsx": 247,
        "./DashBoardPage": 249,
        "./DashBoardPage.jsx": 249,
        "./FeedChannelPage": 251,
        "./FeedChannelPage.jsx": 251,
        "./HostPage": 253,
        "./HostPage.jsx": 253,
        "./LoginPage": 255,
        "./LoginPage.jsx": 255,
        "./ProfilePage": 257,
        "./ProfilePage.jsx": 257
}

How could I hide this map and dynamically manipulate this map in code?

please help?

**Comment by IngwiePhoenix** [comment]
By not using it.

When you use a context, you usually have something like:

    "./file/"+aVar+".js"

aVar in this case would be the basename for the file. As you see, the path is constructed dynamically. WebPack can not tell what the paths may look like, and your aVar will indeed contain the raw basename. So in order to allow you to build contexts, it needs to lay out the require calls as string.

So there is no way to hide it, unless you don’t use it, i’m afraid.

**Comment by pawawat** [comment]
My idea is I've try to write some kind of web admin with redux react. And wondering how can I restrict page access of user based on role

**Comment by IngwiePhoenix** [comment]
That is the job of your backend’s RBAC. A proper RBAC will be able to pick up a malicious attempt and cancel it out.

**Comment by pawawat** [comment]
Well, are there any way to dynamically provide context map by server instead and put it in redux store or something

**Comment by pawawat** [comment]
any suggesstion?

**Comment by bebraw** [comment]
Can you re-open at Stack Overflow for more ideas?
