### ISSUE TITLE
What's the right way to use webpack-specific functionality in node.js?

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#183]
webpack defines `require.ensure` and `require.include`, which aren't available in node.js proper. If I want to create modules that use these functions, but still run in node.js, how do I do that? They can certainly just be defined as no-ops in node.js.

**Comment by mbfisher** [comment]
What's the suggested way to do this, 9 months on?

M

**Comment by jhnns** [comment]
I guess it's still shimming like [sokra explained it](https://github.com/webpack/webpack/issues/183#issuecomment-36219163)

**Comment by sokra** [comment]
yep

**Comment by ryanflorence** [comment]
/me goes ahead and adds the shim to 16 files

**Comment by KpjComp** [comment]
+1, for a better solution than shimming every file.
or using 'enhanced-require' 

I'm currently building an App stack that can be used in Browser & Node.  

As an example: A lot of Javascript engines now implement Promises, but what I'm doing is poly-filling with Bluebird for ones that don't, and keeping the native version for speed.  Bluebird compressed is still 75k, so bundling here makes sense.

Because polyfilling node's require is not ideal, polyfilling another global say like requireEnsure would be a lot easer and only needs to be done once at app startup.  Of course this would require webpack to see requireEnsure as an alias for require.ensure ...

**Comment by snadn** [comment]
I use this
```
let proto = Object.getPrototypeOf(require);
!proto.hasOwnProperty("ensure") && Object.defineProperties(proto, {
	"ensure": {
		value: function ensure(modules, callback) {
			callback(this);
		},
		writable: false
	},
	"include": {
		value: function include() {},
		writable: false
	}
});
```

in global of node

**Comment by fresheneesz** [comment]
@KpjComp FYI Bluebird is surprisingly/embarrassingly faster than native last I checked.

**Comment by KpjComp** [comment]
@snadn:  Nice one,..  Only problem is webpack is giving a critical dependencies warning for this bit -> var proto = Object.getPrototypeOf(require);
Although everything seems to work fine.

@fresheneesz:  I did a couple of tests,
Although not a complete test, I did a simple -> 
```javascript
var k = 0;var proms = [];console.time('t1');for (var l = 0; l < 10000; l ++) proms.push(new Promise(function (resolve, reject) { k ++; resolve(); }));Promise.all(proms).then(function () { console.timeEnd('t1'); })
```
My results,..
Chrome Browser: 
   Bluebird:  377.339ms,  Native: 255.331ms
Node: 
   Bluebird:   79.960ms,   Native: 38.801ms
