### ISSUE TITLE
Generating dependencies (in `make` style)

### ISSUE THREAD

**Issue by katyo** [webpack/webpack#1835]
I would like to integrate **webpack** in embedded software project, which I build using *GNU Make*. I need the dependencies list like this:

```
client.js: src/client.coffee src/client.less
src/client.coffee: src/module1.coffee src/module2.coffee
src/client.less: src/basic.less src/theme.less
...
```

I.e. I need execute **webpack** from **Makefile** only when one or more dependencies was changed.

Is there a simple way to do it? Or does I need to implement plugin?

**Comment by IngwiePhoenix** [comment]
Can you describe more indetail what you want? Do you want to have Webpack print which files depend on what? For that to work, you have to run one build, no matter what.

Since I never worked with Make, I will do a blunt assumption:

    output: dep1 dep2

is the style of Make dependencies.

Going by that assumption, you can feed WebPack multiple entry-points. For instance if you configured it with a setting of `output:{ filename: "[name].js" }`, you can use inlined node-js to run webpack:

```
node -e "require('./make-webpack')('$makeInput', $makeOutput);"
```

`$makeInput` would be the space-separated string of your dependencies you want as entries.
`$makeOutput` would be the name of the output. in your `client.js` example, it would be `client`. i THINK if you set `filename: "[name]"` only, then you can even use `client.js` as the entrypoint name.

`make-webpack.js` could look like this (pseudo):
```javascript
var webpack = require("webpack");
var config = require("./webpack.config");
module.exports = function(deps, name) {
    config.entry = {};
    config.entry[name] = deps.split(" ");
    var compiler = webpack(config);
    compiler.run(SomeCallbackHandler);
}
```

And presto, you made a little tool that you can use underneath Make.

I only know Ninja.. so in Ninja, I would define a rule like so:

```ninja
rule webpack
  command = node -e 'require("./make-webpack")("$in", "$out")'
  description = WebPack: Making $out of: $in
```

You can also customize the script to utilize `argv` if you prefer, but this is a quick and dirty solution!

I hope this helps. :)

**Comment by katyo** [comment]
Thanks.

My own solution is a simple plugin, which looks like this (CoffeeScript):

```CoffeeScript
#
# makedeps-webpack-plugin.coffee
#

{resolve} = require "path"
{writeFile} = require "fs"

class @MakeDepsPlugin
  constructor: ({@output, @target, @depends} = {})->
  
  apply: (compiler)->
    {output, target, depends} = @
    compiler.plugin "emit", ({fileDependencies, chunks}, done)->
      output ?= "webpack-makedeps.mk"
      target ?= chunks[0]?.files?.join " "
      extraDeps = (resolve dep for dep in depends or [])
      depends = [extraDeps..., fileDependencies...].join " \\\n  "
      writeFile output, "#{target}: \\\n  #{depends}", done
```

For example, this plugin can be instantiated like that (CoffeeScript):

```CoffeeScript
{MakeDepsPlugin} = require "makedeps-webpack-plugin"

...
  plugins: [
    new MakeDepsPlugin
      output: "depends.mk"
      depends: [
        "package.json"
        "Cakefile"
      ],
      ...
  ]
```

The result is a file *depends.mk* which contains that:

```
client.js client.css: \
  /home/kayo/project/package.json \
  /home/kayo/project/Cakefile \
  /home/kayo/project/client.coffee \
  /home/kayo/project/client.less \
  /home/kayo/project/bootstrap.js \
  <...>
```

**Comment by IngwiePhoenix** [comment]
Looks good to me! :)

Anything else you would like to know?

**Comment by katyo** [comment]
No, thanks. I think, this issue can be closed.
