### ISSUE TITLE
Is chunk optimization automatically done by default?

### ISSUE THREAD

**Issue by dwiyatci** [webpack/webpack#1857]
As stated in the [chunk optimization](http://webpack.github.io/docs/code-splitting.html#chunk-optimization) docs:

> If two chunks contain the same modules, they are merged into one. This can cause chunks to have multiple parents.

Is this the same concept as [move common modules into the parent chunk](http://webpack.github.io/docs/list-of-plugins.html#3-move-common-modules-into-the-parent-chunk)? If so, this is something that we must manually config via the `CommonsChunkPlugin` and not automatic by default then?

**Comment by sokra** [comment]
Merging equal chunks is done automatically. This is a pretty safe optimization that has mostly positive impact.

Moving common modules in the parent is not done automatically. This is a unsafe optimization, because this increases the size of the parent module, which has negative impact if the user not uses at least two children chunks.

**Comment by bebraw** [comment]
@dwiyatci Safe to close?

**Comment by dwiyatci** [comment]
Yep, thanks for the clarification. Now the line:

 > This can cause chunks to have multiple parents.

have made sense for me, too.
