### ISSUE TITLE
Code built with Webpack 2.x breaks in environments without Promise

### ISSUE THREAD

**Issue by graue** [webpack/webpack#1859]
Hi, [this line in Webpack's support code](https://github.com/webpack/webpack/blob/5811c57f242658bea84819cef66ece6dce2d748e/lib/JsonpMainTemplatePlugin.js#L38) uses `Promise.resolve`, causing code built with Webpack 2.x to break in environments without `Promise`.

Only [67% of users](http://caniuse.com/#search=promise) have native support for `Promise`, and I can't add a polyfill using Webpack since this is in the module loader of Webpack itself. Can this be removed?

**Comment by IngwiePhoenix** [comment]
Or optional - that would also work.

**Comment by graue** [comment]
I worked around it by injecting a module that polyfills Promise into each of my bundles as an entrypoint. Since Promise is only used for async code loading, this works. Should probably suggest that in the documentation though...

**Comment by SimenB** [comment]
> and I can't add a polyfill using Webpack since this is in the module loader of Webpack itself

It would be great if there was an elegant way to do this. We're still on Webpack 1, but support IE8, and there's usage of e.g. `Array.prototype.concat` by dev-server before our bundle (which polyfills using core-js) is loaded. So I have to double-polyfill in dev mode (using `BannerPlugin` instead of entrypoint like OP does, but same principal).

Something like `injectModulesAtTopOfBundle: ['core-js/es5', 'core-js/es6']` in the root webpack config. Shitty name, but you get the idea :smile:

**Comment by kevinSuttle** [comment]
How does this work post Webpack 2.1.0-beta23 with the `new webpack.LoaderOptionsPlugin({{}})` API signature?

**Comment by doug-wade** [comment]
@graue Is there any more reading or resources I could look at on this?  To me, it sounds like you're suggesting that I load the promise polyfill for every user, regardless of whether their browser supports it or not, but that doesn't seem right at all.

**Comment by kevinSuttle** [comment]
@doug-wade Try this: https://qa.polyfill.io/v2/docs/features/

**Comment by graue** [comment]
@doug-wade, yes, I'm suggesting you load it for every user. That's how polyfills work. https://remysharp.com/2010/10/08/what-is-a-polyfill
