### ISSUE TITLE
Using aliases with dynamic imports in 5.94.0

### ISSUE THREAD

**Issue by xtremespb** [webpack/webpack#18726]
# Bug report

I do have the following section in *imports* area in *package.json* file:

```json
"imports": {
  "#root/*": "./*",
  "#core/*": "./src/core/*",
  "#components/*": "./src/core/components/*",
  "#build/*": "./.build/*",
  "#lib/*": "./src/core/lib/*",
  "#bin/*": "./src/bin/*",
  "#site/*": "./site/*",
  "#etc/*": "./site/etc/*",
  "#src/*": "./src/*"
}
```

Then, I'm using dynamic imports and do include those aliases there, as in example:

```js
const api = await import(`#site/../${m.path}/api/index.js`);
this.fastify.register(async () => {
    api.default(this.fastify);
});
```

When I do this, I get the following error during build process:

```
ERROR in ./src/core/lib/heretic.js 311:30-71
Module not found: Error: Invalid "imports" target "./site/.." defined for "#site/*" in the package config /Users/A2506402/Documents/GitHub/heretic/package.json, targets must start with "./"
   @ ./src/index.js 1:0-41 4:24-31
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps to reproduce:

1. git clone https://github.com/hereticjsorg/heretic.git ./
2. Change Webpack version to 5.94.0 in package.json
3. npm i && npm run install-modules && npm run configure
4. npm run build -- --dev

**What is the expected behavior?**

No errors, as it was in version 5.93.0. I.e. there should be no errors during the build process.

**Other relevant information:**
webpack version:  5.94.0
Node.js version: v22.7.0
Operating System: MacOS Sonoma 14.6.1 (23G93)
Additional tools: none

**Comment by alexander-akait** [comment]
That's expected, try to run - `node -e 'import(`#site/../test/api/index.js`);'` (instead `test` you can use any value) without webpack and you will got the same problem, you will have this problem using other bundlers too and just node.js/bun/deno, we fixed it a long time ago, but looks like you don't update your deps before. 

Shortly - you can use `..` before `#`, it means leave context, you need to specify more deep dynamic imports if you want to bundle them. But I don't fully undestand why you just don't use `webpackIgnore` magic comments, because you don't need to bundle them, they are external for you application and cooking on `npm run configure`, your just lose build performance and increase bundle size.

I don't think we can fix this because we want to be compatible with Node.js resolution logic.

Anyway feel free to feedback.
