### ISSUE TITLE
Make webpack and webpack-dev-server logging options consistent

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#1872]
To quote @Download from #476:

> @bebraw Thanks for your comment. I suspected as much. As you said the CLI does offer a solution. I found that if I add the command line option --hide-modules to the call to Webpack, it results in the right amount of logging for me.
> 
> However there is an opportunity for improvement here I think. It would be great if it would be possible to specify the logging in the webpack.config.js. It essentially is in the wrong place now, because the settings aren't actually dev-server specific (or shouldn't have to be at least) as they mostly deal with the compilation process itself..

**Comment by joefraley** [comment]
is this a matter of a --hide-modules flag for webpack core, as there is in webpack-dev-server?

**Comment by bebraw** [comment]
Good question. I guess ideally we'll want to end up with a configuration model that allows us to share the settings across webpack and webpack-dev-server.

I would rather de-emphasize the cli flags and build strong, well understood configuration pattern for logging. I guess ideally you should be able to inject a logging mechanism of your own through that instead of relying on flags implemented by webpack. That would be the most versatile option if we can specify an interface through which to achieve that.

**Comment by Download** [comment]
May I suggest my small but simple logging library, [picolog][https://download.github.io/picolog]? It supports logging levels and not much more and is less than 1kb.

It has these logging levels (from important to less important):

ERROR
WARN
INFO
LOG
DEBUG
TRACE

You could easily tie different log messages webpack currently spits out to different levels and make one single log level flag to control log verbosity. I am using it for my projects and the nice thing is that because I'm using it across multiple projects, I can control all my logging in a uniform way, through the `PICOLOG_LEVEL` environment variable. Very convenient.

**Comment by bebraw** [comment]
Yeah, having a mechanism that would allow plugging in tools like that would be ideal. As long as webpack is able to emit something that has enough data for mapping, we would have tons of flexibility.

**Comment by Download** [comment]
I was thinking more along the lines of adding just one such library (pick mine, pick mine :) and then replacing all `console.log` etc calls with `log.log` or whatever is suitable and just add a single config option to both webpack and webpack-dev-server that allows the user to override the default log level (WARN, or the environment wide PICOLOG_LEVEL).

**Comment by sokra** [comment]
This was fixed
