### ISSUE TITLE
`library.type module` and `optimization.runtimeChunk single` will nest `export` inside `__webpack_require__` callback

### ISSUE THREAD

**Issue by szqsy17** [webpack/webpack#18819]
# Bug report

**What is the current behavior?**
`library.type module` and `optimization.runtimeChunk single` will nest `export` inside `__webpack_require__` callback

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js
```
module.exports = {
  entry: {
    main: {
      import: './main.js',
      library: { type: 'module' },
    },
  },
  optimization: {
    runtimeChunk: 'single',
  },
  experiments: {
    outputModule: true,
  },
  mode: 'development',
  devtool: false,
}
```

main.js
```
console.log('main');
export const main = 'MAIN';
```

output:
![image](https://github.com/user-attachments/assets/14d12cb0-e792-4257-8e7a-a60d16ca8672)

**What is the expected behavior?**
`export` should not be inside `__webpack_require__` callback

**Other relevant information:**
webpack version:  5.95.0
Node.js version: 18.20.4
Operating System: Windows 11
Additional tools: pnpm

**Comment by alexander-akait** [comment]
Set `output.module: true`

**Comment by szqsy17** [comment]
> Set `output.module: true`

tried, not work

**Comment by absidue** [comment]
@szqsy17 Does it work correctly if you set the `mode` to `production`.

**Comment by szqsy17** [comment]
> production

@absidue It does not and the webpack throws an error.
![image](https://github.com/user-attachments/assets/e107ec17-506c-4dba-952d-d2fdbb7e79b8)

**Comment by alexander-akait** [comment]
please use `output.chunkFormat: "module"`, we should generate a better warning here

**Comment by alexander-akait** [comment]
@hardfist What does rspack do in this case?

We can:
- Generate a build error - `The `library.type` "module" doesn't support `array-push` chunk format. Select an appropriate 'target' to allow selecting one by default, or specify the 'output.chunkFormat' directly.`
- Fallback to `chunkFormat: "module"`, but it might be a little confusing because we can have multile entries
- Better `defaults.js`, we already have:
```js
F(environment, "dynamicImport", () =>
		conditionallyOptimistic(
			/** @type {boolean | undefined} */ (tp && tp.dynamicImport),
			output.module
		)
	);
```	

so we assume that when the environment is not provided (no options or browserslist) it is always `true` and so we can fallback to `true`

**Comment by alexander-akait** [comment]
@hardfist here my idea - https://github.com/webpack/webpack/pull/18822
