### ISSUE TITLE
when using `outputModule` library entry files may export additional names

### ISSUE THREAD

**Issue by turbocrime** [webpack/webpack#18951]
# Bug report

**What is the current behavior?**

The `ModuleChunkFormatPlugin` may create arbitrary file-level names when formatting an ESM chunk.

https://github.com/webpack/webpack/blob/31bd6a2d26308c63dfda8d0744139e6211a02fd2/lib/esm/ModuleChunkFormatPlugin.js#L58-L74

In all cases this has the potential to cause some name shadowing issues because the names are common words.

When a chunk is a library entrypoint and also uses a separate runtime chunk, this can cause a `SyntaxError` due to name collision.

Export statements in the user's code attempting to export the names `id`, `ids`, or `modules` will collide with the formatter's names at the file level.

**If the current behavior is a bug, please provide the steps to reproduce.**

## input files

```js
// webpack.config.js
import path from "node:path";
export default {
  experiments: { outputModule: true },
  entry: "./src/index.js",
  output: {
    library: { type: "module" },
    path: path.resolve(import.meta.dirname, "dist"),
  },
  optimization: {
    runtimeChunk: 'single', // any value other than `false`
    minimize: false, // for legibility. no effect
  },
};
```

```js
// src/index.js
export const id = "collision";
```

## output file

```js
// dist/main.mjs
export const id = 792; // this is the template's generated export of id
export const ids = [792];
export const modules = {

/***/ 173:
/***/ ((__unused_webpack___webpack_module__, __webpack_exports__, __webpack_require__) => {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   id: () => (/* binding */ id)
/* harmony export */ });
const id = "collision";

/***/ })

};
;

// load runtime
import __webpack_require__ from "./runtime.mjs";
var __webpack_exec__ = (moduleId) => (__webpack_require__(__webpack_require__.s = moduleId))
import * as __webpack_chunk_0__ from "./main.mjs";
__webpack_require__.C(__webpack_chunk_0__);
var __webpack_exports__ = __webpack_exec__(173);
var __webpack_exports__id = __webpack_exports__.id;
export { __webpack_exports__id as id }; // this duplicated export of `id` is a `SyntaxError`
```

**What is the expected behavior?**

- `ModuleChunkFormatPlugin` should not use names that are at high risk of collision
- Emitted library entry files should not export names unless requested by the developer

Additionally, it seems strange that the output file imports itself, but that doesn't seem to cause a problem.

The example given is a minimal reproduction. I encountered this while working on some complex codesplitting for a browser extension. Maybe the runtime chunk feature is not intended to be combined with the library feature, but i didn't see that suggested anywhere.

**Other relevant information:**
webpack version:  5.96.1
Node.js version: 23

**Comment by nilaygit-10721** [comment]
Could you please assign this issue to me?

**Comment by alexander-akait** [comment]
Yeah, let's fix and use `__webpack_id__` and `__webpack_ids__`

**Comment by turbocrime** [comment]
> Yeah, let's fix and use `__webpack_id__` and `__webpack_ids__`

this is simple to change but it would definitely break chunk consumption across versions

questions,

am i correct in understanding that, chunk formats are/should be capable of consuming each other? is this related to the `__esModule` name i see in some places?

presently the names may be created even when a chunk is not consumed by another chunk or a runtime. such as when a file

1. represents a 'side-effectful import' that defines no exports, and runs immediately at the top level of the file
2. is an application entry file
3. is a library entry file for use by non-webpack importers

it seems like some other chunk formats only emit things conditionally, but i don't understand all the requirements. are there any docs on this?

**Comment by alexander-akait** [comment]
> this is simple to change but it would definitely break chunk consumption across versions

yes, because es modules are all experimental and we recommend using them `[cotententhash]` (for applications), it should not be a problem to change.

> am i correct in understanding that, chunk formats are/should be capable of consuming each other? is this related to the __esModule name i see in some places?

technically yes, chunks in ESM format are able to consume each other of different builds (within one version of webpack, which is guaranteed, it will work for different versions in most cases, but we can change the runtime logic and it may break, but this happens extremely rarely), the minimizer will delete these things if they were not used, but to be honest I don't think it is used by many and I don't think we should really support this

We should add more tests for such cases...

In any case, use the prefix `__webpack_id__` and `__webpack_ids__` is worth using because technically we avoid IIFE using scope analyzer and try to concatenate modules, but it analyzes only your code and doesn't analyze runtime generated code (we assume that it will never have collisions) and if you have `id` variable in entry modules, we will have collision.

So I would say there are two problems here:
- collisions, let's fix it using `webpack` prefix, because this may happen not only for the initial chunk
- avoid generation `id` and `ids` for initial chunks

Also we have `type: "modern-module"` - https://webpack.js.org/configuration/output/#type-modern-module

**Comment by alexander-akait** [comment]
@turbocrime looks like we already fixed it https://github.com/webpack/webpack/pull/18937

**Comment by alexander-akait** [comment]
Just not released

**Comment by alexander-akait** [comment]
> Additionally, it seems strange that the output file imports itself, but that doesn't seem to cause a problem.

This is expected because this is how optimization.runtimeChunk works. We need to put modules in runtime `__webpack_modules__` and mark a chunk was loaded.

> Emitted library entry files should not export names unless requested by the developer

This is a library if you wrote top level export it will be exported.
