### ISSUE TITLE
webpack2: Module parse failed -> 'with' in strict mode

### ISSUE THREAD

**Issue by ianks** [webpack/webpack#1939]
It seems that code which compiles to a `with` statement causes module parsing to fail. in `webpack-2.0.5-beta`. Any idea why this is?

Here an example of this happening (note: you will have to upgrade webpack in the package.json):

https://github.com/auth0/lock/tree/master/examples/webpack

**Comment by sokra** [comment]
`with` is not allowed in strict mode. Check your loaders and source code if one of them is using `with` in strict mode. The error propably point to it.

**Comment by ianks** [comment]
How come this only surfaced in webpack1? I had a few loaders which caused this I happen in webpack2, which makes me think that this will be an issue with people upgrading.

**Comment by scriptjs** [comment]
You might take a look at what I wrote here:

https://github.com/bazilio91/ejs-compiled-loader/issues/13

While you may not be using the same loader, the issue is the same, you will need to pass strict=true to ejs and handle your vars from the locals object.

As @sokra has already mentioned, `with` was deprecate for es6.

**Comment by TheLarkInn** [comment]
@ianks are you still seeing issues with this in webpack 2.1.0-beta.14?
