### ISSUE TITLE
How to completely ignore a require from webpack?

### ISSUE THREAD

**Issue by blink1073** [webpack/webpack#1986]
Is there a way to tell webpack to completely ignore a specific line with a require?

I have a need for a `require(unknownName)` in my application, with pre-configured paths and aliases. The current options are to use `requirejs(unknownName)` or `System.import(unknownName)`, since these are ignored by webpack.

We would like to migrate to `System.import()` along with webpack, but in webpack 2.0, we will not be able to use `System.import()` for this.

**Comment by blink1073** [comment]
This does exactly what I'd like (in Webpack 1.0): `__non_webpack_require__(...)`

**Comment by ChiperSoft** [comment]
I'd like to know how to do this as well. I have a require that conditionally loads components based on attributes on DOM nodes. Webpack sees the require call and turns it into a pattern match, bundling every file in the components directory. I don't want to ignore that entire directory because I will require.ensure the components that will actually be on the page, I just want it to ignore that one line.

Something like a `// webpack-disable` comment, ala eslint, would be very useful.

**Comment by blink1073** [comment]
As a workaround, we are planning to use `window.System.import()`.

**Comment by anovi** [comment]
Same problem. I am using Electron to build a desktop application. I need to `require` user's plugins dynamically. For now i have only came to solution with `eval`:
```
var plugin = eval('require(pak.mainPath)'); // eslint-disable-line
```

**Comment by samiskin** [comment]
@anovi I dealt with this in my Electron app by using `module.require`

**Comment by anovi** [comment]
@samiskin I need `require` in a renderer process. For now i use this:
`var plugin = eval('require(pak.mainPath)'); // eslint-disable-line`
