### ISSUE TITLE
Semantic versioning (semver) should be used for pre-releases

### ISSUE THREAD

**Issue by licyeus** [webpack/webpack#2004]
For `2.0.0` betas, the `-beta` suffix should be incremented (e.g., `2.0.0-beta1`, `2.0.0-beta2`), *not* the patch number. This project is incorrectly incrementing the patch number (e.g., `2.0.0-beta`, `2.0.1-beta`) and breaking version pattern matching, tying users to outdated betas.

Check "express" or "koa" versioning at http://semver.npmjs.com/ and compare against this project. Because exact matching is used for pre-releases, there's no way to automatically stay on the beta upgrade path.

Keep up the great work, Webpack's a godsend. :star2:

**Comment by pyrotechnick** [comment]
This has led to awkward expressions, such as `^1.0.0 || 2.0.0-beta || 2.0.1-beta || 2.0.2-beta`, and requires frequent [updates to dependent modules' package.json files](https://github.com/babel/babel-loader/pull/216)

While this is annoying, the actual problem is that any beta for the "real" `2.0.1`-`2.0.7` versions [can't be published without an npm admin intervening](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f) which leads to more severe issues than those solved.

If they remain published, in the event "v2" is published as `2.0.0`, time-travelling `2.0.1-beta` will appear as a beta of the next patch.

There are a number of ways forward:

1. Leave the betas published and publish "v2" as `2.0.8`, or higher
2. Unpublish the betas, publish "v2" as `2.0.0` and avoid betas until `2.0.8`
3. Unpublish the betas, publish "v2" as `2.0.0` and get an admin to republish any betas of `2.0.1`-`2.0.7`

**Comment by pyrotechnick** [comment]
Resolved by 52822286a347bf525eeab7f035341fc25e857914
