### ISSUE TITLE
webpack-dev-server: command not found

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#2032]
From docs:
![webpack dev server - google chrome 2016-02-12 17 44 40](https://cloud.githubusercontent.com/assets/3880497/13003443/939edcf0-d1b0-11e5-95cf-e4617acede76.png)

When I try to run `webpack-dev-server`:
![mingw32 2016-02-12 17 45 44](https://cloud.githubusercontent.com/assets/3880497/13003461/a666fd86-d1b0-11e5-9a5f-b2a626c734b8.png)

How can I run `webpack-dev-server` from command line? I have installed `webpack-dev-server` as a dev dependency of my app:
```
npm i webpack-dev-server --save-dev
```

**Comment by sokra** [comment]
Either install it globally in addition to the local install, or use it from a npm script, or add `node_modules/.bin` to your PATH.

**Comment by bebraw** [comment]
Assuming a local install, you can do `node_modules/.bin/webpack-dev-server --content-base build/`. Given that's quite verbose, I suggest defining a **package.json** `script` for it. Then you can do something like this this:

```json
"scripts": {
  "start": "webpack-dev-server --content-base build/"
}
```

and then `npm start` or `npm run start`. npm will add `node_modules/.bin` to `PATH` temporarily while running so that shortcut will work even with a local install. This is the way I prefer to use.
