### ISSUE TITLE
loaders `test` regexp Windows vs Unix (Linux, Mac)

### ISSUE THREAD

**Issue by matiishyn** [webpack/webpack#2073]
The problem is that I cannot specify correct `test` in `loaders`, because Node's `path.sep` is `\` in Windows and `/` in Mac/Linux

I'm using [bootstrap-loader](https://github.com/shakacode/bootstrap-loader) with [imports-loader](https://github.com/webpack/imports-loader) to make sure that all JavaScript files have jQuery pre-included (which `imports-loader` actually does).

But the problem is the difference btw Windows and Unix path. Here's my loader inside `webpack.config.js`:

```js
  module: {
    loaders: [
      // this will work on Unix
      { test: /bootstrap-sass\/assets\/javascripts\//, loader: 'imports?jQuery=jquery' },

      // this will work on Windows
      { test: /bootstrap-sass\\assets\\javascripts/, loader: 'imports?jQuery=jquery' },
    ],
  },
```

I couldn't use Node's `path.sep` here. But maybe, there's another way to do it correctly. Google doesn't know much about it

Please help me to resolve it.

**Comment by sokra** [comment]
This will work in both: `{ test: /bootstrap-sass[\\\/]assets[\\\/]javascripts/, ...`

but you better pass an directory:

``` js
{ test: path.resolve(__dirname, "node_modules/boostrap-sass/assets/javascript"), ...
```

**Comment by DiegoYungh** [comment]
Just a note I had on windows, maybe it's my regex parser...

[\\\/]] will resolve to \ OR / but windows use "\\" so it must be [\\\/]+ to catch \\
And if you don't have problems with capture groups use (\\\\|\/) or ([\\]+|\/)

Just saying because I had this issue using imports-loader and it wasn't working on windows, because the regex exclude/include wasn't catching my windows paths and I tried [\\\/]

cheers
