### ISSUE TITLE
repeating `if(module.hot){...}`

### ISSUE THREAD

**Issue by yonatanmn** [webpack/webpack#2074]
Hi. 

I'm trying to build a new flux implementation. 
Iv'e figured out a way to preserve state of my Stores while using HMR with about 20 lines of code nested in `if(module.hot){...}`
Do I need to add those lines to every Store file, or is it possible to create a middleware (or something else) that will do that? 

Thanks

**Comment by jedrichards** [comment]
One approach is to write a Babel plugin that transforms your code and instruments it with the hot reloading stuff.

Take a look at https://github.com/gaearon/babel-plugin-react-transform

And then https://github.com/gaearon/react-transform-hmr

**Comment by yonatanmn** [comment]
Thanks for the reply. 
My files are not react components, but I guess general file transformation should be similar. 
It's not the place to ask for babel's transformers api (unless you happen to know) , but if I'd like to build similar "add-extra-code to some files" with webpack - how can I do that?

**Comment by jedrichards** [comment]
I'm not an expert at this but as far as I know the guys building the react-transform stuff I linked to picked Babel as the best tool for the job ... mainly because as far as I understand it the easiest way to write code transformers these days is using Babel's AST and API. They are heavy users of webpack too, so if there was a simpler way using webpack-only I guess they would have gone down that route. The approach works for any code object, whether React component or not. I don't know much else, sorry :-)

**Comment by yonatanmn** [comment]
Cool. thx
