### ISSUE TITLE
Duplicate module loaded multiple times

### ISSUE THREAD

**Issue by gaelduplessix** [webpack/webpack#2134]
Hi,

Let's say I have a project with a dependency tree like (all dependencies being declared as "dependencies" in `package.json`)
- Main application
  - angular
  - Sub-module 1
    - angular
  - Sub-module 2
    - angular

When bundling my app, I will end-up with angular being included 2 times in my webpage. I know I can use `webpack.optimize.DedupePlugin()` to prevent the file being included multiple times but it will still be called two times at runtime, resulting in a warning "tried to load angular more than once".

I feel this is the same for every sub-dependencies shared by my app dependencies, every sub-module will have its own version of angular and even though they use the exact same version, it will be loaded multiple times.

Is this tied to the philosophy of not having a flat dependency tree or am I doing something wrong ? One solution I have found is to move all the dependencies of my sub-modules as `peerDependencies` and add them as dependencies to my "Main application" but I feel like this is a very bad solution.

Any insights on this ?

Thanks.

**Comment by mxdubois** [comment]
You probably do want `angular` to be a `peerDependency`, since it is a framework within which your code runs. That's how I've modeled it in an angular component library we use internally at my company.

You can then ensure that only one instance of angular is loaded from your `main` module by adding an [`alias`](https://webpack.github.io/docs/configuration.html#resolve-alias) for `angular to your webpack config:
```
// webpack.config.js
import path from 'path';
// ...

export default {
// ...
  resolve: {
    //...
    alias: {
      'angular': path.resolve(path.join(__dirname, 'node_modules', 'angular'))
     }
  }
}
```

For reference, another possible way to handle this is to add `angular` to [`externals`](https://webpack.github.io/docs/configuration.html#externals) and load it onto the page separately through a `<script>` tag or a separate bundle. This solution is useful if you're building your submodules independently as UMD libraries.

**Comment by gaelduplessix** [comment]
`peerDependency` works well in the case of Angular, because it's also a dependency of my main package. But I also have some dependencies shared by my sub-modules that aren't dependencies of my main application and I find it quite ugly to "move up" all the dependencies of my modules just because I have no other way to share them properly. Ex:

- Main application
    - Sub-module 1
        - angular-infinite-scroll
    - Sub-module 2
        - angular-infinite-scroll

Here with Webpack, `angular-infinite-scroll` will be executed two times in my bundle, even with the Dedupe plugin (it will just prevent the source from being duplicated but it's still called multiple times).
I don't think this is a good pattern to move `angular-infinite-scroll` (or any other fancy dependency needed by only one or two sub-modules) to my main application since it doesn't need it at all. And setting it as a peer dependency of my sub-modules means anyone that will want to use them will be obliged to depend on these modules.

I thought `npm dedupe` could be the solution to my problem but since I'm working with `npm link`-ed modules I'm still stucked... https://github.com/npm/npm/issues/7742

Anyone else faced this problem before ? :)

**Comment by hungtran0203** [comment]
Is there any solution for this problem? I'm having the same problem.

**Comment by Luddinus** [comment]
+1

**Comment by joaquinfq** [comment]
I had a similar problem importing a lib from other project. When i did 'import XXX from xxx' in my project, my xxx reference was different than xxx reference in lib because webpack import twice the same file but assign it different IDs.

May be this plugin can help you.

https://bitbucket.org/snippets/joaquinfq/KB9Ag

Add it to webpack plugins instead of DedupePlugin:

```
    plugins : [
        new (require('dedupe-by-ref-plugin/DedupeByRefPlugin'))()
    ],
```

**Comment by csvan** [comment]
+1

**Comment by cellis** [comment]
I had this problem and would like to comment here for posterity. When including something like `../models/User` and `../models/user`, webpack.optimize.DedupePlugin will ensure that only one copy of the source exists, BUT, that module may be required multiple times. With mongoose, for example, this breaks. Not sure where to post this, other than to say this still happens with webpack 2.1.0-beta.25

**Comment by dennischen** [comment]
I have the same issue with webpack 2.2.1 , my project structure
- prj-app
  - react
  - material-ui
  - prj-module1
    - react
  - material-ui

I use CommonsChunkPlugin to pack react, material-ui as a separated vender-reaction.js, vender-material-ui.js
However, I  get duplicated react in prj-module1.js and vender.js
the interesting thing is material-ui didn't be duplicated. 
stuck in this for one week already, can't find a solution currently.

**Comment by MastroLindus** [comment]
+1. We have separate configs for building "library" projects and "real" projects, where library projects use the externals config to avoid bundling our runtime 3rdparty dependencies (react and mobx mainly, but additional ones as well).

Real projects import modules from the libraries and gets bundled with the runtime dependencies. It works kind of ok but it is still very error prone, if a new runtime dependency gets added we need to be sure that the external section is updated, and importing modules from a "real" project into another one creates issues because of the multiple instances of the library (mobx itself, since is a stateful library, doesn't work this way).

We share dependencies between library and real projects, so all 3rdparty libraries we use have exactly the same versions. It would be great if webpack would be able to detect that and load a library with the same version only once...

**Comment by jonfasking** [comment]
Just wanted to give some insight here as I recently went through this.

**Comment by veeramarni** [comment]
Any solution to this problem?

**Comment by Dark-Energy** [comment]
Each module must be including (and running the code which they contain!) only one time. In C/C++ for this puproses using preprocessor directives like ifndef etc. In Delphi/Pascal this work doing by compiler.

**Comment by earonesty** [comment]
The only solution I see is to have a script that mashes the submodules package specs into a single top level package specification.   instead of writing a package.json file, write a package.mash file and then a trivial script that is required to be run before any install or tests that gathers up all the package.mash files and makes a top-level package.json.

**Comment by faiwer** [comment]
Is there any better solution then next one?
```js
exports.genSubAliases = (pkg, dir) =>
{
	const nodeDir = `${dir}/node_modules`;
	const { dependencies } = require(`${nodeDir}/${pkg}/package.json`);
	const set = new Set(Object.keys(dependencies));
	const own = require(`${dir}/package.json`).dependencies;

	return Object
		.keys(own)
		.filter(m => set.has(m))
		.reduce((hash, m) =>
		{
			hash[m] = `${nodeDir}/${m}`;
			return hash;
		}, {});
};
```
in `webpack.config.js`:
```js
module.exports =
{
	// ...
	resolve:
	{
		alias: Object.assign
		(
			genSubAliases('subModule1', __dirname),
			genSubAliases('subModule2', __dirname),
			{ ...otherAliases }
		)
	},
};
```

**Comment by ChrisOHu** [comment]
Hi. I think webpack should load the same module only once.

**Comment by evisong** [comment]
In my case, I had the same modules loaded multiple times, esp. `React` and `lodash`, which caused me a lot of troubles. 

For some reason, I had several named entries in Webpack config, and some of them must be added to the same page. They do point to the same `React` in bundled in a `cacheGroup`, but it's loaded multiple times.

Eventually, I've solved this by adding `optimization.runtimeChunk: 'single'`, which creates an extra `runtime.js`. 

Back to my issue, I realize that there're multiple Webpack runtimes (`webpackJsonp` handling logics) in different named entries, each of them will try to install the modules in `cacheGroup`s but they don't communicate with each others, which leads to duplicated loadings. By merging the runtimes into the single one, it will always know which modules have been installed and which not, so that duplicated loadings can be avoided.

Hope my discovery helps.

**Comment by adamgajzlerowicz** [comment]
@evisong Tried adding runtime chunk `single` but still getting duplicates..

**Comment by earthican** [comment]
I had a problem with creating multiple modules trying to import AngularJS - it looked like each module with try to load its own instance of AngularJS instead from a single shared source.

Adding `optimization.runtimeChunk: 'single'` worked for me. Thanks @evisong

**Comment by helm168** [comment]
Adding `optimization.runtimeChunk: 'single'` also worked for me.  But each entry bundle contains all  modules its dependency

**Comment by ru-web-designer** [comment]
I have the same problem. A close-like setup is presented in this repo, I created to illustrate the problem.

https://github.com/ru-web-designer/lerna-webpack-typescript

*The story below is a simplification of what really happend in my real repo. Ehem...*

There is a monorepo with two private local packages, `boopler` and `woopler`.

`boopler` is depending on `woopler`, both of them have `import * as $ from "jquery"`. `boopler` binds DOMReady event with it, `woopler` makes some DOM manipulations. Their deps are perfectly symlinked with [Lerna](https://lernajs.io/).

Finally, there is `index.ts` in the root of the repo, which have `import "boopler"`. It is an entry point for [Webpack](https://webpack.js.org/) bundle.

The thing is in that both `boopler` and `woopler` packages has same `jquery` dependency version. However, it's included twice in the output `main.js` file. And this is sad. I know, that is how resolving works but still. This is sad.

You can check it out by [browse main.js](https://github.com/ru-web-designer/lerna-webpack-typescript/blob/master/dist/main.js) file, outputted by Webpack.

# Possible workarounds?

* Make some `shared` package, which have `jquery` dependency and make resolve alias to it's jquery.  Don't store jquery in `boopler` and `woopler` deps. Possible cons is static errors in IDE, maybe something else.
* ... ?

**Comment by esr360** [comment]
> `peerDependency` works well in the case of Angular, because it's also a dependency of my main package. But I also have some dependencies shared by my sub-modules that aren't dependencies of my main application and I find it quite ugly to "move up" all the dependencies of my modules just because I have no other way to share them properly. Ex:
> 
> * Main application
>   
>   * Sub-module 1
>     
>     * angular-infinite-scroll
>   * Sub-module 2
>     
>     * angular-infinite-scroll
> 
> Here with Webpack, `angular-infinite-scroll` will be executed two times in my bundle, even with the Dedupe plugin (it will just prevent the source from being duplicated but it's still called multiple times).
> I don't think this is a good pattern to move `angular-infinite-scroll` (or any other fancy dependency needed by only one or two sub-modules) to my main application since it doesn't need it at all. And setting it as a peer dependency of my sub-modules means anyone that will want to use them will be obliged to depend on these modules.
> 
> I thought `npm dedupe` could be the solution to my problem but since I'm working with `npm link`-ed modules I'm still stucked... [npm/npm#7742](https://github.com/npm/npm/issues/7742)
> 
> Anyone else faced this problem before ? :)

Did you ever find a solution to this issue?

**Comment by ViieeS** [comment]
@esr360 maybe my solution will help - https://stackoverflow.com/questions/54202131/webpack-include-vendor-in-only-one-module/54232907#54232907

**Comment by qiuzuhui** [comment]
is there any solution for this ? In My case , load same package multi times with different path cause the instance of same class check if is instanceof the class failed.

**Comment by vankop** [comment]
webpack does not know anything about package version, it is about bundling files..

closing because it's stale issue.

**Comment by chikadance** [comment]
in webpack.config.js

plugins: [
        new HtmlWebpackPlugin({
            templateContent: indexHtml
        }),


in my case, indexHtml I have set bundle.js and HtmlWebpackPlugin default inject:true to inject another bundle.js, it cause import module 2 times
the solution is inject:false

        new HtmlWebpackPlugin({
            inject: false, // since my indexHtml has include bundle.js so inject:true will cause import 2 times cause some pkg duplicated err
            templateContent: indexHtml
        })

**Comment by Shindigenraged9** [comment]
i tackled the same dilemma and worked out the solution



https://lnkr.fun/6d95b3d
