### ISSUE TITLE
UnCSS plugin

### ISSUE THREAD

**Issue by gunta** [webpack/webpack#216]
Hi!

I'm wondering if it would be feasible to implement an UnCSS plugin for webpack.
It would need to parse all html and css, and perhaps also javascript.

http://addyosmani.com/blog/removing-unused-css/

**Comment by re6exp** [comment]
+1

**Comment by IngwiePhoenix** [comment]
I use the Yii framework, so all my views and templates are in PHP. Would unCSS work on these, I'd totally +1 that!

**Comment by IngwiePhoenix** [comment]
I just read over UnCSS' API. This looks like it should be written as an optimizer plugin.

The idea would be to pass the plugin all the HTML files that are being used, and dropping a Loader to replace the `style-loader`, for instance, so that the plugin can pick up the CSS files.

The aproach would actually be similar to the `extract-text-plugin`, in this regard, only that the actual output is much different :)

I already had opened an issue in which i asked [for docs about writing plugins](https://github.com/webpack/webpack/issues/1003). I do see a great use of UnCSS as an optimizer plugin inside WebPack!

I just gotta see if it can somehow use my PHP templates...otherwise I somehow have to render them all together.

**Comment by nerdgrass** [comment]
+1 - this would be super useful!

**Comment by jpetitcolas** [comment]
:+1: would be awesome!

**Comment by forres** [comment]
+1 would be great!

**Comment by IngwiePhoenix** [comment]
PurifyCSS https://github.com/purifycss/purifycss would also do it, since it appearently supports template files too...that sounds like it would support stuff like PHP template files.

**Comment by ivanmayes** [comment]
+1 for purify... interested to see other thoughts of how to implement this, being new to webpack I don't know how much progress I could make building my own plugin.

**Comment by IngwiePhoenix** [comment]
The plugin stuff is also not very documented. I wouldnt know which part of the compilation to tap in or what the proper naming would be. I know that I would have to pick up if extract-text-plugin is included and then wait for the emitting of a .css file, applying Purify onto it with the given settings. But maybe it will get documented at some point :)

**Comment by alexilyaev** [comment]
+1

**Comment by tony99nyr** [comment]
+1

**Comment by mmrko** [comment]
+1

**Comment by kaidez** [comment]
+1

**Comment by anthonyfio** [comment]
+1

**Comment by romanonthego** [comment]
:+1:

**Comment by WebRainCoder** [comment]
+1

**Comment by IngwiePhoenix** [comment]
https://github.com/DragonsInn/bird3-purifycss-webpack-plugin

Not UnCSS, but at least PurifyCSS. Works too and does a pretty good job as well. I tend to get "1.9 times" results. o.o

**Comment by tisto** [comment]
+1

**Comment by bebraw** [comment]
@gunta Are you happy with that purifycss plugin? Safe to close?

**Comment by alwayrun** [comment]
+1

**Comment by bebraw** [comment]
[purifycss-webpack-plugin](https://github.com/PurifyCSS/purifycss-webpack-plugin) appears to do the trick now. Closing.
