### ISSUE TITLE
Loader of Loader of Loader

### ISSUE THREAD

**Issue by prasannavl** [webpack/webpack#2193]
Is there any way to chain loader for a loader?

**Use case**: I'm slowly migrating all my javascript code to typescript, whenever possible. Currently, the custom loaders end up having to either be in separate libraries, or be at the lowest language level supported in nodejs.

If a loader can be applied to a loader, then, language support comes at ease, as typescript/babel can be used. I'm not sure if its possible to already do this, combining with pre-loaders. But the documentation for pre and post loaders barely exist. Are they just semantic differentiation for loader contexts, or do they facilitate these?

Thanks.

**Comment by cspotcode** [comment]
I don't think a loader can be used to transform the source code of another loader.  Loaders are intended to transform the output of other loaders.

If you want to write your loaders in TypeScript, I recommend using [ts-node](https://www.npmjs.com/package/ts-node)'s require hook.

```
// webpack.config.js
require('ts-node/register');
// Now you or webpack can require() TypeScript files
module.exports = { // ...
```

I think you'll still need to configure `[resolveLoader](https://webpack.github.io/docs/configuration.html#resolveloader).[extensions](https://webpack.github.io/docs/configuration.html#resolve-extensions)` so that webpack looks for `.ts` files when locating your loaders.
