### ISSUE TITLE
How to resolve file path from a webpack:/// URI

### ISSUE THREAD

**Issue by felicienfrancois** [webpack/webpack#2395]
I develop a software that parses soucemaps and load source files.

How should I load source files whoose path is starting with `webpack:///`?

**Comment by MatthiasWinkelmann** [comment]
Not sure what you mean by 'load', i. e. where do you want to load these? But http://webpack.github.io/docs/configuration.html#output-devtoolmodulefilenametemplate could possibly useful.

**Comment by felicienfrancois** [comment]
I would like to resolve the source files path on file system.
I'm developing a code editor with a preview window. When the resources have sourcemaps specified, the source files are directly opened for editing.
I have some users that used webpack as an external tool and I would like to be able to map `webpack:///` URIs with local files.

According to the documentation, the webpack URI are of the form `webpack:///[resource-path]?[loaders|hash]` but I see that resource-path is a relative path and may contains `~` characters for modules.
Then, I would like to known how to resolve this `[resource-path]` against the file system programmatically (I use nodejs).
- Is the [resource-path] relative to the project root dir ? to the resources directory ? to the bundlefile path ? to webpack root ? to user home dir ? ...
- Is the path encoded (url encoded or unix style or whatever) ?
- How to resolve tildes (should it be replaced by `node_modules` ? if it can be several directories, how can I guess the real one?
- If there is a loader or hash parameter, should I ignore it ? Does it have an impact on file path resolving ?

**Comment by MatthiasWinkelmann** [comment]
Well, take a look at the link. You can pass a function to filenameTemplate that gets passed an object that contains, amongst other things, the absolute path in the file system. It shouldn't be encoded but if you just try it you'll see the format.

**Comment by felicienfrancois** [comment]
@MatthiasWinkelmann thank you for your answer.
But I'm not looking for tweaking this path. I'm not using webpack myself.
I would like to support webpack in my software, out of the box, without my users having to setup webpack in a custom way to make it works.
So my questions remains valid about the __default__ `devtoolModuleFilenameTemplate`.

Also I'm wondering if there is a reason and/or an utility to have such a default URI instead of the regular path to source file.
Also, the `webpack://` scheme does not seems to be registered in OS when I install webpack. I would expect this scheme to be handled and webpack serve the source files. If not, why using a custom scheme?

Don't see any criticism in my questions, I'm just trying to understand how webpack works to know how I can support webpack in my app.

**Comment by sokra** [comment]
The Source of the `webpack://...` path is inside the SourceMap.

A SourceMap can include a `sourcesContent` property which contains the text content of the sources.

So the URLs in the SourceMap are artifical and are not available on the file system. You should thread them as opaque identifiers. Therefore they have a `webpack://` prefix instead of a `file://` prefix. In most cases source on file system differ from source in SourceMap, because webpack and loaders transform the file.

**Comment by felicienfrancois** [comment]
@sokra thank you for your quick answer.

I was aware of the `sourcesContent` property, but unfortunatelly it does not match my needs. I want to open source files for editing, so i need to locate them on the file system when they are available.
I think sourcemap purpose is not only to provide the source content but also to _map to sources_.
Several tools  are using sourcemaps to resolve the path of source files on local file system (like mine or Chrome devtools sync plugin for example).

Then if the source files are transformed several times, the sourcemap should point to the original files when possible, not to the intermediate ones. I known that not all transformation libraries support sourcemap chaining, but some does.
The solution may be to link to original source files when they exist and can be chain-mapped and to use an identifiable fake path only for intermediate temporary files.

Regarding my need, I will probably add support for webpack URIs by extracting the `[resource-path]` and testing if the file exists in the file system, relatively to the project root.
I'm still wondering if I will try to resolve modules path (`~`) and how i may do that.

**Comment by sokra** [comment]
If you use `[resource-path]` or `[absolute-resource-path]` the paths will be raw paths on fs.

---

Regarding `~`: webpack replaces `node_modules` with `~` for readablity.

**Comment by mattflix** [comment]
"~" may be more "readable", but it breaks all kinds of tools (little-known ones, such as Chrome DevTools) that rely on finding paths related to the file system in the source map.

The paths in a source map should point at *the source* files.  It is sort of the point.

**Comment by jhnns** [comment]
Maybe we need support from source map savvy people – or one from the chrome developer tools team. I feel like the current default behavior does not play well with other tools.

1. Using a custom `webpack://` protocol scheme is basically a hack since all resources do not appear under the original origin anymore (like `localhost:8080`).
2. Replacing `node_modules` with `~` is not appropriate since it breaks tools that try to resolve the file on disk (like Chrome's [Workspace feature](https://developers.google.com/web/tools/setup/setup-workflow)) 
3. It's also surprising that the Webpack footer is still visible inside the source files. Personally, I would remove the Webpack footer completely, as it provides no further value if you're using any of the `devtools`. It can also be a problem if you want to edit the source file inside the developer tools because they write the footer back to the file if you save it:

![bildschirmfoto 2017-03-30 um 15 38 43](https://cloud.githubusercontent.com/assets/781746/24507309/66c5a156-1560-11e7-929c-d4c3084122f3.jpg)

I think, the problem here is that we haven't fully understand all requirements and edge-cases. For instance, usually you want to debug in your source files. There shouldn't be any extra comments (like the webpack footer). The files panel should reflect your workspace as close as possible.

Then, there are files that are generated on the fly and do not exist on the file system. While these files can also be helpful to debug, you can't map them to the workspace. I would also argue that *most* of the time, you don't want to debug these files (maybe as loader authors). I think, these files should be somewhere else. Maybe, it's appropriate to put them under the `webpack://` origin along with the compilation hash, like `webpack://[hash]/`. We could also represent chunks as folders there.

**Comment by jhnns** [comment]
Here's an example issue where people are struggling with this: https://github.com/angular/angular-cli/issues/2453

**Comment by MagicDuck** [comment]
I think there's one additional issue here that I haven't seen anybody talk about, which is sourcemap path collision.
This happens when you have multiple webpack builds that integrate at runtime. For instance, I have a couple of projects that are built as webpack libraries (libraryTarget: "jsonp"). I use those libraries in a 3rd project. When I try to debug, I can see the sourcemaps for the libraries code in the devtool, but if you happen to have a file with the the same path in both libraries, for example:
`"webpack:///src/index.js"`
Then you basically just see the one for last loaded library...
We should have a way namespace those paths. Would be nice if you could change only the webpack:/// prefix independent on the devtool being used. Then we could switch it to something like: `webpack (<library name>):///`
