### ISSUE TITLE
require with expression not passed to externals function

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack#2413]
I use webpack for Node projects and want to `require` JSON files with Nodes native `require`. 

This works:

```
  // in order to ignore built-in modules like path, fs, etc.
  target: 'node',
  externals: [
    // require json files with nodes built-in require logic
    function(context, request, callback) {
      if (/\.json$/.test(request)) {
        callback(null, 'commonjs ' + request);
      } else {
        callback();
      }
    },
    // in order to ignore all modules in node_modules folder
    WebpackNodeExternals()
  ],
```

```
require('./package.json');
```

But this doesn't work:

```
require(path.join(process.cwd(), 'package.json'));
```

It seems it isn't passed to `function(context, request, callback)`. I only get this:

```
WARNING in ./src/index.ts
Critical dependencies:
44:27-86 the request of a dependency is an expression
 @ ./src/index.ts 44:27-86
```

**Comment by donaldpipowitch** [comment]
Ugly hack to get this working:

````
// ./src/index.ts
const unvalidatedProject = require('__PROCESS_CWD_PACKAGE__');
````
````
// ./webpack.config.js
// ...
  externals: [
    function(context, request, callback) {
      if (request === '__PROCESS_CWD_PACKAGE__') {
        callback(null, `require(process.cwd() + '/package.json')`);
      } else {
        callback();
      }
    },
    // ...
  ]
// ...
````
````
// ./dist/index.js
// ...
module.exports = require(process.cwd() + '/package.json');
// ...
````

**Comment by donaldpipowitch** [comment]
If `package.json` is malformed it seems no exception is thrown :( I'd expect `SyntaxError: ./package.json: Unexpected string`.

**Comment by rob3c** [comment]
If you're in node and just trying to load some json files into js objects at runtime without bundling them in advance, it may be easier to create a utility function that uses `JSON.parse` with `fs.readFileSync`, rather than fighting webpack just to do that via node's `require`. I do that in combination with the [strip-json-comments](https://www.npmjs.com/package/strip-json-comments) module, like this:

```
// jsonObjectLoader.js
var fs = require('fs');
var stripJsonComments = require('strip-json-comments');

module.exports = (filename: string) {
    var jsonWithComments = fs.readFileSync(filename, 'utf8');
    var json = stripJsonComments(jsonWithComments);
    return JSON.parse(json);
}
```

That's one solution compatible with webpack and node when you don't know the file path(s) of interest at bundling time.

However, if you know the file's relative location at bundling time and/or want to let webpack decouple its designtime location from its runtime location, but you don't want to inline it for whatever reason (e.g. it's too large, you want it changeable at runtime, etc.), then you can use the `file-loader` webpack plugin to give you its runtime path. Then you use the path given to you to load it using the above method.

Here's an example of letting webpack preserve json files as files in a `/resources` folder instead of inlining them:

```
// config json files to use the file loader in webpack.config.js
module: {
    loaders: [ { test: /\'json$/, loader: 'file?name=resources/[name].[ext]' } ]
}
```
Then in your code you can `require` a json file using its path relative to where you're requiring it from, and webpack will really give you its runtime path in the `/resources` folder, like this:

```
// app.js
var jsonObjectLoader = require('./jsonObjectLoader');
var fooJsonRuntimePath = require('./foo.json'); // returns '/resources/foo.json'
var foo = myJsonUtils.parseFromFile(fooJsonRuntimePath); // object from json after stripping comments
...
```

By letting webpack decouple the runtime location from the designtime location, I've eliminated most headaches associated with `__dirname` and `process.cwd()` type path calculations at runtime, especially when sharing code and resources across different projects for different use-cases (web, cordova, node, etc.);

**Comment by donaldpipowitch** [comment]
You're right `JSON.parse` and `fs.readFileSync` would work and maybe this is the better solution than my hack for the time being. I'm writing a command line tool which `require`s the current `package.json`, so it depends on `process.cwd()` and the file path is not known at bundling time.

While your solution and my solution work, I'd rather tell webpack to opt-in for Nodes `require` as a fallback, if I set `target: 'node'` in such cases. Yes, I don't want to fight webpack, but I also don't want webpack fight with me :D It shouldn't be that hard to opt-out from webpacks `require` in certain cases.

**Comment by rob3c** [comment]
I hear you. FWIW node's `require` just uses `JSON.parse` internally, anyway. I've found an advantage to handling JSON parsing myself (besides reducing magic by being more explicit) is I can do things like support json comments in config files. That's not necessarily relevant for the package.json files you're interested in for this particular application since npm chokes on them, but it may be handy in other custom config files.

**Comment by valleykid** [comment]
I also have a use case for this. I think it can be solved like this:

```
// ./src/require.js
module.exports = require;
```

```
// ./src/app.js
import requirex from './require';
...
requirex(path.join(process.cwd(), 'package.json'));
```

```
// webpack.config.js
{
     ...
     module: {
          noParse: /require.js$/,
          ...
     }
}
```

This way worked for me, suggest you have a try. Good luck~
