### ISSUE TITLE
passing multiple files for a single entry point from CLI

### ISSUE THREAD

**Issue by georgir** [webpack/webpack#2559]
Currently there seems to be no way to pass multiple files for `--entry` arg.
The way to pass structured data that is built-in in optimist with dot notation causes an error in ifArgPair's use of indexOf:
`webpack --entry.z ./a.js --entry.z ./b.js --output-filename z`

But since you do not use the built-in support for dot notation for other options (i.e. `--output-filename` instead of `--output.filename`) perhaps this should be implemented in a custom way too, to be consistent?

`webpack --entry-z ./a.js --entry-z ./b.js --output-filename z` ?

`webpack --entry z=./a.js --entry z=./b.js --output-filename z` ? 
(currently the last one overwrites the first)

`webpack --entry z=./a.js:./b.js --output-filename z` ? 
(using local system specific `path.delimiter`? or allow both `;` and `:` regardless of os? or allow even more natural options, like `,` or space, but that might lead to inability to reference files that contain those)

**Comment by sokra** [comment]
yargs supports dot notation and array parameters. We should support this in our CLI.

**Comment by rrharvey** [comment]
PR #4305 allows for the originally requested feature of multiple files in an entry. I also played with array parameters and dot notation as suggested by sokra. 

Array parameters would introduce a breaking change. 

Right now:
```cmd
webpack --entry ./a.js ./b.js
```

results in:
```
a.js -> null.js
b.js -> main.js
```

if --entry was an array parameter we would get:
```
a.js, b.js -> null.js
```

I didn't add dot notation support because named entry points were already supported. It could be added if you really think it's valuable.

```cmd
webpack --entry foo=./a.js
```

would be equivalent to

```cmd
webpack --entry.foo = ./a.js
```
