### ISSUE TITLE
Updating from 2.1.0 beta 8 to beta 9: app no longer executes

### ISSUE THREAD

**Issue by sethkinast** [webpack/webpack#2603]
My app's Javascript stopped executing when I updated from beta 8 to 9. I stripped the app down to reproduce the problem.

My entry points are:
```
  entry: {
    app: [
      './src/client/index'
    ],
    vendor: [
  << some vendor libs like React >>
    ]
  },
```

In `src/client/index`, I simply have:

    console.log("Hello world");

Both beta 8 and beta 9 compile identical `app.js` files that start with
```
webpackJsonp([1],{

/***/ 129:
/***/ function(module, exports) {

        console.log('hello world');
```

However, if I put a breakpoint in the sourcemapped file at the `console.log()` (or a debugger statement), with beta 9 the breakpoint is never hit and the app never logs "Hello world".

Please let me know what other info I can provide. I have used this app with betas 5-8 without issue. No errors appear in the console; it's as if the entry point is just never executed.

**Comment by gihrig** [comment]
Similar experience at mxstbr/react-biolerplate [issue 468](https://github.com/mxstbr/react-boilerplate/issues/468)

**Comment by Kovensky** [comment]
Cause seems to be commit fd5b896 when CommonsChunkPlugin is used. When the Jsonp helper is called, it tries to execute moduleId `0` instead of what is actually supposed to be executed.

This debugger screenshot should help explain the problem:

![](http://puu.sh/phudQ/2a9c4ac02c.png)

The `for in` is iterating over the indexes of the array instead of the values, but the indexes are being used as if they're the values.

**Comment by sethkinast** [comment]
My app does use CommonsChunkPlugin.

**Comment by sokra** [comment]
ups... sorry.
