### ISSUE TITLE
Incremental builds with many imported image assets

### ISSUE THREAD

**Issue by clessg** [webpack/webpack#2611]
Is there any way to prevent the slowdown that occurs when many image assets are imported? For example, `require('./assets/icons/' + icon + '.gif')`. Assuming the icons folder has 10000 images, incremental builds will become many times slower. (Ideally the solution would not require using a spritesheet or something. In my case, the images are animated gifs.)

Apologies for asking here. I tried on StackOverflow and Gitter and had no luck.

**Comment by bebraw** [comment]
The problem is that the `require` compiles actually to a [require.context](https://webpack.github.io/docs/context.html), hence the behavior. If that icon name isn't entirely arbitrary, you could try defining a `require.context` yourself and restrict its lookup rule so it won't match all 10000 images.

If it's arbitrary, then it's definitely problematic and I don't have a clear solution for that.
