### ISSUE TITLE
webpack dev server doesnot work when set filename with hash 

### ISSUE THREAD

**Issue by huangyingjie** [webpack/webpack#2662]
I'm submitting a...
=====
- [x] bug report

**Webpack version:**
1.2.19

**Please tell us about your environment:**
OSX 10.x 

**Current behavior:**
````js
  output: {
    filename: '[name].[hash].js',
    publicPath: 'http://127.0.0.1:3001/web/public/dist/'
  },
````
The hot load is normal. But when I reload the page manaully, all the changes disappear, and I have to restart webpack dev server, then the changes recover.
If I remove the `.[hash]` of filename, all the things go well.
**Expected/desired behavior:**

* **What is the expected behavior?**
When I set filename with hash, all the changes of the UI remain, without restart webpack dev server.

* **What is the motivation / use case for changing the behavior?**
keep the consistency between production and development.
 
* **Browser:**  
 all Chrome
* **Language:** 
es6/7

**Comment by SpaceK33z** [comment]
You should never use any `[hash]` thingy with dev-server. Aside from this issue, it also results in a memory leak because it will see each output file as a new file every time, so the in-memory files will get bigger and bigger.

In https://github.com/webpack/webpack.js.org/issues/26 I added a note that this should be documented.
