### ISSUE TITLE
webpack 2 not resolve mainFields array

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#2708]
**I'm submitting a bug report**
**I'm submitting a feature request**

**Webpack version:**
2.1.0-beta.14

**Please tell us about your environment:**
 Linux 

``` js

  resolve: {
        descriptionFiles: ["bower.json"],
        mainFields: ["main"],
        extensions: [".js"],
        modules: [
            "bower_components",
            path.resolve('.')
        ]
    }
```

bower.json

``` js
{
  "name": "vendor-jquery-ui.custom",
  "main": [
    "jquery-ui.custom.js",
    "css" //it is folder
  ]
}
```

**Current behavior:**
Module not found error

**Expected/desired behavior:**
Resolve by extension

**Comment by swernerx** [comment]
It seems like this is fixed with beta-20...

**Comment by akomm** [comment]
I have this config:
```js
    entry: {
      'polyfills':   './src/polyfills.browser.ts',
      'vendor':    './src/vendor.browser.ts',
      'createjs':  './src/vendor.createjs.ts',
      'main':      './src/main.browser.ts'
    },
    resolve: {
      extensions: ['', '.ts', '.js', '.json'],
      descriptionFiles: ["package.json", "bower.json"],
      modules: [helpers.root('src'), 'node_modules', 'bower_components']
    },
```

And this imports in `src/vendor.createjs.ts`:
```ts
import 'EaselJS';
import 'PreloadJS';
```

bower_components/EaselJS/bower.json:
```json
{
  "main": "lib/easeljs-0.8.2.combined.js"
}
```

bower_components/PreloadJS/bower.json:
```json
{
  "main": "lib/preloadjs-0.6.2.combined.js"
}
```

Result:
```
ERROR in ./src/vendor.createjs.ts
Module not found: Error: Can't resolve 'EaselJS' in 'src'
 @ ./src/vendor.createjs.ts 4:0-18

ERROR in ./src/vendor.createjs.ts
Module not found: Error: Can't resolve 'PreloadJS' in 'src'
 @ ./src/vendor.createjs.ts 5:0-20
```

This works `src/vendor.createjs.ts`:
```ts
import 'EaselJS/lib/easeljs-0.8.2.combined.js';
import 'PreloadJS/lib/preloadjs-0.6.2.combined.js';
```

Looks like the `modules` entry `bower_components` is used. But the `descriptionFiles` option is not used for some reason. Although it seem to be used for package.json, because when I override the the default and only add bower.json I get errors resolved npm packages, so it is partially used, but not for stuff other than package.json.

**Comment by TheLarkInn** [comment]
@arshtepe could you update to webpack@2.1.0-beta.22 and confirm whether or not this is still an issue?

**Comment by arshtepe** [comment]
@TheLarkInn I have same error in webpack 2.1.0-beta.25

**Comment by joevp** [comment]
beta.25 appears to throw an error when passing an empty string to `resolve.extensions`

**Comment by caisah** [comment]
@joevp I don't think you have to pass an empty string anymore. See this in [the new config example](https://github.com/angular/angular-cli/pull/2237/files#diff-14f7a27a1538756144b408294189f425L33).

**Comment by faller** [comment]
I have same error in webpack 2.1.0-beta.25

**Comment by ambischof** [comment]
Seems to still be an issue in 2.2.0.

It's even more confusing because it seems to ignore the mainField if it is an array.

In the libraries where 'main' field is an array, the error only shows it trying to find it in the `browser` attribute. The error shows `Field 'browser' doesn't contain a valid alias configuration` Well yeah, there is no `browser` in the descriptor file. 
I can only get it to stop looking in `browser` by changing alias field to an empty array where it gives me a generic not found error.

**Comment by codewizz** [comment]
I can confirm this is still an issue. This can be easly seen while using **jquery.scrollTo** plugin:

```
bower install jquery.scrollTo
```

webpack resolve config looks like:

```js
resolve: {
    modules: ['bower_components', 'node_modules'],
    descriptionFiles: ['bower.json', 'package.json'],
    mainFields: ['main', 'browser'],
    mainFiles: ['index'],
}
```

bower.json for an observed plugin looks like:

```js
{
    "name": "jquery.scrollTo",
    "description": "Lightweight, cross-browser and highly customizable animated scrolling with jQuery",
    "homepage": "https://github.com/flesler/jquery.scrollTo",
    "main": [
        "./jquery.scrollTo.js"
    ],
}
```

results:

```js
require('jquery.scrollTo'); // doesn't work, results in Module not found: Error: Can't resolve 'jquery.scrollTo' in
require('jquery.scrollTo/jquery.scrollTo.js'); // works
```

It clearly indicates that somehow bower.json main propery is being ignored. I hope this can be resolved as soon as possible.

**Comment by linaspa** [comment]
@arshtepe it looks like, this issue is related to webpack/enhanced-resolve#30 . enhanced-resolve plugin that's being used in webpack ignores mainFields values with array type.
