### ISSUE TITLE
Circular dependencies don't work

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#272]
It looks like webpack doesn't have the same behavior as node.js for circular dependencies. When I require a module that closes a dependency loop, it seems to just return an empty object that is never populated. In node.js, an empty object is returned (or actually it might be a partially populated object) that is eventually filled in with all the module's exports. 

Am I just doing something wrong, or does webpack not support node.js-like circular dependencies?

**Comment by georeith** [comment]
@damassi I've thought about it and what I am doing is wrong.

The compiler has to make a choice between either executing 2 or 3 and 2 or 4 either way one of the dependencies won't be fulfilled in time. I don't think there is any feasible way of determining which is required to execute first, and should just avoid these sorts of circular dependencies altogether.

**Comment by damassi** [comment]
@georeith - Yup, totally agree.  This was a painful lesson, but a good one!  I was able to get everything resolved by simply resolving the problem.

**Comment by salarkhan** [comment]
Hitting this exact problem currently:
```
FileA:
var b = require file B
var c = require file C
```
```
FileB:
var a = require file A
```
```
FileC:
var a = require file A
```

When I run the code, I get an error in file C: `A.doSomething is not a function`. 

Threw a debugger in there and saw that A is an empty object. What's __really__ weird is that I'm only getting an error in File C, but not File B. Super confused here.

**Comment by fresheneesz** [comment]
Wow you have major circular dependencies going on. Without seeing the rest of your code, there's no way to know what could be going on. I would strongly suggest attempting to remove the need for all those circular dependencies.

**Comment by gsantome** [comment]
Someone could solve this problem? I have exactly the same problem here

**Comment by andpor** [comment]
Wow - have the same issue. Basic circular dependency does not seem to work at all. Desperately need a fix...

**Comment by tovarisch** [comment]
Еhe problem is in switching "module.export" object in internal presentation of webpack in your code. For example "module.exports.foo = "bar";" will work fine even in deep dependency code. Not sure this is solution as is =)

**Comment by jfeldstein** [comment]
The use of `exports.foo` over `module.exports.foo` is baked into webpack. Users can't modify this transpilation. 

If `module.exports.foo` works, why doesn't webpack use that?

**Comment by fresheneesz** [comment]
@jfeldstein That's not how node.js does it, and it would be confusing to have webpack operate in a different way. There's no magic in how modules are put together. Just like if you had this:

```
var exports = {}
var module = {exports:exports}
```

If you reset `module.exports`, the exports variable still exists. Doing something else would probably end up making some people very frustrated when they don't understand why webpack is doing things a different way.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/tree/master/examples/commonjs#jsoutputjs

``` js
var module = {
  // ...
  exports: {}
};

moduleFunction.call(module.exports, module, module.exports, __webpack_require__);

function moduleFunction(module, exports, __webpack_require__) {
  // ...
}
```

**Comment by aspirisen** [comment]
Have the same issue when I extend one class from another - `Uncaught TypeError: Cannot read property 'prototype' of undefined`

**Comment by Clay-Ferguson** [comment]
The worst part of this mess is that i have yet to find a module loader capable of DETECTING a circular dependency and just printing a meaningful error saying "circular dependency".  They all end up failing rather badly and with no hint to what the real problem may be. The "Cannot read property 'prototype' of undefined" is just completely unacceptable, for a problem AS COMMON AS a circular dependency. Also detecting a circular ref is a simple thing to do in the loader. It would be like 10 lines of code, which is just building a map and constantly searching it before you add to it.

**Comment by TheLarkInn** [comment]
Do you have a reproducible example you can provide?

**Comment by mrchess** [comment]
Anyone know if this is resolved or seems to have a sensible fix? I can't share code between folders, for example constant files, because of circular dependency limitations.

**Comment by Clay-Ferguson** [comment]
I actually did find a great solution. The key is that you DO have to BREAK the circular reference at some point in the chain, but there's a methodical to do it. Just use an interface for one or more of your 'import' so that it 'breaks the circularity'. In my particular app it just so happened that if I remove dialogs objects from the 'chain' (using interface imports for those) circularity is solved:

Project:
(https://github.com/Clay-Ferguson/meta64)

Here's the relevant links to let you piece it together:

** Interface to be imported (and won't cause circular issues)
https://github.com/Clay-Ferguson/meta64/blob/master/src/main/resources/public/ts/AudioPlayerDlg.ts

** Implementation of the Interface
https://github.com/Clay-Ferguson/meta64/blob/master/src/main/resources/public/ts/AudioPlayerDlgImpl.ts

** How I construct these types of objects
https://github.com/Clay-Ferguson/meta64/blob/master/src/main/resources/public/ts/Factory.ts

Sorry that I don't have time to post a full "how to" (but merely those examples).  To be clear what I'm saying is if I removed all the similar 'interfaces' from my app, and tried to import dialogs directly that creates circularity, but loading asynchronously, and importing the INTERFACE instead, was the solution.

**Comment by ericgundrum** [comment]
This is a real world issue when working with streams. Unfortunately the module that implements streams for the browser also attempts to import "stream". In fact, 'readable-stream' has code specifically to break the cycle in broswerify.

Consider this project [pouch-websocket-sync-example](https://github.com/pgte/pouch-websocket-sync-example). It fails with the latest webpack because of a circular reference to "stream" deep within the dependency tree in the code that is intended to supply the stream implementation for the browser.

One solution I found is to import "stream-browserify" from my app's entry point. "node-browser-lib" uses this module to implement "stream". By importing it before any other code that attempts to implement "stream", webpack loads it before the dependency cycle forms. (In hindsight, I suspect that importing "node-browser-lib" instead would work, too.)

I could have saved many hours of tracing webpack code if webpack issued a warning when it encountered a dependency cycle. From what I saw in the code, it might be relatively easy to do. (I'd be willing to do it if the maintainers accept the idea.)

**Comment by Clay-Ferguson** [comment]
Eric, you're so right that it takes a big "real world" app to encounter the tricky circular-ref failures, which is why I was unable to provide the "simple failing test case". But once you encounter the failure there is NO WAY to determine what is really going wrong without days of analysis which is what also happened to me too. I'd say I spent 5 full days solving circularity in meta64.com, because all module loaders were too dumb to detect any of it. RequireJS had the same issues.

This is a VERY serious and dire issue for all module loaders to solve, and embarrassingly easy to solve. Circular refs are a totally predictable, normal, to be expected, type thing that I'd claim MOST large existing apps have. I think the module-loader developers just haven't yet realized this problem effects MOST large apps rather than just a few poorly designed ones.

**Comment by ericgundrum** [comment]
[pouch-websocket-sync-example](https://github.com/pgte/pouch-websocket-sync-example) actually is a very simple app -- only a few files. All the heavy lifting is done by dependencies. But, without knowing how those dependencies are implemented, it's hard to know where to look for the error. Certainly this is worse for any large project.

Issue #631 is a discussion about adding a more meaningful message to webpack. It ends with reference to [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin). The plugin certainly looks helpful, but I'd have to know that I need it to make use of it. This is not intuitive to many people.

Looking back on this thread has me thinking that maybe adding to the webpack error message would be immensely helpful. Consider 

> Uncaught TypeError: Cannot read property 'prototype' of undefined -- maybe you have a dependency cycle

But I don't know what other webpack code might generate that error message, or even if it comes from webpack. 

What I recall from tracing the webpack code leaves me thinking there is an easy place to notice and report the problem. Or even notice and _fix_ the problem, for that matter. Though I'd have to study it more carefully to be sure doing so has no performance penalty.

**Comment by Clay-Ferguson** [comment]
That error message is basically the equivalent of a null-pointer exception in Java. It just means they didn't do any error detection whatsoever, and so it just malfunctions ungracefully when it tries to access unset variable.  Countless other bugs would cause precisely the same error, and therein lies the problem. They need to print an error that shows not only that it's a "Circular Ref", but they ALSO need to show the full stack of module loads (like a call stack) that led up to the circle being encountered. Sounds hard to implement, but in reality is not.

**Comment by calvinmetcalf** [comment]
I'm not sure this particular issue has to do with a circular dependency per say, am trouble shooting it at nodejs/readable-stream#237

**Comment by calvinmetcalf** [comment]
there is a bug in how webpack is handling certain complex circular dependencies. specifically it won't build the module [pouch-websocket-sync](https://github.com/pgte/pouch-websocket-sync) correctly specifically the code I got to trigger this was 


```js
var through2 = require('through2');// must be v2 or higher
var TransformStream = require('stream').Transform;
console.log(TransformStream);// should be a function instead is an empty object
```

this works fine in browserify and node

through together a repo that demonstrates the issue

https://github.com/calvinmetcalf/webpack-bug

**Comment by calvinmetcalf** [comment]
fyi the newsest version of readable stream now relies solely relies on pkg.browser in order to deal with preventing 'streams' being bundled in unnecessarily so this shouldn't be an issue anymore

**Comment by ericgundrum** [comment]
@calvinmetcalf, probably you can close. 

I agree that readable-stream v2.2.9 seems to have fixed the circular dependency issue.

**Comment by Clay-Ferguson** [comment]
As someone who said a lot on this issue/thread, i want to thank you guys for fixing it if you have. I had switched to using a single file bundle, even during development, so this issue was not currently affecting me but i know it was very important to get this particular bug fixed, and eventually i will hopefully help confirm at some point that it's working in my scenario also (aka SubNode, sbnode.com)

**Comment by abhinavsingi** [comment]
@Clay-Ferguson tried https://www.npmjs.com/package/circular-dependency-plugin ?

**Comment by Clay-Ferguson** [comment]
@abhinavsingi No switched to bundled approach and never looked back.
