### ISSUE TITLE
Documentation: talk about webpack vs SystemJS 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#2727]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

There has been a lot of community confusion in regards to SystemJS and Webpack. This issue is a stub to add some documentation talking about the difference between a module bundler and a module loader and how they perform 2 different things.

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by jackfranklin** [comment]
👍 awesome stuff - pinging @guybedford who is the authority here rather than me.

I think we can take some inspiration from Guy's talk yesterday at PolyConf which talked through the reasons and motivations behind jspm / SystemJS, which I think will clarify to a lot of users where and how Webpack/SystemJS differ.

I don't think it matters if this lives on the jspm or webpack site, as long as one links to the other.

**Comment by sokra** [comment]
https://github.com/webpack/webpack.io/blob/master/src/content/concepts.md

**Comment by TheLarkInn** [comment]
Although it's clear to me we need just a paragraph or so differentiating a bundler and loader.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#152
