### ISSUE TITLE
JsonpMainTemplatePlugin 'Promise' is undefined IE11

### ISSUE THREAD

**Issue by mhingston** [webpack/webpack#2739]
**Webpack version:**
2.1.0-beta.15

**Please tell us about your environment:**
Windows 10

**Current behavior:**
I'm experiencing the following uncaught exception when running aurelia's [skeleton-esnext-webpack](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack)
![capture](https://cloud.githubusercontent.com/assets/9764437/16600245/0e633d78-42fe-11e6-86a4-15bd3b219ad2.PNG)

The issue appears to originate from the transpiled version of [webpack\lib\JsonpMainTemplatePlugin.js](https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js#L85)

I'm not sure if this is an bug with webpack or a misconfiguration with the [webpack.config](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/webpack.config.js) that is being used for the project.

**Expected/desired behavior:**
Promise API is polyfilled correctly.

**Browser:** IE 11
 
**Language:** ES6/7 (Babel)

**Comment by mhingston** [comment]
I'm closing this as I don't believe this is an issue with webpack, rather aurelia's polyfills.

**Comment by dfleury** [comment]
@mhingston I've got the same issue.
I solved that by "polyfilling" manually before using `require.ensure`. It's a workaround.
Take a look:
```javascript
if (window.Map && Map.prototype.keys && Object.keys && Object.assign)
	initApp()
else {
	if (!window.Promise)
		window.Promise = require('es6-promise')
	require.ensure([ 'babel-polyfill' ], function() {
		require('babel-polyfill')
		initApp()
	})
}
```
That way, Promise will be available when webpack's ensure method try to use it.
Is your call decide which Promise library you'll use to polyfill.

**Comment by Kovensky** [comment]
@dfleury note that your snippet has the [zalgo problem](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony). `initApp` runs synchronously or asynchronously depending on the environment; if you're going to make it asynchronous, it should always be asynchronous.

Also, asynchronously loading polyfills is dangerous if you have any third party scripts, as they might be able to see / use / save code before it is polyfilled.

**Comment by dfleury** [comment]
I think I need to apologize for using a real world snippet without all needed context.
Let's forget my snippet and start again with focus on the Promise problem.

If you take a look at the template @mhingston found, https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js#L85 you will notice webpack use the global Promise available, but this can't be always true. In IE11< this api isn't present.
Webpack isn't providing a built-in standalone promise solution and then we can say for now that, webpack doesn't support dynamic code splitting on IE11< without a Promise polyfill available at the global context.

The important point in my snippet is the moment which I set the window.Promise with an implementation of promise api *before* using require.ensure. Otherwise it'll break.

**Comment by TheLarkInn** [comment]
@dfleury Do you think you could create a minimal example repo that reproduces this behavior?

**Comment by dfleury** [comment]
Take a look on Promise support http://caniuse.com/#feat=promises
If you think it still need an example repo, I'll take a time for do that
(which is scarce at the moment)

**Comment by mimse** [comment]
I'm also having a problem with code splitting on IE 11

**Comment by dennischen** [comment]
I have the same problem when using require.ensure. it is just like dfleury said, the ensure js(.e method) created by webpack use Promise directly, that got error when running with IE 7.

**Comment by tnguyen14** [comment]
Having the same problem where webpack assumes `Promise` as a globally available object, which fails on ie 11. Can this issue be re-opened?

**Comment by bluepnume** [comment]
Any planned resolution for this one?
