### ISSUE TITLE
Webpack 2.1.0-beta.15 -- Handling circular references

### ISSUE THREAD

**Issue by wegry** [webpack/webpack#2759]
```
// a.js, the entry point
import b from './b'
import d from './d'

console.log('b -- the circular reference', b) // prints
console.log('d -- the non-circular reference', d)
```
```
// b.js
import c from './c'

export default function () {
  return c()
}

export var doesntShow = 5
```

```
// c.js
import b from './b'

export default function doesntShow() {
  return b()
}
```

```
// d.js
export default {
  foo: 5
}
```

Firefox 46 on OS X El Capitan console prints

> b -- the circular reference function exports.a()
> d -- the non-circular reference Object { foo: 5 }

When the circular reference of b and c is loaded up by __webpack_require__:
```
// The require function
function __webpack_require__(moduleId) {

	// Check if module is in cache
	if(installedModules[moduleId])
		return installedModules[moduleId].exports;

	// Create a new module (and put it into the cache)
	var module = installedModules[moduleId] = {
		i: moduleId,
		l: false,
		exports: {}
	};

	// Execute the module function
	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

	// Flag the module as loaded
	module.l = true;

	// Return the exports of the module
	return module.exports;
}
```
It looks when b goes to require c, its exports are `{}`. When c pulls in b's exports from `installedModules[moduleId]`, they're `{}`. Is this the intended behavior?

*Edit*: fixed export mix up, b should have been exporting `doesntShow` in addition to `default`.

**Comment by Kovensky** [comment]
Look at the actual parts that call `__webpack_require__`.

That's a consequence of `export default` -- unlike other exports, `export default` is not hoisted, is not a live binding, and it does not export an identifier, but an expression.

Importing something that was exported with `export default` will take a _copy_ of the export. It's not defined yet, because of the circular dependency, so one of them is going to see `undefined`.

If you want to do a default export while keeping it a live binding, then you could do something like `function doesShow () {}; export { doesShow as default }`. Webpack generates getters in that case[^1], which will always DWIM. Unless you actually read/invoke them at the top level. Then it's up to the nasal demons.

[^1]: something roughly equivalent to `exports = { get default () { return doesShow } }` and replacing `b()` with `importedB.default()`

**Comment by sokra** [comment]
The semantic of `export default` often confuse people...
