### ISSUE TITLE
Requiring jQuery at the global level for usage with Jquery UI modules

### ISSUE THREAD

**Issue by IamKritika** [webpack/webpack#2800]
I'm working on angular 2, in which I would like to require jQuery from Jquery ui. Each module adds itself to jQuery by accessing the global variable. I have spent hours searching pretty much every corner of Github and Stackoverflow (and other random websites) looking for solutions, but so far, not a single one has worked.

Methods I have tried:

ProvidePlugin for $, jQuery, and window.jQuery, expose loader imports loader various other combinations of requiring jQuery at different locations in my stack I'm clearly missing something here. Every time I write import "jquery-ui" , I get "jQuery is not defined

Thanks.

webpack.common.config.ts

       var path = require('path');
      var autoprefixer = require('autoprefixer');
      var webpack = require('webpack');
      const DedupePlugin = require('webpack/lib/optimize/DedupePlugin');
      const UglifyJsPlugin = require('webpack/lib/optimize/UglifyJsPlugin');
      
      
      var commonConfig = {
        resolve: {
          extensions: ['', '.ts', '.js']
        },
        module: {
          loaders: [
            // TypeScript
            { test: /\.ts$/, loaders: ['ts-loader'] },
      
            { test: /\.css$/, loaders: ['style','css'] },
            {
              test: /\.html/,
              loader: 'html',
              query: {
                minimize: true,
                removeAttributeQuotes: false,
                caseSensitive: true,
                // Teach html-minifier about Angular 2 syntax
                customAttrSurround: [
                  [/#/, /(?:)/],
                  [/\*/, /(?:)/],
                  [/\[?\(?/, /(?:)/]
                ],
                customAttrAssign: [/\)?\]?=/]
              }
            },
            { test: /\.scss$/, loaders: ['to-string', 'css', 'postcss', 'resolve-url', 'sass?sourceMap'] },
            { test: require.resolve('jquery'), loader: 'expose?jQuery!expose?$' }
          ]
        },
        'uglify-loader': {
          mangle: false
        },
        postcss: function () {
          return [autoprefixer];
        },
        plugins: [
          new webpack.optimize.OccurenceOrderPlugin(true),
          new webpack.DefinePlugin({
            ENV: JSON.stringify(process.env.ENV)
          })
        ],
        devtool: process.env.ENV == 'dev'? 'source-map' : null
      };
      
      module.exports=commonConfig;

**Comment by rafde** [comment]
```
module: {
  loaders: [
    { 
      test: /jquery-ui/, 
      loader: 'imports?jQuery=jquery' 
    }
  ]
}
```
will add `var jQuery = require('jquery');` to all your files that live in jquery-ui when used.

**Comment by IamKritika** [comment]
@rafde this didn't work ... 

I am using typings for jquery and jquery-ui. And have also added jquery and jquery-ui to the node modules but still I am getting the same error of 'JQuery not found'

Imports are done this way - 

`import * as JQuery from 'jquery';
import 'jquery-ui'`

**Comment by mover96** [comment]
With the `expose-loader` try something like this at the top of your `main.ts`:
`import 'expose?$!/path/to/the/js/file.js;` where the /path starts from node_modules but you don't include that since you resolve for that folder (you might have to add that). `$` is the var that I am exposing globally, change this to whatever your modules expect jQuery to be defined as. 

Here is my example, where I want the var `Ps` to be on the window globally:
**In main.ts**
`import 'expose?Ps!perfect-scrollbar/dist/js/perfect-scrollbar.min.js';`

**Absolute path to perfect-scrollbar.min.js**
You do not need to include this anywhere, I am just giving you an idea of how I use `resolve` to check `node_modules` for me:
`C:\Code\stash\app\node_modules\perfect-scrollbar\dist\js`

**Resolve settings in webpack.config**
```js
resolve: {
        modules: [path.resolve(__dirname, '/src'), 'node_modules/'],
        descriptionFiles: ['package.json'],
        extensions : ['', '.js', '.ts']
    }
```
Note that I am using webpack 2 beta, but for a similar setup check out this link https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories
You'll notice by default it is set to check in `node_modules` so you probably don't have to add anything. Just make sure you understand the difference between webpack not being able to find your `jquery-ui` file vs your modules not being able to find the global var.

**Comment by daominhsangvn** [comment]
@IamKritika Add this to your webpack config
```
plugins:{

...

new webpack.ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery',
      jquery: 'jquery'
    })

...

}
```
