### ISSUE TITLE
Feature Request: Stats for time spent in different loaders

### ISSUE THREAD

**Issue by iamdustan** [webpack/webpack#2811]
I often am trying to get a better understanding of where time is being spent in webpack. Node v6 brings a tool to the table with solid support for running webpack attached to the web inspector profiler, but that is a quite the forest to jump into.

What I want is a high level view of what loaders are taking the most time.

Given the following devtime config it would be great to see what time is spent in js total and stylus total and also by loader. While working to optimize our development startup time as well as production build times it would be amazing to see where time is being spent from things that we are configuring (not all of webpack internals as well).

```
loaders: [
  {test: /\.js/, loaders: ['babel']},
  {test: /\.styl$/, loader: 'style!css!stylus'}
];
```

This would allow us to easily focus on what configuration and tools to experiment with for the largest wins.

**Comment by evan-scott-zocdoc** [comment]
I would cherish this. We have a ton of loaders in use and being able to more granularly identify bottlenecks would be amazing.

**Comment by samccone** [comment]
+1 to this. @TheLarkInn Let's work together on landing this improvement into webpack. 

I wonder if we could use a format like HAR to dump the timing with, just so it is a generic format that can be loaded by a lot of different tools, instead of implementing a custom format, or a proprietary format.

**Comment by TheLarkInn** [comment]
I'm down for that. There are some very general and more specific phases that go on in webpack. What do you think the best way to break them up would be? 

Here is just an idea (feel free to critique): This is more like "phases of webpack of things that are happening".:

#### Phase Based(?)

1. Initialization: Compiler consumes options, plugins are applied based on them. Up until the beginning of the Dep Graph collection begins: https://github.com/webpack/webpack/blob/a7565e450e4a7d3dd609ae9582073267c60dd78f/lib/SingleEntryPlugin.js#L24

2. Dep Graph Creation: This is a bunch of parts
  a. (starting with entry): Send raw request (entry path), resolve it
  b. resolver returns path to Module Factories, collects source and creates module object
  c. loaders are applied
  d. module is parsed
  e. Dependencies Attached to module.
  f. For each Dependency, Repeat a/f (BFS Traversal)

3. Sealing Phase
  a. Modules are put into chunks
  b. <Bunch of Plugin hooks fire and perform optimizations, side-effects etc>

4. (Render Phase)[https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L1233]
  a. chunkTemplate.render() 
  b. which trigger each module in above chunks to render
  c. which call the Dependency Templates to render dependencies.

5. Additional Assets etc. (other plugins creating stuff) + Emit
6. Make stats!

Maybe another idea would be since there are so many plugins, that we could also take a plugin approach. 

### Event based timings (?)
**SomePlugin.js**
```js
class SomePlugin {
  apply(compiler) {
    compiler.plugin("some-event", () => {
      start()

      stop()
    });
  }
}
```

This doesn't feel like the cleanest approach, but just throwing ideas out there for this.

**Comment by TheLarkInn** [comment]
@samccone I also agree a standard format like HAR would be great.

**Comment by vigneshshanmugam** [comment]
The easiest solution IMO is to write a plugin and listen to all high level events from compiler and compilation and print it out as part of stats object (stats.timings?).

**Comment by DrewML** [comment]
I'd be happy to just see the right plugin hooks put in place so that this kind of tooling could be iterated on in userland.

Right now, I'm very interested in being able to expose the timing of each loader per file. I dug through the source a bit, but it doesn't look like there are any plugin hooks that would allow me to capture this with the plugin API.

Right now, for a single file, a list of all loaders are passed to the `loader-runner` lib. `loader-runner` has no concept of `Tapable` hooks, so it isn't possible to get granular data without setting up webpack to load a forked `loader-runner`. The best you could do currently (afaict) is determine the amount of time it takes for _all_ loaders to run on a given file.

**Comment by HipsterZipster** [comment]
Have their been any updates on this? I think this would be incredibly useful. #5718 appears to be doing something like this already, do we have any idea how?

**Comment by stephencookdev** [comment]
I've created a plugin to do this (measure timing stats for loaders + plugins): https://www.npmjs.com/package/speed-measure-webpack-plugin

It aggregates all grouped loaders (as the api isn't granular enough otherwise, and tbh I'm not sure timing stats on each individual loader is _that_ helpful)

It gets the plugin timing data by wrapping all of the plugins (so the original plugins are only ever used through a wrapper)

Please give it a go, and let me know what you think

**Comment by samccone** [comment]
Hi all, this landed in webpack 4!

example trace
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://1kj9M7frgskdtlWH_eMFDwuT8USgOte9w

how to use

![](https://pbs.twimg.com/media/DUlhldNVwAAs_kN.jpg:large)

**Comment by SEAPUNK** [comment]
This seems like just a webpack plugin profile, and not a loader profile. I'd like to know which loaders are hogging up all of the time, rather than plugins.

**Comment by TheLarkInn** [comment]
Plugins are instantiated by loaders and could show some insights. I'd try
it first. 😏

**Comment by SEAPUNK** [comment]
That's not helpful. Judging from the example trace link samccone posted, where aside from a multitude of plugins that run for a few microseconds, there's just one big SingleEntryPlugin in the user timing tab, which tells me nothing about what it's actually doing.

**Comment by SEAPUNK** [comment]
Yes, but my point is that it still involves digging around through the devtools, and provided you have some knowledge with the profiler and how to use it, you have to know what you're looking for. Not to mention, you could still profile this stuff without this plugin.

The better solution here would be to just time and log the aggregated times of the loader execution, with maybe some other stats (how many files the loader had to process, whatnot), a la the output of `webpack.ProgressPlugin({profile: true})`.

[PostCSS does this](https://github.com/postcss/postcss-devtools), and I've found it to be very helpful.

**Comment by stephencookdev** [comment]
@SEAPUNK that's exactly what [the plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) I mentioned does
It returns an output like
```
thread-loader, and
babel-loader took 0.56 minutes
    Med   = 401 milliseconds,
    x̄     = 1.08 seconds,
    σ     = 0.57 seconds,
    range = (268 milliseconds, 2.49 seconds),
    n     = 247
file-loader took 7.11 seconds
    Med   = 1.41 seconds,
    x̄     = 1.26 seconds,
    σ     = 436 milliseconds,
    range = (340 milliseconds, 2.02 seconds),
    n     = 29
```

**Comment by evilebottnawi** [comment]
@stephan83 Can you send PR to https://github.com/webpack-contrib/awesome-webpack?

**Comment by stephencookdev** [comment]
@evilebottnawi did you mean to @ me?

**Comment by samrod** [comment]
@stephencookdev I'm getting the following error:
```
/node_modules/webpack/lib/Stats.js:273
                                        size: compilation.assets[asset].size(),
                                                                        ^
TypeError: compilation.assets[asset].size is not a function
 ```

**Comment by stephencookdev** [comment]
Hey @samrod :) Could you [raise an issue against SMP]?(https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/new) (rather than add loads of noise to this thread)

If you could just let me know in that issue what your webpack version is, and any other info about your webpack config to help debug
