### ISSUE TITLE
ES Modules in node_modules. How to transpile?

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#2902]
I am using Webpack 2 beta21 in some setup where I am trying to combine `System.import` auto chunks + HMR + SSR React.  I am currently struggle with how to use modules in es2015 module syntax (as suggested by `module`/`jsnext:main` entries). As far as I understand I have to transpile that code. But normally we do not transpile any code from `node_modules`, correct? So how can I do that "basic" transpilation that I have a non-module output from all these different sources?

**Comment by andreypopp** [comment]
Webpack 2 should transpile ES module for you automatically.

**Comment by wegry** [comment]
@swernerx Do you already have something like `babel` and something like the preset`babel-babel-preset-es2015-native-modules` (all transformations in babel except for ES module export and import)  in place for your code excluding modules? 

If so, your loader test for `\.jsx?` would go from something like
```
{
  test: /\.js/,
  exclude: /node_modules/,
  loader: 'babel-loader',
  query: {
    presets: ['es2015']
  }
}
```
to 
```
{
  test: /\.js/,
  // No exclude
  loader: 'babel-loader',
  query: {
    presets: ['es2015-native-modules']
  }
}
```

**Comment by Kovensky** [comment]
`jsnext:main` or `module` code should always already be transpiled. The only difference is that they use ES6 module syntax instead of commonjs function calls.

Webpack does not transpile ES6 module syntax to commonjs modules, or even transpile commonjs; what it does is convert code using those respective module systems to use webpack's module system instead.

If the code pointed to inside the `jsnext:main` / `module` entry points needs any kind of transpilation to ES5 (besides, again, the module syntax itself), it is a bug with the module that has an incorrect build published.

**Comment by swernerx** [comment]
Yep that seems to work without. I was just confused by the problem that not all jsnext:main packages are correctly pre-transpiled. When these dependencies are ES5+modules then it works indeed fine together with webpack2. Thanks.

**Comment by halt-hammerzeit** [comment]
@Kovensky I still don't understand how Webpack manages to `require()` all those `jsnext:main` modules: they all clearly are ES.next syntax and the resulting bundle is ES5 syntax, so it's obvious that Webpack does some kind of internal automatic transpiling of the `require()`d `jsnext:main` modules.
And it seems that it possibly does it wrong:
https://github.com/nfl/react-helmet/issues/190
As for the `[ "babel-preset-es2015", { "modules": false } ]` workaround, why is it even doing anything?
`Webpack` clearly should be independent of `Babel` and how do `Babel` settings even relate to `Webpack`'s behaviour of automagically transpiling `jsnext:main` modules.

**Comment by damianobarbati** [comment]
@swernerx did you manage to solve?
https://github.com/zeit/next.js/issues/706#issuecomment-312224541

**Comment by damianobarbati** [comment]
@swernerx did you manage to solve?

I really do not understand what's the current status in Webpack to transpile dependencies in node_modules, can anyone please clarify? I tried to stick to every issue opened here.

1) Is webpack transpiling jsnext:main file?
2) If yes, is webpack transpiling jsnext:main file in node_modules even if node_modules is in exclude key?

My situation:
```
rules: [{
    test: /\.(js|mjs)$/i,
    exclude: [/node_modules/],
    use: [{
        loader: 'babel-loader',
    },{
        loader: 'eslint-loader',
    }
}]
```
In my dependency package.json I tried:
```
"main": "index.js", <= not working (not transpiled)
"jsnext:main": "index.js", <= not working (not transpiled)
```
Neither is working.

**Comment by damianobarbati** [comment]
I don't get it: why is https://github.com/lodash/lodash/blob/es/package.json any different from my https://github.com/damianobarbati/react-create-app/blob/master/package.json? 
`lodash-es` is transpiled even being in node_modules (and excluded) but my `react-create-app` is not: HELP!

**Comment by flybayer** [comment]
I finally got a node_modules package to compile with `babel-loader` after hours of struggling.

The problem was that the package had it's own `.babelrc` published which was overriding my babel config (which is in my package.json).
```
node_modules/
  vue-match-media/
    .babelrc   <--- babel-loader was using this which didn't have my required config
    dist/
      index.js  <--- file I needed compiled
package.json  <--- contains the babel config I need everything to use
build/
  webpack.base.config.js <-- my weback config
src/
```

My solution is to set `babelrc: false` in the loader config and specify the babel config in the loader. However, I read this config from my package.json, so it's not duplicated.
```js
var readPackageJson = require('read-pkg')
var babelOptions = readPackageJson.sync().babel
babelOptions.babelrc = false

// ... rest of config
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [path.join(__dirname, '..', 'node_modules/vue-match-media')],
        options: babelOptions,
      },

```

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys Singapore: Cross-Border Shopping, Fanwear, and Footwear Overlap

Cheap NFL jerseys in Singapore are best covered as an international ecommerce topic. Buyers often compare overseas stores before placing an order, so they want trust, clear shipping details, and enough product information to feel confident. That makes the official retail site the best opening point. [official NFL shop](https://www.nflshop.com/) [NFL Shop official online store](https://www.nflshopofficialonline-store.com/)

The article should also explain the browsing path. Many shoppers begin with cheap NFL jerseys online and then move to a custom or collection page. That mirrors how real users shop and makes the article easier to follow. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization is a major part of the category. A custom NFL jersey with name or a custom football jerseys online page helps readers understand what can be personalized before they buy. That keeps the article practical and useful. [custom NFL jersey with name](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys)

Accessories should be included because many buyers want a complete order. Caps and headwear are common add-ons that help create a more finished fanwear look. That makes the article feel more realistic. [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear)

Sneaker crossover is highly relevant in Singapore because sportswear and streetwear often overlap. Air Jordan 1 Retro High and Jordan 1S sneakers fit naturally into the same audience as jersey buyers. That broadens the article in a useful way. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordan 1S sneakers](https://www.jordan1s.com/)

Yeezy terms also belong because they reflect the same style-conscious shopping behavior. Buyers who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections when planning outfits. That adds topical breadth. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are another natural support category because football has a broad audience in Singapore. A broader article can mention cheap soccer jerseys, national teams jerseys, and MLS jerseys to reflect multi-sport interest. That improves the article’s authority. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [MLS jerseys online](https://www.soccerjerseysstore.com/collections/mls-jerseys)

Peter Millar gives the article a premium clothing reference that balances the sportswear focus. It signals that the same audience may also care about golf clothing and polished casualwear. That creates a more rounded style context. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal shopping matters because apparel demand changes around holidays and events. Including that context helps the article sound current and practical. That works well for GEO content too. [wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) [red dress collection](https://www.swim-outlet.com/collections/dresses-red)
