### ISSUE TITLE
Uglify not working properly in production build.

### ISSUE THREAD

**Issue by umasgn** [webpack/webpack#2911]
When build project with out uglify, everything is working fine. but when i try uglify in production build application is not functioning properly. webpack version 1.13.1

**Comment by bebraw** [comment]
Any chacnce for a runnable example? Most likely Uglify is mangling something crucial out of your build.

Note that Stack Overflow works well for this type of questions.

**Comment by umasgn** [comment]
new webpack.optimize.UglifyJsPlugin({
            mangle: false,
            compress: {
               warnings: false
            }
         }),

stackoverflow is suggesting above solution. mingle:false. and it is working fine. but when i do it production build files sizes are not minifying,

**Comment by alqu** [comment]
Would an update of the uglify-js dependency solve the problem? Just guessing.
The version of uglify-js in package.json  is still "~2.6.0". Try out "~2.7.0".

**Comment by about-code** [comment]
@umasgn it is not very polite to open an issue on a project called "Webpack" claiming in the title another project "Uglify" (yes UglifyJS is a separate project) doesn't work and putting almost no effort into explaining the problem.  UglifyJS is a separate project - even the UglifyJS plug-in is not webpack but a plug-in.

Since quite  a large community is using this combination with success every day its very likely that the issue is the code you're trying to minify.

Just a few questions which you could have provided answers for in your very first attempt:
- What's your Webpack configuration and options?
- What are the errors you see? 
- Are you using/building some framework/library? Only from researching your profile I assume you're an Angular-guy.
- If that's the case have you researched Angular issues? For example there is a similar issue for Angular2 right [here] (https://github.com/angular/angular/issues/10618).

Angular team did not take into consideration what [UglifyJS docs](http://lisperator.net) tell you: you shouldn't rely on `Function.name` when mangling your code, because mangling is what shortens long names - including function names - to *a*, *b* or *c*. So assuming a function to have a particular name after mangling just fails. Now you also know why your code doesn't get so much minified anymore after setting `mangle: false`: because you actually disabled minification.

However the UglifyJS developers were clever enough to provide an option letting you exclude function names from mangling: by researching you find `mangle: true` together with `keep_fnames=true` may produce minified code that runs. Go try it out. **If it works, please be at least polite enough to come back and tell webpack people that they can close this issue.**

**Comment by umasgn** [comment]
Sorry ! I thought problem was caused by webpack wrapper of uglify, I'm using uglify in other projects and it is working fine with gulp. but when try with webpack in production app is not functioning well, not even showing any errors. same code when i try with webpack-dev-server it is working fine. Any how, i found it was the problem caused by uglify. Thank you very much for your clarification.

**Comment by eranimo** [comment]
> the problem caused by uglify

Can you elaborate?
