### ISSUE TITLE
`this.inputValue` not available after pitching loader

### ISSUE THREAD

**Issue by cletusw** [webpack/webpack#2920]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.11.4

**Current behavior:**
Pitching loaders are not able to use `this.value` to pass results to the next loader's `this.inputValue`

**Expected/desired behavior:**
A downstream loader should be able to use `this.inputValue` to obtain the previous loader's `this.value` even if the previous loader pitched.

**Minimal repro:**
1. https://plnkr.co/edit/egV5d9yp8NC5tLPwcgks
2. Download as zip
3. `npm install`
4. `npm test`

**Browser:** all

**Language:** all

**Comment by cletusw** [comment]
I believe the solution is as simple as adding `loaderContext.inputValue = privateLoaderContext.value;` before [webpack-core/lib/NormalModuleMixin.js:231](https://github.com/webpack/core/blob/v0.6.8/lib/NormalModuleMixin.js#L231)

**Comment by sokra** [comment]
`this.value` and `this.inputValue` are removed in webpack 2 anyway.

**Comment by tajo** [comment]
I'm trying to fix my loaders for Webpack 2. Since I was using `this.inputValue`, they don't work anymore. I have hard times to find out how to write a loader for Webpack 2 (best practices). There is a [documentation](https://webpack.js.org/loaders/) explaining how to use them but nothing about how to develop them. Is there some documentation other than just going through the source code of other existing loaders? Thank you. I understand it's probably not a priority until v2 is out.

**Comment by sokra** [comment]
You can pass multiple arguments between loaders.

`this.callback(null, a, b, c, d)`

`module.exports = function(a, b, c, d) {`

Maybe this fulfills your use case.

**Comment by sokra** [comment]
Closing this issue, because it's no longer relevant.

@tajo If you want to discuss your issue (which is something different), please open a new issue.
