### ISSUE TITLE
How to configure Webpack for multiple html files with common js and html specific js?

### ISSUE THREAD

**Issue by surenrao** [webpack/webpack#2944]
I have setup an angular 2 version rc5 with webpack project. I am trying to add some extras like a lib.ts (for custom libraries not angular dependant) and redirect.html page which will be used as a callback page by third party for authentication (say Dropbox). so my webpack.common.js now looks like

 ```
entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'app': './src/main.ts',
    'lib': './src/lib.ts'
 },
 plugins: [
     new webpack.optimize.CommonsChunkPlugin({
         name: ['app', 'lib', 'vendor', 'polyfills']
     }),
     new HtmlWebpackPlugin({
         filename:'index.html'
         template: 'src/index.html'
     }),
     new HtmlWebpackPlugin({
         filename:'dropbox.html'
         template: 'src/redirect.html',
         excludeChunks:['app']
     })
 ]
```
This redirect page is just a normal page (not an angular page) which captures access_token using lib.ts and lib.ts is also used by angular as a service which pretty much wraps libs.ts.

Now i want to add a script tag or file only for redirect.html and not for angular or index.html how do i do that? Is there an example which deals with two or more separate html files with some common js includes mixed with some unique html specific js files?

**Comment by rafde** [comment]
@surenrao you neglected to read
> If you have a support request or question please 
submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/webpack) using the tag `[webpack]` or the [webpack Gitter](https://gitter.im/webpack/webpack). Future support requests will be closed.

I would suggest asking there as you will get a wider range of visibility.

**Comment by surenrao** [comment]
@rafde Actually i did, before posting here i posted exact same question to [StackOverflow](https://stackoverflow.com/questions/39277490/how-to-configure-webpack-for-multiple-html-files-with-common-js-and-html-specifi) 
After getting no response, i figured to try my luck directly at the source :)
And if this gets an answer it will be a good reference for others

**Comment by bebraw** [comment]
You are on the right track. A custom html-webpack-plugin template is the key. You can get more control over the result by running webpack in multicompiler mode. Instead of returning an object you can return an array of objects (separate configurations). This allows you to include something extra to that specific template (i.e. script tag). Or you can try solving it at template level as the templates support basic logic (EJS by default iirc). I hope this helps.

Stack Overflow can be a bit slow due to the sheer amount of questions these days but it's definitely better for support.
