### ISSUE TITLE
Use JSON schema to validate webpack configuration

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#2971]
**Current behavior:**

`webpack` constructor accepts any object and it will silently fail when it does not recognise a property, e.g.

```js
const webpackConfig = {
  devtool: 'source-map',
  debug: true,
  context: __dirname,
  target: 'node',
  entry: {
    'app': [
      path.resolve(__dirname, './src')
    ]
  },
  pathinfo: true,
  output: {
    path: outputDir,
    filename: '[name].js'
  }
};
```

Looking at the above configuration, the error is not immediately obvious.

**Expected/desired behavior:**

Use http://json-schema.org/ to enforce `webpack` configuration.

In the above example, an error would be raised since `pathinfo` property belongs to the `output` object.

**What is the motivation / use case for changing the behavior?**

To prevent unintentional configuration silently failing.

**Comment by gajus** [comment]
I am happy to raise a PR.

**Comment by jhnns** [comment]
We have talked about this lately because wrong configuration can be a major pain. If I recall it correctly we were talking about adding a typescript interface definition to the repository @bebraw @TheLarkInn ? This way, IDEs could give you better support when writing the configuration (even when you don't use typescript).

Currently we can't just throw when an unknown property is encountered because some loaders use already arbitrary keys. These arbitrary keys will be discouraged with webpack 2 (and effectively replaced with the [`webpack.LoaderOptionsPlugin`](https://gist.github.com/sokra/27b24881210b56bbaff7#loader-options--minimize)), but I don't think we should actually throw with webpack 2 (we may throw in later versions, however).

Actually, there's already a community solution, it's called [webpack-validator](https://github.com/js-dxtools/webpack-validator). I'm not sure if this should be pulled into core...

But we definitely want to improve the developer experience 👍

**Comment by bebraw** [comment]
webpack-validator uses [joi](https://www.npmjs.com/package/joi). In some ways it's nice but it doesn't allow you to add text based descriptions to the fields. JSON Schema provides that.

I guess if we provided a schema at core level, loaders would have to be able to extend it if we want to support that kind of injection. Sometimes they allow the user to pass extra configuration that way. It would be better to provide a pattern that avoids this, though.

There has also been talk of official TypeScript definitions for configuration. I would go with JSON Schema myself as it's standard (other tools play well with standards). Compared to joi it's missing some functionality. The biggest problem is that we would have to implement dynamic checks on top of JSON Schema. More discussion here: https://github.com/js-dxtools/webpack-validator/issues/89 .

**Comment by gajus** [comment]
@bebraw You don't need to cover the entire configuration. Covering just standard options would be  a good start.

I have mocked up a schema for `output` configuration.

https://gist.github.com/gajus/8d75e1d3a80f5bdf0db9ebd840fb4a03#file-webpack-config-json

**Comment by bebraw** [comment]
@gajus That's a great idea as it covers most of the need. 👍

**Comment by andreypopp** [comment]
> @bebraw You don't need to cover the entire configuration. Covering just standard options would be a good start.

The problem is also typos which misspell standard options like `modules:` vs `module:` — seen this. Some way to report that would be great: `You don't have "module:" defined but there's "modules:", that might be it`.

**Comment by TheLarkInn** [comment]
I think a json schema is an excellent start for now, flow and ts authors could in theory generate type defs based on this.

**Comment by gajus** [comment]
I am writing a PR.

**Comment by gajus** [comment]
Just in case, I will write the JSON schema against the current docs, https://webpack.github.io/docs/configuration.html.

As far as I know, There are a few incompatibilities with the v2 API. If someone could refer me to a summary, that would be helpful.

**Comment by sokra** [comment]
Let's do it. See PR
