### ISSUE TITLE
Loader changes proposal

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#2975]
This is a proposal for some new features for the loader API.

Motivation:
- typescript loaders need more than the normal loader API and access `this._compiler` for this reason. That's bad and we want this loaders to be able to use the public API
- extract-text-plugin is ugly and it should be replaced with a loader only solution
- a group of loaders cannot work together to create a single module/asset. i. e. a sprite-loader should be possible which puts all images in a single image and return a css rule.
### `this.cache`

A (thread-local) object for all loaders to store JS variables. It should always accessed via `var cache = this.cache[__filename] = this.cache[__filename] || {}` to get a loader local cache.

Edit: Instead of this ugly construct it's better to use a method `this.cache([optionalIdentifier])` which defaults to the loaders filename.

Motivation: Typescript needs a global instance of the LanguageServiceHost. This make it possible to share data between loaders.
### `this.defer(options, callback)`

This registers a callback which is called in a later phase of the compilation. It's called after all loaders were executed.

`options.data: any` publish data from this loader.

`callback` is called with `(deferredInfo, callback)`. `deferredInfo` contains:

`data: any[]` All published data from the same loader. Defer callback will execute in this order.

The context (this) in the callback contains at least the following properties:

`this.emitAsset`, `this.emitWarning`, `this.emitError`,

`this.invalidate(data)` schedules a new compilation of the current module, meaning all loaders will be reexecuted. `this.data` is set to the passed data object.

Motivation:
- allow typescript to emit its warnings after all modules are compiled.
- allow to write a separate-css-loader (as replacement to the extract-text-plugin)
### `this.query`

`this.query` can be an object instead of an string. Is happens when a query is set via configuration. This allows to pass any object to the loader if it is executed in the same thread.

This renders `this.options` obsolete and `LoadersOptionsPlugins` will be removed. `minimize` and `sourceMap` need to be explicitly passed to the loader if wished.

Motivation: make `query` the only source of options, while allowing any js value to be passed.
## Other changes required
- Loader matching depending on whether a module is in the in the initial chain.
- Loader matching depending on the issuer.

---

Opinions?

**Comment by jantimon** [comment]
Why is the `filename` in `this.cache[__filename]` required?

**Comment by sokra** [comment]
The `this.cache` object is shared by all loaders. `this.cache[__filename]` gives you a child object that is private to your loader (private to the file calling this line).

My initial plan was to get the private object in the loader runtime, but this would make it impossible to share cache between multiple loaders of a group of loaders.

But I see the ugliness of the required construct. Maybe it's better to offer a `this.cache([optionalIdentifer])`  method returning the cache. It could default to the loaders filename. That's simpler to use.

**Comment by TheLarkInn** [comment]
@s-panferov @jbrantly this change is relevant to both of you. Please speak up if there are any questions or concerns. //cc @robwormald

**Comment by johnnyreilly** [comment]
Sounds cool but it's @jbrantly who should comment really; he's the main person behind ts-loader.

**Comment by jbrantly** [comment]
I'm not entirely sure I understand the point of `this.cache` in this context. The shared instance of LanguageServiceHost is mentioned, but that is currently handled simply by a singleton in the loader module. Perhaps I'm missing the point.

There are a number of issues that make it difficult to integrate TypeScript into webpack. First and foremost is that webpack loaders typically work on a "per-file" basis but TypeScript works best on a "per-project" basis due to inter-dependencies between files. This is handled naively by simply letting TypeScript do it's thing and load all of the files in the project itself, and then the webpack loader can simply query the output for each individual file. This is roughly how the TypeScript loaders work today. However, there are a few problems with this approach:

1. Reporting errors is hard. The blessed loader API allows you to report errors for the currently executing module. In order for TypeScript to accurately report errors, it must have already loaded the entire program to handle inter-dependencies. That would be fine except that the program that TypeScript knows about could be about to change. For example, say `a` depends on `b`. Both files changed at the same time, so both need to be run through the loaders during a watch. `a` runs first. We update the TypeScript host with the new content of `a` and pull the new transpiled content. There are no errors (yet), so we don't report any. Now `b` runs. The changes to `b` technically break `a`, but we've already run `a` so we don't know that. This is (partly) why we need to run error reporting at the end. `this.defer` sounds like it might be a step in the right direction, but probably is not enough. For instance, say in the above example *only* `b` changed, but the error is now actually in `a`. `a` is not run through the loader because it didn't change, and therefore there would be no chance to report an error for it.
2. Reporting errors for files that webpack doesn't know about is hard. In particular `.d.ts` files, but also things like `tsconfig.json` files. This currently requires using unpublished APIs since these are essentially modules that webpack knows nothing about.
3. Chaining loaders before TypeScript is hard. The "initial" state of the TypeScript program is straight from disk since TypeScript goes ahead and loads the entire program when trying to get the output of a single file. If there are additional loaders that should run before TypeScript, then that can be detected and the TypeScript program updated as webpack runs, but it's pretty inefficient.
4. Caching can be a problem. Sometimes a module used to not have an error but now does due to a change in another file, but webpack treats the file as "unchanged" since the contents of the file didn't change. If memory serves this had an effect on error reporting (webpack either wouldn't report the new error or could keep old stale errors around that weren't actually errors anymore). I got around this by changing the "meta" property on the module using unofficial APIs.
 
I'm not sure about solutions for some of these. Some sort of "project-level" APIs might be interesting. Similar to plugin's ability to hook into "after-compile" and  "watch-run", but blessed from a loader perspective instead of a plugin. An api for reporting errors on modules that webpack doesn't know about would also help. I realize this blurs the lines quite a bit between plugins and loaders, but in the initial design goals I had for ts-loader I didn't want people to have to configure both so I used private APIs so that the loader could also act like a plugin.

I've thought in the past it would be cool if you could somehow "preload" a module manually. For example, say `a` depends on `b`, and there is some loader configured to run before TypeScript. The TypeScript loader could say "hey, give me `b` but already run through any other configured loader". This would help with the third issue.

Hope this gives some more perspective into some of the challenges, and I do appreciate you taking a new look at this.

**Comment by robwormald** [comment]
I'll second most of what @jbrantly said, it roughly describes the same issues I've been running into while building the Angular2 integration for Webpack.

Just to explain our use case a little bit further - Angular2 does ahead-of-time compilation, which involves a number of steps I'm having trouble integrating nicely with Webpack.

Take an Angular2 component like so:

```typescript

@Component({
  selector: 'my-component',
  templateUrl: 'my-component.html'
  styleUrls: [ 'my-component.css' ]
})
export class MyComponent {}
```

Our compiler ingests a component like this, and spits out a pre-compiled version of the component as a *new typescript file* - importantly, after compilation, we no longer need the original HTML and CSS as they have been written into the generated code.

So, like @jbrantly said, we're doing this at the program level - we're using Typescript's compiler APIs and have all of the complications he listed, with one additional one:

Our compiler allows a developer to pass in a Resource Loader, which allows me to intercept Angular's requests to fetch the html and css (or scss etc) files:

```
//ts setup
const compilerHost = createNgCompilerHost(tsConfig);
const program = ts.createProgram(files, tsConfig.compilerOptions, compilerHost)

const resourceLoader = {
  get(fileName){
    return readTheFileAsyncSomeHow(fileName)
  }
}

const codeGenerator = createCodeGenerator(program, compilerHost, resourceLoader);

codeGenerator.generate().then(generatedFiles => {})
``` 
The generated files then become the entry data into where I want webpack to take over and run its normal lifecycle. 

Ideally, `readTheFileAsyncSomeHow` should be my simple hook into webpack - i'd like to be able to use the webpack environment to load and transform sass etc files without invoking all the bundling machinery, but that's proved to be difficult.

**Comment by sokra** [comment]
Thanks for the detailed insight @jbrantly and @robwormald

**Comment by markfinger** [comment]
Mindful of the difficulties that a variety of persistent cache implementations have encountered, it may be worthwhile to use a callback or promise API for cache gets, eg: 

```js
this.cache([optionalIdentifier]).then(data => {
  // ...
});
// or 
this.cache(<null | optionalIdentifier>, (err, data) => {
  // ...
});
```

Immediate benefit would be enabling persistent caches with lazily evaluated reads from disk.

CC @mzgoddard @amireh

**Comment by amireh** [comment]
I second @markfinger's call for making `this.cache` an asynchronous API since the changes are moving towards dropping all synchronous loader APIs. However, I see how it can be awkward from the authoring perspective if one wants to manipulate multiple items. Perhaps we should have the API accept an array of identifiers, or leave it to the author to use something like `async` to aggregate them.

It just seems like the asynchronous API is a safer bet on both grounds and the author is provided with a number of ways of working around async awkwardness (which they probably already have to do for the other async APIs anyway.)

On another front, I think the term `cache` _may_ be a little misleading here given its nature (in-memory, process-bound) since one may think it to be persistent. Maybe any of `loaderDataBus`, `transientCache`, `memoryStorage` or `localStorage` would be more descriptive - this might be just me though.

---

Regarding `this.defer`. Seeing how we have a way to share data between different loaders (`this.cache`), I don't see why we can't make this a formal static hook like `pitch` is right now for loaders. The loader is free to share data with itself through different stages if it needs by utilizing the cache and the design would be simpler (both from the loader application and authoring perspectives.)

This would mimic the plugin phases that we already have in place and generally I just see it better to be statically defined than something that may be done during a loader's normal run by calling an arbitrary `this.defer()` callback.

If this is meant to address TypeScript loaders' use-case, they could then be doing their regular transformation process in the loader's "normal" hook (i.e.` module.exports`) then choose to do their program-wide error reporting at that static phase (e.g. `module.exports.seal` or something.) Unless i'm misunderstanding the use case of this, in which case I apologize. :smile: 

Personally I lean towards static definitions because it gives us more room when we do something like distributing the work. For example, in the context of happypack, I could freely choose to apply the `seal` phase of one loader in a different thread where its normal application has happened, assuming I provide it with the proper cache and other needed context. This would still be possible with the `this.defer()` callback approach but a little more complicated.

**Comment by jhnns** [comment]
I've encountered some of @jbrantly and @robwormald problems as well when working on the less- and the sass-loader. These problems typical arise when you're writing a loader for another language that needs to be compiled. Since these other languages bring their own module system, it does not fit well to webpack's concept where you look at each module individually and try to represent each module eventually as JavaScript module.

The problem is that these kind of loaders/plugins

- need to transform contents on a file basis
- need to report errors on a file basis
- but still have to maintain a shared state. The change in one file might affect the result in another file.

I'm feeling that the original concept of a loader that is a function which takes an input and returns something new does not fit here. These requirements ask for an API to register lifecycle events on a per-file basis and I'm not sure if we should extend the loader API or the plugin API to support this.

The `invalidate()` proposal seems pretty unefficient to me :(

Still need to think about it... but it's too late now :)

**Comment by amireh** [comment]
(Not sure if this is the right thread for this, if not I'll happily take it elsewhere.)

I would like to highlight one more request: can we prevent loaders from accepting non-serializable options? I realize this will be a rather breaking change for some loaders, but I'll give a real-case example of why this isn't a preferable thing.

Take a look at [postcss-loader](https://github.com/postcss/postcss-loader#plugins-packs) loader for example - they accept a list of plugins to apply in the form of a _function_ option passed to webpack on some arbitrary `postcss` key. If they were restricted to accepting primitive options via webpack, a solution would've been to require pairs of module paths and options (like webpack does for loaders) which we can serialize as normal and pass on to background threads.

For example:

```javascript
postcss: {
  plugins: [{ path: 'autoprefixer', options: { ... auto prefixer options } }]
}
```

Instead of what they do now:

```javascript
postcss: function() {
  return [ require('autoprefixer')({ auto prefixer options }) ]
}
```

See [this thread](https://github.com/amireh/happypack/issues/84) for some context. On my end, I can try to work around this by allowing people to define custom serializers for such options but build configs are already ugly and complicated...

**Comment by jhnns** [comment]
@amireh 's suggestion makes sense and should work pretty good with multiple processes. :+1: by me.

**Comment by Kovensky** [comment]
@amireh postcss's situation is made (much) harder by postcss's own plugins also having their own configuration files, and even inconsistent loading systems for their config files. For example, `autoprefixer` will look for a `browserslist` file in the currently processed file's directory or ancestor directories (like eslint). `doiuse`, on the other hand, will look for a `browserslist` file in relation to the CWD of the postcss host process (`webpack` in this case).

Also, from the point of view of a user, I actually find postcss-as-a-function useful as I need the same plugins, but a different `syntax` suboption depending on the file extension of the files I process or `@import`. However, the same thing probably could be accomplished with a `loaders`-like include/exclude syntax.

**Comment by jhnns** [comment]
> Also, from the point of view of a user, I actually find postcss-as-a-function useful as I need the same plugins

So you think that we can't get rid of functions stored in the webpack config?

**Comment by Kovensky** [comment]
@jhnns not quite; I think it's a "necessary evil" due to other limitations in the system, such as css-loader (or postcss plugins) being unable to request a file that goes through the full loader pipeline. A way to match input filename to postcss config could also be used.

This can't just be done by having separate postcss instances for each file type as that prevents e.g. sugarss from being able to `@import` css files and vice-versa.

**Comment by amireh** [comment]
@Kovensky 

From webpack's point of view, can't we simply pass a filepath to where postcss's config is exported? Sort of like we do for babel with babelrc. So,

```javascript
{
  loader: 'postcss?configFile=' + path.resolve('some/path/to/postcss.config.js')
}
```

Which then the loader is free to require and use the export. 

This would solve things on my part, because we can serialize strings and `require` will work in each child process the loader is applied in and yield a different instance with absolutely no interference from happypack or the user. The only part that needs to adjust for this is the loader itself.

Unless, again, I'm missing something vital as to why postcss can't do that. IMHO, if babel can do it then any other transformer should be able to as well, and following postcss's [ticket on the issue](https://github.com/postcss/postcss-loader/issues/88) I see they're headed towards that direction already.

The only thing I can think of which may make such a solution not possible is if those plugins are stateful and not pure, which I hope they're not (and webpack has the right to assume they're not, since it's a basic principle of loaders.)

**Comment by Kovensky** [comment]
That workaround would still not quite work for me as the config would only be `require`d once, but I need, essentially, a separate config with a different value for `syntax` depending on the file being loaded.

As for state, some plugins, especially plugins in the cssnext and precss suite, need access to the body of `@import`ed modules to be able to do correct processing. `postcss-custom-properties` is probably the easiest example.

While, in simple CSS, `css-loader` can just add whatever was `@import`ed to the dependency list and it will all work out at runtime, postcss would need to get the result of the webpack pipeline _before_ postcss to be able to do the appropriate substitutions in the result code.

CSS, as a language, is completely global, so there is no way to know what symbol is provided externally, even if there is an `@import`, without being able to access their bodies. This is why plugins such as `postcss-import` are still needed even with webpack managing `@import`.

They can't use the result of the file _after_ it has been `postcss`ed, as those same plugins will often, at least by default, delete the syntax they (think they) processed.

**Comment by jhnns** [comment]
@Kovensky I think I understand your problem, but I'm not sure if it actually relates to this discussion.

I don't know about the internals of postcss, but you should be able to write a loader that resolves the imports for postcss. Take a look at the sass-loader: [Here](https://github.com/jtangelder/sass-loader/blob/d894345fa509a10d4a3f3c8ef88a26cef4ea3366/index.js#L250) we're configuring node-sass to use webpack's resolving algorithm to resolve and read the imported files. You should be able to do that in the postcss-loader as well.
