### ISSUE TITLE
Question: Parallelized builds across threads?

### ISSUE THREAD

**Issue by amilajack** [webpack/webpack#2997]
Wondering what the Webpack's stance is on multithreaded builds.

**Comment by trxcllnt** [comment]
It's possible. We've wired up a build script that watches, communicates status to the main process, then restarts the dev server via [`spawn-rx`](https://github.com/paulcbetts/spawn-rx). [`parallel-webpack`](https://www.npmjs.com/package/parallel-webpack) is also a great option, but doesn't support watching because Promises are one-and-done.

The only drawback for us is that the webpack processes can't share memory, so features like css-modules will generate different module definitions for the same selectors for the client and server builds. This isn't a problem in dev mode (`style-loader` seems to be the way to go for hot-module-reloading, so the server-generated CSS is ignored anyway).

We run production builds (with `extract-text-webpack-plugin` instead of `style-loader`) in the same process so the style cache is shared across builds and we can afford the time.

**Comment by bebraw** [comment]
Yeah, solutions like parallel-webpack or [happypack](https://github.com/amireh/happypack) are the way to go at the moment.

This kind of questions might fit Stack Overflow better (see the issue template disclaimer).

**Comment by amilajack** [comment]
@bebraw my bad. Would be nice if parallelization would come built in. Are there any plans for this?

**Comment by bebraw** [comment]
I'm not aware of any official plans at the moment. It's probably better to rely on third party for the moment.

**Comment by amilajack** [comment]
Would a PR be welcome to add official support?

**Comment by bebraw** [comment]
@sokra @TheLarkInn Any thoughts?

**Comment by amilajack** [comment]
@bebraw @sokra @TheLarkInn On an unrelated note, does targeting 'node' add shims for node API's even though they are not necessary?
