### ISSUE TITLE
`--progress` no longer works for WDS because of a change in webpack

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack#3015]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.22 

**Current behavior:**

`webpack-dev-server --progress` or `webpack-dev-server --progress --profile` does not show a progress bar.

Also see https://github.com/webpack/webpack-dev-server/issues/609.

**Expected/desired behavior:**

It should show a progress bar using the parameters above.

Previously, WDS parsed their own parameters AND those from webpack, and because of that `--progress` works in WDS without any code. However, since 46b12b2095577391fbd88b6d29b7f0b858db4c5c (released in `2.1.0-beta.22`), the parsing of `--progress` has been moved to `bin/webpack.js`. This means that WDS can no longer access this, hence `--progress` no longer works.

@sokra, what was the reasoning behind that move? I could also implement this in WDS, but that would be inconsistent with the other parameters that are getting parsed by webpack.

**Comment by sokra** [comment]
The ProgressPlugin need to be applied on the MultiCompiler and not on the nested Compilers, when using multiple configurations.

This change moves it from Compiler to MultiCompiler.

We need to move the `--progress` definition from `bin/config-yargs.js` to `bin/webpack.js`.
And add `--progress` to the devserver.

That way it's at least consistent with `--json` and co, which are also webpack owned options.

The stats flag could be moved into a separate file so that they could be used by the webpack-dev-server.

**Comment by SpaceK33z** [comment]
> The stats flag could be moved into a separate file so that they could be used by the webpack-dev-server.

So if I understand it correctly, you're saying:

1. Move the yargs arguments with `group: DISPLAY_GROUP` to a separate file
2. In that file, also add the parsing logic for the display options, but without the JSON part. Essentially [these lines of code](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L193-L238).
3. Update WDS so it also parses those display options

**Comment by SpaceK33z** [comment]
Also fixed this in WDS:

https://github.com/webpack/webpack-dev-server/commit/5562fda6753c86db6f7b3861606d6d40d8d008d1
https://github.com/webpack/webpack-dev-server/commit/e3324ab419dc18ae7bdc8a7092b32d831ff86c90
