### ISSUE TITLE
The cache mechanism in _webpack_require__ function may break if importing with a same exporting module

### ISSUE THREAD

**Issue by jumperchen** [webpack/webpack#3088]
#**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
The module imported from '../../index' in the \__webpack_require__ cache may break if a class defined in a nested exporting module.

For example,
```
// module/index.ts
export * from './Root';
export * from './subModule/index';

// module/subModule/index.ts
export * from './src/BranchA';
export * from './src/BranchB';

// module/subModule/src/BranchA.ts
import {Root} from '../../index'; // this will exclude BranchA class itself in Browser environment.

export class BranchA {
	// omitted
}

// module/subModule/src/BranchB.ts
import {Root, BranchA} from '../../index'; // the BranchA in this importing path is undefined in Browser environment.

export class BranchB {
	// omitted
}
```

This issue won't happen in a simple project, but in our complex project, it did happen.
BTW, the same usage can work well in Node environment without any issue.
**Expected/desired behavior:**
1. The importing module '../../index' should contain the BranchA class itself after exporting the class.
2. The BranchB should be able to access the BranchA class from the same importing module '../../index';

 
* **Browser:** [all] 
 
* **Language:** [ES6/7]

**Comment by jhnns** [comment]
Thanks for reporting this. 

It would be extremely helpful if you could setup a small example project that demonstrates the issue. Please don't use typescript in this example project so that we can narrow it down.

It looks like you cannot reproduce it reliably, is that correct?

Also keep in mind that webpack 2 removes unused code. As long as `BranchB` is not using `BranchA`, it will be excluded.

**Comment by jumperchen** [comment]
Yes, it's hard to reproduce this issue in a simple project, I will try to make a runnable example if possible.

In our case, the BranchB will be used, so the BranchA in the BranchB is still undefined, however, the workaround is to import the BranchA by using the following syntax
```
// eithor
import {BranchA} from '../index'; // subModule's index file
// or
import {BranchA} from './BranchA'; // use it directly
```

**Comment by jumperchen** [comment]
This is a runnable project to reproduce this issue - https://github.com/jumperchen/webpack-issue
Please don't check the usage of the code whether is reasonable or not, it just shows up the issue only.

**Comment by sokra** [comment]
I'm pretty sure it's an circular dependency issue.

**Comment by sokra** [comment]
And working as expected

**Comment by sokra** [comment]
See #3100

**Comment by jhnns** [comment]
Yep. `BranchA` and `BranchB` have both a circular dependency on `module/index.ts`. Therefore, `BranchA` must be `undefined` as long as `BranchB` is not executed and exported.

Although circular dependencies are generally supported by the module system, it's best to avoid them where possible because it couples both modules tightly together. In fact, most of the time, they can be avoided.
