### ISSUE TITLE
Can't access "process.env" variables in index.html or other html files

### ISSUE THREAD

**Issue by darkylmnx** [webpack/webpack#3105]
How can i get / access webpack ENV (process.env) variables during process time (not runtime in browser) ? the webpack.DefinePlugin(...) doesn't seem to work in html files, i don't have access to ENV variables in the main index.html

any solution ? is it normal ?

**Comment by wcjordan** [comment]
I'm assuming you're using something like HtmlWebpackPlugin since you reference process (build?) time, not runtime.  To work around similar issues, I've configured my plugin like:

`
Object.assign(pluginConfig, config);
return new HtmlWebpackPlugin({
    vendorsFilename: process.env.NODE_ENV === 'production' ? 'vendors.min.js' : 'vendors.js',
    inject: false,
    hash: true
});
`
or replace with any other boolean logic if your DefinePlugin assignment doesn't match the build time env.

Then in my HTML template I'll do something like:
`
<script type="text/javascript" charset="utf-8" src="static/<%= htmlWebpackPlugin.options.vendorsFilename %>"></script>`


P.S. Webpack uses github issues for tracking bugs with webpack.  For questions like this, please prefer StackOverflow.

**Comment by darkylmnx** [comment]
@wcjordan well i thought this was more a bug than a question since 
`
conf = {
  NODE_ENV: '"production"'
}

new webpack.DefinePlugin({
  'process.env': conf
})
`
gives access to NODE_ENV in any of the js file `src/` of the webpack project but not in html files.

With what you said above, can i access NODE_ENV in the index.html main file of the project ? it doesn't seem to be the case in mine

**Comment by wcjordan** [comment]
I don't think what you're asking is a bug nor a supported use case.  Webpack doesn't expect you to be exposing global variables for the main html file to access.  You could try making a "var" build using the [output.libraryTarget config option](http://webpack.github.io/docs/configuration.html#output-librarytarget) and exporting the desired values, but I'm not sure what the use case for that would be.

Either way I recommend switching to SO, you'll likely get more help there.

**Comment by bebraw** [comment]
Yeah, please re-open at Stack Overflow for more ideas. I would recommend looking into html-webpack-plugin.

**Comment by darkylmnx** [comment]
The use case would be for exemple, adding an API KEY to a script src.

`<script src="https://api.google.com/maps.js?key={{ API_KEY }}"></script>`

**Comment by bebraw** [comment]
html-webpack-plugin and a custom template can definitely do that.

**Comment by rapid227** [comment]
The simple way you can use 

in HTML 
`<p>%NODE_ENV%</p>`

and in script
`<script type="text/javascript" charset="utf-8" src="static/'%NODE_ENV%'==='production'?'vendors.min.js':'vendors.js'"></script>`
or 
`<script>
if('%NODE_ENV%' === 'production') {
.... some code
}
</script>
`
