### ISSUE TITLE
Bundling webpack through node

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#3143]
Hi! Sorry for polluting the issue thread. I'm trying to make a interactive `webpack` tool in terminal. This runs in shell, naturally, but I've run into some issues when setting up the `webpack.config` file based on user input. Is there a neat way to set up a  `webpack` config that you know of or can refer me to? The problem now, is that, as I'm running in the context of the bash, I can't export variables to the `webpack.config` I want to build up. 

I can elaborate if you want me to go more into specific or rephrase!

**Comment by bebraw** [comment]
Can you push what you have together somewhere and highlight the problem spot there? That would help to understand the problem in greater detail.

**Comment by ev1stensberg** [comment]
![skjermbilde 2016-10-15 kl 18 57 23](https://cloud.githubusercontent.com/assets/16735925/19411835/3f5160f8-9309-11e6-94fb-a85c545f7a7b.png)

At the end, you see the config required. But a traditional webpack file will cause an error. I want to build up a config here, based on the questions user answers. 

Any tips?

**Comment by bebraw** [comment]
One problem is that webpack configuration isn't serializable. You can end up having functions there (postcss is a good example), also plugins are problematic (rely on `new`).

Maybe it would be better to use a templating approach (think handlebars), process through templates, and write the configuration based on that.

This isn't the easiest problem due to that serialization problem. If the configuration was serializable, then going from configuration to JavaScript and back wouldn't be an issue. Now you need to figure out a way around it.

**Comment by ev1stensberg** [comment]
can I somehow use JSON.parse or something and parse it back? Thanks for the input!

**Comment by bebraw** [comment]
Nope. That's what I was explaining above. You have to find some other way.

**Comment by ev1stensberg** [comment]
could to a writable stream and store it all in a string? :) Either way this seems flawed in the terms of good written code. Should rework and patch together these as small scripts instead and have the cli at a higher order or something like that. Thanks for helping @bebraw !
