### ISSUE TITLE
Ability to start the watcher without performing an initial build

### ISSUE THREAD

**Issue by victorporof** [webpack/webpack#3190]
**I'm submitting a feature request**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Both in the CLI and in the API, as far as we know, there's no way to start watching sources without also performing an initial build.

**Expected/desired behavior:**
We'd like to have such an API.
- **What is the motivation / use case for changing the behavior?**
  In our project, we're hashing sources to avoid recompiling everything when performing an initial build when nothing has changed, however obviously future changes to the sources should be, indeed, handled. Due to the nature of our application, frequent restarts in development mode are common.
- **Browser:** none, this is a API-only feature request
- **Language:** ES6/7

**Comment by begincalendar** [comment]
@victorporof I know nothing about the mozilla/tofino project, but after a quick skim through the relevant code, it seems as if y'all have implemented a custom mechanism to determine whether a Webpack build should be performed or not, based on whether certain files have changed or not.

Is/Are there any particular reasons why that project is taking that approach, as opposed to just running `webpack --watch ...`, leaving that be and achieving the same result?

The only reason I can think of is that you don't want to leave the command invocation running, but then you created this issue to start the watcher independently of the transpilation.

Anyway... I came across this issue because I am doing what I alluded to, i.e. leaving the `webpack --watch` running.

The problem with that is that Webpack just resolves and watches files based on the ones that existed upon the initial command invocation and doesn't pick up newly added files.

I think it would be handy if Webpack could "re-scan" for resolvable files when new files are added/deleted, but I'm not sure if this is related to what you are after.

All of this seems like it might be related to me and plus I'm curious as to why y'all are doing things that way, so I thought I would start here, before creating a new issue.
