### ISSUE TITLE
Documentation or any info on webpack 2

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack#3275]
Looking at the release page one can see that version 2.1.0 is well under way.

Meanwhile:

- webpack website carries no version info and is apparently 1.x only
- the `master` branch is apparently 1.x (if you trust the npm badge, there's no other version info in the README)
- there are no announcements, news or documentation referring to 2.x

The most obvious question is, of course: how can a project be 2.1 when there's exactly 0 readily available information on 2.x?

However, I'll rephrase it and ask for the following:

- update docs to clearly state which version of webpack they refer two
- create page clearly detailing what 2.x is, how to get it etc.
- update docs to reflect changes in plugins, loaders etc. (there are already people asking how to use, say, `LoaderOptionsPlugin`, see comments [here](https://webpack.github.io/docs/list-of-plugins.html)
- move information on webpack 2.x from gists, unfinished pages and Google docs (really?? really?? google docs????) to the place where they can be easily viewed and accessed by everyone

Unless, of course, webpack 2 is just a testbed and is not intended for public use

**Comment by sokra** [comment]
* https://webpack.github.io/docs/ <- webpack 1 documentation
* master branch is webpack 2. See package.json for a version number.
* https://webpack.js.org/ <- webpack 2 documentation (WIP)
  * This will be the only source of truth. All gist/docs content will move here.
  * We are working on this, to have it ready for release.
* We use google docs for internal notes, they are not intended for public use (they may are public, because it's an open source product)
* You are invited to help publishing more information about webpack 2 -> The webpack 2 page is open-source: https://github.com/webpack/webpack.js.org Just write the content, that you feel is missing.

**Comment by dmitriid** [comment]
> master branch is webpack 2. See package.json for a version number.

The README specifies no version. The badges show version 1.x. All links are to the 1.x documentation.

For all intents and purposes the master branch is version 1.x

> https://webpack.js.org/ <- webpack 2 documentation (WIP)

Which of the public docs for webpack contain a link to this website?

> We are working on this, to have it ready for release.

When is the release? The project seems to have been released (it's already approaching 2.1). Yet there are no available timelines, no announcements, all info is scattered in multiple places and, well, I had to open this issue just to learn that webpack.js.org even exists.

> We use google docs for internal notes, they are not intended for public use (they may are public, because it's an open source product)

And yet, this is the only publicly available roadmap for the project (https://webpack.github.io/docs/ -> Roadmap). There's also a gist somewhere

> Just write the content, that you feel is missing.

I feel that all content is missing. Because the only info about this website is available in this issue. For all intents and purposes webpack.js.org doesn't exist:

- The README links to https://webpack.github.io/docs/
- https://webpack.github.io/docs/ links to other pages within https://webpack.github.io/docs/
- Google Search points to https://webpack.github.io/docs/
- The repo description links to https://webpack.github.io/docs/

**Comment by dmitriid** [comment]
Basically, to rephrase again.

<hr />

Complaint: "update docs to clearly state which version of webpack they refer too"

Answer:
> https://webpack.github.io/docs/ <- webpack 1 documentation
> master branch is webpack 2. See package.json for a version number.
> https://webpack.js.org/ <- webpack 2 documentation (WIP)

Counter-complaint:
- the website for 1.x doesn't display a version anywhere
- master branch advertises itself as 1.x. Looking into `package.json` *is not* clear information
- the website for 2.x doesn't display a version anywhere 

<hr />

Complaint: create page clearly detailing what 2.x is, how to get it etc.

Answer:
> master branch is webpack 2. See package.json for a version number.
> https://webpack.js.org/ <- webpack 2 documentation (WIP)
> This will be the only source of truth.
> You are invited to help publishing more information about webpack 2 -> The webpack 2 page is open-source: https://github.com/webpack/webpack.js.org Just write the content, that you feel is missing.

Counter-complaint:

However you search for it, the only information you get on webpack / webpack 2 are:
- the 1.x docs
- the github repo which advertises 1.x
- a link to a roadmap on Google Docs

Nowhere is there a clearly stated section/page/sentence:
- saying what webpack 2 is
- that its docs are moved to a different WIP website, with a link to the website
- the timeline (however tentative) for the release

<hr />

Sorry if I sound bitter/aggressive. It's just I've been trying to find info on Webpack 2 and have come up with nothing *repeatedly*. And I don't often have the time to sift through [references](https://www.google.com/search?rls=en&q=%22webpack.js.org%22&ie=UTF-8&oe=UTF-8#q=%22webpack.js.org%22+site:github.com) in a pull request to a non-linked repo somewhere.

**Comment by sokra** [comment]
webpack 2 has not been released yet -> no link yet.

The old docs have no version number, because there is currently only one release version (1.x).

We try to update all the stuff until/for release.

@bebraw Could you add the complaints to the doc MVP?

**Comment by mnasyrov** [comment]
I'm agree with @dmitriid, it's so difficult to find info about webpack2 (changelog and roadmap in particular). While webpack2 is in beta more and more teams have started using it (e.g. angular-cli, ionic2 and guys who use them). People can't wait for a final release, we want try and use it now and grow projects along with webpack2 :)

By the way, there is a huge discussion about this theme already: #1545.

**Comment by dmitriid** [comment]
@mnasyrov Thank you for the link to the issue!

@sokra 

> webpack 2 has not been released yet -> no link yet.

How do you expect people to find out about it and help you with it? I think this comment perfectly summarizes the frustration: https://github.com/webpack/webpack/issues/1545#issuecomment-255618736 There's a reason this comment has 34 votes

**Comment by dmitriid** [comment]
Also. Today I learned (in a comment to an issue somewhere) that there's an official webpack blog. Not a single public webpack resource points to the blog: not the old documentation site, not the new documentation site, not the README.

**Comment by donaldpipowitch** [comment]
There is an official blog?

**Comment by dmitriid** [comment]
@donaldpipowitch https://medium.com/webpack

I was very surprised to discover it as well :)

**Comment by donaldpipowitch** [comment]
I think there is _a lot_ of value in the things @dmitriid and [#1545 (comment)](https://github.com/webpack/webpack/issues/1545#issuecomment-255618736) said.

I _do_ know @sokra, @bebraw, @TheLarkInn and others are working hard on webpack@2 itself _and_ the docs. But in my opinion some statements are a little bit weak (no offense!).

> webpack 2 has not been released yet -> no link yet.

It _is_ released. It is released with more than 30 beta versions. Docs for webpack 2 could be labeled as beta versions themself _or_ a lack of docs for version 2 could be made explicit until version 2 becomes stable (however that would not be true - there are a lot of (beta) docs about version 2).

> The old docs have no version number, because there is currently only one release version (1.x).

Well 1.x _is_ a version number. Why not add this to the docs? _"Hi, these are the docs for webpack@1. New docs for webpack@2 will be released at a later time."_ As far as I know _many_ people use webpack@2 even if it is a beta for several months. Why not make the difference clear in the docs for everyone?

Things like that could be added to the README.md as well. IMHO the current README.md should be _all_ about webpack@2 and not about webpack@1 anymore. I personally would add a note to the README.md on master similar to this:

```
## Attention: Webpack 2 Beta

Hi,

we're currently working on webpack@2. While it is in a beta phase we recommend to only use fix versions of webpack@2 as every beta release could break your build. If you're looking for documentation of webpack@1 you can visit [the branch `webpack-1`](https://github.com/webpack/webpack/tree/webpack-1) or https://webpack.github.io/.

Docs for webpack@2 will be released on https://webpack.js.org/, but they are currently in a beta phase, too. 
```

If development for webpack@2 happens on `master` the README.md should reflect this (imho).

Maybe an additional point for docs MVP:
- List of all communication channels. (https://medium.com/webpack was new for me and I just asked [yesterday](https://twitter.com/PipoPeperoni/status/798193665604718592) about an Twitter account. The docs could link to the correct blog and could say that a Twitter account is planned, but currently available, because the name is taken.

I would _love_ to see stats about how many people download v1 and v2 last week, to _really_ find out if _"webpack 2 has not been released yet -> no link yet."_ is an important argument. As long as it is public and released in beta version it _is_ released (imho). Sadly it looks like I can't get the data about that currently: https://github.com/npm/download-counts/issues/6 :(

And if you _really_ want to point out that _"webpack 2 has not been released yet"_ and maybe shouldn't even be used, it should be the first line on the current README.md.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/pull/3293/files#diff-04c6e90faac2675aa89e2176d2eec7d8R20

**Comment by donaldpipowitch** [comment]
Thank you @sokra. Small changes like these have a lot of value. Thanks.

**Comment by dmitriid** [comment]
Thank you!

**Comment by SpaceK33z** [comment]
So in the past months we have fixed most of the issues:

- README of webpack/webpack repo clearly states that it is for v2 with link to v1.
- webpack.js.org states what version it is for. There is an open PR to clarify it more in the getting started guide (https://github.com/webpack/webpack.js.org/pull/546)
- webpack v1 docs [clearly states that it is for v1](https://webpack.github.io/docs/).

@dmitriid, are you satisfied with this? If so, can you close this?

**Comment by dmitriid** [comment]
Awesome!

Minor issues: 
- repo description points to webpack.github.io (don't forget to change it after the release!)
- official blog visibility is still close to zero. There's a separate issue for this as well in webpack.js.org repo. This is a shame, as news like [this](https://medium.com/webpack/webpack-2-2-the-release-candidate-2e614d05d75f#.t23mwfu9f) are very important. Other than slapping a link "follow news on blog here" in readme and v1 docs landing page, I don't know how to raise the visibility of the blog :(

However, we can definitely  close this particular issue, as the major problems have indeed been resolved.

Woohoo!

**Comment by dmitriid** [comment]
Forgot to colse the issue. Closing it now.
