### ISSUE TITLE
Webpack is breaking npm ssh2 module

### ISSUE THREAD

**Issue by renegadeandy** [webpack/webpack#3332]
Hi,

I want to use the ssh2 pack from https://www.npmjs.com/package/ssh2 in my Electron app inside an angular 2 service.

I found that it didn't work out the box - which was strange because all other npm packages just 'worked' including an FTP module.

I come here after this stack overflow post, and a followup issue on the ssh2 package github :

http://stackoverflow.com/questions/40646733/using-npm-package-ssh2-within-an-angular2-application-running-under-electron?noredirect=1#comment68563936_40646733

And this ssh2 issue:

https://github.com/mscdex/ssh2/issues/502

The ssh2 package maintainer suggested I added an issue here to see if you guys on the webpack side can help at all, because I think he has run out of ideas on what he can do to fix it.

Any and all support would be very graciously received.

**Comment by SpaceK33z** [comment]
Okay so the issue is our implementation of the EventEmitter is not as expected. The package [node-libs-browser](https://github.com/webpack/node-libs-browser) provides those polyfills. You could make an issue there, or add a comment to https://github.com/webpack/node-libs-browser/issues/44. It seems like there are more problems with that implementation.

**Comment by mscdex** [comment]
I'm not sure I'm convinced that's the issue. I looked into it and the current EventEmitter implementation used by `node-libs-browser` has included `return this` in its `.on()` implementation ever since its first release back in 2011. `node-libs-browser` has used that same EventEmitter implementation since `node-libs-browser` v0.5.0 (released in March 2014) and before that it used its own in-house implementation which *still* had `return this` for its `.on()` implementation.

This is what has me confused. With all of this evidence I cannot see how it is possible for `.on()` to return `undefined`.

**Comment by renegadeandy** [comment]
Why is this issue closed - it is not fixed!

**Comment by SpaceK33z** [comment]
Please provide more information to confirm that this is really a webpack bug.

**Comment by renegadeandy** [comment]
What would you like from me!

**Comment by renegadeandy** [comment]
@mscdex maybe you can help here?
