### ISSUE TITLE
Watch mode not working for newly added file

### ISSUE THREAD

**Issue by zxx714** [webpack/webpack#3357]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Watch mode not working for newly added file

**If the current behavior is a bug, please provide the steps to reproduce.**

I used the webpack demo in angular2 website and added the watch mode in build script, source: https://bitbucket.org/zxx714/angular2-webpack

And run the build. After it had finished bundling, I added a ts file into the app directory, but the webpack could not detect the change to work. I have tried a js file, neither does it. 

**What is the expected behavior?**
Watch mode when building can detect the added file and work

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack version:1.13.3
node version:7.1.0

**Comment by SpaceK33z** [comment]
Could you try using Node.js v6? There are lots of issues with Node.js v7 and watching unfortunately in chokidar, also see https://github.com/paulmillr/chokidar/issues/550.

**Comment by SpaceK33z** [comment]
webpack will only rebuild when you `require` a file, not when you add a file to a directory. This is a feature. At least in your description of this issue it seems like you are only adding the file to the directory.

Also, in your `package.json` (found in your repo), you have `--watch` AND `--bail`. You probably don't want both of those, since with `--bail` it stops the process after the first error.
