### ISSUE TITLE
Removal of DedupPlugin

### ISSUE THREAD

**Issue by patrickhousley** [webpack/webpack#3463]
Why was the dedup plugin deprecated? Without it my build is several kb larger.

**Comment by sokra** [comment]
Use `npm dedupe` instead.

**Comment by farism** [comment]
I'm currently trying to switch a project over to a monolith using lerna. The issue I'm running into is that `npm dedupe` is meant to work with a very specific structure with top level node_modules. With the following structure I think having the dedupe in webpack makes more sense:

```
.
│──node_modules
│  └───some_dep_v1
│──packages
│  └───package1
│  │   └───node_modules
│  │   |   └───some_dep_v1
│  └───package2
│  │   └───node_modules
│  │   |   └───some_dep_v2
```

`some_dep_v1` is being included in bundle twice. `npm dedupe` will not solve this issue. Furthermore, the deeper modules depended on by both `some_dep_v1` and `some_dep_v2` will also be duplicated. I believe that this should be solved at the build level and not the dependency manager level.

Any thoughts @sokra?

**Comment by sokra** [comment]
> I believe that this should be solved at the build level and not the dependency manager level.

I believe this should be solved on dependency manager level. But they can't optimize it yet.

maybe propose `lerna dedupe` that moves common dependencies `some_dep_v1` to the parent if compatible...

**Comment by patrickhousley** [comment]
Thanks @sokra.

**Comment by farism** [comment]
Thank you for replying!

RE resolving at the build level, it seems that we just disagree there. It seems some of the core contributors to lerna oppose this is well.  https://github.com/lerna/lerna/issues/334

I think the reason that I disagree with handling at the dependency manager level (at the moment) is because currently npm is really only meant to work with a traditional node application with a top level node_modules file. I think there are too many potential variations on how someone could structure a monolith repo, and npm can't possibly handle all of them.

I realize there is yarn (and even plans to merge lerna into yarn) so I think you are right, eventually it can be handled at the dependency manager level. But for now with the current state of tooling, I think maybe the most flexible approach would be to have the dedupe plugin available, because then we did customize it. 

Of course we could always fork it as a standalone plugin as well.

**Comment by maciej-gurban** [comment]
@farism Have you had any luck resolving the issue?

**Comment by farism** [comment]
@maciej-gurban We've switched to using Yarn workspaces and webpack 3 has been fine.
