### ISSUE TITLE
Thoughts on language integration into module system

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#355]
I'm considering different ways to have language packs loaded asynchronously using webpack.  I'm thinking that I could do something similar to my last solution in #309 (note the [] around the module name and the absence of the callback function).

I'm not sure if I want the actual language data to be stored inside the module but I want changes to the language data to trigger a build operation.  So I'm unsure how webpack watches files and if the watches will link across the file system.  Of course I could check this but its probably an easy question for ehm, someone to answer.

Additionally I could perhaps do some hacky stuff to have as many themes chunks built as there are languages and this would prevent an extra call to the server but would increase the initial build time by a noticeable amount.

I'm considering sharing a lot of message strings between the PHP and JS code but I don't know if that is practical.  That is another matter.

Is there a MagicalPlugin for me?

**Comment by dschissler** [comment]
Solved.  Use po-loader:

* [github](https://github.com/perchlayer/po-loader)
* [npm](https://www.npmjs.com/package/po-loader)

**Comment by StoneCypher** [comment]
po loader is pretty dramatically limited, and does not support the emerging JS internationalization standard.  PO is decades old and radically behind the strawman standard.  My strongly held opinion is that this should not be considered to be a solution.

**Comment by sompylasar** [comment]
@StoneCypher :+1:

**Comment by dschissler** [comment]
@StoneCypher I haven't perceived the limitations yet.  Would you care to list them?

**Comment by dschissler** [comment]
> po loader is pretty dramatically limited

I'm able to do some pretty nice things with it though.  I have map that allows me to make a fallback for languages in case that the full locale for the country code is not available.

From my [Webird](https://github.com/perchlayer/webird) project.

`app/locale/config.yml`
```yaml
---
default: en_US
map:
  en: en_US
  ru: ru_RU
  de: de_DE
...
```

My locale module:
```coffee
'use strict'
# system
Jed = require 'jed'
# configuration
localeConfig = require "#{LOCALE_ROOT}/config"

localeDefault = localeConfig.default
map = localeConfig.map

langRaw = window.navigator.userLanguage || window.navigator.language
langParts = langRaw.replace('-', '_').split('_')
# The Locale consists of a language and country
language = langParts[0]
country = if langParts.length > 1 then '_' + langParts[1].toUpperCase() else ''
# Set full locale
locale = "#{language}#{country}"

# There is only one variable here and it Webpack expands its search using a regex
# to find all of the messages. The constant LOCALE_ROOT is evaluated at compile time
getLangLoader = (locale) ->
  bundleLoader = require "bundle!#{LOCALE_ROOT}/#{locale}/LC_MESSAGES/messages.po"
  return bundleLoader

i18n = null
module.exports =
  gettext: (message) -> i18n.gettext message
  ngettext: (msg1, msg2, n) -> i18n.ngettext msg1, msg2, n

  init: (loadApp) ->
    # Try to load the locale specified by the browser. Webpack will throw an exception
    # if it does not exist since it has been required with a regex.
    try
      waitForLangChunk = getLangLoader locale
    catch eLocale
      localeNext = if map.hasOwnProperty(language) then map[language] else localeDefault
      waitForLangChunk = getLangLoader localeNext

    waitForLangChunk (messages) ->
      console.log messages
      i18n = new Jed messages

      loadApp()
```

**Comment by StoneCypher** [comment]
@dschissler - no gendering.  rudimentary pluralization support.  no nested rules (pluralization works differently in some languages for formal vs informal, eg.)  only a handful of language tweaks.  no explicit support for most of the stuff in the unicode cldr.  no support for dates, in either direction; times, in either direction; money.  terrible number formatting.  essentially every improvement over .PO made by XLIFF, ICU, or .RES.  extreme difficulty of multiple locales in a single context (which is quite commonly needed.)  no character set exposure (try getting a spanish speaker and a portuguese speaker to agree on the sorting of a dictionary.)  no collations.  no handling of script information.  no bcp47 support.  no plural casing.  no trans-group pluralization (eg whether to use "people" or "persons" away from the digit later when switching between british and american english.)  no group singular (an american hears "people" as plural, because it's many items; a british person singular, because it's one group.)  no color localization (green for good and red for bad are wrong in half the planet.)  no mechanism for closing resolution (if you have US english and UK english, which one do you give to a Canadian, which to an Australian, and which to a Chinese speaker who only nominated the language root?)  no 639, no 15924, no 3166, and no un m.49.  no external tagging (some professions and some religious titles cause conjugation in languages, eg sensei/sempai in japanese, or doctor in english.)  no opportunity to add custom tagging.  no ability to estimate locale from broswer settings or geo-whatever.

lots of other stuff too.  that's just what i can come up with off the top of my head.  i can be more detailed if you want.

i think probably the big one to me, though, is that the strawman standard is due to be directly supported in browsers and node.  po requires support libraries and always will.

**Comment by StoneCypher** [comment]
that is, the strawman standard is the upcoming javascript official approach.

so standardizing on something else seems really weird to me.

**Comment by StoneCypher** [comment]
jed exists to help an existing author's other-language system reach the web.

the new data format is basically a deep json tree.

http://wiki.ecmascript.org/doku.php?id=strawman:i18n_api&rev=1280420664

there is tooling for it.  the reason it's sort of rare is because they're shims: the browsers are expected to handle it natively, and soon.  however, people are producing shims so that they can get ahead of the game.

the reason it's not in browsers yet is the standard hasn't 100% officially crystallized.  there have been no meaningful changes to it in over a year, and it's expected that the current shims are actually complete.  mostly it's neckbeard wars over fine details (particularly how to parse dates and expose extra-national names, eg japanese name order in an english context) at this point.

the most popular shim implementation, which facebook, yahoo, and some of microsoft use in production today, is `Intl.js` [github](https://github.com/andyearnshaw/Intl.js/).  however there are others too.

**Comment by StoneCypher** [comment]
I mean if you choose to standardize around `.PO` because you're out of time, it's not a catastrophe.  People will just work around it.

But I think it's pretty solidly the case that `.PO` for web use is not a thing and isn't gonna be.

Either way, props for getting on something like this.  Very few tool vendors care about i18n.  :trophy:

**Comment by StoneCypher** [comment]
if you're looking for implementations, it's useful to know that this goes under a *ton* of names.  javascript i18n, strawman i18n, ecma 402, tc39, et cetera.

**Comment by dschissler** [comment]
@StoneCypher thanks for the detailed information.  While now I don't at all doubt that this is ultimately the way to go its my impression that the current situation is a epic cluster f**k that won't be resolved for at least a few years.  I'll be working on deciphering the scrolling spec sheets in the meantime and hoping for something not aimed at the people writing the spec themselves.  Hell, if you are so up on it you could probably make some pretty good money for years to come by writing a series of articles on the matter with Google Ads on them.

**Comment by jhnns** [comment]
@StoneCypher Thx for the detailed overview. I18n is a mindfuck, I've been researching this topic several times and was surprised, that there are so little resources (and tools) about it – given that it *should be* a problem every software has to deal with.

**Comment by dschissler** [comment]
@jhnns My business partner thinks that I've spent too much time on my PO solution and I've come to find out that I'm a localization baby.  What a time waste its been from dashes to underscores - the works.  Currently I'm trying to convince my Ukrainian localizer who speaks five languages with a linguistics degree that she could be making six dollar figures with this stuff.  Its epic craziness.

**Comment by StoneCypher** [comment]
@dschissler , @jhnns - the situation is *essentially* resolved right now.  The best thing to do IMO is to accept the JS strawman standard.  It's final-ish, it's where the web is going, two of the big four browsers already do it, a third probably does, and both node and io.js have stated it's their intent.

If however you're out of time, that's understandable.

**Comment by jhnns** [comment]
>  It's final-ish, it's where the web is going, two of the big four browsers already do it

That are good news indeed :+1:
