### ISSUE TITLE
Global variable problem with `library`

### ISSUE THREAD

**Issue by boringer** [webpack/webpack#3560]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

(Code below) After bundled, I import `mylib-bundle.js` by `<script>`, and I see my expected object is wrapped by a property `default`, which means I have to use something like `mylib.default.fn1` to access its properties.

However, if I change `export default` in `mylib.js` to `module.exports =`, it works well.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// mylib.js

import fn1 from './fn1';
import fn2 from './fn2';

export default {
    fn1,
    fn2
};



// Part of webpack.config.js

{
    entry: 'mylib.js',

    output: {
        filename: 'mylib-bundle.js',
        library: 'mylib',
        libraryTarget: 'umd', // Or 'var' by default
        umdNamedDefine: true
    
}
```

**What is the expected behavior?**

```html
<script src="mylib-bundle.js"></script>
<script>
    mylib.fn1(); // Not `mylib.default.fn1();`
</script>
```

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

- Windows 10
- Node 7.2.0
- Webpack 2.2.0-rc.2

**Comment by egoroof** [comment]
The same here. I thought `umd-module` should help with it but see #3559.

**Comment by sokra** [comment]
`export default` export it with the name `"default"`.

You may want to use this instead:

``` js
export {
    fn1,
    fn2
};
```

**Comment by egoroof** [comment]
@sokra but what if I export single class?

i.e:
```js
export class ID3Writer {
}
```

Using `umd` module with name `ID3Writer` I have to call constructor like this: ID3Writer.ID3Writer() but why not just ID3Writer()?

**Comment by boringer** [comment]
@sokra 

If use that instead, I have to import like this:

```javascript
import * as mylib from './mylib-bundle';
```

This is not very nice. According to standard, `export default` is used to make things simpler, and then I can use `import mylib from './mylib-bundle'` to import it, which is an alias of `import { default as mylib } from './mylib-bundle'`.

For example, these styles are the same behavior:

```javascript
// ES Module
import $ from 'jquery';

// CommonJS
const $ = require('jquery');
```

```html
<!-- Tag -->
<script src="jquery.js"></script>
<script>
    $; // Does't need `$.default`
</script>
```

**Comment by sokra** [comment]
That's how the ES2015 module spec work.

``` js
export class ID3Writer {}
```

### with `{ library: "ID3Writer", libraryTarget: "umd" }`

``` js
import { ID3Writer } from "./mylib-bundle";
```

``` html
<script src="mylib-bundle.js"></script>
<script>
    new ID3Writer.ID3Writer();
</script>
```


### with `{ library: undefined, libraryTarget: "umd" }`

``` js
import { ID3Writer } from "./mylib-bundle";
```

``` html
<script src="mylib-bundle.js"></script>
<script>
    new ID3Writer();
</script>
```

**Comment by egoroof** [comment]
> library: undefined

omg, looks very strange for me, but anyway thanks for explanation

**Comment by sokra** [comment]
just omit the `library` options. I used `undefined` to make it clear...

**Comment by QuentinRoy** [comment]
Just to clarify, it is now impossible to build a UMD library that can be directly required with commonjs (`var foo = require('mylib')`, which should also make `import foo from 'mylib'` possible with webpack) and set to the right browser global value (e.g. `MyLib` as specified) except if one is ready to forget about tree shaking and es6, is it?
I do not want to complain the above looks exactly as one would want a library to be bundled so that it can work efficiently whatever the user is using...

**Comment by boringer** [comment]
@QuentinRoy 
I've realized something wrong with my understanding, so I closed this issue. I want to delete it but there's no way to.

Thanks a lot to everyone, sorry for wasting your time.

**Comment by QuentinRoy** [comment]
@boringer No there is something very inconvenient in the way webpack is currently dealing with UMD bundling which, IMHO, makes it mostly useless.
The main reason is that webpack "dumbly" wraps whatever is exported when you use UMD target (except for the odd global loop thing @sokra was talking about earlier, I am not too sure why there is an exception here).
If you use ES6 (the only way to leverage tree-shaking), you can only export ES6 modules (previous version allowed you to export commonjs even from ES6 modules but that is now forbidden). As a result, you end wrapping an ES6 modules in a UMD wrapper. In my opinion it does not make much sense as the whole point of UMD is to make your library usable using different module system. I would have expected webpack to adapt the module instead of just wrapping it...

**Comment by egoroof** [comment]
@QuentinRoy yeah, I was exporting commonjs and importing ES6 modules, and now since rc4 I switched to import commonjs, because what you say about how libraries should work is true.
