### ISSUE TITLE
Discourage mixing CJS and ES6 module syntax in docs

### ISSUE THREAD

**Issue by wyuenho** [webpack/webpack#3571]
Experience has shown that it is easy to fall into a trap like this:

```javascript
// a.js
module.exports = function foo () {};

// b.js
import a from './a.js'; // error, no default member found in a
a.foo();
```

Much code has been written like this and it used to work in Webpack 2 beta, which only exacerbates the problem of spec-incompliant code like above. Webpack's doc seems to [advertise the ability to mix and match different module syntax](https://webpack.js.org/concepts/modules/) without mentioning gotchas. I suggest that Webpack should actively discourage this practice when possible, and point people to tools such as [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) to help fix their code.

**Comment by bebraw** [comment]
Can you move this to the [doc repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.

**Comment by Kovensky** [comment]
That `a.js` actually is still supposed to work AFAIK...

It should only break if there is an `import` or `export` in the same file. Since it's very unlikely a user would use both `export` and `module.exports` in the same file, it's more likely to happen if there's an `import` and `module.exports` exporting.

I wonder if there's a way to make `module` / `exports` be `ReferenceError`, but only in the `module` parse goal...
