### ISSUE TITLE
Resolve alias not working as expected

### ISSUE THREAD

**Issue by avanderhoorn** [webpack/webpack#359]
I have the following setup in my config:

```
...
    resolve: {
        alias: {
            'app': './src/app.js'
        }
    },
...
```

With this I'm expecting that I should be able to go `var shell = require('shell');` anywhere in my code base and it will include `./src/shell.js`.

Instead, when I try and build, I get the following errors:

```
ERROR in ./build/shell/index.js
Module not found: Error: Cannot resolve module app.js in /Users/anthonyvanderhoorn/Projects/client/build/shell
 @ ./build/shell/index.js 5:14-32

ERROR in ./build/shell/components/shell.js
Module not found: Error: Cannot resolve module app.js in /Users/anthonyvanderhoorn/Projects/client/build/shell/components
 @ ./build/shell/components/shell.js 3:14-32
```

I've looked through http://webpack.github.io/docs/configuration.html#resolve-alias and think I have everything right but its not working.

Any thoughts?

**Comment by wpitallo** [comment]
This worked for me as well thanks. 
Why does this not work using (resolve) tried every possible combination?

resolve: {
    root: path.resolve('./src/shell'),
    modulesDirectories: ['./src/shel'],
    extensions: ['', '.js', '.jsx']
},

**Comment by jhnns** [comment]
@wpitallo I can't give you a simple answer because this depends on the path which is passed to `require()`, your folder structure, other configs, etc.

Given your code snippet, I can tell that you're using the `modulesDirectories` in a wrong way. `modulesDirectories` should be an array with just folder names (no paths!), like `["node_modules", "web_modules"]`. And for the record, you should also *not* add `"bower_components"` to it, as bower_components are not resolved the recursively like node_modules are resolved.
