### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined with Code Splitting and -p flag

### ISSUE THREAD

**Issue by dsawardekar** [webpack/webpack#368]
I have a [basic react app](https://github.com/dsawardekar/react_with_webpack) built with webpack. The app has 2 files `app/app.js` and `app/vendor.js`. The vendor.js file requires a few libraries like `es5-shim`, `react`, `jquery` etc. And the `app/app.js` uses the same libraries but also has a React component that is rendered on the page on load.

My `webpack.config.js` is using Code Splitting. I would like to split the final app into `dist/app.js` and `dist/vendor.js`. The `dist/app.js` should contain only app code and `dist/vendor.js` contains all the external libraries. The config is show below,

``` js
var webpack = require('webpack');

module.exports = {
  entry: {
    app: './app/app.js',
    vendor: './app/vendor.js',
  },
  output: {
    path: 'dist',
    filename: '[name].js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor.js')
  ],
  externals: {
    'jquery': 'jQuery'
  },
  module: {
    loaders: [
      { test: /\.js$/, loader: 'jsx-loader' }
    ]
  }
};
```

This works fine and produces the 2 different files I needed. But when I use the `-p` flag to build a production version the app stops working with the error,

``` log
Uncaught ReferenceError: webpackJsonp is not defined
```

I have a feeling I'm using the `CommonsChunkPlugin` incorrectly. Is this the correct plugin for splitting an app into 2 files `vendor` and `app`?

Thanks.

**Comment by nuclearspike** [comment]
I disagree with the comment that it doesn't provide any additional benefit in production. Vendor code is much less likely to be as changing as your app code. If your server is setup so that the files are referenced with a hash of the file, you can tell the browser through the headers to cache the files for a year or more and they won't even bother making the request the next time they visit your site as long as the hash has not changed. With as many libraries as I'm using, having that code split into a much more static file and then a separate file for my app saves quite a bit of downloading for repeat visitors (where my app code has changed, but not the vendor bundle).

**Comment by steinbachr** [comment]
for me as well I was tripped up by the requirement of `minChunks: Infinity`. Previous configuration of:

```
....
entry: {
        main: './src/Main.react.js',
        core: ['jquery', 'backbone', 'react', 'react-dom', 'react-router', 'react-helmet']
    },

    output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].[hash].bundle.js',
        chunkFilename: '[id].[hash].bundle.js',
        publicPath: '//static.rukkus.com/js/spa/dist/'
    },

    plugins: [
        ....
        new webpack.optimize.CommonsChunkPlugin({
            names: ['core'],
            filename: '[name].js'
        }),
        ...
    ]
``` 

was yielding the `webpackJsonp` is not defined error. However, adding `minChunks: Infinity` to the `CommonsChunkPlugin` config fixed the issue.

**Comment by shidaping** [comment]
you do not import vendor.js in your html. 
try to add
`<script type="javascript" src="./dist/vendor.js">`
to your html file
before <script type="javascript" src="./dist/app.js">

**Comment by luckydrq** [comment]
>From a technical view it makes no sense to use the CommonsChunkPlugin with a single app entry.

@sokra I think an additional http request may not cause situation worse. On one side, modern browsers support multiple download threads which makes resource download duration shorter i think. On the other side, if resource changes, the common chunk which refers to `vendor` chunk you guys discussed above probably not change at all, so it can be cached by cdn or static server.

**Comment by FAOfao931013** [comment]
@shidaping it solved my problem `webpackJsonp is not defined`

**Comment by sbrudz** [comment]
FYI, if you followed the [code splitting example](https://webpack.js.org/guides/code-splitting-libraries/#manifest-file) in the webpack 2 docs and are seeing this error, another possible cause is that you forgot to include the manifest.js file in your HTML page.  (That was the root cause of the issue for me.)

**Comment by congwenm** [comment]
worked for me 
```
{
        test: /\.(sass|scss)$/,
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader!sass-loader?importLoaders=1'
        })
}
```

**Comment by sag1v** [comment]
@sbrudz thanks! lack of manifest was my issue as well.

**Comment by uinz** [comment]
@shidaping not work with 

```js
new ScriptExtHtmlWebpackPlugin({
    defaultAttribute: 'async'
})
```

**Comment by shahabganji** [comment]
@sbrudz Why should we add the manifest file in our HTML? does it not have any overloads?

**Comment by sbrudz** [comment]
@shahabganji If you create a manifest.js file as described in the [webpack 2 code splitting](https://webpack.js.org/guides/code-splitting-libraries/#manifest-file) documentation, then that file contains all the webpack runtime code.  Your other bundle files (main, vendor, etc.) will be generated without the runtime code but they will depend on that runtime code being loaded in order to function properly.  Because of this, the manifest.js file needs to be loaded in your HTML along with the other bundle files.  Otherwise, you'll get an error about webpackJsonp not being defined and things won't work.  

If you don't create a manifest.js file and just create a vendor bundle, then the webpack runtime code will be placed in your vendor.js file and no separate manifest file is needed.

Note that "manifest" is not a special name.  If you specify a bundle name that doesn't have a corresponding key in the entry section, then the CommonsChunkPlugin will put the remaining common code (which is just the webpack runtime stuff) into that bundle file.  So you could call it "runtime" or "webpack" and get a file with a different name but the same purpose.

**Comment by nuclearspike** [comment]
And as a reminder, the order the files are loaded does matter. If you load client.js then vendor.js (assuming no manifest) then you'll get the error. vendor (or manifest) must be loaded first.

**Comment by shahabganji** [comment]
@nuclearspike yeah, that's JavaScript rules 👍🏻👍🏻

**Comment by dottodot** [comment]
Is there anything that would cause this error. My files are loaded in order and I have a manifest.js file.

**Comment by agosto-koulor** [comment]
If you're using the Script async attribute, remove it.

**Comment by halben** [comment]
If you're using the script async attribute, remove it.

**Comment by dottodot** [comment]
I'm not using the async attribute so it's not that.

**Comment by shahabganji** [comment]
@dottodot, In my case it was owing to not referencing the manifest.js file prior to my application files.

**Comment by pixedd** [comment]
same issue here, our files order is ok in our html, we added Infinity option:

`      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: '[name]' + (prod ? '.[hash].js' : '.js'),
        minChunks: Infinity
      }),`

We can't reproduce the issue but we have a lot of error logs from differents browsers (safari 10.1.1 on Mac OS X 10.12, Chrome 59.0.3071 on Windows 7 and some firefox 54)

**Comment by jeantimex** [comment]
we had the same issue, turns out our vendor.js and app.js are loaded dynamically by JavaScript (document.createElement('script')...), and by default the scripts are executed asynchronously when they are loaded dynamically, so we just need to set the `async` to false, so that we make sure vendor.js executed first, that will make sure the webpackJsonp is defined.

**Comment by demanzonderjas** [comment]
I had the same problem and solved it by including commons.js (which is built via the CommonChunks plugin) first in the index.php, then the other bundle(s).

**Comment by rishmaflipkart** [comment]
Adding jsonpFunction:"webpackJsonp" to the output of webpack config solved the issue for me.

**Comment by 01Kuzma** [comment]
HI there!
Could anybody explain me the difference between these two configurations:
```
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            filename: 'vendor.[chunkhash].js',
            minChunks (module) {
                **return module.context && module.context.indexOf('node_modules') >= 0;**
            }
        }),
```
and the second:

```
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            filename: 'vendor.[chunkhash].js',
        	**minChunks: Infinity**
        }),
```

I was using the first, but IE 10 thrown me a **webpackJsonp is not defined** error. So the second config solves this issue. But is there a big difference between them?
Sorry for noob question.

**Comment by Pranidhi0421** [comment]
I am having same issue even after adding infinity and manifest.

entry: {
      vendor: ['react', 'react-dom'],
    app: [
      'babel-polyfill',
        "./src/app.jsx",
    ]
	}

new webpack.optimize.CommonsChunkPlugin({
          names: ['vendor'],
          filename: 'vendor.js',
          minChunks: Infinity
      }),
       new webpack.optimize.CommonsChunkPlugin({
          name: "manifest",
          filename: 'manifest.js',
          minChunks: Infinity
      })

**Comment by Pranidhi0421** [comment]
Can any one help me on the above issue please

**Comment by ethannguyens** [comment]
My case is that `manifest` need to load before `vendor`

**Comment by tomuplec** [comment]
A similar problem, I get this error in Chrome:

Uncaught ReferenceError: webpackJsonp is not defined at main.js:1

it relates to this first line of code 
webpackJsonp([19], {      
of course this is closed later on. 

It seems similar and I'm new to Webpack, anyone know what it could be?

**Comment by olofsellgren** [comment]
This might help someone:

If there are multiple webpack runtimes on the same page (e.g.a third party script, also compiled with webpack) you might need to rename output.jsonpFunction if the other script also is using the default jsonpFunction name.

https://webpack.js.org/configuration/output/#outputjsonpfunction

> This needs to be changed if multiple webpack runtimes (from different compilation) are used on the same webpage

webpack example
```js
module.exports = {
  //...
  output: {
    jsonpFunction: 'MyLibrary'
  }
}
```

vue-cli (vue.config.js) example:
```js
module.exports = {
  //...
  configureWebpack: {
    output: {
      jsonpFunction: 'ThirdPartyServicesShouldNamespaceStuff'
    }
}
`

**Comment by talhaanees** [comment]
@olofsellgren Now it says mylibrary is not defined. Sorry new to webpack any idea why this is happening?
