### ISSUE TITLE
Loaders & Dependency Management

### ISSUE THREAD

**Issue by mattdesl** [webpack/webpack#378]
Hey, nice tool you've got here!

I am running a simple test with the `json-loader`, with code like this:

``` js
var foo = require('./package.json');
module.exports = foo.version;
```

My config:

``` js
module.exports = {
    context: __dirname,
    entry: "./index.js",
    module: {
        loaders: [
            {
                test: /\.json$/,
                loader: "json"
            }
        ]
    }
}
```

Let's say I was to author this package on NPM as `foo`. Now, I'm writing another module called `bar`, which depends on `foo`. The code for that new module:

``` js
var test = require('foo');
console.log(test)
```

Unfortunately, bundling the above gives me `Cannot find module "package.json"` errors. Presumably because it doesn't know to use the JSON loader when resolving the `foo` module. 

Browserify handles this by putting transforms in the `package.json`, so that when it reaches that module, it knows to transform it. This seems like a pretty important feature for code re-use and dependency management. 

Or am I simply missing some configuration?

**Comment by sompylasar** [comment]
Related: http://spmjs.io/ (was mentioned in a comment to the npm blog post)

Let's hope `concord` will make its way in the nearest future. Very promising.

**Comment by trusktr** [comment]
Suggestion: move concord out of the `webpkac` org and into a new org for modules specs, since it should apply to all build systems. f.e. github.com/concord/spec

**Comment by brion** [comment]
I'm working on packaging [ogv.js](https://github.com/brion/ogv.js) and its audio output component [audio-feeder](https://github.com/brion/audio-feeder) in npm, and this static assets problem is definitely biting me.

audio-feeder (and thus ogv.js) needs to ship a Flash .swf file for audio support on IE 11, which _must_ be served from the actual web server -- you can't cheat with a data: or blob: URI. There are also several emscripten-compiled .js files meant to be loaded from web workers, for which blobs _might_ work though I'm less sure about IE support.

As long as I declare 'file-loader' in my dependencies and specify my loader options inline like require("file?name=audio-feeder/[name].[ext]!./dist/dynamicaudio.swf") or require("file?name=ogv.js/[name].[ext]!./dist/ogv-worker-video.js") everything seems to work ok in a test project that does a require('ogv').

However having to repeat the full loader setup on every invocation gets a little verbose if I want my files in a particular directory structure like that... currently I need to have consistent filenames within a base directory, though I can probably rewrite things to pass full hashable paths down to the Flash loader and the worker threads.

Has there been any progress on providing loader configuration defaults per-module in the package.json, or an alternate interface versus overloading require()?

**Comment by sompylasar** [comment]
@brion The core idea of webpack is that the app developer, not module developer, decides how the assets should be packaged and served. In your case, you should make your static resources published into your npm package as raw files, and your module should accept a URL for each of them. The app developer who does the bundling would require these assets and will provide your module with every needed URL. They can be hosted differently, e.g. on a CDN, and you never know what app dev would need. You can make the API of your module so that it demands specifying the URLs.

**Comment by brion** [comment]
Sure, all the paths are configurable. But it'd be nice if webpack could pack the assets for a web app, both reliably *and* configurably.

Reliable: default case should Just Work. Assets belonging to dependencies and dependencies of dependencies and dependencies of dependencies of dependencies should be packed/bundled/copied along with the other output.

Configurable: all paths should be customizable in the app's webpack config.

Both: Things like inlining images should be configurable in general, but module developer still needs to be able to specify "this .swf file cannot ever be inlined as a data URI because Flash won't load it that way" or "this .PNG file needs to be embedded as data, not a URL".

It seems to me that having defaults in package.json that can be overridden in the app config globally and on a per-module basis would go a long way. Webpack is supposed to help the app developer, and I'm all in favor of that!

**Comment by brion** [comment]
Also I'm going to go on record as saying that requiring the app developer to read readmes of every module in the dependency graph to get a list of every static asset they have, and manually require all those resources individually, and pass every URL through into the configuration of every affected module, seems like a very developer-unfriendly configuration system.

Not only is it poorly scalable to an initial setup, it would require every package update in the dependency graph to be checked for additional asset files. Maintenance would be ... Unpleasant in this model.

This is literally what computers are for: put the list of assets in a manifest file and have the computer manage them but with the human's oversight.

**Comment by jhnns** [comment]
> Also I'm going to go on record as saying that requiring the app developer to read readmes of every module in the dependency graph to get a list of every static asset they have, and manually require all those resources individually, and pass every URL through into the configuration of every affected module, seems like a very developer-unfriendly configuration system.

Yep, that's true. The situation has not improved – still it's the best way to configure things on app level instead of on library level.

@brion I think it's currently the best solution to separate actual source files that should be added to the webpack bundle from static assets that should just be emitted to the output folder. In your case, I'd place the `dynamicaudio.swf` and the `ogv-worker-video.js` into a dedicated assets folder and then configure the `file-loader` to be applied on all these assets by default.

**Comment by brion** [comment]
@jhnns yeah, the trick with the worker .js assets is that default require('foo.js') behavior is to execute, not to return a URL. So if I just write this:

```
var worker = new Worker(require('./dist/ogv-worker-video.js'));
```

it won't actually work unless the webpack configuration includes a suitable binding, maybe:

```
{ test: /ogv-.*.js$/, loader: "file?name=/some-dir/ogv.js/[name].[ext]" },
```

I'm also a bit unclear from reading https://webpack.github.io/docs/using-loaders.html on whether I can specify an inline loader type like these to guarantee I get a URL to an actual file from require():

```
flashObject.src = require('file!dynamicaudio.swf');
var worker = new Worker(require('file!ogv-worker-video.js'));
```

while still allowing the loader options to be overridden in the app's config. Do inline loader options override the regex-configured ones, or the other way around?


I think I'm going to do an initial package release without the external webpack exposure -- just manual documentation of the dist-ready assets and how to set the asset paths at runtime -- and keep refactoring and testing until I'm happier with the resulting output.

(I am now using webpack to build my pre-packed distribution bundle for use outside the npm universe -- it's pretty awesome at that level! Still getting the hang of it though, and really looking forward to more module composability. :)

**Comment by sompylasar** [comment]
Can this help with the worker? https://github.com/borisirota/webworkify-webpack

**Comment by sompylasar** [comment]
> whether I can specify an inline loader type

This is technically possible but highly discouraged in the webpack world.

**Comment by brion** [comment]
@sompylasar webworkify-webpack looks like it does the blob loader trick I
would need to support cross domain loading of the modules, but doesn't seem
like it would handle my use case correctly, in that it appears to pack the
worker modules into the main source and provides no asynchronous load
mechanism.

(Also, I need to confirm that IE 10/11 can load workers from blob URLs,
which I have not tested.)

I'm supporting multiple codec modules in a media player widget, and need to
avoid loading codecs that are not needed for whatever files get played (or
if playback never is started, at all). I also want to avoid parsing
JavaScript for those modules -- large, dense code bases cross-compiled from
C libraries -- on the main thread, which would happen with
webworkify-webpack as it seems to fetch live code modules and turn their
source back into strings. So even if I loaded them asynchronously, it would
need me to load them into the main thread's __webpack_require__ world as
live modules first, wasting CPU time and memory.

**Comment by brion** [comment]
Yeah, looks like async loading with code splitting per http://webpack.github.io/docs/code-splitting.html would work for the on-demand loading, but would still parse on main thread and then again on the worker. I can play games with turning source files into modules that eval strings to reduce that perhaps, but that feels a bit ugly when I have to pack into a string anyway for the worker blob load trick.

Back to the original  topic...

I think it would be very useful to expose a list of static asset files in the package.json, which would be machine-readable versus just a mention in the read me. At the least I would love as an app packager to have an automated report generated every time I run webpack.

Better still would be a common runtime registry interface allowing modules packed using webpack to ask for the app-packager-configured URLs.

This sounds a lot like require('foo.png') but with the specificity that it always returns a URL, rather than only returning a URL when file-loader or url-loader is configured and trying to import JavaScript code otherwise.

The app packager could then set all the loader options they want by making a giant mapping of registered asset keys to require() invocations, with inline loaders or with configuration in the webpack config object.

Going one step further, an initial such mapping can be auto generated by a build tool, with overrides specified by the app packager.

This would I think pretty much do what I want, would allow for both automatic and manual configuration of the asset loader details, as long as dealing specifically with URLs to static assets. And it remains much less ambitious than the concord ideas linked from discussin last year -- packages are responsible for prebuilding their static assets if they want to make js from coffee script or css from sass.


I think his could be done pretty straightforwardly as a plugin to webpack, in a way that could still allow for full manual configuration of everything if you didn't want to use the build tool plugin.

Eg something like this in usage:

```
var staticLoader = new require('static-asset-loader')(
	'audio-feeder', // package name
	'assets' // base dir for assets in package
);

function AudioFeeder(options) {
	if (options.base) {
		staticLoader.base = options.base;
	}
	flashObject.src = staticLoader.url('dynamicaudio.swf');
	// ...
}
```

with added to the package.json:

```
"assets": ["dynamicaudio.swf"],
```

and in the app's calling code, choose either:


```
// paths configured by build tool
var audioFeeder = new require('audio-feeder');
```

or


```
// dont forget to copy the assets
var audioFeeder = new require('audio-feeder', {
	'manually/specified/path/to/copied/assets'
});
```

The build plugin would scan through the package manifests and build a default map, like:

```
require('static-asset-loader').override({
	'audio-feeder': {
		'dynamicaudio.swf': require('audio-feeder/assets/dynamicaudio.swf')
	}
});
```

which would get processed for loaders and included in with the other modules, with a call forced to make sure it runs before app code tries to use the assets. The tool could even suggest mappings for your config file as defaults.

Suitable static analysis could probably avoid the need for adding a list of files to the package.json.

Thoughts?

**Comment by sompylasar** [comment]
@brion 

> Better still would be a common runtime registry interface allowing modules packed using webpack to ask for the app-packager-configured URLs.
> 
> This sounds a lot like require('foo.png') but with the specificity that it always returns a URL, rather than only returning a URL when file-loader or url-loader is configured and trying to import JavaScript code otherwise.

The thing is, you don't always have a URL for an arbitrary module if you don't use file-loader or url-loader. The module can be embedded into a chunk of JS next to other modules.

> packages are responsible for prebuilding their static assets

This part looks reasonable, and even looks like almost what I suggested: a package exports its static assets for the app to use (it may bundle or just manually expose at a URL). This is how ES6 npm modules are made compatible with the surrounding ecosystem: they are transpiled into ES5 CommonJS which are consumable by Node.js natively.

> with added to the package.json:

This looks exactly what I suggested, but with added automation.

> Eg something like this in usage:

This looks even better. But I'd make something like:

```
// In a module that provides static assets.
var url = require('static-asset-provider')('./assets/dynamicaudio.swf');  // Can be found and resolved statically by webpack
if (!url) {
    throw new Error('Cannot get URL of `dynamicaudio.swf`. Check your bundler configuration.');
}
```

```
// In an app that uses webpack to bundle.
plugins: [
    // Captures all `require('static-asset-provider')`,
    // and replaces it with `require('/full/path/to/assets/dynamicaudio.swf')`
    new StaticAssetProviderPlugin()
]
```

No need to scan through some manifests, every dependency is expressed with the code itself (that's one of the core ideas and benefits of webpack which I extremely like).

**Comment by brion** [comment]
@sompylasar 

Definitely agree that static analysis beats explicit manifests in this case; I like your plugin config example. :)

I guess what I want is the power of static analysis in the packing system that webpack already provides with require() and readFileSync(), plus more flexible machine-readable annotations about the return type and the sync-ness of the load that will allow working default behavior that is also reconfigurable.

> The thing is, you don't always have a URL for an arbitrary module if you don't use file-loader or url-loader. The module can be embedded into a chunk of JS next to other modules.

In many cases it doesn't matter to the library whether you use a local URL, remote URL, or pre-pack them into data: URLs, or even runtime-convert a string literal into a blob: URL. What you care about as a library author is you need to feed a URL into some HTML or CSS or JS API.

At other times, that packing simply will not work, such as the Flash .swf file example -- you specifically need a URL, but you also specifically need an externally-referenced file. For this reason I would consider them separate data types ('static URL' versus just 'URL').

Similarly, strings and array buffers can be either embedded as modules returning literals in the packed JS, or they can be loaded from static files at runtime via XHR. Supporting both effectively requires using an async interface for the asset loading -- something not needed for URL references because the loading is done in someone else's code in the browser engine.

To extend your version of the example a bit with types and sync-ness:

```
var assets = require('static-asset-provider');


// These always return URLs, but we don't care if you pre-packed the file data or not.

img.src = assets.url('./assets/loading-spinner.svg');

worker = new Worker(assets.url('./assets/prepacked-worker.js'));


// When you need a URL that *must* be served as a separate asset to work,
// but you still don't care what it's named or what directory it's in etc.

flashObject.src = assets.staticUrl('./assets/dyamicaudio.swf');
```

We could extend this further to allow string & ArrayBuffer imports to be either separate files loaded via XHR or strings/arrays packed into the source, at the app packager's desire:

```
// Async loader interface allows the files to be either loaded via XHR or packed in JS.

assets.string('./assets/example.js').then(function(str) {
  textarea.text = str;
});

assets.buffer('./assets/codec-setup.mem').then(function(buf) {
   audioCodecInitializerData = buf;
});


// When you need a string or buffer and you need it NOW
// sync XHR may be unsafe or difficult to use, as browser makers hate it.
// Possibly redundant to readFileSync()

textarea.text = assets.stringSync('./assets/example.js');

audioCodecInitializerData = assets.bufferSync(./assets/codec-setup.mem');
```

I think these can all fit with the static analysis plugin model you suggest in a way that leaves the _packaging location/method_ up to to the app packager, while the library author remains in control of what datatypes they'll get back.

So if the app packager tried to configure the .swf file in a way that couldn't be loaded as a real remote URL, the asset loader plugin would yell and scream at build time that this would not work because it's the wrong data type.

Similarly, the default behavior of ```static-asset-provider``` when not rewritten could be configurable with a runtime interface to supply URLs or pre-packed string/buffer data. That helps avoid the 'webpack vendor lock-in' problem described in a few places earlier on this thread -- a library that needs static assets using this system would benefit from webpack + a plugin, but would not require it.

**Comment by brion** [comment]
I'll try putting together a plugin based on this model and see how it works out...

**Comment by jhnns** [comment]
Haha, you've summoned a monster by reviving this thread @brion :wink: 

Your quote summarizes the essence of the previous discussion:

> I think these can all fit with the static analysis plugin model you suggest in a way that leaves the packaging location/method up to to the app packager, while the library author remains in control of what datatypes they'll get back.

Writing `require("./some/img.png")` is like requesting a hook from the build system to do something. The build system cannot know what the library author is expecting from this `require()`: It could return a url, a data url or just the size of the image. So this should be up to the library author. The library author, on the other hand, should not have any assumptions about how these things end up into the final bundle. It should "just work"™.

The proposed concord spec tries to solve this with a declarative solution which maps paths to type definitions and then type definitions to build system transformations.

Example: `require("./some/img.png")` is referenced by using `*.png`, then mapped to `url/image` which is then mapped to `url-loader!./some/img.png` in a webpack environment.

The concept sounds really nice, but it requires a lot of community effort. And I'm still unsure if a declarative approach is flexible enough. Perhaps it is better to move more responsibility to the library author (like you should compile your ES2015 stuff before pushing it to npm).

---

@substack 's approach is different and very node-focused: You would not `require("./some/img.png")`, but write something like this:

```javascript
var sizeOf = require("image-size");
var dimensions = sizeOf("images/funny-cats.png");
```

Then, your build system would need a transform/loader which "anticipates" the API calls by reading the AST. Thus, you can do things at build time what you cannot do at runtime (like reading files from disk). This approach is very isomorphic friendly because you don't have to do anything in node.js to make this code work. 

On the other hand, it's not very scalable because you'd need a `image-sizeify` for browserify, an `image-size`-plugin for webpack, etc. It basically pushes responsibility to the eco-system.

---

@brion @sompylasar your approach is similar to @substack 's one, but it sounds really interesting. I'm curious about your prototype...

**Comment by jhnns** [comment]
One thing I wanted to add to subtack's approach:

It looks really nice, because you don't have to compile your stuff before feeding it to node. But there are also disadvantages: Depending on the use-case it could really slow down your application startup because every `require()` is synchronous. What if you'd required several LESS files? In node, compilation could only be done sequentially. This is basically why [enhanced-require](https://github.com/webpack/enhanced-require) is deprecated.

Although it looks like an overhead, in practice it's better to streamline the client and the server environment by always having a build step before execution.

**Comment by brion** [comment]
@jhnns hehe, monster indeed! :)

I want to avoid overriding require() in part because files of the same *file* type may need to be referenced and used in different ways... But I also don't want to go too crazy on transformations. For instance an image-size build time plugin would be awesome! But... As a module author I could use a webpack loader, or some similar transform system, in *my* pre-publish build stages to do that.

I'd like to concentrate on an interface for that last step, where my module code gets packed into someone else's project either manually or via webpack or browserify. At that point I already know the image's size from my build, so I just need either its contents or a URL reference to it.

So, hoping to keep it unambitious, which may make it easier to get working...

**Comment by jhnns** [comment]
> So, hoping to keep it unambitious, which may make it easier to get working...

That's a valid point. In this case, it's certainly better to solve the asset referencing issue then to catch all potential edge-cases. That's what I was trying to say about pushing responsibility to the library authors. They should do as much as possible without having any assumptions about the build system.

**Comment by sompylasar** [comment]
@brion 

> In many cases it doesn't matter to the library whether you use a local URL, remote URL, or pre-pack them into data: URLs, or even runtime-convert a string literal into a blob: URL. What you care about as a library author is you need to feed a URL into some HTML or CSS or JS API.

Yes, it doesn't matter which URL you get, but sometimes you really *don't have a URL*, neither local, nor remote, nor data, nor blob. What you have is, e.g. base64 of the file contents. Yes, you can somehow transform it into a `data:` or `blob:` URI.

> To extend your version of the example a bit with types and sync-ness:

Yes, I like your approach. It will be harder to statically extract, but nonetheless it's possible.

> We could extend this further to allow string & ArrayBuffer imports to be either separate files loaded via XHR or strings/arrays packed into the source, at the app packager's desire:

Yes, great!

> Similarly, the default behavior of `static-asset-provider` when not rewritten could be configurable with a runtime interface to supply URLs or pre-packed string/buffer data. That helps avoid the 'webpack vendor lock-in' problem described in a few places earlier on this thread -- a library that needs static assets using this system would benefit from webpack + a plugin, but would not require it.

Exactly! One thing is that if 'static-asset-provider' is not rewritten by something like `webpack` or `require-hacker`, there cannot be any URL, because this library knows nothing about URLs, and how the assets are served, and where this server will be located (the 'L' for locator in 'URL').

> I'll try putting together a plugin based on this model and see how it works out...

Wow would be very cool! Please link from here as soon a something is pushed.
