### ISSUE TITLE
Running multiple webpack dev servers in the same host

### ISSUE THREAD

**Issue by jsrraman** [webpack/webpack#3805]
Currently I am running a webpack dev server on the localhost port 3000 for one UI project

```
webpack-dashboard -- webpack-dev-server --config webpack.dev.js --inline --hot --watch --host 0.0.0.0 --port 3000
```

Now when I want to run another webpack dev server on the localhost port 4000 for another UI project it throws `EADDRINUSE` error because webpack-dev-server is bound to first UI project in port 3000

How do I configure webpack-dev-server to run both UI projects simultaneously?

**Comment by catchmareck** [comment]
I am facing the same problem right now. Have you found a solution?

**Comment by norbiu** [comment]
> I am facing the same problem right now. Have you found a solution?

Did you?

**Comment by catchmareck** [comment]
@norbiu Unfortunately, no. I just start multiple dev servers on different ports

**Comment by JohanSchobben** [comment]
I know it has already been 4 years since the last comment, but it might help people in the future. 

What I did was run both servers on different ports and configure a proxy on the host server that I want to interact with.

So I had my local server run on port 4200 and my some other project running on port 3000. I did add this config to the server running on port 4200.

```JSON
{
  "/assets/other-application/": {
    "target": "http://localhost:3000"
  }
}

```
