### ISSUE TITLE
webpack@2.2.0-rc.4 alias not working with Angular2 components

### ISSUE THREAD

**Issue by Bolza** [webpack/webpack#3947]
I'm using webpack@2.2.0-rc.4 to serve NG2 project. Linking my modules only works  using relative paths. The absolute paths are not working.

This is how the resolve is configured

     config.resolve = {
            modules: [path.resolve(__dirname, "src"), 'node_modules'],
            extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
        };

this is how i link the files

    import { Child } from 'app/components/child.component';

and i get `Cannot find module` even if my there is a class in `src/app/components/child.component.ts`.

In the meantime i asked also on stackoverflow (http://stackoverflow.com/questions/41632650/webpack2-alias-not-working-with-angular2-components)

**Comment by mhheise** [comment]
I gather your folder structure resembles this:

```
src
-- app
   -- app.module.ts
   -- components
       -- child.component.ts
```
I take it you are trying to import from your `src/app/components/child.component.ts` file into your `src/app/app.module.ts` file?

In that case, you should specify the relative path for your import in your `app.module.ts` file like this:
```ts
import { Child } from './components/child.component';
```
Otherwise, you are hinting to `webpack` that the file can be found at what would be an absolute path of `src/app/app/components/child.component`.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Provide information about your folder structure.
