### ISSUE TITLE
utf8 issue upon updating from 2.2.0-rc.3 to 2.2.0-rc.4 or later

### ISSUE THREAD

**Issue by kball** [webpack/webpack#3984]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Starting with rc.4 or later, I get this error:
```
> ./node_modules/webpack/bin/webpack.js
/Users/kball/git/foundation-sites/node_modules/webpack/lib/Compiler.js:324
                                        content = Buffer.from(content, "utf8");
                                                         ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at Compiler.writeOut (/Users/kball/git/foundation-sites/node_modules/webpack/lib/Compiler.js:324:23)
    at Compiler.<anonymous> (/Users/kball/git/foundation-sites/node_modules/webpack/lib/Compiler.js:312:20)
    at /Users/kball/git/foundation-sites/node_modules/webpack/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/Users/kball/git/foundation-sites/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/kball/git/foundation-sites/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/Users/kball/git/foundation-sites/node_modules/webpack/node_modules/async/dist/async.js:3089:3)
    at Compiler.emitFiles (/Users/kball/git/foundation-sites/node_modules/webpack/lib/Compiler.js:301:20)
    at /Users/kball/git/foundation-sites/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

gist of configuration here: https://gist.github.com/kball/6cd4f435afad9fb4e3813fe7297aa676

Full setup here: https://github.com/zurb/foundation-sites/tree/684d86b3943fd29eb7775e64a6468f08b0752d5d (this is on a work in progress branch of Foundation)

**What is the expected behavior?**
in rc.3 this works properly, generating a single bundle. In later versions it breaks.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/a

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

current node version: v4.2.2
webpack versions: 2.2.0-rc4 through 2.2.0-rc7
OS: OS X 10.11.6

**Comment by egoroof** [comment]
> current node version: v4.2.2

Update it to 4.5+

**Comment by brendo** [comment]
> Update it to 4.5+

This is a fairly 'big' change for an RC considering that the default NodeJS runtime environment for AWS Lambda is 4.3.2. Internally our CI images are synced with the AWS runtime platform, and since RC4 our builds will fail when compiling our code to be deployed using Serverless.

Don't mind if this is a requirement of Webpack, but introducing (or enforcing) this change in an RC is a bit risky IMO.

**Comment by TheLarkInn** [comment]
We followed the LTS for node and dropped support for minimum supported node version which is 4.7. Is there a way we can assist finding a polyfill for Buffer.from?

**Comment by brendo** [comment]
> We followed the LTS for node and dropped support for minimum supported node version which is 4.7.

Yep, that's fine and I understand the reasoning behind the change, I just worry about why it was enforced in an RC and not in a previous beta/alpha.

> Is there a way we can assist finding a polyfill for Buffer.from?

If you have a recommendation that'd be brilliant, thanks!

**Comment by TheLarkInn** [comment]
Maybe we can reach out to the AWS Lambda team and see what we can do. Ill attempt this tonight.

**Comment by TheLarkInn** [comment]
Oh I should have ask you mentioned the default env was <4.7, is there not a way to imply upgrade to node 4.7?

**Comment by brendo** [comment]
> Oh I should have ask you mentioned the default env was <4.7, is there not a way to imply upgrade to node 4.7?

Not typically. AWS Lambda is just FaaS, so the code is zipped and AWS deploys it into a runtime environment upon request. This is current [runtime environment for AWS Lambda](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

Technically, as webpack is just being used to _build_ our code, our CI environment (which we control) could have a different version of Node installed. For "reasons", we have chosen to keep this environment in-step with the AWS runtime environment so that we can build and test our code in an environment that mimics production.

As I mentioned before, I agree with the reasoning behind the change, it's just when it was enforced that irks me.

**Comment by kball** [comment]
I can update my environment without trouble, however it looks like AWS Lambda *only* provides v0.10.36 and v4.3.2 as runtimes... and I don't know about ya'all but I've found node consistency between versions to be... strikingly poor.  Dunno how many folks are using Lambda.

I see this package out there: https://www.npmjs.com/package/buffer-v6-polyfill dunno if that will fix this case - I'm not at work and don't have my dev env setup here to test easily, but I can play with that in the morning
