### ISSUE TITLE
New CommonsChunk vendor algorithm/functionality

### ISSUE THREAD

**Issue by elfey** [webpack/webpack#4135]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Currently CommonsChunk is great for applications that explicitly define chunks, but for applications that don't, there's an issue... we have to explicitly declare all of our vendors, which change, and every time a dependency is removed/added, we have to update that list of vendors.

There's also the added issue that when we define that list of vendors we'd like to include in our `vendor.js`, we're typically going to request that the entire dependency and functionality of that dependency is included so that we don't get errors or lose functionality. That means that for certain dependencies, we end up including the entire dependency, even if we're only using one function from it.

I'd like to propose that CommonsChunk plugin scans the list of dependencies for each file, and it counts `import` statements for each dependency. If the count for a particular dependency is greater than the `minDependency` (or we could call it `minImport`) value, it's safe to assume that because of how common that dependency is within the application (and how often it's being `import`ed) that it's an essential part of the application's vendors and isn't going away any time soon.

So we automatically take that dependency and bundle it into the `vendor.js` file.

This means that we get `vendor.js`, and its beautiful caching properties, without the pain of continuously having to modify our config file.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's a total pain to constantly be updating vendors.

**Comment by elfey** [comment]
As a side note, we could generate a hash based on the contents of the file, which would allow our clients to know when the vendor file has changed (useful for cache busting).

**Comment by TheLarkInn** [comment]
Technically that's how the algorithm works today. Check out the source of CommonsChunkPlugin and you'll see that it checks against all entry chunks (or a specified subset), and then tracks the number of times a module.is requested from each chunk. If it turns out that the module spans at minimum (unless minChunks is specified) across chunks. If so, it separates that code into a new bundle. Ideally youd provide a name for that bundle with the filename property. 

In regards to your second concern: take a look at this section I wrote on passing minChunks property a function.

https://webpack.js.org/plugins/commons-chunk-plugin/#passing-the-minchunks-property-a-function

**Comment by elfey** [comment]
@TheLarkInn So could that be accomplished with something like this?

```js
new webpack.optimize.CommonsChunkPlugin({
    names: Object.keys(package.dependencies),
    filename: '[chunkhash].vendor.js'
})
```

**Comment by TheLarkInn** [comment]
```
new CommonsChunkPlugin({
  name: "my-single-lib-chunk",
  filename: "my-single-lib-chunk.js",
  minChunks: function(module, countOfHowManyTimesThisModuleIsUsedAcrossAllChunks) {
    // If module has a path, and inside of the path exists the name "somelib", 
    // and it is used in 3 separate chunks/entries, then break it out into
    // a separate chunk with chunk keyname "my-single-lib-chunk", and filename "my-single-lib-chunk.js"
    return module.resource && (/somelib/).test(module.resource) && count === 3;
  }
});
```
This is the example seen above from the docs page. Maybe you aren't understanding (or maybe I am not understanding).

It would be fair to say that any module you request from your import/require statements will come from `node_modules` right? 

So you could implement exactly what you are talking about by modifying the above example to instead of being a regex to some lib, to be instead `/node_modules/`. This will automatically collect all requests which come from node_modules and move them to a separate chunk.

**Comment by elfey** [comment]
@TheLarkInn I see what you mean now, that works great. UglifyJS gives a ton of warnings though when it's setup that way.

<img width="1260" alt="screen shot 2017-01-29 at 10 25 12 pm" src="https://cloud.githubusercontent.com/assets/24572473/22411434/e40e40b4-e671-11e6-98fc-7682dd641c8c.png">

And there's more.

This doesn't typically happen - how can we suppress this?

**Comment by elfey** [comment]
@TheLarkInn that works great, thanks.

**Comment by dmitriid** [comment]
This still requires you to list all modules from `node_modules` in the `entry` object though, don't you? As in

```
  entry:   {
    app: './app.js',
    lib: [
      "axios",
      "es6-promise",
      "fast.js",
      "google-map-react",
      "jed",
      "jquery",
      "mobx",
      "mobx-react",
      "mobx-react-devtools",
      "moment",
      "moment-timezone",
      "pikaday",
      "po2json",
      "react",
      "react-dom",
      "router5"
    ]
  },
  output:  {
    path:          './build/app.js',
    publicPath:    '/events/build/js',
    filename:      "[name].js",
    chunkFilename: ".js"
  },
```

etc.?

**Comment by dmitriid** [comment]
Ah, nevermind. I have just re-read "Implicit Common Vendor Chunk" section.
