### ISSUE TITLE
Override __webpack_public_path_ in manifest file

### ISSUE THREAD

**Issue by alfeg** [webpack/webpack#4242]
I'm using common chunk plugin extracting manifest file as stated in docs for webpack 2

```
new webpack.optimize.CommonsChunkPlugin({
     name: 'manifest',
     chunks: ['vendor']
 })
```

In my app I override global __webpack_public_path_ in runtime. But I can see that this path is not overriden in manifest file. 

How to solve this problem?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
