### ISSUE TITLE
BannerPlugin doesn't take placeholders into account

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4252]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```javascript
new webpack.BannerPlugin({
  banner: '[hash]',
}),
```

outputs `[hash]` in the banner.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the config above as a part of a webpack build.

**What is the expected behavior?**

It should output the hash, not the template.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 2.2.1, Node 6.9.1, macOS 10.12.3

**Comment by karanjthakkar** [comment]
@bebraw I'd like to give this a shot. Since this is my first contrib to the webpack codebase, can you point me in the direction of where to start?

**Comment by bebraw** [comment]
@karanjthakkar Look into `loaderUtils.interpolateName`. That feels like the starting point for this one.

**Comment by sokra** [comment]
`compilation.getPath` does the replacement.

**Comment by thescientist13** [comment]
Hello!

So I was taking a look at this today to see if I could and was trying to figure out how to best approach this.  

So indeed `compilation.getPath` does do the replacement, but it takes a filepath.

However, in the filter callback in `BannerPlugin.apply`, it seems that we are dealing with file _contents_;
```javascript
compilation.assets[file] = new ConcatSource(banner, "\n", compilation.assets[file]))
```

How would one apply the logic of `compilation.getPath` to file contents instead of a file path?
