### ISSUE TITLE
Throws an error if "entry" field is missing in array config

### ISSUE THREAD

**Issue by leo** [webpack/webpack#4272]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Webpack throws an array if the exported configuration doesn't contain an "entry" field. That's not okay because many people (like us at @zeit) are exporting an array for multiple configs.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone [this](https://github.com/zeit/now-desktop)
2. Bump "webpack" dependency to latest version
3. Run `npm run dev`

**What is the expected behavior?**

It should not throw an error.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Latest node
- Latest npm
- Latest macOS

**Comment by sokra** [comment]
This configuration https://github.com/zeit/now-desktop/blob/master/webpack.config.js#L123-L139
has not entry property. This is not allowed. You can move the CopyWebpackPlugin into another configuration and remove this (empty) config.

I would recommend to remove the CopyWebpackPlugin, because this isn't webpack "style". webpack configuration should declaratively describe the build process. CopyWebpackPlugin is an imperative step.

**Comment by leo** [comment]
@sokra Ahhhh, interesting! Thanks. Will try that!
