### ISSUE TITLE
Module not found - webpack looking for filename prefixed with backslash

### ISSUE THREAD

**Issue by joshma** [webpack/webpack#428]
I'm new to webpack, so if I'm missing something obvious help would be much appreciated, but I've been experiencing issues with finding modules.

For background, I'm attempting to move our project over from AMD/RequireJS, so most of our require paths are relative to the project root instead of relative to the file. The project root is `./web/coffee/editor` (relative to the repo root), and so a file might `require('analytics')` to require `./web/coffee/editor/analytics.coffee`.

I figured I'd set the `resolve.root`:

```
module.exports = {
    entry: './web/coffee/editor/main',
    output: {
        path: './web/static/build',
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            { test: /\.coffee$/, loader: 'coffee-loader' },
            // { test: /\.css$/, loader: 'style!css' }
        ]
    },
    resolve: {
        alias: {
            'raven$': '../../static/lib/raven.jquery.native.min.js'
        },
        extensions: ['', '.js', '.json', '.coffee'],
        root: './web/coffee/editor'
    },
    bail: true
};
```

However, from the errors I get it looks like webpack is attemping to load `./web/coffee/editor\analytics.coffee` (note the backslash) instead of `./web/coffee/editor/analytics.coffee` (which exists!)

```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'analytics' in /Users/joshma/myproject/web/coffee/editor
  at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compilation.js:213:38)
  at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/NormalModuleFactory.js:55:19)
  ...truncated...

resolve module analytics in /Users/joshma/myproject/web/coffee/editor
  looking for modules in ./web/coffee/editor
    ./web/coffee/editor\analytics doesn't exist (module as directory)
    resolve 'file' analytics in ./web/coffee/editor
      resolve file
        ./web/coffee/editor\analytics doesn't exist
        ./web/coffee/editor\analytics.js doesn't exist
        ./web/coffee/editor\analytics.json doesn't exist
        ./web/coffee/editor\analytics.coffee doesn't exist
  looking for modules in /Users/joshma/myproject/node_modules
    /Users/joshma/myproject/node_modules/analytics doesn't exist (module as directory)
    resolve 'file' analytics in /Users/joshma/myproject/node_modules
      resolve file
        /Users/joshma/myproject/node_modules/analytics doesn't exist
        /Users/joshma/myproject/node_modules/analytics.js doesn't exist
        /Users/joshma/myproject/node_modules/analytics.json doesn't exist
        /Users/joshma/myproject/node_modules/analytics.coffee doesn't exist
```

Any ideas?

**Comment by machineghost** [comment]
For what it's worth, I just had the same question, and found it through this bug report (not through the official documentation).  Perhaps this information, which is *extremely* relevant to people transitioning from AMD, could  be surfaced more prominently in other places (eg. in the tutorial)?

**Comment by jhnns** [comment]
@machineghost Which information should be more prominent? The docs can be edited by everyone and we appreciate every contribution.

**Comment by machineghost** [comment]
Sorry for not responding sooner; I've been dragged away from my "convert to Webpack" project, and so I haven't really gotten far enough along to offer meaningful details.  But to answer your point, I'm brand new to Webpack, and I wouldn't feel comfortable editing the wiki of software that I never even got working myself.

The general sentiment I was trying to express was that if you are just starting to learn *any* library, you don't even know what you don't know.  Telling a person in that state "well you should have just RTFM-ed" is kinda missing the point that they *couldn't* solve their problem by RTFM-ing, because they don't even know enough to know what to ask (ie. enough to know where in the manual to look, or even to realize that the manual holds the information they seek).

You have to keep in mind, when someone's new and they see "ModuleNotFoundError", that doesn't translate to "oh gee, well now obviously I should go the webpack documentation, find the configuration section, and then read up on `resolve.root`"  It translates in to "I've got a mysterious error that wasn't mentioned in the tutorial; guess I better Google it".

And hey, that totally worked for me in my case.  But if all the experienced AMD/Webpack people already know this fact, wouldn't it make sense for them to add it to  a more n00b-friendly place (like in the main tutorial, or in a separate "Webpack: AMD" tutorial, or *something*)?

But I do pledge that if I ever can find the time to get my own webpack install working, and I get comfortable enough with Webpack to feel like I can edit the wiki without saying something incorrect, I will happily add the information about AMD needing an absolute `resolve.root` ... if I haven't forgotten what it's like to be a n00b, and thus where the information needs adding, by then ;)

**Comment by jhnns** [comment]
Agreed. Having a section in the docs like "webpack for require.js users" (similar to the [browserify section](http://webpack.github.io/docs/webpack-for-browserify-users.html)) would be helpful.

However, that takes time and experience with large require.js projects.

**Comment by alexindigo** [comment]
@sokra @jhnns I have similar problem, but not exactly. My paths are all absolute (I did go through documentation, several times). This is resolve part of my config:

```
    extensions: ['', '.hbs', '.js'],

    modulesDirectories: [
      path.resolve('./node_modules/'),
      path.resolve('./node_modules/beaker/node_modules/')
    ],

    root: [
      path.resolve('./'),
      path.resolve('./node_modules/'),
      path.resolve('./node_modules/beaker/'),
      path.resolve('./node_modules/beaker/node_modules/')
    ],

    fallback: [
      path.resolve('./'),
      path.resolve('./node_modules/'),
      path.resolve('./node_modules/beaker/'),
      path.resolve('./node_modules/beaker/node_modules/')
    ]
```

_(I have my app "inheriting stuff from another "module", long story, but I did manage to make it work with r.js and now converting it to webpack)._

And this is the error I see:

```
{ [ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js in /Users/alex/Projects/app-rentals/node_modules/beaker/app/lib/helpers/rendr-handlebars]
  name: 'ModuleNotFoundError',
  message: 'Module not found: Error: Cannot resolve \'file\' or \'directory\' /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js in /Users/alex/Projects/app-rentals/node_modules/beaker/app/lib/helpers/rendr-handlebars',
  details: 'resolve file\n  /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js doesn\'t exist\n  /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js.hbs doesn\'t exist\n  /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js.js doesn\'t exist\nresolve directory\n  /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js/package.json doesn\'t exist (directory description file)\n  /Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js doesn\'t exist (directory default file)',
  missing: 
   [ '/Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js',
     '/Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js.hbs',
     '/Users/alex/Projects/app-rentals/node_modules/handlebars/runtime.js.js' ],
```

So as you can see it's looking for a module only within "top level" node_modules, despite what specified in the config.

Please advise.

**Comment by jhnns** [comment]
The `modulesDirectories` config makes no sense. It should contain an array of folder names, like `["node_modules", "bower_components"]`, not real paths. If you're not using bower, you should not modify this.

If you just want to require stuff from `node_modules`, you don't have to do anything. It works out-of-the-box.

**Comment by alexindigo** [comment]
Ok, just module names, not full paths, noted. Thanks. Although seems like absolute paths work as well.

What I'm trying to do is to require from `node_modules` and from `node_modules/beaker/node_modules`.

And webpack is ignoring it in `root` and in `fallback`.

**Comment by alexindigo** [comment]
Ok, my bad. Had left overs from previous experiments in `alias` section. Works nicely. Thanks.

**Comment by jhnns** [comment]
Just wanted to leave as a note: Requiring from `node_modules/beaker/node_modules` is really an antipattern in node.js and will probably bite you sooner or later :). Starting with npm 3 you can not be sure about the contents of this folder.

**Comment by alexindigo** [comment]
I know :) It is bad. And it was the best solution we could find. Enterprise world is messy. :)

**Comment by heisian** [comment]
The docs are a bit confusing. It's not immediately made clear that `path.resolve` returns an absolute path. At first glance it looks like they contradict themselves because they say **not** to use `./app/modules`, then immediately after in the example show `./app/modules` being used. Nevermind that it's wrapped in a resolver - people often look for patterns when reading.

> resolve.root
The directory (absolute path) that contains your modules. May also be an array of directories. This setting should be used to add individual directories to the search path.

> It must be an absolute path! Don’t pass something like **./app/modules**.

> Example:
```node
var path = require('path');

// ...
resolve: {
  root: [
    path.resolve('./app/modules'),
    path.resolve('./vendor/modules')
  ]
}
```

**Comment by sokra** [comment]
You could report your concerns to the docs repo (webpack/webpack.js.org)...

I think `path.resolve` is more realistic, but an extra explanation doesn't hurt.

**Comment by heisian** [comment]
Will do. Definitely yes, it is realistic, but put yourself in the position of a newbie who knows absolutely nothing about webpack, little about node, and is just trying to learn how to get started and it is **very** confusing to say:

"DON'T USE THIS SYNTAX."
"Example: wrap(THAT SYNTAX WE TOLD YOU NOT TO USE)"

**Comment by heisian** [comment]
..followed by a snarky-ass comment, "RTFM"
