### ISSUE TITLE
service worker & CORs issue in pwa app with webpack

### ISSUE THREAD

**Issue by didi0613** [webpack/webpack#4285]
![screen shot 2017-02-14 at 2 15 56 pm](https://cloud.githubusercontent.com/assets/10135897/22952010/32ec0504-f2c0-11e6-9623-fba9ae73792f.png)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I've met an issue in my PWA app when I was trying to upgrading to webpack v2. After getting a successful build and run in dev env, I got a console error saying:
Service worker has become redundant
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
This only affects dev environment. Can anyone please help?

**If the current behavior is a bug, please provide the steps to reproduce.**
Git clone/download https://github.com/electrode-io/electrode
Follow the instructions and runs the app in dev mode
Checkout to `webpack2.0` branch.
Open localhost:3000 and open console log

**What is the expected behavior?**
Console log should be no errors and service worker should register successfully.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: v2.2.0
node version: v6.9.4
OS: mac
browser: chrome Version 56.0.2924.87 (64-bit)

**Comment by didi0613** [comment]
@bebraw  Please let me know how can I share my configuration file here.

**Comment by bebraw** [comment]
@didi0613 It's good. Just noticed your repo. Thanks. 👍

**Comment by sheprdinc** [comment]
what was the resolution on this @bebraw @didi0613  ?

why is that there's a simple/easy work-around for webpack-dev-server, but not one for production?

i'm using axios, but could use fetch if necessary... to be honest, i care far more about why this issue is happening in production rather than in dev mode, but unfortunately all of my google searches and github searches return solutions only for devServer ... any one figured this out with a production setting in webpack? this cors issue is killing me, trying to get data from google maps api using restful endpoint, gmaps library not an option

for any one with help, thanks a ton!
