### ISSUE TITLE
Override async chunk names.

### ISSUE THREAD

**Issue by arackaf** [webpack/webpack#4287]
I chatted about this with @bebraw on gitter, and he said to bring it here as a feature request.  

The problem is that async chunks are given non-descriptive names by default, with no way to override, except by using the old CJS-based `require.ensure` code splitting api.

What would be ideal would be a way to let the developer come up with his or her own unique names for each async chunk.  Something like

```
output: {
    createAsyncChunkName: modulesContained => name
}
```

Where webpack would pass all the modules in an async chunk to the provided function, which would be responsible for generating a unique name.  I assume if the generated names are ever duplicated, webpack would just error out.

The use case boils down to being able to analyze build results.  My plan is to eventually get webpack in use at work, where we literally have hundreds of async split points.  I imagine there'd be value in having a feasible way to quickly identify which split point is in which chunk.

**Comment by timse** [comment]
there is something like this here i guess?
https://github.com/webpack/webpack/pull/3436

**Comment by jouni-kantola** [comment]
I don't know if this is related to this exact feature request, but I guess the solution for naming and resolving async chunks could solve my take on this as well. Let me know if you want me to address this as a separate issue.

As `import` or `system.import` is used the async chunks are prefixed with an enumerated ID/index. The consequence of this is that when additional chunks are added, order becomes important too preserve file names. In the long run, a lot of files will be cache busted even though the contents are not changed, but because the enumerated ID is changed.
File: `0.affjfjcmcm.js` becomes `1.affjfjcmcm.js` if webpack splits a chunk that gets ID `0`.

**Comment by arackaf** [comment]
One thought I just had: why not just name the async chunks the *same as* the full, resolved async-imported name, adjusted to be a valid filename? For example:

`System.import('./shared/tasks-modal');`

would create an async chunk named `app-tasks-shared-tasks-modal.js`.

**Comment by mischkl** [comment]
Also related: #2682, #1949
