### ISSUE TITLE
Nested route relative import fails

### ISSUE THREAD

**Issue by ishan28mkip** [webpack/webpack#4298]
Bug / Feature ( Can be both )

React-Router-Webpack Configuration
Assuming file loaders and public path are configured to output at root directory.

Suppose you are using react-router and having multiple level route nesting,
For e.g: abc.com/dashboard/overview

On this route you are displaying a component named Overview,
In this component I include an image using `import Success from ./success.png`
Now I write `<img src = { Success }/>`, this would fail to load image because the browser will try to find image at `abc.com/dashboard/success.png` whereas the image is at `abc.com/success.png`

This is because the browser assumes the path to be relative. To mitigate this problem I think the import should include a forward slash in the beginning to make it an absolute path.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
