### ISSUE TITLE
 Error of Can't resolve '[object Object]'

### ISSUE THREAD

**Issue by eldyvoon** [webpack/webpack#4299]
I got this error with one of my js

`Module not found: Error: Can't resolve '[object Object]' in 'C:\Users\My-Laptop\Projects\myapp
 @ ./resources/assets/app/entries/landing.js 6:0-45`

I don't think there's a problem with my entry's config. It's like this

`entry : { landing: ' ./resources/assets/app/entries/landing.js' }`

My landing.js is here http://pastebin.com/TkEJ3570

Need help and thanks! PS: I don't have issue using webpack 1 at all, had this problem migrating to webpack 2.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
