### ISSUE TITLE
http://localhost:8080/eaa07aac28a3946323b8217ac58959d5.png")marker-icon.png

### ISSUE THREAD

**Issue by fangjianming** [webpack/webpack#4300]
webpack打包之后出现的这个错误，有人遇到类似的问题吗？是配置出现的问题吗？

**Comment by fangjianming** [comment]
eaa07aac28a3946323b8217ac58959d5.png")marker-icon.png  使用的配置

test: /\.(jpg|png|gif)$/,
            loaders: [
                'file-loader', 
                'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
            ],

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
