### ISSUE TITLE
prefix specific css file urls paths

### ISSUE THREAD

**Issue by newasmod** [webpack/webpack#4301]
set webpac.config to prefix url in background-image: url(_prefix_- path)
so if i have in css file something like:
.limage09o { background-image: url('/img/image.png'); }
i want webpack to add prefix to url('/img/image.png') like:
url('../../../../img/image.png')

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
