### ISSUE TITLE
LoaderOptionsPlugin make webpack unusable?

### ISSUE THREAD

**Issue by Thstone37** [webpack/webpack#4321]
![image](https://cloud.githubusercontent.com/assets/11756943/23148678/272855c6-f822-11e6-87d3-21c5da45d75b.png)

**Comment by michael-ciniawsky** [comment]
Please use the ISSUE_TEMPLATE, but I assume it is for postcss-loader 😛 , since your are on `webpack` v2.2.1` and `postcss-loader` >= v1.0.0 supports webpack 2 please remove `LoaderOptionsPlugin` and 

```diff
+ {
+  test: /\.css$/,
+   use: [
+   'style-loader',
+   { loader: 'css-loader', options: { importLoaders: 1 } },
+   { loader: 'postcss-loader', options: { plugins: () => [...PostCSS Plugins] } }
+  ]
+ },
- plugins: [ new webpack.LoaderOptionsPlugin() ]
``` 

LoaderOptionsPlugin should only be used for loaders not supporting webpack 2. otherwise you dont need it :)

These question are also better suited for StackOverFlow 😛

**Comment by bebraw** [comment]
There's also a typo. Use `plugins` over `pulgins`. Please re-open at Stack Overflow.
