### ISSUE TITLE
webpack should force case on windows

### ISSUE THREAD

**Issue by tcoopman** [webpack/webpack#435]
I just had some strange errors after a typo in my require with react.

I had:

```
var React = require('React'); //instead of require('react')
```

On linux this will fail.
But as this is on windows this works, but later on this gave problems:

```
....
WARNING in ./~/react/lib/ReactServerRenderingTransaction.js
There is another module with a equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/React/lib/ReactServerRenderingTransaction.js
There is another module with a equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/react/lib/onlyChild.js
There is another module with a equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
....
```

Can webpack force the case of imports on windows, so the require fails?

**Comment by Industrial** [comment]
It doesnt matter if a module name is the same as another module name. It matters that their relative and absolute paths are different. If you stick it all in an object and use only the filename part, of course you get clashes. why doesn't webpack just do:

```
var webpackObject = {
  'some/path/to/my/module': function(){ /*myModule*/ },
  'some/path/to/my/other/Module': function(){ /*myModule*/ }
}
```

This is totally acceptable but for webpack it is not acceptable. That's a problem. :)

**Comment by axelson** [comment]
+1 for getting more info into the error message. Currently I'm staring at:

    WARNING in ../~/script-loader/addScript.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    WARNING in ../~/Script-loader/addScript.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

Which makes it difficult to track down which module is causing the issue. I'd rather not resort to running on Linux just to find the problem...

**Comment by axelson** [comment]
I ended up doing a manual binary search on my modules and found I was calling `require("Script!./myfile.js")` instead of `require("script!./myfile.js")` which makes some sense given the warning but was not what I expected at all. I thought it was something that was being loaded through the script loader, not the script loader itself.

**Comment by Swivelgames** [comment]
The biggest issue I see is that when these discrepancies exist, Webpack treats them as different modules, and loads both of them. We run into major issues because (1) we don't know the issue exists due to the warning/error messages, (2) we do NOT want multiple copies of the same module loaded and packed into our code. e.g. I don't want module 1.2 and Module 1.2 loaded, because that doubles the file size, transfer size, etc... because of that minor discrepancy.

Why not treat them the same (as it should), and simply throw a warning if the case is now lowercased? There's no reason why Webpack should be including and packing multiple instances of the same module+version combo in a single package.

**Comment by sokra** [comment]
Using the wrong casing is wrong, because there are case-sensitive filesystems, that won't find the file at all. This means using the wrong casing would break on cases-sensitive filesystems (i. e. production linux server).

It's better to emit an error in every case than to emit only an error on case-sensitive filesystems.

**Comment by Industrial** [comment]
Don't design for the users that will not comprehend the difference between case sensitive and case insensitive. They need to learn the difference by making mistakes. Design it for the poor sysadmin/devops that is going to have to deploy their toys on a real system, imho.

**Comment by Swivelgames** [comment]
@sokra @Industrial I can get on board with that. If we error out, instead of warning the user, than Webpack won't even get to the point of packaging the same module twice, which solves the issue.

The final issue we're left with is the current message's ambiguity, which does not facilitate a resolution. It's not a difficult correction to make, regardless of skillset and experience, so I can definitely agree that ERRORing out (as opposed to warning the user, which allows the process to continue) would be an effective means for ensuring resolution. However, the error message still definitely needs to be updated to be less ambiguous.

(1) Fatal instead of Warn (on all platforms)
(2) Disambiguate error/warning message

:smile: :+1:

**Comment by istarkov** [comment]
+1  `(1) Fatal instead of Warn (on all platforms)`

**Comment by KidsKilla** [comment]
Friendly bump.

**Comment by vsych** [comment]
+1 and on os x

**Comment by LeiZeng** [comment]
+1 (1) Fatal instead of Warn (on all platforms)

on os x

It breaks the compiling eventually when try to deploy our project on Linux.

**Comment by Urthen** [comment]
Since this bug seems to have been passed over by webpack core, we've got a plugin in the meantime to force case sensitivity: https://github.com/Urthen/case-sensitive-paths-webpack-plugin

It uses a fatal error whenever you try and import a module with the wrong case - even if you don't ever import the module with the correct case.

**Comment by TheLarkInn** [comment]
@Urthen Thanks for creating the plugin. Would you like to PR this into core as a feature now? Going to mark this as Help Wanted. (Pruning issue list).

**Comment by Swivelgames** [comment]
@TheLarkInn @Urthen Any updates on this? Would be awesome to have this. :) This is still an issue, unfortunately.

**Comment by mc-zone** [comment]
I'd like to work with it. But how could we detect case wrong with high efficiently? It may bring performance decrease due to bunch of disk read.

Node v9.2 has add an implementation [`fs.realpath.native`](https://nodejs.org/dist/latest-v9.x/docs/api/fs.html#fs_fs_realpath_native_path_options_callback) that can read real path with case-sensitive for a file. I think it performance maybe better than readdir iterative for all requests, but can't use below v9.2.

**Comment by mc-zone** [comment]
Also add a resolve failed check in webpack/enhanced-resolve#137. Just triggered when request not found in CASE-SENSITIVE env and using `readdir`. Not sure how could we do it elegantly in CASE-INSENSITIVE env.

**Comment by Urthen** [comment]
The (in)efficiency of my plugin is part of the reason I haven't decided to try and port it to Webpack. Right now the plugin works by, for each path, checking the contents of it's parent directory (which will, so far in practice, always return the correct casing even on case-insensitive systems) and seeing if one matches. This is then performed recursively up to the current working directory.

It has intelligent caching to prevent it from repeatedly checking the same information. It saves the contents of each directory, so when there are two or more files in the same directory, it only reads that directory's contents once. 

In practice it generally reads all (Javascript source-containing) directories in the project once. It's not too inefficient, but it certainly isn't elegant. If we're OK with this behavior and want to add it in as an internal official optional plugin, I can take a look at that.
