### ISSUE TITLE
chrome vue-cli 2.0 npm run dev error

### ISSUE THREAD

**Issue by BusyHe** [webpack/webpack#4350]
vue-cli 2.0 

npm run dev 

![image](https://cloud.githubusercontent.com/assets/17348825/23240571/25807e46-f9a9-11e6-9efa-87a84e497a56.png)

how it happened?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
