### ISSUE TITLE
加载 中文名称的文件 有问题

### ISSUE THREAD

**Issue by qq645381995** [webpack/webpack#4355]
在本地开发调试环境下 用了CopyWebpackPlugin 把 csv格式的文件复制到一个目录下 让网页可以下载该文件
但是 文件名是英文的可以下载，但是文件名称改成中文就不能下载 
是 webppack 对中文不支持吗？

**Comment by timse** [comment]
oks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
