### ISSUE TITLE
append: true for SourceMapDevToolPlugin make an error

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4375]
webpack2:

```javascript
{
plugins: [
		new webpack.SourceMapDevToolPlugin({
			columns: true,
			append: true,
			exclude: /node_modules/
		})
	]
}
```

![image](https://cloud.githubusercontent.com/assets/1060733/23308737/1e460fb2-fae7-11e6-8232-7a342aace891.png)

if I set `append` to false,the error will not appear.

**Comment by zzzgit** [comment]
Is it relay to the mode name of `devtool`,which mode should I use?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
