### ISSUE TITLE
certain complex dependency chains don't resolve

### ISSUE THREAD

**Issue by calvinmetcalf** [webpack/webpack#4378]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
in certain circumstances calling `require('stream').Transform` give an object
**If the current behavior is a bug, please provide the steps to reproduce.**
see this [repo](https://github.com/calvinmetcalf/webpack-bug)

**What is the expected behavior?**
it should be a Transform stream constructor 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@2.2.1

split off from #272 also see nodejs/readable-stream#237

**Comment by bebraw** [comment]
Can you confirm this against webpack 2?

**Comment by ericgundrum** [comment]
@bebraw, I have confirmed the behavior is the same in webpack 1.14.0 and 2.2.1.

**Comment by calvinmetcalf** [comment]
confirmed as well and updated the demo repo, you don't even need through2, calling

```js
var Transform = require('readable-stream/transform');
var TransformStream = require('stream').Transform;
```

gives an empty object for TransformStream

**Comment by bebraw** [comment]
Thanks for confirmation. Now the big question is why. I wonder what's so special about Node `stream` in this case. Does it work without that first import?

**Comment by calvinmetcalf** [comment]
yes it does it also works if you replace the second line with a call to `var TransformStream = require('readable-stream').Transform;`, bearing in mind that all `require('stream')` does is (more or less)

```js
module.exports = Stream;
...
Stream.Readable = require('readable-stream/readable.js');
Stream.Writable = require('readable-stream/writable.js');
Stream.Duplex = require('readable-stream/duplex.js');
Stream.Transform = require('readable-stream/transform.js');
Stream.PassThrough = require('readable-stream/passthrough.js');
```

it could possibly be related to [this part of readable](https://github.com/nodejs/readable-stream/blob/4dbe6e20051e44025d3cbec3ed9603483d8b27cb/lib/_stream_readable.js#L28-L35) which is in there to avoid bundling in the streams library unless the user does first because we only actually need it in cases of people doing `readable instanceof stream`

**Comment by bebraw** [comment]
Maybe the next question is, can the behavior be confirmed somehow without `stream` while constructing a similar scenario.

Does webpack even capture `Stream = require('st' + 'ream');`?

**Comment by ericgundrum** [comment]
I spent many hours in the relevant webpack code yesterday. I do not think there is anything special about streams to set this up. (I'll try to create a repo to demonstrate it without streams.)

To create a module, webpack first puts an empty object in the cache, then it begins executing the code to fill in `module.exports`. In the problem case, the dependency chain leads to another call to create this first module. At that point, webpack finds the module in the cache and returns it, but that is still the empty object because the code that fills in the exports is still loading the dependencies.

If webpack were to check that the module had been loaded instead of just in the cache, it would see `module.l` is false.

[This webpack template code](https://github.com/webpack/webpack/blob/93ac8e9c3699bf704068eaccaceec57b3dd45a14/lib/MainTemplate.js#L60) is the function controlling all this.

**Comment by bebraw** [comment]
I wonder what's the right fix. It's that cache bit that's biting here. Would treating it somehow differently be the key?

Basically you have a graph like:

A -> B
B

And it's that first part that's stalling it. Does this mean the nested case has to be detected?

**Comment by ericgundrum** [comment]
@bebraw It seems more complicated. I'm still trying to wrap my head around it. I've not been able to create the same error with a simple cycle. There is something subtle about the streams case that triggers this, but I've not found exactly what yet.

**Comment by ericgundrum** [comment]
I've had no luck reproducing this without streams. I created a [repo](https://github.com/ericgundrum/depends-cycle.git) without streams to demonstrate as best I could the cycle I found in the streams example.

I found that doing a [redirect](https://github.com/ericgundrum/depends-cycle/blob/master/b_redirect.js) from one require to another is important to generate the empty object when there is a cycle. But without streams, webpack shows the same results as node: an empty object representing the module doing the redirect. I suspect node's behavior with streams differs because `stream` is an internal module -- no dependency cycle.

As far as I can tell webpack behaves the same as node in all cases. Browserify matches node when the redirect file contains nothing but a single `require`. When I added some logging (and changed from `exports` to `module.exports`), its behavior changed. (See the git log if this interests you.)

Using streams seems to be a special case. Maybe this whole thing belongs back at [nodejs/readable-stream#237](https://github.com/nodejs/readable-stream/issues/237).

**Comment by sokra** [comment]
browserify and webpack handles `require("str" + "eam")` different:

* webpack handles it like `require("stream")` and will load the module.
* browserify doesn't capture it and will throw instead.

Constructs like `try { require("str" + "eam") }` are sometimes used as browserify hack to exclude a module from the bundle. But this is bad. Instead use the `browser` field in package.json to exclude modules from the bundle. Or better don't rely on such dependencies!

**Comment by sokra** [comment]
> To create a module, webpack first puts an empty object in the cache, then it begins executing the code to fill in module.exports. In the problem case, the dependency chain leads to another call to create this first module. At that point, webpack finds the module in the cache and returns it, but that is still the empty object because the code that fills in the exports is still loading the dependencies.

This is defined this way in the CommonJs spec. In case of a cycle require may return an unfinished object.

**Comment by calvinmetcalf** [comment]
> browserify and webpack handles require("str" + "eam") different:
> 
>     - webpack handles it like require("stream") and will load the module.
>     - browserify doesn't capture it and will throw instead.
> 

@sokra this is not correct, browserify will also load it if it's available in the bundle but will not include it in the bundle soley due to this call, the call throws if it was never loaded.  The whole point of this being here is so that if somebody else includes the `streams` module readable streams will be able to inherit from it (so as not to break `foo instanceof Stream` checks), but if you just require `readable-streams` you won't get the outer streams stuff you don't need.

**Comment by sokra** [comment]
> @sokra this is not correct

no it's not true.

``` shell
$ cat test.js
var internalStream = require("./test2");
var stream = require("str" + "eam");
console.log(stream === internalStream);

$ cat test2.js
module.exports = require("stream");

$ node_modules\.bin\browserify test.js > bundle.js

$ node bundle.js
false
```

**Comment by calvinmetcalf** [comment]
@sokra you are correct, which is embarrassing as I wrote the code in question, this means though that webpack works like I assumed browserify did and shouldn't have an issue with cycles considering 

1. node doesn't
2. the code used to just have a straight stream require there and there were not any problems

**Comment by calvinmetcalf** [comment]
so fyi the overly clever dependency stuff has been taken out of readable-stream and we just use pkg.browser to handle this sort of stuff, so you cant reproduce against the most recent version of readable-streams
