### ISSUE TITLE
Laravel-mix(webpack) require dynamic vue component error

### ISSUE THREAD

**Issue by lichnow** [webpack/webpack#4387]
I use laravel-mix `npm run dev`,and get some errors,webpack can not build

in tool.js
```
module.exports = {
	view: function(view) {
        const template = 'template';
        try {
            return resolve => require([`./template/${template}/views/${view}`], resolve);
        }catch(ex) {
            console.log(ex);
        }
	}
};
```

in routes.js

```
export default function () {
    return {
        path: '/',
        component: require('tools').view('DashBoard.vue'),
        name: 'dashboard'
    }
}
```

error1 `Critical dependency: the request of a dependency is an expression`
error2 `app.js:12 Uncaught Error: Cannot find module "."`

please help me,Thx

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
