### ISSUE TITLE
Performance warning file size is wrong

### ISSUE THREAD

**Issue by blade254353074** [webpack/webpack#4421]
![image](https://cloud.githubusercontent.com/assets/9346008/23577712/8d6fce26-0101-11e7-9dd1-f42e7fe5dae0.png)
![image](https://cloud.githubusercontent.com/assets/9346008/23577710/6ac6c938-0101-11e7-900a-2959c87094a2.png)

**Comment by bebraw** [comment]
Can you provide a little project to study? Thanks.

**Comment by blade254353074** [comment]
Yeah...

https://github.com/blade254353074/Reantx

And I found an another problem. I'm still checking on it.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by bebraw** [comment]
@blade254353074 Ok. Please open another issue and fill in the details really carefully. 👍

**Comment by blade254353074** [comment]
Sorry, my bad...
