### ISSUE TITLE
Add Analytics tracking

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4437]
**Do you want to request a *feature* or report a *bug*?**
Feature/Enhancement

**If this is a feature request, what is motivation or use case for changing the behavior?**
Motivation: We could benefit by understanding how people use webpack, in a variety of ways. By using Google Analytics we could track (if the user decides to opt-in), how they leverage webpack, the sizes of their bundles etc. Right now, we really know nothing beyond npm trends, npm stats, and random polls. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by mmckeaveney** [comment]
Hi Sean, I'm looking to get involved and submit a first PR. Have you started work on this, or is it something I could pick up? I'd probably need a bit more information exactly around the sort of metrics that need to be collected - but I'm willing to grab a shovel :) Thanks.

**Comment by ScriptedAlchemy** [comment]
Ive been very tempted to add some post-install analytics to my larger projects. But have been hesitant due to the blowback I've seen in the past. Could this be opt-in, like we usually get when installing apps? 

"help improve this product with anonymous telemetry" or something like that? I know Next.js has telemetry enabled by default - however, i am not sure what they are tracking. 

The community seems quite sensitive to being tracked via OSS projects

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy we should discuss what we should collect, memory/cpu usage is very interesting, but it potential do build slower

**Comment by ScriptedAlchemy** [comment]
Agreed. I do believe that data, especially around build performance profiling would be very valuable. Ill give this some thoughts around potential data stats collection

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
Still make sense
