### ISSUE TITLE
how to export umd module has amd define name

### ISSUE THREAD

**Issue by gastrodia** [webpack/webpack#4439]
now the module export is :
```
else if(typeof define === 'function' && define.amd)
		define(["react"], factory);
```

but I want

```
else if(typeof define === 'function' && define.amd)
		define('skong-react-ui',["react"], factory);
```

where to config this?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
