### ISSUE TITLE
Recommended configuration for style-loader misleading

### ISSUE THREAD

**Issue by jAndreas** [webpack/webpack#4442]
**Do you want to request a *feature* or report a *bug*?** 

report a bug

**What is the current behavior?**

Wrong documentation or wrong code. The "useable" feature from the style-loader won't get called if you set it up with the recommended configuration. The style-loader doesn't understand the "options" object, so creating an option field with the property "useable: true" doesn't affect anything. You have to pass the loader string as "style-loader/useable" in order to make it work, which is contrary to https://webpack.js.org/loaders/style-loader/#recommended-configuration

**Comment by sokra** [comment]
It looks like this issue is *not directly related* to this project. We try to only keep issues directly related to this project in the issue tracker. Therefore I'm closing this issue.

Please file the issue on **webpack-contrib/style-loader**.

You can easily copy your text if you click on *"edit"* on this issue. Also make sure to follow the issue requirements of the target project when pasting this issue.
