### ISSUE TITLE
UglifyJsPlugin compress `with:0%`  to `width:0` , that cause some style problems

### ISSUE THREAD

**Issue by haoranw** [webpack/webpack#4486]
webpack:v2.2.1

i'm using UglifyJsPlugin to compress css files,
and add `width:0%` in the style of flexbox ,to compatible with some old  browsers(that only support older version of flexbox ) 

But UglifyJsPlugin compress `width:0%`  to `width:0` , that cause some style problems

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
