### ISSUE TITLE
A problem about code splitting

### ISSUE THREAD

**Issue by cage1618** [webpack/webpack#4488]
Nodejs version: 6.2.1
webpack version: 1.13.3

I use React + React-router in my project and with webpack code splitting. 
But the below code do not splitting:
```javascript
childRoutes: [
    ...['page1', 'page2'].map((p) => {
        return {
            path: p,
            getComponent(nextState, callback) {
               return require.ensure([], (require) => {
                  return callback(null, require('./' + p + '.js'));
               });
            }
        };
    })
]
```

If I write code for every page, it's work well.
```javascript
childRoutes: [
  {
     path: 'page1',
     getComponent(nextState, callback) {
         return require.ensure([], (require) => {
             return callback(null, require('./page1.js'));
         });
     }
  },
  // page2 route
]
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
