### ISSUE TITLE
webpack2 error：“Path must be a string, Received undefined”

### ISSUE THREAD

**Issue by yellowfrogCN** [webpack/webpack#4495]
![image](https://cloud.githubusercontent.com/assets/20294717/23995045/be75f916-0a82-11e7-93cc-0a1dbfeb91e1.png)

webpack construction is too complex, simply can not find the reason, can you tell me where the problem is,Problems that may occur in the module. thank you！

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
