### ISSUE TITLE
DefinePlugin does not work with ES6 files

### ISSUE THREAD

**Issue by nojvek** [webpack/webpack#4498]
```js
class Constants {
    constructor() {
        this.apiService = API_SERVICE
    }
}
```

I am using `var BABEL_LOADER = 'babel?plugins[]=transform-es2015-modules-commonjs'` as the js loader.

This seems to break the parser for DefinePlugin and the replacement never takes place. The failure is silent and no errors are given.

**Comment by langpavel** [comment]
It works. Try digging more deeply ;-)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
