### ISSUE TITLE
FR: webpack should throw error if no referenced dlls

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4506]
When using DllPlugin and DllReferencePlugin in combination. The DllReferencePlugin should check if imports in the dll manifest.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
