### ISSUE TITLE
Feature: Reuse DLL bundles for production rebuild - export tree-shakable es2015 module format

### ISSUE THREAD

**Issue by Phoscur** [webpack/webpack#4516]
As I'm trying different starter projects for webpack2 with angular, trying to refactor them a bit, to create a cluster of dependencies, making an extended framework for reuse in multiple projects. 

I'm wondering, if those DLL bundles, that speed up development build time, could be reused long term for production builds, which still want to get tree-shaken. That's why I would expect a new DLL bundle export format to be needed.
Obviously, these es2015 DLLs won't really work for development in browsers besides Edge.

Any opinions on this are welcome!

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by Phoscur** [comment]
Mhh yeah I get it closing as this is a question disguised as a feature idea. I removed The template, because it only lenghtened my issue, the template questions are geared towards Bugs.. 
I take it you are still willing to discuss, so I will repost with clear focus on the Feature.
