### ISSUE TITLE
Access to a module original source code

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#4522]
How can I get an access to a module source from my plugin?
`someModule.source().source()` returns a generated code (where `require` -> `__webpack_require__`)
I can use `someModule.source()._source.source()`, but `_source` is like a "protected" field and not garantee that it will remain in feature versions of webpack.
Any ideas? Except `fs.readFile` because there are modules that generate from the loaders and have not a physical file.

Also i can use `someModule.source().map().sourcesContent[0]`
But why `sourcesContent` is array? Can it contain more than 1 element?

Or `someModule.source().listMap().children[0].originalSource`
The same question: why `children` is array? Can it contain more than 1 element?

Maybe the best solution is to create a PR and add `originalSource` method that being a public and returns `_source` value?

There is no help in Gitter :(

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by smelukov** [comment]
@sokra Oh, I'm sorry...
Created a new issue [#4526](https://github.com/webpack/webpack/issues/4526)
