### ISSUE TITLE
Webpack strips out exports from define, introducing circular dependency problems

### ISSUE THREAD

**Issue by richardspence** [webpack/webpack#4555]
Webpack when bundling with umd does not handle `exports` and therefore introduces circular dependency problems.

## Actual
in app.bundle.js
```js
	else if(typeof define === 'function' && define.amd)
		define([dependencies], factory);
```
## Expected
```js
	else if(typeof define === 'function' && define.amd)
		define(['require', 'exports', dependencies], factory);
...
var result = webpackJsonp([0,2],{...});
for(prop in result ){
    exports[prop]=result[prop];
}
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by richardspence** [comment]
I thought I answered all the relevant information in the template.  Will create a new issue
