### ISSUE TITLE
在windows 10 使用webpack打包不能打包

### ISSUE THREAD

**Issue by zhangjinsong** [webpack/webpack#4571]
在windows 10使用webpack命令会提示选择编辑器，打开后编辑webpack.js。注意是只要包含webpack命令的都会这样
![image](https://cloud.githubusercontent.com/assets/12949599/24323413/e1b43f8a-11af-11e7-92cb-cf25918c42af.png)

**Comment by zhangjinsong** [comment]
![image](https://cloud.githubusercontent.com/assets/12949599/24323422/f40ce79a-11af-11e7-9b57-ae3c9c8ea7ea.png)

**Comment by zhangjinsong** [comment]
![image](https://cloud.githubusercontent.com/assets/12949599/24323447/35cfa2d0-11b0-11e7-8681-0d56ce1bad11.png)

**Comment by michael-ciniawsky** [comment]
Update to webpack v2.3.**2**

**Comment by michael-ciniawsky** [comment]
And please write in english (via Translator etc.), bad/generated english is still way better than mandarin

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
