### ISSUE TITLE
[Help wanted] Webpack exclude custom file in 'production'

### ISSUE THREAD

**Issue by Catx7** [webpack/webpack#4579]
Hello,

I want to exclude a file when I am building the project and creating '/dist' folder.
File path is something like this. 'src/utils/devFile.js'
The file contains some paths that I want to be excluded from production files.It is ok to be used for devs only.

`// ------------------------------------
// Bundle Output
// ------------------------------------

webpackConfig.output = {
  filename: `[name].[${config.compiler.hashType}].js`,
  path: paths.base(config.distDir),
  publicPath: config.compiler.publicPath
};`

This is my bundle output.
How can  I exclude that file when running production env.
I am using babel-node too.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
