### ISSUE TITLE
webpack/lib/optimize/CommonsChunkPlugin.js --- error bug fix

### ISSUE THREAD

**Issue by peterlevel1** [webpack/webpack#4593]
filename: webpack/lib/optimize/CommonsChunkPlugin.js 
line: 334 
for(let entrypoint of chunk.entrypoints) {

you should add if (chunk.entrypoints) { ... }
before----- for(let entrypoint of chunk.entrypoints) {

webpack version: 2.3.2
download from npm 

**Do you want to request a *feature* or report a *bug*?**
a *bug*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
nodejs version: 6.9.2 
webpack version: 2.3.2

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.`

Or send a PR
