### ISSUE TITLE
What guarantees does entrypoints in Stats have?

### ISSUE THREAD

**Issue by klavs** [webpack/webpack#4598]
`webpack --json --profile` reports a chunk more than once for a single entrypoint under `"entrypoints"`.

```json
"entrypoints": {
    "site": {
      "chunks": [
        5,
        1,
        0,
        null,
        5,
        4
      ],
      ...
    }
}
```

My first impression was that these chunks are ordered and not repeating. What guarantees does an entrypoint have in this context?

**Comment by sokra** [comment]
The `null` looks weird. A bug?

**Comment by klavs** [comment]
@sokra, I do expect `null` to be there, because I am using `CommonsChunkPlugin` to split off vendor modules that, in this case are not present, so no chunk is created. (A similar setup can be seen here: https://github.com/klavs/advanced-webpack-commons-chunk-example/blob/master/webpack.config.js)

**Comment by klavs** [comment]
I am more interested in why chunk 5 is there twise. Chunk 5 is a `manifest` chunk.

**Comment by sokra** [comment]
I guess the duplicate 5 is caused by the `null`. `5 < null = NaN` this breaked sorting...

We should filter out `null` values here.

**Comment by klavs** [comment]
Actually that might not be the root cause.
`webpack@2.2.1` does not produce duplicates even if there is `null`.
`webpack@2.3.2` does have duplicates in both cases.

**Comment by sokra** [comment]
Could you create a minimal repro case for this?

**Comment by klavs** [comment]
Sure, there is already a small repo I linked earlier.
https://github.com/klavs/advanced-webpack-commons-chunk-example

**Comment by sokra** [comment]
You CommonsChunk configuration is not supported. You are only allowed to select entry chunks for the commons chunk plugin. After that chunks are converted into non-entry chunks and the commons chunk become an entry chunk. This way it's not allowed to select the same chunk twice for multiple commons chunks.

So this is technically outside of the supported scope. Technically webpack should error here.

But hey it's working fine on runtime...

The error occurs because before the manifest chunk is created there are three entry chunks: common-vendor, site-vendor, admin-vendor. (which is theoretically wrong, because an entrypoint should only have a single entry chunk.) So the manifest chunk is added to every Entrypoint of these chunks, which is twice for both.

We could add a check [here](https://github.com/webpack/webpack/blob/master/lib/optimize/CommonsChunkPlugin.js#L335) or [here](https://github.com/webpack/webpack/blob/master/lib/Entrypoint.js#L18) to prevent this.

---

Correct support in the commons chunk plugin is difficult because we only have the notation of `any of these chunks is loaded before this chunk` (`parents`) but missing the notation of `all of these chunks are loaded before this chunk`. This is needed to add the relation correctly. If we add this relationship, we will have to add support for it in every optimization too...

cc @timse

**Comment by sokra** [comment]
The `null` should be eliminated. When removing a chunk we don't remove it from the entry points. That's a bug.

**Comment by timse** [comment]
ill look into why the duplication now appears. However commonschunk is a tricky beast 😨

**Comment by timse** [comment]
this should reestablish the behaviour as in 2.2.1 (https://github.com/webpack/webpack/pull/4615)

no idea why i this change happend.
