### ISSUE TITLE
Module not found: Error: Can't resolve './foo.json'

### ISSUE THREAD

**Issue by sughanpandita** [webpack/webpack#4631]
module.exports = {
  entry: {
    app: './build/aws.js',
    libraries: ['./src/libraries.js']
  },

  resolve: {

    modules: [
      'node_modules',
      path.resolve('./build'),
      path.resolve('.'),
      path.resolve('../../../lib')
    ]
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'libraries',
      filename: 'lib.bundle.js'
    })
  ],

  output: {
    path: './dist',
    filename: 'bundle.js'
  },
     loaders:[

         { test: /vendor\/.+\.(jsx|js)$/,
             loader: 'imports?jQuery=jquery,$=jquery,this=>window',
         }

     ]
};

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
