### ISSUE TITLE
Fails loading webpack.config.coffee (SyntaxError)

### ISSUE THREAD

**Issue by samme** [webpack/webpack#4639]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

See <https://github.com/samme/webpack-config-coffee>.

Results of `npm run build`:

```
> webpack
webpack.config.coffee:1
(function (exports, require, module, __filename, __dirname) { path = require 'path'
                                                                             ^^^^^^
SyntaxError: Unexpected string
[…]
```

**What is the expected behavior?**

<https://webpack.js.org/configuration/configuration-languages/> suggests webpack.config.coffee should load successfully.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node 4.4.7, webpack 2.3.3

**Comment by timse** [comment]
are you using `node-interpret` as specified in the doco?

**Comment by samme** [comment]
That part is ambiguous. But `npm install -D interpret` makes no difference. Is there another step?

**Comment by timse** [comment]
well i doubt a simple install will do the trick. You need to tell node to use it.
Anyways I doubt this is a webpack problem, stupid question, but why use coffescript ?:)

**Comment by samme** [comment]
See #956. It sounds like this is supposed to be automatic.

**Comment by samme** [comment]
Also, webpack has found `webpack.config.coffee` on its own. The problem is it's interpreting it as JS (hence the SyntaxError).

**Comment by timse** [comment]
yeah, i learned that myself :D well then it seems to be a bug then :)

**Comment by samme** [comment]
Thanks for checking anyway 😃

**Comment by ch1c0t** [comment]
I can reproduce it only for CoffeeScript. Your repo works just fine with LiveScript after I did `mv webpack.config.coffee webpack.config.ls`.

**Comment by sokra** [comment]
Could be a bug in node-interpret or coffeescript...

**Comment by samme** [comment]
```
SyntaxError: Unexpected string
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (webpack-config-coffee/node_modules/webpack/bin/convert-argv.js:96:18)
```

**Comment by lucastheisen** [comment]
I know this issue is specifically about `coffeescript`, but I am having a very _similar_ problem with `typescript`.  It is clear, according to the [documentation](https://webpack.js.org/configuration/configuration-languages/), and the [source code](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L25-L37), that you just need to import the implementation you desire to use from the list available in node-interpret (though the name node-interpret is confusing because the [git project is js-interpret](https://github.com/js-cli/js-interpret), and the [npm module is interpret](https://www.npmjs.com/package/interpret)).  I include the implementation [ts-node](https://www.npmjs.com/package/ts-node) as a devDependency and it runs my `webpack.config.ts` but fails due to an incompatible target module type (es2015, and node only _currently_ supports commonjs).  I wrote up my problem in [this issue on ts-node](https://github.com/TypeStrong/ts-node/issues/313).  I think we may need a way to customize the behavior of interpret, or a way to specify a custom map instead of the one provided by interpret...  Still thinking through how though.

**Comment by lucastheisen** [comment]
It might be worth noting, that this approach appears to be [deprecated in node](https://nodejs.org/api/globals.html#globals_require_extensions):

> **Deprecated** In the past, this list has been used to load non-JavaScript modules into Node.js by compiling them on-demand. However, in practice, there are much better ways to do this, such as loading modules via some other Node.js program, or compiling them to JavaScript ahead of time.
> 
> Since the module system is locked, this feature will probably never go away. However, it may have subtle bugs and complexities that are best left untouched.
> 
> Note that the number of file system operations that the module system has to perform in order to resolve a require(...) statement to a filename scales linearly with the number of registered extensions.
> 
> In other words, adding extensions slows down the module loader and should be discouraged.

So perhaps this feature should be removed from webpack as it stands and another approach should be taken...

**Comment by samme** [comment]
[Docs now show](https://webpack.js.org/configuration/configuration-languages/#coffeescript) that `npm i -D coffee-script` is also required.
