### ISSUE TITLE
Very sorry showing from "node-libs-browser"

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#4640]
**Do you want to request a *feature* or report a *bug*?**

Bug/feature

**What is the current behavior?**

Right now, I am looking to mock the majority if not all Node.js modules for the browser.
By default Webpack looks to:  'node-libs-browser/X'

```js

  node: {
    assert: 'empty',
    buffer: 'mock',                  // supported
    child_process: 'empty',
    cluster: 'empty',
    console: 'mock',         // supported
    constants: 'empty',
    crypto: 'empty',
    dgram: 'empty',
    dns: 'mock',                // supported
    domain: 'empty',
    events: 'empty',
    fs: 'empty',
    http: 'empty',
    https: 'empty',
    module: 'empty',
    net: 'mock',                //supported
    os: 'empty',
    path: 'empty',
    process: 'mock',         // supported
    punycode: 'mock',
    querystring: 'empty',
    readline: 'empty',
    repl: 'empty',
    stream: 'empty',
    string_decoder: 'empty',
    timers: 'empty',
    tls: 'mock',             // supported
    tty: 'mock',            // supported
    url: 'empty',
    util: 'empty',
    v8: 'mock',        // supported
    vm: 'empty',
    zlib:'empty',
  }
```

right now, it only supports like 7 out of the ~25 core modules...
is there something I am missing? Can I help create these mocks/polyfills? I would be glad to help!...

**Comment by sokra** [comment]
see webpack/node-libs-browser repo.

btw. the values translate into the following:

`true`: Use a full replacement which tries to provide equal behavior like the node.js module
`"mock"`: Use a minimal replacement that doesn't provide any useful behavior but doesn't crash on load
`false`: Don't use a replacement, it will error when you try to load it.

**Comment by ORESoftware** [comment]
hmmm, I will try true instead of "mock" for some of these...

**Comment by ORESoftware** [comment]
@sokra I have my own fs shim/polyfill that I would like to use. How can I use it with Webpack to patch fs in the browser? There is currently no fs shim in the node-browser-libs project and that's a big problem for me. Please lmk thanks.

**Comment by jhnns** [comment]
Actually, the [list of supported (or half-supported) node core modules is longer](
https://github.com/webpack/node-libs-browser) :grin: (thanks to the browserify community):

![bildschirmfoto 2017-04-05 um 11 09 44](https://cloud.githubusercontent.com/assets/781746/24698305/6da2069c-19f0-11e7-8345-d7ab86d2fc82.jpg)

Not supported modules are modules that cannot be implemented in a compatible way inside the browser.

Shimming the `fs` module is exceptional hard because there is no official fs access inside the browser. If you want to access files on your server, you need to do this on build time (in case your bundle is built on the server). In this case, it's better to use the [require context feature](https://webpack.js.org/guides/dependency-management/#require-context) where you can specify a regular expression what files you want to include inside the bundle. Be careful, this can make your bundle very big because it includes every file inside that directory that matches the regexp.

**Comment by ORESoftware** [comment]
@jhnns @sokra 

thanks - it's very important for me to be able to create my own shims and polyfills.

TBH, some of these "official" ones on the list that @jhnns do not work well or do not fit my use case at all.

What I need to be able to do is tell Webpack to use my polyfills, e.g.:

```js
// webpack.config.js

node: {
  assert: true,
  fs: 'oresoftware/my-fs-polyfill',
  path: 'oresoftware/my-path-polyfill'
}
```

this is very important to me, and this will be of benefit to the community at large.

the most important thing to be aware of here, is that there is no official polyfill for fs - but I have one, that works for me!

I want to use it with Webpack. How can I do that? Is there any docs for this? thanks!

**Comment by ORESoftware** [comment]
@jhnns I have a specialized shim/polyfill for fs that will work for my use case - I am looking for a way I can use my shim instead of the non-existent official shim. I guess `aliases` might work?

**Comment by ORESoftware** [comment]
@jhnns thanks, nevermind, I think you answered my question on another thread -` resolve.alias` should work, thanks!
