### ISSUE TITLE
tree shaking donot work for es6 class

### ISSUE THREAD

**Issue by ok111net** [webpack/webpack#4649]
I import some es6 class,but not use it,and then build it with webpack,but this es6 class is all in my code,the tree shaking isnot work! but import functions it work well.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
