### ISSUE TITLE
Critical dependency: the request of a dependency is an expression.

### ISSUE THREAD

**Issue by rublev** [webpack/webpack#4657]
I am getting this error for a lot of the libraries I'm using. It is getting quite ridiculous and I'm debating if at this point I should just drop back to webpack1 and wait for this all to blowover.

I'm using webpack 2.3.2 and webpack-dev-server 2.4.2.

It seems like webpack has no problem with dynamic imports, it just has an issue when a context can't be established?

Does anyone have any ideas how to fix these errors without dropping back to webpack1?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by rublev** [comment]
@sokra My bad I'm still terrible at this issue stuff. Will do.
