### ISSUE TITLE
I tried the webpack-closure-compiler aka PLOVR

### ISSUE THREAD

**Issue by TyrfingMjolnir** [webpack/webpack#4662]
**Do you want to request a *feature* or report a *bug*?**
Probably bug

Sad :-(
**What is the current behavior?**
java error

**If the current behavior is a bug, please provide the steps to reproduce.**

https://asciinema.org/a/7gbdlwkvzurbqaqglmohsxofu

https://asciinema.org/a/7gbdlwkvzurbqaqglmohsxofu

webpack-closure-compiler

**What is the expected behavior?**
PLOVR compiled output

**If this is a feature request, what is motivation or use case for changing the behavior?**
Have a real compiler run for production deployment.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

FF Dev Ed 54.0a2 (2017-03-19) (64-bit)

$ node -v
v7.7.3

$ uname -a
Linux x240webshop 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux

**Comment by sokra** [comment]
It looks like this issue is *not directly related* to this project. We try to only keep issues directly related to this project in the issue tracker. Therefore I'm closing this issue.

Please file the issue on **roman01la/webpack-closure-compiler**.

You can easily copy your text if you click on *"edit"* on this issue. Also make sure to follow the issue requirements of the target project when pasting this issue.

**Comment by 5angel** [comment]
@sokra it seems Closure Compiler breaks harmony on ADVANCED settings: it can't optimize an "a" getter correctly. Can you direct to me to the part that is responsible for this? Seems like a quick fix.

**Comment by 5angel** [comment]
Ok, it's this part: https://github.com/webpack/webpack/blob/aecc297c509f08f95148ccb2915a2b9ff3ee5fa3/lib/MainTemplate.js#L148

So there's a getter function named "a" that get's defined on all harmony modules and gets called via dot notation later. Now I only need to find where webpack does this.
