### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#4668]
I use code-splitting with require.ensure
Why I can not set bundle name with string variable?
if I use anything but string literal - I get the error

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by budarin** [comment]
I dont speak about bundle path, which is need to determine entry point for a bundle, but about last parameter - bundle name.
Why it should not be a variable?
