### ISSUE TITLE
Loading chunk 0 failed. at HTMLScriptElement.onScriptComplete

### ISSUE THREAD

**Issue by lovepluskaka** [webpack/webpack#4672]
### My code is:   
     if (configs.renderingConfig && configs.renderingConfig.codeSyntaxHighlighting) {
             require.ensure([], () => {
                    const theme = configs.renderingConfig.highlightingTheme || 'default';
                    window.hljs = require('highlight.js');
                    require(`highlight.js/styles/${theme}.css`);
             }, 'highlight');
      }
There is the same warning in terminal  

> require function is used in a way in which dependencies cannot be statically extracted

And there is also two error in browser  

> Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete 

> vendor.js?v=20170309:92 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by lovepluskaka** [comment]
Sorry,It just a question.I will post it on  Stack Overflow.

**Comment by lovepluskaka** [comment]
@sokra  Sorry,It just a question.I will post it on  Stack Overflow.
