### ISSUE TITLE
I'm getting errors when trying to require x-ray 

### ISSUE THREAD

**Issue by guyiluz** [webpack/webpack#4682]
``I'm using win 10 and this is what I'm getting when i enter "webpack" 
```

```
ERROR in ./~/x-ray/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\guyil\Desktop\webpack test - Copy\node_modules\x-ray'
 @ ./~/x-ray/index.js 17:9-22
 @ ./index.js

ERROR in ./~/destroy/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\guyil\Desktop\webpack test - Copy\node_modules\destroy'
 @ ./~/destroy/index.js 14:17-30
 @ ./~/http-context/lib/response.js
 @ ./~/http-context/lib/context.js
 @ ./~/x-ray-crawler/lib/index.js
 @ ./~/x-ray/index.js
 @ ./index.js

ERROR in ./~/http-outgoing/index.js
Module not found: Error: Can't resolve '_http_common' in 'C:\Users\guyil\Desktop\webpack test - Copy\node_modules\http-outgoing'
 @ ./~/http-outgoing/index.js 27:13-36
 @ ./~/http-context/lib/response.js
 @ ./~/http-context/lib/context.js
 @ ./~/x-ray-crawler/lib/index.js
 @ ./~/x-ray/index.js
 @ ./index.js
```
```

```
# any idea how to fix it?

```
this is my webpack.config.js:
```
module.exports = {
    entry: "./index.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style-loader!css-loader"},
              {test: /\.json$/, loader: 'json-loader'}
        ]
    }

};
```
Thanks!
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
