### ISSUE TITLE
Why externals for `ui-router` and `chart.js` doesn't work?

### ISSUE THREAD

**Issue by saeidalidadi** [webpack/webpack#4684]
I have an error when using `externals` as bellow:

`webpack.prod.config.js`:

```javascript

exports.config = () => {
  entry: {
     app: '/app.js'
  },
  externals: {
    angular: 'angular',
    uiRouter: 'angular-ui-router',
   ...
  },
  ...
}
```
and I have imported all externals inside `head` of my template file.

So after that all externals have been loaded this error fired in my web console.

```log
admin.bundle.js:1738Uncaught ReferenceError: ui is not defined

```

the line of error in my bundle file:

```javascript

/* 63 */
/***/ (function(module, exports) {

module.exports = angular-ui-router;

/***/ }),
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by maniksingh92** [comment]
Sorry for bumping a closed issue, but @saeidalidadi you should try quoting `'angular-ui-router'` as `' "angular-ui-router" '` . Note the additional double quotes enclosing the module name.
