### ISSUE TITLE
Module '" + loader.path + "' is not a loader (must have normal or pitch function)

### ISSUE THREAD

**Issue by jackharter** [webpack/webpack#4687]
Module '" + loader.path + "' is not a loader (must have normal or pitch function) is the error thrown by webpack after adding "-loader" to !Style!CSS! as suggested in the tutorial at https://webpack.github.io/docs/tutorials/getting-started/. I don't understand this error? Thanks for helping me. - jack

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by jackharter** [comment]
Yes close the issue. I wanted some support on a product that seems to be suffering some tutorial and documentation issues. So, here's a development suggestion. Make sure your tutorials work and that your documentation is complete and accurate.
