### ISSUE TITLE
ExternalsPlugin with ProvidePlugin to provide require

### ISSUE THREAD

**Issue by ccorcos** [webpack/webpack#4740]
**Do you want to request a *feature* or report a *bug*?**

Both? depends on the intention.

**What is the current behavior?**

If I use the ProvidePlugin to provide a `require` function, then the require statements created by the Externals function are not patched.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/ccorcos/webpack-externalsplugin-provideplugin

**What is the expected behavior?**

I would expect the ProvidePlugin to be able to patch the require statements output by the ExternalsPlugin

**If this is a feature request, what is motivation or use case for changing the behavior?**

I explained in the README of the repo, but basically, I want to be able to compile a website that works in the browser **and** inside of an electron app.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
/p/t/webpack-externals-provide ❯❯❯ node -v
v7.8.0
/p/t/webpack-externals-provide ❯❯❯ m info
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
/p/t/webpack-externals-provide ❯❯❯ ./node_modules/.bin/webpack -v
2.4.1
```

**Comment by sokra** [comment]
yeah, this doesn't work. As workaround create a file with the content you like `require("require.js")("something")` and use `resolve.alias` to point `something` to this file.

But anyway require.js will not load your module. You need to use the `libraryTarget: "amd"` or `"umd"` to be able to load modules via require.js. Why? because loading modules via require.js is async.
