### ISSUE TITLE
Externals modules included in bundle

### ISSUE THREAD

**Issue by khankuan** [webpack/webpack#4754]
Hi, I have the following config to exclude libraries from the bundle. However, it seems like they are still included as the bundle is large and stats.json shows them as well (although the external modules are listed as well).
```
config.output = {
    path: outputDistDir,
    filename: '[name].js',
    library: 'lib',
    libraryTarget: 'umd'
};
config.externals = {
    react: {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react'
    },
    'react-dom': {
      root: 'ReactDOM',
      commonjs2: 'react-dom',
      commonjs: 'react-dom',
      amd: 'react-dom'
    }
}
``` 
Are there other factors like common chunks or extract text plugin that would affect externals? Cheers!

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
