### ISSUE TITLE
When use require.ensure ,   Webpack  can't packed inside the css file , why?

### ISSUE THREAD

**Issue by a526672351** [webpack/webpack#4781]
# On the entry page JS, I asynchronous require to my component JS 
- Page JS like this：

require.ensure([], function() {
                    require('../common/box/box-shop-nav/box-shop-nav.js');
                });

- Component JS like this : 

require('../box-shop-nav/css/box-shop-nav.scss');

Why webpack can't packed inside the css file ?
-----------------------------------------------------------------------------
# When my page JS,edit like this, it can working .
- Page JS like this：

 require('../common/box/box-shop-nav/box-shop-nav.js');

The webpack can packed it .

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
