### ISSUE TITLE
webpack not creating a folder/directory

### ISSUE THREAD

**Issue by ramojej** [webpack/webpack#4793]
I'm using Windows 8 and my current webpack version is 2.4.1.

Here's webpack.config.js
```
module.exports = {
	entry: "./app/assets/scripts/App.js",
	output: {
		path: __dirname +  "./app/temp/scripts",
		filename: "App.js"
	}
}
```
and here's the output, problem is it's not creating the scripts folder and App.js file under temp directory
![webpack](https://cloud.githubusercontent.com/assets/12524474/25519992/c0353fd4-2c2c-11e7-906a-0d9f5579ec20.PNG)

**Comment by Axnyff** [comment]
I'm using Windows 10 so it might vary but I think what's causing you troubles is the "." in your output.path property. 

It's probably creating a directory very similar to your working directory but with an extra dot:

I'm working in a "test" directory and it creates next to it a "test." directory

**Comment by ramojej** [comment]
@Axnyff Thank you! I removed the "." in my output.path and it worked like a charm. However, my travel-site folder doubled. The one have a "." at the end of the name. Whenever I delete the one with the ".", the one without "." is having "." at the end. What cause this?
![wew](https://cloud.githubusercontent.com/assets/12524474/25555105/9ad2b174-2d10-11e7-8c4e-d0a233dc21ac.PNG)

Here's the code you suggested

```
module.exports = {
	entry: "./app/assets/scripts/App.js",
	output: {
		path: __dirname +  "/app/temp/scripts",
		filename: "App.js"
	}
}
```

**Comment by Axnyff** [comment]
That's a Windows bug i think, windows is deleting the wrong folder.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
