### ISSUE TITLE
issue with webpack?

### ISSUE THREAD

**Issue by sangramkb** [webpack/webpack#4799]
![image](https://cloud.githubusercontent.com/assets/28225588/25565763/3687bff8-2deb-11e7-8f1c-5d81376f1af4.png)

I am new to react and webpack.
can someone please help me out in resolving above issue?

**Comment by naknode** [comment]
Hey @sangramkb, this type of "issue" is more of a question which would be better suited over at [StackOverflow](http://stackoverflow.com/tags/webpack) tagged with `javascript` and `webpack`. (Not sure if allowed here.) There, you'll be able to show more code to process what went wrong instead of a single image. 

From what I can see, the syntax of your command `webpack -d && copy src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot` is wrong, as the terminal tells us. 

I would not recommend using manipulation commands such as `copy` as that kind of logic should be handled by webpack.

I also highly recommend looking into a tool called [create-react-app](https://github.com/facebookincubator/create-react-app) which uses webpack to bundle your resources.

**Comment by TheLarkInn** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
