### ISSUE TITLE
how to create dynamic context for import()

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#4805]
I see how to create static context:
`require.context("./test", false, /\.test\.js$/);`

Here we get context module which has some properties like resolve, keys, id.

But I can't find how to create context module for dynamic import(). Could you please tell me how I can do this?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
