### ISSUE TITLE
Doubt not issue ( can't resolve module woff within css file )

### ISSUE THREAD

**Issue by devarashetty** [webpack/webpack#4806]
I tried to use `@font-face` and the loader style-loader along with url loader and file loader for fonts but it still shows some weird error 

**Code**

CSS File

```
@font-face {
  font-family: 'fontello';
  src: url('../../sass/fonts/fontello/fontello-webfont.woff2') format('woff2'),
       url('../../sass/fonts/fontello/fontello-webfont.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}
```

Webpack.Cient.js

```{ 
     { test: /\.(woff|woff2|ttf|eot|svg|png|jpg|gif)(.*)?$/, 
      loader: 'file?name=asset/[name].[ext]' 
    },
    {
      test: /\.css/,
      loader: 'style-loader!css-loader',
    }```


**ERROR**

Module not found: Error: Can't resolve '../../sass/fonts/fontello/fontello-webfont.woff2' in '/home/sairam/Downloads/goin/goin/src/modules/goin_theme/client/css'

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
