### ISSUE TITLE
require.resolveWeak is not working with dynamic values

### ISSUE THREAD

**Issue by pfrankov** [webpack/webpack#4808]
Unfortunately, `require.resolveWeak` doesn't work properly.
I'm trying to include all `*.spec.js` files but only for already included modules.

```js
const context = require.context("./src/", true, /\.spec\.js$/);

context.keys().forEach(function(key) {
	if (require.resolveWeak(key.replace(".spec.", "."))) {
		context(key);
	}
});
```
And suddenly I'm getting an error: `Cannot find module "."`

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
