### ISSUE TITLE
module

### ISSUE THREAD

**Issue by Awadhesh31** [webpack/webpack#4810]
ERROR in /home/awadhesh/angular/project/src/app/app.component.ts (2,31): Cannot find module './home'.

ERROR in /home/awadhesh/angular/project/src/app/app.component.ts (8,3): Argument of type '{ selector: string; templateUrl: string; styleUrls: string[]; directives: any[]; }' is not assignable to parameter of
type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './home' in '/home/awadhesh/angular/project/src/app'
 @ ./src/app/app.component.ts 11:0-39
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

**Comment by Awadhesh31** [comment]
module not found

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
