### ISSUE TITLE
React + Webpack + Socket.io + SSR

### ISSUE THREAD

**Issue by soutomario** [webpack/webpack#4827]
Hi, i'm working in a personal project, and I want to use webpack-dev-server with hot loader for dev and SSR for production with react-router, and I'm not finding a way of make these things work together.

Does anyone already had this problem or try to build something like this?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
