### ISSUE TITLE
How to use postcss-loader in webpack2?

### ISSUE THREAD

**Issue by SendLessLove** [webpack/webpack#4847]
How to use postcss-loader in webpack2?
there was a problem with the postcss-loader,here's my code.

`{
        test: /\.less$/,
        include: [
          path.resolve(__dirname, "src/css")
        ],
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'postcss-loader', 'less-loader']
        })
},`
Please tell me what to do!

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by SendLessLove** [comment]
thank you for reminding me,i made a mistake,sorry
