### ISSUE TITLE
HMR is not working when html file change

### ISSUE THREAD

**Issue by joenil** [webpack/webpack#4855]
I got this in console but the page dosen't reload:
![image](https://cloud.githubusercontent.com/assets/11400674/25922809/244a21b2-360d-11e7-8ca1-5d6b55845490.png)
it's only get full reload for js and hot reload for css files change, my config like this:
``` javascript
const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const InlineManifestWebpackPlugin = require('inline-manifest-webpack-plugin')

const production = process.env.NODE_ENV === 'production';

module.exports = {
    entry: {
        main: './src/script/app.es',
        libs: ['Lufylegend', 'pako']
    },

    output: {
        filename: 'js/[name]_[hash]_[id].js',
        path: path.resolve(__dirname, 'release')
    },

    module: {
        rules: [
            // export lufy methods
            {
                test: /lufylegend/,
                use: 'exports-loader?LInit,LSprite'
            },
            {
                test: /\.styl$/,
                use: production ? ExtractTextPlugin.extract({
                    use: ['css-loader', 'stylus-loader']
                }) : ['style-loader', 'css-loader', 'stylus-loader']
            }
        ]
    },

    plugins: [
        new webpack.HotModuleReplacementPlugin(),

        new webpack.optimize.CommonsChunkPlugin({
            names: ['libs'],
            minChunks: function (module) {
                return module.context && module.context.indexOf('node_modules') !== -1;
            }
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'manifest'
        }),

        // dist html file
        new HtmlWebpackPlugin({
            filename: 'app.html',
            template: './src/app.html'
        }),

        new InlineManifestWebpackPlugin({
            name: 'webpackManifest'
        }),
        
        new ExtractTextPlugin('css/[name]_[contenthash].css')
    ],

    resolve: {
        extensions: ['.js', '.es'],
        alias: {
            Lufylegend: path.resolve(__dirname, 'libs/lufylegend-1.10.1/lufylegend-1.10.1.min.js'),
        }
    },

    devServer: {
        port: 8080,
        compress: true,
        inline: true,
        hot: true,
        historyApiFallback: {
            index: '/app.html'
        }
    }
}
```

**Comment by mm-x** [comment]
Hi, I am having same issue. Did you manage to fix?

**Comment by evilebottnawi** [comment]
@joenil @mm-x for static assets please use `contentBase` option for `webpack-dev-server` (see https://webpack.js.org/configuration/dev-server/#devserver-contentbase). If this don't help you please create issue in `webpack-dev-server` repo, thank for issue!

**Comment by andreyvolokitin** [comment]
@evilebottnawi, I have the similar issue. My HTML is built using PostHTML and webpack, so it is not static I guess. I looked into ```webpack-dev-server``` source and as far as I understood, in case of ```hot: true``` [client just emits](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L215) ``` webpackHotUpdate``` when ```webpack-dev-server``` detects that some update is needed, and then ```webpack/hot/dev-server.js``` [listens to it](https://github.com/webpack/webpack/blob/0e5405a3eabc3536340654f50100f7ab93c78504/hot/dev-server.js#L43) and checks what changed. Does this mean that ```webpack-dev-server``` can't see what changed and needs to make a request to webpack in order to detect this? Can ```webpack-dev-server``` potentially see that the changed file was HTML file and reload the page right away without making a request to webpack? And if not, does this mean that webpack source also needs to be changed to fix this?

**Comment by andreyvolokitin** [comment]
When webpack done compiling, ```webpack-dev-server``` [sends message with compile stats to the socket](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L71), which in turn sends message to the client (https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L671 , https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L133), which in turn [emits](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L215) ```webpackHotUpdate``` on ```webpack/hot/emitter```. At the same time ```webpack/hot/dev-server.js``` [listens](https://github.com/webpack/webpack/blob/0e5405a3eabc3536340654f50100f7ab93c78504/hot/dev-server.js#L43) to ```webpackHotUpdate``` and decides if all modules are up to date or not. 

Seems like webpack HMR feature (which is used by ```webpack-dev-server``` if I am correct) is not considering a use case of HTML/template page being changed. It listens to  ```webpackHotUpdate``` and checks if some *modules* were changed, but HTML does not fall into that category because in discussed use case it is not a module (and it can't be a "hot module" anyway). So either should ```webpack-dev-server``` detect if HTML was changed after webpack compiling (I am not sure if this possible) and then do a full page reload without invoking "hot update" logic. Or webpack itself should handle this use case if ```webpack-dev-server``` has no means to do it

**Comment by jrichardsz** [comment]
Maybe this could help you:
https://github.com/webpack-contrib/transform-loader/issues/24#issuecomment-392617648
