### ISSUE TITLE
General failure to parse 'spec.ts' modules for Karma/Jasmine unit testing

### ISSUE THREAD

**Issue by Exertive** [webpack/webpack#4874]
I suspect that a bug is preventing compilation of specification files in Karma unit testing. The 'spec' files are part of an application which builds and runs fine in both development and production.

All attempts at building the application using 'npm test' fail. The error message is as below:

ERROR in ./src/app/app.component.scss
Module parse failed: C:\...\trunk\src\app\app.component.scss Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
|
| @import '~@angular/material/core/theming/all-theme';
|
| @include mat-core();

The configuration files used are exactly those in the AngularClass starter application but with additional libraries including Material loaded into the application. Loaders for both TypeScript and SASS are included in webpack.test.js but are not invoked for compilation of unit test files. The same error occurs for both TypeScript and SCSS files with '@' not recognized as part of an initial import statement.

The expectation is that the test modules (.spec.ts) will compile and run. The error is not version-specific. It occurs with both Angular 2.4.X and Angular 4.X.Y. It is not test specific. i.e. any test fails. However, it does appear to be application/dependency specific.

I suspect that correct module resolution/compiler loading is being thrown by the nature/size of the application bult by Webpack prior to compilation of the unit tests.

David

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
