### ISSUE TITLE
adding target results in error "require not defined"

### ISSUE THREAD

**Issue by wende60** [webpack/webpack#4888]
hi there,

i am using webpack 2, react and electron. Adding a target like "target: 'electron' to my webpack.config.js always results in an error:
Uncaught ReferenceError: require is not defined.

My setup can be found here:
https://github.com/wende60/timeTracker

The expected behaviour is to set the target 'electron' and then to be able to import ipcRenderer from electron...

Is this a bug or missconfiguration?

cheers, jo

**Comment by sokra** [comment]
maybe `electron-renderer`

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by wende60** [comment]
sorry for that, moved to https://github.com/webpack/webpack/issues/4891
