### ISSUE TITLE
how to polyfill require ? it's a big problem

### ISSUE THREAD

**Issue by anlexN** [webpack/webpack#4901]
because i couldn't use it in node. as i know , i set webpack target: 'node', i see node-libs-browser built in webpack . 
But i still get this error: "require is not defined" !!!!!!!!!!!!
And i can't use import es6 syntax!!!!!!!!!!
![require](https://cloud.githubusercontent.com/assets/8686739/26248863/89bd4f4a-3cd6-11e7-80e0-0bbf3bec1d48.PNG)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
