### ISSUE TITLE
feature request: webpackChunkName for a whole file's imports

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack#4928]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
each `import()` statement needs to be individually marked with the `webpackChunkName` comment

**If the current behavior is a bug, please provide the steps to reproduce.**
e.g.

```js
import(/* webpackChunkName: "foo" */ './foo');
```

**What is the expected behavior?**
It would be great to define this at the module root and have all children in the dependency graph inherit the chunk name.

**If this is a feature request, what is motivation or use case for changing the behavior?**
If you dynamically import many modules, it can be tedious to add the comment to each one. e.g.

```js
Promise.all([
    import(/* webpackChunkName: "fizz" */ './foo'),
    import(/* webpackChunkName: "fizz" */ './bar'),
    import(/* webpackChunkName: "fizz" */ './baz'),
])
```

It would be cool to be able to do this:

```js
/* webpackChunkName: "fizz" */

Promise.all([
    import( './foo'),
    import( './bar'),
    import('./baz'),
])
```

And have all the following import statements in the current scope be marked for inclusion in that chunk name.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 7.x
Latest Webpack
OS X

**Comment by sokra** [comment]
This is a very specific use case. In general it won't make sense to set the chunk names on all imports.

won't fix, just write it multiple times

**Comment by probablyup** [comment]
How do you figure? require.ensure allows you to do this today. There's no
equivalent for dynamic import.

**Comment by zioth** [comment]
I agree that this is a valuable use-case. In our product, each chunk includes several components, because they aren't big enough individually to justify a whole chunk to themselves. Each chunk is defined in its own index file. Currently, we have to put `webpackChunkName` on every `import()`, resulting in less readable code. If it could appear just once in the file, not only would the code would be more readable, but developers would be less likely to accidentally give a component the wrong chunk name.
