### ISSUE TITLE
Module not found: Error: Can't resolve 'kendo.core.min' in 'c:...

### ISSUE THREAD

**Issue by liadoster** [webpack/webpack#4930]
0
down vote
favorite
I'm try to use webpack in my project.

I created some JS files responsible to load all my js files, by use "require" (for example require('./app/Scripts/angular.js');). Some of my JS files that I loaded used ADM definition: "define.amd?define(["kendo.core.min"],y)".

When I run webpack I got the follow error:

"ERROR in ../app/Scripts/kendoui/cultures/kendo.culture.he-IL.min.js Module not found: Error: Can't resolve 'kendo.core.min' in '....'"
I tried to define alias for 'kendo.core.min' and it still happening:

resolve: { alias: {'kendo.core.min': './app/Scripts/kendoui'} },
I also tried this: modules:

[ path.join(__dirname, "./app/Scripts/kendoui"), "node_modules" ] 
What should I do?

**Comment by bebraw** [comment]
Can you please fill the issue template? There's not enough information.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
