### ISSUE TITLE
[WASM] - Handle shared memory across any/all WASMModules

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4957]
We need to be able to create a reusable memory module so that memory can be shared across all `WASMModule`.

An example code that would be valid for this use case may look like: 

**entry.js**
```javascript
import(“./abc.js”).then(abc => abc.doIt());
```
**abc.js**
```javascript
import { duplicateText } from “./string.cpp”;
 
export function doIt() {
  console.log(duplicateText(“Hello World”));
}
```
 
*string.cpp*
```cpp
extern “C” const char* duplicateText(const char* text) {
  int len = strlen(text);
  char* newstr = new char[len*2 + 1];
  strcpy(newstr, text);
  strcat(newstr, text);
  return newstr;
}
```

**Comment by imvetri** [comment]
I can join hands with someone else interested in this.

**Comment by TheLarkInn** [comment]
@imvetri That would be awesome. Since we do not have the implementation of WASM started yet, we should create a few examples including the one above and use it as the basis for development. 

Also if you would like to generate some more sample modules, there is a great [LLVM online IDE](https://mbebenita.github.io/WasmExplorer/?state=%7B%22options%22%3A%7B%22showGutter%22%3Atrue%2C%22showConsole%22%3Atrue%2C%22showOptions%22%3Atrue%2C%22autoCompile%22%3Atrue%2C%22showLLVM%22%3Afalse%2C%22darkMode%22%3Atrue%2C%22fastMath%22%3Afalse%2C%22noInline%22%3Afalse%2C%22noRTTI%22%3Afalse%2C%22noExceptions%22%3Afalse%2C%22cleanWast%22%3Afalse%2C%22wasmBaseline%22%3Afalse%2C%22dialect%22%3A%22C%2B%2B11%22%2C%22optimizationLevel%22%3A%22s%22%7D%2C%22source%22%3A%22int%20two()%20%7B%5Cn%20%20return%202%3B%5Cn%7D%22%7D.) that you can leverage.

Why don't we start drafting out together each of the features we would like to see from this and what it would entail.

**Comment by imvetri** [comment]
@TheLarkInn  Any scenarios you have in mind for sample modules, if so could you list them for me. I will start with POCs for them.

**Comment by TheLarkInn** [comment]
Of course and absolutely. I'll share this issue with the community and see if anyone else would like to be involved!!

**Comment by TheLarkInn** [comment]
It appears there is already a great discussion happening here also: https://github.com/systemjs/systemjs/issues/1671 should try to work as closely as possible on a single module that both projects can use (if possible)

**Comment by jayphelps** [comment]
Did you all have thoughts on whether or not _shared_ memory is truly a priority at this point? It's important to make some distinctions to clarify what I mean and my current expectations: _compiling_ source like rust/c files using a loader would presumably create a single wasm module aka binary as a combination of all the files. These wouldn't need shared memory because there is only wasm binary.

If instead you're linking already compiled wasm binaries, that's a different story because they need ABI compatibility as a prerequisite which isn't doable right now reliably. There's also the argument that it's not a good **default** because unrelated modules could cause memory corruption to the others, e.g. imagine one brings in a GC the others don't use/know about. In systemjs/systemjs#1671 the recommendation was that separate modules each get their own memory (at least by default).

I'm on the fence about it, probably because I haven't thought enough about the practical implications. I feel separate by default is nice (and doable now) however seemingly can introduce hard to understand issues where one module calls the other (directly or indirectly) passing along a pointer that the receiver cannot deference because it's not in their own memory. I feel (without proof) that will be critical to understand for webpack users which is pretty unfortunate.

All that said, I'm an armchair compiler dude so certainly my understanding has gaps. We'll really need to lean heavily on the wasm team on this one for direction, with clarification IMO.

***

Although I'm hesitant to duplicate discussions, certainly webpack has different requirements/usecases as systemjs so IMO it's worth discussing partially independently and then we can collect our thoughts and collab.

**Comment by justinmchase** [comment]
@jayphelps I'm just learning about this but I needed it (shared memory across modules) already for a scenario I'm working on.

I would like to make a language but I don't want to use C or any traditional languages as the base. One of the interesting features about wasm is that you can dynamically compile to wasm and either run it or save it to disk and load it again later.

So I grabbed a compile of stdlib as a module so I can at least get malloc/free but since it's its own module I need to share memory across the two. Its not that hard to do but if you malloc in one module and need to get the memory at that location in another then you need to share it.

I'm not sure how common what I'm doing will be but it seems pretty critical for any scenario where you have more than 1 module.

**Comment by xtuc** [comment]
We actually close this now. wasm modules are able to import the memory of other wasm modules.

**Comment by sokra** [comment]
I guess we can close this, as memory sharing is possible
