### ISSUE TITLE
Angular js build failed

### ISSUE THREAD

**Issue by Shamoncushbu** [webpack/webpack#4996]
I've two angular js files

**1.route.js**

    var route =angular.module("main",['ngRoute']);

**2.development.js**

    route.config(['$routeProvider', function($routeProvider) {
        $routeProvider.
        when('/test', {
            templateUrl:'app/test.html',
            activetab:'emp',
            controller:'WelcomeController'
        })
    }]);
    
    route.controller('WelcomeController',function ($scope) {
        alert('ok');
    })
    

Here i am using webpack to build the above two files

module.exports = {

   

     entry:{
             source:[__dirname+'/resources/assets/js/components/route.js',__dirname+'/resources/assets/js/components/development.js']
        },
        output: {
            path: __dirname+'/public/prod',
            filename: '[name].js'
        },
    
    
    };
          

i got the final file in `source.js` but i got the following error 

> source.js:73 Uncaught ReferenceError: route is not defined

It happens only when i build the files if i separably include it in html page it works fine

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
