### ISSUE TITLE
Not reload page on edit object value

### ISSUE THREAD

**Issue by ali-master** [webpack/webpack#5023]
Hi,

When i edit an object value, the page is not **reloaded automatically**...But if **I refresh the page** that fixes the problem!!!

webpack: 2.6.1
webpack-dev-server: 2.4.5

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
