### ISSUE TITLE
error Found incompatible module when upgrading to webpack 2

### ISSUE THREAD

**Issue by php-cpm** [webpack/webpack#5036]
I'm upgrading from webpack 1 and meet this problem 

https://github.com/webpack/webpack/commit/6a18da107006a68dc805919c951184bf491afd71#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I'm using nodejs 5.5.0,and can't install webpack 2.6.0  caused by error Found incompatible module

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
