### ISSUE TITLE
web pack module build error

### ISSUE THREAD

**Issue by IvanPodgur** [webpack/webpack#5062]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Getting the following error output, is there a way to get a more info out of web pack on this issue.

```
62% 478/543 build modulesError
at NormalModule.<anonymous> (...../node_modules/webpack/lib/NormalModule.js:113:20)
at NormalModule.onModuleBuild (..../node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
at nextLoader (..../node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
at ...node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
at Storage.finished (....node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
at .../node_modules/graceful-fs/graceful-fs.js:78:16
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:438:3)
69% 1917/1919 build modules
```

**Comment by IvanPodgur** [comment]
running: `webpack --display-error-details --display-reasons --progress -p --config  webpack.config.prod.js`

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

Please also update to latest webpack version!
