### ISSUE TITLE
Module parse faild with requirejs

### ISSUE THREAD

**Issue by chenp1204** [webpack/webpack#5065]
The following is error message:

ERROR in ./~/_requirejs@2.3.3@requirejs/bin/r.js
Module parse failed: E:\iview-project-2.0\node_modules\_requirejs@2.3.3@requirejs\bin\r.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| /**
|  * @license r.js 2.3.3 Copyright jQuery Foundation and other contributors.
 @ ./~/_cesium@1.34.0@cesium/index.js 5:16-36
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.4.5@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
