### ISSUE TITLE
import ... as webpackChunkName

### ISSUE THREAD

**Issue by bradennapier** [webpack/webpack#5093]
Is there a way that we can use the magic parameters or similar to allow us to specify a group of modules which should be apart of a given chunk?

For example, say I am importing 5 modules which really will always be imported together.  Doing all the separate import statements will chunk each one separately -- and as discussed since bytes cost less than packets it would prob be best if I could group them?

Does importing modules and defining their chunkName as the same as another chunk merge them into a single chunk?  If not is there any way to manage this properly?

**Comment by bradennapier** [comment]
Ok upon a bit of extra testing it does appear to merge them into chunks.  Then my question is how will this really effect the bundle?  I think some more information about this could be very beneficial.  For example, say I import the same module 20 times from different places and with different chunknames - i would imagine that means that it would be included 20 times in each of those chunks ( I don't do that anywhere ).

In this manner, I can imagine people could get themselves into big trouble if things aren't handled properly.  

Does importing a module 20 times without a chunkname provided only create a single chunk?  All this information as-to how it will really handle things I think are pretty important to have if at all possible.

Thanks for all of your hard work!  Loving WP2

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
