### ISSUE TITLE
npm install -g webpack fails on docker container

### ISSUE THREAD

**Issue by thesellsword** [webpack/webpack#5117]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
Command `npm install -g webpack` fails in a fresh ubuntu docker container. Please note `npm install -g webpack@2.6.1` worked

Error log:
```
root@1ee245bf5bd9:# npm install -g webpack
/root/.nvm/versions/node/v7.4.0/bin/webpack -> /root/.nvm/versions/node/v7.4.0/lib/node_modules/webpack/bin/webpack.js

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/.nvm/versions/node/v7.4.0/lib/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

sh: 1: node: Permission denied
/root/.nvm/versions/node/v7.4.0/lib
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.4-moby
npm ERR! argv "/root/.nvm/versions/node/v7.4.0/bin/node" "/root/.nvm/versions/node/v7.4.0/bin/npm" "install" "-g" "webpack"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/trimtool/ui/static/app/npm-debug.log
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Do `npm install -g webpack` in a ubuntu docker container.

**What is the expected behavior?**
The webpack module should be installed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

*System Information* :
*Ubuntu*
```
root@1ee245bf5bd9:# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```
*NPM*
```
root@1ee245bf5bd9:# npm --version
4.0.5
```
*Node*
```
root@1ee245bf5bd9:# node --version
v7.4.0
```

**Comment by codeocelot** [comment]
I feel like you're quiet a few feet deep in tech, and peeling off a bunch of those layers will help debug your particular situation.  The following info is probably really helpful: 

- Can you provide the exact container you're trying to run this in?  Is this one of the official docker images anyone can get from [Docker Hub](https://hub.docker.com/explore/)? 
- Could you also detail how you're running the docker container, including a dockerfile if you're using one, or the command line you're using? 
- I surmise you've installed `nvm` on your container, and are using that to install your node version.  From my own experience, using nvm isn't always straightforward, since there's a number of security considerations.  To eliminate `nvm`, are you able to run webpack using the [official Docker node image](https://hub.docker.com/_/node/)?

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
