### ISSUE TITLE
naming chunk names in webpack configuration.

### ISSUE THREAD

**Issue by AbinayaSubbiah** [webpack/webpack#5124]
I implemented lazy loading module in angular 4. it work well. and when I navigate to the new page, it will load extra js file like: 0.chunk.js, 1.chunk.js.

my question is: how to change that chunk name? ex: 1.chunk.js => about.js 0.chunk.js => user.js

Anyone please post code for the configuration.

**Comment by 0nse** [comment]
Given your Webpack configuration, you can set the `output.chunkFilename` to `'[name].js'`. It will then use the `webpackChunkName`s you have defined using Webpack's [magic comments](https://medium.com/webpack/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a).

Find more information about this in [the code splitting documentation](https://webpack.js.org/guides/code-splitting-async/#chunk-names). Be aware that this is for dynamic imports and only supported since Webpack 2.4.0.

**Comment by whitecolor** [comment]
Buf if you import the same files/modules in different places you have to provide a comment in all places?

While "magic comment" working solution, it is still seem kind of hacky way and not very reliable. It would be good if one could configure this in configuration something like:

```js
dynamicImportChinkNames: {
   './MyComponent': 'my-component'
}
```

Or more sophisticated configuration.

```js
dynamicImportChinkNames: [{
   testImportName: /MyComponent.*/
   chunkName:: 'my-component'
}]
```

**Comment by gkatsanos** [comment]
Same question. Does one need to explicitly specify each dynamic import chunk name separately, or is there a default config that takes the filename as [name] ?  @0nse
