### ISSUE TITLE
Can't launch web-server. DeprecationWarning: Chunk.modules is deprecated

### ISSUE THREAD

**Issue by omak-oorzhak** [webpack/webpack#5142]
How to fix this:
```
webpack: wait until bundle finished: /undefined
(node:11328) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

```
I didn't have this problem with webpack v.2.6.1.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
