### ISSUE TITLE
HMR Not Working With Typescript Commonjs Modules

### ISSUE THREAD

**Issue by pixelshaded** [webpack/webpack#5189]
Typescript: 2.3.4
Webpack: 2.6.1
React: 15.6.1
React-hot-loader: 3.0.0-beta.6

Compiler Options:
```
"target": "es5",
"module": "commonjs",
"moduleResolution": "node",
"rootDir": "src",
"outDir": "dist",
"sourceMap": true,
"lib": ["es2015", "dom"],
"jsx": "react",
"noImplicitAny": true,
"noImplicitReturns": true,
"noImplicitThis": true,
"noUnusedLocals": true,
"suppressImplicitAnyIndexErrors": true,
```

We were using babel with flow and recently converted over to Typescript. The ts config uses module commonjs even though we are running the js in the browser (we were doing this because a few libs exported non-module objects). We noticed that HMR wasn't working. The browser is getting HMR data like the updated file etc, but nothing actually changes on the page. As soon as we use es2015 instead (along with allowSyntheticDefaultImports because of the non-modules), HMR works again. Is this to be expected? Does HMR not work with commonjs modules?

**Comment by Kovensky** [comment]
HMR works with commonjs _iff_ you use commonjs directly.

You need to write accept callbacks that call `require` in them to be able to receive the newly evaluated code, and you have to update the variables where you saved the result of the first require so you can't use `const` requires. Only ES2015 modules have live bindings that are updated just by accepting the module.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
