### ISSUE TITLE
No scope hoisting after migration to webpack 3 ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by kof** [webpack/webpack#5199]
I have migrated a project from webpack 2 to webpack 3 and added ModuleConcatenationPlugin. Yet I see absolutely no change in the dist.

You can compare 2 versions by checking out master https://github.com/cssinjs/jss and https://github.com/cssinjs/jss/tree/webpack3 branches and then running `npm run build` in each, which will produce `dist/jss.js` file.

**Comment by probablyup** [comment]
@kof try using the new optimization bailout flag (`--display-optimization-bailout)` when compiling - might give you a hint.

**Comment by kof** [comment]
nope, nothing

**Comment by sokra** [comment]
You didn't allow webpack to handle ESM because you use the `es2015` babel preset without `modules: false` flag.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by kof** [comment]
ok, sorry, thanks

**Comment by jrencz** [comment]
> You didn't allow webpack to handle ESM because you use the es2015 babel preset without `modules: false` flag.

@sokra I think it should be mentioned in plugin documentation on https://webpack.js.org/plugins/module-concatenation-plugin/

**Comment by sokra** [comment]
Yep. Send a PR.
