### ISSUE TITLE
webpack-source error

### ISSUE THREAD

**Issue by zhangking** [webpack/webpack#5203]
webpack 3

the error log
```
/node_modules/.1.0.1@webpack-sources/lib/ConcatSource.js:48
				map.add(item.listMap(options));
				             ^

TypeError: item.listMap is not a function
```
and I print `item`, It's `[Function: source]`
 
I want to know what might be the problem and I can debug

**Comment by bebraw** [comment]
Can you provide a standalone project to run and study? Please simplify as much as possible.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by stepancar** [comment]
@sokra , i have the same issue but with item.source()
Could you please give a look to our project?
This is a build log https://travis-ci.org/alfa-laboratory/arui-feather/jobs/255237762#L718
All sources here https://github.com/alfa-laboratory/arui-feather/tree/feat/add-md-lint
to reproduce:

git clone https://github.com/alfa-laboratory/arui-feather.git
git checkout feat/add-md-lint
npm i
npm run gemini-ci

this branch - migration to webpack 3
Thank you!

**Comment by stepancar** [comment]
@sokra , created issue https://github.com/webpack/webpack/issues/5325
