### ISSUE TITLE
Referencing `require` causes immediate exception

### ISSUE THREAD

**Issue by mattpap** [webpack/webpack#5209]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```
$ echo "console.log(require);" > some.js
$ node_modules/.bin/webpack --entry ./some.js --output-filename=some.webpack.js
```

This results in the following output (reformatted for readability):
```
console.log(!(
  function webpackMissingModule() { 
    var e = new Error("Cannot find module \".\""); 
    e.code = 'MODULE_NOT_FOUND'; 
    throw e; 
  }()
));
```
This run results in immediate exception and doesn't allow me to pass `require` as an argument to a function.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

At minimum, the generated code shouldn't include function call, just function definition. Preferably, webpack should do nothing or rename `require` as it does by default.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node: 6.10.3
webpack: 3.0.0 and beta (3.0.0-rc.2)
OS: ubuntu linux 16.04

**Comment by ooflorent** [comment]
@mattpap What would you expect here? Should `require` be a binding to the native `require` or to webpack's one? I'm asking this because both function differs. `Module#require` accepts a `String` whereas `__webpack_require__` accepts a `Number`, so the following would not work as expect:

```js
var requireDebug = req => p => console.log(p) || req(p)

requireDebug(__non_webpack_require__)("./a") // ok
requireDebug(__webpack_require__)("./a") // fails since `./a` isn't a valid module id
requireDebug(require)("./a") // ???
```

Maybe what you are looking for is [`__non_webpack_require__`](https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific-).
