### ISSUE TITLE
__webpack_require__ is not defined

### ISSUE THREAD

**Issue by qmy777** [webpack/webpack#5212]
I don't know why and how. But my windows browser console shows this error.

![image](https://user-images.githubusercontent.com/9345799/27838544-f5daa978-611d-11e7-9478-04d253d74baa.png)

![image](https://user-images.githubusercontent.com/9345799/27838563-0f636722-611e-11e7-8c88-977c7da61148.png)

I need help~ Thx~

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
