### ISSUE TITLE
DefinePlugin doesn't traverse UMD module definitions (created by webpack) in dependencies

### ISSUE THREAD

**Issue by marcellomontemagno** [webpack/webpack#5216]
Hi, I'm trying to export an UMD named "B" (created by webpack) as a NPM module containing the following code in the dist.js:

```

//....umd module definition....

if (process.env.NODE_ENV !== "production") {
    console.log('+++++dependency running in dev mode++++++');
  } else {
    console.log('+++++dependency running in prod mode++++++');
}

//....umd module definition....

```
then I'd like another project named "A" to import that UMD as a NPM dependency, and through the usage of:

```
new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
})
```

I'd like to skip the execution of the line 

`console.log('+++++dependency running in dev mode++++++');`

I want this to happen at the moment "A" is built.

For some reason DefinePugin doesn't traverse the UMD module definition, is this an intended behaviour?

DefinePugin works as I expect if the check of process.env.NODE_ENV is outside the UMD definition or inside any simple function (both inside the project "A" or the dependency "B").

Unfortunately Skipping the line at the moment "B" is built doesn't fit my use case.

You can find the minimal code and the configuration reproducing the issue here:

[project "A"](https://github.com/marcellomontemagno/define-plugin-test)

and here:

[UMD dependency "B"](https://github.com/marcellomontemagno/define-plugin-dependency-test)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
