### ISSUE TITLE
webpack.DefinePlugin | constant will change only if file changes

### ISSUE THREAD

**Issue by marekkobida** [webpack/webpack#5219]
How can I resolve this issue?

_Steps:_
1. [START AT **12:00**]: webpack --watch
2. webpack will create process.env.DATE = "05.07.2017 **12:00**"
3. [AT **12:01**]: I'm changing random file
4. webpack will change process.env.DATE = "05.07.2017 **12:01**"
5. **5** minutes of silence
6. [AT **12:06**]: I'm changing random file
7. webpack will change process.env.DATE = "05.07.2017 **12:06**"
8. ...loop

_webpack.config.js_
```
...
plugins: [
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('development'),
      'DATE': // new Date()...
    }
  })
]
...
```

_index.js_
```
...
ReactDOM.render(
  <div>Last updated at [{process.env.DATE}]</div>, 
  document.getElementById('root')
)
...
```

**Comment by Kovensky** [comment]
I am more surprised about `process.env.DATE` changing at all.

From what I can tell, it should only change when your `webpack.config.js` is evaluated, and it's only evaluated once, before webpack even starts watching files.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
