### ISSUE TITLE
Web Pack ExtractTextPlugin is caching CSS so no changes are recognized.

### ISSUE THREAD

**Issue by guillaumearchambault** [webpack/webpack#5226]
Feature

Web Pack ExtractTextPlugin is caching CSS so no changes are recognized.

Is it possible to use options in 
module: {
		rules: [
			{
				test: /(\.scss)$/,
				use: ExtractTextPlugin.extract({
					use: [
						{
							loader: 'css-loader'
						},
						{
							loader: 'sass-loader'
						}
					],
					fallback: "style-loader"
				})
			},

so that any changes in css files will be recognized when page refreshes ?

**Comment by shaodahong** [comment]
ExtractTextPlugin provides an option for us to disable it
```
new ExtractTextPlugin({
      disable: true
}),
```
It should be disabled in the dev

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
