### ISSUE TITLE
Webpack 3.1.0 breaks multi compiler with webpack-hot-server-middleware

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#5227]
There seems to be some undocumented change on the way multi compiler setups are made accessible for plugins as https://github.com/60frames/webpack-hot-server-middleware/issues/31 breaks and report that it does not can access the two passed configured compilers.

Has anybody an idea where this is coming from, whether some API was changed, or whether that's a regression in Webpack?

**Comment by swernerx** [comment]
That issue is probably related to this new feature: "Support array of functions as configuration" reported in the changelog.

**Comment by sokra** [comment]
Sounds like a serious bug in the feature @AndersDJohnson. But you didn't follow the issue template, so same right for everyone:

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by swernerx** [comment]
I tried reproducing it. But somehow I can't in a small example.

It seems to be some issue with npm-5.1.0 where there were two different installations at the same moment. This resulted into a check in the hot-server-middleware:

```
if (!(multiCompiler instanceof MultiCompiler)) {
  throw new Error(`Expected webpack compiler to contain both a 'client' and 'server' config`);
}
```

to fail. 

Deleting node_modules and the package-lock.json file and reinstalling everything works.
