### ISSUE TITLE
Error: 'output.filename' is required, either in config file or as --output-filename  webpack 3.0.0

### ISSUE THREAD

**Issue by guguji5** [webpack/webpack#5228]
I want to report a *bug*?

I am new one to webpack,learning html-webpack-plugin comparing to the official website.and config the webpack.config.js as below 

```
var HtmlWebpackPlugin = require('html-webpack-plugin');

var webpackConfig = {
  entry: 'index.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  plugins: [new HtmlWebpackPlugin()]
}
```

run cli `./node_modules/.bin/webpack --config webpack.config.js`
But get an error like that.

`Error: 'output.filename' is required, either in config file or as --output-filename` 

what's wrong and how to solve ？

**node 6.10.2 webpack 3.0.0 and window 10 OS*8

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
