### ISSUE TITLE
ModuleConcatenationPlugin: JavaScript heap out of memory

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#5256]
When using, `new webpack.optimize.ModuleConcatenationPlugin()` I am getting the `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

```
<--- Last few GCs --->
  154254 ms: Mark-sweep 1324.6 (1437.9) -> 1324.6 (1437.9) MB, 1012.4 / 0.0 ms [allocation failure] [GC in old space requested].
  155267 ms: Mark-sweep 1324.6 (1437.9) -> 1324.6 (1437.9) MB, 1012.6 / 0.0 ms [allocation failure] [GC in old space requested].
  156328 ms: Mark-sweep 1324.6 (1437.9) -> 1332.8 (1421.9) MB, 1061.0 / 0.0 ms [last resort gc].
  157361 ms: Mark-sweep 1332.8 (1421.9) -> 1341.1 (1421.9) MB, 1032.7 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================
Security context: 00000266E3BCFB49 <JS Object>
    1: token(aka token) [00000266E3B04381 <undefined>:1729] [pc=0000022506B6474D] (this=00000266E3B04381 <undefined>,type=00000266E3B04FB1 <String[4]: name>,value=00000094B9F86569 <String[4]: this>,is_comment=00000266E3B04381 <undefined>)
    2: arguments adaptor frame: 2->3
    3: read_word(aka read_word) [00000266E3B04381 <undefined>:~1962] [pc=0000022506B8867B] (this=00000266E3B04381 <unde...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**  Webpack 3.1.0, Windows 10

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
