### ISSUE TITLE
<b>Error in ulglifying the scriptfile due to presence of "const" keyword using javascript</b>

### ISSUE THREAD

**Issue by shivangsoni** [webpack/webpack#5258]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by shivangsoni** [comment]
Hey guys getting problem in figuring out how this "const" keyword can stop to conversion of minified js file. One more thing is it possible to dynamically change "const" variable to "var" in javascript.(If not i might have to manually change code).

**Comment by michaelsanford** [comment]
@shivangsoni You should edit the original comment and fill in the template; the questions are there to help make sure contributors provide enough information for the team to understand the issue fully.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
