### ISSUE TITLE
"webpack#ajv" not installed after update to webpack 3.1.0

### ISSUE THREAD

**Issue by ahmehri** [webpack/webpack#5262]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

**What is the current behavior?**
`yarn check` results in the following error:
```
error "ajv" is wrong version: expected "4.11.7", got "5.2.1"
error "webpack#ajv" not installed
error Found 2 errors.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
* Update to webpack 3.1.0.
* Run `yarn check`.

**What is the expected behavior?**
No errors.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js version: 8.1.0
wepack version: 3.1.0

**Comment by sokra** [comment]
How should webpack influence this? Isn't this a yarn bug if it incorrectly install ajv?

**Comment by ahmehri** [comment]
@sokra I wasn't sure if this is related to yarn or not since this error didn't occur with webpack < 3.0.0. I'm not sure but I think this error is caused because yarn didn't install ajv not the opposite.

**Comment by swernerx** [comment]
It's probably related to the package manager. I have seen the same issue... even with `ajv` by using npm@5.2.0.

**Comment by haines** [comment]
The problem here is not really a yarn bug, but rather that webpack's dependency on `ajv@^5.1.5` is incompatible with one of webpack's transitive dependencies which depends on `ajv@^4.9.1`.

The only for webpack to attempt to solve this issue would be to downgrade to `ajv@^4.11.8`, but I don't think that's a very good option (other packages, e.g. `eslint@^4.0.0`, will pull in `ajv@^5.0.0` anyway, so this will crop up elsewhere).

The resolved dependency tree for my package has:
```
webpack@3.2.0
-> watchpack@1.3.1
-> chokidar@1.7.0
-> fsevents@1.1.2
-> node-pre-gyp@0.6.36
-> request@2.81.0
-> har-validator@4.2.1
-> ajv@4.11.8
```

Working backwards,
- `har-validator@5.0.3` bumps to `ajv@^5.1.0`
- `request/request@baf9c1f` bumps to `har-validator@~5.0.2`
- `node-pre-gyp@0.6.36` depends on `request@^2.81.0`

So all that needs to happen is a minor or patch release of request and all will be well again*

\* assuming no other dependencies in your package pull in ajv@^4.0.0, e.g. for me `eslint@3.19.0` is still going to be a problem 😞

**Comment by sokra** [comment]
> The problem here is not really a yarn bug, but rather that webpack's dependency on ajv@^5.1.5 is incompatible with one of webpack's transitive dependencies which depends on ajv@^4.9.1.

The package manager should be able to solve this. I. e. it could create a tree like this:

```
node_modules
  ajv@5
  webpack
  watchpack
  chokidar
  fsevents
  node-pre-gyp
  request
  har-validator
    node_modules
      ajv@4
```

**Comment by haines** [comment]
Ah, yeah, you're quite right, yarn does actually do that, `ajv@4.11.8` gets installed to `node_modules/har-validator/node_modules/ajv`. My bad.

I guess `yarn check` is doing the wrong thing here then?

**Comment by haines** [comment]
I've raised this with yarn, installing webpack on its own does not cause this error, it seems to require another package to have a transitive dependency on ajv@4; weird!

**Comment by sokra** [comment]
Great
