### ISSUE TITLE
[Feature Request] add options to exclude certain files/folders for ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by skynewborn** [webpack/webpack#5266]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
All files will be processed by ModuleConcatenationPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
If some files/folders could be added to the exclude option, any modules from those files/folders would be ignored for the concatenation.

**If this is a feature request, what is motivation or use case for changing the behavior?**
There is a project at work where a React component is implemented using recursive reference (i.e., the component imports itself as a sub-component in certain cases). That causes compile failure when ModuleConcatenationPlugin is applied.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3

**Comment by sokra** [comment]
Instead of allowing to filter the module, I would like to fix the bug. Could you provide a repro repo to demonstrate the failure?

**Comment by doberkofler** [comment]
@sokra I just upgraded to webpack 3.2 and wanted to use the new ModuleConcatenationPlugin plugin but after rebuilding all modules several modules throw JavaScript exception. After just removing ModuleConcatenationPlugin everything works as expected.
Independently from the possibility that i might have hit a bug in this new plugin, I was wondering if in principle the ModuleConcatenationPlugin plugin should be able to work with any code or if there are restrictions by design? If there are any, are they documented somewhere and how would I be able to identify the code that cannot be concatenated?

**Comment by sokra** [comment]
It doesn't work with all code, but it automatically bails out for incompatible modules. `--display-optimization-bailout`.

Could you provide a repro case, the error message and the module code for the bug you hit in a separate issue?

**Comment by doberkofler** [comment]
@sokra Would it still generate code if it bails out? In my case it generated code that no longer worked as expected. I'm trying to create a reasonably sized repro case. Thank you for all the great work!

**Comment by skynewborn** [comment]
@sokra Sorry for not replying earlier. I tried to reproduce the issue with a much more simpler project using the code from the work project, but failed. I'm not sure exactly which part caused the issue I mentioned, and I definitely cannot share the whole work project... Anyway, I will keep trying to pin the code that caused this issue. Thanks for the quick reply!

**Comment by doberkofler** [comment]
@sokra I've created a new issue #5288 that hopefully helps to track down this problem
