### ISSUE TITLE
DllReferencePlugin: manifest object as promise [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#5273]
Can you please allow the `DllReferencePlugin` to accept a promise as `manifest` property?
Because file may not exist until webpack is actually fired!

In fact I'm stuck with this scenario:
- single webpack.config.js
- multiple configs exported: `module.exports = [webpackVendorConfig, webpackConfig];`
- first config is for dll bundles
- second config is for app bundling

The following (in the second config aka app bundling, 2nd in order) is going to fail because `manifest.json` is not generated yet by the first configuration: but that's going to be run first and `manifest.json` will exist!
```
    new webpack.DllReferencePlugin({
        manifest: require(`../build/manifest.json`), //this is going to exist after webpack runs the first config in the pipeline!
        name: `vendor`,
    })
```

**Comment by sokra** [comment]
You can pass a file path.

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by damianobarbati** [comment]
Sorry for being a j**k @sokra, here the complete issue info.
I tried to pass a filepath to `manifest` because I thought webpack was going to require it when needed.
But it looks like it is not, please do not close the issue!

Here the repro: 
https://github.com/damianobarbati/react-app/tree/v1.0.7

To run:
```
yarn install
yarn build:dev
```
Error:
```
Error: ENOENT: no such file or directory, open '../build/visitor/vendor.manifest.json'
```

Relevant line => https://github.com/damianobarbati/react-app/blob/v1.0.7/config/webpack.config.js#L56

Commenting the second config works fine => https://github.com/damianobarbati/react-app/blob/v1.0.7/config/webpack.config.js#L294

**Comment by damianobarbati** [comment]
Opening a dedicated issue as you asked: thanks again and I apologize @sokra  :)
