### ISSUE TITLE
How to force reload page if hmr could not update

### ISSUE THREAD

**Issue by SergeyShablenko** [webpack/webpack#5280]
How to force webpack hmr to reload page in this case
![image](https://user-images.githubusercontent.com/13334277/28176012-926b4a54-67fe-11e7-9973-e91d659ddc9d.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
