### ISSUE TITLE
Pass [hash] to pug files from webpack.config

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [webpack/webpack#5302]
Im using the pug-html-loader to load a large number of pug templates and convert them to html in the build directory. this is working fine, but I want to be able to insert the webpack hash in the pug templates.

I cant work out how to set up my webpack.config to pass this data to the pug-html-loader

This is the loader in my webpack.config
```
{
	loader: "pug-html-loader",
	options: {
		exports: false,
		pretty: PRODUCTION ? false : true,
		data: { hash: WEBPACK HASH HERE  }
	}
}
```
As you can see I want to insert the webpack hash in the data object where I have `WEBPACK HASH HERE` currently, but cant work out how to access/pass that in the webpack.config file

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by matthewjumpsoffbuildings** [comment]
I posted on stack overflow months ago, and ive asked on multiple other places, and nobody has offered any response. I know it doesnt fit the standard issue template, because its not a bug or a feature request, but Im at the end of my rope here... please can you at least let me know if this is even possible?

**Comment by sokra** [comment]
It's not possible. hash is generated after loaders. loader result contribute to hash. This is circular.

**Comment by snoack** [comment]
I have a [similar problem](https://stackoverflow.com/questions/47322288/get-hash-of-different-chunk-into-service-worker-using-webpack). While obviously you cannot get the hash of the file/chunk/compilation the template is part of, how about getting the hash of a different chunk?

**Comment by techsin** [comment]
+1
