### ISSUE TITLE
React Installation issues

### ISSUE THREAD

**Issue by nafisakanwal** [webpack/webpack#5311]
I am configuring Reactjs at my local, but when i am running the command 
npm install webpack webpack-dev-server --save-dev
I am getting Lots of errors see bellow:
E:\xamp\htdocs\Reactjs>npm install webpack webpack-dev-server --save-dev
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "webpack" "webpack-dev-server" "--save-dev"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xamp\htdocs\Reactjs\npm-debug.log

E:\xamp\htdocs\Reactjs>

Can somone have idea about these issues 
Thanks in advance

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
