### ISSUE TITLE
Can I load non-module libraries into webpack module?

### ISSUE THREAD

**Issue by Vasikaran** [webpack/webpack#5318]
I want to load non-module libraries  like google fonts into webpack module. The non-module libraries don't have **module.exports** method. Is there any way to achieve it? 

If  that's possible, Is there any way to add non-module as chunks?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
