### ISSUE TITLE
Importing promises in Angular 4

### ISSUE THREAD

**Issue by yvessabourin** [webpack/webpack#5329]
Bug Report

Output from: ng 4.3.0.node 3.10.9 and npm 6.9.2. macOS (Sierra)

I have developed a service to pick up a list of invoices from RabbitMQ using amqplib and bluebird.

When I use pure Javascript, that part works fine. I then migrated to Typescript with an ES5 target and got the invoice recuperation part to work alright, but the objective is to import the result into a component to display the information (or use dependency injection eventually). The import however is always showing the promise as undefined.

After noticing that bluebird was ignored by the compiler, I decided to remove bluebird in view of some conflicts with zone.js and use native promises instead, but the result was the same.

Using Gulp to target ES5 I have managed to make things work as expected with pure Javascript, but bringing the code back into Angular I always run into the same wall. I suspect a problem with either Angular-CLI (1.0.0-beta-28.3) and/or Webpack configuration.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
