### ISSUE TITLE
Style/CSS is invalid

### ISSUE THREAD

**Issue by tkggusraqk** [webpack/webpack#5335]
Webpack3 build, rewrite the third-party style is invalid, webpack2 no problem, but dev when the webpack3 performance is right
`<style>
[v-cloak] {
  visibility: visible
}
html,
body {
  height: 100%;
  width: 100%;
  margin: 0px;
  padding: 0px;
}
/* overwrite iview */
.ivu-poptip-arrow {
  display: none
}
</style>
`

[pro](http://chuantu.biz/t5/144/1500630396x2890171902.png)
[dev](http://chuantu.biz/t5/144/1500630472x2064103272.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
