### ISSUE TITLE
Warn user about duplicate plugins

### ISSUE THREAD

**Issue by esbenp** [webpack/webpack#5363]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Seems a lot of issues are created from users unaware that some CLI flags are merely shortcuts to create plugins. Having duplicate plugins causes unwanted behaviours. Example issues are #4192, #4713, #5233. Surely there are more.

**If the current behavior is a bug, please provide the steps to reproduce.**

Add something like `UglifyJsPlugin` and run webpack with `--optimize-minimize`

**What is the expected behavior?**

Give presedence to CLI (#5359)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Beginners to Webpack might be confused when to use flags like `--optimise-minimize` or when to use plugins `new UglifyJsPlugin`. We could add console warnings when multiple instances of the same plugin type exists or similar. Add a short link to documentation page that explains how CLI flags are short-cuts and that CLI flags will take presedence. The React library is particularly good at providing these warnings.

An initial list of some things to consider:
* Are there any plugins that could have multiple instances?
* Should check blindly for duplicates, or should there be a blacklist (like multiple `UglifyJsPlugin` instances are unwanted, but that might be the case for other plugins)
* What to do about flags with multiple features (e.g. `-p`) - should warnings communicate that `-p` is more than just minification?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
Something about the plugin system is that Plugins are simply instances with an apply function on the prototype chain. 

I've attempted to try and do this [in another project](https://github.com/TheLarkInn/bundle-buddy-webpack-plugin/blob/master/src/index.js#L30-L47) however I'm not sure if this is even remotely reliable. This is because really anyone can modify the names of these plugins based upon how the import/require them and reference them into their configuration.

**Comment by ooflorent** [comment]
> Something about the plugin system is that Plugins are simply instances with an apply function on the prototype chain.

In webpack 4, the plugins defined in the configuration are _added_ like this:

```js
for (const plugin of plugins) {
  plugin.apply(compiler);
}
```

Whereas internal defined plugins are added this way:

```js
new NodeStuffPlugin().apply(compiler);
```

What's interesting in the last example is that webpack doesn't know _what_ is the plugin. A plugin is a closure that accept a `Compiler` instance. But for compatibility reasons `.apply` has been kept.

Knowing this, how webpack could identify that a plugin is duplicated? Well, it could check `config.plugins` for duplicated `plugin.constructor`, that may be ok most of time but it won't catch plugins added outside of `.plugins`.

_Now let's assume we solved the deduplication._

I understand that having the same plugin added multiple times is mostly unintended and would slow down the build or introduce WTF moments, but what about the cases where it's intended?

The most duplicated plugins are probably:

- `UglifyJsPlugin` because of misconfiguration
- `HotModuleReplacement` for the same reasons
- **`DefinePlugin` because it is intended** (note: `EnvironmentPlugin` adds `DefinePlugin`) https://github.com/webpack/webpack/blob/c963e3db54adef8e1e3aea4383e09fa472131106/lib/EnvironmentPlugin.js#L46

cc @probablyup

**Comment by TheLarkInn** [comment]
With the new plugin system we can detect multiple instances with interceptors. See how ProfilingPlugin does this.

**Comment by ooflorent** [comment]
That’s true for plugins using `hooks`. Not those who are relying on the compat layer.

**Comment by ooflorent** [comment]
Even with `intercept` there will be false alarms. For example, given following plugin:

```js
new DefinePlugin({
  "a.b" : 1,
  "a.c": 2,
})
```

It will register the same hook multiple times:

```js
canRename.for("a").tap("DefinePlugin", …) // called twice
```

**Comment by probablyup** [comment]
What if the new plugin system had a way of a plugin signaling that duplication was OK? Or perhaps vice versa (disallow). Uglify definitely shouldn't be run more than once.

I do think comparing constructors is probably sufficient, short of a way of adding unique names to plugins. We aren't looking for a silver bullet here, just a good-enough way of avoiding pitfalls.
