### ISSUE TITLE
All the chunks are loaded at once, not on demand

### ISSUE THREAD

**Issue by yantakus** [webpack/webpack#5364]
I have the following issue with [this demo app](https://github.com/yantakus/webpack-example): when a page is loaded, all the chunks of the app are loaded at once, not just the ones needed for this exact route. When a user goes to another page, of course, no more chunks are loaded on demand.

**Comment by awesomenaz** [comment]
Hi @yantakus this is react-boilerplate, why don't you raise an issue with the folks there. It could be related to the configuration they have and how they manage routes chunking.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
