### ISSUE TITLE
Webpack build times can they improved in dev mode?

### ISSUE THREAD

**Issue by enigma1** [webpack/webpack#539]
Can we have an option to disable the chunk optimize assets calls when in development? On my system (desktop/i3/4GB) typical build times exceed 30secs. Now if I go into the Compilation.js and skip the optimize-chunk-assets/after-optimize-chunk-assets calls then I get the bundle ready in a couple of secs.

With the implementations I tried so far I do not see side effects but would like to confirm it.

**Comment by tkriplean** [comment]
@sokra I thought I'd share here an one of the performance challenges I ran into with "optimize chunk assets" being triggered in development, which seems pertinent to this issue. 

I was seeing 3-4s recompilation times in development mode, getting stuck at the optimize chunk assets step. I was confused why the optimization was even being triggered, as I had no plugins that enabled it (as @enigma1 had). 

The issue was that I was using the [-d](http://webpack.github.io/docs/cli.html#development-shortcut-d) CLI option, which was overriding my "cheap-eval-source-map" setting for devtool in my webpack config file to "source-map". In turn, the watch process was recreating the sourcemaps every time I made even the smallest change to a file. Recompilation speed drastically improved after removing the -d option. 

Why does the "development shortcut" -d specify devtool "source-map" in the first place? It seems to lead to really slow build times in dev mode. Why not have -d equal "--debug --devtool cheap-eval-source-map --output-pathinfo"?

**Comment by sokra** [comment]
> Why not have -d equal "--debug --devtool cheap-eval-source-map --output-pathinfo"?

Yes, I've changed that in the webpack-2 branch for the next major version, but it's a breaking change so we just can't change it in the 1.x version.

**Comment by tkriplean** [comment]
Great, thanks

**Comment by dschissler** [comment]
I was drinking beer with some nice fellows some weeks ago and they told me that webpack works much better if it is used without gulp.  They couldn't specify what the issues were exactly but that it was simply problematic.  I don't need gulp at all as everything is performed with a loader.  I don't have a huge project and my build times were 8-10 seconds on an Ubuntu Thinkpad T430s and now I have a bit of a slower and light Macbook 12 and it is taking 20 seconds on first build in my Ubuntu VM.  So its become too slow and I think that I must be doing something wrong if other people are getting just several seconds.  My private project is based on this [webpack config](https://github.com/perchlayer/webird/blob/master/dev/gulpfile.webpack.js).  Is there anything glaringly wrong with this?  I'm not using angular in my private project.

**Comment by JsonHunt** [comment]
I noticed significant build time boost of the "additional chunk assets" slowness by adding this in webpack-config:

```
var pkg = require('./package.json');
var excl = Object.keys(pkg.devDependencies).map(function(i){
	return new RegExp("node_modules/"+i);
});
module: {
   noParse: excl,
   ....
```

**Comment by dschissler** [comment]
@JsonHunt I think that you might want to find a different way to do this because most of the Webpack and front end dependencies (to be compiled and provided to client) should be put into devDependencies.  Then if your application also requires something of a server process say like Socket.io then you can install those on the server by calling install to exclude devDependencies.  So in other words everything installed for Webpack is a devDependency (ie. Frontend framework, jquery, etc).

**Comment by ZuBB** [comment]
thanks @tkriplean! your hint do works

**Comment by trzenaro** [comment]
@IAMtheIAM 
Is there any file I need to change to apply the setting "cheap-module-source-map"?
I'm just running "ng serve" and I can't find where to change to apply the configuration.

**Comment by guiomie** [comment]
@trzenaro I think this is something youd want to modify in the anglar-cli code. 

Take a look at this file, it has a devTools property -> https://github.com/angular/angular-cli/blob/5431abc8457b436e68799f481d0d40c4cdcb29e2/packages/angular-cli/models/webpack-build-development.ts

**Comment by trzenaro** [comment]
@guiomie 
Thank you. That's what i needed. It solved

**Comment by guiomie** [comment]
@trzenaro  I modified the file with 'cheap-eval-source-map' and I don't see an improvement. Did you do something after the modification to the file?

**Comment by trzenaro** [comment]
@guiomie I forgot to mention that It didn't work when I tried to modify the file in the globally angular-cli module.
Take a look at the same file on your project tree
../your-angular-cli-project/node_modules/angular-cli/models/webpack-build-development.js

One more tip:
I'm using "eval" instead of "cheap-eval-source-map" because I had some issues while debugging. I don't know why the generated file is pointing to the wrong line (most of the times is 3 or 4 lines above where it should be)

**Comment by guiomie** [comment]
Thanks for the precisions. I tried with cheap-eval-source-map and eval in my local project node_module folder, and I'm still at around ~10s, maybe it's it my laptop that isn't strong enough.

**Comment by SpaceK33z** [comment]
Closing this issue since there is not really anything to fix here anymore...
