### ISSUE TITLE
stats.assetsByChunkName does not include dynamic chunks

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#5403]
Using `import()` we get chunks in stats for sync chunks but not for async chunks. 

Repo to reproduce: 
https://github.com/mohsen1/universal-async-component-example/blob/master/webpack.config.ts#L91

Update fileds to be only `assetsByChunkName`

Node: 8.0.0

Webpack: 3.4.0

**Comment by mohsen1** [comment]
Hmm... My chunks have ids not names. Is that why?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
