### ISSUE TITLE
css file + ModuleConcatenation bailout: Module is not an ECMAScript module

### ISSUE THREAD

**Issue by AlexGalays** [webpack/webpack#5404]
Webpack 3.4.1 reports `ModuleConcatenation bailout: Module is not an ECMAScript module` even for modules that obviously couldn't be an ES module such as LESS file. Having lots of LESS files this is very distracting.
The LESS files are loaded using ExtractTextPlugin->style->css->less.

Is there any way to tell ModuleConcatenationPlugin to ignore some modules?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by atav32** [comment]
@AlexGalays you could add some options, [ModuleConcatenationPlugin.js](https://github.com/webpack/webpack/blob/f75418f6683af5e7cab86d67d896bf5001075836/lib/optimize/ModuleConcatenationPlugin.js) and open a PR
