### ISSUE TITLE
uglifyjs not working on transpiled file:ERROR in bundle.js from UglifyJs Unexpected token: keyword (function)

### ISSUE THREAD

**Issue by ir-fuel** [webpack/webpack#5412]
I understood that UglifyJS does not work on ES6 code, but it seems something else is wrong on my side.

The development/hot reload builds work fine. When building for production however I get

```
ERROR in bundle.js from UglifyJs
Unexpected token: keyword (function) [bundle.js:105316,6]
```

This is what my config looks like for js(x) files

```
      {
        test: /.jsx?$/,
        exclude: /node_modules/,
        include: path.join(__dirname, 'client'),
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              plugins: [
                "transform-decorators-legacy",
                "transform-class-properties"
              ],
              presets: [
                ['es2015', {modules: false}],
                'react',
              ],
            }
          }
        ]
      },

```

When opening the generated `bundle.js` I see no occurences of `let` or `const`, so I presume the code was correctly transpiled to ES5.

I am running webpack 3.4.1

Any idea what I might be missing?

Thanks

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
