### ISSUE TITLE
Exception in Module Concat Plugin

### ISSUE THREAD

**Issue by jezell** [webpack/webpack#5415]
Adding ModuleConcatPlugin to my webpack config results in following error:

```
ERROR in chunk main [initial]
[name].[chunkhash].js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at enterNode (.../node_modules/webpack/lib/optimize/ConcatenatedModule.js:118:14)
    at getPathInAst (.../node_modules/webpack/lib/optimize/ConcatenatedModule.js:97:24)
```

This using Webpack 3.4.1. Everything compiles without issues if the concat module plugin is removed.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
