### ISSUE TITLE
Proxy access to http local over a https site, the sock-js request used a wrong https protocol.

### ISSUE THREAD

**Issue by iahu** [webpack/webpack#5440]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
HRM not work.

**If the current behavior is a bug, please provide the steps to reproduce.**
I set up a http dev-server, proxy 'https' access to the 'http' dev-server over a 'https' site.
the sock-js request goes to use the https protocol. Because of the dev-server runs on a http protocol, https request would not be processed.

**What is the expected behavior?**
the sock-js request use `http` protocol.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack version: 2.3.3
Node.js version: 6.9.5\
OS: Mac OS 10.12.5

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server

**Comment by orangeyyy** [comment]
Hi @sokra  I have got the same problem, the steps to reproduce the problem is shown as below:
1, start a webpack dev server at local which is use **http**;
2,start a proxy server to proxy the resource online to local(the online site use **https**),in this case we can debug the online website at local;

everything is ok now except the HMR, the screen is shown below ：
![default](https://user-images.githubusercontent.com/19667299/39661845-774e9d04-508b-11e8-99a5-d4edd34e5c1a.png)
the reason of this problem is that HMR send the sockjs-node request with **https** protocol which is same with the online site, so I wander to know if we can set the protocol of the sockjs-node request to **http** and the problem will be resolved.

http:
![image](https://user-images.githubusercontent.com/19667299/39661893-276867f6-508c-11e8-88dc-08e1942e74ef.png)

https:
![image](https://user-images.githubusercontent.com/19667299/39661891-1b901eb0-508c-11e8-85d8-7c8b3e323332.png)


sorry that this case need use a online https website so is hard for me to provide a test case repo, hope you can understand what say above

**Comment by rainjm** [comment]
I have got the same problem @orangeyyy

**Comment by evilebottnawi** [comment]
@rafde if you self signr certificate what is not accepted your browser

**Comment by rainjm** [comment]
@evilebottnawi 
This https site service is not built by me, and how to set up ssl in intranet ip
