### ISSUE TITLE
How to include a worker/process file with webpack

### ISSUE THREAD

**Issue by wagenaartje** [webpack/webpack#5445]
I have a file that creates child processes, the code is similar to this:

```js
var cp = require('child_process');

function process () {
  return cp.fork('./worker');
}
  
module.exports(process);
```

But `./worker` doesn't seem to be included in the bundle. Which causes the following error:

```js
    Error: Cannot find module 'C:\Users\USER\Documents\GitHub\PROJECT\worker'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Function.Module.runMain (module.js:605:10)
        at startup (bootstrap_node.js:158:16)
        at bootstrap_node.js:575:3
    module.js:487
        throw err;
        ^
```
How can I make sure worker files are bundled as well? I want my whole project in óne file.

[See StackOverflow question](https://stackoverflow.com/questions/45521024/how-to-include-a-worker-process-file-with-webpack)

**Comment by wagenaartje** [comment]
I now use the [`CopyWebpackPlugin`](https://github.com/kevlened/copy-webpack-plugin) to place the `worker.js` file next to bundle file. However, this is a pain in the ass for `require` statements in `worker.js`.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
