### ISSUE TITLE
angular.min.js:sourcemap:123 TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by RagguRavi** [webpack/webpack#5456]
var app=angular.module('myapp',[]);
app.controller('mycon',control);

function control($scope){
	var s=$scope;
	s.name="ravi";
	s.uname="raviraggu";
	s.submit=function(){
		window.alert("clicked");
	}
}

app.directive('myDir',function(){
	return
	{
		template:'This is template'
	};
});

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
