### ISSUE TITLE
Usage with Web Components

### ISSUE THREAD

**Issue by wprater** [webpack/webpack#547]
Any examples of how one can use this with Web Components, or say, Polymer?

**Comment by VictorBlomberg** [comment]
[polymer-loader](https://github.com/JonDum/polymer-loader) seems to have some support, but as of now requires the JavaScript Polymer(...) registration in a separate JavaScript file, which makes it somewhat incompatible with Polymer Paper Elements collection, if I understand it correctly. I've filed an issue https://github.com/JonDum/polymer-loader/issues/1, and I plan to look into it.

There's also a related issue in the [html-loader]() repo, https://github.com/webpack/html-loader/issues/14.

Have anyone here made any progress?

**Comment by jhnns** [comment]
This is probably also related to webpack/webpack#860 since polymer components can host html, js and css?

**Comment by VictorBlomberg** [comment]
Yes, it seems highly relevant. Asked OP about current status, with any luck it could be a good start.

**Comment by aabluedragon** [comment]
Any news / plans? Polymer is now 1.0, and still can't be used nicely with webpack.

**Comment by yutingzhao1991** [comment]
I make a simple solution with [polymer-ext](https://github.com/yutingzhao1991/polymer-ext)

**Comment by cookiengineer** [comment]
Following this issue and looking at the code inside [polymer-loader](https://github.com/JonDum/polymer-loader/blob/master/index.js), I am a bit concerned.

Is this the proposed solution?

The problem I have is the mixup between the document objects. There are actually two, one for the HTML Imports component and one for the main javascript runtime (where the library is added as a property to window).

How would someone write a loader if his code relies on those two objects in order to have a proper supported Shadow DOM implementation?

I'm asking because the code for my library fytoJS looks [like this](https://github.com/Artificial-University/fytoJS#fytojs-quick-example) and I have no single clue where to start with webpack.

**Comment by AircityScript** [comment]
Loaders should do only a single task , but those loaders do actually like a manager.How terrible they are!
Somehthing should be done to support inline web components

**Comment by aruntk** [comment]
I've built a package to handle polymer/webcomponents files and html imports (with code reload support) https://github.com/aruntk/wc-loader. check out.

**Comment by Shyam-Chen** [comment]
https://github.com/rnicholus/web-components-loader

**Comment by vardius** [comment]
I've setup a [simple boilerplate](https://github.com/vardius/web-components-webpack-es6-boilerplate) webpack2 project for web components. Hello world example with template.  You can easy add polymer to it.

**Comment by jrunning** [comment]
For those following this thread, [webpack-contrib/polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader) is worth taking a look at. @robdodson did a writeup on Medium: https://medium.com/dev-channel/how-to-use-polymer-with-webpack-b41812d78b15

**Comment by evilebottnawi** [comment]
Thanks everyone! Please use https://github.com/webpack-contrib/polymer-webpack-loader for web components
