### ISSUE TITLE
Could not find package.json up from: /

### ISSUE THREAD

**Issue by ramiromd** [webpack/webpack#5492]
I have a little Node Express packaged application with the following _webpack.config.js_:
```
module.exports = {
    target: 'node',
    entry: './server.js',
    output: {
        filename: 'node-server.min.js'
    }
}
```

When i run `node node-server.min.js` the application works fine but, when i load the file from Electron i am getting the following error message:

> Uncaught Error: Could not find package.json up from: /
>     at Function.pkginfo.find (node-server.min.js:6373)
>     at Function.pkginfo.read (node-server.min.js:6390)
>     at module.exports (node-server.min.js:6341)
>     at Object.<anonymous> (node-server.min.js:6403)
>     at Object.styles (node-server.min.js:6408)
>     at __webpack_require__ (node-server.min.js:20)
>     at Object.<anonymous> (node-server.min.js:14624)
>     at Object.<anonymous> (node-server.min.js:14699)
>     at Object.<anonymous> (node-server.min.js:14701)
>     at __webpack_require__ (node-server.min.js:20)

I am loading node-server.min.js file with a script tag.

Any ideas ?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
