### ISSUE TITLE
Angular2 Webpack2 file imports fail with error 404

### ISSUE THREAD

**Issue by darshil-doshi** [webpack/webpack#5524]
I want to report a bug

I am trying to build Angular2 project for production profile. 'dist' folder is created successfully, but when the index.html does not load. It gives error 404 for imports, etc. Here is the error:
![screen shot 2017-08-16 at 2 20 26 am](https://user-images.githubusercontent.com/14038070/29335813-87763c7c-8229-11e7-93e7-b82d62ea3bec.png)

Whereas, the dev profile is working perfectly.

Code is available here - https://github.com/darshil-doshi/angular2-webpack2

For reference, I followed angular2-webpack tutorial on https://angular.io/guide/webpack
I am using all the latest versions of webpack, loaders and plugins.

Please help me resolve this issue.

Thanks,
Darshil

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
