### ISSUE TITLE
[HOW TO] disable log level?

### ISSUE THREAD

**Issue by MegaUITeam** [webpack/webpack#5529]
[HOW TO] disable log level?

I can not find anything in the documentation https://webpack.js.org/concepts/hot-module-replacement/

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
