### ISSUE TITLE
Webpack lazy-loading chunk progress 

### ISSUE THREAD

**Issue by Makio64** [webpack/webpack#5536]
*Request for new feature*

Currently Webpack provide a powerfull & easy way to create chunk, very effiscient for code splitting on site and app.

As webpack already know the size of each bundle, it'll be amazing if we could have an easy way to handle the loading progress of the chunk during the runtime to create precise loader animation., here a syntaxe suggestion : 

```
require.ensure([module1,module2], (require,progressCallback)=>{
     //loaded
})

progressCallback = (percent)=>{
    //animation
}

```

Using the lazy-loading a lot on professional site, I feel providing precise loading time to my user is important, but I'm curious to have other developer as well as the webpack team opinion on it.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
