### ISSUE TITLE
Pass options to UglifyJsPlugin & use -p & not get an error

### ISSUE THREAD

**Issue by Artkoch** [webpack/webpack#5538]
I'm need to pass `drop_console: true` option to UglifyJsPlugin. But every time I do that it throws an error:
`Cannot read property 'sections' of null`

As far as I can understand, this is due to me using -p flag in package.json. 
Thus, it leaves me two options, remove -p, or don't pass `drop_console: true` option .
Neither of which I want to choose. I want to use -p, because it adds some magic which is important for prod build.

Is there a way to pass `drop_console: true` option to UglifyJsPlugin and use -p?

**Comment by michael-ciniawsky** [comment]
`uglifyjs-webpack-plugin` version ?

The `-p` flag sets `this.minimize` to `true` (`html-loader`, `css-loader`) and pushes `new UglifyJSPlugin()` into the plugins `{Array}`. I personally discourage it's usage, handling it in the `webpack.config.js` via `env === 'production' ? x : y ` is the more explicity and predictable way

**webpack.config.js**
```js
const env = process.env.NODE_ENV
...
{
  loader: 'css-loader'
  options: { minimize: env === 'production' ? true : false }
}
...
plugins: [
   env === 'production' ? new UglifyJSPlugin() : false
].filter(Boolean) // <= 
```

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by Artkoch** [comment]
Fair enough.
