### ISSUE TITLE
Multiple Entry Points with DllPlugin

### ISSUE THREAD

**Issue by chhu1** [webpack/webpack#5541]
**Current**
entry config
```
entry: {
  react: [
    'react',
    'react-dom',
    'prop-types'
  ],
  vendor: [
    'react-motion',
    'react-router-dom',
    'mobx',
    'mobx-react'
  ],
  vendor2: [
    'classnames',
    'querystring',
    'es6-promise',
    'fetch-jsonp',
    'isomorphic-fetch',
    'history/createHashHistory'
  ]
}
```

output
``` 
                Asset          Size       Chunks                    Chunk Names
     dll/vendor.65b2d.dll.js   354 kB       0  [emitted]  [big]  vendor
      dll/react.65b2d.dll.js   224 kB       1  [emitted]         react
    dll/vendor2.65b2d.dll.js  29.4 kB       2  [emitted]         vendor2
 dll/vendor.65b2d.dll.js.map  2.68 MB       0  [emitted]         vendor
  dll/react.65b2d.dll.js.map  1.82 MB       1  [emitted]         react
dll/vendor2.65b2d.dll.js.map   223 kB       2  [emitted]         vendor2
```

**expect**

`entry.vendor` is dependent on `entry.react`
vendor.65b2d.dll.js does not include react module

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
