### ISSUE TITLE
hot update failed in vue multipage 

### ISSUE THREAD

**Issue by zhengcaiyunjob** [webpack/webpack#5550]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

 when I create a multi-page system with vue, I use the webpack-dev-server, but I found the config of hot modules replacement failed, I refered some releated documents and found that the directory that contains the runtime code is not the source that the browse running. the releated demo is https://github.com/zhengcaiyunjob/vue-webpack。the same problems also exist in vue-cli demo.

the reproduce step is ；
1. git clone https://github.com/zhengcaiyunjob/vue-webpack.git;
2. cd vue-webpack;
3. npm install;
4. http://127.0.0.1:3001/index1.html#/foo；
5. then you can modify any files in directory index1, or the siblings directory, the hot modules replacement failed.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
