### ISSUE TITLE
Importing action creator to reduce bundle size do not work anymore

### ISSUE THREAD

**Issue by moimael** [webpack/webpack#5552]
Hi,

We use the babel import plugin and `import * as actions from 'redux-form/lib/actions';` to import redux form action and keep the bundle size reasonable. It worked fine up until now. It seems like now, `actions.<action_name>` does not work anymore, all actions are exported under the `default` key, so we have to change it to `actions.default.<action_name>` which is not expected and also is a breaking change.

Thanks.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
