### ISSUE TITLE
Handling app updates with chunking and lazy loaded routes doesn't seem possible.

### ISSUE THREAD

**Issue by zackiles** [webpack/webpack#5553]
**Do you want to request a *feature* or report a *bug*?**

This could be a bug or feature.

**What is the current behavior?**
My app has multiple React routes, and will lazy load chunks on route change. If a user is viewing the site while a new build is made, this will remove chunks the browser holds references too, and when the user changes their route the app will request that missing chunk and receive a 404 html response. Because it's a 404 (and html) webpack fails to load this chunk resulting in a complete app crash requiring the user to refresh and/or clear their cache to get the new version. This will sometimes show a "Syntax error: Unexpected token <"  in the console when trying to load these missing chunks.

**What is the expected behavior?**
That the app doesn't crash. Possibly a way to detect missing chunks from the server and force a reload to get the new updated version which points to the correct chunks.

I'm aware of the offline plugin which can auto-update all the chunks if it detects an update, but this isn't a reliable solution because service workers aren't supported on every browser.

**Comment by sokra** [comment]
* Don't delete chunks from previous versions from the server. Keep them around for a bit (maybe a few weeks)
* `Syntax error: Unexpected token <`: Configure your server to send correct 404 responses in these cases. Don't send HTML when JS is requested.
* Attach an error handler to the `import()` calls. `import().catch(...)

**Comment by yantakus** [comment]
Hi @sokra. Thanks for the answer. How do you expect `import().catch(...)` to help in this case? We already [do this](https://github.com/yantakus/webpack-example/blob/master/app/routes.js#L57). But it doesn't prevent the app from crashing when server returns an HTML page instead of requested JS file.

**Comment by sokra** [comment]
> We already do this.

Try to call the `getComponent` `cb` in case error too. Maybe with an error page.

**Comment by yantakus** [comment]
@sokra Sorry for the late response. The problem is [`importModules.catch()`](https://github.com/yantakus/webpack-example/blob/master/app/routes.js#L57) doesn't get fired at all because I get this error first:

![canada s medical marijuana marketplace and community - lift 2017-09-21 15-20-18](https://user-images.githubusercontent.com/2179726/30695355-95225b5c-9ee0-11e7-8f8c-dc1fff1577b9.png)

I even tried to wrap everything in try catch like this:

```javascript
try {
  importModules.then(() => {
    ...
  });
} catch (err) {
  ...
```

But `catch` block gets never called. So I think the above error happens somewhere before `importModules` is fired.

Any ideas on how to intercept it and make hard reload of the page?

**Comment by alexander-akait** [comment]
It means you still get 404, something wrong with configuration, feel free to feedback
