### ISSUE TITLE
Plugins (eg. "watch-run") for MultiCompiler instance not works

### ISSUE THREAD

**Issue by shyr1punk** [webpack/webpack#5565]
I don't know, its a bug or feature.

I create a MultiCompiler instance and add "watch-run" plugin:
```
const multiCompiler = webpack([{...}, {...}]);

multiCompiler.plugin('watch-run', function(watching, cb) {
  console.log('watch-run'); // don't print
  cb();
});

const watcher = multiCompiler.watch({}, (err, stats) => {
  console.log('Rebuild complete ' + new Date().toLocaleString()); //print
});
```
And this plugin's don't executes after project file change.

If I add plugin for compiler instance in `MultiCompiler.compilers` it's works:

```
const multiCompiler = webpack([{...}, {...}]);

multiCompiler.compilers[0].plugin('watch-run', function(watching, cb) {
  console.log('watch-run'); // print
  cb();
});

...
```

In docs i found only single compiler usage example https://webpack.js.org/concepts/plugins/#anatomy

I suggest:
1) Add docs for multi compiler plugin usage OR
2) Make it possible add plugins for MultiCompiler instance with binding to each complilers OR
3) I do something wrong?

Node.js 8.1.4
Webpack 2.7.0
MacOS X 10.11.6

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
