### ISSUE TITLE
How in the world do you SET process.env

### ISSUE THREAD

**Issue by bradennapier** [webpack/webpack#5574]
Electron forces you to SET the process.env in the main (node) process.  However webpack is converting it and making my app fail.

```js
process.env.GOOGLE_API_KEY = 'mykey'
```

is changed to:

```js
'mykey' = 'mykey'
```

thus an error. 

Using the environment plugin does nothing because there is a default key that i need to replace with my own and that ONLY does it if the key does not already exist.

https://electron.atom.io/docs/api/environment-variables/

**Comment by bradennapier** [comment]
When the target is electron-main webpack needs to not break node.js .... this is stupid as hell and tons of people are running into this and the only solution looks like a complete freaking mess

**Comment by bradennapier** [comment]
Had to use lodash to set the environment variables... LOL -- need a way to stop webpack from doing things.

```js
// webpack-ignore-next-line 
process.env.GOOGLE_API_KEY = 'mykey'
```

In node it is LEGAL ot set the process.env and you probably should not kill the feature all together in the first place... super super super annoying...

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
