### ISSUE TITLE
Createjs project html+js+lib want to use it within iframe inside vue component

### ISSUE THREAD

**Issue by andrew-basilioos** [webpack/webpack#5582]
<template>
      <div class="main pusher">
       <iframe :src="canvas"></iframe>
      </div>
    </template>

    <script>
    export default {
     data() {
        return {
         canvas:require("html-loader!../../none_node_modules/testCanv/Untitled-1.html")
        }
      }
    }
    </script>

    <style>

    </style>
it doesn't work , it will load the main home page not Untitled-1.html with no console errors

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
