### ISSUE TITLE
Promise-based Node API

### ISSUE THREAD

**Issue by stevenvachon** [webpack/webpack#5605]
From https://webpack.js.org/api/node/

Instead of:
```js
webpack(config, callback);
// or
webpack(config).run(callback);
```

it should be:
```js
webpack(config).then(stats => {}).catch(error => {})
```

**Comment by TrySound** [comment]
@stevenvachon `run` should exist for incremental build.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by stevenvachon** [comment]
@sokra what else did you want me to tell you? This is a feature request.

**Comment by stevenvachon** [comment]
@TrySound perhaps webpack should be a constructor, then:
```js
new webpack(config).run().then(stats => {}).catch();
```

**Comment by brainkim** [comment]
Hello from 2020, was there any progress on this?

**Comment by filmaj** [comment]
Hello from 2023, this worked for me in case anyone else is curious:

```javascript
const { promisify } = require('util');
const webpack = require('webpack');
const webpack_config = require('./webpack.config');
const compiler = webpack(webpack_config);
const pack = promisify(compiler.run).bind(compiler);
const close = promisify(compiler.close).bind(compiler);
const build = await pack();
```
