### ISSUE TITLE
Separate vendors file and visibility of imported code

### ISSUE THREAD

**Issue by karedas** [webpack/webpack#5632]
Hello, 
in my project I have the following architecture:

[root_projects]
[resources]
- [js]
[vendors]
--- [jquery_plugins1]
--- [jquery_plugins2] -[jquery_plugins2]
--- [jquery_plugins3] -[jquery_plugins3]
-- [Modules]
--- MyLib. MyModules1
--- MyLib. MyModules2
--- MyLib. MyModules3
--- MyLib. MyModules4

.....

What I did is to create an entry vendors. js that collects all the plugins placed inside the "js/vendors"folder. Within my html then recall, through the classic tag <script>, the output file (called vendors. min. js) and to follow other js files necessary to the page.

What I can't do (or make it simple) is to make sure that the modules inside vendors are visible at other entry points.

I have for example the lazyload plugin, included in the vendor. js file (package npm) through the call "var lazyload = require (' lazyload');" but that my main. js can't see. The error that appears to me at the simple call "**$(' selector').lazyload();**" it is "lazyload is not defined". 
In turn all the other plugins are not visible, the only way I was able to find is with a "**module.exports.pluginname= require('pluginname')**"  and recall the instance with the library of Webpack (example: **MyLib.vendors.pluginname)**).

Would you help me?
Thank you

(Sorry for my english!)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
