### ISSUE TITLE
setInterval with hotload is getting latest interval going on.

### ISSUE THREAD

**Issue by azurinko** [webpack/webpack#5659]
Current behaviour:

Once I have hotload turned on (tested with electron only but I bet it works everywhere) and I load a script with `setInterval(fn(){}, time)` and make it running everything is ok, and interval is running.

Once I change interval and save file, original interval is still running, new interval is running too, atleast that's what's my console is saying, can be confusing if you expect new interval to be runned automatically, you got to reaload page for that...

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
