### ISSUE TITLE
Dynamic Requires

### ISSUE THREAD

**Issue by JzKUO** [webpack/webpack#5680]
When I write:
```
require('../assets/home/img_1.jpg')
```
it works fine.

**But** if I write:
```
const path = '../assets/home/img_1.jpg'
require(path)
```
it goes wrong
> the error message shows:
> Error: Cannot find module "."

When I write:
```
const img_name = 'img_1.jpg'
require(`../assets/home/${img_name}`)
```
it works fine

Why?

**Comment by TheLarkInn** [comment]
This is because you need to tell webpack at least a partial path to your module. Nothing in webpack can be purely dynamic.

For support questions please visit gitter.im/webpack/webpack or open a question on Stack Overflow! 

For relevant documentation: https://webpack.js.org/guides/dependency-management/#require-with-expression
