### ISSUE TITLE
Full refresh with multiple webpack

### ISSUE THREAD

**Issue by vitorcamachoo** [webpack/webpack#5683]
Hello. Hi have a doubt. I have multiple webpack configs (imagine core and auth application). When running on dev mode, core application will run as webpack-dev-server with browsersync plugin. The other applocation will only run with webpack watch. Thanks thing is, core will render core assets and auth assets, and when I change something that belongs to core it apply HMR without refresh. When I made any change to auth, it will reload all the application.
Someone had that trouble before?
These webpack process are completely separated. They are consuming a common webpack config.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
