### ISSUE TITLE
async commons chunk is not named and not loaded with chunkhash

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#5693]
I have such config for common chunks:

![image](https://user-images.githubusercontent.com/736697/30542386-a38d4822-9c98-11e7-8233-43668eb966f0.png)

So it creates chunk that has shared code of `reader-app`, `promo-page` (which are chunks loaded using  `System.import` and `/*webpackChunkName: *` comment) but this chunk doesn't get symbolic names:
![image](https://user-images.githubusercontent.com/736697/30542470-f5fb5536-9c98-11e7-8cea-b99630fe6fa4.png)

webpack 3.6.0 seen from screenshot.

Without `async` option it is named `app-common`.

The next problem with loading this chunk and hashing the name.

The chunk is loaded ok when there are no hashes in chunk names used but when use `'-[chunkhash]'` suffix for chunkFilename, then it puts `undefined` in the request instead of hash.
![image](https://user-images.githubusercontent.com/736697/30542882-6ee52480-9c9a-11e7-9c9f-ec0d7c942019.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
