### ISSUE TITLE
Error: Cannot find module 'path-exists' while running webpack build via npm

### ISSUE THREAD

**Issue by sanjeet1827** [webpack/webpack#5716]
I observed a very wired problem while running webpack build via npm.
Sometimes an error is thrown Cannot find module 'path-exists' which automatically gets solved after some times (may a day or few hours).

If I install this module on my project directory then it give same error for module 'is-arrayish' and so on when installing modules every time when it is thrown in error.

Can anyone please help me out.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
