### ISSUE TITLE
This is not an issue! I really love Webpack ♥, thank you!

### ISSUE THREAD

**Issue by zaclummys** [webpack/webpack#5724]

**Comment by TheLarkInn** [comment]
You're welcome. 🙇🙇🙇 And thank you for the kind feedback. If you ever want to be more involved in the project, never hesitate to reach out.

**Comment by GeKorm** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

Hope I'm doing this right 😂

**Comment by evilebottnawi** [comment]
Big thanks!
