### ISSUE TITLE
add files to watch

### ISSUE THREAD

**Issue by firebird631** [webpack/webpack#5741]
During my process, I want to ignore some files to watcher. So I customize the watch method with a filter on the list of files. It works, ignored files are no longer watched. But what I need is to watch them again just after this compilation has done. So I try to add them to file dependencies, but it doesn't works.

Is a where a way to temporarely ignore some specifics files/pattern ?

In more details, my problem is, I rebuild i18next json output according to changes on some js or html template. If there is some changes I rebuild translation json files. But during this process if they stay watched I have an infinite loop, so I ignore them (that part works). But after I want to watch again them if I manually update a translation into those files (part that doesn't want to works).

So I have a state, and according to this state, ignore translation files from be watched, rebuild them, and reinject them to the watch list. But how to ?

Thank

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
