### ISSUE TITLE
i follow the tutorial but failed to bundle js file

### ISSUE THREAD

**Issue by sunq0001** [webpack/webpack#5746]
i follow the tutorial strictly to type webpack cmd.
> ./node_modules/.bin/webpack src/index.js dist/bundle.js

but it shows error

> '.' is not recognized as an internal or external command

then i tried
> node_modules/.bin/webpack src/index.js dist/bundle.js

still fail
> node_modules' is not recognized as an internal or external command

then i have to use global webpack, it can work, but without bundle lodash.js 
can anyone help?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
