### ISSUE TITLE
How can I solve watching problem in webpack?

### ISSUE THREAD

**Issue by kifli01** [webpack/webpack#5774]
I really hope, you can help me.
When I import a module in the index.js in a following way: ( import Test from './src/test'; ) Webpack recognizes the .web.js extension and uses it. However, if I make changes in the file system for instance I delete or rename this file, the webpack will notice that the file is missing. Nevertheless, it doesn't recompile and doesn't use the other file opportunity (test.js).

I have used webpack 3.6.0 and I tried to use in Watch mode, too. But unfortunately it doesn't work.

![webpack](https://user-images.githubusercontent.com/18379150/31309642-c9f81c1c-ab89-11e7-9992-4fa206da4464.gif)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
