### ISSUE TITLE
Allow non-integer module ids when performing requires

### ISSUE THREAD

**Issue by kpdecker** [webpack/webpack#579]
Currently modules work well enough with string values due to the object failover mechanism in `renderChunkModules`. Unfortunately the actual require calls simply concat `module.id` so this breaks down if string identifiers are needed for modules.

It would be nice if either `JSON.stringify` or a custom plugin point were used for the various places that the `__webpack_require__(x)` call is generated so modules with complex id naming can be supported.

Background here, we're building a versioned module linking system that simple ids will be quite difficult to safely resolve into the integer space at build time so we are attempting to use string prefixes on the per-module ids to avoid identifier conflicts.

**Comment by adjohnson916** [comment]
I have a use case for this as well. We have a non-traditional repo structure with some git submodules not under node_modules.  I want to map a nested dependency's require()s the root's copies of those dependencies, otherwise  the de-duping doesn't work. I tried using externals config but can't map to the generated module IDs without some kind of generated metadata mapping to IDs from name.
