### ISSUE TITLE
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by fengxinming** [webpack/webpack#5792]
WARNING in ./node_modules/.2.19.0@moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'D:\demows\h5-travel-plus\node_modules\.2.19.0@moment\src\lib\locale'

plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
