### ISSUE TITLE
webpack does not generate source map for webworker

### ISSUE THREAD

**Issue by raxim1** [webpack/webpack#5803]
it's generating the js file, but it's not generating the source map file to be able to debug easier

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
