### ISSUE TITLE
process.binding problem in the browser using `ng test`

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#5865]
Here is a screenshot of the problem:

<img width="1436" alt="screenshot 2017-10-21 12 39 48" src="https://user-images.githubusercontent.com/11139560/31855287-106c8772-b65d-11e7-9657-40382a018b9d.png">

My library (suman) creates its own polyfill for process, so that process.binding becomes a noop.

But the standard process polyfill throws an error when process.binding is called.

Does anyone know how to handle this problem? I really don't understand why the authors of the process polyfill for the browser decided to throw errors instead of making these methods on process no-ops.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
