### ISSUE TITLE
Feature request - Streaming a build to browser

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#5890]
Is there some way to stream a Webpack build to the browser

Something like this:

```js
const webpack = require('webpack');

app.use(function(req,res,next){ 
  webpack().pipe(res);
});
```

**Comment by ORESoftware** [comment]
I see there is a Gulp "plugin" for creating a streaming build - I am not sure how high fidelity is it.

What I am looking to do, is something like this:

<html>
 <head>
  <script src="a">
  <script src="b">
</head>
 <body>

  <script>
    // put the webpack build in here somehow
   // but I am not sure if you can write to a script tag in a streaming manner lol
 </script>
</body>

</html>

**Comment by ORESoftware** [comment]
Ok it looks like I can do this:

fs.createReadStream('template.html').pipe(writeToScriptTagWithWebpackBuild()).pipe(res);

the only tricky part is how to create a Webpack build that writes to a stream instead of writing to an output file.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
