### ISSUE TITLE
How can I bundle all assets files using WebPack?

### ISSUE THREAD

**Issue by willowTank** [webpack/webpack#5901]
Dear Sir.
Now I have developed frontend by react js.  When I run 'npm run build' it generates all assets files on build dir.
but I want all assets files are combined as one file.
Best Regards

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
