### ISSUE TITLE
Watch config in watch mode

### ISSUE THREAD

**Issue by paulpflug** [webpack/webpack#5921]
Hey,

The main reason for restarting webpack is a change in the configuration, at least for me.

For one of my projects I created a small package to read and watch a configuration file and all of its dependencies: [read-conf](https://github.com/paulpflug/read-conf).

All `require` calls while reading the config will be watched and invalidated, once changed:
```js
// example config
somePlugin = require("somePlugin") // all files read here will also be watched
// great for plugin development
// won't work for loaders, as they are given by name or path
module.exports = {
  ...
  plugins = [
    new somePlugin()
  ]
  ...
}
````

Something similar to this could go in the cli: 
```js
readConf = require("read-conf")
webpack = require("webpack")
compiler = null
watcher = null
readConf({
  name: "webpack.conf",
  filename: ,// if a config filename is given in args
  assign: {}, // options object generated from args, overwrites read-in config
  watch: ,// if webpack is in watch mode
  cancel: => {
    compiler.close()
    watcher.close()
  },
  cb: (conf) => { return new Promise((resolve) => {
    compiler = webpack(conf)
    // if  in watch mode
    watcher = compiler.watch({},=>{})
    // else
    compiler.run(=>{resolve()})
  }}
})
```

This functionality would definitely improve my webpack experience.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by paulpflug** [comment]
I'm sorry..
