### ISSUE TITLE
output.libraryTarget: expose library as an CMD module

### ISSUE THREAD

**Issue by JunreyCen** [webpack/webpack#5950]
1.CMD([Common Module Definition](https://github.com/cmdjs/specification/blob/master/draft/module.md))
2.how to make the library support cmd, such as [transform jquery into cmd module](https://github.com/seajs/seajs/issues/971)

My project use seajs to manage js modules, so it's neccessary for webpack to support output cmd library, instead of modifying output manually!

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
