### ISSUE TITLE
Cannot read property 'createDocumentFragment' of undefined

### ISSUE THREAD

**Issue by Archin-modi** [webpack/webpack#5969]
I have Big problem after successfully build project. when i was build project successfully after close the project and open next day they will run successfully. but  suddenly there is an error.
please help me.
![capture](https://user-images.githubusercontent.com/18736127/32909352-7bc09e94-cb2c-11e7-8083-ecd469601e65.PNG)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
