### ISSUE TITLE
Trouble getting bootstrap glyphicons to work

### ISSUE THREAD

**Issue by tombray** [webpack/webpack#597]
I'm attempting to use the standard bootstrap glyphicons in my app but it appears that the fonts aren't being used, although the files are generated and I'm not seeing errors.

Here are my loaders:
```
        loaders: [
            { test: /\.css$/, loader: "style!css" },
	        { test: /\.(jsx|js)$/, loaders: ['jsx'] },
            { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
            {
                test: /\.(otf|eot|svg|ttf|woff)/,
                loader: 'url-loader?limit=8192'
            }
        ]
```
Here are a few lines from the generated bundles.js that point to the processed files:
```
module.exports = __webpack_require__.p + "7ad17c6085dee9a33787bac28fb23d46.eot"
...
module.exports = __webpack_require__.p + "e49d52e74b7689a0727def99da31f3eb.ttf"
...
module.exports = __webpack_require__.p + "68ed1dac06bf0409c18ae7bc62889170.woff"
...
module.exports = "module.exports = __webpack_public_path__ + \"ff423a4251cf2986555523dfe315c42b.svg\""
```
I see the following in the webpack-dev-server output:

```
                                Asset     Size  Chunks             Chunk Names
 7ad17c6085dee9a33787bac28fb23d46.eot    20335          [emitted]  
68ed1dac06bf0409c18ae7bc62889170.woff    23320          [emitted]  
 e49d52e74b7689a0727def99da31f3eb.ttf    41280          [emitted]  
 ff423a4251cf2986555523dfe315c42b.svg    62926          [emitted]  
                            bundle.js  2143250       0  [emitted]  main
chunk    {0} bundle.js (main) 2024166 [rendered]
```

I'm using the unminified bootstrap.css and requiring that in my app. Any guidance you can give me for troubleshooting this?

Thanks!

-Tom

**Comment by mmahalwy** [comment]
Any luck on this?

**Comment by bdefore** [comment]
I'm also having this issue.

**Comment by clauderic** [comment]
I also have this issue, any luck?

**Comment by ppalladino** [comment]
Also having the same issue. Any path to success?

**Comment by clauderic** [comment]
Make sure you don't have two loaders processing the same file, that was the issue in my case

**Comment by ppalladino** [comment]
Actually, I think my problem is a bit different. I am loading bootstrap sass and webpack is blowing up trying to resolve the font file references. Thanks @clauderic but I think I need to poke around elsewhere....

**Comment by clauderic** [comment]
You can always skip the loaders entirely by using the absolute path to the fonts in your css, something along the lines of `url('/fonts/font.ttf')`, in which case webpack will not try to parse the font files at all

**Comment by ppalladino** [comment]
@clauderic Yeah, that is sort of my plan. I don't want all of the bootstrap component partials anyway, so I am creating my own sass file which brings in the core and cherry picking the bootstrap components I want. In doing so I can easily leave out the import of the glyphicons partial and make my own. So problem solved! Thanks for the quick reply.

**Comment by llambda** [comment]
I had this issue too, my problem was I had the svg-loader loader and also the .svg url loader. 

Here is a working bootstrap webpack with working glyphicons.

```
'use strict';

var webpack = require('webpack');

module.exports = {
    context: __dirname + '/app',
    entry: './main.js',
    output: {
        path: __dirname + '/client',
        filename: 'bundle.js'
    },
    module: {
        preLoaders: [
            {test: /\.js$/, exclude: /node_modules/, loader: 'jshint-loader'}
        ],
        loaders: [
            {test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
            {test: /\.less$/, loader: 'style-loader!css-loader!less-loader'},
            {test: /\.css$/, loader: 'style-loader!css-loader'},
            {test: /\.woff(2)?(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
            {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
            {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
            {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" }
        ]
    }
};
```

Then in your JavaScript:

```
require('bootstrap/less/bootstrap.less');
```

**Comment by ppalladino** [comment]
Thanks @llambda, I did not try your solution as I am cherry picking the sass modules I need. But, thanks for chiming in!

**Comment by max-mykhailenko** [comment]
Any news about this question?

**Comment by llambda** [comment]
You have to require the bootstrap.less, not the bootstrap.css, otherwise you won't get the fonts loaded.

**Comment by b-d-m-p** [comment]
I was having the same issue and then I realized that if my fonts are in the root of my project it works. My app compiles to a folder called "build", which is where the fonts are being output to. 

I'm new to this whole webpack thing. Is there a way I can get the project to see the fonts in the "build" folder?

**Comment by SkateFreak** [comment]
The solution that worked for me:
Check your "publicPath" attribute in webpack.config.js.

for instance:

entry: path.resolve(__dirname, 'app/index.js'),
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js',
        publicPath: 'build/'
    }

**Comment by b-d-m-p** [comment]
@SkateFreak Thanks! That worked perfectly!

**Comment by bebraw** [comment]
@tombray Safe to close?

**Comment by eduardonunesp** [comment]
Looks safe, the @llambda hint worked here

**Comment by A-Kasaaian** [comment]
@SkateFreak You saved my day :)

**Comment by nirajrajgor** [comment]
@clauderic Your answer was perfect for me. keep up the good work

**Comment by quadsurf** [comment]
@clauderic 

unfortunately this did not work for me:
loaders: [
    {
        test: /\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/,
        loader: 'url-loader'
    }
]

but changing it to this did solve it for me:
loaders: [
    {
        test: /\.woff$|\.woff2$|\.ttf$|\.eot$|\.svg$/,
        loader: 'url-loader'
    }
]

so basically, the difference was removing the following from each file type:
|\?)
and then i also had to remove all the left parenthesis

Can someone please help me understand why that lucky experimentation worked?

**Comment by thejohnfreeman** [comment]
I faced a similar problem tonight and wrote up my solution. Just in case it can help anyone here:

https://gist.github.com/thejohnfreeman/563337119e20d090ea2d22bee9b05a6b

**Comment by jbarr33** [comment]
I'm experiencing a problem with fonts NOT loading with webpack-dev-server only vs. using webpack build is fine. In both cases the fonts are "found" and processed. For build they are written to disk correctly and are served up to browser just fine. But for webpack-dev-server, even though it says the fonts are emitted I get a 404 on the fonts in Chrome, Firefox, and IE for the fonts.

I'm using Webpack 2.2.1 and webpack-dev-server 2.3.  Also using file-loader directly for fonts and url-loader only for images with specific regex's for each font. A ttf example below.

Any help would be appreciated.

Thanks.

**webpack-dev-server-output**
```
  ../fonts/glyphicons-halflings-regular.eot    20.1 kB          [emitted]
  ../fonts/glyphicons-halflings-regular.svg     109 kB          [emitted]
 ../fonts/glyphicons-halflings-regular.woff    23.4 kB          [emitted]
../fonts/glyphicons-halflings-regular.woff2      18 kB          [emitted]
```

**webpack.config.js**
```

    devServer: {
       contentBase: 'apps/' + appName,   // points to root of app
       https: false
    }, 
.
.
.
{
	test: /\.ttf$/,
	use: 'file-loader?name=[name].[ext]&outputPath=../fonts/&publicPath=/dist/fonts/&mimetype=application/octet-stream'
}
```

**Comment by jiggneshhgohel** [comment]
@jimbarrett33 I was facing the same problem you have mentioned and using the solution provided by @SkateFreak at https://github.com/webpack/webpack/issues/597#issuecomment-141787044 helped me resolve the problem

Before specifying the `output.publicPath` option this is what I was seeing

![screenshot from 2017-04-27 18 42 49](https://cloud.githubusercontent.com/assets/10440841/25484886/5f0085ba-2b79-11e7-880b-01638c8c21a7.png)

After adding that option the expected output as below:

![screenshot from 2017-04-27 18 43 56](https://cloud.githubusercontent.com/assets/10440841/25484934/9c044172-2b79-11e7-85d0-adf4a1dec3d9.png)

I am using **webpack 2.4.1** and **webpack-dev-server 2.4.4**

### example_application/webpack.config.js

**Before**


```
var path = require("path");

module.exports = {
  entry: {
    app: [
      "./src/index.js"
    ]
  },

  output: {
    path: path.resolve(__dirname + "/dist"),
    filename: '[name].js',
  },

  module: {
    rules: [
      {
        test: /\.(css|scss)$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'file-loader?name=[name].[ext]'
      },
      {
        test: /\.elm$/,
        exclude: [ /elm-stuff/, /node_modules/ ],
        loader: 'elm-webpack-loader?verbose=true&warn=true'
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&mimetype=application/font-woff'
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader'
      }
    ],

    noParse: /\.elm$/
  },

  devServer: {
    inline: true,
    stats: { colors: true },
    historyApiFallback: true
  }
};

```

**After**

```
....

module.exports = {
  ....

  output: {
    path: path.resolve(__dirname + "/dist"),
    filename: '[name].js',
    publicPath: "/"  // <-------------------------- added this
 }

...
...

```

**I also found various other links on web which mentioned about this problem and solutions suggested were to modify loader configuration and changing output file location etc. But I think that was not the problem in my case i.e. for development purpose. To get to the root cause of the problem I tried to inquire into why 404 is being returned when the logs show that the chunks are emitted.**

![screenshot from 2017-04-27 18 51 16](https://cloud.githubusercontent.com/assets/10440841/25485166/8420859c-2b7a-11e7-83c8-3ec0f333d533.png)

I tried to find out where the emitted resources are generated and this took me looking for where the hell these emitted chunks are stored on my dev machine file-system. But I couldn't find them. Tried to go through webpack docs and also searched on web for knowing about the default location on file-system webpack generates files to. Unfortunately no luck.

Then I shifted my focus from webpack to webpack-dev-server because at the end it is webpack-dev-server which is serving the resources and hence I started my finding in direction of where does webpack-dev-server generates the processed files and I found following SO posts wherein I discovered that  webpack-dev-server uses webpack-dev-middleware under the hood, which internally uses a in-memory file system and the processed and emitted files are stored on and served from this in-memory file system.

  http://stackoverflow.com/questions/33318457/bundle-js-file-output-and-webpack-dev-server
  http://stackoverflow.com/questions/31967771/where-do-the-webpack-output-files-from-the-react-hot-loader-go
  http://stackoverflow.com/questions/41309796/isnt-webpack-dev-server-generating-bundle-js-in-memory

I digged into the webpack-dev-middleware [source code](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/Shared.js#L86) and found that it uses [memory-fs](https://www.npmjs.com/package/memory-fs) which is a simple in-memory filesystem and Holds data in a javascript object.

And [here](https://github.com/webpack/webpack-dev-server/blob/99b273c0898f68ba3d81e5675defe99d52f8822d/lib/Server.js#L64) is how webpack-dev-server uses webpackDevMiddleware

```
// middleware for serving webpack bundle
this.middleware = webpackDevMiddleware(compiler, options);
```

Then I tried to find out from where those options are coming (in execution sequence ):

[processOptions(wpOpt);](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L430) -- **webpack/webpack-dev-server/../bin/webpack-dev-server.js#L430**

[function processOptions(wpOpt) {](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L196) -- webpack/webpack-dev-server/../bin/webpack-dev-server.js#L196

-----------------------------------------------------------------
_in  processOptions(wpOpt) function_

```
 	if(!options.publicPath) {
		options.publicPath = firstWpOpt.output && firstWpOpt.output.publicPath || "";
		if(!/^(https?:)?\/\//.test(options.publicPath) && options.publicPath[0] !== "/")
			options.publicPath = `/${options.publicPath}`;
	}
```

As can be seen  we can specify webpack-dev-server specific `publicPath`  option probably in object shown below in and defined in our webpack.config.js .

```
  devServer: {
    inline: true,
    stats: { colors: true },
    historyApiFallback: true
  }
```

But if that is not specified webpack-dev-server falls back to webpack's `output.publicPath` option. Again if it is not found set in case of development mode then it is set as an empty string `""`.

And this option is then further passed to the Server initialization.

-----------------------------------------------------------------

[server = new Server(compiler, options);](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L358) -- **webpack/webpack-dev-server/../bin/webpack-dev-server.js**

[function Server(compiler, options) {](https://github.com/webpack/webpack-dev-server/blob/99b273c0898f68ba3d81e5675defe99d52f8822d/lib/Server.js#L21) -- **webpack/webpack-dev-server/../lib/Server.js#L21**

Knowing the internal workings re-reading the documentation of webpack's `output.publicPath` option  [here](https://webpack.js.org/configuration/output/#output-publicpath) **is making sense now**.

![screenshot-webpack js org 2017-04-27 19-16-42](https://cloud.githubusercontent.com/assets/10440841/25486383/91e50cb2-2b7e-11e7-8d4f-7871a55cd6b7.png)

**P.S** I am very much new to this webpack, NodeJS, modules and related-stuff. I am first-time using webpack while trying to follow a Elm-Lang tutorial and while doing that encountered problem of fonts not getting loaded and hence my journey of finding a solution to it and understanding this whole thing. If any of the above information or understanding of mine I have shared has any mistakes please be kind enough to rectify those and informing me know about those.

Thanks for taking the time to read through this.

**Comment by petrpacas** [comment]
@jiggneshhgohel Thanks for sharing your thought process, mate!

**Comment by wsw70** [comment]
@jiggneshhgohel : thanks a lot for the detailed information. I had the same [question on StackOverflow](https://stackoverflow.com/a/45376588/903011) and your answer is right to the point.

Please copy/paste my answer over there if you wish (and remove the top part, and maybe copy/paste your info from GitHub over there?), so that I can accept it, I will then delete mine as I had no contribution to the solution.

**Comment by jiggneshhgohel** [comment]
@wsw70 I don't think it would be worth to copy all the details from here to answer your question on Stackoverflow. I think you have summarized it well and I am up-voting the answer :-) 

Thanks.

**Comment by rosethorn999** [comment]
@SkateFreak Thanks your sharing.  It Fixed my path issue.  But after I modify it to new value `publicPath:'newValue'` .  The npm webServer hot-reload is not working...Anyone have some idea?
