### ISSUE TITLE
only want dynamic Imports in production environment

### ISSUE THREAD

**Issue by PanJiaChen** [webpack/webpack#5996]
like:https://github.com/webpack/webpack/issues/4636

l have a big project. It‘s has about 200 pages, , l used the dynamic Imports every page.
but the hmr spend too long time

![image](https://user-images.githubusercontent.com/8121621/33130187-773010c6-cfcd-11e7-9cff-04f4f4c2864d.png)

when l not use dynamic Imports, It reduced the advanced module optimization time to milliseconds.

![image](https://user-images.githubusercontent.com/8121621/33130258-b0df43aa-cfcd-11e7-8443-0ad47dc2e2b3.png)

**So** l want only in production use lazy-loading by dynamic Imports.
**But** if l write a function like
```js
function _import(file) {
 return  import(`@/views/${file}.vue`)
}
```
according to
 > Every module that could potentially be requested on an import() call is included. For example, import(`./locale/${language}.json`) will cause every .json file in the ./locale directory to be bundled into the new chunk. At run time, when the variable language has been computed, any file like english.json or german.json will be available for consumption.

**So** it will  require every `.vue` in `@/views` and build this `.vue` although l not use it.

```js
//@/views/login
import socialsignin from './socialsignin'

//@/views/socialsignin
```
it will build like this.
static/js/22.41970889bdf8bc55e772.js (2.84 KB) is build,but will never be used

![image](https://user-images.githubusercontent.com/8121621/33130887-bde277d2-cfcf-11e7-8b11-b5b5092801f0.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
