### ISSUE TITLE
Angular CLI adding hashed code internally in vendor.js file while running the build.

### ISSUE THREAD

**Issue by Sandy2308** [webpack/webpack#6021]
When I am running the "npm run build" then the Angular CLI is giving me the 5 different bundled files.
1) main.js
2) Inline.js
3) polyfills.js
4) styles.js
5) vendor.js

So inside the vendor.js file I can see something like below.

"form","h1","h2","h3","h4","h5","h6","header","hgroup","hr","main.234bhasd42341234","nav","ol","p","pre","section","table","ul"]

Above code is having main.234bhasd42341234 instead of main because of that I am getting an below  error while rendering. Please let me know If anyone is having any solution for this.
 
![image](https://user-images.githubusercontent.com/34028550/33305099-76036720-d432-11e7-9130-a1399513c2e7.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
