### ISSUE TITLE
Output a single vue component

### ISSUE THREAD

**Issue by TommyCat008** [webpack/webpack#6025]
How can I output only a single vue component ！
Anybody can help me , thx !

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by TommyCat008** [comment]
ok, i had made a mistake, and i had already solved this question. thx!
