### ISSUE TITLE
Cannot statically analyse 'require(..., ...)' in line

### ISSUE THREAD

**Issue by cybermerlin** [webpack/webpack#6031]
```
            var paths = [];
            this.kit.forEach(function(name) {
                var iconConfig = config.icons[name];
                if ( f.isObject(iconConfig) && iconConfig.plugin ) {
                    paths.push("classes/grid/toolbar/icons/" + iconConfig.plugin);
                }
            });
            require(paths, callback);
```
need something to ignoring some `require()`

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by cybermerlin** [comment]
возможно, вам не нужна помощь по доработке проекта. Пусть и дальше он остается сюрпризом младенцев.

**Comment by Starkemis** [comment]
> возможно, вам не нужна помощь по доработке проекта. Пусть и дальше он остается сюрпризом младенцев.

Fuck you.
