### ISSUE TITLE
The webpack config 'output.path' should support function.

### ISSUE THREAD

**Issue by hopefuture** [webpack/webpack#6037]
The webpack config 'output.path' should support function. Different output path can be set dynamically based on different entry.  Sometimes I want different entries to be generated into different folders. For example

```
output: {
    path: function(entry) {
      return require('path').resolve('./build', entry);
    },
    publicPath,
    filename: '[name].css',
    sourceMapFilename: '[file].map',
  },
```

Hopefully, it will be supported in future releases. Thanks.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
