### ISSUE TITLE
dynamic import() chunk basepath

### ISSUE THREAD

**Issue by janryWang** [webpack/webpack#6070]
how to config the basepath?

![image](https://user-images.githubusercontent.com/4060976/33605047-1434e3cc-d9f3-11e7-9103-943cc9ce20e1.png)

**Comment by janryWang** [comment]
@sokra

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
