### ISSUE TITLE
require.context() rebuilds on every incremental build

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#6093]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`require.context()` modules get rebuilt even when modifying unrelated file. See image below. In that instance, only the first file was edited, but it seems to rebuild the require.context()'s for the whole product...
![image](https://user-images.githubusercontent.com/95201/33743593-675b45ee-db62-11e7-9bd5-b3e2441dd640.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

add a `require.context()` to one of your js files.
An example: `require.context('my-config', true, /[.]json$/);`
(in our case, we use an alias in the first arg, not sure if that matters or not)

**What is the expected behavior?**
`require.context()` does not get rebuilt each incremental build, unless necessary.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node v8.9.1, webpack 3.8.1

**Comment by TheLarkInn** [comment]
@MagicDuck do you think I could twist your arm into repro'ing with a small repro repository that we can test against?

**Comment by MagicDuck** [comment]
@TheLarkInn arm successfully twisted :)
see repro repo here:
https://github.com/MagicDuck/require_context_issue

**Comment by sokra** [comment]
This seem to be a bug. It should rebuild depending on the director timestamp.

**Comment by ericpitcher** [comment]
@sokra @TheLarkInn We've got this problem in our codebase at work, running latest version webpack 4.43.0. Our code uses require.context to require locale json files, those json files are colocated with component files, the directory argument to require.context() thus also watches all the other files that are beside the json files that we want to glob require.

We have 30 languages and our build was slow when I started at my current workplace. We are using hmr with React, changing a Component also rebuilds all the locale modules which takes 4 seconds, I got the build time down to 1 second when not executing the require.context but I will need to find a way around this. Is there something I could do to fix this?

**Comment by ericpitcher** [comment]
@sokra Hi Tobias, do you know if this is a bug or will require.context always work like this?

**Comment by evilebottnawi** [comment]
@ericpitcher it is bug, we need fix it

**Comment by sokra** [comment]
require.context will watch the directory for changes. Changes to any file in the directory will rebuild the context module. Building the context basically means calling readdir. The modules in the context are watched and build separately

**Comment by ericpitcher** [comment]
@evilebottnawi thanks for response!
 
@sokra I can't tell if what you are describing is buggy behavior or how it is supposed to work. We're using webpack-dev-server at my work, with watch mode, watching for changes on modules in ./src. 

Then there's the fact that there's about 1600 json locale files (30 different languages) colocated with components spread throughout directories below ./src, and require.context globs for the locale json files. 

For each of the 30 locales we do (where `'../../'` is `src` dir):

`const translationContext = require.context('../../', true, /.*Locales.*.de.json$/);`

Changes to any file in src will also rebuild the modules that all of the require.context calls build.

Admittedly our approach to implementing localization could be different and more effective where we wouldn't need to use require.context. There's a couple of developers before me that had not cared much about our slow build speeds but I do care about developer experience and I'd say there's got to be a lot more codebases that's got this performance problem that don't know it and would benefit by an update :)

**Comment by evilebottnawi** [comment]
@ericpitcher Can you create reproducible test repo? Maybe something other do invalidation

**Comment by ericpitcher** [comment]
@evilebottnawi 

Here https://github.com/ericpitcher/webpack-require-context-rebuilding
`npm start` runs webpack-dev-server

Entry file (index.js) has `const context = require.context('./foo', true, /.+.en.json$/);`

When you change a module in ./foo, for instance `module-in-foo.js` which doesn't match the require.context regex,
that module gets rebuilt (expected), but there is also some computation around the matched require.context modules that happens (I'm not entirely sure that they are all rebuilt), but that computation in our codebase takes a long time because we have about 1600 matched files like I wrote earlier. Does it really need to do any computation when the file that is changed does not match the regex?

Here's a screenshot of webpack terminal output when changing `module-in-foo.js`:

<img width="647" alt="Screenshot 2020-07-18 at 15 52 28" src="https://user-images.githubusercontent.com/2662680/87854283-26c08680-c911-11ea-8cd5-dcafc688f03f.png">

In the output above I do expect to see this line when I change `module-in-foo.js`:
`[./src/foo/module-in-foo.js] 37 bytes {main} [built]`
But I do _not_ expect to see this line:
`[./src/foo sync recursive .+.en.json$] ./src/foo sync .+.en.json$ 200 bytes {main} [built]`

---

The require.context call cares about the `foo` directory in our case, when changing a module that is outside of the `foo` directory we do not get that computation, which really is what I'd expect when changing `module-in-foo.js` also because it does not match the regex:

<img width="456" alt="Screenshot 2020-07-18 at 15 52 52" src="https://user-images.githubusercontent.com/2662680/87854429-3b514e80-c912-11ea-8483-c34232d69e9a.png">

**Comment by ericpitcher** [comment]
@sokra @evilebottnawi any info on this, has it been fixed?

**Comment by alexander-akait** [comment]
bump, no

**Comment by sokra** [comment]
A snapshot type that only snapshots the directory structure instead of the whole content could help here. Bonus points if it allows filtering by regexp...

**Comment by ericpitcher** [comment]
Fyi, I've tested this in v5 and the performance problem is still there

**Comment by 7rulnik** [comment]
@sokra @alexander-akait sorry for the mention, but just discovered this bug in the storybook. It's a major blocker for webpack 5 adoption.

**Comment by sokra** [comment]
Could you please create new issue if this is still a problem?

This issue is about webpack 3...

**Comment by tmeasday** [comment]
@sokra this issue is very much alive in webpack5 and also affects dynamic `require()` and `import()` calls. I created another repro, although probably @ericpitcher's is just as good: https://github.com/tmeasday-shopify/webpack-require-context-repro

We are very interested about this for Storybook in large code bases because we rely on `require.context()` or some other globbing mechanism to import story files.

Would you like me to open a new ticket or can this ticket be reopened?

**Comment by tmeasday** [comment]
> require.context will watch the directory for changes. Changes to any file in the directory will rebuild the context module. Building the context basically means calling readdir. The modules in the context are watched and build separately

Assuming this is still true, I can see why it might cause the issue. I've experimented a little bit and if the changed file is outside of the `require.context()`'s "field of view", the rebuild times are better; but certainly still nowhere near as fast as if there is no `require.context()` (~500-1000ms rebuilds vs 10ms). 

Note this includes the case when the changed file does not affect the `require.context()` at all (not inside the context, nor imported by a file inside the context).
