### ISSUE TITLE
module.hot.accept how to use with define

### ISSUE THREAD

**Issue by geoshar** [webpack/webpack#6108]
I have something like:
```javascript
define([
    './core',
    './show/share',
    './show/topMenu'
], function(lib) {
    return lib;
});
```
I'm trying this
```javascript
define([
    './core',
    './show/share',
    './show/topMenu'
], function(lib) {
if(module.hot){
   module.hot.accept('./show/share', function(){
     lib.share();
    });
}
    return lib;
});
```
Nothing good happens, `share` is undefined, on the `./show/share` module, i have:
```javascript
define([
    '../core'
], function(lib) {
lib.prototype.share = function(){
alert('works');
}
return lib;
});
```

Is there a way to solve this, or just i should use `imports` and `exports` instead of `define`?

**Comment by sokra** [comment]
``` js
define([
    'require',
    './core',
    './show/share',
    './show/topMenu'
], function(require, lib) {
if(module.hot){
   module.hot.accept('./show/share', function(){
     require('./show/share');
     lib.share();
    });
}
    return lib;
});
```

> Is there a way to solve this, or just i should use imports and exports instead of define?

yes, please use import/export if possible. AMD is outdated.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
