### ISSUE TITLE
dynamic `import()` without creating a separate module

### ISSUE THREAD

**Issue by ccorcos** [webpack/webpack#6125]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Currently whenever you `import()` a module, it will create a separate chunk. 

**What is the expected behavior?**

Sometimes you just want lazily import the module, like you would with `require` back in the day.

**If this is a feature request, what is motivation or use case for changing the behavior?**

My application has an asynchronous initialization process and I want to lazily import the rest of the application once the initialization is complete.

**Comment by Wildhoney** [comment]
You could still use `require`.

The difference between the two is that the file `require`d will **only** be included in the build if it's used, which will increase the size of your build. There's not much asynchronicity happening because you still just have a single output file, and the user has to download the entire JS before execution begins.

With `import` &ndash; which is part of the official ECMA spec &ndash; we achieve true asynchronicity because your app bootstraps, and then chunk files are imported dynamically, thus you could defer that import until they're actually needed. Users download a small file which renders the app's skeleton, and then loads in the rest of the app.

To me it sounds like you do in fact want `import` because you mention asynchronicity. However, as `import` is part of the official spec, it wouldn't make sense to diverge from its intended behaviour. For that we could still use `require` which adheres to how the Node spec expects it to behave.

**Comment by sokra** [comment]
https://webpack.js.org/api/module-methods/#import-

see `webpackMode: "eager"`

**Comment by ccorcos** [comment]
Interesting -- so `require` is going to stick around?

**Comment by Wildhoney** [comment]
Yeh, I see no reason why it'd disappear from Webpack &ndash; `import` makes perfect sense for the browser environment as it's all about bytes over the wire, which we can defer until it's needed.

For Node, `require` makes sense as it gives us the modularity (in the same way `import` does) that we've come to expect from our programming languages. It just so happens that `require` also *sometimes* makes sense for the browser as well, where you can setup conditional builds &ndash; i.e, include *this* only when needed.

I don't have any experience with TS on the Node side, but [this Stackoverflow question](https://stackoverflow.com/questions/12742082/nodejs-require-inside-typescript-file) looks like it may be of some use 👍
