### ISSUE TITLE
execSync is not a function error

### ISSUE THREAD

**Issue by veerbala82** [webpack/webpack#6127]
Hi Folks,

I get the below error when i run "npm run dev" in my poweshell for compiling my web3 app.js file.

Uncaught TypeError: webpack_require(...).execSync is not a function

Following is my code:

var fs = require('fs');

var executeC = require('child_process').execSync('solc --bin --abi --optimize -o bin ./contracts/FoodSafe.sol');;

I have imported web3 and truffle contract in my js file.

**Comment by ericmdantas** [comment]
What's your node version?

**Comment by veerbala82** [comment]
v8.9.3

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
