### ISSUE TITLE
Content Security Policy error using webpack-dev-server

### ISSUE THREAD

**Issue by croraf** [webpack/webpack#6139]
I'm using:
```
"webpack": "^3.10.0",
"webpack-dev-server": "^2.9.7"
```

My webpack.config.js:
```
var path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    publicPath: "/assets/",
    filename: "bundle.js"
  },
  devServer: {
    contentBase: path.join(__dirname, "dist"),
    compress: true,
    port: 9002
  },
  module: {
    rules: [
      { test: /\.js$/, use: 'babel-loader' }
    ]
  }
};
```
My src/index.js contains
```
import ReactDOM from 'react-dom';
import React from 'react';

ReactDOM.render(
    <h1>Curve!</h1>,
    document.getElementById('root')
);
```

When I start webpack-dev-server and go to localhost:9002 I get the following error:
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src http://localhost:9002”). Source: ;(function installGlobalHook(window) {`

Why is that so?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by insin** [comment]
Note for future travellers, try configuring `historyApiFallback: {disableDotRule: true}` in your `devServer` config.

**Comment by SaroarShahan** [comment]
If you guys still face any problem of content security policy, no worries. Just [click here](https://stackoverflow.com/questions/46422290/webpack-dev-server-react-content-security-policy-error/54199426#54199426) to check my answer at StackOverflow. You don't have to use any meta tag. You will be able to fix it by webpack or cli command.
