### ISSUE TITLE
Prompt users to install webpack-cli on first usage

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#6157]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
Feature

**What is the expected behavior?**
When I "surface" the webpack cli bin command to my node scripts, I should be able to run webpack without any manual installation. 

As a user, when I run `webpack`  command line tool and webpack-cli is not installed, I should be informed that `webpack-cli` was not found inside of my project and prompt me to install it. 

In addition to this, webpack should detect if the user is using yarn/npm (package.lock or no .lock vs yarn.lock files) and use the appropriate installer.

When finished installing, webpack should build as expected.
If webpack-cli is already installed, webpack should build as expected.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Being able to allow users to seamlessly use webpack in the simplest manner (0CJS/CLI-only/etc) is a hot path for webpack usability. We need to be able to allow them to install webpack-cli on first run

**Comment by TheLarkInn** [comment]
https://github.com/webpack-contrib/npm-install-webpack-plugin/pull/115/files Maybe this PR is a somewhat okay example of how some of this could be accomplished

**Comment by sokra** [comment]
I guess there is somewhere a package for this on npm. I heard rumours that yeoman has some.

**Comment by grisanu** [comment]
Hi! I am interested in taking this issue but want to get some clarifications about it first.

I see that in the [v4.0.0-alpha.1](https://github.com/webpack/webpack/issues/6132) pre-release, there is a bullet point about moving the CLI to `webpack-cli` explicitly. I'm assuming that that is what this issue is about? 

That when a `webpack` command is 'surfaced' in `package.json` or something and the `webpack-cli` isn't yet installed. You want to prompts the user to install `webpack-cli`?

I'm probably missing something, but isn't hasn't `webpack-cli` been made a dependency to `webpack`? So shouldn't the installation of `webpack` either with `npm` or `yarn` also install `webpack-cli`? I've been trying to go through the commits, but can't find the ones about moving CLI to `webpack-cli`

Thank you!

**Comment by sokra** [comment]
it was intentional to makewebpack-cli not a dependency of webpack:

* Less depenencies when only using the node.js API
* Both projects can develop indiviually.
* Breaking changes for webpack-cli doesn't mean breaking change for webpack and in reverse.

Current you get a error message asking to install webpack-cli when using the CLI from webpack. This could be improved. Instead of an error webpack should ask the user if webpack-cli should be installed (if we find a yarn.lock or package-lock). No just aborts with an error, yes installs the webpack-cli and continues. Install should happen with saving as devDependency.

**Comment by random-forest** [comment]
In my opinion, I did it. What should I do next?

**Comment by sokra** [comment]
Send a PR.

**Comment by random-forest** [comment]
👍

**Comment by ev1stensberg** [comment]
@random-forest here's an example of how you can do it, using [`inquirer`](https://github.com/SBoudrias/Inquirer.js):

https://github.com/webpack/webpack-cli/blob/master/lib/commands/serve.js

**Comment by g0t4** [comment]
So, going forward will the typical end user be encouraged to `npm install webpack-cli` and no longer `npm install webpack`? 

Is that something we'll see in the docs? For example, would that end up in https://webpack.js.org/guides/installation/#local-installation?

**Comment by g0t4** [comment]
Also, how about keep `webpack` as the command name? That might cause less confusion. 

Separately, why extract the CLI to a new package versus the API to a new package? I'm not suggesting this, just curious to learn more about the thought process and maybe more about how to think about this re-organization.

**Comment by ev1stensberg** [comment]
@g0t4  CLI for CLI and webpack for node api.

**Comment by TheLarkInn** [comment]
Wes, I think the problem lies within the sheer amount of different
dependencies that the cli uses. Unfortunately we dont want to muddy all of
our users with a bunch of Babel and other dependencies for just webpack
alone (if let's say they are just using the node API).

This is crazy but, maybe we could create a webpack target for the cli that
publishes two packages. One with the base API cases, and the other with the
additional webpack-cli add-ons.

**Comment by ev1stensberg** [comment]
It's in the roadmap, CLI should be a buffer for the CLI and node API

**Comment by abiduzz420** [comment]
Hi, I'm looking for issues to contribute to webpack. I find this to be an interesting feature, I would like to work on this, if nobody is ?

**Comment by ev1stensberg** [comment]
I think maybe this already is implemented @abiduzz420. I can grab some other issues for your if you'd like!

**Comment by abiduzz420** [comment]
Yeah sure @ev1stensberg That would be great! :)

**Comment by ev1stensberg** [comment]
Could you do this? https://github.com/webpack/webpack-cli/issues/249

**Comment by abiduzz420** [comment]
Thanks @ev1stensberg for pointing out. I shall take it up :)

**Comment by ev1stensberg** [comment]
Awesome, send me a message if you need help :)

**Comment by TheLarkInn** [comment]
Hi there @abiduzz420, is there a PR already open for this? I'm tracking down all of our outstanding work for webpack 4 and want to get a status on this. 

AKA: This will block webpack 4, or we should move this to the webpack 4.x milestone since we have 20 days to release.

**Comment by abiduzz420** [comment]
No, not yet @TheLarkInn .I shall get it done soon.

**Comment by TheLarkInn** [comment]
No problem! Just tracking progress!

**Comment by PlayMa256** [comment]
It seems to have a pr already open for this feature #6222 which has conflicts, and nobody fixed those yet.

**Comment by ev1stensberg** [comment]
Ping the author, if he isn't responding, go ahead and implement it in your own. Wierd, cause I saw something similar like this at the next branch a while ago, if I recall right.

**Comment by PlayMa256** [comment]
Author pinged. I will have this done ASAP.

**Comment by PlayMa256** [comment]
Quick question: If you have `webpack-cli` installed in your machine, `require.resolve` works?
`require.resolve` was to work on any machine, but somehow here it does not.
I've linked my local `webpack` folder on a dummy project, and although it installs, add to my `package.json`, it still says that `webpack-cli` is not installed.

I just want to double check, instead of submitting a pr and it is a :poop:

**Comment by ev1stensberg** [comment]
Installing both the CLI and webpack is a nice practice

**Comment by PlayMa256** [comment]
Well, indeed, since `webpack-cli` will use `webpack` as an api and vice versa.  But i'm saying, require.resolve is more reliable to check if a package is installed than querying the `package.json` file, which is what happens [here](https://github.com/webpack/webpack/blob/next/bin/webpack.js#L5) already. This same clause is throwing an error, even if i already have `webpack-cli` installed. I just want to double check if this servers it pourposes, or any other implementation would still work.

**Comment by ev1stensberg** [comment]
Could you make a repro repository and I'll have a look @PlayMa256 ?

**Comment by PlayMa256** [comment]
@ev1stensberg download [this](https://github.com/PlayMa256/dummyProject) repo, and link your local `webpack` project inside of it. Than run `npm start` which will throw the error saying you don't have `webpack-cli`.
Install it manually, than run `npm start` again, it should throw the same error again.

Your `webpack/bin/webpack.js` should looks like [this](https://gist.github.com/PlayMa256/efb007cd17cd5954d49f1c52f44fd1ba).

The problem remains at line 20.
For what i tested and also found in the internet, `require.resolve` will try to find only on the root of where it's being execute. What i mean by that:
Dummy project has `webpack` as dependency and `webpack` has the binary which executes the `require.resolve` command.
Turns out that node will try to resolve the module, based on the `webpack` folder as a project root, not the dummy project.

**Comment by ev1stensberg** [comment]
Think the problem with your repro is that you don't have webpack installed as a devDependency. Either way, `require.resolve` will not look for the dependency, it will look for the actual file `webpack-cli`, so if you do something like `npm install webpack webpack-cli` it would still be validated correct. ( still with `npm link` )

If you feel like there's something wrong with that, I can help you setting this up, was hard to get anything out of your repro as it was basically a empty package.json without anything. 

This is what I got when linking etc, it works as expected: 

<img width="582" alt="skjermbilde 2018-02-09 kl 17 02 25" src="https://user-images.githubusercontent.com/16735925/36036918-7d3fed52-0dbb-11e8-8172-ab1661ae26ea.png">

**Comment by PlayMa256** [comment]
Thank you @ev1stensberg ! i misunderstood the linking part of npm!

**Comment by ev1stensberg** [comment]
No worries!

**Comment by sendilkumarn** [comment]
Just a curious question, why this needs `inquirer` can we do it with any other light weight library (if available) ?

**Comment by ev1stensberg** [comment]
Visually, it's looking better. Polymer is using inquirer too

**Comment by sendilkumarn** [comment]
I agree, but just out of curiousness, any lightweight library would be interesting to handle this.

**Comment by nveenjain** [comment]
Is this issue still open for PR??

**Comment by PlayMa256** [comment]
No, there is an open pr on that.

**Comment by ev1stensberg** [comment]
Not implemented, free for grabs

**Comment by nveenjain** [comment]
On it!

**Comment by malixsys** [comment]
@nveenjain see https://github.com/webpack/webpack/pull/6467
