### ISSUE TITLE
devServer config

### ISSUE THREAD

**Issue by geddski** [webpack/webpack#616]
Question: when you set the devServer to use a contentBase of "./build", the index.html is no longer served unless you create a copy of it in the `build/` directory. How can you make webpack-dev-server serve up the index.html pointing to /build/ for assets?

webpack config:
```js
devServer: {
    contentBase: './build'
}
```

html:
```html
<script src="build/entry.js"></script>
```

**Comment by mindjuice** [comment]
@geddski What did you end up doing about this?  I'm looking into the same issue.  I suppose copying it isn't the end of the world, but I'd like webpack to do it through config rather than me running a CLI command.

**Comment by Industrial** [comment]
I have a `src` dir. This contains all sources. Client side and server side (nodejs). Including the `src/client/index.html` and my entry file `src/client/js/app.js`, `src/client/styles/app.less`, etc.

I want all of this to be compiled to build, so that I get: `build/client/index.html`, `build/client/js/app.webpack.js`, `build/client/css/app.css`, etc.

Is this possible? I think webpack-dev-server should copy over all things that are not compiled and then serve it all from the build dir.

**Comment by bebraw** [comment]
[html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) might be a neat way to solve this if you don't mind the templating.

If the original question is still relevant, please re-open at Stack Overflow.
