### ISSUE TITLE
Misleading message on CaseSensitiveModulesWarning when the conflict involves folders

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#6175]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

```
WARNING in ./src/Foo.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* .../node_modules/babel-loader/lib/index.js??ref--14-0!.../node_modules/eslint-loader/index.js??ref--13!.../src/Foo.js
    Used by 1 module(s), i. e.
    .../node_modules/babel-loader/lib/index.js??ref--14-0!.../node_modules/eslint-loader/index.js??ref--13!.../src/index.js
* .../node_modules/babel-loader/lib/index.js??ref--14-0!.../node_modules/eslint-loader/index.js??ref--13!.../src/foo.js
    Used by 1 module(s), i. e.
    .../node_modules/babel-loader/lib/index.js??ref--14-0!.../node_modules/eslint-loader/index.js??ref--13!.../src/index.js
 @ ./src/Foo.js
 @ ./src/index.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- src/index.js
```js
import './foo'
import './Foo'
```

- src/foo.js
```js
export {}
```

- src/Foo/index.js
```js
export {}
```

**What is the expected behavior?**

The error message mentions a `Foo.js` file, but there is no `Foo.js`; it is `Foo/index.js`.

The error message could also be made more readable by printing the module ID without the loader string; e.g.' `./src/index.js` instead of `.../node_modules/babel-loader!.../node_modules/eslint-loader!.../src/index.js`.

**Comment by sokra** [comment]
> The error message mentions a Foo.js file, but there is no Foo.js; it is Foo/index.js.

There is a Foo.js file according to the filesystem. The filesystem is case-insensitive, that's why Foo.js and foo.js addresses the same file. That's the issue.

> The error message could also be made more readable by printing the module ID without the loader string; e.g.' ./src/index.js instead of .../node_modules/babel-loader!.../node_modules/eslint-loader!.../src/index.js.

The problem could be in the loader string too.

---

You can send a PR to improve this message:

* Omit the loader string if there is no diff here.
* Improve the error message to be more readable.
* ...

**Comment by Kovensky** [comment]
Oh, I see; the `Foo/index.js` is not being considered at all 🤔

**Comment by sokra** [comment]
Ah I see the folder. Yeah, it's not considered because it resolves successfully to `Foo.js` and files are preferred over folders. The behavior is probably different on a case-sensitive filesystem. That's why this warning is useful.

=> Don't name your folder case-insenstive-equal to your files. That doesn't work on case-insensitive filesystem. It may compile successfully on linux, but fails on OSX and Windows.
