### ISSUE TITLE
webpack2, webpack3, require module 

### ISSUE THREAD

**Issue by wuchuguang** [webpack/webpack#6188]
The require in webpack2 and webpack3?
in webpack2 ,i can use require('module') "export default " module
in webpack3,i can use require('module').default "export default" module

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
