### ISSUE TITLE
what's wrong??? cannot open the URL:'https://doc.webpack-china.org/guides/output-management/'

### ISSUE THREAD

**Issue by hello-guoguo** [webpack/webpack#6196]
### it's info:
```
无法访问此网站

网址为 https://doc.webpack-china.org/guides/output-management/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_SPDY_PROTOCOL_ERROR
```

## Have you ever met???

**Comment by EugeneHlushko** [comment]
Doesn't look like a bug but a question, try stackoverflow @hello-guoguo

**Comment by hello-guoguo** [comment]
@EugeneHlushko emmmmmm...

**Comment by EugeneHlushko** [comment]
The links work well for me so i suggest asking a question instead of opening an issue :|

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

--> https://github.com/webpack-china/webpack.js.org
