### ISSUE TITLE
The index html file is not being generated with HtmlWebpackPlugin in Linux

### ISSUE THREAD

**Issue by mgolshan-talentnet** [webpack/webpack#6211]
I have a react project and while building the project, this command runs:
```
new HtmlWebpackPlugin({
  inject: true,
  template: 'public/index.html',
  minify: {
    removeComments: true,
    collapseWhitespace: true,
    removeRedundantAttributes: true,
    useShortDoctype: true,
    removeEmptyAttributes: true,
    removeStyleLinkTypeAttributes: true,
    keepClosingSlash: true,
    minifyJS: true,
    minifyCSS: true,
    minifyURLs: true
  },
  filename: '/index.' + Date.now() + '.html'
}),
```

When I build the project in Windows, it generates the fingerprinted index file like `index.1514560078687.html` inside the folder `build` along with other assets and files.
But, when I run it in Ubuntu, it generates all files but the index file. Even if I set `filename: '/index.html'`, it won't be generated.

Any idea?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by mgolshan-talentnet** [comment]
OK.
Sure.
Sorry about that
