### ISSUE TITLE
how to visit local webpack-dev-server through LAN

### ISSUE THREAD

**Issue by NameNull** [webpack/webpack#6237]
I add the host 0.0.0.0 to the options of devServer, but I can only visit the file 192.168.0.149:8080 in through local access, but not LAN, why?

**Comment by NameNull** [comment]
i defined the port 887

**Comment by NameNull** [comment]
![image](https://user-images.githubusercontent.com/11754843/34554983-7277fec2-f16a-11e7-9d03-88b659b14452.png)

**Comment by NameNull** [comment]
![image](https://user-images.githubusercontent.com/11754843/34555015-99940f3c-f16a-11e7-8dd1-e277d1cdb6f0.png)

**Comment by NameNull** [comment]
![image](https://user-images.githubusercontent.com/11754843/34555104-0dff0f02-f16b-11e7-86aa-66ca888e2d23.png)

B computer

**Comment by NameNull** [comment]
A and B is in the same LAN

**Comment by NameNull** [comment]
![image](https://user-images.githubusercontent.com/11754843/34555168-537517a2-f16b-11e7-9111-3ddd0f23889f.png)
![image](https://user-images.githubusercontent.com/11754843/34555178-5d24efb6-f16b-11e7-99d2-b965fab9bb76.png)

and my config is here

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
