### ISSUE TITLE
Syntax Error: Unexpected token  for async generator 

### ISSUE THREAD

**Issue by githoniel** [webpack/webpack#6247]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
async function* gen() {
    yield 'hello';
}
```
with babelrc
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["last 2 Chrome versions"]
      }
    }]
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"]
}
```
error with
```
Syntax Error: Unexpected token (16:9)

  14 |
  15 | class c {
> 16 |     async* test() {
```
If I use babel-stage2 to transform async/await and generator. It works well.
But I don't need it, I just want to use native async generator

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/githoniel/async-generator-bug-demo
a vue-cli project, change babelrc and add async generator only

**What is the expected behavior?**
support async generator. It is support in Chrome@Latest

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
win10 10.0.16299.125
node v8.9.3
webpack 3.6.0
babel-core 6.22.1
babel-loader 7.1.1

**Comment by ooflorent** [comment]
That's the expected behavior. Async generators are not part of ECMAScript specification, yet, see https://github.com/tc39/proposal-async-iteration for more information. Webpack uses an ES2017 compliant parser and adds support for dynamic imports. That's the only supported feature that is not included in the spec. For others, please use a transpiler.

> It is support in Chrome@Latest

This does not mean that Webpack have to support it. Feel free to reopen the issue once it has reach stage 4.

**Comment by trusktr** [comment]
I'm getting this same error with just `async function`. I'm on Webpack `3.10`. How can I make it not crash on `async function` syntax?

**Comment by trusktr** [comment]
Ah, [MatAtBread/webpack-async-await](https://github.com/MatAtBread/webpack-async-await) does the trick.
