### ISSUE TITLE
Watcher doesn't see a new file until restart

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#6262]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Consider this project:

`package.json`

```json
{
  "scripts": {
    "start": "webpack --watch src/index.js dist/bundle.js"
  },
  "devDependencies": {
    "webpack": "^3.10.0"
  }
}
```

`src/index.js`

```js
import x from './x';
alert(x);
```

`src/x.js`

```js
export default 42;
```

Then do this series of steps:

1. Run `npm install`.
1. Run `npm start`.
1. Delete `src/x.js`.
1. Create `src/x` folder.
1. Create `src/x/index.js` with same content as `src/x.js` used to have.

**What is the expected behavior?**

Webpack recovers from a "not found" error. At the very least after re-saving either `src/index.js` or `src/x/index.js`.

Actual behavior is that Webpack gets stuck insisting `./x` is not found, and the only way to fix it is by restarting the watcher.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS X Sierra, Node 8.9.1 (but it's an old issue, existed at least since 2016 https://github.com/facebookincubator/create-react-app/issues/1164).

I couldn't figure out how to correctly set up Webpack beta so I didn't test that.

**Comment by sokra** [comment]
This is caused by the "unsafe" resolver cache. You can disable the cache with `resolve.unsafeCache: false` but this has very negative impact on performance.

**Comment by gaearon** [comment]
Is there any middle ground or a heuristic we could use? For example, if a file is not found, then invalidate any cache entries around it on any FS event.

**Comment by bpartridge** [comment]
This seems to be the same root issue as #5523, and we're running into it as well when gradually refactoring a codebase (in our case, the watcher starts reporting ENOENT when you rename x.js to x.ts or similar).

It seems that this is where the cache entry is saved (in the line above, `resolve.unsafeCache` is what determines the `cachePredicate`): https://github.com/webpack/webpack/blob/f352436a0fd6491b8cc1aadeddfbe02c878686ff/lib/NormalModuleFactory.js#L240

And the cache entry is read here: https://github.com/webpack/webpack/blob/f352436a0fd6491b8cc1aadeddfbe02c878686ff/lib/NormalModuleFactory.js#L215

Perhaps one way to achieve this with a minimal performance overhead would be to have a synchronous plugin tap immediately after a cache entry is read or created? Then a new plugin, only enabled during dev (and perhaps enabled by default?), could then:

- run an asynchronous NodeFileWatcher
- maintain a weak trie of the cache entries
- mark parts of that trie as invalidated when a filesystem change is detected
- quickly check the trie synchronously before returning a module from cache

This way you wouldn't need to completely turn off the caching, and overhead would be minimal - no need to go out to every resolver out there. And once the API hooks are inserted, the proposed plugin could be developed in a separate repository to meet all these edge cases, so that ongoing webpack core development isn't affected.

Am I missing anything here? Any reason not to try this approach?

**Comment by rhys-vdw** [comment]
Also suffering from this issue at present while slowly migrating from JS to TS. Branch changes are particularly annoying as they nearly always involve renames. I tried to `unsafeCache: false` and it didn't appear to work (although I'm not sure if this might be a symptom of other plugins or configuration).

**Comment by wujashek** [comment]
Actually after spending few hours on this, I'm quite sure unsafeCache option is actually not in resolve but in modules section of configuration.

At least for v3.x,

```
class NormalModuleFactory extends Tapable {
	constructor(context, resolvers, options) {
		super();
		this.resolvers = resolvers;
		this.ruleSet = new RuleSet(options.rules || options.loaders);
		this.cachePredicate = typeof options.unsafeCache === "function" ? options.unsafeCache : Boolean.bind(null, options.unsafeCache);`
```

And it can be actually a function and then it is a predicate.
Maybe I'm not aware of sth, otherwise it's quite a mess.

**Comment by Lukortech** [comment]
I am going to hop on the train and mention it really slows down my developement since no changes detected causes the need to restart and open new server for my react-app each time I run into this.

**Comment by sokra** [comment]
webpack 5 has this problem fixed

**Comment by minimit** [comment]
In webpack 5 it's not fixed when using multiple aliases #10015

**Comment by raminrez** [comment]
@gaearon  @minimit we have the same issue when using multiple aliases

**Comment by minimit** [comment]
> @gaearon @minimit we have the same issue when using multiple aliases

it's getting worked on webpack 5 https://github.com/webpack/webpack/issues/9802#issuecomment-563159161

**Comment by vankop** [comment]
Should work with `webpack@next`. Feel free to report new issue with reproducible repo.
