### ISSUE TITLE
Sharing a webpack bundle

### ISSUE THREAD

**Issue by jasonmcaffee** [webpack/webpack#628]
Hello, I'm trying to find a way to share a webpack bundle with another project.
In my webpack bundle I have moduleA and moduleB, and I would like to reference those modules inside of another webpack project.
e.g. 
Project 1:
  -> module A
  -> module B
Project 2:
  -> module C require('Project 1/module A', 'Project 1/module B')

I've done some searching and can't seem to find an example of this. (I've seen examples using the CommonChunksPlugin, but that only seems to work if both projects are built in the same process, and that is not the desired behavior)

Thanks

**Comment by coderitual** [comment]
Jason, I understand your need because I have the same problem. It would be nice to treat webpack bundle like it was external library in other languages (eg. dll). I have many webpack projects and sometimes want to use some bundled ones like i have sources in my current dir.

I think we need something like external bundle option (and then we could add these bundles to html scripts or select to bundle it in our current project).

**Comment by snowmantw** [comment]
So...does this means we need to put libraries as source directories, rather than packed files to be included? For example, if I have a library in ES6 module format:

    lib/foo.js:
    export function Foo() { /*...*/ }

And I want to use this `lib` in `app`. From the answers above, I couldn't `import` such module as:

    app/main.js
    import { Foo } from 'path/to/lib-packed.js/foo.js'

(note another issue is `/foo.js` would be a path within the packed file rather than indicating to a real path like `path/to/lib-packed.js`)
Rather that, I need to copy the whole directory of `lib` and import it as:

    app/main.js
    import { Foo } from 'path/to/lib-directory/foo.js'

And then to webpack whole `app` as the final package, instead of have packaged libraries within a packed app, unless I use them as AMD/CommonJS/Whatever "old school" loader:

    app/main.js
    require('Foo', 'path/to/lib-packed-as-library')

And maybe add some `r.js` tricks, right?

**Comment by coderitual** [comment]
Right.

**Comment by sokra** [comment]
> It would be nice to treat webpack bundle like it was external library in other languages (eg. dll).

@coderitual There is a `DllPlugin` which creates a bundle which behaves like a dynamic linked library. Another bundle can import it with the `DllReferencePlugin`. All used "dll"s need to be added as `<script>` tag. See [dll](https://github.com/webpack/webpack/tree/master/examples/dll) and [dll-user](https://github.com/webpack/webpack/tree/master/examples/dll-user) examples.

This has negative impact on loading performance (more requests) and positive impact on caching (app can change independend from dll).

The normal user don't want this. You want a single bundle.

**Comment by coderitual** [comment]
@sokra Thanks! Now I'm mostly using full sources of other local packages (symlinks in node_modules) but I'll check this plugin.

**Comment by bebraw** [comment]
@jasonmcaffee Safe to close?

**Comment by moo3** [comment]
> There is a DllPlugin which creates a bundle which behaves like a dynamic linked library. 

I have a similar scenario but the bundle is created by non-webpack bundlers (r.js). Does that mean webpack cannot read r.js built bundles and when there are multiple define blocks in a file they will not exposed to be required from other files?
