### ISSUE TITLE
npm run build  can't pack,but no error

### ISSUE THREAD

**Issue by Kemper-Diao** [webpack/webpack#6282]
My project is build by vue-cli+webpack . when I use 'npm run build'  to pack the project ,Terminal always show  'building for production...'. but no error. what's the problem . how to  resolve......

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
