### ISSUE TITLE
The module name about import/require in the folder of node_modules will be replaced with resolve.alias

### ISSUE THREAD

**Issue by keshidong** [webpack/webpack#6293]
Whether the webpack can limit the scope of resolve.alias. let it work on some folder or not work on some folder.

Now, resolve.alias also replace the module name even the code at the node_modules folder. It not reasonable. Because of the complexity of module dependency, we can't control the module name not conflict with resolve.alias. So if limit the scope of resolve.alias, some problems may be avoided.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
