### ISSUE TITLE
Add an option to throw an error when a circular dependency occurs

### ISSUE THREAD

**Issue by adamziel** [webpack/webpack#631]
Right now it's rather hard to track errors caused by circular dependencies - you need to check why exactly this variable in that file is an empty object at a given point of time.

**Comment by joshma** [comment]
@sokra would you say circular top-level dependencies are wrong? It's hard to see how returning an empty object is ever desired behavior - we were surprised to find that today.

**Comment by jhnns** [comment]
The object is not empty, it's just not initialized at this point. It's a reference to the `exports` object. It will be a problem if you overwrite `module.exports` or if you try to save references from the `exports` object, like say `var someProperty = require("some-module").someProperty`.

Imho that's the best way to handle circular dependencies. The only alternative I know would be an error...

**Comment by AZielinski** [comment]
An error would not be bad if it could be turned on/off in config file

**Comment by joshma** [comment]
Yeah, I realized later that this is following node convention, which has the `module.exports` issue brought up above. That seems reasonable to me, but an error would definitely be nice.

**Comment by steida** [comment]
Just spend 6 hours chasing a weird bug caused by circular dependency. Innocent import

```
import {firebase, promisify, firebaseValidationError, set} from '../firebase'
```

everything was resolved except firebase, which is exported as const

```
export const firebase = new Firebase(firebaseCursor().get('url'))
```

So functions were resolved and variables not. I probably understand why, but for love of god, please add some warning at least.

**Comment by jatwork** [comment]
"would you say circular top-level dependencies are wrong? It's hard to see how returning an empty object is ever desired behavior." +1 on this.

**Comment by jonrh** [comment]
Same thing happened to me, about 6 hours spent realizing I was doing circular dependencies. A warning would have been nice. Or maybe populating the object with some warning string as a hint, instead of having it be empty. I'm genuinely curios to see examples of circular dependencies in code that are fine and do not cause this issue.

**Comment by adamziel** [comment]
Symfony2 (A PHP framework) introduced a great concept of so called "Developer Experience" - basically a User Experience of using library: http://symfony.com/blog/making-the-symfony-experience-exceptional

This issue is an example of terrible developer experience - see comments above, almost everyone (including me) wasted many hours on tracking this thing. Sending a PR was already suggested, but I believe this is rather something that a core team should be concerned with.

**Comment by gmethvin** [comment]
Even without true circular dependency detection, it'd be nice if there was a way to validate in a dev environment that all the imported variables are defined. Something like
```javascript
import {foo, bar} from './foobar';
```
should throw an error like `imported value 'foo' is not defined` to make it clear there is an import issue.

**Comment by vitalets** [comment]
+1 for warning for circular dependencies! Spend a lot of time on debugging...

**Comment by vitalets** [comment]
Dealing with cyclic dependencies I found this tool that can analyze code and throw warnings:
https://github.com/pahen/madge

grunt plugin
https://github.com/pahen/grunt-madge

hope this helps

**Comment by jatwork** [comment]
For those who've been struggle with, ES6 module has completely solves this problem by export **bindings**. Please check this article out:
http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by ykka** [comment]
+1

**Comment by trusktr** [comment]
I believe I might be having this problem with an ES2015 module. What should be happening during the import of a circular dependency?

I basically have this:

1. module A imports module B
1. module A stores ref to module B to use later, at run time, by some other module that imports A.
1. module B imports module A, and needs to use the ref to module A in the module code itself in order to define some export B, during the runtime of the module itself (not the runtime of anything that it exports).

Should that work?

A guess a good question might be: which module gets evaluated first? Can I control that order? Is it a matter of which of the two modules gets imported-for-the-first-time first?

**Comment by trusktr** [comment]
In case someone with curcular dependency problems stumbles here, this is what solved my problem:

First, here are the modules in their original form that was giving me the problem of A being undefined (`{}`) in module B:

```js
// A.js
import B from './B'

const A = new window.SomeClass
export default A

// modify A here. Add properties, etc.
```

```js
// B.js
import A from './A'

const B = window.something // a global
export default B

// modify B here. Add properties, etc.
```

```js
// main.js
import A from './A'
import B from './B'

// importing A and B caused an error (inside of A or B code) because module A in an empty object (`{}`)
```

I modified both modules so export setup functions, then I call those functions in the main file, so now it all works, and A is no longer an empty object:

```js
// A.js
import B from './B'

const A = new window.SomeClass
export default A

export function setupA() {
  // modify A here. Add properties, etc.
}
```

```js
// B.js
import A from './A'

const B = window.something // a global
export default B

export function setupB() {
  // modify B here. Add properties, etc.
}
```

```js
// main.js
import A, {setupA} from './A'
import B, {setupB} from './B'

setupA()
setupB()

// No more error!
```

 After things have been imported into main.js, A is no longer undefined, and we can thus run the setup functions for each module that depend on each other. 

Is there a bug here in the way Webpack is handling the circular dependency?

**Comment by moshemal** [comment]
+1 for warning when a circular dependency exist

**Comment by SPSpwetter** [comment]
There's a plugin for this: circular-dependency-plugin.

**Comment by sokra** [comment]
https://github.com/aackerman/circular-dependency-plugin

**Comment by ericgundrum** [comment]
Being able to add a plugin to find the error is better than manually tracing the code. But, choosing to add the plugin presumes that I know my app is failing because of a dependency cycle. 

Many users may not recognize this failure condition (an empty object) represents a possible dependency cycle. A webpack warning would be very helpful -- even buried deep in verbose output.

**Comment by wpcarro** [comment]
I agree with @ericgundrum and I believe that circular dependency warning should exist and should even be an opt-out behavior. I think this would meet most developers' expectations.
