### ISSUE TITLE
Is there something like rollup-plugin-commonjs for Webpack?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#6311]
I'm curious to know: is there something like `rollup-plugin-commonjs` (which converts CommonJS modules to ES6 Modules so that tree-shaking can be done) for Webpack?

**Comment by sokra** [comment]
https://github.com/indutny/webpack-common-shake

It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
