### ISSUE TITLE
The problem of resource compilation

### ISSUE THREAD

**Issue by afuno** [webpack/webpack#6348]
Guys, here there was a problem of expansion of Rails application which uses Webpacker 3.2 (or 3.2.1).

The main discussion was conducted here: https://github.com/rails/webpacker/issues/1168

The problem seems to be that node does not have enough RAM. But on the server 4 Gb of RAM. And when deploying, node does not consume more than 12% of the RAM of the server.

I any more do not know as to be. Projects are not deployed. No one understands until the end what happens.

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
