### ISSUE TITLE
Partial builds are super slow for a Vue starter project with webpack 3.6.0

### ISSUE THREAD

**Issue by sandorTuranszky** [webpack/webpack#6361]
I have "webpack": "^3.6.0", & "extract-text-webpack-plugin": "^3.0.0", and partial builds are super slow for a Vue starter project.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by sandorTuranszky** [comment]
@sokra I see a lot of sense in your issue template. But my case is dead simple to reproduce - I simply installed the official (sorry, forgot to mention it) Vue starter project and it takes 15 sec to partially reload.
