### ISSUE TITLE
Forcing a specific shared module to go into it's own chunk

### ISSUE THREAD

**Issue by KidkArolis** [webpack/webpack#640]
Imagine a SPA with one entry chunk and 10 pages. 3 of those pages use highcharts and highcharts is quite hefty. 

I don't want to put it into entry chunk to not slow down the initial page load and it's only needed in 3 pages anyway.
I don't want to put it into each of those 3 page chunks since it weighs them all down.

I want to force highcharts into it's own chunk, independently of how other chunks are created and merged, moved to parent, etc. I want this highcharts chunk to only be loaded if one of those 3 pages is loaded.

I can achieve that in r.js with modules/include/exclude config. I was wondering if there's a way to achieve this in webpack.

The only thing I could think of (while typing this issue) is to try and put a `require.ensure(["highcharts"])` into the entry chunk and hope that highcharts will end up into it's own chunk and won't be bundled together with other chunks. I'll try that now and see if it works.

Finally, I imagine a plugin could be written where you could say something like `new ForceChunk(["highcharts"])`, but was wondering if there's already a way to achieve this. Also, not sure if this plugin is possible without converting `require("highcharts")` calls into async calls in those 3 pages.

**Comment by sokra** [comment]
You can now use the CommonsChunkPlugin to create an additional chunks that is loaded in parallel to the normal additional chunks.

https://github.com/webpack/webpack/tree/master/examples/extra-async-chunk

**Comment by KidkArolis** [comment]
Amazing!

**Comment by vladar** [comment]
I also ended up with several async CommonsChunkPlugins, but since it is an optimization step it seems to affect performance of incremental builds.

It is actually conceptual problem, because currently webpack is a bit too smart about what goes where for async chunks. Sometimes developers just know their system better (like in the subject post), but right now there are no simple and documented ways to configure async bundles (preferably on build step, not optimization one).

The most common use case is indeed extracting big libraries to their own chunk. I also have like 3 big libraries that are occasionally required, but I really don't want them to be in commons chunk, because they are used on 5% of pages at most.

If only we could write config like this:

```
{
    entry: './main',
    bundles: [
        {entry: 'my/custom/module1', chunkFilename: 'chunk1.js'},
        {entry: 'my/custom/module2', exclude: 'my/custom/module1', chunkFilename: 'chunk2.js'}
    ]
}
```

It would make dealing with big code bases so much easier. My main concern with approach using multiple CommonsChunkPlugins is performance - it made incremental builds significantly slower for us.

**Comment by megapctr** [comment]
Was there any progress on this issue? My use case is that translations are packed into the commons file, so I won't benefit from caching if either of these is updated.

I don't know how the plugin works internally, but it doesn't seem difficult to add an `exclude` option
