### ISSUE TITLE
Source maps with newer Chrome DevTools' workspaces

### ISSUE THREAD

**Issue by ruszki** [webpack/webpack#6400]
**Do you want to request a *feature* or report a *bug*?**
Feature, but also a bug in a sense.

**What is the current behavior?**
Source map plugins inject three new lines and a footer template into every source map objects. This behavior not works well with Chrome DevTools' new workspaces 2.0 API.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use any kind of source map, and try to modify files through DevTools.

DevTools expects that the original source code is the same as the code in source map. With current behavior this isn't the case.

**What is the expected behavior?**
Remove the modifications of code in source maps, or, at least, have an option to alter this behavior.

**If this is a feature request, what is motivation or use case for changing the behavior?**
To be able to use DevTools' Workspaces to modify source codes from Chrome itself.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack version: 3.10.0

An example for the problematic code in Webpack: [SourceMapDevToolPlugin.js#L188](https://github.com/webpack/webpack/blob/c963e3db54adef8e1e3aea4383e09fa472131106/lib/SourceMapDevToolPlugin.js#L188)

ModuleFilenameHelpers::createFooter function can be rewritten, but the three new line characters are injected regardless.

**Comment by simonbuchan** [comment]
In my testing, workspaces works fine so long as:
- `moduleFilenameTemplate` (`output.devtoolModuleFilenameTemplate` for devtool) maps the resource to an absolute `file:` URI, including using `/` on windows.
- `module` is enabled (default for plugins, or use one of the `module-` devtool values), otherwise the source only maps to the transpiler output, which is pretty useless.
- `columns` is enabled (default for plugins, or do *not* use one of the `cheap-` devtool values), otherwise there seems to be two bugs (which seems to be this issue):
    - `moduleFilenameTemplate` is invoked, but the result path is not used: the default `webpack:///[resource-path]` is encoded!?
    - the mapped file shows the footer

In particular, any of the following `devtool`s work:
- `module-source-map`
- `eval-module-source-map`
- `inline-module-source-map`

with:

```
output: {
  devtoolModuleFilenameTemplate(info) {
    return `file:///${info.absoluteResourcePath.replace(/\\/g, '/')}`;
  },
},
```

**Comment by ruszki** [comment]
Replacing backslashes in absolute resource paths solves file recognition in Chrome on Windows. It seems that Chrome display the file itself in that case, and it uses only some metadata from source maps. Debugging is broken in a very strange way in my case, but that's Chrome's problem.

When footer is removed, setting devtoolModuleFilenameTemplate is not required, and even debugging seems ok.

**Comment by simonbuchan** [comment]
Interesting about it matching by content if it doesn't recognize the path - how does it know how to save changes back? It might explain why my devtools deadlocks when I first open it for ~15s - I have my `C:\code` directory added as a workspace root 😱

I don't see debugging issues either with the known good types above - not sure what's going on there?

**Comment by simonbuchan** [comment]
Hmm, with more experimentation, I'm going to retract recommending `eval-module-source-map`, it seems to miss several modules (in my case, the entry point and the CSS files!?). But yeah, no problems with debugging or mapping files with `module-source-map`.

I'm using the babel 7 beta, could that be the difference?

**Comment by rafde** [comment]
I had the best experience with `inline-source-map` since it adds the source map to the bundle. Sadly, the size of the bundle increases a lot.

**Comment by simonbuchan** [comment]
Without `module`, you will be debugging the post-loader-transform code, if you are using any, so you probably want `inline-module-source-map`.
The filename template is required not to name the map on disk, it's what the name is *in the source map* - workspaces needs this to find the file on disk so you can save changes back (which, when you have it working, is surprisingly nice)

**Comment by strobox** [comment]
Also have problem with css-loader source maps. Temporary solution was "dirty" edition of source code of css-loader and adding `file:///` prfix

**Comment by RyanAtViceSoftware** [comment]
Any updates on this? I've tried everything in this thread and since Chrome updated to 63+ I haven't been able to get workspaces to work. Trying all the various devtool settings still results in souremaps not being established as shown below.

![image](https://user-images.githubusercontent.com/10080111/37154151-b607ac4e-22a4-11e8-8cb4-25875ec46253.png)

I'm using a ejected `create-react-app` config.

**Comment by simonbuchan** [comment]
From the description, that link looks it's for [local overrides](https://developers.google.com/web/updates/2018/01/devtools#overrides) (added in chrome 65).

You should simply need to drop your project directory (or higher up) on the devtools (once, ever) to give devtools access to write to it, and it will happen automatically - which you obviously have, since it's showing up in the Sources -> Filesystem tab.

Check that the Sources -> Network tab includes `file://` -> `C:/path/to/my/project/src` -> all the project source files, (taken from the source map). Those names are from the `output.devtoolModuleFilenameTemplate` / `SourceMapDevToolPlugin({ moduleFilenameTemplate })` - which the default `create-react-app` should configure correctly for development.

In production builds, CRA uses a relative path, which won't work in Chrome Workspaces by default, due to the issue described here.

**Comment by RyanAtViceSoftware** [comment]
Thanks for the details but I've checked out the things you recommended and still can't get it working. This is what the network path looks like. I'm not seeing `file://` but I am seeing the local path embedded in the url.

![image](https://user-images.githubusercontent.com/10080111/37212390-97c54b4e-2374-11e8-9108-646696ca3cd3.png)

This is the webpack code related to what you mentioned

```
    publicPath: publicPath,
    // Point sourcemap entries to original disk location (format as URL on Windows)
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
```

Anything else I can try?

**Comment by simonbuchan** [comment]
Strange, it's missing the `file:///` prefix, and it shouldn't need the resolve (absolute-resource-path is already absolute if it makes sense) - I was sure I picked up those tricks from CRA but it looks like it's been doing it that way for forever.

Just adding the file prefix there should fix it.

**Comment by RyanAtViceSoftware** [comment]
@simonbuchan that fixed it, thanks so much. Can you explain a bit of background on how that works?

For anyone else here's the code that fixed it in a create-react-app based app.

```
    devtoolModuleFilenameTemplate: info =>
      'file:///' + path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
```

After making that change this is what I see in the debug tools

![image](https://user-images.githubusercontent.com/10080111/37349297-15cec286-26a4-11e8-8969-631cb219a618.png)

**Comment by simonbuchan** [comment]
> Can you explain a bit of background on how that works?

Basically, chrome has two ways of mapping a source map source to a file on disk: match the content or match the path. Because the content doesn't match with the added webpack footer (or because you're not using `devtool: "module-*"` so it has the transpiled source), chrome has to match by the path, and since it doesn't have path mappings any more you have to give it the full path. Since source maps paths are actually URLs, this means you need the `file:///` prefix so it knows you aren't (for some reason) talking about `https://localhost:8080/C:/projects/my-project/src/file.js`.

So yeah, it would be nice if we got one of:
- webpack drops the footer in the source map so it matches (as described in OP), or
- webpack makes the default `moduleFilenameTemplate`  work with chrome workspaces, or
- chrome workspaces gets better at mapping paths.

**Comment by ctwhome** [comment]
thank you for keeping posting about it. I tried absolutely everything, and nothing. I am working on Mac, and a custom Webpack config ,not from create-react-app.

If anyone is desperate as well it can be run with chromium Version 62.0.3202.94 (Developer Build) (64-bit), and old version of chrome, it is working without any problem.

**Comment by RyanAtViceSoftware** [comment]
@ctwhome thanks for sharing your notes too. I was trying to setup it up on mac this time and got stuck again but your tip worked like a charm. It's working for me with `eval-source-map` which provides the benefits described below from the webpack documentation

> eval-source-map - Each module is executed with eval() and a SourceMap is added as a DataUrl to the eval(). Initially it is slow, but it provides fast rebuild speed and yields real files. Line numbers are correctly mapped since it gets mapped to the original code. It yields the best quality SourceMaps for development.

**Comment by jakeNiemiec** [comment]
For chrome "workspaces", you need to set [`devtoolModuleFilenameTemplate`](https://webpack.js.org/configuration/output/#output-devtoolmodulefilenametemplate).

```javascript
devtoolModuleFilenameTemplate: (info) => 'file://' + path.resolve(info.absoluteResourcePath)
```

**Comment by yehudahkay** [comment]
Using webpack I can generate sourcemaps that chrome recognizes, however I am only able to edit the scss in the sources panel and then cntl+s for save. Scss changes I make in the element styles panel do not persist to disk. Does anyone know if this is the correct behavior for chrome?

**Comment by bkarlson** [comment]
@yehudahkay, scss live editing was removed from Chrome unfortunatelly

https://bugs.chromium.org/p/chromium/issues/detail?id=996226&q=scss&can=2

**Comment by tettoffensive** [comment]
What is the current status of how to debug properly? I'm finding a lot of various github issues from  as far back as 2016. I'm using VSCode and Chrome 81.0.4044.129, but I can't seem to get debugging working correctly with my Nuxt.js application. They recommend using `'source-map'`.

I don't see any of the options recommended at the start of this thread even being an option for webpack devtool here: https://webpack.js.org/configuration/devtool/

**Comment by simonbuchan** [comment]
@tettoffensive they all seem to be there for me? Don't get confused between talking about the devtool *plugin* options like `module` and `columns`, and the devtool *option* values like `cheap-module-source-map`, which adds a plugin with those options.

You will certainly want to at least use one of the `module-` devtool values if you are using any source module transformations like typescript, otherwise you are debugging the output of those transformations. After that there's a variety of things that could be going wrong depending on your situation, and it's not very realistic to debug them in an old issue thread. For these issues I've generally used the old standard method of working up from a simple, working example to the broken setup, to see where it starts going wrong, but at that point things can sometimes get tricky and you might need to start digging to find out what's happening.

**Comment by tettoffensive** [comment]
@simonbuchan Thanks, I wasn't aware there were two different devtools. I'm not 100% sure, but it looks like Nuxt.js uses [vue-devtools](https://github.com/vuejs/vue-devtools) which uses the ***option*** and not the *plugin*.

I'll do as you suggested and debug from a simple example. I don't mean to debug from an old thread, but it's hard to find a centralized source of truth. This one had the most recent activity of what I've found.

**Comment by simonbuchan** [comment]
Well there aren't really two... `devtool: "module-source-map"` is a shorthand equivalent to something like `plugins: [new SourceMapDevToolPlugin({ module: true })]` (hence the warning to only use one in the docs, otherwise it gets applied twice!), likewise for the other values for `devtool`.

And I just wanted to make clear that with this there's enough things that could be going wrong it's implausible that  you're going to get a nice simple "you're doing this wrong" without basically asking someone to do debugging on your project source code, which is probably a bit much to ask of random strangers 😉

**Comment by nfarina** [comment]
> ```
> ...
>   output: {
>     devtoolModuleFilenameTemplate: info =>
>       'file://' + path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
>   },
> ```

_Thank you_ @ctwhome for sharing this - this finally allowed me to output paths to my _actual source files_ in Webpack's source maps, which magically enabled Chrome DevTools (after granting permissions via Workspaces) _and_ VSCode's built-in debugger to work for me - for the first time ever!

**Comment by kyran15** [comment]
> Interesting about it matching by content if it doesn't recognize the path - how does it know how to save changes back? It might explain why my devtools deadlocks when I first open it for ~15s - I have my `C:\code` directory added as a workspace root 😱
> 
> I don't see debugging issues either with the known good types above - not sure what's going on there?





https://csser.space/questions/uncovering-inline-styles-infused-with-javascript-for-effective-debugging-of-javascript-code
