### ISSUE TITLE
npm install webpack error 

### ISSUE THREAD

**Issue by tusharthe** [webpack/webpack#6401]
PS C:\Program Files\nodejs\node_modules\npm> npm i webpack --save
npm ERR! Unexpected end of JSON input while parsing near '...d-resolve":"0.5.x","c'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tkpar\AppData\Roaming\npm-cache\_logs\2018-01-28T06_06_30_062Z-debug.log
PS C:\Program Files\nodejs\node_modules\npm>

[2018-01-28T06_08_13_605Z-debug.log](https://github.com/webpack/webpack/files/1670811/2018-01-28T06_08_13_605Z-debug.log)
![capture](https://user-images.githubusercontent.com/20502003/35479537-036ac46a-0420-11e8-8762-bf30f69f0655.PNG)

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
