### ISSUE TITLE
Error: You did not specify any valid target chunk settings.

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#6403]
From here https://webpack.js.org/plugins/commons-chunk-plugin/
> name: string, // or 
> names: string[] 
> // If omitted and `options.async` or `options.children` is set all chunks are used, otherwise `options.filename` is used as chunk name.

Config
```
entry: './index.js',
output: {
    filename: '[name].js',
    path: path.resolve(__dirname, '..', 'public'),
    publicPath: '/',
    pathinfo: true, 
},
new webpack.optimize.CommonsChunkPlugin({
    chunks: ['react', 'react-router-dom', 'react-dom'],
    filename: "vendors.js",
}),
```

Why error?

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
