### ISSUE TITLE
The case for Workers

### ISSUE THREAD

**Issue by surma** [webpack/webpack#6472]
**Do you want to request a *feature* or report a *bug*?**

Feature! 🎉 

**What is the current behavior?**

(This is gonna be a bit longer.)

Let’s imagine working on a project using [WebWorkers]. Let’s say I am using this great new shiny library [Comlink]. It’s needed by both `main.js` and `worker.js` as Comlink is an abstraction over `postMessage`. Of course both `main.js` and `worker.js` have other dependencies besides Comlink.

![dependencies](https://user-images.githubusercontent.com/234957/36124715-048b2918-1049-11e8-8f4f-815b3a5e4148.png)

(You might already be able to tell where I’m going with this)

**Attempt 1: Entry points**

Listing both `worker.js` and `main.js` as entry points doesn’t yield the expected results as all static imports will be inlined. Comlink will be (down)loaded twice. The semantics of entry points are that only one entry point will be loaded at a time. In the context of my example, though, two entry points are loaded in parallel.

![suboptimalchunk](https://user-images.githubusercontent.com/234957/36125110-a067fa04-104a-11e8-9f56-704ca86b76d8.png)

**Attempt 2: Dynamic loading**

I tried some hackery with `import()`, but the problem is that WebPack (rightly) assumes that there’s is a global registry of loaded modules. `worker.js`, however, runs in a different realm and has a separate global scope to `main.js`

**Workaround: Force a common chunk**

My current workaround is to use the entry point approach and manually maintain a list of shared modules that need to be put in a separate chunk using `CommonChunksPlugin`:

```js
module.exports = {
  entry: {
    main: './src/main.js',
    worker: './src/worker.js',
  },
  output: {
    filename: '[name].js',
  },
  plugins: [
    // Force comlink into its own bundle
    new webpack.optimize.CommonsChunkPlugin({
      name: 'comlink',
      minChunks: 2,
    }),
  ],
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Under the assumption that there’s good caching headers, the optimal behavior is to put Comlink in it’s own chunk (or a chunk for shared modules) so it’s only downloaded once. The second request by the worker will hit the HTTP cache and re-use the already downloaded shared chunk.

![optimalchunk](https://user-images.githubusercontent.com/234957/36125059-67bd99d4-104a-11e8-8e92-a2005b23a26a.png)

**API**

I’m not sure what the API for this would look like. This API would not only be useful for workers, but also for pages that load another entry point in an iframe (although, tbh, I struggle to find a good example for this 🤷‍♂️ )

 I think the most straight-forward way would to add a `realmEndpoints` (name pending lol) to the webpack config which lists entry points that can be loaded in parallel to _one_ of the main entry points.

What do y’all think? API suggestions/corrections? Am I just holding it wrong?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

[WebWorkers]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API
[Comlink]: https://github.com/GoogleChromeLabs/comlink

**Comment by sokra** [comment]
Currently a `web` compilation and a `webworker` compilation can't share chunks, because they are using different ways to lazy-load chunks. web uses JSONP, webworker uses `importScripts`.

**Comment by sokra** [comment]
It may be possible to create a new agnostic target in which chunks have the same format, than something like this could work.

---

For on-demand-loading:

While in web target loading chunk in parallel is easily possible via `<script>` tags, `importScripts` in webworker context is sync and don't allow parallel loading. We would need to use `fetch` instead, which has cross-origin limitation, but I assume this won't be a problem in webworkers.

For initial loading:

web target support multiple initial chunks via multiple `<script>` tags in HTML. `new Worker()` only supports a single argument. So it's difficult to startup a worker with multiple parallel initial chunks.

It may be possible to solve these challenges with a ServiceWorker doing the parallel requests and concatenation the responses...

**Comment by surma** [comment]
> Currently a target: "web" compilation and a target: "webworker" compilation can't share chunks, because they are using different ways to lazy-load chunks. web uses JSONP, webworker uses importScripts.

I forgot about that bit! In my workaround (see below) I currently also hand-load the chunks using `importScript`. I think an agnostic format that can be loaded by both workers and web would be great to see.

```js
const base = `${location.protocol}//${location.host}${location.pathname.split('/').slice(0, -1).join('/')}`;
new Worker(`data:application/javascript,window=self;importScripts('${base}/comlink.js');importScripts('${base}/worker.js');`));
```

**Comment by surma** [comment]
> It may be possible to solve these challenges with a ServiceWorker doing the parallel requests and concatenation the responses...

This feels like early optimization/over-engineering to me. I see where you are coming from, but just supporting WebWorkers with sequential `importScript()` for now seems totally sufficient. Maybe allow to inject another function than `importScript` so developers can write their own loader if they really need parallel fetching. I think in the long run it’s easier to bet on ES6 module loading to land in workers and use that.

**Comment by sokra** [comment]
> WebWorkers with sequential importScript()

fetch + eval is a good option too.

**Comment by TCMiranda** [comment]
`importScripts('foo.js', 'bar.js');       /* imports two scripts */`

>Note: Scripts may be downloaded in any order, but will be executed in the order in which you pass the filenames into importScripts() . ...

From [MDN Using Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers):

Seems that it doesn't means that 'foo.js' and 'bar.js' could be downloaded in parallel.
In fact they are downloaded and executed synchronously.

`prefetch` as script also works. Even using `importScript`, and the file is loaded from disk cache.

**Comment by TCMiranda** [comment]
Isn't it possible to infer a "web+webworker" target by seeing `importScripts` being used? Or the target is to keep using `import` / `require` inside workers?

**Comment by mixtur** [comment]
It seems to be the same as https://github.com/webpack/webpack/issues/6908. And both issues seems dead. Why is that? Sounds like a very useful feature to have

**Comment by evilebottnawi** [comment]
bump

**Comment by cacheflow** [comment]
Has this work been done already? Could this possibly be in Webpack 5? @evilebottnawi @sokra?

**Comment by evilebottnawi** [comment]
@cacheflow i think no, it is not high priority, but you can send a PR and help us :+1:

**Comment by TheBous** [comment]
Any workaround / solutions ?

**Comment by zbigg** [comment]
I've managed to make it working, by creating really ugly `importScripts` based polyfill of DOM required to load script in worker context.

Here is SO answer with this polyfill: https://stackoverflow.com/a/59743427/269448

Ugly, but works for me for very limited use case.

**Comment by onzag** [comment]
@zbigg I commented in SO as well, I found a solution by creating an injection file, which is based on @surma solution but a plugin could actually be written for it... also the solution proposed by surma doesn't work too well because it implies some security concerns so there would be issues when opening stuff like IndexedDB whereas the injection file has no problems.

The answer is in the same thread.

I might go around writting the webpack plugin once I am less tired, however I'd not consider it a real fix. More of a hack.

But on the plus side everything works just fine and having code in common between the main app and the worker becomes trivial once the injector is setup properly.

**Comment by onzag** [comment]
Alright I wrote this as a temporary solution

https://www.npmjs.com/package/worker-injector-generator-plugin

Thanks @zbigg @surma 

I've heard of ideas of using fetch and eval for async but I've dismissed them because eval won't execute in some safe contexts, relying in eval doesn't seem like a good idea either.

**Comment by anilanar** [comment]
@surma Some software that works as a "widget" embedded inside a host website, the iframe case happens. We use that approach at https://www.userlike.com and I know that https://www.intercom.com does the same.

**Comment by tobiu** [comment]
in case this one is still relevant, i figured out a pretty sweet approach to handle this, including split chunks across different apps (which run inside a worker).

details (the code) is here:
https://github.com/neomjs/neo/tree/dev/buildScripts

**Comment by evilebottnawi** [comment]
Should work out of box for webpack@5, but need more tests, feel free to try it

**Comment by sokra** [comment]
`new Worker(new URL("./worker", import.meta.url))`

**Comment by sanbornhilland** [comment]
> Should work out of box for webpack@5, but need more tests, feel free to try it

I'm not seeing this work out of the box, using Webpack 5 and Comlink 2. Do I need to change my imports to use the syntax suggested by @sokra, specify 

		new Worker(new URL("./worker", import.meta.url))

**Comment by sanbornhilland** [comment]
Okay for anyone who comes along with the same migration questions I had, I've gone a little further on this and it does indeed work out of the box in Webpack 5. I had to do two things.

1. Drop `worker-loader` and use this syntax mentioned by @sokra 

	new Worker(new URL("./worker", import.meta.url))
	
1. For workers that were using comlink, drop the `comlink-loader` and switch to use the new syntax with an explicit call to Comlink like:

```js
const worker = new Worker(new URL('./myClass.comlink', import.meta.url))
const MyClass = Comlink.wrap(worker)

const foo = new MyClass()
```

As far as I can tell it works great and code splitting works without any additional setup so that's awesome 🥂

**Comment by terpimost** [comment]
Guys, I'm very confused by this situation, documentation, examples and workarounds.
I do appreciate work that Webpack team does and would happily donate money if somebody could put clarity in this.
It is so frustrating that I'm happy to pay just to get an answer.
 
There is [example](https://github.com/webpack/webpack/tree/master/examples/worker) of how Webpack can understand that we are importing a worker .
That helps us to not create a separate entry point - ok. But it doesn't demonstrate how worker and not worker would share module from a separate chunk. It looks like webpack 5 can't do that, correct? Is there a suggested way on how to do that?

In the example https://github.com/webpack/webpack/tree/master/examples/worker we have `chat-worker` which imports history from `chat-module`, while `example.js` creates a worker from `chat-worker`. The resulted bundle is 2 files 'main.js' and 'chat.js': 
![image](https://user-images.githubusercontent.com/1903309/110858803-8399f400-8288-11eb-99fc-958720d18ad6.png)
but there is no code shared between chat-worker.js and example.js!
_fibonacci is kind of the same case..._ 

Lets add import of `chat-module` into the `example.js` like this:
```
import { history as historyChat } from './chat-module'
console.log('history=',historyChat)
```
And result of such bundle is this:
![image](https://user-images.githubusercontent.com/1903309/110859083-e55a5e00-8288-11eb-999a-8392757121ea.png)
`chat-module.js` appears twice in our bundle: inside `main.js` and inside `chat.js`.

So please can somebody give a clear answer on how can I get the result like this:
- `main.js` imports `chat-module.js` from a chunk like `chat-module-chunk.js`
- `chat-worker.js` imports `chat-module.js` from a chunk like `chat-module-chunk.js`
- `main.js` uses `chat-worker.js` and staff works :)

Now imagine a situation when `main.js` imports 5 different modules including soething from npm, while worker.js includes 5 of the same modules. What is the webpack.config.js magic should be written to put those 5 modules in one single chunk? Not all of those modules are from npm, some from my project, they are from different folders. 

All my attempts of chunk splitting optimization don't produce workable app. 
Right now I have to live with chunks which has huge portion of module duplicates because worker imports bunch of staff and the main app imports same staff.

Do I have to change all imports to dynamic? Do I need to do that only in the worker or I have to do that in both places? and after ask webpack to split only async chunks?
Which functions should I use for that? How I should direct webpack to produce particular modules I want into a single chunk?

**Comment by anilanar** [comment]
@terpimost I'm not sure if it's the same for workers or not but for normal chunks, you gotta use `chunks: 'all'` to make entrypoints share chunks. Otherwise, chunks are only shared between async chunks. 

Documentation says:

> Providing all can be particularly powerful, because it means that chunks can be shared even between async and non-async chunks.

**Comment by alexander-akait** [comment]
@terpimost Can you provide simple example?

**Comment by surma** [comment]
@terpimost 

Take a look at the [code-splitting example](https://github.com/GoogleChromeLabs/tooling.report/tree/live/tests/code-splitting/subtests/between-workers/webpack) that we have for Webpack 5 on [tooling.report](https://tooling.report).

Looking at the [webpack config of that example](https://github.com/GoogleChromeLabs/tooling.report/blob/live/tests/code-splitting/subtests/between-workers/webpack/webpack.config.js#L20), I wonder if you are merely missing a `minSize: 0`.

**Comment by surma** [comment]
Also, I am thing I can officially call this issue resolved with Webpack 5 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by terpimost** [comment]
@surma @anilanar @alexander-akait sorry guys I forgot to tell that Webpack can split code nicely thanks to:
```
splitChunks: {
      chunks: 'all',
      minSize: 0,
    },
```
BUT after that the app **simply doesn't work**: 
![image](https://user-images.githubusercontent.com/1903309/110964291-09697e00-8321-11eb-9184-96c143060696.png)
Here is the example https://github.com/terpimost/webpack-examples/tree/main/worker

Please tell me if I'm doing something wrong. Here is the video with clarifications:
https://www.loom.com/share/58022b5a4b69474199c16bad3b2b0309

**Comment by anilanar** [comment]
@terpimost `chunks: all` changes entrypoints in a dynamic way. Webpack, after a build is done, will tell you what js files you need to load for an entrypoint to work. To get the list of those files programmatically (or automatically), you need to use html webpack plugin or webpack manifest plugin that would output a json file to tell you what files needs to be loaded.

**Comment by terpimost** [comment]
Ok, so we must load all the assets with shared libraries in index.html before our main app and the way to do so is HtmlWebpackPlugin. And if something isn't working we have an error in importing scripts in html or error in dynamic imports.
shared modules must be loaded first
after that main app
Do we need to be sure that shared modules loaded in html before we use Worker in which those modules are also used?

**Comment by anilanar** [comment]
@terpimost Sorry, I don't know how it would work for workers. In a worker context, you somehow need to load all files that belong to the worker entrypoint; because a web worker is like a separate browser tab with 100% isolation from the main js thread. Workers need a different handling similar to what HtmlWebpackPlugin does and I'm not sure if webpack or a plugin has a feature to support that. 

That's all the knowledge I have I can share with you :no_mouth:

**Comment by sokra** [comment]
Workers will automatically load all the chunks they need if it's splitted into multiple chunks.
I think (not super sure) that you only need `chunks: "all"` if you want to split the real entrypoints. The worker entries should get splitted without it too. So two worker should share chunks even without that. But the threshold of 20kb will still apply if you don't set minSize.

**Comment by terpimost** [comment]
@sokra and @anilanar thank very much for clarifications. I understand that new way of creating a worker is
`const w = new Worker(new URL('./worker.js', import.meta.url));`
which will handle things for us, but could you please clarify how can I do the same without using `import.meta.url`?
From my understand steps should be like this:
- allow webpack to split chunks `chunks: 'all', minSize: 0,`
- create and entry point for the worker to actually produce it as a file
- exclude such worker in HtmlWebpackPlugin so it will not be placed in index.html
- create a worker as with usual file
I'm confused about the last step, `const w = new Worker('worker.js')` and `const w = new Worker('./worker.js')` doesn't work.

I guess I should use a new way of importing assets in Webpack 5 or somehow construct the URL without using `import.meta.url`. Or I just should use old WorkerLoader for this purpose?

Could you please help me with that?

**Comment by tobiu** [comment]
As already mentioned 6 months ago: webpack does a great job regarding worker based split chunks.

The neo.mjs project is adjusted to use webpack v5 now and we get split chunks across different threads (workers & main thread) as well as for different Apps which run inside the Application worker.

Obviously each thread does need to load the shared chunks it needs on its own. Not an issue for me, since the main threads are extremely lightweight.

In case you need an very advanced example on how it can be done:

https://github.com/neomjs/neo

All webpack related logic is inside the buildScripts folder.


Best regards,
Tobias
