### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by malballah** [webpack/webpack#6479]
I ma having an issue when building angular 5 app please look at the screenshot, I do not know how to start to figure it out:

![untitled](https://user-images.githubusercontent.com/6220899/36151907-cfcf4f18-10d1-11e8-9334-095e092925b2.png)

**Comment by evilebottnawi** [comment]
@malballah Seems related to https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/231 and https://github.com/jantimon/html-webpack-plugin/issues/849

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
