### ISSUE TITLE
Incorrect description in "multiple-entry-points" example for webpack 4

### ISSUE THREAD

**Issue by mikegreiling** [webpack/webpack#6528]
The `multiple-entry-points` README.md says:

> - `commons.js` contains:
>   - the module system
>   - chunk loading logic
>   - module `common.js` which is used in both pages

https://github.com/webpack/webpack/blob/master/examples/multiple-entry-points/README.md

However with webpack 4, this no longer seems to be the case.  In the output below, it appears the module system and chunk loading logic exist within `pageA.js` and `pageB.js`.

I am unsure if the description is wrong or if the example output is wrong, but in either case there is a mismatch here.

/cc @sokra 

I'd be happy to open a MR to correct this if you could describe what's happening here.  Is there supposed to be webpack runtime code in both `pageA.js` and `pageB.js` rather than in `commons.js`?

**Comment by sokra** [comment]
You are right, this behavior changed for v4. module system and chunk loading logic is now in pageA and pageB.

Do you want to send a PR to fix the description in the example? Edit `template.md`.

**Comment by mikegreiling** [comment]
@nveenjain go for it!  I probably won't have the time to get to it this week 😄

**Comment by nveenjain** [comment]
I was having a doubt however, shouldn't the unoptimized code be one with development mode?? and in bundle-common.js, we are calling webpack-cli with mode set to none, which i think is not supported now (as it is throwing errors), mode can only be either `development` or `production`?? Should i also edit that?

**Comment by sokra** [comment]
The example building system sets `mode`.

**Comment by nveenjain** [comment]
@sokra, exactly that's what i'm saying the bug is,  i think https://github.com/webpack/webpack/blob/master/examples/build-common.js#L47 sets mode to none. I don't know why this was not reported though. I was completely confused as to what is going on, but after changing mode to development it worked fine and no optimizations were involved, it actually would affect the stats for every unoptimized code in example. I might be wrong though, but then i don't know what was the exact cause of error.

**Comment by nveenjain** [comment]
I'm afraid to say many files have changed.. Was i implementing it right or am i wrong?
