### ISSUE TITLE
Webpack 4.0 file-loader json issue

### ISSUE THREAD

**Issue by sergey-shpak** [webpack/webpack#6586]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
JSON parse error (' Unexpected token m in JSON at position 0') after `file-loader` plugin handles json files.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
entry:{
  '0': './manifest.json'
}
//...
module: {
  rules:[{
    test: /\.(json|html)/,
    exclude: /(node_modules|bower_components)/,
    use: [{
      loader: 'file-loader',
      options: { name: '[name].[ext]' },
    }],
  }]
}
```

**What is the expected behavior?**
Loading json files and no errors.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.** 
node v8.9.4, webpack 4.0.1, Ubuntu 16.04

**Comment by michael-ciniawsky** [comment]
You don't need any loader for `.json` anymore (since `webpack >= v2.0.0`). `webpack >= v4.0.0` introduced `Module.type` and JSON got it's own `module.type = 'json'` (It doesn't get parsed by the JS Parser anymore). Either remove `json`  from `Rule.test` or explicitly set the `Rule.type` to another `Module.type` e.g  `type = 'javascript/auto'`

**webpack.config.js**
```diff
module: {
  rules:[{
+   type: 'javascript/auto',
    test: /\.(json|html)/,
    exclude: /(node_modules|bower_components)/,
    use: [{
      loader: 'file-loader',
      options: { name: '[name].[ext]' },
    }],
  }]
}
```

or

**webpack.config.js**
```diff
module: {
  rules:[{
-   test: /\.(json|html)/,
+   test: /\.html/,
    exclude: /(node_modules|bower_components)/,
    use: [{
      loader: 'file-loader',
      options: { name: '[name].[ext]' },
    }],
  }]
}
```

**Comment by enjikaka** [comment]
@michael-ciniawsky https://github.com/webpack-contrib/file-loader/issues/259

Seems like Webpack 4 is not ignoring JSON loaded by other loaders?

**Comment by Acanthostega** [comment]
In fact this is a problem when we do not want to bundle the JSON files for nodejs bundle (target="node").

For example, I have a situation where I need to do the bundle of a nodejs application. Some part of this application need to have access to a large number of JSON files containing large data. Thus requiring those files include them in the bundle but their size is too important and webpack crashes because of missing memory.

So I want to use file-loader on some specific json files to put them on the output directory of the bundle, with an hashed name and then read and parse the file with fs to access the content of the JSON files,without bundling, and keeping the hash name functionality to not expose the JSON directory structure on the output directory that will be provided to other people.

I do not see a way to pass the type="javascript/auto" in an inline loader (require("file-loader!file.json")) that will allow me to keep my build working. If webpack in version 4 doen't try to parse a JSON file when using a loader on it as for version 3, the problem will be solved.

**Comment by rustam-gaifiev** [comment]
have the same issue

import '!file-loader?name=[name].[ext]!./manifest.json';
import 'file-loader?name=[name].[ext]!./.htaccess';

**Comment by omichelsen** [comment]
I have to echo that this is not solved and the suggested code change does not achieve the same thing.

The goal is to take a `manifest.json` and copy it to the output dir (perhaps hashed), and get a URL for it with file-loader. Using built in json parsing I don't see how we can achieve this? I don't want the JSON inlined in my output, and I want to control the file name that it is assigned.

My current setup is using https://github.com/markdalgleish/web-app-manifest-loader with file-loader to further resolve some image paths in the manifest itself. If you have a better suggestion I am all ears :-)

**Comment by diegopf** [comment]
@omichelsen I had the same issue and https://github.com/arthurbergmz/webpack-pwa-manifest seems to do the trick

**Comment by differentsmoke** [comment]
I believe the actual problem was not properly understood. The problem is not loading JSON into your bundle, but rather loading JSON as a separate file that will be added to the output directory. Is there a way to achieve this on Webpack 4? If not, this should probably remain open.

**Comment by sergey-shpak** [comment]
adding `type = 'javascript/auto'` or using `copy-webpack-plugin` solves the problem (in my case)

**Comment by enjikaka** [comment]
I also ended up using `copy-webpack-plugin` instead.

**Comment by Tatsujinichi** [comment]
I don't think this should be closed.  
If I specify a different loader for a json file it breaks.  
The "but it is handled for you now," argument does not hold any water here, I should be able to add preprocessing/custom loaders, or use any other loader I want for any file extension I choose to require.
'javascript/auto' is a hack.

**Comment by Tatsujinichi** [comment]
@michael-ciniawsky This is a problem for me as well, for example I need to replace text in JSON files before they are loaded.

**Comment by vsaarinen** [comment]
I'm still having trouble with this. Here's my situation:

My project has a bunch of JSON files. Most of the files I want to import directly as objects (i.e. what json-loader and Webpack 4 do), but since a few of them are very large, I want to import them using file-loader and fetch the JSON files dynamically when the app runs.

Previously, this worked fine by doing `require('file-loader!!../path/to/large-file.json')` for the large files. Since upgrading to Webpack 4, however, doing this produces the same error as described in the OP.

Based on the discussion in this issue, I tried to get around the problem by adding the following to the rules section of my Webpack config file:

```
  {
    test: /\.json/,
    type: 'javascript/auto',
    use: [require.resolve('json-loader')],
  },
```

Now I no longer get an error at build time, but run into a new problem: the emitted (large) JSON files now contain the following content:

```
module.exports = { <json content> }
```

Trying to fetch and parse these as JSON files obviously doesn't work.

The only way I've gotten this situation to work is by renaming my large JSON files to some other extension than JSON, but that's quite an ugly hack. What's the recommended solution to this situation?

**Comment by vsaarinen** [comment]
Alright. So do I have to change my default loader to be file-loader, and then override it with `require('json-loader!../data/smaller-file.json')` when I do want to import the contents of the JSON file?

**Comment by vsaarinen** [comment]
I tried that approach but am still unable to load some of my JSON files using file-loader and some using json-loader/Webpack's native JSON importing – I get the same error as the OP for files that I tried importing with `require('json-loader!../data/smaller-file.json')`. 

The only thing that has worked so far is renaming the extension of the JSON files that I want to load using file-loader.

**Comment by pristas-peter** [comment]
If someone needs different solution, just rename the .json to another extension and it will work.

**Comment by johnsanthosh** [comment]
ORIGIN_DESTINATION_DATA contains "src/data/origin_destination.json" string  rather than the actual json content.  I'm not able to figure out what is wrong.

`const ORIGIN_DESTINATION_DATA = require('../.././data/./origin_destination.json');`

_Webpack config_ : 

`var webpack = require('webpack');
var path = require('path');

const flaskApp = path.join(__dirname, '../', 'airsage');

module.exports = {
	entry: __dirname + '/src/index.jsx',
	output: {
		path: flaskApp + '/static',
		filename: 'bundle.js',
	},
	resolve: {
		extensions: ['.js', '.jsx', '.css']
	},
	module: {
		rules: [{
				test: /\.(js|jsx)$/,
				exclude: /node_modules/,
				loader: 'babel-loader'
			}, {
				test: /\.less$/,
				loaders: ["style-loader", "css-loader", "less-loader"]
			}, {
				test: /\.css$/,
				loaders: ['style-loader', 'css-loader']
			}, {
				test: /\.(png|woff|woff2|eot|ttf|svg)$/,
				loader: 'url-loader?limit=100000'
			}, {
				test: /\.geojson$/,
				loader: 'url-loader?limit=100000'
			}, {
				type: 'javascript/auto',
				test: /\.json$/,
				use: [{
						loader: 'file-loader',
						options: {
							name: "./plugin-config/[name].[ext]"
						}
					}
				]
			}

		]
	},
};
`

**Comment by the-simian** [comment]
Has anyone figured out a way to *willfully bypass* the native json loader so that we may define a partifular pipeline?

**Comment by lecstor** [comment]
@the-simian adding `type: 'javascript/auto'` to my json loader rule (as mentioned by @akoliyot 👍) fixed this for me.
```
            {
              type: "javascript/auto",
              test: /locale\/.+\.json/,
              loader: require.resolve("@lingui/loader")
            },
```
the closest I found to an explanation was https://scotch.io/tutorials/whats-new-in-webpack-4
> javascript/auto used to be the default module in webpack 3 but webpack 4 completely abstracted the JavaScript specificity from the code base to allow for this change so that users can specify the kind of module they want.

**Comment by blachawk** [comment]
Thank you @akoliyot for that solution with file-loader.  I have it working on my end.

**Comment by marigerr** [comment]
There is info on webpack docs under Module/Ruletype 

https://webpack.js.org/configuration/module/#ruletype

![image](https://user-images.githubusercontent.com/15229372/57181330-89576f00-6e92-11e9-8895-01a95e860ad1.png)

**Comment by elgs** [comment]
Just to be clear, you still need the file-loader to load JSON, is it correct?

**Comment by panlina** [comment]
So there's no way to workaround it for inline loader? Since there's no way to set `type: "javascript/auto"`.
