### ISSUE TITLE
Feature request: warn if a require() is a devDependency

### ISSUE THREAD

**Issue by dbkaplun** [webpack/webpack#6603]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Doesn't warn

**If the current behavior is a bug, please provide the steps to reproduce.** N/A

**What is the expected behavior?** Warnings for imports and requires that are devDependencies.

**If this is a feature request, what is motivation or use case for changing the behavior?** Ensures that proper `dependencies` are tagged as such.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.** N/A

**Comment by ooflorent** [comment]
This is not webpack's responsibility. If you want this feature, use `eslint-plugin-import` and enable [`import/no-extraneous-dependencies`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) rule.

Moreover, if you bundle a project, including its dependencies, then better add them to `devDependencies`. This way when your bundle is distributed and installed, its dependencies will not be included since they are already bundled.
