### ISSUE TITLE
SplitChunksPlugin emit different chunks with same chunk hash but different name

### ISSUE THREAD

**Issue by zation** [webpack/webpack#6652]
When I use `[chunkhash]` for `output.chunkFilename`, I get below errors:

```
ERROR in chunk admin/system
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk frontend/home
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk frontend/not-found
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk vendors~admin/account~admin/auth~admin/dashboard~admin/not-found~admin/system
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk vendors~admin/account~admin/auth~admin/system
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk vendors~admin/account~admin/dashboard~admin/not-found~admin/system
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js

ERROR in chunk vendors~admin/account~admin/system
75002edf.chunk.js
Conflict: Multiple assets emit to the same filename 75002edf.chunk.js
```

Should the chunk hashes to be different or same? In this blog: https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366 webpack suggest we should not use `[name]` in chunkFilename. But if different chunk share the same hash code, what should we use in chunkFilename?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
