### ISSUE TITLE
DllReferencePlugin with multiple dll requires useless libs too

### ISSUE THREAD

**Issue by KulakovSerg** [webpack/webpack#6656]
**Do you want to request a *feature* or report a *bug*?**
bug or wrong plugin usage

**What is the current behavior?**
With config like this:
```js
plugins: [
  /* react and polyfills */
  new webpack.DllReferencePlugin({
  context: process.cwd(),
  manifest: path.join(cacheDir, 'vendorsLite-manifest.json'),
  }),
  /* all other libs */
  new webpack.DllReferencePlugin({
  context: process.cwd(),
  manifest: path.join(cacheDir, 'vendors-manifest.json'),
  }),
]
```

entrypoint which use vendorsLite.js only requires vendors.js too

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should requires only used dlls, not all! Or it should not require any bundles, just libraries if they have been required

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 3.x, any nodejs versions, any OS

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Vanuan** [comment]
> entrypoint which use vendorsLite.js only requires vendors.js too

How webpack is supposed to know whether entrypoint use only packages from vendorsLite. You clearly indicated in your config that all your entrypoints both vendorsLite and vendors.

> It should requires only used dlls, not all! Or it should not require any bundles, just libraries if they have been required

Define "used". Dlls are considered "used" if you specifide them in "plugins" section of your config file. There's no other way to indicate which entrypoints "use" which Dll files.

----

I think you're talking about actual npm packages included in your dlls. Is that a correct assumption? You expect Webpack to inspect dependency tree of all your entrypoints and do some magic so that your bundles are smaller. Unfortunately, magic doesn't exist. You either use DllPlugin (which saves CPU from excessive compiling by sacrificing bundle siz)e or you don't. Webpack doesn't generate dlls on the fly. It generates dlls only once. So when you change your entrypoints dependency tree is not reevaluated. This is done on purpose to increase performance.

**Comment by dev-anton** [comment]
@Vanuan 

> How webpack is supposed to know whether entrypoint use only packages from vendorsLite. You clearly indicated in your config that all your entrypoints use both vendorsLite and vendors dlls.

It's might be interesting, but Webpack 2 had the described behavior.
