### ISSUE TITLE
I have problem when create bundle.js

### ISSUE THREAD

**Issue by VanThanh1812** [webpack/webpack#6661]
When create, I got message: 
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
Then, I follow message but still get same error. So, What 's my proble, anyone help me, pls. Thanks so much.

**Comment by michael-ciniawsky** [comment]
```
$ node_modules/.bin/webpack
```

**package.json**
```js
{
   "build": "webpack"
}
```

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by VanThanh1812** [comment]
Thanks every one, I fixed my problem, thanks you so much ;)

**Comment by Prasanna-Poonacha** [comment]
@VanThanh1812 how did you fix this?

**Comment by jalal246** [comment]
same problem here!
```

{
   "build": "webpack"
}
```
when run build i got 
```
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
```

**Comment by abel-condori** [comment]
try
`npm i -g webpack@2.2.1`
worked for me

**Comment by kyle-villeneuve** [comment]
installing webpack globally fixed the issue for me
