### ISSUE TITLE
optimization.runtimeChunk is disabled by default

### ISSUE THREAD

**Issue by yangmingshan** [webpack/webpack#6683]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
optimization.runtimeChunk is disabled by default.

**If the current behavior is a bug, please provide the steps to reproduce.**
If don't set optimization.runtimeChunk to `true`, webpack will not split a runtime chunk.

**What is the expected behavior?**
According to this [post](https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a) optimization.runtimeChunk should always enabled by default.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node 9.7.1, webpack 4.1.0, macOS High Sierra 10.13.3

**Comment by ooflorent** [comment]
That's the expected behavior since `runtimeChunk` requires additional _work_ to load the newly created chunk. It is the responsibility of the user to load this chunk. If `chunkFilename` contains a hash then you have to extract the filename from the stats which requires advanced knowledge of webpack.

By having `runtimeChunk` enabled by default it would be harder for newcomer to load a production build into their HTML pages.

**Comment by yangmingshan** [comment]
It's good to know, thanks.

**Comment by edmorley** [comment]
> By having runtimeChunk enabled by default it would be harder for newcomer to load a production build into their HTML pages.

It seems like a few features are disabled by default for this reason (eg also `optimization.splitChunks.chunks: 'all'`). Perhaps newcomers should be steered towards using `html-webpack-plugin` more? Or even that plugin included by default for `target: 'web'` - given the zero-config drive at the moment?
