### ISSUE TITLE
Change or allow configuration of split chunk filename delimiter - currently tilde (~)

### ISSUE THREAD

**Issue by sbrown-fc** [webpack/webpack#6710]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Split Chunks are output to a filename containing tilde (~) characters, e.g. vendors\~app-ui.js.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Change, or allow configuration of the character used.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I am packaging solutions for use with SharePoint and tilde (~) is not a valid filename character in that environment.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node 9.7.0
Webpack 4.1.1
Windows 7

**Comment by ManuelBauer** [comment]
Created a pull request for this feature :)
For more info see: https://github.com/webpack/webpack/pull/6712

**Comment by justinkames** [comment]
I've got the same issue, any update on the status of this?

**Comment by sbrown-fc** [comment]
The delimiter can be configured as of version [4.2.0](https://github.com/webpack/webpack/releases/v4.2.0) using `splitChunks.automaticNameDelimiter`.

**Comment by justinkames** [comment]
Awesome, thanks!

**Comment by mjpearse** [comment]
Just putting a note here for search engines as this was a valid workaround to an issue we had.

On just one of our dev boxes (a dell laptop), IIS 10 on windows 10 would 404 for any chunks which had a tilde followed by a number.  Fine for chunks that were tilde followed by a letter.  
ie
~2 doesn't work
~a works

Changing windows 8point3 settings in FSUTIL did not help.  Uninstalling and reinstalling IIS making sure all windows components were the same as other working installs did not help. 
It is likely one machine had some different security settings given it was a windows install from a different manufacturer rather than a clean install.  Tilde followed by a number was reportedly a security vulnerability in IIS.

So we ended up changing the delimiter using this option.
