### ISSUE TITLE
Webpack performance budgets and asset size limit warning apply to images

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#6769]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The webpack performance budgets and asset limit warning applies to images.

![image](https://user-images.githubusercontent.com/2301847/37473737-63319738-2834-11e8-9c8e-0d804fd03635.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/joshunger/bugrepro.git
cd bugrepro
yarn build
```

**What is the expected behavior?**
Per #3216 @addyosmani said "Highlight at build-time any JavaScript chunks or bundles" so should it apply or not apply to images?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

* Operating System: Darwin 17.4.0
* Node Version: 9.5.0
* NPM Version 5.6.0
* webpack Version 4.1.1

**Comment by sokra** [comment]
I think it makes sense to also apply the limit to images

**Comment by joshunger** [comment]
Yeah that's why I wanted to log the issue for discussion since the original issue doesn't mention images or anything non JavaScript

**Comment by TheLarkInn** [comment]
Did the default assetFilter predicate change for this feature? I'm all for large image prevention in many, ways, however I also think they would need to be measured differently.

**Comment by joshunger** [comment]
> however I also think they would need to be measured differently

Do you have analytics on what that number should be?

**Comment by TheLarkInn** [comment]
Image perf isn't my specialty but I could find out some baseline information that is valid. The hard thing is that really instead of checking size you would rather check if compressed or not, because images can come in many sizes, etc. @zouhir is someone who pops up at the top of my head.

**Comment by TheLarkInn** [comment]
cc @molant how accessible for sonarwhal are the image based rules for checking if compression exists?

**Comment by joshunger** [comment]
Likely a separate issue, but please also consider embedded thumbnails and other data stored in the image.

**Comment by molant** [comment]
> how accessible for sonarwhal are the image based rules for checking if compression exists?

We are using third party services for image optimization but it shouldn't be complicated creating one with the usual image compression packages. There are maybe other checks that could be done that don't require running the tools like checking at color space, if it's progressive or not, quality, etc. but that will be a bit more complicated to do.
In case it's helpful, the [cloudinary rule](https://github.com/sonarwhal/sonarwhal/tree/master/packages/rule-image-optimization-cloudinary) code is [here](https://github.com/sonarwhal/sonarwhal/blob/master/packages/rule-image-optimization-cloudinary/src/rule.ts).

> > however I also think they would need to be measured differently
>
> Do you have analytics on what that number should be?

Shouldn't this number depend on the other resources that are being downloaded too?
From what I've seen you can configure the asset and entry sizes but maybe there's a better way that takes into account an ideal load time for a given connection speed (e.g.: "load under 5 seconds on a 3G network") and the total number of resources that need to be downloaded?
As we all know, 1MB file is not the same as 10x100KB files and that's going to have a big impact on the sites load speed.

In sonarwhal we have an [initial approach on perf budgets](https://github.com/sonarwhal/sonarwhal/tree/master/packages/rule-performance-budget) that takes into account RTT, TCP slow start phase, etc. It's far from perfect (no parsing time, no limit on number of connections to a server, etc.), but so far it's been good enough for most of the sites we've scanned.

**Comment by zouhir** [comment]
interesting, so here is what I think:

**From Build tool & browser network point of view:**
All your website assets are the same, you have RTT \ latency, then asset download time, then either decode or execute and no matter what operation it is, the larger the size the worse the performance. so they all should be under your budget.

**Based on personal experience & notes:**
- CSS assets: hardly goes over 10-20% of my budget.
- Large JPEG (an modern agency websites & hero banners): easy starts at 50% of my budget.
- JS easiest to go over 100% of the budget.

**Why we need image size in there:**
Everyone knows how to optimise images & not so many websites out there doing so, good to have that as a reminder especially one of the most common problem in the web is unoptimised and oversized images.

**What might be fair for everyone:**
Perform assets extension match where I can tell my budget as, that would be a better solution than having no images or getting people to stop using the performance object because of some specific asset type.
```
{
 '/\.css/': 40,
 '/\.svg/': 20,
 '/\.js/': 200,
 '/\.png/': 60,
 '/\.jpeg/': 100,
 '/\. webm/': 300,
}
```

Here are my initial thoughts, keen to keep watching this discussion as close as possible.

**Comment by changhuixu** [comment]
font-awesome has a svg file of 610 KiB...

**Comment by Primajin** [comment]
Yes there should definitely be a way to set own budgets. I have a relative small app but there is one big image - and I am OK with that. The problem is, since warnings are treated as errors on CI, my build is now always failing. So setting a threshold would allow me to still be warned if all of the sudden my JS would spike up or I accidentally put a raw image in there - but an image exceeding 244KiB is OK with me.

**Comment by Primajin** [comment]
#7769 was never reviewed... If it would have been we could close this issue here...

**Comment by Primajin** [comment]
I'm trying to perform CPR on this thread for a while now... @Zeracy can you please check #7769 again? And could one of the @webpack team spare a moment to review it? I'd be delighted 😅👍🏻

**Comment by StephanBijzitter** [comment]
It's a shame this is not here yet, I generally appreciate the warnings very much, but 

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  apple-touch-startup-image-2732x2048.png (255 KiB)
```

Can currently only be eliminated by increasing `maxAssetSize`, but that would also increase the limit for a lot of other assets.
Alternatively, I could use `assetFilter` to disable the checks on images, but that could also mean it would accept a PNG file of 100MB. Being able to set different limits for different "matches" (be it glob or regex) would be perfect.
