### ISSUE TITLE
UMD build can't be used in node env

### ISSUE THREAD

**Issue by vreshch** [webpack/webpack#6784]
Ehen using build with libraryTarget: 'umd',  targeted build in node enviroment; getting: 
AR: 
Node give "ReferenceError: window is not defined"
ER: 
no issues  in node & browser

Not possible to set target param to match both platforms;

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack version 4.1.1 
It's due to webpackUniversalModuleDefinition - "this" should be as param instead of window

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by vreshch** [comment]
**Do you want to request a *feature* or report a *bug*?**
bug



**What is the current behavior?**
Then using build with libraryTarget: 'umd', targeted build in node enviroment; getting:
Node give "ReferenceError: window is not defined"

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create UMD library with config: 
`output: {
        path: '...',
        library: 'library',
        libraryTarget: 'umd',
        umdNamedDefine: true
  },`
Then require the library from nodejs 

**What is the expected behavior?**
no issues in node & browser
UMD library work in different platforms;

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack version 4.1.1
It's due to webpackUniversalModuleDefinition - "this" should be as param instead of window

**Comment by MarkRabey** [comment]
I'm having the same issue. My output is:
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(window, function() {
return /******/ (function(modules) {
...
```
That `window` there seems to be the issue. The documentation suggests that instead of `window`, I should have `typeof self !== 'undefined' ? self`. If I change that manually my library works in both the browser and Node environments. Obviously changing it myself is **not** the solution.

**Comment by ScottRudiger** [comment]
I solved this by setting `globalObject` to `'typeof self !== \'undefined\' ? self : this'` in `output`; e.g.,
```javascript
output: {
...
  globalObject: 'typeof self !== \'undefined\' ? self : this'
...
},
```

**Comment by MarkRabey** [comment]
I solved it by switching to Rollup.

**Comment by egoroof** [comment]
omg updated from webpack 3 to webpack 4 and got this issue
no updates here?!

**Comment by or2008** [comment]
any updates on this?

**Comment by esr360** [comment]
Would love to see an official solution to this problem

**Comment by gpoitch** [comment]
https://github.com/webpack/webpack/pull/8625

**Comment by terwer** [comment]
> I solved this by setting `globalObject` to `'typeof self !== \'undefined\' ? self : this'` in `output`; e.g.,
> 
> ```js
> output: {
> ...
>   globalObject: 'typeof self !== \'undefined\' ? self : this',
> ...
> },
> ```
> 
> Edit: But, I agree it should output this way by default whenever `libraryTarget` is set to `umd` (especially since that's what appears in the docs). It certainly caused some time of confusion/frustration.

It works for me

**Comment by sethlivingston** [comment]
For those arriving here and getting a little confused as to whether and when this will be fixed, the pull request that fixes the issue was rejected for Webpack 4 and slated for Webpack 5. However, I don't see any mention of the PR or issue in the Webpack 5 project, and of course I don't know when it will be released anyway.

The fix provided by @ScottRudiger appears to be the only way to get past this issue right now.

**Comment by fullofcaffeine** [comment]
Going through the same issue when trying to require a UMD-compiled js on nodejs, any updates about this one?

**Comment by vbabak** [comment]
According to the [docs](https://webpack.js.org/configuration/output/#outputglobalobject) include `output.globalObject` into **webpack.config.js**:
```
module.exports = {
  output: {
    globalObject: 'this'
  }
}
```
_To make UMD build available on both browsers and Node.js, set output.globalObject option to 'this'._

**Comment by KevinGhadyani-minted** [comment]
What's the difference between these two solutions for this problem:

```js
module.exports = {
  output: {
    globalObject: 'typeof self !== \'undefined\' ? self : this
  }
}
```

```js
module.exports = {
  output: {
    globalObject: 'this'
  }
}
```

Where does it get `this` or `self`? Is there an `exec` somewhere?

**Comment by minkeshj** [comment]
You can set `target: node` property for webpack config.

**Comment by privatenumber** [comment]
@KevinGhadyani-minted 

The first version checks to see if it can use `self`. `self` doesn't exist in Node.js, so it's a way to identify a non-Node.js environment like a browser or a Web worker.

I imagine there won't be a difference in most-cases when it's loaded top-level because `self === this`, but might make a difference if the module loader used is creating a context for it.

I would default to using `this` unless you find that you need the `self` check.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/6522, workaround above
