### ISSUE TITLE
webpack.DllReferencePlugin is not effective in 1.15.0

### ISSUE THREAD

**Issue by GoFighting** [webpack/webpack#6891]

**Comment by ooflorent** [comment]
It looks like you just deletedour [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
