### ISSUE TITLE
add more mode enum?

### ISSUE THREAD

**Issue by zp1996** [webpack/webpack#6948]
when i in `webpack 3.x`, use a env like `alpha`,but in `webpack 4.x` will error,due to this:
https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L1112 

now, i must do like:
```js
const DefinePlugin = require('webpack/lib/DefinePlugin');
...
{
   mode: 'none',
   plugins: [
     new DefinePlugin({
       'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
     })
   ]
}
...
```

**Comment by ooflorent** [comment]
Use `optimization.nodeEnv="staging"`

--- 

It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
