### ISSUE TITLE
webpack hangs in docker container when build

### ISSUE THREAD

**Issue by HaitaoYue** [webpack/webpack#7024]
af-webpack:getUserConfig UserConfig: {"entry":"app/assets/src/index.js","extraBabelPlugins":["transform-decorators-legacy",["import",{"libraryName":"antd","libraryDirectory":"es","style":true}]],"alias":{"components":"/app/app/assets/src/components"},"ignoreMomentLocale":true,"theme":"./app/assets/src/theme.js","outputPath":"app/public","publicPath":"/static/dist/","hash":false} +0ms
  roadhog:build user config: {"entry":"app/assets/src/index.js","extraBabelPlugins":["transform-decorators-legacy",["import",{"libraryName":"antd","libraryDirectory":"es","style":true}]],"alias":{"components":"/app/app/assets/src/components"},"ignoreMomentLocale":true,"theme":"./app/assets/src/theme.js","outputPath":"app/public","publicPath":"/static/dist/","hash":false} +0ms
  roadhog:getWebpackConfig babel: /app/node_modules/roadhog/lib/babel.js +0ms
  roadhog:getWebpackConfig browserslist: last 2 versions +0ms
  babel:config:config-chain Ignored '/app/app/assets/src/theme.js' because it failed to match one of [ /(\/app\/\.roadhogrc\.mock\.js|\/app\/\.webpackrc\.js|\/app\/webpack\.config\.js|\/app\/mock|\/app\/src)/ ] from '/app' +0ms
  af-webpack:getConfig use user's eslint bin: /app/node_modules/eslint/lib/api.js +0ms
  af-webpack:getConfig userRc: {"extends":"eslint-config-egg"} +1ms
  af-webpack:getConfig use user's .eslintrc: /app/.eslintrc +0ms

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
