### ISSUE TITLE
splitChunks keep a lot of common modules into a single bundle

### ISSUE THREAD

**Issue by jinxin479** [webpack/webpack#7041]
<img width="608" alt="19fbe9e2-189d-463a-940d-fa272669b5a4" src="https://user-images.githubusercontent.com/15315816/38763764-42447ff0-3fd5-11e8-90ef-f6215250739b.png">

this is the config about splitChunks;
```
webpackConfig.optimization={
  occurrenceOrder: true,
  runtimeChunk: true,
  usedExports: true,
  concatenateModules: true,
  

  splitChunks: {
    automaticNameDelimiter: "-",
    name: true,
    maxAsyncRequests: 7,
    maxInitialRequests: 5,
    minChunks: 2,
    cacheGroups: {
      vendor: {
        test: /[\\/]node_modules[\\/]/,
        chunks: "initial",
        name: "vendor",
        priority: 10,
        enforce: true
      },
      lazy: {
        test: ({ resource, count })=>{
          return /antd/.test(resource)
        },
        chunks: "async",
        name: "lazy",
        priority: 10,
        enforce: true
      },
      "lodash-moment": {
        test: ({ resource, count }) => {
          return resource&&/lodash|moment|immutable/.test(resource)
        },
        chunks: "all",
        name: "lodash-moment-shared-bundle",
        priority: 10,
        enforce: true,
      },
      
    }
  }
}
```

**Comment by jinxin479** [comment]
but what maxAsyncRequest should be

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
