### ISSUE TITLE
exporting 'exports.default' rather than 'exports'

### ISSUE THREAD

**Issue by mhelvens** [webpack/webpack#706]
I'm writing a library with ES6 module notation. The main module exports only a default object:

```
// defining MainObject
//...
export default MainObject;
```

Inside other ES6 modules, Webpack seems to handle this well, extracting the `exports.default` when needed. But when exporting my library to, e.g., UMD, the entire `exports` object is exported.

I'd like the option to export `exports.default` instead. Right now, my build-process fixes this with a simple search/replace operation on the Webpack output:

```
.pipe(replace(
    'return __webpack_require__(0)',
    'return __webpack_require__(0).default'))
```

It works, but it's not ideal.

**Comment by loganfsmyth** [comment]
Webpack just uses standard `require` calls, but if you're using `6to5`, it wraps all `import` calls in logic to use `.default` and fall back to `exports`.

If you don't want a standard ES6 export for your entry point, perhaps you can have it do `module.export = ` instead of using ES6 `export`? It's really all up to the transpiler, rather than webpack.

**Comment by mhelvens** [comment]
I don't think there *is* a standard export from ES6-to-ES5. Within ES6, there is special syntax to deal with an `exports` object, a default value or both. With AMD/CommonJS, you can only export a single value, so a choice has to be made.

The choice that Traceur makes (6to5 too, probably) is to send the whole `exports` object. This is sensible for ES6-to-ES6, since it contains all exported data, with `exports.default` being the default value. It can then be properly dissected on the import-side.

But when an ES5 entry-point is made from an ES6 module that *only* exports a default value, it makes sense for that value to be exported directly. Using old syntax inside an ES6 module doesn't seem like a nice solution when it should be done transparently. And while this may be solvable as a feature of the transpiler, general post-processing of the entry-point export value seems like a useful Webpack feature in any case.

**Comment by nathancahill** [comment]
I ran into this issue as well. I'm exposing a exported library with the `output.library` option. When I export the library like this, it works as expected:

```js
module.exports = Library;
```

When I export the library like this, I get an exports object with a `default` key:

```js
export default Library;
```

I believe this should become something like this:

```js
exports["default"] = Library;
module.exports = exports["default"];
```

Instead I get the same code as @mhelvens got:

```js
return __webpack_require__(0)
```

**Comment by vvo** [comment]
Same issue: module is doing export default functionr() {}, using UMD feature of webpack does not work.

Did any of you guys solved this "the right way"?

I have trouble understanding what went bad here, export default function() {} when using webpack "libraryTarget" to umd I really think we should get the exported function, not default: function() {}

But maybe I miss some information

**Comment by sukazavr** [comment]
@vvo +1

**Comment by banunatina** [comment]
Same issue! 
I fixed this by using `module.exports = lib` instead of `export default lib` in the entry file for my code.

**Comment by greypants** [comment]
+1

**Comment by greypants** [comment]
:point_up: yeah... It's a Babel thing: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

Can get back to how it was with https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by skaapgif** [comment]
The problem lies in how webpack exports a library. 

Babel adds `exports.__esModule = true` to each ES6 module. On importing a module Babel calls `_interopRequireDefault` to check for that property, if it sees it it imports `module.default`, otherwise just the module.

Webpack's library compiler simply strips out `__esModule` breaking babel's ability to correctly import the given source as a ES6 module.

**Comment by skaapgif** [comment]
If you're exporting a `commonjs` library, a quick fix is to set `library: 'commonjs2'` as this does not strip away the required `__esModule` attribute.

**Comment by christopherbalz** [comment]
Changing to 'commonjs2' as suggested above works for me.

**Comment by sidjain26** [comment]
Can someone explain this to me. I am writing a library with `target: "node"` , `libraryTarget: "commonjs2"`  and `library: jwt`. 

From within my `src/index.js` file, I have multiple exports:

```javascript

export { a, b, c}

export default (d) => "e";

export const f = "g";
```

I consume this library in my project like:

```javascript

import jwt, { a, b, c, f } from "jwt";

```

However, `jwt` is set to the entire `module.exports` object rather than `module.exports["default"]`. Is this expected behavior or am I doing something wrong?

**Comment by skaapgif** [comment]
@f0rr0 Since you're not using babel you'll have to look at how Node V6 detects ES6 modules vs older `module.exports` modules. Understanding that Babel used `.__esModule` was what eventually led me to a solution.

This DRAFT spec https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module suggests a parse goal field in `package.json`, but it's not immediately clear from that document whether or not it has been implemented.

Hope that points you into the right direction.

**Comment by f0rr0** [comment]
@skaapgif Thanks for the heads up! This was clarified at https://github.com/webpack/webpack/issues/2945

**Comment by madikarizma** [comment]
@banunatina Funny coming across you here. Your comment solved an issue for me in Vue.js. Thanks!

**Comment by abhinavsingi** [comment]
@f0rr0 @skaapgif - did you try add-module-exports plugin from babel?

**Comment by albertogasparin** [comment]
I've also faced this issue. I've written a library with Typescript + Babel + Wepack, and the `libraryTarget: 'umd'` exports an object with a `default` key, instead of my lib code. 

Unfortunately the workarounds above did't work because:
- Typescript with target es2015+ allows only `export default x`
- `add-module-exports` is useless when babel `modules: false` is set

So, I had to come up with a different solution: adding a custom UMD wrapper with [wrapper-webpack-plugin](https://github.com/levp/wrapper-webpack-plugin). Just remove the `library*` options under `output` and add the plugin:

``` js
const WrapperPlugin = require('wrapper-webpack-plugin');
module.exports = {
  //...
  plugins: [
    //...
    new WrapperPlugin({
      test: /\.js$/,
      header: ('(function umdWrapper(root, factory) {' +
        '  if(typeof exports === "object" && typeof module === "object")' +
        '    module.exports = factory().default;' +
        '  else if(typeof define === "function" && define.amd)' +
        '    define("NAME", [], function() { return factory().default; });' +
        '  else if(typeof exports === "object")' +
        '    exports["NAME"] = factory().default;' +
        '  else' +
        '    root["NAME"] = factory().default;' +
        '})(this, function() {' +
        'return ').replace(/NAME/g, 'MyAwesomeLib'), // this is the name of your lib
      footer: '\n})',
    }),
  ],
};
```

(PS: The header code is almost entirely copied from the default Webpack UMD wrapper)

**Comment by LewisWBPD** [comment]
Just for reference for anyone coming from a google search, Webpack 3 has an option called [libraryExport](https://webpack.js.org/configuration/output/#output-libraryexport) that can be set to "default" which should hopefully fix this issue.

**Comment by viion** [comment]
What is the correct solution for this? I am facing this where I have:

```js
const MyApp = {
    refresh: foo () {
        console.log('Lorem Ipsum');
    }
};

export default MyApp;
```

Webpack:
```
config.output.library = 'MyApp';
config.output.libraryTarget = 'var';
```

and I have to do `MyApp.default.foo()`

I've seen suggestions of using `modules.exports = MyApp` but you cannot include that if you use `import` (which I do in this script...)

So what is the correct answer to **not** use the `default` property? I want to be able to do `MyApp.foo()`

**Comment by bomzj** [comment]
`output.libraryTarget: 'umd'` works for me.

**Comment by lustan3216** [comment]
```
export let Lulala = {a: 1, b: 2}
```
```
output: {
    path: path.join(__dirname, 'dist'),
    filename: 'Lulala.min.js',
    libraryTarget: "umd",
    library: undefined,
  }
```

It's a workaround for me to remove the default key.
I can use like this `Lulala.a #1 `

**Comment by jherax** [comment]
> 
> 
> Just for reference for anyone coming from a google search, Webpack 3 has an option called [libraryExport](https://webpack.js.org/configuration/output/#output-libraryexport) that can be set to "default" which should hopefully fix this issue.

Good solution, the [`output.libraryExport`](https://webpack.js.org/configuration/output/#output-libraryexport) was the perfect solution. This worked for me:

```javascript
    output: {
      // ... other options
      library: 'myLibNamespace',
      libraryExport: 'default',
      libraryTarget: 'umd'
    },
```
