### ISSUE TITLE
Make optimization.splitChunks.chunks default to 'all' for web targets

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack#7064]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The default value for `optimization.splitChunks.chunks` is `'async'`, which means that `SplitChunksPlugin` doesn't split vendor files out of the entrypoint by default. Instead users have to override the value themselves to `'all'`. Source:
https://github.com/webpack/webpack/blob/3a5fda909f2ecf911c73429cb4770948dbd31d24/lib/WebpackOptionsDefaulter.js#L216

**What is the expected behavior?**
That if `target == 'web'` (since as I understand it, targets like node don't support `chunks: 'all'`), then `optimization.splitChunks.chunks` be set to `'all'` in `WebpackOptionsDefaulter.js` instead.

**If this is a feature request, what is motivation or use case for changing the behavior?**
* It's one less thing users need to adjust to have an optimal webpack setup with minimal config.
* My understanding is that the default was set to `async` for now since otherwise it would cause breakage for cases where tooling isn't consuming the stats output for the generated file names. However at some point in the future hopefully enough tooling/plugins/... will have been fixed that it's viable to do this (in a future major version bump of webpack, since this would be a breaking change still :-)).

Many thanks :-)

**Comment by edmorley** [comment]
Similar to https://github.com/webpack/webpack/issues/6683#issuecomment-381999270 I think it might be worth steering new users towards html-webpack-plugin (or even including it by default for `target: 'web'`, so we can get closer to the "zero-config with optimal defaults" world without them holding everything else back.

**Comment by sokra** [comment]
Yeah the idea of defaulting it to `async` was a simpler getting started experience. With `all` extra "random" files are created that need to be included in the HTML. This could be confusing for users, when not generating the HTML. Especially since the bundle just stops working once you reached to threshold for vendor or commons splitting.

When forgetting to pass the option bundle will still work. It may be less optimal for long-term-caching, but for this you need additional options anyway.

So in this case we chose DX over optimization.

Maybe we revisit this in future when HTML entrypoints are supported.

**Comment by edmorley** [comment]
(bump to remove inactive label)

Also, perhaps this could be rolled into:
https://github.com/webpack/webpack/projects/5#card-11066307
("add detailed configuration for production mode to enable long term caching, initial splitting, http2 defaults")

**Comment by mifopen** [comment]
Can we only replace the content of the chunk with the reference to the common chunk like dll plugin does?

If I add entry with referenced css file and then add it to my html file (or whatever I use) then I won't want this entry just disapeared at some time in the future just because someone else uses that css file in another entry.

**Comment by edmorley** [comment]
> (bump to remove inactive label)

**Comment by edmorley** [comment]
> (bump to remove inactive label)

**Comment by evilebottnawi** [comment]
bump

**Comment by mifopen** [comment]
bump

**Comment by mifopen** [comment]
bump
