### ISSUE TITLE
about MiniCssExtractPlugin

### ISSUE THREAD

**Issue by sanshuiwang** [webpack/webpack#7107]
example::
In the hello.js to import style.css file ,
I to change code in style.css file, 
build package over, output  hello. chunkhash .js  , m.hash.css
chunhash and hash value all change
so why?

output: {
    path: path.resolve(__dirname, "../build"),
    filename: "js/[name].[chunkhash:8].js",
    chunkFilename: "demandJs/[name].[chunkhash:8].js"
  },

 new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: "css/[name].[hash].css",
      chunkFilename: "css/[name].[hash].css"
    }),

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
