### ISSUE TITLE
cant compile examples

### ISSUE THREAD

**Issue by PerspectivesLab** [webpack/webpack#7124]
hi there, impossible to compile the examples:
after : npm install
then : npm run build:examples

its hangs forever on cd aggressive-merging && node build.js

and no tutorial, or any information on wiki or website....

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
