### ISSUE TITLE
Feature Request: better support for native Web Components CSS

### ISSUE THREAD

**Issue by Hanterdro** [webpack/webpack#7127]
Hey,

Webpack 5 will include the extract CSS plugin. This are great news.
It would be a great when importing a css file we would have an option that the CSS file would be but not added automatically to the document. Instead of that we would get back the PATH of the file.

Example:

```
{
            test: /\.scss$/,
            oneOf: [{
                resourceQuery: /getUrl/,
                doNotAddToDocument: true, //find a better name for this
                use: [
                    {
                        loader: 'css-loader',
                    }, {
                        loader: 'resolve-url-loader'
                    }, {
                        loader: 'sass-loader
                    }]
            }]
        }
```

```
  import fileUrl from './myDesign.scss?getUrl‘;
```

For Web Components I need the CSS inside the shadow DOM of the Web Component. If I get the URL I could add  the file path in the template of my Web Component.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
