### ISSUE TITLE
How can i config when i run 'webpack' and happen this problem

### ISSUE THREAD

**Issue by 171563857** [webpack/webpack#7142]
ok!

yes,it's version of 3.6.0

how can i try this :)
**Do you want to request a *feature* or report a *bug*?**
i have some question for run 'webpack'

QAQ...but i find many solution and none can solve it
**What is the current behavior?**

![qq 20180428153000](https://user-images.githubusercontent.com/22027896/39393536-03c858da-4af9-11e8-9064-5a8de8e53dca.png)
![qq 20180428152943](https://user-images.githubusercontent.com/22027896/39393539-08cf028e-4af9-11e8-822d-7a38667ae36c.png)
Thanks!!

**Comment by PlayMa256** [comment]
How are you calling webpack, which parameters are you given to webpack? The config seems to be ok, but it is not looking into this file.

**Comment by 171563857** [comment]
sorry
i just know why i can't webpack
because i use vue-cli and webpack will loading ./webpack.conf.js to get config
but i didn't create this file in current folder
is it this way ? i will close this problem if 'yes' 
^0^ thanks for you help

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by PlayMa256** [comment]
@171563857 apparently, the problem here is that your webpack config file has a different name than the usual one. When you invoke `webpack`, the cli goes and looks for common webpack file names, currently it looks for `webpack.config` or `webpackfile`. You can see [here](https://github.com/webpack/webpack-cli/blob/master/bin/convert-argv.js#L49).
When `webpack-cli` can't find those files, webpack defaults a lot of configs for you. I was not able to find the template you are using for vue-cli, so i can't tell you much. Execute `webpack` passing `--config path/to/my/webpack/config/file` and it should identify your configurations.

**Comment by TheLarkInn** [comment]
@PlayMa256 Have you tried removing the context property?

**Comment by 171563857** [comment]
![_20180506003805](https://user-images.githubusercontent.com/22027896/39665380-c36167d2-50c5-11e8-8451-c7a69f2d2787.png)
it's my project file structure
i run "webpack" in /ROOT and not have webpack.config.js in there
so happen this error that i think 
i don't know if it's right ?
i use "vue-cli" and it provide some packing methods,so doesn't need to use "webpack "
