### ISSUE TITLE
CHANGELOG.md ?

### ISSUE THREAD

**Issue by Ceane** [webpack/webpack#715]
The Changelog is buried away on the site, would you consider moving it to the top of the repo?

**Comment by jkimbo** [comment]
+1

**Comment by DarkPark** [comment]
would be very nice to add such information in each [release](https://github.com/webpack/webpack/releases) as it's not clear how to migrate from version to version and are there any breaking changes

**Comment by warrenrumak** [comment]
+1, changelogs are vital to the principles to open source software. It should be considered a point of pride to show off the work you've done, not a chore.

**Comment by warrenrumak** [comment]
Is closing this with no comment an acknowledgement that the webpack authors have chosen to not have a CHANGELOG.md file like most other popular open-source products?

**Comment by DarkPark** [comment]
very strange decision

**Comment by Ceane** [comment]
I closed it because no one took it up. I should have done this a while back but now I am submitting two top level CHANGELOGs to the repo, one for 1.12.0 and above and one for pre 1.12 releases. The regular CHANGELOG.md is will mirror the format of Babel's CHANGELOG and the other one with older releases will mirror the existing CHANGELOG. Seeing that there are tons of releases, I did not go back and retroactively add in details to the older one, so anyone who wants to volunteer can do so. 

@sokra Not sure if you want to be in on this, however I will volunteer to update the CHANGELOG.md for future releases, minor and small.

Here's the PR for reference: https://github.com/webpack/webpack/pull/1658

**Comment by sokra** [comment]
Is it really a problem for you that the changelog is a [wiki page](http://webpack.github.io/docs/changelog.html) instead of a markdown in the repo?

For me it is easier to have it in the wiki, because a changelog in the repo would force me to update it with every release and I don't have the time to do this. I would rather update it in batches when I have the time to do it...

**Comment by DarkPark** [comment]
It's not a problem as long as there is a changelog somewhere.
Though there is a common way to have `changelog.md` in the project root or history details in each release (e.g. https://github.com/DarkPark/stb/releases)

**Comment by warrenrumak** [comment]
@sokra Whether it's easy for you to maintain is not the issue here.  You're building software that other people use and depend on.  It's time to think about how the work you do is presented and understood by others, not just what is personally convenient and saves you, what, a few minutes a month, if that?

Those of us who build applications deal with dozens of packages, and the question of whether or not we're going to upgrade to a newer version is based on the information that package presents about what new features, bug fixes and changes are included.  It's very frustrating and time-wasting to have to review every commit to decide whether or not it's safe to upgrade.

People don't like digging through tons of different web sites to find changelogs.  Every web site has its own structure, and certainly there've been cases where the web site wasn't updated by the time the release went out.  (I've encountered this with Webpack multiple times this year)  .... Coffeescript, for instance, hides their changelog 75% of the way down a massive, unusable homepage.  They release new versions just twice a year... am I supposed to remember where their changelog is everytime I see a new version is available in npm?  Ugh.  No.

With Angular, Aurelia, Gulp, Browserify, Karma, Bower, npm, and even node.js itself, it's very simple and consistent:  the changelog is in the repository, either in the root directory or in a documentation subdirectory.  Npm always includes changelog files when creating packages even if you don't specify it in the files glob -- that's how important they think it is.  Most of those projects take it a step further and directly link the description of the changes to the pull requests so that people interested in seeing how a specific change was implemented can read the code.

Have a look at how those projects document what they do, and think about whether you trust those projects more because of it.

**Comment by sapegin** [comment]
And don’t forget about tools like [npm-upgrade](https://github.com/th0r/npm-upgrade) which open change logs automatically. They couldn’t find change log somewhere in unusual location like a wiki on a site.

**Comment by mik01aj** [comment]
+1. Release notifications from [Sibbell](https://sibbell.com/about/) will get more meaningful then :)

**Comment by Ceane** [comment]
@sokra The reason I introduced it is because it mirrors other open source projects and I think that the community here welcome this change, as I see less and less projects using Github Wiki pages. I really would like to thank you for this project, webpack has been a great tool. We're here to help, if allowed.

**Comment by leoselig** [comment]
+1 from our side too
webpack is awesome, maybe we can adjust the "public relations work" a little :P

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#108
