### ISSUE TITLE
make ProfilingPlugin accessible for plugins option

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack#7154]
It seems ProfilimgPlugin can not be used through the plugins option of the cli.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by DanielRuf** [comment]
> Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

Hm, but I see many questions also in the issues here on GitHub so this is a bit confusing. And would this be ok on StackOverflow today?

**Comment by DanielRuf** [comment]
There you go: https://stackoverflow.com/questions/50096722/how-to-use-profilingplugin-with-webpack-cli-for-webpack-4
