### ISSUE TITLE
[webpack 4] How do I prevent creating a chunk?

### ISSUE THREAD

**Issue by vasivas** [webpack/webpack#7317]
In development mode, I need to disable the ability to create a chunk. How to do this?
`webpack 4` is actually not used by many developers. Especially in a similar configuration. So I took the liberty of asking here.

Generation of the file `vendors~first~second.js` simply stopped the whole development process :(

![screenshot_2018-05-16_10-17-04](https://user-images.githubusercontent.com/12833683/40102475-474dc0d8-58f3-11e8-8b54-473c87f12e26.png)

minimal example https://github.com/vasivas/wb4-chunk-demo

development uses a library that cannot be added to a dll. But it is also impossible to give up dll.
it is necessary that the modules are not taken out in a separate chunk, and compiled in the bundle.

**Comment by ooflorent** [comment]
It looks like you just deleted our **issue template**. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.
