### ISSUE TITLE
Disable code generated by webpack for dynamic splitting.

### ISSUE THREAD

**Issue by vasivas** [webpack/webpack#7367]
use dynamic `import()`. I need to add and remove styles (`.css`) depending on the route.
Before adding, I check for the existence of the tag in html markup and if it is not there, then add it.
But `webpack` adds the same code to html markup after me. This leads to errors.
How do I leave dynamic splinting but disable code generation that adds tags to html?

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
