### ISSUE TITLE
【compile BUG】moduleId is null

### ISSUE THREAD

**Issue by warfrogsdf** [webpack/webpack#7391]
/***/ 3:
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(null);
__webpack_require__(null);
module.exports = __webpack_require__(null);

/***/ }),

/***/ null:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

**Comment by warfrogsdf** [comment]
my dist only one bundle，6M big，because this？

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
