### ISSUE TITLE
Chrome 40 doesn't recognized source map urls produced with #eval

### ISSUE THREAD

**Issue by splodingsocks** [webpack/webpack#740]
Hi there!

Using Webpack 1.5.3 and Chrome 40 (not Chrome 39, it works properly), open a page with a javascript error and click on one of the links in the backtrace for that error. (In a file from the Webpack bundle, of course).

If your experience is like mine, a new blank tab will pop up with the URL that devtools should be using to navigate to the source inside of bundle.js.

when the `devtool` string in the webpack config is set to '#inline-source-map' Chrome understands the link just fine, but there have been reports of reduced accuracy in line numbers with that method, and also the filename in the backtrace is always 'bundle.js'. '#eval' seems to be more accurate, and it shows original filenames in the backtrace, but clicking on that backtrace link breaks in Chrome 40.

I'm opening up this issue here not because this is necessarily a webpack issue, but because I thought it'd be a good place to get ideas about what could be going wrong.

Any ideas? :)

**Comment by pahomov** [comment]
Same on Chrome 41. Link like webpack:///./folder/file.js?:166:31 opens a new tab.

**Comment by chemoish** [comment]
Anyone having issues with `eval-source-map` on Chrome 45?

**Comment by idolize** [comment]
@chemoish Same.

I think it's because `eval-source-map` generates filenames with a "query string" at the end (like `someFile.js?65d2`), but `source-map` generates normal filenames (`someFile.js`).

So if you put a breakpoint in `someFile.js` then Chrome does not activate it when using `eval-source-map` (I assume because Chrome must see `someFile.js` and `someFile.js?65d2` as different files).

**Comment by pitaj** [comment]
I believe that #740, #1194, and #2145 are all at least in part caused by the following issue:

**A source map declaration comment is not recognized if surrounded by a block comment**

For instance, at least in Chrome 49 and Firefox 45, the following will not work:
```js
/*
//@ sourceMappingURL=/config/assets/app.js.map
//# sourceMappingURL=/config/assets/app.js.map
*/
```

However, this will work*:

```js
//@ sourceMappingURL=/config/assets/app.js.map
//# sourceMappingURL=/config/assets/app.js.map
```

*In FF 45, this won't map to source, but it will display the "//@ is deprecated" warning message

I haven't been able to identify the cause of this problem. I imagine it's something related to [this line](https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L22) which then goes to [this line](https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/WebpackOptionsApply.js#L210) which appears to be the root issue. Using `devtool: '#source-map'` or `devtool: 'source-map'` appears to solve the issue at least in Chrome.

**Comment by bebraw** [comment]
Can you try with webpack 2 against current Chrome?

**Comment by Vanuan** [comment]
Chrome version: 57
Webpack version: 2.2.0-rc.2

cheap-module-source-map: Chrome shows "sourcemap detected", but doesn't actually shows files.
eval-source-map: Chrome doesn't show "sourcemap detected"
source-map: Chrome shows "sourcemap detected", but doesn't actually shows files.

How is it supposed to work?

**Comment by jdunnaway** [comment]
I also see this issue in Firefox and Chrome when the last line of my file contains a comment.

`exports.Something = Something; //This comment breaks source maps`
