### ISSUE TITLE
Dynamic import() error, wrong file path on nested routes

### ISSUE THREAD

**Issue by pldg** [webpack/webpack#7417]
# Bug report

**What is the current behavior?**
Dynamic import `import()` doesn't work on nested routes: the file path of lazy loaded file is not begin parsed correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a simple test repository [test-webpack-dynamic-import](https://github.com/pldg/test-webpack-dynamic-import), please read the *README.md* file.

**What is the expected behavior?**
`import()` file path should not be relative but absolute path, or webpack should automatically rewrite the file path if the file is called from a location different from the root folder.

**Other relevant information:**
webpack version:  4.9.1
Node.js version: 8.11.1

Reference to original issue [#6483](https://github.com/webpack/webpack/issues/6483).

**EDIT:** How to solve this problem: See my repository [learn-webpack/dynamic-import](https://github.com/pldg/learn-webpack/tree/master/dynamic-import) and [learn-webpack/publicpath](https://github.com/pldg/learn-webpack/tree/master/publicpath)

**Comment by sokra** [comment]
You can use the `output.publicPath` option to modify the url. Or use a `<base>` tag.

**Comment by pldg** [comment]
Add `output.publicPath` or `<base>` tag do not solve the problem.

I made two branches for testing that scenarios:

- [publicPath branch](https://github.com/pldg/test-dynamic-import/tree/publicPath)
- [base-tag branch](https://github.com/pldg/test-dynamic-import/tree/base-tag)

**Comment by bebraw** [comment]
Confirmed.

**Comment by pldg** [comment]
Thanks @sokra, your solution works. Would be nice to add some resolving logic to webpack runtime, let it rewrite every urls as relative path that point to the correct asset, without the need of `publicPath`. Maybe the label for this issue should be changed from "bug" to "feature request".

**Comment by ourmaninamsterdam** [comment]
I'm having a similar issue and have tried adjusting the `publicPath` to no avail. 

I'm building a component library that uses code splitting, where Webpack outputs a main bundle and any chunks. I am then loading this library in my main application, however at runtime the application cannot resolve the dynamic chunks from the component library and I get this:

```
Unhandled Rejection (Error): Loading chunk 1 failed.
(missing: http://localhost:3000/1.22903e1b8e0b58875f97.js)
```
produced by this line: `<script charset="utf-8" src="/1.b57b3648a17b2bbe2f3c.js"></script>`

Main component library bundle is here: `/node_modules/pwa/dist/bundle.js`
And the chunk: `/node_modules/pwa/dist/1.22903e1b8e0b58875f97.js`

Does Webpack support code splitting within third-party dependencies?

**Comment by flyyang** [comment]
@ourmaninamsterdam  it depends on your server config. make sure http://localhost:3000/1.22903e1b8e0b58875f97.js to find the /node_modules/pwa/dist/ folder.

**Comment by oukjweather** [comment]
I'm having a similar issue as well. I have multiple layers of libraries and my application is not able to load from the correct location the child library chunks.

Application A uses Library A which it loads via npm from a private git repository.
Library A depends on Library B also found on a seperate private git repository. 

Libraries A and B both have polyfills and dynamic imports which get code split into seperate chunks. Both libraries are built using webpack as library with a libraryTarget of 'umd'. 

The application fails to run properly with multiple failures to retrieve files that do not exists at the wrong path. These request are being made by Library A's bundle. Its as if the application webpack did not communicate to the library webpack its absolute path and where to go to retrieve stuff at. Should the application webpack be using the main or browser entries from the libraries package.json file? 

Would think it would use the module entry and build all the dependencies using es6 modules where possible and defined in package.js and do all the code splitting based on those paths from the application. So as an example, if package.json in library_a has the key module defined as '/src/index.js'. Then webpack would load 'node_modules/library_a/src/index.js' and then any of its dependencies, say 'node_modules/library_b/src/index.js' or 'node_modules/library_a/node_modules/library_b/src/index.js' directly depending on where it was in the tree. What it appears to be doing is loading 'node_modules/library_a/dist/js/libary_a.js'. Because libary_a.js is a webpack distribution, it tries to load as if it was operating out of the library as the root.

**Comment by oukjweather** [comment]
I found upgrading all my libraries to use webpack 4.29.1 and changing out npm for yarn resolved the issue for me. Thanks.

**Comment by astr0junk** [comment]
still not worked =(

**Comment by muke1908** [comment]
@ourmaninamsterdam @seanbrookes  Wondering if you have found a solution for this?

**Comment by cgfeel** [comment]
> @ourmaninamsterdam @seanbrookes Wondering if you have found a solution for this?

same issue!

@ourmaninamsterdam @seanbrookes Wondering if you have found a solution for this?
