### ISSUE TITLE
Why HashedModuleIdsPlugin is not enabled by default in "mode: production "

### ISSUE THREAD

**Issue by cocody** [webpack/webpack#7421]
In webpack@4.10.0, as we all know, the chunks is save as ID. It's let to "vendor.js" hash change per run "webpack". so we can install `HashedModuleIdsPlugin` to avoid this. But why we need to "install HashedModuleIdsPlugin" rather "buildIn mode: production" ?

**Comment by evilebottnawi** [comment]
It is part of long term caching out of box issue (https://github.com/webpack/webpack/issues/4913) for `webpach@5`. Also PR with option https://github.com/webpack/webpack/pull/7399 and will be enable by default for production in `webpack@5`. We can't do this in `webpack@4`, because it is breaking change. Thanks!
