### ISSUE TITLE
How to make webpack DefinePlugin work on node_modules folder?

### ISSUE THREAD

**Issue by lopugit** [webpack/webpack#7486]
I'm using a custom node_modules folder inside a child directory to do non-relative path requiring and it's broken my DefinePlugin config for webpack, can I include node_modules folder like with webpack rules?

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
