### ISSUE TITLE
NormalModuleReplacementPlugin and lib files

### ISSUE THREAD

**Issue by kang-chen** [webpack/webpack#7523]
trying to use NormalModuleReplacementPlugin for lib files that aren't exported.

question 1. is this supported? couldn't find it in documentation 

example usage:

```
module.exports = function overrideModule(options){
    return new webpack.NormalModuleReplacementPlugin(
        new RegExp("^"+options.match.replace(/\./g, "\\.")+"$"), (resource) => {
            if (resource.context.includes(options.withinModule)) {
                resource.request = options.replacement
            }
        }
    )
}
```

```
overrideModule({
  match: "./ModuleFoo",
  withinModule: "@submodule/component/lib/another-component",
  replacement: path.join(modulePath, "ModuleBar")
})
```

works fine without ```/lib``` path

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
