### ISSUE TITLE
Every entry point has their own module cache (webpack 4) instead of a shared module cache (webpack 3)

### ISSUE THREAD

**Issue by timneutkens** [webpack/webpack#7556]
# Bug report

**What is the current behavior?**

When loading 2 entry points on the same page that share a common module, the module is instantiated twice, even when it's bundled into the commons bundle.

We ran into this while upgrading [Next.js](https://github.com/zeit/next.js) to webpack 4 and it's currently blocking the upgrade until we know if this is expected behavior.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a reproduction for both webpack 3 and webpack 4, also added an explanation about how Next.js handles things and research into the issue: 

https://github.com/timneutkens/webpack-instantiation-issue

**What is the expected behavior?**

Following webpack 3 there should be only one instance of a shared module. Which is not the case in webpack 4 when having multiple entries on the same page. Though this might be expected.

My main question being: is this expected? Should we bind the "singleton" instance to `window` so that it will be the same across multiple module instances, or is this a regression/bug?

**Other relevant information:**
webpack version: 4.12.0
Node.js version: any
Operating System: any
Additional tools:

**Comment by sokra** [comment]
This is expected. But we got you covered with the `optimization.runtimeChunk` option. Try `optimization.runtimeChunk: "single"` or `optimization.runtimeChunk: { name: "commons" }`

**Comment by timneutkens** [comment]
I forgot to mention that the `runtimeChunk` does include the runtime into a single chunk, but the `var installedModules` code is still in both entrypoints as far as I've tested

**Comment by timneutkens** [comment]
Okay I figured it out, thank you very much for mentioning that the runtimeChunk could have the same `name` as the commons bundle, doing that mirrors the behavior CommonsChunkPlugin had for Next.js in webpack 3 😌

**Comment by timneutkens** [comment]
I'm going to re-open this as the configuration I currently have works but makes *every* module go into the `manifest` chunk, even when defining `minChunks`. I'm sure there's something wrong in my configuration, but I can't seem to get it to work the exact same way as we did with webpack 3, this is the current `CommonsChunk` configuration: https://github.com/zeit/next.js/blob/canary/build/webpack.js#L186-L233

The new configuration I've added is:

```
    runtimeChunk: {
      name: 'manifest'
    },
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        default: false,
        vendors: false,
        commons: {
          name: 'manifest',
          filename: dev ? 'static/commons/manifest.js' : 'static/commons/manifest-[chunkhash].js',
          chunks: 'initial',
          minChunks: totalPages > 2 ? totalPages * 0.5 : 1
        }
      }
    }
```

Which kinda works, it loads the files correct, but the entry chunks are left with only the `webpackJsonp` call:

```
module.exports =
__NEXT_REGISTER_PAGE('/', function() {
            var comp =
        (window["webpackJsonp"] = window["webpackJsonp"] || []).push([["bundles/pages/index.js"],[],[[3,"manifest"]]])
            return { page: comp.default }
          })
        ;
//# sourceMappingURL=http://index.js.map 
```

@TheLarkInn this is what I sent on twitter dm, just posting it here so that future people upgrading from 3 to 4 can benefit from the solution too 👍

**Comment by sokra** [comment]
> minChunks: totalPages > 2 ? totalPages * 0.5 : 1

In some cases this can be `minChunks: 1`. `minChunks: 1` without `test` will literally select every initial module (because every module will match this condition). This will mover entry module from the entry chunks into the manifest chunk. That's probably not what you want.

I recommend choosing `minChunks >= 2` which will select module common in at least two entrypoints. This is still not optimal for performance, because it will affect entrypoints not sharing this module.

Note that it's not required to have the module factory function only once on the page. You can allow duplication, modules are still only instantiated once when there is only one runtime chunk.

Try dropping the `name` and `filename` options to make webpack automatically create names for the create chunks. This will also have a better result. i. e. when entrypoint `a` and `b` share a module it will go into the chunk `a~b` while a module shared between `c` and `d` will go into the chunk `c~d`. This way other entrypoints will not be affected.

Maybe also drop `chunks: 'initial'` to do the same also for async chunks.

Now you are nearly equal to the `default` default cacheGroup, so you can choose to use this instead.

``` js
    runtimeChunk: {
      name: 'manifest'
    },
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        vendors: false
      }
    }
```

The `vendors` default will separate the node_modules from the app modules assuming they change less often/independent from the app modules.

The recommended configuration for your case would be:

``` js
    runtimeChunk: "single", // = { name: "runtime" }
    splitChunks: {
      chunks: 'all',
    }
```

**Comment by timneutkens** [comment]
@sokra thank you very much! Just letting you know it all worked out, changing `1` to `2` was really the only problem 😅, though your explanation made me opt to rewrite a bit of logic in Next.js so that now all chunks are automatically rendered whatever the configuration, making it really easy to add additional splitting where needed. The splitting with the default setting gave very big bundles per-page vs the current commons-configuration, so I disabled it for now, but we can ship an improvement at a later time 🙌

The only thing that I haven't figured out yet is how to make this part https://github.com/zeit/next.js/blob/canary/build/webpack.js#L206-L218 work, which is basically `_app.js` is always used on every page, meaning modules imported there don't have to be replicated into other bundles, as the code is always there. Do you have any idea how to do this? Otherwise I'm going to investigate this further 👍

**Comment by timneutkens** [comment]
Going to close this one 👍
