### ISSUE TITLE
Support fully disabling Node polyfills perhaps?

### ISSUE THREAD

**Issue by loganfsmyth** [webpack/webpack#756]
This is kind of half feature request half bug report :P

1.5.x introduced 'setImmediate' pollyfilling, which is great, but in our case it was kind of a regression because it meant when we updated, we had a new rewrite that polyfilled setImmediate calls that were previously not rewritten. That caused some of our tests started failing because of slight timing differences between the new setImmediate polyfill and `Q` own internal polyfill.

I'll just set `setImmediate: false` now, but I'm now slightly concerned about updated in the future silently starting to inject polyfills that I don't expect. Not necessarily the end of the world, but we try to track all 3rd-party code that we package and distribute, and this would have probably been missed if not for the test failures it caused.

Thanks!

**Comment by sokra** [comment]
True. Any idea what we can do?

**Comment by jhnns** [comment]
Mhmm ... polyfill should always be agnostic. They should do nothing if the thing, they're poly-filling, is already present. This rule is currently violated, because the current implementation just injects the `setImmediate` polyfill when it encouters a call for `setImmediate`.

But this should probably not be handled on webpack level, but on polyfill level. I've sent a PR to [timers-browserify](https://github.com/jryans/timers-browserify/pull/11).

**Comment by jhnns** [comment]
Does [this](https://github.com/jryans/timers-browserify/pull/12) fix your issue?

**Comment by loganfsmyth** [comment]
@jhnns setImmediate wasn't present, so that part of the polyfill is fine, my point is that it unexpectedly injected it starting with a minor version bump, which could constitute a breaking API change.

I guess I mostly posted this because I think it's important to be aware that adding new features is awesome, but defaulting them to enabled is potentially a bad idea.

My main request with this is to be able to set `node: false` to just disable all automatic node polyfilling. I'd rather specifically whitelist things manually than risk having new node deps added to that list. That or major version bumps need to be used when adding new default => `true` options to that.

**Comment by rhumaric** [comment]
The automatic polyfilling of setImmediate also poses an issue when you want to mock it using Sinon's fakeTimers in tests. 

Sinon will still override `window.setImmediate` OK. Unfortunately, this is not the method that will be executed by the module into which Webpack injects setImmediate. Even if the polyfill uses the native implentation, the `setImmediate` in the module is the one that was there at the time of Webpack's injection, not the mock created by Sinon at the time the test is run:(

Disabling the automatic polyfilling and letting devs add their own polyfill would be handy for this scenario too.

**Comment by noyesa** [comment]
I would like to be able to disable the node polyfills as well. I would rather have my code depend directly on the polyfill, since we want to avoid situations where version bumping a build tool (webpack) can impact the stability of running production code or introduce potential security flaws because code is getting automatically injected. Our team is currently enforcing this through code reviews, but I'd rather be able to disable this feature entirely.

**Comment by jhnns** [comment]
> since we want to avoid situations where version bumping a build tool (webpack) can impact the stability of running production code

Updating your build tool can always impact your production code. But it's probably more likely with webpack since it's more invasive than others – which makes it more powerful, but also more "dangerous".

**Comment by noyesa** [comment]
@jhnns You're not wrong, but polyfilling large blocks of code from Node dramatically increases the surface area for failure. We've adopted webpack and we're perfectly fine with the runtime code it's injecting and accept that we're taking a risk, but that's worth it. We'd just like the ability to control or shut off node module shimming.

**Comment by jhnns** [comment]
Yep. I do understand that.

Btw: [these polyfills](https://github.com/webpack/node-libs-browser) are not just used by webpack, they were mainly created and are maintained by browserify users, so I'd expect them to be very reliable.

**Comment by noyesa** [comment]
Yeah I agree it's pretty low risk, but the APIs of these things do change with different node versions. I've already seen APIs previously considered "frozen" according to the node documentation become unfrozen in node 4.x+, and it's not really clear what API compatibility these polyfills target in the first place.

**Comment by mridgway** [comment]
The `setImmediate` polyfill is especially bad in this case because it caused the polyfill we were using (https://github.com/YuzuJS/setImmediate) to not be loaded. In this case, the `setImmedate` polyfill that webpack uses (https://github.com/jryans/timers-browserify) causes crashes in safari when `setTimeout` (used under the hood) is called too many times.

**Comment by jhnns** [comment]
Again, this problem should not be addressed by webpack, but by the polyfills. This way browserify users will also benefit from this.

**Comment by igorpetrov** [comment]
Browserify's polyfills uses `window` object which is break things for me. Today I've spent a lot of time to investigate it.
Of course it related to polyfill implementation and can be fixed, but we are not immune from such issues in future.
+1 for disabling not expected polyfills.

**Comment by bebraw** [comment]
@jhnns Any idea what to do with this one?
