### ISSUE TITLE
Node.js API watch callback calls twice during initial build

### ISSUE THREAD

**Issue by mdreizin** [webpack/webpack#762]
Hello @sokra,

I have found that `watch` callback calls twice during initial build via [Node.js API](http://webpack.github.io/docs/node.js-api.html#the-long-way).

Is it by design or an issue?

**Comment by cowwoc** [comment]
@sokra We discussed on IRC that `watch()` runs an initial full build (to ensure that module IDs remain the same during its lifetime). The documentation at http://webpack.github.io/docs/node.js-api.html reads `Note: watch will automatically run an initial build, so you should either call run or watch.` but I didn't understand the documentation.

Is it possible to be more explicit? Perhaps this could be rewritten as `Note: When watch() is launched, it will run a full build before emitting incremental updates. This is by design.`

**Comment by lencioni** [comment]
I'm running into this as well, when trying to use the `stats` object to inject script tags into my template engine in my express server. The problem for me is that `stats` usually gives me references to the files generated by the first run (either by `Object.values(stats.toJson().assetsByChunkName)` or `Object.keys(stats.compilation.assets)`), which gives me "Cannot find module" errors. Occasionally, I get references to the files generated by the second run, in which case my JS usually works fine. Wrapping the contents of the callback to the webpack run in a `setTimeout` of any length doesn't seem to make any difference.

Am I doing something weird here or misunderstanding how this is supposed to be used?

**Comment by lencioni** [comment]
And occasionally it takes the assets from the second run and my JS doesn't work. I get an error

> Uncaught TypeError: Cannot read property 'call' of undefined

on lines like:

```js
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
```

**Comment by abhinavsingi** [comment]
Any solutions to this problem? I'm too facing this issue when running webpack from Node instead of its by default bundler
