### ISSUE TITLE
a error after refresh

### ISSUE THREAD

**Issue by fukua777** [webpack/webpack#7634]
![err1](https://user-images.githubusercontent.com/19884392/42144790-9c40a3fa-7def-11e8-8668-bdbfbb6ef206.png)
![err2](https://user-images.githubusercontent.com/19884392/42144801-b16734f6-7def-11e8-8157-740f2f486e75.png)

A site packed in webpack is normal when the first load, but i'll get a error after refresh  as shown in the figure, it should be `var e2 = ..`, what should i do?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
