### ISSUE TITLE
How to expose variables inside the vendor.js?

### ISSUE THREAD

**Issue by benji0818** [webpack/webpack#764]
I'm working on a program that has depended on some old code, which is rely on jQuery.
Having benefits from webpack, I was going to manage my code with that.
But, I need to expose jquery lib to global environment for making sure that old code works fun.
After seaching, also tried many times, I failed.
Plz give me some advice, Thanks

**Comment by Chrazy** [comment]
Do something like this in your entry point (pretty standard):
```
window.jQuery = window.$ = require 'jquery'	# expose jQuery so dependencies to window.jQuery works
```

**Comment by jhnns** [comment]
@Chrazy 's solution is straight-forward.

If you don't want to include that into your entry point (because you don't want to include jQuery in your entry bundle), you can also consider using the [legacy-loader](https://github.com/peerigon/legacy-loader) with the [publish-option](https://github.com/peerigon/legacy-loader#publish).

**Comment by benji0818** [comment]
Thx!
