### ISSUE TITLE
Add a test mode, like development and production

### ISSUE THREAD

**Issue by dietergeerts** [webpack/webpack#7659]
## Feature request

**What is the expected behavior?**

The ability to set `--mode` to `test`, which then will set `NODE_ENV` to `test` too.

**What is motivation or use case for adding/changing the behavior?**

That `NODE_ENV` is being set, as that adds consistency in projects. In a test config, styles aren't loaded (node-noop/null-loader), and other settings are being applied. Some rely on the `NODE_ENV` being set to test. With the `--mode` feature, we now end up with 3 scripts that aren't consistent, as the test script needs to set it itself, while the others set the mode option. For new people on the project, that's confusing.

**How should this be implemented in your opinion?**

The same as the other modes, probably with some default settings?

**Are you willing to work on this yourself?**
yes, though I know a lot how webpack works in a functional way, I don't know the internal code.

**Comment by ooflorent** [comment]
> The ability to set `--mode` to `test`, which then will set `NODE_ENV` to `test` too.

You could achieve this using:

1. `mode=test`
2. `optimization.nodeEnv=test`

**Comment by dietergeerts** [comment]
We pack doesn't even allow setting mode to test... It then throws a nice error message

**Comment by dietergeerts** [comment]
I use the old way again, but it would be nice if webpack did allow it, as not the scripts aren't consistent:
```
"start": "webpack-dev-server --mode development",
"build": "webpack --mode production",
"test": "cross-env NODE_ENV=test \"webpack\""
```
would make more sense to also allow test....

**Comment by ematipico** [comment]
What's wrong with setting the environment through `NODE_ENV`?

**Comment by sokra** [comment]
```
"start": "webpack-dev-server --env development",
"build": "webpack --env production",
"test": "webpack --env test"
```

**Comment by edmorley** [comment]
[webpack-command](https://github.com/webpack-contrib/webpack-command) (which has been implied is going to be the replacement for webpack-cli) doesn't support `--env` unfortunately.

**Comment by dietergeerts** [comment]
@sokra , then what's the point of having the new mode option???

**Comment by evilebottnawi** [comment]
@edbedbe @dietergeerts 

> What's wrong with setting the environment through NODE_ENV?

**Comment by ooflorent** [comment]
Modes behave like presets. When one is selected, it enables some plugin to tweak the build according to it. For example, production mode turns on minification (and more).

**Comment by edmorley** [comment]
> What's wrong with setting the environment through NODE_ENV?

Doing so on Windows is frustrating, since a `package.json` scripts entry of eg `NODE_ENV=test foo` doesn't work, and the generally recommended "solution" is to use [cross-env](https://github.com/kentcdodds/cross-env), which add 500ms to startup time when I tested locally, due to multiple invocations of node and Window's poor process start times.

As such, any solution that can move configuration to command parameters (whether that be `--mode` or `--env`) is preferred.

**Comment by dietergeerts** [comment]
@evilebottnawi , then why does the mode variable set the NODE_ENV too? but only with 'production', 'development' or 'none'???

**Comment by qiuyaofan** [comment]
I have same question.I need to use process.env.NODE_ENV to handle code on three On-line environment. Because development,test,production has different ip.

**Comment by reiz** [comment]
I set `NODE_ENV=test` in my Docker image and even started the app with `NODE_ENV=test node server.js`. But no matter what I did, during runtime, `process.env.NODE_ENV` always returned `production`. I was searching for the root cause for almost 2 hours. Until I found the [mode webpack](https://webpack.js.org/configuration/mode/) documentation. Why the hell is webpack overwriting my `NODE_ENV` value? What's wrong with you guys? 
It's pretty normal to have `test` environment. Some companies have even 4 and more stages. Webpack should really not make any assumptions here and for sure not simply overwrite the `NODE_ENV` variable. That just feels like a huge bug! 
I totally support this feature request.

**Comment by kahurangitama** [comment]
I would leave exaclty the same comment as @reiz . Spent whole day on it

**Comment by FloodGames** [comment]
Depending on the process,

```
new webpack.DefinePlugin({
        "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV), //important to override webpack mode
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
})

```
Together with mode:"none" it allows me to run process.env.NODE_ENV = test for example (instead of only development and production)
