### ISSUE TITLE
Hot update bug 

### ISSUE THREAD

**Issue by seekwe** [webpack/webpack#7676]
* Operating System: Windows10
* Node Version: 10
* NPM Version: 5
* webpack version: 4.15

![](http://ww1.sinaimg.cn/large/63a61209gy1ft1kdney7vj20wj0i9abl.jpg)

![](http://ww1.sinaimg.cn/large/63a61209gy1ft1kffefn4j20n40ck3yx.jpg)

error:
![](http://ww1.sinaimg.cn/large/63a61209gy1ft1keux8zjj212x0h4dgy.jpg)

yes:
![](http://ww1.sinaimg.cn/large/63a61209gy1ft1keypaefj20zt0br74v.jpg)

I don't know. do you understand the picture?
```js
/* harmony default export */ var carvue_type_script_lang_js = ({
```
```js 
/* harmony default export */ var pages_carvue_type_script_lang_js = __webpack_exports__["default"] = (carousel["default"]);
```
Should not be ` = ( carousel [ " default" ); `

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
