### ISSUE TITLE
Webpack is very very slow even with cache plugins

### ISSUE THREAD

**Issue by jamalabo1** [webpack/webpack#7684]
# Bug report

**What is the current behavior?**
Webpack is very very slow, 

in webpack 3 recompile time (hot reload) was 1~3s now (webpack 4) its above 3min

**If the current behavior is a bug, please provide the steps to reproduce.**

its not a bug its an issue

**What is the expected behavior?**

balanced compile time and recompile time

**Other relevant information:**
webpack version:  4.15.1
Node.js version:  8.10.0
Operating System: Windows 10
Additional tools: copy-webpack-plugin, webpack-dev-server

i have searched for this issue online and many of issues said use plugins like: 
`hard-source-webpack-plugin`
`mini-css-extract-plugin`

but non of them was helpful and the compile and recompile time are **very** slow

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by jamalabo1** [comment]
@sokra i dont know what is the problem but i know that webpack 4 compile time is **very** slow.

### How i got into this issue?
i used an package that require latest React version and i upgraded react and webpack and when i run the command that runs webpack, i waited for at least 5mins for compile and when recompile (hot reload) (webpack-dev-server) its take a lot of time, then i used the plugins above and the compile time decreased to 3min

**Comment by evilebottnawi** [comment]
@jamalabo1 please create minimum reproducible test repo, without this we can't help

**Comment by jamalabo1** [comment]
i dont understand what reproduce mean!
like you want to see what i have done?
what is my source code?

**Comment by evilebottnawi** [comment]
@jamalabo1 repo with you config where we can reproduce slow build

**Comment by pleunv** [comment]
One thing I noticed while trying a lot of different combinations of `happypack`/`hard-source-webpack-plugin`/`cache-loader`/`thread-loader` in order to try to improve my rebuild times was that all non-js loaders appear to get called with all matching files on every rebuild, even if those files were not changed.

This is for example what `speed-measure-webpack-plugin` reports on initial build and rebuild after changing 1 `js` file:

```
-- Initial Build
[babel-loader] took 2 mins, 1.09 secs
  module count = 1367
[cache-loader] and [graphql-tag/loader] took 1 min, 2.087 secs
  module count = 256

-- Incremental Rebuild
[cache-loader] and [graphql-tag/loader] took 4.54 secs
  module count = 256
[babel-loader] took 2.65 secs
  module count = 1
```

On the incremental rebuild it's hitting `babel-loader` with the one changed file, but also hitting the other loaders (which I've reduced to just one for testing purposes) with all matching files (`*.gql` in this case). Is this the default behavior, or is this due to the loader implementation?

If this data is correct, the additional loader hits seem to be the main culprit for my (and probably other people's) incremental rebuild time issues.

**Comment by pleunv** [comment]
I'll see if I can put together a smaller repro for that, but if I recall correctly this was also happening for file-loader, url-loader, etc.

**Comment by jamalabo1** [comment]
i have updated webpack to version: `4.16.5`
and webpack-dev-server to : `3.1.5`

i dont know if this solves the problem or not, but the hot reload and compile time decreased 1~2 min

**Comment by omril1** [comment]
I have a feeling that copy-webpack-plugin is causing the slowness.

**Comment by wuzinong** [comment]
Same issue with me, any solution for this case? @jamalabo1
