### ISSUE TITLE
optional dependencies when using es6 import/export

### ISSUE THREAD

**Issue by RaananW** [webpack/webpack#7713]
I am trying to define optional externals in an es6 project.
The feature exists - https://github.com/webpack/webpack/issues/339 , but there is no flag that I can set in the (externals) configuration to make a dependency optional. Digging into the code I found that optional is a flag checking for reasons, and if every reason's dependency is marked as optional. But I can't seem to find where it is defined.

What would be the best way to define an external dependency optional? Have I missed something and it is possible doing it using configuration?

**Comment by sokra** [comment]
``` js
try {
  require("external");
} catch(e) {
  // fallback
}
```

**Comment by RaananW** [comment]
Thanks

But :smile:
to keep an es6 (or esm) project consistent, I don't want to use require when importing anything. I use the import keyword.
As a fallback, we are also offering a UMD module, built with webpack. The UMD definition has the option to automatically define the require as optional, but, as i wrote, it is not a flag anywhere I can find.
You can see it here - https://github.com/webpack/webpack/blob/master/lib/UmdMainTemplatePlugin.js#L162
and here for AMD externals as global - https://github.com/webpack/webpack/blob/master/lib/UmdMainTemplatePlugin.js#L97

All I actually want to know is how to get the (external) module to be defined as optional, without using the try-catch method.

**Comment by evilebottnawi** [comment]
Answer above https://github.com/webpack/webpack/issues/7713#issuecomment-404584442

**Comment by RaananW** [comment]
I know closing the ticket is automated, but this ticket is not resolved.
The issue is the fact that this has to be done manually, so es6 projects can't use this feature. Unless there is something I'm missing, of course.
The feature us already there, there is just a need to expose it using configuration.

**Comment by lorisleiva** [comment]
Hi everyone 👋 

I've read a few issues across GitHub of libraries using optional externals via a try/catch. None of them are fully resolved.

The major issue is that you get a warning `Module not found: Error: Can't resolve 'xxx'`.

If a library wants to offer optional adapters for third-party dependencies out-of-the-box, its users will receive a warning for each optional dependencies that this user doesn't need. I'm not sure that this is an acceptable behaviour.

## To be more precise.
**Current context:** wrap `require('xxx')` in a try/catch and register `xxx` as an external in webpack configurations.
**Current behaviour:** library users get `WARNING Module not found: Error: Can't resolve 'xxx'`
**Expected behaviour:** no warning

Am I missing something?

Here's a couple of those issues I was talking about:
- https://github.com/wowserhq/blizzardry/issues/101
- https://github.com/lorisleiva/javel/pull/3#issuecomment-465278136

**Comment by AlexLeung** [comment]
@lorisleiva here's another example: websockets/ws/issues#1220
What would recommend in this case and what is the best fix? I dislike the idea that I need to know about every transitive dependency which has optional dependencies and I need to go explicitly externalize them. While this could lead to a can of worms implementation, it would be nice if webpack could analyze the code to see if the require is within a try catch, then auto externalize if so.

**Comment by slorber** [comment]
Hey,

If there is a good solution to this problem, please let me know.

In the meantime, you can probably disable the warning with warningsFilter option: https://webpack.js.org/configuration/stats/#statswarningsfilter

```
        stats: {
          warningsFilter: [
            (warning) =>
              warning.includes("Can't resolve 'xyz"),
          ],
        },
```

Not sure it will work for you because our setup is not very usual (we actually duplicate some code from Webpack), but this worked for me.

**Comment by sag1v** [comment]
@sokra / @alexander-akait 

I know this is an old issue but unfortunately there's not yet an idiomatic way to use optional deps.
As a library author, using this method you mentioned:

```
// esm/componentA.js
let foo;
try {
  const foo = require("optional-peer-dep");
} catch(e) {}

// do something with foo
console.log(foo);

```

Can this break my lib's tree-shaking support for my consumers?

Lets say the above code is written in `esm/componentA.js` module but the consumer is not importing this module, would it still shake off the consumer's bundle file?

**Comment by sag1v** [comment]
@alexander-akait Thanks!

Just to be sure though, if i mix a `require()` inside an esm module would i break the tree-shake support of my module or is it perfectly find to mix `import` and `require` in the same file?

**Comment by alexander-akait** [comment]
@sag1v `import(...)` works fine in commonjs, so feel free to mix them

**Comment by dotcarmen** [comment]
now that import attributes (`import ... with { ... }`) is allowed, can this issue be revisited? for example:
```js
import external from "external" with { optional: true };

// external is `undefined | typeof import("external")`
if (external) {
  external.doThing();
}
```
