### ISSUE TITLE
Missing external configuration for type:commonjs

### ISSUE THREAD

**Issue by yangchendoit** [webpack/webpack#7738]
![tim 20180718190514](https://user-images.githubusercontent.com/27750211/42877842-8def60f4-8abd-11e8-9928-2f1d0d3b0b93.png)

when i update webpack version to 4, i get this. i can't find what that means,

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
