### ISSUE TITLE
webpackPrefetch 4.16.1 does not create <link rel=”prefetch ...

### ISSUE THREAD

**Issue by IzaGz** [webpack/webpack#7739]
dynamic import
like `
import(/* webpackChunkName: "custom-chunkname" */ /* webpackPrefetch: true */ '../components/UniqueComponent')`
does not create the  `<link rel=”prefetch ...` in html as described in docs

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
