### ISSUE TITLE
server side rendering  webpack 4.6 prefetch/preload (dynamic imports)

### ISSUE THREAD

**Issue by IzaGz** [webpack/webpack#7740]
I use server sider rendering with nodejs.
I have view templates wich i render, in them for example i provide
`    <script type="text/javascript" src="/js/app.js"></script>
    <script type="text/javascript" src="/js/vendor.js"></script>
`
since webpack 4.6 there is a prefetch/preload that states to add the `<link rel=”prefetch ...`
Seems there is no description about how to deal with server side rendering cases.
Maybe somewhere it is emplemented or described in docs?
Because the webpack does not add the `<link rel=”prefetch ...` to the html , cant see any `prefetch` word in html elements in chrome .
Should it be implemented, or maybe there already some libs?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
