### ISSUE TITLE
monorepo with webpack

### ISSUE THREAD

**Issue by karaxuna** [webpack/webpack#7745]
I'm trying to create monorepo which will contain components that are built with typescript and sass. Folder structure looks like this:

    - packages
        - components
            - src
                - Slider
                    - Slider.ts (import 'Slider.scss')
                    - Slider.scss
                - Modal
                    - Modal.ts (import 'Modal.scss')
                    - Modal.scss
            - webpack.config.js
        - app1
            - src
                - index.ts (import Slider from `components/src/Slider/Slider`)
            - webpack.config.js
        - app2
            - src
                - index.ts (import Slider from `components/src/Slider/Slider`)
            - webpack.config.js

I want to use components in app1 and app2. What I tried is building components with `DllPlugin` and referencing it in app1 and app2 with `DllReferencePlugin`, it works well for typescript files, but what about scss, images, fonts and other assets? When building app1 or app2, I want their dist folder to include all assets from components. The reason why I'm not importing directly `components/src/Modal` without dll plugin is that components folder may have different webpack configuration like alias for example. What's the best practice for accomplishing this?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
