### ISSUE TITLE
dedupe module but have a single module instance

### ISSUE THREAD

**Issue by KeithWoods** [webpack/webpack#777]
I'm having some issues with a module (RX) that is required by my project and 2 of my projects dependencies, this is the setup:

    myProject
    -lib
    -node_modules
    -rx 
    -dependency1
    --node-modules
    ---rx
    -dependency2
    --node-modules
    ---rx

The problem is Rx is getting instantiated more than once. I thought I could use the dedupe plugin to get around this, while that does ensure only one module for RX is packed, it doesn't solve the mutiple instantiations. 

After reading some [discussions](https://github.com/webpack/webpack/issues/47#issuecomment-16060272) on deduping in webpack and checking out the [example](https://github.com/webpack/webpack/tree/master/examples/dedupe) I understand this is expected behaviour, it differs from npm dedupe for valid reasons (avoiding unintentional potential version bumping for one).

A problem with this approach (in this instance) is that Rx sticks itself at window.Rx, a typical usage of this library is to modify it's configuration adding new functionality. Given webpack will instantiate the module more than once, each time it blows away the existing window.Rx that has already been configured. 

Is there a way I can dedupe more in-line with npm's model whereby a single instance of Rx is used for my project and both it's 2 dependencies? 

Really appreciate any help, webpacks a fantastic tool, appreciate the effort put in. 

(I should mention the reason I don't just use npm dedupe is that these dependencies are in-house, and they exist in 'myProject's node_modules via sym links, i.e. 'npm link'. npm dedupe doesn't work with npm link)

**Comment by jhnns** [comment]
Symlinking your dependencies isn't a good idea either. You can install any git repository with npm. As long as git is able to clone the repository, you can also install private dependencies.

I don't think that webpack should also implement npm's dedupe mechanism. Usually you're using npm for that.

**Comment by sokra** [comment]
you can workaround this by aliasing `rx` to an absolute path `resolve.alias.rx = require.resolve("rx")`

**Comment by sonic78** [comment]
Thanks for getting back @jhnns. We're only using npm link in dev, it's allowing us to integrate packages, ironing out integration bugs. We'd then push them to our private npm repo. Once pushed they'd be 'npm install'ed as normal, at which point npm dedupe would work.

And again thanks @sokra. I can't get the aliasing to work, I've had to go for the absolute path as using a relative path doesn't work as it's relative to each file doing a require('rx'). I'm still using this with the dedupe plugin otherwise I get 2 instance of rx in the bundle (even with the aliasing in place).

    resolve: {
    	modulesDirectories: ['node_modules', 'libs', 'config'],
    	alias: {
    		"rx$": "C:\\myProject\\src\\Client\\node_modules\\rx\\dist\\rx.all.js"
    	}
    }, 
    ....
    plugins: [
    	...
    	new webpack.optimize.DedupePlugin()
    ]

At this point the deduped module rx still gets instantiated twice. I'll have to get a simple sample based of the dedupe example to demo this tonight, until then I'm going to put up with the 'npm publish, npm install' loop then use npm install with npm dedupe rather than npm link.

I'll get back with a sample as I want to figure this out, it's going to be a really common requirement to have multiple dependent packages that assume a single instance of a common dependency at runtime, more common perhaps for teams whos packages add functionality to other packages, i.e. augment angular or augment rx.

Thanks again for the help.

**Comment by jhnns** [comment]
@sonic78 I agree with you, it is pretty common and will be even more important when people start to split their monolithic apps into multiple parts. However, it's not really helpful that npm's folks are discussing about [deprecating `peerDependencies`...](https://github.com/npm/npm/issues/5080)

**Comment by sonic78** [comment]
That is a massive thread :). I think dedupe is their recommended preferred solution (haven't read it all) but logically that'd make sense). 

I haven't forgotten about getting this working, I've just not had time to figure it out. In any case it's not really an issue with webpack, more a feature, If I can't get to it by Monday I'll just close this updated any findings when I get around to it.

**Comment by quangbuule** [comment]
Have this issue been fixed? I have the same issue here.

**Comment by jsg2021** [comment]
Ditto. I have a project that when developing, the modules are linked in.  I cannot seem to keep my shared module from being instantiated multiple times.

**Comment by bebraw** [comment]
@KeithWoods Apparently Rx 4 should improve things. Is it safe to close this?

**Comment by bebraw** [comment]
Closing as Rx 4 is out there now. If relevant, feel free to open again.
