### ISSUE TITLE
Path aliases in tsconfig.json for TypeScript-powered Webpack configuration not working properly

### ISSUE THREAD

**Issue by ghost** [webpack/webpack#7800]
# Bug report

**What is the current behavior?**
Imports in TypeScript-powered configuration files relying on path aliases defined in the `tsconfig.json` cannot be resolved at all.

**If the current behavior is a bug, please provide the steps to reproduce.**
In my current project I do have most of my files in `Source/*` while storing multiple Webpack configuration files in `Webpack/*`. My global `tsconfig.json` in the root folder looks as follows:

```json
{
	"compilerOptions": {
		"moduleResolution": "node",
		"lib": ["es2017", "dom", "dom.iterable"],
		"target": "es6",
		"module": "commonjs",
		"sourceMap": true,
		"alwaysStrict": true,
		"noImplicitAny": true,
		"strictNullChecks": true,
		"esModuleInterop": true,
		"jsx": "react",
		"baseUrl": "Source",
		"paths": {
			"*": ["*", "../node_modules/*"]
		}
	},
	"include": [
		"Source/**/*",
		"Test/**/*",
		"Webpack/**/*",
	]
}
```

Unfortunately though the line `import * as constants from "Utilities/Constants";` is causing the following issue during runtime (however VSCode can properly resolve the dependency in the editor and does not complain at all):

```
Error: Cannot find module 'Utilities/Constants'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
	at Function.Module._load (internal/modules/cjs/loader.js:507:25)
	at Module.require (internal/modules/cjs/loader.js:637:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (D:\Source\electron-typescript-boilerplate\Webpack\webpack.config.base.ts:10:1)
	at Module._compile (internal/modules/cjs/loader.js:689:30)
	at Module.m._compile (D:\Source\electron-typescript-boilerplate\node_modules\ts-node\src\index.ts:439:23)
	at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	at Object.require.extensions.(anonymous function) [as .ts] (D:\Source\electron-typescript-boilerplate\node_modules\ts-node\src\index.ts:442:12)
	at Module.load (internal/modules/cjs/loader.js:599:32)
```

Surprisingly enough `import * as constants from "./../Source/Utilities/Constants";` works without any problem. So basically path resolution is wrong when executing either `webpack` or `webpack-dev-server`. Even manually prepending a `TS_NODE_PROJECT=\"tsconfig.json\"` as an environment variable does not work at all.

**What is the expected behavior?**
The import `Utilities/Constants` should be properly resolved to the `./../Source/Utilities/Constants` path and included rather than failing with the message that the module cannot be found.

**Other relevant information:**
webpack version:  4.16.3
Node.js version: 10.7.0
Operating System: Windows 10 Build 1803

**Further information:**
Adding `require("tsconfig-paths").register();` as the very first line in the base webpack config file however resolves this particular issue (even though I don't personally like it too much) but I get another one with `typings-for-css-modules-loader` which doesn't happen when using relative paths:

```
ERROR in ./Source/Styles.scss (./node_modules/typings-for-css-modules-loader/lib??ref--5-1!./node_modules/sass-loader/lib/loader.js!./Source/Styles.scss)
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
TypeError: query.substr is not a function
	at Object.parseQuery (D:\Source\electron-typescript-boilerplate\node_modules\loader-utils\lib\parseQuery.js:12:11)
	at Object.module.exports (D:\Source\electron-typescript-boilerplate\node_modules\typings-for-css-modules-loader\lib\index.js:54:37)
 @ ./Source/Styles.scss 2:14-152 21:1-42:3 22:19-157
 @ ./Source/App.tsx
 @ ./Source/Index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./Source/Index.tsx
```

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by NearAutomata** [comment]
@montogeek Unfortunately I couldn't strip everything and clean dependencies not related to the issue, so please excuse the size. You can find a "lightweight" repository with this issue [here](https://github.com/NearAutomata/webpack-typescript-paths-issue).

Once cloned run the following commands:
```
yarn
yarn run build-renderer-hot
```
This will start up the `webpack-dev-server` and you will see the first error message as described above referring to this particular line of code:

https://github.com/NearAutomata/webpack-typescript-paths-issue/blob/18afa6bf69a1c100127cae6fb5975fb42b39826b/Webpack/webpack.config.base.ts#L10

Keep in mind that this is not an error of the TypeScript compiler (otherwise it would've said that it cannot compile the file) but a Webpack issue.

**Comment by sokra** [comment]
The line you are talking about is in the configuration file, isn't it? Webpack uses ts-node to "run" it when it has the ts extension. This is not related to webpack. See also the stack trace of the error.

**Comment by NearAutomata** [comment]
@sokra The thing is that there would be a `TSError: ⨯ Unable to compile TypeScript` if the file to be imported cannot be properly resolved. So I am assuming that an initial pass of `ts-node` is in fact successful, but something along the lines of finally executing webpack with the imported config is not.

What do you suggest? Shall I attempt to reference this issue in the `ts-node` repository?

**Comment by NearAutomata** [comment]
@sokra I was just crawling through the issues of `ts-node` and according to [this issue](https://github.com/TypeStrong/ts-node/issues/634) `ts-node` is never resolving non-relative paths in the first place. Since this particular resolution works when bootstrapping `tsconfig-paths` as described at the end of my initial post I have to rely on that once I get an answer [over here](https://github.com/Jimdo/typings-for-css-modules-loader/issues/69) regarding the `typings-for-css-modules-loader` where all of a sudden the loader won't work.
