### ISSUE TITLE
Import an exception behavior of a module that uses `import()` internally

### ISSUE THREAD

**Issue by u3u** [webpack/webpack#7843]
# Bug report

**What is the current behavior?**

I am developing a vue plugin that is built using `@vue/cli` 3.0.0-rc.10. Additional features can be loaded via option options when installing the plugin (asynchronously loaded via `import()`).

If you import it using `<script>`, it will work fine.
But there was a problem when importing via webpack:

<img src="https://user-images.githubusercontent.com/20062482/43634012-9a4f4a4e-973d-11e8-8a14-1a0c5dcf9c8d.png" width="500">

Here webpack gets extra functionality by asynchronously loading the script element, but this file is not copied to `publicPath`, causing the file to not exist and cannot be loaded.

<img src="https://user-images.githubusercontent.com/20062482/43634320-57e1bc2c-973e-11e8-80d6-49667305fdf1.png">

**What is the expected behavior?**

I am not sure if the current behavior is expected, but I think it should be copied to `publicPath` and the module loaded correctly.

**Other relevant information:**
webpack version: v4.16.4
Node.js version: v9.11.1
Operating System: macOS High Sierra Version 10.13.6
Additional tools: -

**Comment by u3u** [comment]
`vendors~color-thief.js` and `color-thief.js` are resources in the installed third-party modules. This module uses `import()` to dynamically import them. When I import this third-party module, these two resources will be lost (they will not be packaged by webpack again).

@sokra 
Maybe I didn't describe it clearly, I don't know if you can understand what I mean. 😅

**Comment by u3u** [comment]
Related to these two issues: #2471, #6818

There seems to be no better solution at the moment, maybe the extra features should be manually imported by the user.

**Comment by sokra** [comment]
I don't understand the problem. Could you create an example repo?

**Comment by kezugo** [comment]
i've got exactly the same situation, the library im working on is using dynamic imports, after publishing it (with files option from package.json to publish all generated stuff from webpack) im not able to use the lib in different projects. I guess because chunks generated by webpack during dynamic imports cant be loaded from main.js file (entry point to the app). Im really keen to get to some information if somebody has made it working.

**Comment by gurupras** [comment]
I ran into the same problem as well. I did manage to find a 'solution' for it though.

@sokra If you can clone and `npm link` https://github.com/gurupras/svg-file-icons, you will find that webpack has cleanly generated JS files for a few hundred icons along with a `bundle.js` which is supposed to be the entry point.

If I now link this repo within, say, a VueJS project (you can do this within the `docs` directory of the same project)  and call `import FileIcons from '@gurupras/svg-file-icons'` in `App.vue`, it wont error out, but all dynamic imports referenced by the `bundle.js` will fail to load because they aren't being copied over by Vue's subsequent webpack build.

Currently, I managed to solve this issue by importing the source rather than the built umd result.
In my case:  
`import FileIcons from '@gurupras/svg-file-icons/src/file-icons'` works  
`import FileIcons from '@gurupras/svg-file-icons/dist/bundle.js'` will eventually 404 on dynamic import

The problem, however, is that this 'solution' *requires* the end-user to re-bundle.

**Comment by EvanBurbidge** [comment]
@gurupras I think we were speaking on stack overflow, I'm hitting this exact same issue. Is there no way anyones found to resolve the dynamic chunks within an external third party library?

**Comment by gurupras** [comment]
If re-bundling isn't an issue for you (given your description on [stackoverflow](https://stackoverflow.com/a/54320585/1761555), it may not be), you could always just import the sources rather than the built UMD as shown above.

If you don't like having to write something like  
```import { router } from 'superlib/long/internal/path/index.js```
just change the `main` of the library's `package.json` to point to the entrypoint rather than the bundled UMD. Once that's done, you can go back to using 
```import { router } from 'superlib'```

**Comment by EvanBurbidge** [comment]
@gurupras  yeah that seems to be the way i'll have to do it, i'm also utilising lerna hoisting in order to manage dependencies across packages.

**Comment by alex-ayala** [comment]
I have also been dealing on this and I was able to create an example repo that replicates this issue: https://github.com/alex-ayala/dynamic-import-issue.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by Mando75** [comment]
Just wanted to drop in and say that this is still a problem. I'm curious if anyone has found a better solution than just re-bundling the module like mentioned above. I think it is not an issue for most people to re-bundle, but it's rather annoying that it is required to deploy a package that way.

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/11127

**Comment by muke1908** [comment]
@alexander-akait Does it work out-of-the box? I am still not able to make dynamic import work from inside node_modules.

**Comment by tsi** [comment]
> Let's close in favor https://github.com/webpack/webpack/issues/11127

@alexander-akait I think the original issue here more resembles https://github.com/webpack/webpack/issues/6818 which is not resolved yet.
It's not about incorrect `pathAuto` but rather about missing the chunks in the consuming applications' build.

**Comment by zd819** [comment]
Hey, has anyone managed to find a solution for this?
My npm package I am developing uses dynamic imports and builds fine. When a consuming application uses the package, it also builds fine but in runtime when I use the package with the dynamic imports inside I always get an error of the form:
ChunkLoadError: Loading chunk 'X' failed
