### ISSUE TITLE
Unpredictable process.env.NODE_ENV

### ISSUE THREAD

**Issue by zwhitchcox** [webpack/webpack#7894]
So, everytime I've tried to create a bug report with webpack, everyone has been extremely rude/unhelpful, so I'm not going to put much effort into this. If anyone has any interest though (doubtful), they can check out the issue I made here: https://github.com/mui-org/material-ui/issues/12526

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
