### ISSUE TITLE
referring to a type without a variable 

### ISSUE THREAD

**Issue by lishengzhuang** [webpack/webpack#7903]
ERROR in Illegal State: referring to a type without a variable {"filePath":"E:/****/node_modules/ng-zorro-antd/antd.d.ts","name":"ɵet","members":[]}

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
