### ISSUE TITLE
Webpack 4 entry point requires leading ./ on Windows

### ISSUE THREAD

**Issue by thunderkid** [webpack/webpack#7919]
# Bug report

**What is the current behavior?**
Webpack 4 (on Windows 10 at least) is overly fussy about the format for the entry point. If I use:
`entry: 'ts/index.tsx'`
then I get the error message
`Can't resolve 'ts/index.tsx'`.
However, if I use
`entry: './ts/index.tsx'`
then it works fine.

I'd call this a bug and not a feature. Note that `HtmlWebpackPlugin` is not fussy in this way. So it's perfectly happy with 
```
        new HtmlWebpackPlugin({
            ...
            favicon: 'images/favicon.png'
        }),
```
Having different levels of format-fussiness in different parts of your `config.js` file is fragile and confusing. Note also that many people on #6858 have reported problems that may be caused by this (but I can't comment there as commenting's been locked...)

**Comment by thunderkid** [comment]
@montogeek:
Don't you think `'ts/index.tsx'` should just work too?

**Comment by sokra** [comment]
> entry: 'ts/index.tsx'

> entry: './ts/index.tsx'

These options have different meanings.

`ts/index.tsx` looks for a module called `ts` in `node_modules`.

It's similar to `import "ts/index.tsx"` vs `import "./ts/index.tsx"`

**Comment by myshov** [comment]
@sokra hi
First of all hank you for your hard work on the project!

I would like to add that using of relative paths in the config file feels counterintuitive. Because  we operate paths in terms of files there, but not in terms of module paths. AFAIK rollup don't force to use relative paths in configs.

I write this because I've tried to write config from scratch by memory (just for fun). And I stumbled upon on this small issue.
