### ISSUE TITLE
Child html-webpack-plugin for "index.html": 1 asset  Entrypoint undefined = index.html

### ISSUE THREAD

**Issue by DorisOu** [webpack/webpack#7925]
"webpack": "^4.16.5",
"html-webpack-plugin": "^3.2.0",
webpack.config.js:
const path = require('path');
const webpack = require('webpack');
const htmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
devtool: 'eval-source-map', //打包调试，生产环境需要去掉
    mode: "development",
    entry: './src/scripts/index.js',   
    output: {
        path: path.resolve(__dirname, 'dist'), 
        filename: 'js/[name]-[chunkhash].js',
    },
   plugins: [
        new htmlWebpackPlugin({
            filename: 'index.html',
            template: path.resolve(__dirname,'index.html'),
            title: 'webpack for test', 
            inject: false,
            minify: {
                removeComments: true,  
                collapseWhitespace: true  
            }
      }),
   ]
}

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
