### ISSUE TITLE
Error Module not found: Error: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by harishdrish123** [webpack/webpack#7929]
Hello all,

I am using hybride-crypto-js with webpack but getting below error:

ERROR in ../node_modules/hybrid-crypto-js/lib/keymanager.js
Module not found: Error: Can't resolve 'react-native' in '/home/hyper1/Sawtooth-projects/webpkdemoo/node_modules/hybrid-crypto-js/lib'
 @ ../node_modules/hybrid-crypto-js/lib/keymanager.js 1:0-42 30:8-20 40:8-20
 @ ../node_modules/hybrid-crypto-js/lib/index.js

Can anyone help me to solve this issue?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
