### ISSUE TITLE
Cannot find module './$RECYCLE.BIN/'

### ISSUE THREAD

**Issue by binler** [webpack/webpack#8006]
I'm using webpack 4.17.2. After run webpack, I run node and has error like this.
![image](https://user-images.githubusercontent.com/8288216/45197319-bebba680-b28a-11e8-8246-2a2f0e6afb71.png)
This is the first time I have seen such an error!
Help me!!!!

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
