### ISSUE TITLE
Production-Build with mapping-files

### ISSUE THREAD

**Issue by LeopoldLerch** [webpack/webpack#8007]
Hi,
I am using webpack 3, Typescript with awesome-typescript-loader. I would like to have a minified production build, but with Mapping-files. Somehow I am not able to force Mapping files for my ts(x) files when webpacking using "-p".

Any Help? I already added SourceMap: true to tsconfig as well as to the awesome-typescript-loader-options. But it had no effect. Using any configuration in devtool-option of webpack, the output is limited somehow to mapping-files of the node-modules-folder.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
