### ISSUE TITLE
Simpler API for custom jsonp loader

### ISSUE THREAD

**Issue by kornelski** [webpack/webpack#803]
I'd like to use `require.ensure`, but I have special requirements for loading chunks and I can't use the built-in jsonp loader (for offline support and to work around browser bugs I need to load JS from `localStorage`).

I "only" need to replace the few lines that create a new script and insert it to DOM, but replacing that bit seems like a rather a complex thing to implement (please correct me if there's a better way):
- I've written a custom function for `options.target` that invokes all usual webpack plugins (same as `WebpackOptionsApply`) except the `JsonpTemplatePlugin`.
- I've had to copy&paste&edit code of `JsonpTemplatePlugin` and `JsonpMainTemplatePlugin` plugin to modify the script loader part.

That already seems like a fragile hack — I'm duplicating webpack's built-in functionality and probably relying too much on implementation details.

There's another thing that has bitten me hard: `options.target == "web"` is magically special due to `defaultByTarget` in `WebpackOptionsDefaulter` and affects several other configuration options. This change in defaults was unexpected and has broken my build in subtle ways that were hard to debug.

Could you:
- add configuration option or a more direct plugin API for replacing the jsonp loader code?
- and/or make it easier to use custom `target` that extends behavior of `"web"`?
  
  For example you could make `target` an instance of a class that has properties/getters for the defaults, so then instead of:
  
  ``` js
  options.resolve.modulesDirectories = defaultByTarget(options.resolve.modulesDirectories,
      ["web_modules", "node_modules"],
  …
  ```
  
  it'd be something like:
  
  ``` js
  options.resolve.modulesDirectories = options.resolve.modulesDirectories || options.target.getDefaultModulesDirectories();
  ```

**Comment by jhnns** [comment]
Sorry for being a bit off-topic and I don't know if you can change your requirements, but I don't think that the `localStorage` is the right tool to save application code. It would be better if the application itself didn't know that it's cached offline.

We're using the Application Cache for that task and besides of [its horrible reputation](http://alistapart.com/article/application-cache-is-a-douchebag) it's working pretty well for us. It's very easy to generate the manifest from webpack's assets collection. There is also already [a plugin for that](https://github.com/lettertwo/appcache-webpack-plugin).

I can give you support on how to use the Application Cache in your app.

**Comment by pornel** [comment]
[We use appcache already](http://labs.ft.com/2012/08/basic-offline-html5-web-app/). We monitor how well it works for our users we're consistently seeing a long tail of users stuck with months-old versions of appcache. We've added the `localStorage` hack out of necessity, and I don't think we can drop it yet.

**Comment by sokra** [comment]
I try to consider this when refactoring it for error handling...

**Comment by pornel** [comment]
Thanks :)

**Comment by Taytay** [comment]
I stumbled across this because I too need to change the way the JsonpMainTemplatePlugin emits code. In particular, I need to add one line to it: `"script.crossorigin = 'anonymous';",`

We host our scripts on a CDN, and in order to have the browser pass complete exception information in window.onerror, we need to use CORS, and this "crossorigin" tag is essential. I was coming here to ask how to do it, and it sounds like @pornel has already gone down that road. 

I look forward to an easier way to override or tweak "built-in" behavior like that. 

P.S. Webpack is awesome. :)

**Comment by elliottsj** [comment]
FWIW, a plugin such as the following is a simpler way of overriding the `requireEnsure` function which inserts the `<script>` in the DOM to load the chunk:
```js
// webpack.config.js
module.exports = {
  // ...
  plugins: [
    {
      apply(compiler) {
        compiler.plugin('compilation', function(compilation) {
          compilation.mainTemplate.plugin('require-ensure', function(source, chunk, hash) {
            // `source` is the source code returned by the existing 'require-ensure' plugin,
            // e.g. from JsonpMainTemplatePlugin.js or NodeMainTemplatePlugin.js

            // e.g. surround the chunk-loading code with `'start';` and `'end';` string literals
            return this.asString([
              "'start';",
              source,
              "'end';",
            ]);
          });
        });
      }
    }
  ]
};
```

### `requireEnsure` before
```js
/******/ 	// This file contains only the entry chunk.
/******/ 	// The chunk loading function for additional chunks
/******/ 	__webpack_require__.e = function requireEnsure(chunkId, callback) {
/******/ 		// "0" is the signal for "already loaded"
/******/ 		if(installedChunks[chunkId] === 0)
/******/ 			return callback.call(null, __webpack_require__);

/******/ 		// an array means "currently loading".
/******/ 		if(installedChunks[chunkId] !== undefined) {
/******/ 			installedChunks[chunkId].push(callback);
/******/ 		} else {
/******/ 			// start chunk loading
/******/ 			installedChunks[chunkId] = [callback];
/******/ 			var head = document.getElementsByTagName('head')[0];
/******/ 			var script = document.createElement('script');
/******/ 			script.type = 'text/javascript';
/******/ 			script.charset = 'utf-8';
/******/ 			script.async = true;

/******/ 			script.src = __webpack_require__.p + "" + chunkId + ".client.bundle.js";
/******/ 			head.appendChild(script);
/******/ 		}
/******/ 	};
```

### `requireEnsure` after
```js
/******/ 	// This file contains only the entry chunk.
/******/ 	// The chunk loading function for additional chunks
/******/ 	__webpack_require__.e = function requireEnsure(chunkId, callback) {
/******/ 		'start';
/******/ 		// "0" is the signal for "already loaded"
/******/ 		if(installedChunks[chunkId] === 0)
/******/ 			return callback.call(null, __webpack_require__);

/******/ 		// an array means "currently loading".
/******/ 		if(installedChunks[chunkId] !== undefined) {
/******/ 			installedChunks[chunkId].push(callback);
/******/ 		} else {
/******/ 			// start chunk loading
/******/ 			installedChunks[chunkId] = [callback];
/******/ 			var head = document.getElementsByTagName('head')[0];
/******/ 			var script = document.createElement('script');
/******/ 			script.type = 'text/javascript';
/******/ 			script.charset = 'utf-8';
/******/ 			script.async = true;

/******/ 			script.src = __webpack_require__.p + "" + chunkId + ".client.bundle.js";
/******/ 			head.appendChild(script);
/******/ 		}
/******/ 		'end';
/******/ 	};
```

---

### Explanation
The `requireEnsure` function is added to the bundle in [MainTemplate.js#L83](https://github.com/webpack/webpack/blob/9162f9e6eea62137139f95b8aaedee335c870edd/lib/MainTemplate.js#L83). Since it's calling `this.applyPluginsWaterfall("require-ensure", /* ... */)`, we can simply add another plugin to the `this._plugins['require-ensure']`array (by calling `.plugin("require-ensure", /* ... */)`) to modify the return value. See also: [`applyPluginsWaterfall`](https://github.com/webpack/tapable/blob/88ec6f4f23b2efb95488f4ad1cbd1df09b688fdf/README.md#applypluginswaterfall).

[JsonpTemplatePlugin plugs into `"this-compilation"` to apply the `"require-ensure"` plugin to `mainTemplate`](https://github.com/webpack/webpack/blob/9162f9e6eea62137139f95b8aaedee335c870edd/lib/JsonpTemplatePlugin.js#L12-L16), so we can plug into the `"compilation"` step since it [runs after `"this-compilation"`](https://github.com/webpack/webpack/blob/9162f9e6eea62137139f95b8aaedee335c870edd/lib/Compiler.js#L398).

Then all we have to do is call
```js
compilation.mainTemplate.plugin('require-ensure', function(source, chunk, hash) {
  // Whatever you return here will be the body of the `requireEnsure` function
  return 'your-chunk-loading-code';
})
```

Still not quite ideal since it depends on internal details, namely `compilation.mainTemplate` and the `"require-ensure"` step, but it works.

**Comment by Karl-Gustav** [comment]
@elliottsj do you have a repo where this is setup and working?

**Comment by elliottsj** [comment]
@Karl-Gustav not anymore, unfortunately. Is my plugin example above not working anymore? There may have been some changes in recent webpack versions that could cause it to stop working, after all `compilation.mainTemplate.plugin('require-ensure', ...)` isn't quite a "public" API.

**Comment by Karl-Gustav** [comment]
@elliottsj I couldn't get it working, but that is just as likely me not fully understanding what i was doing. That was why I was wondering if there was some working examples anywhere 😄

**Comment by elliottsj** [comment]
@Karl-Gustav Here is an example; hope it helps!

https://github.com/elliottsj/webpack-require-ensure-plugin-example
