### ISSUE TITLE
Variable Definition not global accessible due webpack

### ISSUE THREAD

**Issue by xyNNN** [webpack/webpack#8033]
Hey folks,

I've a legacy JS file which define a global variable like in the following example.

`
var core_functions = function () {
}
`

I'm using webpack to bundle/build all my assets ... after that the browser throws an error that core_functions is not defined. How can I fix this error and tell webpack that this variable definition should be global (And yes, I know that this is not the best way).

Thanks in advance!

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
