### ISSUE TITLE
requireEnsure runtime missing (__webpack_require__.e is not a function) when an entrypoint has a dynamic AND regular import of a module which is also dynamically imported by a second entrypoint.

### ISSUE THREAD

**Issue by mbehzad** [webpack/webpack#8110]
# Bug report

**What is the current behavior?**
I have 2 entry points / bundles. Let's call them `A` and `B` they have some modules in common but are loaded on separate pages for example mobile/regular site or internal website / public facing website. therefor it makes more sense to have two dedicated bundles and no common chunk.
Bundle `A` has a dependency on Module `M` in form of a dynamic import i.e. `import("./M")` Bundle B has the same file with a dynamic import but also some regular imports of module M in other files i.e. `import M from "./M"`
when bundling A and B (config `splitChunks -> false` and default `optimization.runtimeChunk: false`). the B bundle has the `__webpack_require__.e(/*! import() | M */ "M")` code to request loading the M chunk. but misses the requireEnsure function (i.e. `__webpack_require__.e = function requireEnsure(chunkId) {`) in its runtime which is only present in the A bundle. And would result to a `__webpack_require__.e is not a function` runtime exception.
When removing the entry point for A from the webpack config, then instead of the requireEnsure call there is a Promise.resolve with the module M which was loaded for the reqular imports.
when removing the regular imports of the Module M from the B then the `requireEnsure` function definition is present in both bundles.
There is a workaround to use `optimization.runtimeChunk: "single"` and load the generated runtime with the requireEnsure part for both bundles. but i would prefer one js file to be generated and needed to be loaded.

**If the current behavior is a bug, please provide the steps to reproduce.**

A CodeSandbox with minimal setup to reproduce this issue and the results are provided under:
https://codesandbox.io/s/llplqpml2q
**What is the expected behavior?**
The B bundle should have Promise.resolve and reference to the already loaded Module M, even if another entrypoint is defined in the webpack config.

**Other relevant information:**
webpack version:  4.20.2
Node.js version: v8.4.0
Operating System:  windows 10
Additional tools: `
    "@babel/core": "7.1.0",
    "@babel/plugin-syntax-dynamic-import": "7.0.0",
    "@babel/preset-env": "7.1.0",
    "babel-loader": "8.0.3",`

**Comment by sokra** [comment]
hmm... you found a tricky bug...

Here is why this happens:

Technically module C should result in different code depending on which chunk/bundle is generated.

In A is should generate `__webpack_require__.e("M").then`
In B it should generate `Promise.resolve().then`

but we cache the generated source of each module so it only results in a single generated source, the first one, and the second chunk just reuses the cached source. This results in incorrect code generated.

Not sure what's best the solution for this. Always running code generation is probably a bad idea because of performance reasons. Always generating the `__webpack_require__.e` and ensuring chunk independent module code would an option. Tracking multiple variants per module is also an idea and may open up more possibilities...

**Comment by bitores** [comment]
**// This file contains only the entry chunk.
// The chunk loading function for additional chunks
 __webpack_require__.e = function requireEnsure(chunkId, callback) {...}**
