### ISSUE TITLE
Explore using urls instead of absolute paths in source-map 'sources' array

### ISSUE THREAD

**Issue by loganfsmyth** [webpack/webpack#8226]
## Feature request

I've been exploring improvements to the `source-map` library to bring it more in line with the source-map specification, and one of the things I've run into is the fact that Webpack expects tooling to use the absolute path as the entry in the 'sources' array.

This directly conflicts with the spec, in the case of Windows paths, because
```
C:\\some\directory\file.js
```
will just be parsed as a URL with `c:` being the protocol and a `pathname` as
```
\\some\directory\file.js
```
which is clearly not helpful.

**What is the expected behavior?**

The 'sources' entry should be a valid URL, either a relative path as a simple UUID, or as a absolute path to the file itself?

**What is motivation or use case for adding/changing the behavior?**

Bugs like
* https://github.com/postcss/postcss-loader/issues/390
* https://github.com/mozilla/source-map/issues/355

**How should this be implemented in your opinion?**

In a perfect world it seems like Webpack would slowly transition to supporting `file:` URLs in source-map `sources` so that loaders could output that, and checks like https://github.com/webpack/webpack/blob/945a9514ca23dfa3438df2ca7abd1238a2ea0c72/lib/EvalSourceMapDevToolModuleTemplatePlugin.js#L64 could perform a lookup based on that URL, and fall back to doing the looking based on `identifier`.

For instance, if loader added support for a `this.resourceURL`, they could transition to inserting the URL, if the property is present, and fall back to using the `resourcePath` for older Webpack versions.

For the example above for instance, the URL would be

    file:///C://some/directory/file.js

The downside here being that if some other loader in the chain wants to process the sourcemap and it expected the non-URL versions, they'll likely have issues and would also need to be updated to handle the `file:` URL implementation. I think that's acceptable though as long as loaders bump their major versions when switching to use the URL version.

**Are you willing to work on this yourself?**
possibly!

**Comment by sokra** [comment]
Seems like a useful change. As first step we can add support for `file://` urls when processing the source map. This seems like a non-breaking change to me. Do you want to send a PR?

webpack itself doesn't generate these SourceMap, they are coming from loaders. So loaders need to be changed too.

The SourceMaps webpack emits are defaulting to this name schema: `webpack://[namespace]/[resourcePath]` which should result in a valid url. Maybe we need to replace `\` with `/` here.

**Comment by loganfsmyth** [comment]
My concern at the moment is that, while adding support for the URL version in the `findModule` is a first step, no loader could adopt it without some indication from Webpack itself, unless they want to drop support for all previous versions of Webpack. That was my motivation for asking for something along the lines of `resourceURL`.

My thought was that, since Webpack essentially treats the 'sources' array like part of it's public loader API, it would make sense for Webpack itself to expose the value that it expects to receive in `sources`. This would also allow loaders to transition gradually without dropping support for older Webpack versions.

**Comment by justingrant** [comment]
Related: is the webpack:// URL scheme documented anywhere?  If not, then documenting the current scheme would be quite helpful (e.g. when authoring a custom function for `devtoolModuleFilenameTemplate` in order to work around upstream sourcemap problems) and would add value well in advance of any transition to a new URL scheme. 

Also, FWIW, the `info` argument that's passed into `devtoolModuleFilenameTemplate` functions is frustratingly insufficient. In particular, if upstream the absolute path is lost or corrupted, there's no way for the `devtoolModuleFilenameTemplate` function to know which path, module, or file (any of them!) generated the sourcemap.  Would be great to get more diagnostic/debugging details into the `info` argument!

**Comment by justingrant** [comment]
@loganfsmyth @sokra - Is this proposal moving forward?  A few questions/suggestions: 

1. In addition to (or instead of?) this proposal, should we also require `sources` paths to be relative URLs with no URL scheme?  Absolute paths (whether file:// URLs or native file-system paths) for a sourcemap are fragile in the face of different build-time vs. runtime environments. This is especially true for libraries that are bundled with webpack, because a library always must use relative paths because there's no way to know where on disk the library will be installed.  This doesn't have to be a hard prohibition-- it could be a warning. I think requiring relative paths and/or URLs could have a few advantages: 
   * Makes it easier for webpack-bundled libraries to emit correct sourcemaps by default
   * Avoids confusion between Windows drive letters and URL schemes
   * Probably reduces the work that most devs would need to do to adapt to the change, because relative paths and relative URLs for many files will be identical.
   * Makes sourcemaps a little smaller
   * Avoids the `webpack://` URI scheme which has long been a source of confusion, especially for devs who don't use webpack but see these URLs inside chrome dev-tools
   * By removing URL schemes from `sources`, will remove the temptation for devs to put HTTP URLs in sourcemaps, given that most existing tools probably won't support HTTP URLs.

2. Is there any reason to delay merging @volune's PR https://github.com/webpack-contrib/source-map-loader/pull/75 which enables `source-map-loader` to correctly process relative URLs?  It's been ready for 8 months waiting for maintainer review. ;-(  If our goal is to prevent absolute WIndows paths, having `source-map-loader` accept relative URLs seems important.

3. What should be the (relative) URL format for a source file that lives inside `node_modules`?  This would be helpful because (copying from https://stackoverflow.com/questions/56879619/relative-sourcemap-path-format-for-sources-inside-node-modules): 

> If this were a regular app bundle (not a library), then this wouldn't be a problem because the sourcemap could just use the absolute path to all source files. But because it's a library that won't know the path where it will be deployed, it must use only relative paths in its sourcemap. 
> 
> But the problem with relative paths to node_modules dependencies is that those paths are non-deterministic. For example, if I install `some-library` that has a dependency on `graphql` and `graphql` isn't installed already, then `npm install some-library` will install `graphql` in `./node_modules/graphql` (relative to my app's package.json). But if I've previously installed another version of the `graphql` library (e.g. as a dependency of a different library), then `graphql` it will end up in `./node_modules/some-library/graphql`.  This unpredictability means that there's no static relative path to `node_modules` within a sourcemap.
> 

BTW, if you have an opinion about which relative URL format should be used for this case in the current version of webpack, I definitely could use your advice!  

4. Will there be console warnings emitted if sourcemaps use non-URL paths?  If not, how will loader authors discover the need to make this change?

5. What will be the default URL used if users don't override `devtoolModuleFilenameTemplate`? Will it be a relative or absolute URL? Even if absolute URLs are allowed without a warning, for the reasons above it seems smart to emit relative URLs by default.

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
bump
