### ISSUE TITLE
Webpack require incompatibility with nodejs require

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#829]
I found this when including the [EventEmitter2](https://github.com/asyncly/EventEmitter2) library. This is their require statement:

    var EventEmitter2 = require('eventemitter2').EventEmitter2;

This works fine in Node/browserify, but in webpack EventEmitter2 will be `undefined`. EventEmitter2's main js is set up [like this](https://github.com/asyncly/EventEmitter2/blob/master/index.js):

    module.exports = require('./lib/eventemitter2');

For some reason Webpack doesn't include this step in the chain.

**Comment by sokra** [comment]
File this issue at the library. They export different stuff in AMD and CommonJs (https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L580-L588). Because webpack supports both and AMD is tried first you get a different result.

It's a bad design to thread AMD and CommonJS different.

---

You can workaround it with the imports-loader `import?define=>false`. see http://webpack.github.io/docs/shimming-modules.html#broken-amd

**Comment by DelvarWorld** [comment]
Hmm. I wonder how browserify gets around that. Thanks for the import tip!

**Comment by sokra** [comment]
browserify doesn't support AMD. So there is no problem here...

**Comment by wurmr** [comment]
I worked around this in my `webpack.config` with this module loader:

```js
{ // Turn off AMD module loading on eventemitter2
      test: /eventemitter2/,
      loader: 'imports?define=>false'
}
```

Not the cleanest, but works for now.

**Comment by mjw56** [comment]
Just ran into this exact same issue with EE2. Thanks @sokra and @wurmr as that solution worked like a charm.

**Comment by ScreenDriver** [comment]
Thank you @sokra and @wurmr. Something like that should be highlighted in the webpack docs.
