### ISSUE TITLE
Does resolve.alias support network addresses?

### ISSUE THREAD

**Issue by qq326943819** [webpack/webpack#8296]
The local is nice but network addresses can't work.

**Comment by qq326943819** [comment]
The local is nice but network addresses can't work.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by qq326943819** [comment]
so sorry
