### ISSUE TITLE
How to avoid the error of "webpackjsonp is not defined" using CommonsChunkPlugin

### ISSUE THREAD

**Issue by TongDaDa** [webpack/webpack#8346]
I have used the CommonsChunkPlugin, and I want to pre-load the preLoad.js before vendor.js, and main.js of loading, but as `vendor.js` belong to a common module and `webpack have to first load it`, so If I first load the preLoad.js through `HtmlPlugin sort`，the error happened that is webpackjsonp is not defined.

What do I want to do?
I only want the `preLoad.js` to depend on the plugin of the environment that is  Babel, and Webpack Splitting Code, and no other, but why must let the `vendor.js` as a first loading script?  I thought this  `vendor.js` file only contain these dependencies(react, redux...) for the property of "vender.js" in my entry.

plugins as follow:

``` javascript
   entry:{
        main:path.join(SRC_PATH,"main.js"),
        "vendor.js":["react","redux","antd","react-router","react-dom","react-redux"],
        preLoad: path.join(SRC_PATH, "preLoad.js"),
    },
 new webpack.optimize.CommonsChunkPlugin({
            filename:"vendor.js",
            name: "vendor.js", 
}),
```

**Comment by ooflorent** [comment]
`CommonsChunkPlugin` was buggy and hard to properly configure. For this reason it has been removed from webpack since version 4.0.0. I recommend you to upgrade your project to the latest webpack version so you no longer have to worry about vendor chunks.

---

It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by TongDaDa** [comment]
To upgrade webpack is my greatest scared thing...  That above my question, you don't understand?  @ooflorent

**Comment by TongDaDa** [comment]
Vnedor.js is my Loading Animations that is showing the <body> before loading the vendor.js because the size of file of vendor.js is not small, during its loading, I use the Vendor.js to showing loading Animation.

But now, just like above my question to saying, the preLoading.js will be loaded after the vendor.js had loaded. I don't want to do this, but there happened a `webpackjsonp is not defined ` of error.

@ooflorent
