### ISSUE TITLE
Error typing messages with typescript and react?

### ISSUE THREAD

**Issue by Dominic-Preap** [webpack/webpack#8390]
Is it OK with these error messages when I use `electron-webpack dev` with typescript and react?

![image](https://user-images.githubusercontent.com/14802170/48670387-d72d2480-eb49-11e8-9266-82268b0bcf00.png)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by Dominic-Preap** [comment]
Very sorry, I opened the issue on the wrong repo.
