### ISSUE TITLE
about loader

### ISSUE THREAD

**Issue by Lyd9607** [webpack/webpack#8396]
recently, when i saw the source code ,i could't find the file which have deal with the loader ,so i want to know which file and hook the loader has been used, thank u every much

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
