### ISSUE TITLE
write a loader seem wrong can you help me

### ISSUE THREAD

**Issue by ckrad** [webpack/webpack#8580]
```
module.exports = function (content, map) {
  return `
  import React from 'react';
  import ReactDOM from 'react-dom';
  import { AppContainer } from 'react-hot-loader';
  import App from '${this.resourcePath.replace(/\\/g, '\\\\')}'

  const render = (App) => {
    ReactDOM.hydrate(ENV_IS_DEV ? <AppContainer><App {...window.$$data} /></AppContainer> : <App {...state} />, document.getElementById('app'));
  };

  if (ENV_IS_DEV && module.hot) {
    module.hot.accept('${this.resourcePath.replace(/\\/g, '\\\\')}', () => { render(Entry) });
  }
  render(App);
  `;
};

```

i write a loader like this. but it seems to be wrong.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
