### ISSUE TITLE
HMR support for import() with non-constant request (implicit context)

### ISSUE THREAD

**Issue by Jessidhia** [webpack/webpack#8637]
## Feature request

**What is the expected behavior?**

`module.hot.accept(...)` where the first argument is the same as the first argument given to an `import()` should be able to work. Currently, as when the path is not static, it is actually compiled to a trampoline module (`ContextModule#getLazySource`, or `webpackAsyncContext` by default), and as there is no way to delegate HMR to parents, it is not possible to accept hot reloads from modules with dynamic paths.

It is technically possible to rewrite it in terms of `require.context` by using the 4th argument, but that loses features like the magic comments and has semantics closer to `require.ensure` instead of `import()`.

**What is motivation or use case for adding/changing the behavior?**

My use case: hot reloading of translations in development. The specific translation files loaded depend not only on the language setting, but also on the specific page's requirements (`namespace`s in i18next terminology), and the latter is a freeform string that corresponds to a filename.

For example, on a backend plugin that loads english:

```js
if (module.hot) {
  module.hot.accept(`./text/en/${namespace}.yaml`, () => {
    services.backendConnector.reload('en', namespace)
  })
}
return (await import(`./text/en/${namespace}.yaml`)).default
```

The accepted module id is a correct module id for the reloaded module, but there is a context module in between that prevents the hot reload from being accepted.

**How should this be implemented in your opinion?**

I'm... not sure. I'm not familiar with HMR internals. It'd probably require that context modules get some kind of special treatment by the HMR API, or require that a general purpose API be added to `module.hot` that could then be called by context modules to say that they are "not part of" the hot reloading chain of the given modules.

This could probably be made slightly easier by converting the context modules to ES modules.

**Are you willing to work on this yourself?**

Probably not, at least not now.

**Comment by Kovensky** [comment]
I was actually able to workaround this issue _for my specific use case_ by refactoring the specific function with the `import()`s into its own ES module and storing data about which languages/namespaces are loaded per instance in the module.

Moving the specific function that would do nothing but delegate to `import()s` to an ES module fixed the problem with `module.hot.accept` specifically -- it is now possible to accept that module and as it is a direct child it is a valid accept. It also fixed a runtime warning about a "disposed module" trying to import another module that I encountered when trying other fixes; as static ES module imports are live bindings they are always current with the hot reloaded module namespace.

The other part of the trick involved using a `Set` that's only defined when `module.hot` is enabled, to store which languages and namespaces were actually loaded at runtime. This `Set` is then iterated in the `module.hot.accept` callback to correctly reload the data for each instance.

(PS: this is kinda excessive but it's because the `i18n.reloadResources` API doesn't discard removed translations; so one needs to keep track of which resources were loaded to be able to throw them out and then reload them. This does cause a flash of untranslated text but it's HMR only so meh.)

**Comment by Kovensky** [comment]
Did webpack support `import.meta.hot`? If it does it's great (and I should add type definitions for it to `@types/webpack-env`) but that's not quite the issue at hand.

Anyway, the specific issue is kinda about the ergonomics of hot reloading dynamic imports.

First, unlike static imports, dynamic imports have to be re-imported to get access to the new bindings. Second, when the import is a dynamic string, an intermediate context module is created behind the scene -- this means that the imported module is not a direct child of this module, but an indirect descendant.

This is basically a duplicate of https://github.com/webpack/webpack/issues/834 but, unlike in the original issue, there is no way to get access to the intermediate context to be able to accept it. Even if there would be, it would have the same caveat as the one I mentioned in my solution post -- any change to any module that is fulfillable by the context would invalidate all children of the context, not only the children that actually changed.

**Comment by Kovensky** [comment]
Yeah, an `import.meta.hot` wouldn't fix this issue but it'd get rid of some of the "commonjsness" of accessing `module.hot`. AFAIK even in `javascript/esm` files it happens to work because the plugin looks for the `module.hot` expression itself, erasing it before there is an error due to `module` being `undefined` there.

**Comment by sirlancelot** [comment]
Could this be solved by making all immediate children of the generated context also children of the generated context's parent?

My simple scenario:

```js
// File: @/lang/index.js

async function fetchMessages(locale) {
  const module = await import(/*
    webpackChunkName: "lang/[request]",
    webpackExclude: /index/
  */ `@/lang/${locale}`)
  return module.default
}

if (process.env.NODE_ENV !== "production" && module.hot) {
  module.hot.accept("@/lang/en-US", () => { /* ... */ })
}
```

The HMR service doesn't see this callback because the file "en-US.js" is not a direct descendant of "index.js" as there is the generated async context between them.
