### ISSUE TITLE
error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by chandu89** [webpack/webpack#8661]
When I am adding Webpack merge, I am getting error.
I have  created separate webpack config for devlopment and prod.
> error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencies

Can Anyone help me on this?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
