### ISSUE TITLE
When hot-reload on webpack, worker file doesn't apply

### ISSUE THREAD

**Issue by Junyong34** [webpack/webpack#8665]
![image](https://user-images.githubusercontent.com/25451713/51513729-b639c600-1e4f-11e9-9271-5a55a8e9e2c1.png)

If you import to 1 and modify the worker file,
If you import to 2, reloading will not work and the changes will not be reflected.

Can you tell me why?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
