### ISSUE TITLE
build hangs

### ISSUE THREAD

**Issue by galkinrost** [webpack/webpack#867]
Hi, all!
I've tried to build project with usage of lessjs library (https://github.com/less/less.js/)
When i use dist file webpack report a warning:

```
 WARNING in ./~/less/dist/less.js
    Critical dependencies:
    13:435-442 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
     @ ./~/less/dist/less.js 13:435-442
``` 
But when i try to include CommonJs module it hangs without any output.

Versions:
less 2.4.0
webpack 1.7.2

**Comment by jhnns** [comment]
You should `require()` your LESS files with the [less-loader](https://github.com/webpack/less-loader) instead of adding the LESS runtime to your application. Thus your LESS files are compiled once instead of compiling it for every user.

**Comment by galkinrost** [comment]
I need to recompile less in my application. So i have to include less-js library in the app

**Comment by galkinrost** [comment]
May be there is any way to ignore the warning?

**Comment by jhnns** [comment]
`Critical dependencies` is not a warning that should be disabled. It's usually caused by dynamic `require()` expressions and will be turned off by default starting with webpack 2.0. See discussion on dynamic dependencies https://github.com/webpack/webpack/issues/845#issuecomment-77030660

It's probably caused by [these lines](https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/dist/less.js#L13). Try to alias `less` with [`less/lib/less-browser/index.js`](https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less-browser/index.js) instead.

**Comment by galkinrost** [comment]
The alias `less-browser` hasn't such functionality that I need, but this one  <a href="https://github.com/less/less.js/blob/6fd2a5751cc8313481913bcb1623bf6c50089df8/lib/less/index.js">less/lib/less/index.js</a> has. Thank you very much for your help!
