### ISSUE TITLE
How can I add debugging for json-loader? 

### ISSUE THREAD

**Issue by NikolaySolodukhin** [webpack/webpack#8733]
How can I add debugging or logging for json-loader in webpack 4? 
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
