### ISSUE TITLE
Webpack should have a way to ignore `require` calls

### ISSUE THREAD

**Issue by sindresorhus** [webpack/webpack#8826]
# Bug report

**What is the current behavior?**

Webpack tries to handle all `require()` calls, even those not meant for browser usage. This makes it almost impossible to have a module that works in both Node.js and the browser, but has some added capabilities in Node.js.

Note that this is about authoring reusable npm packages, not end-user apps. I don't have the ability to set any Webpack config like the `externals` option since I'm making packages other devs will consume.

This is the kind of awfulness we have to do because of Webpack: https://github.com/sindresorhus/ow/blob/d62a06c192b892d504887f0b97fdc842e8cbf862/source/utils/node/require.ts We have wasted countless of hours on this.

Prior discussion that went mostly ignored by the Webpack team: https://github.com/webpack/webpack/issues/196#issuecomment-354900072

**What is the expected behavior?**

I expected to be able to annotate the code to make Webpack ignore certain `require()` calls.

For example with a comment:

```js
const require('chalk'); // webpack-ignore
```

I know for certain that this `require()` call will not be used in the browser, so I should be able to have it in my source code without Webpack printing warnings to users or erroring out.

I need this as a module maintainer (not user).

Telling users to use the `externals` config is out of the questions, as my package might be a dependency many levels down.

Some more examples of where I have to use awful code to work around Webpack:

- https://github.com/sindresorhus/file-type/pull/187/files#diff-168726dbe96b3ce427e7fedce31bb0bcR923

**Other relevant information:**
webpack version: 4.29.0 (applies to any version though)
Node.js version: 10.15.0
Operating System: macOS 10.14.3
Additional tools:

**Comment by SamVerschueren** [comment]
I totally agree, the current solution is ugly and silly. There should be an easier way to work around this problem...

**Comment by wmertens** [comment]
I use `_non_webpack_require` for this. Before I found out about that I had an external named `nodeRequire` that pointed to the global `require`

**Comment by jhnns** [comment]
Hi @sindresorhus 👋,

thanks for raising this issue. I agree that it must be annoying for you as a maintainer to get these kind of issues. However, I don't think that webpack is to blame for this either. Dynamic imports is something no bundler is able to handle in a good way. If webpack did not print out a warning for dynamic requires, people might get "Could not find module xyz" *on runtime* which is worst imo.

I see the magic comment as a last resort because it's webpack specific. I would like to have something that works with all bundlers.

The [`browser` field in the `package.json`](https://gist.github.com/defunctzombie/4339901) is something that all bundlers respect. So you would have two entries in your module, one that is intended for browsers and one that is intended for node. Then you would require all node-only dependencies in your `main` entry. Imo electron should add this kind of package switch too because it's less error prone than looking for some magic global variables that are only available in certain environments. Why is that package switch not working for you?

**Comment by sindresorhus** [comment]
> However, I don't think that webpack is to blame for this either. Dynamic imports is something no bundler is able to handle in a good way.

This is not about dynamic imports.

> If webpack did not print out a warning for dynamic requires, people might get "Could not find module xyz" on runtime which is worst imo.

No, they would not get "Could not find module xyz" at runtime because the require call would be behind a conditional that is never hit in the browser. I'm asking for a way to tell Webpack to ignore a `require()` call because I know best. When automatic behavior fails, we should be able to override it.

> I see the magic comment as a last resort because it's webpack specific. I would like to have something that works with all bundlers.

The `browser` field in package.json is not a standard either. We could come up with a universally recognized magic ignore comment.

> The browser field in the package.json is something that all bundlers respect.

Do you have a source for that assertion? Can you point me to the Webpack docs about the `browser` field?

> So you would have two entries in your module, one that is intended for browsers and one that is intended for node. Then you would require all node-only dependencies in your main entry.

You're asking me to massively refactor my codebase to support Webpack. It's not as easy as *just* using the `browser` field. It would mean creating entry points that can easily be swapped out. It's not always that simple.

All I want is to make Webpack ignore a `require` call that is not used in the browser...

**Comment by jhnns** [comment]
> This is not about dynamic imports.

That's correct, but dynamic and conditional imports have similar limitations.

> No, they would not get "Could not find module xyz" at runtime because the require call would be behind a conditional that is never hit in the browser.

That depends on the quality of the conditional. But I'm sure that you would get it right 😉 

> Do you have a source for that assertion? Can you point me to the Webpack docs about the browser field?

No, that's just my experience. It's widely adopted in the NPM ecosystem afaict but I have no stats for it. We have no dedicated page for module authors in our docs, but if you're looking for the issue number: https://github.com/webpack/webpack/issues/151

> You're asking me to massively refactor my codebase to support Webpack. It's not as easy as just using the browser field. It would mean creating entry points that can easily be swapped out. It's not always that simple.

That's true: it's not an easy refactoring. But again, it's not only to support webpack. Other bundlers might just have decided to ignore occurrences of `require()` they don't understand, which is not ideal as well.

While I personally think that every code base would benefit from this refactoring, I do understand that it's not feasible for module authors with existing code. So I see the use case. How would that comment look like?

```js
require(/* ignore */ "./something.js")
```

This would be similar to:

```js
import(/* webpackChunkName: "something" */ "./something.js")
```

I guess the `ignore` comment would only work for CommonJS `require()` and dynamic `import()`.

Would do other bundler maintainers think about this? @lukastaegert @devongovett @goto-bus-stop

**Comment by goto-bus-stop** [comment]
For the `"browser"` field, most popular bundlers support [excluding dependencies](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module):

```json
"browser": {
  "chalk": false
}
```

AFAIK, browserify, webpack and rollup all support this. If Parcel uses browser-resolve it supports it too (not sure). Meteor doesn't support it, last I checked.

Browserify intentionally ignores dynamic requires entirely, so you can do `require('ch' + 'alk')`. This is a semi common thing to do in cryptography related modules in the browserify ecosystem, usually they'll do `require('cr'+'ypto')` in node and use browser APIs in the browser. Browserify also doesn't track aliasing so you can do `nodeRequire = require; nodeRequire('chalk')`.

For webpack, ignoring dynamic requires is probably not an option… I don't know of any use case for aliasing though aside from this, so that might be on the table?

But ideally, the `browser` field object form (w|c|sh)ould be used for this :)

**Comment by lukastaegert** [comment]
The `browser` field seems well documented to me: https://github.com/defunctzombie/package-browser-field-spec

Personally, I am not a fan of introducing a new universal annotation when we have something that is already widely adopted. The `browser` field also supports replacing or ignoring very specific imports. For rollup, this is solved by providing a dummy file with an empty object as default export in those cases.

Otherwise as we do not natively support dynamic require but only dynamic imports, those are handled rather permissively: If they cannot be resolved at runtime they will be left in the code unchanged, which should not be an issue if the code is never run. I plan to at least print a proper warning when a dynamic import that is just a string cannot be resolved, similar to how we handle unresolved static imports (a warning telling you that we assume this is external). However, I would only print this warning in case the dynamic import is not tree-shaken anyway. To me it seems that at least some parts of this should be solvable via tree-shaking.

**Comment by sindresorhus** [comment]
For anyone else encountering this issue and need a workaround, this is probably the best one: https://twitter.com/kamilogorek/status/1102272038411137025

**Comment by TheLarkInn** [comment]
@sindresorhus There's no doubt your contributions to the NodeJS/Isomorphic JS ecosystem is considerable. 

The more bundle-able modules are the more positive impact to your modules consumers. So its really important to us, to help you make this easier! 

You have the maintainers of Rollup (@lukastaegert), Browserify (@goto-bus-stop), and webpack here all verbally in support of the standard that exists today with the browser field. 

Is there maybe a hotlist of "most requested" modules you own that would need considerable refactoring? As far as I'm concerned we could all try and pitch our respective contributor ecosystems to help PR this code for you! (If you are willing).

We're in it together <3 🤗

**Comment by devongovett** [comment]
In parcel at least, you can also do this:

```javascript
if (process.browser) {
  require('./browser');
} else {
  require('./node');
}
```

Not sure about other bundlers.

**Comment by TheLarkInn** [comment]
We can do similar, but does this error in Browser ENV for non bundler using consumers? That's my guess why that isn't the most feasible.

**Comment by lukastaegert** [comment]
It will also error when bundled vanilla Rollup as we do not polyfill globals by default (which is partly because otherwise we would mess up those patterns when bundling for libraries, though).

**Comment by TheLarkInn** [comment]
We do like leveraging `process` however this may cause optimization bailouts for our users inside deep module graphs because we do mock injections on `process` standalone. We do leverage `process.env.NODE_ENV` but looks like @lukastaegert mentioned it is problematic still.

**Comment by devongovett** [comment]
Parcel inlines `process.browser` similar to how we inline `process.env.NODE_ENV`. When collecting dependencies, we check if they are inside a falsy branch, and ignore if so (leaving `require` as is). This applies to any branch, including `process.env` comparisons and `process.browser` checks, but also any other code we can evaluate statically. Since `process.browser` is inlined, we don't include the process runtime at all unless other process features are used.

**Comment by TheLarkInn** [comment]
@devongovett That's interesting, perhaps when we use the `target` [feature](https:/webpack.js.org/configuration/target), maybe we should also have a `process.target` or `process.env.target` inlining. I guess it doesn't solve the "people of non bundler" use cases though right (in the browser scenario?).

**Comment by devongovett** [comment]
Yeah non-bundler people would be a problem, but if you're using `require` it wouldn't work in a browser anyway right?

**Comment by TheLarkInn** [comment]
@devongovett Haha I told myself the same thing, but a great example is at Microsoft we have some legacy teams using requireJS, and therefore still can consume require's yet get that kind of `process.whatever` code and it nukes. 

Not a deal-breaker for the majority, but a consideration haha.

**Comment by martonx** [comment]
There are cases where there is 3rd party requirejs on a site, and our webpack bundle should run on these sites, using the 3rd party requirejs's require function. In this case we have to be able to ignore webpack require, and use the external require function.

**Comment by techhead** [comment]
> For anyone else encountering this issue and need a workaround, this is probably the best one: https://twitter.com/kamilogorek/status/1102272038411137025

This is what I ended up going with for doing a conditional import in the NodeJS environment.

```javascript
const nodeVer = typeof process !== "undefined" && process.versions?.node;
const nodeRequire = nodeVer
  ? typeof __webpack_require__ === "function"
    ? __non_webpack_require__
    : require
  : undefined;
```

Webpack will optimize away the bare `require` in this case so that you don't end up with the ugly warning below (and extra code injected).

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by sokra** [comment]
To close up this issue:

**Do not** try to workaround webpacks parser to create node-only `require()`s!

Do use the `browser` field in package.json to differ between environments. See also @jhnns comment about that: https://github.com/webpack/webpack/issues/8826#issuecomment-469197689

In future you may also use the `exports` field in package.json.

Creating parser hacks has multiple disadvantages:
* It may break when the parser becomes smarter
* I breaks bundling for node.js usage
* It includes unneeded code for browser usage
* Future tools have to emulate the way this stuff is parsed to be compatible.
  * We also had to add hacks to support hacks people did for browserify

A webpack ignore has also multiple disadvantages:
* It's webpack-specific and breaks other bundlers (or they have to support webpack ignore too, which would be weird)
* I breaks bundling for node.js usage
* It breaks when minimized and comments are removed

**Comment by wmertens** [comment]
@sokra but how to require something at runtime in a bundle that was created by webpack?

**Comment by evilebottnawi** [comment]
@wmertens You can bundle something by webpack/other tool, and use `externals`

**Comment by msklvsk** [comment]
What about this use case?
```ts
import Config from '../config' // use a sample/dev config for free typings

function main() {
  const config = require(process.argv[2]) as typeof Config
  // ...
}
```
`externals` can’t handle this.

**Comment by dvcrn** [comment]
So what was the conclusion here? To use `browser` in the package.json? 

I am still running against a wall with third-party node modules that have a 

```
if (!inBrowser) {
  foo = require("bar");
}
```

in them, which give me a "module not found" error on build. I added the `browser` field to my package.json as well:

```
  "browser": {
    "foo": false,
  },
```

So how to solve this? I could fork all the modules that have this and manually patch them but it would be much easier if I could just dummy-out this require because it would never get hit due to the conditional `if`

**Comment by sokra** [comment]
You can also do the same in config

`resolve.alias.bar: false`

You can do that globally or inside of `module.rules` to only affect certain modules

**Comment by dvcrn** [comment]
@sokra thanks for the quick reply! I tried that method already but without luck - I'm still getting the "Module not found" errors (it also complained when I tried to set it to `false` that the value has to be of type string for aliases). 

Using `create-react-app` with `craco` here to modify the webpack config. 

Another thing I tried without luck was setting `"paths"` in package.json. 

The modules I'm trying to nop-out are `worker_threads` and `crypto`

**Comment by sokra** [comment]
Seems like you are using webpack 5 and that's only available for webpack 5.

Try this instead: `externals: { crypto: "var {}" }`

**Comment by dvcrn** [comment]
Yes you're right, `create-react-app` still uses webpack 4. 

Using `externals` in the webpack config solved it for me, it's building now! Thanks for the quick help!

**Comment by JounQin** [comment]
> What about this use case?
> 
> ```ts
> import Config from '../config' // use a sample/dev config for free typings
> 
> function main() {
>   const config = require(process.argv[2]) as typeof Config
>   // your `config` is typed
>   // ...
> }
> ```
> 
> `externals` can’t handle this. (Nothing browser here, node-only.)

@msklvsk If you just want webpack bundles correctly, you can use [`__non_webpack_require__`](https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific), if you want it also works from source, there is a hack pattern from `prettier`: `eval('require')('your-dep')`(You'd better replace this hack back after compiling).

**Comment by ravimaharjan** [comment]
https://www.npmjs.com/package/webpack-ignore-dynamic-require

**Comment by hkjpotato** [comment]
> Yes you're right, `create-react-app` still uses webpack 4.
> 
> Using `externals` in the webpack config solved it for me, it's building now! Thanks for the quick help!

@dvcrn can you share how you add "externals" in create-react-app? It seems no easy way to modify the webpack configs.

**Comment by dvcrn** [comment]
@hkjpotato I'm not at my machine right now so I can't check the full code but we're using craco to override webpack configuration. Something like this in craco config (copied from a different github issue):

```
module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      webpackConfig.externals = {
        react: 'React',
        'react-dom': 'ReactDOM'
      }
      return webpackConfig;
    }
  }
}
```

**Comment by rdsedmundo** [comment]
In need of this 5 years on. Coincidentally it was for the `chalk` module as well, which used only during tests. I don't get why it's possible to do for a dynamic `import` call with `/* webpackIgnore: true */` but not with `require`.

**Comment by alexander-akait** [comment]
@rdsedmundo Due perf reasons, but it works if you set https://webpack.js.org/configuration/module/#moduleparserjavascriptcommonjsmagiccomments
