### ISSUE TITLE
Building Dojo with webpack

### ISSUE THREAD

**Issue by jacowley** [webpack/webpack#890]
When I try to use webpack to build a Dojo AMD-based application with Dojo 1.10.4 I get the following error:

```
/Users/jcowley/git-src/webpack-test/node_modules/gulp-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:204
                                        throw e;
                                              ^
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/jcowley/git-src/webpack-test/web/legacy/bower_components/dojo/i18n.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at DependenciesBlock.loadPitch (/Users/jcowley/git-src/webpack-test/node_modules/gulp-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:191:17)
    at DependenciesBlock.doBuild (/Users/jcowley/git-src/webpack-test/node_modules/gulp-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:239:4)
    at DependenciesBlock.build (/Users/jcowley/git-src/webpack-test/node_modules/gulp-webpack/node_modules/webpack/lib/NormalModule.js:66:14)
```

Is building Dojo with webpack a known problem or is there something special I need to do?

Thanks.

**Comment by whymarrh** [comment]
I too would like to know the answer to this, is this an issue with Dojo somehow having its own loader?

A reduced test case (of sorts) is [available as a Gist here][1]. You can run:

    npm install && npm run webpack

  [1]:https://gist.github.com/whymarrh/532497deaece4530872b

**Comment by sokra** [comment]
Looks like dojo uses something like `i18n!` in a request...

**Comment by jacowley** [comment]
I think it is because Dojo's loader plugins are evaluated at build time. I managed to get further through the build by using https://github.com/jrburke/amdefine in the Dojo plugins. However I still got an error at some stage because the some of the plugins refer to document if I remember correctly.

**Comment by wmfeht** [comment]
Dojo makes extensive use of loader plugins at runtime, in the case of i18n! it is loading the appropriate internationalization package at runtime. At build time, a runtime plugin can perform its own optimization. (for example, dojo/text inlines a text file to a string similarly to webpack's html or file-loaders).

The issue here is whether or not supporting the full AMD specification (https://github.com/amdjs/amdjs-api/wiki/Loader-Plugins) is important for webpack. If left unimplemented, it makes migrating some large requirejs and dojo projects to webpack impossible.

**Comment by leth** [comment]
Does anyone know a good workaround for this?
The options that spring to my mind are:
- not webpacking dojo
- writing a custom loader

Are either of those infeasible? It's the end of the day and I'm pretty certain I've not grokked the full implications of either of them yet.

**Comment by whymarrh** [comment]
@leth I looked into this quite a bit as well and gave up on trying to get webpack to work with Dojo. I regret not writing up the process, but I eventually ran into #439 and ended up using the [Dojo build system](https://dojotoolkit.org/reference-guide/1.10/build/) instead. Though if you're set on using webpack, option 1 might work (e.g. loading Dojo from a CDN, and having webpack deal with everything else).

**Comment by wmfeht** [comment]
@whymarrh Unfortunately Dojo is used for a lot of large internal applications and embedded control panels (think web-based control panel for a router), this makes downloading from a CDN impractical. Also, Dojo is about ~30-40MB of loose files, of which only a small portion get used in any given app, making a build step which includes the framework necessary.

The build system is very similar in concept to webpack, which is why attempting to use webpack to migrate older applications to use ES6 modules and npm for dependency management is so appealing (but currently impossible).

How hard would it be to detect an AMD plugin and treat is as a module with a custom build step instead of a loader plugin?

**Comment by whymarrh** [comment]
I do remember looking into exactly what you're describing (amongst other things). I don't remember the process I went through nor all the issues I encountered, but *I* wasn't able to get it working. That's not to say that it's impossible or that it's not worth exploring again, but #439 is an example of what you may encounter. Also, since Dojo uses AMD I would take a look through [the open AMD-related bugs](https://github.com/webpack/webpack/issues?utf8=✓&q=is%3Aopen+is%3Aissue+label%3Abug+amd) to see if any of those will be blockers as well. (If you do end up figuring it out, please do share it, whether it be as [an answer on Stack Overflow](http://stackoverflow.com/q/29134254/1267663) or your own method.)

As for the Dojo build system, you can still use an ES6 transpiler and npm for dependency management, albeit with an workflow adjusted to meet Dojo's requirements.

**Comment by bebraw** [comment]
@jacowley Any luck with this? Has the situation changed?

**Comment by kvcrawford** [comment]
FYI: @nordth wrote https://github.com/Nordth/dojo-webpack-loader

**Comment by bebraw** [comment]
Closing as there's a loader now.

**Comment by chuckdumont** [comment]
There's also https://github.com/OpenNTF/dojo-webpack-plugin which offers:

*    Support for Dojo loader config properties, including baseUrl, paths, packages, map and aliases
*    Support for client-side synchronous and asynchronous require() calls for packed modules.
*    Webpack loader implementations of standard Dojo loaders (e.g. dojo/has, dojo/i18n).
*    Limited support for client side execution of some Dojo loader extensions.

**Comment by jslegers** [comment]
What about RequireJS plugins like `requirejs/text` (which is similar to `dojo/text`)?
Is there any way Webpack can handle those?!

See also https://github.com/webpack/webpack/issues/5735.
