### ISSUE TITLE
Can I use webpack as a build tool ?

### ISSUE THREAD

**Issue by szrenwei** [webpack/webpack#892]
I found that webpack only bundle the files that has a reference in javascript; how about other files? Must I still need to use gulp together? Is there a way or example to show how to manage all my static files? Thanks.

**Comment by jhnns** [comment]
Yes, webpack is essentially a build tool. Other files are processed with [loaders](http://webpack.github.io/docs/loaders.html). Also check out [this great tutorial](http://christianalfoni.github.io/javascript/2014/12/13/did-you-know-webpack-and-react-is-awesome.html) by @christianalfoni

**Comment by sokra** [comment]
webpack manages all files that are part to the dependency tree. It doesn't just copy files.

**Comment by szrenwei** [comment]
Thanks. 

But sometimes I don't want to add all my files to the dependency tree. For example, I have a css file, but I don't want to load it by js. So webpack won't manage it( give it a hash name...etc ). I had use webpack with gulp to achieve this.

**Comment by christianalfoni** [comment]
Hi @szrenwei !

Remember that you can lazy load anything also. So if you have some CSS you do not want to load with the initial payload you can:

*main.js*
```js
require.ensure([], function () {
  require('./myCSS.css');
});
```

Webpack does automatically for you. Just use `require.ensure` instead of require. Without having the experience to back this completely, I do think you can make webpack handle or your static assets. Its more a matter of "when" and "how much" do you want to load, not "how" to load it. 

Lets say a different scenario, you want to load some initial CSS before loading the main bundle. Just do:

*main.js*
```js
require('./mainCSS.css');
require.ensure([], function () {
  require('./app.js');
});
```

**Comment by jhnns** [comment]
And if you want to serve the CSS separately because it should be downloaded with the initial chunk in parallel, you can use the [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin)
