### ISSUE TITLE
Make output easier to profile

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#900]
I'd like to be able to more easily understand Chrome's JS profile flame charts. Unfortunately, webpack uses anonymous functions all over the place so it is difficult to see what is calling what because just about everything is named `(anonymous function)` or `fn`. Here's a screenshot of what I am looking at:

![screen shot 2015-03-20 at 7 09 05 am](https://cloud.githubusercontent.com/assets/195534/6750424/76309aa2-ced0-11e4-9d15-9cad7a5ff158.png)

Would you be open to a pull request that names some of these functions? This might also help out #824 a little.

**Comment by jhnns** [comment]
That's because every module is wrapped into an anonymous function closure. Depending on different loaders, there might even be more IIFE.

I think, that's a good idea. The function names are stripped-out by minifyers anyway. The only problem I see is, that we could potentially hide global variables. Thus we need to prefix the IIFEs involved.

What do you think @sokra?
