### ISSUE TITLE
guidance for node-only libraries being consumed by webpack

### ISSUE THREAD

**Issue by daprahamian** [webpack/webpack#9049]
A few weeks ago, a change in the [`mongodb`](https://www.npmjs.com/package/mongodb) project caused errors for users of webpack (you can see more details [here](https://jira.mongodb.org/browse/NODE-1925))

`mongodb` is fundamentally a node-only library, and is not meant to be run in a browser environment. We had assumed that users would not try to run the library through `webpack` since it could be run in node, but there appear to be some frameworks that automatically bundle server-side files for their users (ex: [now.sh](https://zeit.co/now))

Is there any guidance for packages that are only meant to run in node being webpack-d? Is there a way to mark on the library-side that a package should not be bundled? Or is there a common extension that we can refer users to?

Thank you for your time.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue as closed

> Is there any guidance for packages that are only meant to run in node being webpack-d? Is there a way to mark on the library-side that a package should not be bundled? Or is there a common extension that we can refer users to?

What do you mean? Why this library can be bundled? Can you create minimum reproducible test repo for investigation?

**Comment by TheLarkInn** [comment]
Hi @daprahamian!!!!!!

A few points here based on your comments in your issue tracker: 

> Bundlers are not necessary for node. There is a decent chance that a user does not intend to bundle mongodb into their project. It can inflate the bundle by hundreds of kB with no appreciable gain.

node developers/authors are encouraged to bundle their JavaScript even run on node. This is because it significantly reduces runtime and startup cost of that service running on node. For those who choose to do this, they do so using the `target: node` property. It is [documented in our documentation](https://webpack.js.org/configuration/target). This is a very common practice at Microsoft and included in multiple places in our Azure documentation as well (especially where serverless costs are based on run and startup times). Please do not discourage developers to _not_ bundler their node code. (As seen in the issue). 

> There are some things that are perfectly valid node syntax (like dynamically requiring in files, and using variables in `require` calls) but will not work in bundlers. 

There are work-arounds for developers here, however we usually encourage that library authors try not abuse the dynamic nature of the `require("")` statement. In about 90% of cases, you just need to provide a partial path and an expression which is supported vs. a purely dynamic variable in the `require()` statement. This can be worked around if needed, however webpack doesn't _break_ when this happens just throws a warning saying its bad practice. (Just because its possible, doesn't mean its a good development practice). 

> We do link to some binary modules like kerberos, which AFAIK will not work out of the box with webpack.

Users can opt out of this by setting an `externals` property. This will just tell webpack to ignore the module and don't parse it, and trust that it will work. 

> Supporting webpack may implicitly encourage users to attempt to run the driver in a web browser (which either will not work or become a major security issue)

I think just being clear that this will only work in a node target is fine. If documenting this is too much effort we can try and assist. (Hopefully a small "bundlers" section can't hurt right?)

> Certain projects like now.sh attempt to bundle code without the users knowing, leading to situations where code works fine in a dev environment, but fails in production.

Working through the above problems should make this one far less common! 

>In some cases, babel would disrupt the feature detection by polyfilling Symbol.asyncIterator

This one is our of our hands unfortuately because a user is free to transform code via webpack how they please! 

If you'd like to reach out, I'm happy to discuss this more or work through this more also. Find my MS email on my github page! <3

**Comment by daprahamian** [comment]
Hi @TheLarkInn,

Thank you for your response. It appears that your guidance is to only have top-level require calls with non-dynamic names. In that case, I am looking to be able to address the following:

1. We sometimes have circular dependencies that we get around by wrapping require calls in a function. An example can be seen [here](https://github.com/mongodb/node-mongodb-native/blob/master/lib/operations/collection_ops.js#L26). I am assuming that, since the webpack call is still dynamic, that this will still work under webpack and we will not have to change it.

2. We wrap certain require statements in `try/catch` blocks, as they are optional dependencies. An example is [here](https://github.com/mongodb-js/mongodb-core/blob/master/lib/auth/scram.js#L12). This is typically for optional modules that we do not require the user to install. I'm assuming these will also work as well.

3. The original bug that caused this was attempting to dynamically import a file that used node 10 syntax (commits [here](https://github.com/mongodb/node-mongodb-native/commit/b972c1e79eb30cd44b591cf5ab96ad688cb0a206) and [here](https://github.com/mongodb/node-mongodb-native/commit/e0826fb10a74976079c94e9af43c1a9798ce3094)). Because it was a dynamic import wrapped in a try/catch, it was silently caught if run in a lower node version. But in webpack, since every module is loaded in, it caused a parse error. Is it possible to achieve this at all in webpack? Or is this just something we should avoid?

Regardless of the answers to these questions, I feel like from a feature perspective I am looking for the following:
+ It would be nice to have some sort of documentation along the lines of "How to make your library safe for webpack". 
+ On top of this, it would be nice to see a set of linter rules that could warn against behavior that would be problematic for webpack.

Thank you for your time,
Dan
