### ISSUE TITLE
[StackOverflow Question] Seperating css preprocess watch from js

### ISSUE THREAD

**Issue by etisdew** [webpack/webpack#9148]
Is there a convention for avoiding a wasteful update to unaltered files of another extension ie less, sass? Or am I right in thinking a separation of concerns by isolating your styles from the file watchers concerns would be the most efficient strategy for avoiding the issue?

I'v had to dance around this for years, please provide clarity on the best means of going about this in anyones opinions. This would make a good referable but if you disagree I apologize for cluttering your issues. I have no doubt many of us are just ignorant of the api to do this.

Ref. StackOverflow https://stackoverflow.com/questions/56202810/how-to-make-webpack-4-compile-sass-only-if-a-sass-file-has-changed-and-js-only/56202847?noredirect=1#comment99028339_56202847

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
