### ISSUE TITLE
Why is packing so slow?I'm going crazy.Files only 10M long

### ISSUE THREAD

**Issue by 690284557** [webpack/webpack#9164]
Why is packing so slow?
[INFO] Hash: 4df452bd58785b5b563a
[INFO] Version: webpack 4.8.0
[INFO] Time: 528914ms
[INFO] Built at: 2019-05-21 11:16:33
[consoleText.txt](https://github.com/webpack/webpack/files/3206314/consoleText.txt)
I'm going crazy.Files only 10m long

**Comment by 690284557** [comment]
[webpack.zip](https://github.com/webpack/webpack/files/3206348/webpack.zip)

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
