### ISSUE TITLE
Plugin templates don't get updated with HMR

### ISSUE THREAD

**Issue by micburks** [webpack/webpack#9197]
# Bug report

**What is the current behavior?**

An `ImportDependencyTemplate` plugin does not re-run or update template through HMR when a dependency is changed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction here: https://github.com/micburks/webpack-hmr-instrument

**What is the expected behavior?**

When a dependent file is updated:
- The `ImportDependencyTemplate` plugin should build a new template
- Client should be updated via HMR

**Other relevant information:**
webpack version: 4.32.2
Node.js version: 10.15.3
Operating System: MacOS
Additional tools:

**Comment by sokra** [comment]
This is working as expected. The Dependency hasn't changed, only the content of the referenced module.

A Dependency only depends on the module id of the referenced module. Otherwise changing one module would invalidate the whole chain of modules referencing it.

Actually a Dependency can choose on which information it depends on. See `updateHash` method of Dependency. If you need more data, you might look into creating your own dependency with a different `updateHash` method.

**Comment by micburks** [comment]
That's super helpful, thanks for the explanation!

It looks like if I create a new Dependency, I'd have to also create a new Parser that will invoke it. This doesn't seem particularly straightforward to do, unless I'm mistaken and there's a simpler way.

**Comment by sokra** [comment]
You can also replace the ImportDependency with your custom one after parsing.

**Comment by micburks** [comment]
Sounds reasonable. Do you have an example of that? I can't seem to find an example in practice

**Comment by micburks** [comment]
I was able to get this working. For posterity's sake, I hooked into `compilation.hooks.afterOptimizeDependencies` and replaced the `ImportDependency` found in `modules.blocks.dependencies` with my custom dependency. My dependency is added to `compilation.dependencyFactories` and `compilation.dependencyTemplates` similar to `lib/dependencies/ImportPlugin.js`. Then my dependency uses build-time data to update the hash to signal an update.

Thanks @sokra for the help!
