### ISSUE TITLE
AMD require call is incorrectly replaced by webpack and causes SyntaxError

### ISSUE THREAD

**Issue by vladar** [webpack/webpack#920]
I am in the process of migrating from RequireJS to Webpack, but following AMD module that worked in RequireJS produces "SyntaxError: missing ; before statement" with webpack:

```
define([], function() {
    var modules = [];
    if (modules.length) {
        require(modules, function() {});
    }
});
```

This is basically an excerpt that causes error. Webpack transforms it to following:

```
    var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;!(__WEBPACK_AMD_DEFINE_ARRAY__ = [], __WEBPACK_AMD_DEFINE_RESULT__ = function() {
        var modules = [];

        if (modules.length) {
            __webpack_require__(1)!/* require */(/* empty */function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = modules; (function () {}.apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}());
        }
    }.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
```

Browser reports "SyntaxError: missing ; before statement" in the string _**webpack_require**(1)!_ after function call.

Is it a bug or I can transform this call to some other form?

I use webpack 1.7.3

**Comment by bebraw** [comment]
Can you see this issue in webpack 2?

**Comment by tomaszpupiec** [comment]
Part of my code looks like:

`
		require([area + 'controllers/' + page + 'Controller'], (Controller) => {
			controller = new Controller.default(params);
		});
`

and is transpiling to:

`
__webpack_require__.e/* require */(1/* duplicate */).then(function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = [__webpack_require__(9)(area + 'controllers/' + page + 'Controller')]; 
((Controller) => {
      controller = new Controller.default(params);
}.apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}).catch(__webpack_require__.oe);
`

It causes "SyntaxError: missing ) in parenthetical".
Seems that problem is using "apply" on arrow function.

Any solution ?

**Comment by naruaway** [comment]
I think 28f2ffe7f94de886111dbc0b45e3d9df06ae7 already fixed this problem.
