### ISSUE TITLE
To be able to pass a simple string to the config file to specify output

### ISSUE THREAD

**Issue by dara-khosrowshahi-007** [webpack/webpack#9247]
## Feature request

O.K.

**What is the expected behavior?**

Same as before.

**What is motivation or use case for adding/changing the behavior?**

Reducing code by one line or so.

**How should this be implemented in your opinion?**

Accept a string as follows

```

// output
output: `${DIST_DIR}/bundle.js`,


```
instead of an object literal like the current way

```
    output: {
      filename: 'bundle.js',
      path: DIST_DIR
    },

```
**Are you willing to work on this yourself?**

yes

**Comment by sokra** [comment]
There were plans to add this before but this never took off.

There are some consistency issues with this shortcut:

* Where to split `filename` and `path`? (Note that `filename` could be something like `scripts/[name].js`)
* Should this only specific `path` and `filename` should use the default?
* Should this only specific `filename` and `path` should use the default?

We could only allow non-absolute paths for `output`, which would it be a shortcut for `filename`?

Still there could be confusion because there are two way to specific a option value...

So in the end it probably makes sense to not add the shortcut at all to avoid inconsistency and confusion for

> Reducing code by one line or so.

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/9247#issuecomment-500699344
