### ISSUE TITLE
multi-entry

### ISSUE THREAD

**Issue by Peroluo** [webpack/webpack#9248]
Can you modify the location of multi-entry on-demand chunks?

**Comment by Peroluo** [comment]
Multiple entries cannot be used with on-demand loading

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
