### ISSUE TITLE
[Feature]: Abstract progressplugin to webpack contrib

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack#9252]
## Feature request

https://github.com/webpack/webpack/blob/master/lib/ProgressPlugin.js

It would be nice to abstract the progressplugin to webpack contrib if we can do that to avoid code that some users don't need as apart of webpack. Furthermore I think we should allow the progressplugin to have more flavors instead of one bar that is outputting in a single fashion. 

I suggest that we can make use of [Ora](https://github.com/sindresorhus/ora) as well as look out for other spinners that might make the CLI visually better and improve the user experience for webpack. I'm up for doing this task if allowed.

Even

**What is the expected behavior?**
ProgressPlugin with various of flavors

**What is motivation or use case for adding/changing the behavior?**
Better Interface

**How should this be implemented in your opinion?**
Abstracted Progress Plugin to another repository with more options

**Are you willing to work on this yourself?**
yes

**Comment by evenstensberg** [comment]
CC @webpack/contributor-team for insight

**Comment by evenstensberg** [comment]
Relevant: https://github.com/webpack/webpack-cli/issues/717

**Comment by evilebottnawi** [comment]
Don't think it is should be in `webpack-contrib` org, better use `webpack` org for this. 

Why don't use this?
```
new ProgressPlugin({ handler: customHandle });
```

**Comment by hulkish** [comment]
@evenstensberg hmm, i agree with the decoupling of progress plugin. but, i personally view the ora usage a little undesirable from a dependency standpoint

**Comment by evenstensberg** [comment]
We can do that. Does it make sense to move it as a seperate plugin in /webpack ?

**Comment by okonet** [comment]
@evenstensberg I’m still getting email notifications for webpack issues. 

> You are receiving this because you are on a team that was mentioned.

Can you please check and remove me from those teams? Thanks!

**Comment by evilebottnawi** [comment]
@evenstensberg 

> We can do that. Does it make sense to move it as a seperate plugin in /webpack ?

Will be great to look on PoC, it is hard to say how to solve problem(s) better without examples. We already have option to change behavior as i written above. Why it is not solve problem?

**Comment by sokra** [comment]
I think it's difficult to move the ProgressPlugin into a separate repo. It's very coupled to webpack internals so keeping it up-to-date as separate repo would be a hard job.

You can still build a ora progress plugin on top of this like @evilebottnawi mentioned: https://github.com/webpack/webpack/issues/9252#issuecomment-500874186

So I don't see strong arguments for separating it.

**Comment by evenstensberg** [comment]
Gotcha

**Comment by niieani** [comment]
I think what's more important is to make the handler payload better. There's different types of progress that we can track and we should have separate object signatures for each, rather than just sending a bunch of pre-prepared strings down to it.

Currently in order to make a good handler you need to parse this information our with something like RegExps, which is really bad for performance and generally a poor experience.

E.g. in my implementation of a progress bar using the ProgressPlugin I have to resort to regexps/splits to re-parse the data out of the strings in order to be able to position these parts properly. The result is something like this:

![progress-bar](https://user-images.githubusercontent.com/563469/47649441-99a62e80-db7d-11e8-88b9-6fe3c9eddbbc.gif)

If instead we provided a default handler that simply makes these strings as they are now, we can get the same behavior, and still give greater flexibility for alternative handlers.

I would imagine handler being most flexible e.g. when called like this:

```js
handler({compilerIndex, currentStage, doneModules, activeModules, lastModulesCount, moduleCount, count, mode})
```

And some of those parameters would obviously be `undefined` in certain stages (which is fine). By "stage" I mean the hook currently being executed, or compilation.

It could also be a disjoint union of various statuses with their own meta, ideally typed with JSDoc.

**Comment by evilebottnawi** [comment]
@niieani do you have idea how we can change plugin for better integration as you written above? Maybe you can send PoC?

**Comment by evenstensberg** [comment]
Reopening for design discussion

**Comment by sokra** [comment]
@niieani Makes sense to make it more customizable.

Maybe it makes even sense to split the jobs into `handler` and `formater`, so it's called in this way:

``` js
handler(...formater({compilerIndex, currentStage, doneModules, activeModules, lastModulesCount, moduleCount, count, mode}))
```

This could keep compatiblity with existing handlers, makes it easy for the simple case, but allows customizablility for the advanced case. It would also allows to only change the format while keeping the default `handler` (which prints to stderr)

**Comment by evilebottnawi** [comment]
bump, still feel free to sens a PR with PoC
