### ISSUE TITLE
SplitChunksPlugin name truncation config parameter or default

### ISSUE THREAD

**Issue by ryandrew14** [webpack/webpack#9266]
## Feature request

**What is the expected behavior?**
using `splitChunks.name: 'truncate'` in the Webpack config

**What is motivation or use case for adding/changing the behavior?**
In my use case for this function, I wanted to truncate my webpack chunk names that were getting too long. The default Webpack naming was ending in names >50 characters long, resulting in really poorly readable output from the build command. 

This is a pretty simple thing, but took me a while to figure out, as I had to `console.log` for what the Chunk objects actually look like from the function I was passing to `splitChunks.name`. So, it's tough enough to figure out and seems like a common enough use case (or a reasonable default) that it's worth a feature. Let me know what you think.

**How should this be implemented in your opinion?**
The existing `splitChunks.name` option can be used; This should either be a default (to make the SplitChunksPlugin's naming play nice with Webpack's default formatting and chunk splitting settings) with an option like `splitChunks: 'verbose'` or be an option like `splitChunks.name: 'truncate'`.

**Are you willing to work on this yourself?**
Absolutely! I would love to.

**Comment by sokra** [comment]
What's the difference to `name: true`? This already concatenates the chunk names and is the default. I have difficulties understanding the difference from your description above.

**Comment by ryandrew14** [comment]
Oops -- I was using the wrong word. I meant truncate but wrote concatenate. The auto-concatenated names from `name: true` were making my formatting unreadable because they were too long.

**Comment by sokra** [comment]
Ah now I get it.

The default name is actually already truncated to 100 chars maximum. So you want to lower the limit, maybe make it an option?

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/lib/optimize/SplitChunksPlugin.js#L160-L168

**Comment by ryandrew14** [comment]
This sounds great, let me try it out tonight and see if it solves the problem. I'll send a PR if it works for me.

Would you rather to see the option in a format like 
```javascript
splitChunks: {
   name: {
      content: 'myCustomName',
      truncateLength: 100,
   }
}
```
or like
```javascript
splitChunks: {
   name: 'myCustomName',
   truncateLength: 100,
}
```

**Comment by sokra** [comment]
For consistency with `automaticNameDelimiter` and `automaticNamePrefix` this would probably a good option:

``` js
splitChunks: {
   name: 'myCustomName',
   automaticNameMaxLength: 100,
}
```

https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/lib/optimize/SplitChunksPlugin.js#L128

https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/lib/optimize/SplitChunksPlugin.js#L165-L168

https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/schemas/WebpackOptions.json#L551-L555

https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/schemas/WebpackOptions.json#L580-L588

https://github.com/webpack/webpack/blob/bba93d2a85a35dc793dda6d347e54b094e2ce784/lib/WebpackOptionsDefaulter.js#L233

Send a PR

---

Since automatic naming was removed in webpack 5 you probably have to add a similar thing for webpack 5 and the id generation:

``` js
optimization: {
  chunkIds: "named",
  chunkIdMaxLength: 100
}
```

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/schemas/WebpackOptions.json#L485-L495

add `maxLength` here:

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/lib/ids/IdHelpers.js#L50-L60

and to these two methods:

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/lib/ids/IdHelpers.js#L108-L163

and to this plugin:

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/lib/ids/NamedChunkIdsPlugin.js#L21-L25

other plugins need to be changed too, but you can pass `Infinity` as maxLength there.

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/lib/WebpackOptionsApply.js#L483

https://github.com/webpack/webpack/blob/4b2c5784edcf507d5aace489c240904f03c5b710/lib/WebpackOptionsDefaulter.js#L300-L304

Send another PR

**Comment by ryandrew14** [comment]
Sounds good, will go for this tonight. Thanks!
