### ISSUE TITLE
webpack4: Error--Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by denkyira5544** [webpack/webpack#9336]
I am using webpack 4 with npm -v 6.9.0 and getting the error below when I run my webpack 

 node_modules\webpack\bin\webpack.js:90
	let notify =
	^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by vankop** [comment]
looks like you need to upgrade nodejs

**Comment by denkyira5544** [comment]
I am using the latest nodejs v10.16.0 with npm 6.9.0 so what version should I upgrade to?

**Comment by denkyira5544** [comment]
I have upgraded my Nodejs to Node.js v12.5.0 and running webpack  "webpack 4.35.0", but still getting the same error

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by egor-no** [comment]
but it's not completed, there's not even an answer here...
