### ISSUE TITLE
How to exclude library from specific entry?

### ISSUE THREAD

**Issue by ugg0t** [webpack/webpack#9342]
I have my root app that can import bundles of sub apps. Sub apps can be run in a standalone mode as well. The problem is that root app and imported sub app use different instances of library (probably, the versions of lib instances are the same). I want them use only one copy of library.
So, I want in my webpack config something like that:
```
entry: {
    standalone: 'standalone.js', // bundle for standalone mode
    render: { // bundle for sub app
        name: 'render.js',
        exclude: ['react'],
    }
}
```
Is there a way to do that?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
