### ISSUE TITLE
Webpack 5: Asset invalidations do not invalidate sources that emitted the asset

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#9354]
# Bug report

This came up in https://github.com/zeit/ncc-watcher/pull/4, where we have a custom watch process.

**What is the current behavior?**

When an asset (from `emitFile`) is emitted and later invalidated in the watcher, the asset being output in the build remains the old asset.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run a watched build where a source emits an asset, and the asset is invalidated, while the source is cached.

**What is the expected behavior?**

The asset invalidation should be invalidating the underlying source so that that the new asset is emitted.

**Other relevant information:**
webpack version:  5.0.0-alpha.17

**Comment by sokra** [comment]
Which loader calls `emitFile`? Does the loader correctly declare dependencies on the emitted content with `this.addDependency(...)`?

**Comment by guybedford** [comment]
These are the relocator loader emissions - https://github.com/zeit/webpack-asset-relocator-loader/blob/master/src/asset-relocator.js#L315.

I thought that by default Webpack would relate these emissions to the module being handled through the loader?

**Comment by sokra** [comment]
By default a loader resp. the module only depends on the resource. In your case you are reading additional files inside of the loader (i. e. here: https://github.com/zeit/webpack-asset-relocator-loader/blob/c7fdb5e0726f91ecf8d586d06a975171ccbf108e/src/utils/sharedlib-emit.js#L21). webpack doesn't know that the loader resp. the module also depends on these additional files. The consequences are watching and caching won't work as expected. The module won't be invalidated when an additional files has changed. The loader **won't be executed**.

Add these dependencies with `this.addDependency` or `this.addContextDependency`.

Here `this.addContextDependency` probably makes sense because you are globbing a directory. `this.addContextDependency` add a directory as dependency. Any change in this directory will invalidate the module.

Note that webpack 5 doesn't yet implement timestamping for directories so it probably will always be invalidated. This has only a negative performance effect, but compilation is still correct. It'll will become faster once this is implemented. Watching should work as expected.

---

PS: Don't do that

https://github.com/zeit/webpack-asset-relocator-loader/blob/c7fdb5e0726f91ecf8d586d06a975171ccbf108e/src/asset-relocator.js#L310

Due to caching you can't be sure that the loader will be executed at all for a compilation. When all modules with this loaders are cached `__webpack_require__.ab` won't be injected and the cached source code will crash at runtime because `__webpack_require__.ab` is undefined. Instead use an plugin to add `__webpack_require__.ab` or flag the loader as non-cacheable.

**Comment by guybedford** [comment]
@sokra if a given loader for a resource emits asset files, then invalidations of those asset files should invalidate the resource that emitted them. Is this not the case? The globbing is not so much a concern as node_modules paths arent typically updated during watched builds. The specific issue we were having was that change a single asset was invalidating the loader, but the second time it is rebuilt it does not invalidate in the build and using the old output, and we are not sure why.

Re the loader trick, see https://github.com/zeit/webpack-asset-relocator-loader#caching for how I'm getting around this. Creating a plugin and a loader was simply not suitable for this use case.

**Comment by guybedford** [comment]
Specifically - the invalidation works the first time, but the second time it still uses the old source.

// cc @TooTallNate

**Comment by sokra** [comment]
adding `this.addDependency(assetPath)` before this line https://github.com/zeit/webpack-asset-relocator-loader/blob/c7fdb5e0726f91ecf8d586d06a975171ccbf108e/src/asset-relocator.js#L374 fixed the issue in https://github.com/zeit/ncc-watcher/pull/4 for me.

You should call `addDependency` for each file you read/access in the loader. And `addContextDependency` for every directory.

**Comment by guybedford** [comment]
@sokra you really didn't have to do that, thank you so much, I owe you one. I mistakenly thought we had an `emitFile(path)` API instead of an `emitFile(source)` API, so that was the gap in the mental model.

**Comment by sokra** [comment]
https://github.com/zeit/ncc-watcher/blob/664261f983ae4c01bcd5854dba5e9338d0294e67/src/index.ts#L106-L111

`{}` will always be valid and always cache files. So the comment should be updated.
