### ISSUE TITLE
办理国外文凭,成绩单,使馆认证

### ISSUE THREAD

**Issue by vsdfasdawd** [webpack/webpack#9369]
[办理国外文凭](https://www.diplomaclub.net),成绩单,使馆认证[https://www.diplomaclub.net](https://www.diplomaclub.net)

**Comment by alanhg** [comment]
@vsdfasdawd 滚蛋

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
