### ISSUE TITLE
externals is not support object

### ISSUE THREAD

**Issue by yegao** [webpack/webpack#9373]
the version of my webpack is 4.35.2
when I config my webpack.config.js like following
```
externals:{
    lodash : {
        commonjs: 'lodash',
        amd: 'lodash',
        root: '_' 
    }
}
```
the package give me an void 0
```
function (e, t) {
    e.exports = void 0
}
```

**Comment by evilebottnawi** [comment]
Please use issue template

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
