### ISSUE TITLE
Module parse failed Need appro

### ISSUE THREAD

**Issue by shobishani** [webpack/webpack#9385]
I'm not sure if I am at the right place to report this bug Please look into it and guide me. I am using react-mapbox package that loads it's css file from node_modules and it gives me error on while running dev server and while running build as well.

**Error while webpack build?**

`ERROR in ./node_modules/mapbox-gl/dist/mapbox-gl.css 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
| /* stylelint-disable */
> .mapboxgl-map {
|     font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
|     overflow: hidden;
 @ ./node_modules/react-mapbox-gl/lib-esm/map.js 38:8-47
 @ ./node_modules/react-mapbox-gl/lib-esm/index.js
 @ ./client/app/components/blocks/mapbox/MapBox.tsx
 @ ./client/app/components/blocks/index.ts
 @ ./client/index.tsx
 @ multi babel-polyfill ./client/index.tsx
`
**Here is my Webpack configuration**
[`Click here to read config`](https://gist.github.com/shobishani/fa64288deed2784059568a1ef0c489d6)

**Other relevant information:**
webpack version:  
` 4.31.0`
Node.js version: 
`v10.16.0`
Operating System: 
`Linux ubuntu`
Additional tools:
`css-loader
node-sass
postcss
sass-loader
stylelint
stylelint-scss
stylelint-webpack-plugin
tslint`

**Comment by evilebottnawi** [comment]
you need `css-loader`

**Comment by TheImpressionist** [comment]
Elaborate on why `exclude: /node_modules/` causes these issues.

Without the `exclude` the whole node_modules will get loaded onto there, I might not need a million of useless CSS that I'm not using and that is causing issues that's still present under `node_modules`.

Yet if I leave it, it's impossible to ever a get a build done, because of the same error.

**Comment by evilebottnawi** [comment]
@TheImpressionist :-1: ? You problem not related to this, please read issue before set :-1: You just have invalid configuration

**Comment by TheImpressionist** [comment]
How's `exclude: /node_modules/` an invalid configuration. Isn't the intended feature of it to actually do excluding?

```js
{
    test: /\.(css|sass|scss)$/i,
    exclude: /node_modules/,
    use: [
      'style-loader',
      'css-loader',
      {
        loader: 'postcss-loader',
        options: {
          plugins: [
            require('postcss-modules'),
            require('autoprefixer'),
            require('cssnano')({
              zindex: false,
              reduceIdents: false,
            })],
        },
      },
      'sass-loader',
    ],
  },
```

Elaborate what is wrong with the said CSS configuration. Why does `exclude` cause loader issues, where the file type cannot be recognized anymore? Because you answer is devoid of any explanation other than "remove". That solves the issue in the context where `exclude` may not be necessary, but in the context where it is, leaves you wondering what's wrong.

**Comment by evilebottnawi** [comment]
@TheImpressionist you should change the tone otherwise I will stop any help to you, you disable loader for node_modules but loads css from node modules and says what webpack doesn't as you expected :confused: What you expected? You load css assets from `./node_modules/antd/lib/tooltip/style/index.css` so you need handle `node_modules` too

**Comment by TheImpressionist** [comment]
What tone. Elaboration was all that was needed. I'm merely commenting on the lacking answer. If that is considered to "rude", then I'll be damned. I guess it's all ponies and rainbows or nothing at all.

Full answers, or at least answers explaining what is actually going on reduce the need for new issues over, and over, and over.

Thanks for clearing it up. While, I'm definitely am NOT loading the following: `./node_modules/antd/lib/tooltip/style/index.css`, I am loading something else from a different package.

So, as long as CSS is being loaded from `node_modules`, regardless of the package, it will include everything from `node_modules`, as I understand. Meaning if I want to avoid loading CSS that I'm not using I have to provide a more elaborate exclusion regex? Because I'm not sure how will two loaders will help in this case.

Say if I have the following import:
`import 'rc-slider/assets/style.css'`
I have to setup a loader specifically for this asset and then exclude the rest?

**Comment by evilebottnawi** [comment]
@TheImpressionist you can use `null-loader` for assets what you don't need and use yes you need more complex setup for this case, `exclude` just exclude files what loader doesn't handle, it is not exclude file from build.

```js
{
    test: /\.(css|sass|scss)$/i,
    include: /node_modules/,
    loader: 'null-loader'
},
```

all `css`/`sass`/`scss` was empty

**Comment by TheImpressionist** [comment]
I see. I'll give the `null-loader` a try, thanks.
