### ISSUE TITLE
Add ability to use native nodejs require resolve method

### ISSUE THREAD

**Issue by lucas-rudd** [webpack/webpack#9393]
## Feature request

**What is the expected behavior?**
I am using a 3rd party library which uses the nodeJs `require.resolve` method to get the path of a module at runtime. The specific piece of code in question is as follows

```
var sourceDir = path.join(path.dirname(require.resolve('dep')), 'dir', 'subdir');
```

When bundled with webpack, this results in the following

```
var sourceDir = path.join(path.dirname(/*require.resolve*/(124)), 'dir', 'subdir');
```

which results in a runtime failure, as `path.dirname` requires a string.

**What is motivation or use case for adding/changing the behavior?**
To support 3rd party packages which may use the built in NodeJs implementation of `require.resolve`

**How should this be implemented in your opinion?**
Through the use of a key `_use_node_resolve_` in webpack config to indicate that webpack should leave the `require.resolve` implementation alone when bundling.

**Are you willing to work on this yourself?**
With some guidance and help, yes

**Comment by evilebottnawi** [comment]
Do you build project for web or node?

**Comment by lucas-rudd** [comment]
nodeJs

**Comment by kettanaito** [comment]
I apologize for intrusion, is there any progress on this?
I need for my NodeJS application to be able to call the native `require.resolve()` to resolve a path to a given module. I cannot substitute it with anything else.

**Comment by evilebottnawi** [comment]
@kettanaito can you create minimum reproducible test repo?

**Comment by kettanaito** [comment]
@evilebottnawi I've resolved it and will share the solution that worked for me below.

> From my investigation, `webpack` replaces the native `require` module from NodeJS by their own implementation to allow certain webpack features. It seems it connects a module's require calls with the _module IDs_ kept in webpack.

**Webpack injects a native `require` module into your bundle through `__non_webpack_require__ ` namespace**. Thanks to @sokra for [revealing this hidden gem](https://github.com/webpack/webpack/issues/4175#issuecomment-277232067).

```js
const module = __non_webpack_require__('module-name')
```

I was looking for a way to use `require.resolve()`, so the proper way ended up to be `__non_webpack_require__.resolve(modulePath)`. This is rather an edge case, but I wasn't able to find any mention of this global variable in webpack's documentation.

**Comment by quoininc-huudatran** [comment]
How would i go with this if I share my module between nodejs and client. In my nodejs run, I do not use webpack to bundle the code, I just `git clone`, `npm ci`, and `npm start`. That same file is also used inside of the client-side (React) that is build during `npm ci` process.

My goal is to get the folder where the `package.json` resides. Can I do that without the need to separate my code from server-side or webpack'ed client-side?

My code is:
```javascript
const PROJECT_ROOT = path.dirname(require.resolve('./../../package.json'));
```
or
```javascript
import packageJson from './../../package.json';
```

All this was working fine with webpack2. I'm am not sure how to convert this to work with webpack4. I've tried the `fs.readFileSync()` but on browser, I get the `a.default.readFileSync is not a function` error.

**Comment by kettanaito** [comment]
@quoininc-huudatran, I'm not sure if I understand your particular problem correctly, but if you just need a folder name/path, consider this:

```js
const packageJsonPath = path.resolve('../../package.json')
const packageJsonDirname = path.dirname(packageJsonPath)

// Alternatively, you can parse the path and get more info
const parsedPath = path.parse(packageJsonPath)
```

- [`path.dirname(path)`](https://nodejs.org/api/path.html#path_path_dirname_path)
- [`path.parse(path)`](https://nodejs.org/api/path.html#path_path_parse_path)

To manipulate paths you don't have to require a module. Let me know if that helps.

It's worth mentioning, that you shouldn't use built-in modules on the client, so if your goal is for the _client_ to know the folder of `package.json` consider:

1. Figuring that out as a part of webpack build step and provigint the package json directory via [`webpack.EnvironmentPlugin()`](https://webpack.js.org/plugins/environment-plugin/):

```js
// webpack.config.js
// The same functionality as from the snippet above
const PACKAGE_JSON_DIRNAME = path.dirname(path.resolve('../../package.json'))

module.exports = {
  // your webpack config,
  plugins: [
    new webpack.EnvironmentPlugin({
      PACKAGE_JSON_DIRNAME,
    })
  ]
}
```

Later, in the client, access that environmental variable as:

```js
// src/app.js
process.env.PACKAGE_JSON_DIRNAME
```

2. Figuring that out on the server, only in case of more complicated scenarios.

**Comment by quoininc-huudatran** [comment]
> @quoininc-huudatran, I'm not sure if I understand your particular problem correctly, but if you just need a folder name/path, consider this:
> 
> ```js
> const packageJsonPath = path.resolve('../../package.json')
> const packageJsonDirname = path.dirname(packageJsonPath)
> 
> // Alternatively, you can parse the path and get more info
> const parsedPath = path.parse(packageJsonPath)
> ```

This wouldn't work for a package...

```js
const otherPackageJson = require.resolve('@namespace/packageName/package.json');
```

I am requiring the file in order to be able to use values. In my example above, it would be something like:

```js
const { name, version } = require('./../package.json');
```

> Later, in the client, access that environmental variable as:
> 
> ```js
> // src/app.js
> process.env.PACKAGE_JSON_DIRNAME
> ```
> 
> 1. Figuring that out on the server, only in case of more complicated scenarios.

Yes, my case is a shared code between client and server, so I cannot rely on webpack to do these things... and I rather not have my code polluted with 

```js
if (process.env.VARIABLE) {
   // use variable
} else {
    const { name, version } = require('./../package.json');
}
```

**Comment by kettanaito** [comment]
@quoininc-huudatran, thanks for the reply. I don't think the issue you describe is connected to the  problem OP describes.

The original issue is that webpack stubs the calls to `require.resolve` in order to inject additional info about the module imports. So, when calling `require.resolve()` your code is subjected to change once it compiles. Sometimes you may want to avoid that.

In your case you seem to import a package json file and grab some values from it. There is no need to require the package json just to know where it's located, so you might have gone with:

```diff
const PROJECT_ROOT =
  path.dirname(
-   require.resolve('./../../package.json')
+   path.resolve('./../../package.json')
  );
```

I'd still not recommend trying to perform that on the client, you shouldn't operate with file system as a client runtime (and client's code is what gets executed runtime). That's why I've suggested to resolve the package's directory as a part of build step, as one of potential solutions. I'm still not sure why you need to know the directory name, as you can import package json and grab values from it directly.

**Comment by quoininc-huudatran** [comment]
@kettanaito Above, I'm showing you the two use cases where the webpack4 breaks while it was working perfectly in webpack2. They are not directly related.

I'm required to use the `require.resolve()` because I need access to third party modules' path (I do not know in which `node_modules` they are installed in because it could be in any parent folder's `node_modules`). `path.resolve()` will not be able the handle this case.

So somehow, the webpack4 (maybe webpack3 too?) is breaking my code sharing between my backend and frontend shared code.

I believe it is therefore that it is related to the OP.
