### ISSUE TITLE
Non-deterministic output breaking long-term caching

### ISSUE THREAD

**Issue by RR2DO2** [webpack/webpack#950]
While using webpack for a project using react-bootstrap, I noticed my distribution hashes kept changing. I've narrowed this down to a simple test case, in my situation both react-bootstrap and react-bootstrap-daterangepicker are affected. This is mainly an issue for long-term caching as the hashes for files keep changing.

What happens is that whenever I execute webpack, the output will be different. Looking at diffs between runs it seems that the indexes passed into requires keep changing. Probably some async operations returning  in variable order somewhere? Example diff chunk:

```diff
141c141
< 	    !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(5), __webpack_require__(4), exports], __WEBPACK_AMD_DEFINE_RESULT__ = function(momentjs, $, exports) {
---
> 	    !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(6), __webpack_require__(4), exports], __WEBPACK_AMD_DEFINE_RESULT__ = function(momentjs, $, exports) {
```

Repro case exists out of a package.json to install the requirements and a webpack config:

package.json:
```json
{
    "name": "webpack-repro",
    "version": "0.0.0",
    "dependencies": {
        "react-bootstrap": "0.20.1",
        "react-bootstrap-daterangepicker": "0.2.4"
    },
    "devDependencies": {
        "webpack": "1.7.3"
    },
    "private": true
}
```

webpack.config.js:
```javascript
'use strict';

var path = require("path");
var webpack = require("webpack");

module.exports = {
  entry: {
    vendor: [
      "react-bootstrap",
      // "react-bootstrap-daterangepicker",
    ],
  },
  output: {
    path: path.join(__dirname, "js"),
    filename: "[name].js",
  }
};
```

**Comment by sokra** [comment]
add the `OccurenceOrderPlugin`.

**Comment by RR2DO2** [comment]
Reading the documentation for this that looks like the OccurenceOrderPlugin should do the trick and I'll give it some testing. I don't think records will help though as I've seen non-deterministic output even when clearing out the output directory.

It's probably worth making a mention of this on the long term caching page? Is there a reason this behaviour isn't default?

**Comment by alexeits** [comment]
The `OccurenceOrderPlugin` doesn't seem to solve the problem very well for keeping the vendor chunk unchanged. It looks like that code modifications could result in module reordering even without adding new external dependencies.

**Comment by mhelvens** [comment]
`OccurenceOrderPlugin` seems to work well enough, at least for my case. I have to put generated files on GitHub for the benefit of the Bower package manager. It's nice not to re-commit those files when the source code hasn't changed.

But a simple option to make the output deterministic would be useful. Why not base the module order on the order in which they are imported/required?

**Comment by sokra** [comment]
With the next major version occurence order is on by default.

**Comment by tcurdt** [comment]
Can't one just write a loader that calculates the md5 of the final content? Question is only how make that available to the variable expansion so that "[name]-[md5].[ext]" would work.

**Comment by mhelvens** [comment]
@tcurdt: Or better: the md5 of the minification of the final content. That way, changes to comments and whitespace would not reorder the modules.

**Comment by tcurdt** [comment]
@mhelvens true - but I could live with the final step of the loader pipeline. Which would be easy to implement in a loader. Just no clue how to get the md5 from the loader into the [md5].

**Comment by mhelvens** [comment]
But even more sensible than playing with hashes, I think, is to just use the order in which the modules are imported / required.

The module imports of a project form a tree, with an entry-point as its root. The imports in any given module are also ordered, since source code is just plain text; thus, a [plane tree](http://en.wikipedia.org/wiki/Tree_(graph_theory)#Plane_tree). I daresay webpack already has a representation of this tree in memory. Why not just use a [pre-order traversal](http://en.wikipedia.org/wiki/Tree_traversal#Pre-order) of this tree to determine the module order in the output?

**Comment by tcurdt** [comment]
Not so sure about the sensible. I would vote for having content addressable files (be it just for cache busting or CDNs) any time.

**Comment by mhelvens** [comment]
I think I misunderstood your proposal. You're talking about file names? I don't think that's what this issue is about. The issue here is that separate runs of webpack on the same source code may result in different output, because of some indeterminacy in the ordering of module definitions.

Choosing a filename for cache busting seems a separate issue. And isn't this already possible using [`[hash]` and/or `[chunkhash]`](http://webpack.github.io/docs/configuration.html#output-filename)?

**Comment by tcurdt** [comment]
@mhelvens re-reading I agree - it's not the same problem.

**Comment by sokra** [comment]
It's determistic now

**Comment by MPV** [comment]
@sokra When was this fixed? We're getting this issue with Webpack 1.12.2.

**Comment by plefferts** [comment]
@MPV I see this issue as well.  1.12.2

**Comment by MPV** [comment]
For my project, our current hypothesis is that different contents of different node_modules folders (due to for example different npm versions, v2 vs v3, or having worked on different branches with different package.json + dependencies installed). This in turn then seems to affect which packages webpack chooses to require, thus giving different / non-deterministic output.

Still have not been able to fully prove that this is the case, but any help troubleshooting / testing / solving the issue further is more than welcome of course.

**Comment by plestik** [comment]
Running into this issue as well. Non-deterministic output breaks our serviceworker-caching process because we use load-balancing and the files are different on each server, even though the source is the same. We use the OccurenceOrderPlugin. Output for reference: https://gist.github.com/plestik/934bc56a212d468cc6ee

**Comment by nickperkinslondon** [comment]
Why is this closed? None of the linked issued seem to address the problem.  I have a "vendor" bundle whose contents seem to get "randomized" every time I build it.  Exact same modules, different order.  I have tried the "occurrence order plugin" -- it made no difference.  The benefit of splitting bundles is completely lost if the "vendor" bundle gets re-ordered every time, for no reason.  There must be a simple, deterministic order that depends only on the set of modules being included!  I am now looking for alternatives to webpack because this is essentially a deal-breaker.  Hopefully I am missing something...is there a solution to this?

**Comment by michael8090** [comment]
I'm facing the same problem even with `OccurenceOrderPlugin` ( by the way, why is it renamed to `Occur**r**enceOrderPlugin`....) and `recordsPath`. I get different chunk hashes on different machines.......

And I've also found that the chunk hashes before and after uglify are the same.... which indicates webpack calculates the hash before uglify
