### ISSUE TITLE
HotModuleReplacementPlugin occasionally not working

### ISSUE THREAD

**Issue by dejour** [webpack/webpack#9514]
# Bug report

**What is the current behavior?**
After webpack detect changes, it produce new bundles, but it won't call the
compiler done hooks.And hmr doesn't work correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Webpack calls the done hook, And hmr works correctly.

**Other relevant information:**
webpack version:  4.35.0
Node.js version:  12.7.0
Operating System: macOs
Additional tools:

After some debugging, I find the problem was caused by this code
``
currentChunk.files.push(filename);
compilation.hooks.chunkAsset.call(currentChunk, filename);
``
from HotModuleReplacementPlugin.js. After i delete it, everything works fine.
Maybe someone can think of something related to this problem.

**Comment by evilebottnawi** [comment]
@dejour can you clarify? Also please create minimum reproducible test repo

**Comment by dejour** [comment]
@evilebottnawi Hi, I made a reproduction repo quite similar to my work case.https://github.com/dejour/ssr-reproduction/tree/master, Hope that's useful.

**Comment by dejour** [comment]
I'm not sure which one (vue-server-plugin or HotModuleReplacementPlugin) is the real problem.

**Comment by maximandrews** [comment]
I have similar issue with my own custom hot reloader.
I figured out that events of `compiler.hooks.done` are not always called either called ones.
I'm subscribing to `compiler.hooks.done` in two different plugins and it calls `done` event handlers of both plugins randomly.

webpack@4.41.2

**Comment by maximandrews** [comment]
### I found the problem!!!

When one of the plugins throws Error in event handler the rest of the handlers in other plugins will not be called and error in original handler is silenced therefore, the developer can't understand why their great code working mysteriously i.e. sometimes works, other times fails.

The issue is with tapable, because it creates string text functions on the fly (loud thoughts: why the hell would you even do that for? :) ) That's your project, absolutely, and you decided how you code it, but it is so unreadable. I was not able to visualize in my mind the bigger picture of logic of your code, my intuition suggested that there is a problem with thrown errors as everything just silently dies.

Here the repo to reproduce
https://github.com/maximandrews/tapableThrownErrorIssue

Please, submit issue to `tapable` repo. I don't have time to do that at the moment.
Thanks!

**Comment by maximandrews** [comment]
#https://github.com/webpack/tapable/issues/10

**Comment by maximandrews** [comment]
https://github.com/webpack/tapable/issues/10

**Comment by maximandrews** [comment]
I suppose 
```
currentChunk.files.push(filename);
compilation.hooks.chunkAsset.call(currentChunk, filename);
```
throws an error and tapable silently crashes.
Repo to reproduce tapable silent crash:
https://github.com/maximandrews/tapableThrownErrorIssue

above I referenced issue related to tapable silent crash.

**Comment by maximandrews** [comment]
@evilebottnawi why you believe it will works? Have you tried?

I just checked and pushed new commit to https://github.com/maximandrews/tapableThrownErrorIssue 

After you throw the error in one of the callbacks of the plugin the hook `failed` callback is never triggered.

**Comment by evilebottnawi** [comment]
@maximandrews hm, сan you show what you want to get, maybe real code?

**Comment by maximandrews** [comment]
@evilebottnawi:
1) I would like to be notified of an error if my callback for some reason throws one.
2) At the moment, if callback throws an error then execution of callback crushes silently and none of the other callbacks (even from different plugin) will never going to be executed. There will be no even notice that something went wrong.

Thank you for your generous offer to help with my real code, but everything what I was willing to get in my code I already did.

### The problem I described above with `webpack` and/or `tapable` still persists [since 2016](https://github.com/webpack/tapable/issues/10).

First time it was noticed in 2016 and I came across it again just recently. This issue makes debugging process difficult and time consuming.

Therefore, I'm kindly informing you that specific part of your code do not perform well. If you capable, please, fix it.

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
Sounds like an problem in the vue server plugin. It seems like it graps all files from the `stats.entrypoints` and checks that there is only a single file there. This is not the case when using HMR, as hot update files are also associated with the chunks they origin from. But they are flagged with `hotModuleReplacement`. The plugin should probably filter the files it needs, just like the html webpack plugin filters only non-`hotModuleReplacement`, non-`development` files.
