### ISSUE TITLE
Why does output.path have to be absolute, but not entry?

### ISSUE THREAD

**Issue by jez9999** [webpack/webpack#9592]
The webpack config file seems inconsistent in that output.path has to be absolute but entry doesn't (it can be relative, like `./public/js/module.js`).  What's the reason for this discrepancy?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
