### ISSUE TITLE
regression: multiple HMR assets to same filename warning / error

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack#9706]
# Bug report

This applies to v4.40.0+ and according to notes in the source, v5.0.0+

**What is the current behavior?**

At present, webpack will throw an error-ish warning when multiple HMR assets are written to the same output file. The message in our context appears as:

`Conflict: Multiple assets emit different content to the same filename 6b8d0b5-wps-hmr.json`

This code block outlines the problem: https://github.com/webpack/webpack/blob/b93048643fe74de2a6931755911da1212df55897/lib/Compilation.js#L2012-L2022

[`webpack-plugin-serve`](https://github.com/shellscape/webpack-plugin-serve) has been utilizing a method to reduce the output noise from HMR asset emissions very successfully for over a year, without negative consequence, and to the benefit of users. While this method is unorthodox, it's still completely valid. The method can be seen [here](https://github.com/shellscape/webpack-plugin-serve/blob/3ca6e830eac93525bbed9142fa76e991caee967b/lib/plugins/hmr.js#L22-L25)

```js
  compiler.options.output = Object.assign(compiler.options.output, {
    hotUpdateChunkFilename: `${compiler.wpsId}-[id]-wps-hmr.js`,
    hotUpdateMainFilename: `${compiler.wpsId}-wps-hmr.json`
  });
```

The `compiler.wpsId` is managed and vetted internally, and is engineered to avoid conflicts, even with multiple concurrent file saves.

This can (and should) be considered a regression bug. Previously, webpack took no action. Neither the commit messages, related pull request (#9687), nor release notes for v4.40.0 outline why this change was made. Since it was not a direct need, and rather likely a tangential addition, it should be considered a regression.

**If the current behavior is a bug, please provide the steps to reproduce.**

This issue https://github.com/shellscape/webpack-plugin-serve/issues/157 outlines the problem and provides a repo and instructions for reproduction.

**What is the expected behavior?**

The expected behavior would be that of webpack prior to version 4.40.0 - which is inaction, allowing manipulation of the HMR filenames without consequence.

Given that the `TODO` in `lib/Compilation.js` indicates that this will be turned into a fatal error in v5, this will essentially cripple our tool without a means to circumvent. I would like to suggest an option that would allow disabling the check that was added, or perhaps a hook that would allow swallowing this error in future versions.

**Other relevant information:**
webpack version:  v4.40.0+
Node.js version: v12.3.1
Operating System: 
Additional tools: MacOS 10.13.2

**Comment by davidroeca** [comment]
Maybe there could be a way to avoid this warning when certain configurations are set? `hmr` and `watch` come to mind.

**Comment by sokra** [comment]
The warning was added to find deeper problems/bugs. Here is what currently happens:

* webpack-plugin-serve set `output.hotUpdateMainFilename` to a constant string value
* html-webpack-plugin compiles the template with a child compiler
* webpack/HotModuleReplacementPlugin attaches to the `compilation` hook and emits a hot update file for each compilation
  * This unfortunately includes the child compilation from the html-webpack-plugin
* webpack/Compilation merges all assets from child compilations to the root compilation, which causes the conflict warning

So there is actually a bug in the HotModuleReplacementPlugin, which should attach to the `thisCompilation` hook instead of `compilation` and only generate hmr update files for the root compilation.

**Comment by shellscape** [comment]
Thank you for addressing this.
