### ISSUE TITLE
SourceMapDevToolPlugin to support a cache option - it's really slow

### ISSUE THREAD

**Issue by nojvek** [webpack/webpack#9721]
## Feature request

**What is the expected behavior?**
SourceMapDevToolPlugin should be really fast for files that haven't changed content.

**What is motivation or use case for adding/changing the behavior?**
The longest time in our build is generating sourcemaps. Uglify has a cache option so it's pretty fast. Sourcemaps not so much.

**How should this be implemented in your opinion?**
Have a cache, and cacheDirectory option like uglify. 

**Are you willing to work on this yourself?**
I can, someone give me a pointer.

**Comment by sokra** [comment]
It has an in memory cache, but no persistent cache. We can plan to do this for webpack 5, where we have a persistent caching API

**Comment by nojvek** [comment]
Awesome. Look forward to persistent cache. Hopefully it’s like the typescript incremental option

**Comment by smelukov** [comment]
@sokra can I try to do it by myself or someone already handling this issue?

**Comment by sokra** [comment]
This might be not directly related to SourceMapDevToolPlugin. The highest cost is to get the SourceMap from the Source object. This object might come from some other step (probably either Chunk Generation or TerserPlugin) and need to be cached there.

**Comment by sokra** [comment]
hmm... Maybe it also works with that.

Here are a few hints how to implement it:

Use the current in-memory caching as base. Since the Cache API does memory caching if persistent caching is disabled, you can replace the current caching with the new one.

The cache API is at `compilation.cache`. Important methods are `get` and `store` (lib/Cache.js for the API).

The current cache uses the input Source object as key. This won't work for the cache API as object identity break when serialized.

Create a cache identifier i. e. from the asset name: `${compilation.compilerPath}/SourceMapDevToolPlugin/${asset.name}`

Create a `etag` from the hash of the input Source: `asset.source.updateHash(hash)` `createHash("md4")` `lib/util/createHash.js`.

Call `compilation.cache.get(cacheIdentifier, etag, ...)`

Call `compilation.cache.store(cacheIdentifier, etag, assets)`.

**Comment by smelukov** [comment]
Seems like we can just don't call `getTaskForFile` if we have a data in our cache for `source + options` etag

**Comment by evilebottnawi** [comment]
@smelukov yep, terser use they keys for cache https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L301

**Comment by smelukov** [comment]
@evilebottnawi 👍
Ok, I'll deal with it :)

**Comment by sokra** [comment]
> I think that `options` are important to cache because it can be changed by webpack executions

You don't need that. Config is captured by buildDependencies, so this is automatically handled by the caching system.

buildDependencies capture the config, all dependencies of the config, webpack and all loaders.
