### ISSUE TITLE
Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by donotlb** [webpack/webpack#9732]
# Bug report

**What is the current behavior?**

webpack shows a warning when rebuild:   
> Multiple assets emit different content to the same filename app.js.map

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
```javascript
const path = require('path')
const webpack = require('webpack')

module.exports = {
  mode: 'development',
  entry: {
    app: './entry.js'
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: '[name].js'
  },
  devtool: false,
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      filename: '[name].js.map'
    }),

    new webpack.HotModuleReplacementPlugin() // !!!!!!! remove this line, the warning will not display
  ]
}
```

entry.js  

```javascript
console.log(`
  modify this module, then webpack shows warning:
  WARNING in Conflict: Multiple assets emit different content to the same filename app.js.map
`)
```

reproduction steps:  

1. use `SourceMapDevToolPlugin` and `HotModuleReplacementPlugin` (refer to webpack.config.js)
2. `npx webpack --watch`
3. modify content of entry.js, then save
4. webpack shows a warning: `Multiple assets emit different content to the same filename app.js.map`

webpack doesn't show this warning if i remove the line `new webpack.HotModuleReplacementPlugin()`

**What is the expected behavior?**

webpack should not show a warning

**Other relevant information:**
webpack version:  4.41.0
Node.js version: v10.15.3
Operating System: win10

**Comment by mvshvets** [comment]
I have the same warning. I am using devServer and webpack.SourceMapDevToolPlugin. The file names are static.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by donotlb** [comment]
@evilebottnawi 

https://github.com/donotlb/webpack-iss-9732

**Comment by evilebottnawi** [comment]
@dolymood WIP

**Comment by evilebottnawi** [comment]
@donotlb Please use `filename: '[file].map[query]'` for `SourceMapDevToolPlugin`, you can't use `[name]` because hmr emit updates for example using `app.3d0af954e7d8c1e90af5.hot-update.js` file and you have two files before source map:
- 3d0af954e7d8c1e90af5.hot-update.json
- app.js - `[name]` is `app`
- app.3d0af954e7d8c1e90af5.hot-update.js - `[name]` is `app`

then you generate source map using `[name].js.map` for second asset and third asset and get two assets with the same name `app.js.map`

**Comment by evilebottnawi** [comment]
The problem is resolved, feel free to feedback, thanks for issue

**Comment by Shelmy-pp** [comment]
Please help to solve this warnings after angular 9 and primeng 9 migration

WARNING in ./src/assets/css/style.css
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(146:3) start value has mixed support, consider using flex-start instead

WARNING in Conflict: Multiple assets emit different content to the same filename loading.gif

WARNING in Conflict: Multiple assets emit different content to the same filename password-meter.png

**Comment by MartinsOnuoha** [comment]
If you're facing this problem with Quasar, be sure to set `gzip` to `false` in `quasar.conf.js` within the `build` object.

**Comment by kerasus** [comment]
> If you're facing this problem with Quasar, be sure to set `gzip` to `false` in `quasar.conf.js` within the `build` object.

in quasar i need `gzip: true`
so this work for me:

in quasar.conf.js

`    chainWebpack (chain) {
      const hashh = '[id].[name].[chunkhash]'
      chain.output.filename('js/[name]/'+hashh+'.bundle.js')
      chain.output.chunkFilename('js/[name]/'+hashh+'.chunk.js')
      chain.plugin('eslint-webpack-plugin')
        .use(ESLintPlugin, [{ extensions: [ 'js', 'vue' ] }])
    },
`

**Comment by Grawl** [comment]
For me using Quasar v1 this problem caused because I placed different images with same name in different folders, and then I import them.

Files tree:

```
- foo
	- index.ts
	- assets
		-  image.png
 - bar
	- index.ts
	- assets
		-  image.png
```

`foo/index.ts`:

```ts
import image from './assets/image.png`
```

`bar/index.ts`:

```ts
import image from './assets/image.png`
```

And then I get error in build console when I run `quasar dev`:

```
Error: Conflict: Multiple assets emit different content to the same filename img/image.png
```

But I do not get this error when I run `quasar build`.

It's because Webpack config in Quasar uses image hash only on `build` mode, not `dev`.

When I look into this image in browser, it's `/img/image.png` for both images from both folders. But I don't want to name images differently since they in different folders already, and I cannot guarantee that every image in my project have unique name.

So I added this to `quasar.conf.js`:

```js
chainWebpack(chain) {
	chain.module.rule('images')
		.use('url-loader')
		.loader('url-loader')
		.options({ esModule: false, limit: 0, name: 'img/[hash].[ext]' })
},
```

Now every image has hash in filename.

**Comment by Haixing-Hu** [comment]
> 

@Grawl you saved me a lot of time 👏🏻

**Comment by khelkun** [comment]
@alexander-akait 
Sorry to bother you but I don't understand what's going on here. I had this simple config in a webpack 3 project:
```
const path = require('path')
const webpack = require('webpack')

module.exports = {
  mode: 'development',
  entry: {
    app: './entry.js'
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: '[name].js',
    sourceMapFilename: '[name].js.map'
  },
  devtool: 'source-map'
}
```

After upgrading to webpack 5, I encountered the error mentionned in this issue:

> Multiple assets emit different content to the same filename app.js.map

Commenting `sourceMapFilename` config solves the issue. The `app.3d0af954e7d8c1e90af5.hot-update.js` was not existing in webpack 3?

**Comment by alexander-akait** [comment]
Do you update webpack-dev-server, and why don't use the default `'[file].map[query]'` value for `sourceMapFilename`? Try to add `[query]`

**Comment by mlisowsk** [comment]
@alexander-akait Hi Alexander, I think it would be helpful if the documentation at https://webpack.js.org/plugins/source-map-dev-tool-plugin/ could be updated to remind users of using correct `sourceMapFilename`. 

Specifically the examples there use `'[name].js.map'` which is likely why so many people make this mistake. (The example may work due to its simplicity, but you know our first attempt is copy & paste the example ;-) )

**Comment by alexander-akait** [comment]
:+1:
