### ISSUE TITLE
在使用svg时，我用electron-vue集成现有vue-cli3项目， sv图标显示不出来

### ISSUE THREAD

**Issue by websmallrabbit** [webpack/webpack#9814]
```
import Vue from 'vue'
import SvgIcon from '@/components/SvgIcon'// svg component

// register globally
Vue.component('svg-icon', SvgIcon)

const req = require.context('./svg', false, /\.svg$/)
// const requireAll = requireContext => requireContext.keys().map(requireContext)

const requireAll = requireContext => requireContext.keys().map((key) => {
  console.log(key, req)
})
requireAll(req)
```

![image](https://user-images.githubusercontent.com/34472552/66709578-cc026900-ed99-11e9-8b24-f9341d4ff172.png)

现在项目能出来图片的是这样的
![image](https://user-images.githubusercontent.com/34472552/66709590-010ebb80-ed9a-11e9-8020-b0b11faabfb6.png)

我当前项目是vue-cli3
网上有人说electron-vue不支持vue-cli3， 我认为应该是webpack配置的问题，大神应该怎么解决

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.

**Comment by terranc** [comment]
想问electron打包之后require.context能正常使用？
