### ISSUE TITLE
how can i ignore compile error

### ISSUE THREAD

**Issue by zhangyuang** [webpack/webpack#9823]
![image](https://user-images.githubusercontent.com/17424434/66794819-57fcc800-ef35-11e9-89b7-d504460cc93b.png)
when the code running, it will never run this code in catch, but when compiling, it prompt error，how can i fix it?

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
