### ISSUE TITLE
How to make dependencies support IE11

### ISSUE THREAD

**Issue by lxfu** [webpack/webpack#9920]
Project address: [react-g6](https://github.com/lxfu/react-g6)
The project relying on @antv/g6, not surport with IE11, i need how do I configure rules?
My current configuration is as follows。
rules: [
      {
        test: /\.js$/,
        include: [path.resolve("src"), path.resolve("node_modules/@antv/g6")],
        use: "babel-loader"
      }
    ]

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
