### ISSUE TITLE
IIFE file loading

### ISSUE THREAD

**Issue by frontend14** [webpack/webpack#9998]
I am using webpack 4.38 version. 

We have a depency file in IIFE . When I try to add it as entry point , file is not self executed. 
Kindly help me 
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.38 
Node.js version: 6.7
Operating System: Mac OS
Additional tools:

**Comment by evilebottnawi** [comment]
Please clarify what do you mean

**Comment by frontend14** [comment]
I have a file in IIFE format (Immediately Invoked Function Expression) . I cannot import it . So I tried to add it as an entry file. Now the problem is as the file is enclosed in webpack functions, its not getting self executed . Hence I face issue in it.

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template. Also make sure your issue is not a question. Questions should be posted on Stack Overflow.
